export const CRISIS_AUTOPILOT_TRIGGER_TYPES = Object.freeze([
  'NEW_THERMAL_DETECTION',
  'NEW_OFFICIAL_REPORT',
  'NEW_FIELD_REPORT',
  'NEW_CAUSAL_SOURCE_FAMILY',
  'WEATHER_CHANGED',
  'GEOMETRY_CHANGED',
  'PRIORITY_CHANGED',
  'SOURCE_CONFLICT',
  'ROAD_CLOSURE',
  'RESOURCE_ACKNOWLEDGED',
  'PROVIDER_FAILURE',
  'PROTECTION_THRESHOLD_REACHED',
  'FIELD_OBSERVATION',
]);

export const CRISIS_AUTOPILOT_ACTIONS_BY_TRIGGER = Object.freeze({
  NEW_THERMAL_DETECTION: Object.freeze(['RECOMPUTE_INCIDENT_TRUTH', 'RANK_NEXT_COLLECTION']),
  NEW_OFFICIAL_REPORT: Object.freeze(['RECOMPUTE_INCIDENT_TRUTH', 'RECOMPUTE_PRIORITY']),
  NEW_FIELD_REPORT: Object.freeze(['RECOMPUTE_INCIDENT_TRUTH', 'RECOMPUTE_DECISIONS']),
  NEW_CAUSAL_SOURCE_FAMILY: Object.freeze(['RECOMPUTE_INCIDENT_TRUTH', 'RECOMPUTE_PRIORITY', 'RECOMPUTE_DECISIONS']),
  WEATHER_CHANGED: Object.freeze(['RECOMPUTE_WATCH_CONDITIONS', 'RECOMPUTE_EXPOSURE', 'RECOMPUTE_DECISIONS']),
  GEOMETRY_CHANGED: Object.freeze(['RECOMPUTE_EXPOSURE', 'RECOMPUTE_PRIORITY', 'REPLAN_OPERATIONS']),
  PRIORITY_CHANGED: Object.freeze(['RECOMPUTE_DECISIONS', 'REPLAN_OPERATIONS']),
  SOURCE_CONFLICT: Object.freeze(['RANK_CONFLICT_RESOLUTION_COLLECTION', 'RECOMPUTE_DECISIONS']),
  ROAD_CLOSURE: Object.freeze(['RECOMPUTE_RESPONSE_REACHABILITY', 'REPLAN_OPERATIONS']),
  RESOURCE_ACKNOWLEDGED: Object.freeze(['RECOMPUTE_RESOURCE_PLAN']),
  PROVIDER_FAILURE: Object.freeze(['RANK_ALTERNATIVE_SOURCE', 'RECOMPUTE_WATCH_CONDITIONS']),
  PROTECTION_THRESHOLD_REACHED: Object.freeze(['PREPARE_PROTECTION_ACTION_FOR_AUTHORITY_REVIEW']),
  FIELD_OBSERVATION: Object.freeze(['RECOMPUTE_INCIDENT_TRUTH', 'RECOMPUTE_DECISIONS']),
});

export const UNCERTAINTY_STATES = Object.freeze([
  'KNOWN',
  'UNKNOWN',
  'UNKNOWN_BUT_ACCEPTABLE',
  'UNKNOWN_BLOCKING_ACTION',
  'UNKNOWN_BEING_COLLECTED',
  'UNKNOWN_CURRENTLY_UNOBTAINABLE',
]);

export const REGRET_STATES = Object.freeze(['ACT_NOW', 'PREPARE_NOW', 'WATCH', 'DEFER']);

export const COMMAND_STAFF_ROLES = Object.freeze([
  'INTELLIGENCE_OFFICER',
  'OPERATIONS_OFFICER',
  'PLANNING_OFFICER',
  'LOGISTICS_OFFICER',
  'SAFETY_OFFICER',
  'PROTECTION_OFFICER',
  'PUBLIC_INFORMATION_OFFICER',
  'RED_TEAM',
]);

export {
  ACTIVE_WORK_STATES,
  BLOCKED_COLLECTION_WORK_STATES,
  CLOSED_WORK_STATES,
  SCHEDULE_BOUND_WORK_STATES,
  UNOBTAINABLE_STATES,
  collectionWorkLifecycle,
  incidentBinding,
  isActiveWork,
  isClosedWork,
  isGovernedCollectionWork,
  isUnobtainable,
  objectId,
  requiredIncidentId,
  requiredProjectionClock,
  stateOf,
  terminalReason,
  validInstant,
  workLastCheck,
  workNextCheck,
  workOwner,
  workSource,
} from './work-lifecycle.mjs';
