import { createHash } from 'node:crypto';
import { bboxCovers, observationSuitability, sceneAgeHours } from '../../../../../packages/domain/src/observation-integrity.mjs';
import { ProductionIntegrityViolation } from '../../../../../packages/domain/src/production-integrity.mjs';

export function opticalScenes(region=null){const scenes=region?.scenes?.length?region.scenes:[region?.latest,region?.previous].filter(Boolean);return scenes.map((scene)=>{if(scene.fixture||scene.provenance?.synthetic===true)throw new ProductionIntegrityViolation('Synthetic catalogue scene rejected by production.',{sceneId:scene.id??null});return{...scene,sensor:scene.sensor??'Sentinel-2',resolutionMeters:scene.resolutionMeters??10,source:scene.source??'Copernicus Data Space Ecosystem',kind:'optical'};});}
function localBinding(scene,coordinate){const coversSelection=!Array.isArray(scene.bbox)||bboxCovers(scene.bbox,coordinate),proof={mode:'catalog_only',sceneId:scene.id,coordinate,bbox:scene.bbox??null,coversSelection},bindingHash=createHash('sha256').update(JSON.stringify(proof)).digest('hex');return{state:coversSelection?'catalog_only':'rejected',renderAllowed:false,scientificInferenceAllowed:false,pixelVerified:false,scienceBandsVerified:false,reason:coversSelection?'Catalogue footprint contains the coordinate, but raster pixel binding has not been proven.':'Catalogue footprint rejects the selected coordinate.',bindingHash,proof};}
function result(scene,{coordinate,currentImageryService,clock},binding){const imageUrl=scene.previewUrl?currentImageryService.proxyUrl(scene.previewUrl):null,suitability=observationSuitability(scene,clock()),catalogCoversSelection=!Array.isArray(scene.bbox)||bboxCovers(scene.bbox,coordinate);return{...scene,imageUrl,renderState:binding.renderAllowed&&(scene.visualCogUrl||imageUrl)?'renderable':'metadata_only',coversSelection:catalogCoversSelection,catalogCoversSelection,ageHours:sceneAgeHours(scene.acquiredAt,clock()),suitability,evidenceBinding:{state:binding.state,bindingHash:binding.bindingHash,renderAllowed:binding.renderAllowed,scientificInferenceAllowed:binding.scientificInferenceAllowed,pixelVerified:binding.pixelVerified,scienceBandsVerified:binding.scienceBandsVerified,catalogCoversSelection,reason:binding.reason,proof:binding.proof}};}
export function decorateScene(scene,{coordinate,currentImageryService,geoIntegrityService,clock,scienceRequired=false}){if(!scene)return null;if(scene.fixture||scene.provenance?.synthetic===true)throw new ProductionIntegrityViolation('Synthetic scene rejected by production.',{sceneId:scene.id??null});if(!geoIntegrityService)return result(scene,{coordinate,currentImageryService,clock},localBinding(scene,coordinate));return geoIntegrityService.verifyScene(scene,coordinate,{scienceRequired}).then((binding)=>result(scene,{coordinate,currentImageryService,clock},binding));}
export function selectionReason(primary,scenes,now=new Date()){if(!primary)return{selected:[],rejected:scenes.map((scene)=>({id:scene.id,reason:'No defensible current observation'}))};const selected=[],suitability=observationSuitability(primary,now);if(suitability.ageHours!==null)selected.push(`${Math.round(suitability.ageHours)} h old`);if(primary.sensor==='Sentinel-1')selected.push('all-weather radar available');else if(suitability.cloudCover!==null)selected.push(`${Math.round(suitability.cloudCover)}% cloud cover`);if(primary.resolutionMeters)selected.push(`${primary.resolutionMeters} m nominal resolution`);const rejected=scenes.filter((scene)=>scene.id!==primary.id).slice(0,5).map((scene)=>{const quality=observationSuitability(scene,now),reason=!quality.cloudSuitable?'cloud cover above optical threshold':quality.ageHours!==null&&quality.ageHours>72?'older observation':scene.sensor!==primary.sensor?'lower-ranked sensor for this decision':'less suitable comparison';return{id:scene.id,sensor:scene.sensor,acquiredAt:scene.acquiredAt,reason};});return{selected,rejected};}
