import { shell } from './components.js?v=2.1.0';
import { unselectedIntelligence, unselectedOperations } from './unselectedReferenceRoutes.js';

const bars=count=>`<div class="vigia-boot-rows">${Array.from({length:count},(_,index)=>`<span style="--boot-row:${index}"></span>`).join('')}</div>`;
const panel=(className,title,body='')=>`<section class="${className} panel-surface vigia-boot-panel"><header><div><h2>${title}</h2><p>Connecting to incident services</p></div></header>${body||bars(5)}</section>`;
const map=className=>`<div class="${className}"><div class="vigia-boot-map" role="status" aria-label="Connecting map"><span>Connecting map</span></div></div>`;

export function renderBootRoute(route,state){
  const visible=state?.runtime?.showSkeleton===true?' is-visible':'',wrap=body=>shell(route,`<section class="vigia-boot-route${visible}" aria-hidden="true">${body}</section>`,{pageClass:'final-white-route-page'});
  // Loading keeps the same route geometry; it never announces missing data as zero.
  const connecting=html=>html.replace(/>([^<]+)</g,(_,text)=>`>${text.replaceAll('Unavailable','Connecting').replaceAll('unavailable','connecting').replaceAll('No incident context available','Connecting incident context').replaceAll('No retained scene is available for this incident.','Waiting for the incident map.')}<`).replace(/data-action="[^"]*"/g,'').replace(/<button(?! disabled)/g,'<button disabled');
  if(route==='intelligence')return wrap(connecting(unselectedIntelligence()));
  if(route==='operations')return wrap(connecting(unselectedOperations()));
  if(route==='reports-analytics')return wrap(`<section class="reports-route"><section class="report-controls panel-surface">${bars(1)}${bars(1)}${bars(1)}${bars(1)}</section><section class="reports-leadership-strip reports-leadership-strip--reference"><dl>${['Leadership decisions','Measured outcomes','Verified current incidents','Near misses','Prevention opportunities','Last evaluation'].map(label=>`<div><dt>${label}</dt><dd>Connecting</dd></div>`).join('')}</dl></section><section class="report-tabs panel-surface">Decision Summary · Outcome Analysis · System Performance · Situation Quality</section><div class="report-reference-summary"><div class="report-reference-core"><div class="report-reference-charts">${panel('report-reference-panel','State transitions over time',bars(4))}${panel('report-reference-panel','Why operators intervened',bars(4))}</div><div class="report-reference-trends">${['Resolution performance','False alarm rate','Decision latency'].map(label=>panel('',label,bars(1))).join('')}</div>${panel('report-reference-panel','Human decisions by category',bars(4))}</div><aside class="report-reference-rail">${panel('report-reference-panel','Key insights',bars(4))}${panel('report-reference-panel','Latest decision-ready changes',bars(4))}</aside></div></section>`);
  if(route==='command-overview')return wrap(`<section class="overview-metrics">${Array.from({length:4},()=>'<article class="overview-metric vigia-boot-metric"></article>').join('')}</section><div class="overview-primary">${panel('situation-map','Situation Map',map('situation-map__canvas'))}${panel('priority-rail','Priority Items')}</div>${panel('system-health','System Health',bars(6))}`);
  if(route==='incidents')return wrap(`<div class="incidents-toolbar panel-surface">${bars(1)}${bars(1)}${bars(1)}${bars(1)}</div><div class="incidents-layout">${panel('incident-inventory','Incident inventory',bars(7))}<aside class="incidents-side">${panel('incidents-map','Incident Summary',map('incidents-map__canvas'))}${panel('incident-changes','Latest changes',bars(4))}</aside></div>`);
  if(route==='incident-detail')return wrap(`<div class="incident-detail-workspace"><div class="incident-detail-left">${panel('selected-incident-card','Selected incident',bars(3))}<div class="incident-detail-left-body">${panel('incident-local-nav','Incident sections',bars(6))}${panel('incident-assessment','Current assessment',bars(5))}</div></div>${panel('incident-detail-map','Current operating picture',map('incident-detail-map__canvas'))}</div>${panel('decision-delta','Latest decision delta',bars(4))}`);
  return wrap(`${panel('global-filters','Global filters',bars(1))}<div class="global-workspace">${panel('global-map','Global situational view',map('global-map__canvas'))}<aside class="global-rail">${panel('global-rail-card','Regional Summary',bars(5))}${panel('global-rail-card','Source Health Overview',bars(4))}</aside></div>`);
}
