import { esc, badge } from './components.js?v=2.1.0';
import { icon } from './icons.js?v=2.1.0';
import { tileMap } from './map.js?v=3.0.0';
import { display, incidentCoordinate, incidentId, incidentLabel, operatorText, section, timeLabel } from './canonicalViewModel.js?v=2.1.0';
import { finiteNumberOrNull } from './truth.js?v=2.1.0';
import { vigiaStateLabel } from './operatorPrimitives.js?v=3.2.0';

const toneForState=input=>{const state=String(input??'').toUpperCase();if(/VERIFIED|READY|ACTIVE|HEALTHY|COMPLETED|SATISFIED|OPERATIONAL|CONTAINED|MONITORING/.test(state))return'green';if(/BLOCK|FAILED|REVOKED|CRITICAL|CONTRADICT/.test(state))return'critical';if(/DEGRADED|WAIT|UNKNOWN|UNAVAILABLE|INSUFFICIENT|OPEN|STALE|EVIDENCE|VALIDATION|PENDING/.test(state))return'warning';return'teal';};

export function routeTabs(items,active,action){return `<div class="phase-b-tabs" role="tablist">${items.map(([id,label])=>`<button role="tab" aria-selected="${active===id}" class="${active===id?'is-active':''}" data-action="${esc(action)}:${esc(id)}">${esc(label)}</button>`).join('')}</div>`;}
export function operationalStatement(title,body='',meta=''){return `<section class="operational-statement"><span>Operational statement</span><h2>${esc(title)}</h2>${body?`<p>${esc(body)}</p>`:''}${meta?`<small>${esc(meta)}</small>`:''}</section>`;}
export function unavailableValue(label='Unavailable',reason='canonical_projection_not_available'){return `<span class="unavailable-value"><strong>${esc(label)}</strong><small>${esc(operatorText(reason))}</small></span>`;}
export function emptyTruthState(title,body,action=''){return `<div class="empty-truth-state" role="status">${icon('evidence',22)}<strong>${esc(title)}</strong><p>${esc(body)}</p>${action?`<button class="button button--ghost" data-action="${esc(action)}">Retry</button>`:''}</div>`;}
export function technicalDisclosure(label='Technical details',rows=[]){const items=rows.filter(([,value])=>value!==null&&value!==undefined&&value!=='');return `<details class="technical-details"><summary>${esc(label)}</summary><dl>${items.map(([name,value])=>`<div><dt>${esc(name)}</dt><dd>${esc(String(value))}</dd></div>`).join('')}</dl></details>`;}
export function sectionState(source,key,{label=key,compact=false}={}){const item=section(source,key),stateLabel=operatorText(item.state);return `<div class="section-state ${compact?'section-state--compact':''}">${vigiaStateLabel(item.state,{label:stateLabel,compact})}<small>${esc(label)}</small>${technicalDisclosure('Details',[['Canonical state',item.state],['Projection authority',item.authority??'BACKEND_CANONICAL'],['Reason',item.reason]])}</div>`;}
export function truthCell(label,value,{meta='',tone='teal'}={}){return `<article class="truth-cell truth-cell--${tone}"><span>${esc(label)}</span><strong>${esc(display(value))}</strong>${meta?`<small>${esc(meta)}</small>`:''}</article>`;}
export function itemRows(items,{emptyTitle='No records returned',emptyBody='The backend returned no items for this surface.',render}={}){return items.length?items.map(render).join(''):emptyTruthState(emptyTitle,emptyBody);}
export function labelValue(label,value,{meta='',tone=''}={}){return `<div class="label-value ${tone?`label-value--${tone}`:''}"><span>${esc(label)}</span><strong>${esc(display(value))}</strong>${meta?`<small>${esc(meta)}</small>`:''}</div>`;}
export function humanState(input){return vigiaStateLabel(input);}
const mapLayerRows=(scene,name)=>{const layer=scene?.layers?.[name];return ['READY','DEGRADED'].includes(layer?.state)&&Array.isArray(layer.value)?layer.value:[];};
const mapCoordinate=value=>Array.isArray(value)&&value.length===2&&value.every(Number.isFinite)?value:null;
const mapBoundsCenter=value=>{const bounds=Array.isArray(value)?value:[value?.west,value?.south,value?.east,value?.north];return bounds.length===4&&bounds.every(Number.isFinite)&&bounds[0]<bounds[2]&&bounds[1]<bounds[3]?[(bounds[0]+bounds[2])/2,(bounds[1]+bounds[3])/2]:null;};

const sceneDefinitions=Object.freeze({
  COMMAND:{sceneType:'COMMAND_SITUATION',zoom:7,layers:['incidentPoints','observations','thermalSupport','wind','weather'],controls:['layers','focus','thermal','zoom'],labelPolicy:'PRIORITY_INCIDENTS'},
  INCIDENTS:{sceneType:'INCIDENT_INSPECTION',zoom:10,layers:['incidentPoints','observedGeometry','thermalSupport','observations','weather','wind','contextAssets'],controls:['layers','focus','thermal','zoom'],labelPolicy:'SELECTED_WITH_NEARBY_CONTEXT'},
  INTELLIGENCE:{sceneType:'INTELLIGENCE_FORECAST',zoom:11,layers:['incidentPoints','observedGeometry','thermalSupport','observations','weather','wind','terrain','forecastGeometry','contextAssets','responseCoverageSurface','responseCoverageRoutes','responseFacilities'],controls:['layers','focus','thermal','zoom'],labelPolicy:'SCIENTIFIC_FEATURES'},
  OPERATIONS:{sceneType:'OPERATIONS_ASSIGNMENTS',zoom:9,layers:['incidentPoints','operationalAreas','controlLines','divisions','stagingAreas','bases','resources','assignments','locations','stagedResources','responseCoverageSurface','responseCoverageRoutes','responseFacilities'],controls:['layers','focus','thermal','resources','zoom'],labelPolicy:'ASSIGNMENTS_AND_RESOURCES'},
  INCIDENT_DETAIL:{sceneType:'INCIDENT_TACTICAL',zoom:12,layers:['incidentPoints','observedGeometry','thermalSupport','observations','weather','wind','controlLines','divisions','stagingAreas','bases','resources','locations','roads','contextAssets','responseCoverageSurface','responseCoverageRoutes','responseFacilities'],controls:['layers','focus','thermal','zoom'],labelPolicy:'TACTICAL_FEATURES'},
  GLOBAL:{sceneType:'GLOBAL_AWARENESS',zoom:4,layers:['incidentPoints','observations','weather'],controls:['layers','zoom'],labelPolicy:'GLOBAL_CLUSTER_HIERARCHY'},
});
const availableSceneLayers=(scene,names)=>names.filter(name=>{const layer=scene?.layers?.[name];return ['READY','DEGRADED'].includes(layer?.state)&&(Array.isArray(layer.value)?layer.value.length>0:layer.value!==null);});
const sceneClass=input=>String(input??'UNSCOPED').toLowerCase().replaceAll('_','-');

export function canonicalMap({state,incidents=[],selected=null,zoom=5,thermal=false,label='Incident map',className='',commandProjection=null,mapScene=null,scope=null,vqa='',legendMarkup=null}){
  const mapProjection=commandProjection?.map??null;
  const resolvedScope=String(scope??mapScene?.scope??(commandProjection?'COMMAND':'INCIDENT_DETAIL')).toUpperCase(),fallback=sceneDefinitions[resolvedScope]??sceneDefinitions.INCIDENT_DETAIL;
  const projectedIncidents=Array.isArray(commandProjection?.priorityIncidents)?commandProjection.priorityIncidents:[];
  const sceneIncidents=mapLayerRows(mapScene,'incidentPoints');
  const projectedById=new Map(projectedIncidents.map(row=>[String(row?.incidentId??''),row])),canonicalRows=incidents.map(row=>({incidentId:incidentId(row),name:incidentLabel(row),coordinate:incidentCoordinate(row),state:row?.incident?.lifecycleState??row?.incident?.status??row?.incident?.state??row?.evaluation?.state??row?.state}));
  let mapRows=sceneIncidents.length?sceneIncidents.map(row=>({...projectedById.get(String(row?.incidentId??'')),...row})):projectedIncidents.length?[...projectedIncidents]:canonicalRows;
  if(['GLOBAL','INCIDENTS'].includes(resolvedScope)){const filteredIds=new Set(canonicalRows.map(row=>row.incidentId).filter(Boolean));mapRows=mapRows.filter(row=>filteredIds.has(String(row?.incidentId??'')));}
  const selectableIds=new Set([...mapRows,...canonicalRows].map(row=>String(row?.incidentId??'')).filter(Boolean)),stateSelectedId=String(resolvedScope==='GLOBAL'?state?.globalSelectedIncidentId??'':state?.selectedIncidentId??''),componentSelectedId=incidentId(selected);
  const selectedId=String(stateSelectedId&&selectableIds.has(stateSelectedId)?stateSelectedId:componentSelectedId&&selectableIds.has(componentSelectedId)?componentSelectedId:commandProjection?.focusedIncidentId??mapScene?.selectedIncidentId??mapScene?.focusIncidentId??'');
  const selectedCanonical=canonicalRows.find(row=>row.incidentId===selectedId);if(selectedCanonical?.coordinate&&!mapRows.some(row=>String(row?.incidentId??'')===selectedId))mapRows.push(selectedCanonical);
  const backendLayers=Array.isArray(mapScene?.layerSet)?mapScene.layerSet.filter(name=>typeof name==='string'&&name):null,backendControls=Array.isArray(mapScene?.controls)?mapScene.controls.filter(name=>typeof name==='string'&&name):null,definition={sceneType:typeof mapScene?.sceneType==='string'&&mapScene.sceneType?mapScene.sceneType:fallback.sceneType,zoom:finiteNumberOrNull(mapScene?.camera?.zoom)??fallback.zoom,layers:backendLayers??fallback.layers,controls:backendControls??fallback.controls,labelPolicy:typeof mapScene?.labelPolicy==='string'&&mapScene.labelPolicy?mapScene.labelPolicy:fallback.labelPolicy},sceneType=definition.sceneType,sceneIdentity=typeof mapScene?.sceneId==='string'&&mapScene.sceneId?mapScene.sceneId:`${sceneType}:${resolvedScope==='COMMAND'?'regional':selectedId||'unselected'}`;
  const storedCamera=state?.mapSceneCameras?.[sceneIdentity]??{},storedAssociationMatches=!selectedId||String(storedCamera.selectedIncidentId??'')===selectedId,storedZoom=storedAssociationMatches?finiteNumberOrNull(storedCamera.zoom):null,storedCenter=storedAssociationMatches?mapCoordinate(storedCamera.center):null;
  const selectedCoordinate=mapRows.find(row=>String(row?.incidentId??'')===selectedId)?.coordinate??incidentCoordinate(selected);
  const firstCoordinate=mapRows.map(row=>row?.coordinate).find(item=>Array.isArray(item)&&item.length===2)??incidents.map(incidentCoordinate).find(Boolean);
  const projectedCenter=mapCoordinate(mapScene?.camera?.center)??mapCoordinate(mapProjection?.center),selectedMapCoordinate=mapCoordinate(selectedCoordinate),globalSelectionCenter=resolvedScope==='GLOBAL'&&stateSelectedId?selectedMapCoordinate:null;
  const coordinate=globalSelectionCenter??storedCenter??projectedCenter??selectedMapCoordinate??mapBoundsCenter(mapScene?.bounds??mapScene?.camera?.bbox)??mapCoordinate(firstCoordinate),resolvedZoom=globalSelectionCenter?Math.max(storedZoom??definition.zoom??zoom,7):storedZoom??definition.zoom??finiteNumberOrNull(mapProjection?.zoom)??zoom,resolvedThermal=definition.controls.includes('thermal')?(typeof storedCamera.thermal==='boolean'?storedCamera.thermal:thermal):false,fitBackendBounds=globalSelectionCenter===null&&storedZoom===null&&storedCenter===null;
  const layerVisibility=state?.mapLayerVisibility?.[sceneIdentity]??{},availableLayers=availableSceneLayers(mapScene,definition.layers),visibleLayers=availableLayers.filter(name=>layerVisibility[name]!==false),showBasemapLabels=layerVisibility.basemapLabels!==false;
  const focusedLayer=state?.mapFocusedLayer?.[sceneIdentity]??null;
  const incidentMarkers=mapRows.map((row,index)=>{
    const identifier=String(row?.incidentId??incidentId(row)??''),coordinateValue=row?.coordinate??incidentCoordinate(row),stateValue=String(row?.state??'').toUpperCase(),area=finiteNumberOrNull(row?.areaHa);
    const selectedMarker=identifier===selectedId,name=row?.name??row?.label??incidentLabel(row);
    const observedAt=row?.updatedAt??row?.observedAt??null,observationLabel=observedAt?`observed ${timeLabel(observedAt)}`:area===null?'Observation time unavailable':`${area.toLocaleString('en-US')} ha`;
    const semanticTone=stateValue==='VERIFIED_CURRENT'?'critical':stateValue==='DETECTION_CANDIDATE'?'warning':stateValue==='NEEDS_REVALIDATION'?'info':stateValue==='HISTORICAL_CLOSED'?'green':stateValue==='ACTIVE'?'critical':stateValue==='CONTAINED'?'green':stateValue==='MONITORING'?'info':selectedMarker?'critical':'warning';
    return{identifier,kind:'incident',classification:stateValue,coordinate:coordinateValue,label:name,short:name,meta:observationLabel,status:mapScene?.fieldPresentation&&stateValue==='NEEDS_REVALIDATION'?'Earlier report':operatorText(stateValue),selected:selectedMarker,showLabel:resolvedScope==='GLOBAL'?selectedMarker&&resolvedZoom>=7:selectedMarker||(resolvedScope==='COMMAND'&&index<5),tone:semanticTone,iconName:stateValue==='MONITORING'?'droplet':stateValue==='HISTORICAL_CLOSED'||stateValue==='CONTAINED'?'warning':'flame',action:identifier?`inspect-incident:${identifier}`:'',openAction:identifier?`open-incident-workspace:${identifier}`:''};
  }).filter(item=>Array.isArray(item.coordinate));
  const resourceMarkers=visibleLayers.includes('resources')?mapLayerRows(mapScene,'resources').filter(row=>mapCoordinate(row?.coordinate)).map((row,index)=>({identifier:row.resourceId??`resource:${index}`,kind:'resource',coordinate:row.coordinate,label:row.label??row.resourceId??'Resource',short:row.label??row.resourceId??'',meta:row.assignmentId?`Assignment ${row.assignmentId}`:'No assignment linked',status:operatorText(row.state??''),showLabel:resolvedScope==='OPERATIONS'&&index<3,tone:String(row.state??'').toUpperCase()==='STAGED'?'warning':'info',iconName:'people',action:row.resourceId?`inspect-map-feature:resource:${row.resourceId}`:''})):[];
  const observationMarkers=visibleLayers.includes('observations')?mapLayerRows(mapScene,'observations').filter(row=>mapCoordinate(row?.coordinate)).map((row,index)=>{const id=String(row.id??`observation:${index+1}`),source=operatorText(row.platform??row.instrument??row.source??row.sourceFamily,{missing:'Thermal observation'}),frp=finiteNumberOrNull(row.frpMw),uncertainty=finiteNumberOrNull(row.geolocationUncertaintyM),facts=[frp===null?null:`FRP ${frp.toLocaleString('en-US')} MW`,uncertainty===null?null:`±${uncertainty.toLocaleString('en-US')} m`].filter(Boolean).join(' · ');return{identifier:id,kind:'observation',coordinate:row.coordinate,label:`${source}${facts?` · ${facts}`:''}`,short:source,meta:facts,status:row.observedAt?timeLabel(row.observedAt):'Acquisition time unavailable',showLabel:false,tone:'critical',iconName:'detect',action:`inspect-map-feature:observation:${id}`};}):[];
  const assetMarkers=visibleLayers.includes('contextAssets')?mapLayerRows(mapScene,'contextAssets').filter(row=>mapCoordinate(row?.coordinate)).map((row,index)=>({identifier:row.id??`asset:${index+1}`,kind:'asset',coordinate:row.coordinate,label:row.label??row.kind??'Mapped context asset',short:row.label??row.kind??'Mapped asset',meta:'Mapped context · not physical evidence',showLabel:false,tone:'info',iconName:'map',action:`inspect-map-feature:asset:${row.id??index+1}`})):[];
  const responseFacilityMarkers=visibleLayers.includes('responseFacilities')?mapLayerRows(mapScene,'responseFacilities').map((row,index)=>{const properties=row?.properties??row,coordinateValue=mapCoordinate(row?.geometry?.coordinates??row?.coordinate),availability=String(properties.capacityAvailability??'UNKNOWN');return coordinateValue?{identifier:properties.facilityId??row.id??`response-facility:${index+1}`,kind:'resource',coordinate:coordinateValue,label:properties.label??operatorText(properties.facilityKind),short:properties.label??operatorText(properties.facilityKind),meta:mapScene?.fieldPresentation?operatorText(properties.facilityKind):`${operatorText(properties.facilityKind)} · ${operatorText(availability)}`,status:mapScene?.fieldPresentation?'Mapped location':operatorText(properties.capacityState??properties.routeState??'UNKNOWN'),showLabel:false,tone:properties.presentation?.showCapacity!==true?'info':availability==='CONFIRMED_AVAILABLE'?'green':availability==='CONFIRMED_NO_AVAILABLE_CAPACITY'?'critical':'warning',iconName:({hospital:'plus',health_center:'plus',fire_station:'flame',police_station:'prevent',public_prosecutor:'evidence',civil_protection:'prevent',water_point:'droplet'}[properties.canonicalType]??'overview'),action:`inspect-map-feature:response-facility:${properties.canonicalId??properties.facilityId??row.id??index+1}`}:null;}).filter(Boolean):[];
  const markers=[...incidentMarkers,...resourceMarkers,...observationMarkers,...assetMarkers,...responseFacilityMarkers];
  // A transient session refresh failure must not destroy an already admitted,
  // last-good geospatial renderer. Projection admission happens before this
  // component receives mapScene; mutation readiness remains governed by the
  // live session contract, while tile/source failures report through the map's
  // own degraded states.
  const enabled=state?.runtime?.status!=='error'&&coordinate!==null;
  const commandChrome=Boolean(commandProjection);
  const sceneWind=mapLayerRows(mapScene,'wind')[0]??null;
  const presentation=mapProjection||mapScene?{...(mapProjection??{}),wind:Object.hasOwn(mapScene??{},'windReading')?(mapScene.windReading?.available?{...mapScene.windReading,realWorldValue:true}:null):mapProjection?.wind??sceneWind,incidents:mapRows,focusId:selectedId,mapScene}:null;
  const vqaAttribute=vqa?` data-vqa="${esc(vqa)}"`:'';
  const controlsVqa=vqa?` data-vqa="${esc(vqa)}.controls"`:'';
  const controlButton=name=>({layers:`<button class="icon-button" data-action="map-layers" aria-label="Open ${esc(sceneType)} layers">${icon('layers',18)}</button>`,focus:`<button class="icon-button" data-action="map-focus" aria-label="Center selected incident">${icon('detect',18)}</button>`,thermal:`<button class="icon-button ${resolvedThermal?'is-active':''}" data-action="map-toggle-thermal" aria-label="Toggle governed thermal layer" aria-pressed="${resolvedThermal?'true':'false'}">${icon('flame',18)}</button>`,resources:`<button class="icon-button" data-action="map-layers" aria-label="Open operational resources and assignments">${icon('people',18)}</button>`,zoom:`<button class="icon-button" data-action="map-zoom-in" aria-label="Zoom in">${icon('plus',18)}</button><button class="icon-button" data-action="map-zoom-out" aria-label="Zoom out">${icon('minus',18)}</button>`}[name]??''),toolNames=definition.controls.filter(name=>name!=='zoom'&&controlButton(name)),toolSet=esc(toolNames.join(',')),toolControls=toolNames.length?(commandChrome?`<div class="canonical-map__tools"${controlsVqa} data-map-control-set="${toolSet}">${toolNames.map(controlButton).join('')}</div>`:`<div class="canonical-map__controls"${controlsVqa} data-map-control-set="${toolSet}">${toolNames.map(controlButton).join('')}</div>`):'',zoomControls=definition.controls.includes('zoom')?`<div class="canonical-map__zoom" data-map-control-set="zoom">${controlButton('zoom')}</div>`:'',controls=`${toolControls}${zoomControls}`;
  const declaredLegend=Array.isArray(mapScene?.legend)?mapScene.legend.filter(name=>typeof name==='string'&&name):[],legendItems=[visibleLayers.includes('incidentPoints')&&resolvedScope==='COMMAND'?['incident','Priority incidents']:null,visibleLayers.includes('observedGeometry')?['observed','Observed geometry']:null,visibleLayers.includes('observations')?['thermal','Thermal observations']:null,visibleLayers.includes('forecastGeometry')?['forecast','Forecast scenario']:null,visibleLayers.includes('operationalAreas')?['operations','Operational areas']:null,visibleLayers.includes('controlLines')?['control','Control lines']:null,visibleLayers.includes('responseCoverageSurface')?['response','Sampled road reachability']:null,visibleLayers.includes('responseCoverageRoutes')?['response','Road-routed response paths']:null,visibleLayers.includes('responseFacilities')?['resources','Response facilities']:null,visibleLayers.some(name=>['resources','assignments','locations'].includes(name))?['resources','Operational resources']:null].filter(Boolean),legendSet=esc(legendItems.map(([,text])=>text).join(',')),legend=legendMarkup!==null?legendMarkup:!legendItems.length?'':`<div class="canonical-map__legend"${vqa?` data-vqa="${esc(vqa)}.legend"`:''} data-map-legend-set="${legendSet}">${legendItems.map(([tone,text])=>`<span><i class="legend-key legend-key--${tone}"></i>${esc(text)}</span>`).join('')}</div>`;
  const focusChip=focusedLayer?`<div class="canonical-map__focus-chip" role="status"><span>${esc(operatorText(focusedLayer))} highlighted</span><button type="button" data-action="map-clear-focus">Clear focus</button></div>`:'';
  return`<div class="canonical-map ${commandChrome?'canonical-map--command':''} canonical-map--scope-${sceneClass(resolvedScope)} ${className}" data-map-scene-owner="${esc(resolvedScope)}" data-map-scene-type="${esc(sceneType)}" data-map-scene-contract-source="${mapScene?'BACKEND_MAP_SCENE':'LOCAL_EXPLICIT_FALLBACK'}" data-map-camera-source="${storedZoom!==null||storedCenter?'OPERATOR_OVERRIDE':mapScene?'BACKEND_MAP_SCENE':'LOCAL_EXPLICIT_FALLBACK'}" data-map-camera-incident="${esc(storedCamera.selectedIncidentId??'')}" data-map-label-policy="${esc(definition.labelPolicy)}" data-map-declared-controls="${esc(definition.controls.join(','))}" data-map-declared-legend="${esc(declaredLegend.join(','))}" data-map-legend-set="${legendSet}"${vqaAttribute}>${tileMap({coordinate,zoom:resolvedZoom,thermal:resolvedThermal,markers,presentation,mapScene,scope:resolvedScope,sceneIdentity,sceneType,selectedIncidentId:selectedId,declaredLayers:definition.layers,visibleLayers,showLabels:showBasemapLabels,label,enabled,fitBounds:fitBackendBounds})}${controls}${legend}${focusChip}</div>`;
}
export function generatedAt(source){return source?.generatedAt?`Generated ${timeLabel(source.generatedAt)}`:'Generation time unavailable';}
export function objectTitle(item,fallback='Record'){
  const title=operatorText(item?.title??item?.label??item?.name??item?.quantity_question??item?.missingQuantity??item?.transitionId??item?.entityId??item?.eventType??item?.id,{missing:fallback});
  return title==='Operational change'?'Assessment updated':title;
}
export function objectState(item){return operatorText(item?.state??item?.status??item?.classification,{missing:'Not reported'});}
export function objectMeta(item){return operatorText(item?.reason??(Array.isArray(item?.reasons)?item.reasons.join(' · '):null)??item?.whyItMatters??item?.why_it_matters??item?.explanation??item?.summary??item?.basis,{missing:'Explanation unavailable'});}
