import { esc } from './components.js?v=2.1.0';
import { icon } from './icons.js?v=2.1.0';
import { evidenceDebtItems, incidentAssessment, incidentChangedAt, incidentId, incidentLabel, incidentLocation, incidentNextDecision, operatorText, timeLabel } from './canonicalViewModel.js?v=3.0.0';
import { freshnessState, relativeTimeLabel, vigiaIncidentSelect, vigiaStateLabel } from './operatorPrimitives.js?v=3.2.0';

const rows=value=>Array.isArray(value)?value:[];
const text=(...values)=>operatorText(values.find(value=>value!==null&&value!==undefined&&String(value).trim())??null,{missing:'Not reported'});
const latest=items=>items.map(item=>item?.observedAt??item?.updatedAt??item?.at??item?.changedAt).filter(value=>Number.isFinite(Date.parse(value))).sort((a,b)=>Date.parse(b)-Date.parse(a))[0]??null;
const title=(item,fallback)=>text(item?.title,item?.label,item?.name,item?.whatIsMissing,item?.missingQuantity,item?.quantity_question,item?.reason,fallback);
const sourceNames=(graph,scene)=>[...rows(graph?.sources),...rows(graph?.evidence),...rows(graph?.observations),...rows(scene?.layers?.observations?.value),...rows(scene?.layers?.thermalSupport?.value)].map(item=>text(item?.sourceFamily,item?.provider,item?.platform,item?.instrument,item?.source)).filter(value=>value!=='Not reported');
const priorityScore=item=>Number(item?.operationalTruth?.priority?.score??item?.incident?.operationalTruth?.priority?.score??item?.incident?.priority?.score??item?.priority?.score??0);
const orderedIncidents=incidents=>[...incidents].sort((first,second)=>priorityScore(second)-priorityScore(first)||Date.parse(incidentChangedAt(second)??0)-Date.parse(incidentChangedAt(first)??0)||incidentId(first).localeCompare(incidentId(second)));

export function incidentContextSwitcher({state,incidents=[],incident=null,source=null}){
  const ordered=orderedIncidents(incidents),currentId=incidentId(incident),index=Math.max(0,ordered.findIndex(item=>incidentId(item)===currentId)),previous=ordered[index-1]??null,next=ordered[index+1]??null,changed=incidentChangedAt(incident),graph=incident?.evidenceGraph??source?.data?.evidenceGraph?.value??{},sources=new Set(sourceNames(graph,null)),fresh=freshnessState(changed,Date.now());
  return`<section class="incident-context-switcher panel-surface" data-vqa="incident.context-switcher">
    <div class="incident-context-switcher__select"><small>Incident context</small>${vigiaIncidentSelect({id:'incident-context',label:'Incident context',value:currentId,incidents:ordered,openId:state.openSelectId,query:state.incidentContextSearch,inputKey:'incident-context-search',selectionAction:'select-context-incident'})}</div>
    <div class="incident-context-switcher__meta" aria-live="polite">${vigiaStateLabel(incidentAssessment(incident),{compact:true})}<span>${esc(incidentLocation(incident))}</span><span>${esc(fresh.label)}${changed?` · ${esc(timeLabel(changed))}`:''}</span><span>${sources.size?`${sources.size} sources`:'No supporting source returned'}</span></div>
    <div class="incident-context-switcher__steps"><button class="icon-button" data-action="select-context-incident:${esc(incidentId(previous))}" ${previous?'':'disabled'} aria-label="Previous incident">${icon('chevron',15)}</button><button class="icon-button incident-context-switcher__next" data-action="select-context-incident:${esc(incidentId(next))}" ${next?'':'disabled'} aria-label="Next incident">${icon('chevron',15)}</button></div>
  </section>`;
}

export function incidentQuicklook({incident,detail=null,work=[],scene=null,route='command-overview',expanded=globalThis.__VIGIA_QUICKLOOK_EXPANDED__===true}){
  if(!incident)return'';
  const canonical=incidentId(detail)===incidentId(incident)?detail:incident,graph=canonical?.evidenceGraph??{},observations=[...rows(scene?.layers?.observations?.value),...rows(scene?.layers?.thermalSupport?.value),...rows(graph?.observations)],lastObserved=latest(observations)??incidentChangedAt(canonical),fresh=freshnessState(lastObserved,detail?.updatedAt??Date.now()),sources=[...new Set(sourceNames(graph,scene))],familyCount=Number(canonical?.independence?.distinctFamilyCount??0),changes=rows(canonical?.transitions),material=changes.sort((a,b)=>Date.parse(b?.at??b?.changedAt??0)-Date.parse(a?.at??a?.changedAt??0))[0],unknown=evidenceDebtItems(canonical?.evidenceDebt)[0],human=work.find(item=>/NEEDS_YOU|HUMAN|AUTHORITY|MANUAL|ACKNOWLEDGEMENT_REQUIRED/.test(String(item?.lane??item?.state??item?.status??item?.humanAttention?.state??'').toUpperCase())),activity=work[0],risk=[canonical?.risk?.summary,canonical?.exposure?.summary,canonical?.atRisk].find(value=>typeof value==='string'&&value.trim())??null,next=incidentNextDecision(canonical),identifier=incidentId(canonical),truth=canonical?.operationalTruth??incident?.operationalTruth??{},assessment=canonical?.evaluation?.operatorStatement??canonical?.claim?.proposition??null,whyShown=truth?.priority?.explanation??truth?.priority?.rationale?.[0]??'Selected from the current prioritized incident queue.',sourceStrength=sources.length?`${sources.length} admitted source${sources.length===1?'':'s'} · ${sources.slice(0,3).join(' · ')}`:familyCount?`${familyCount} admitted causal famil${familyCount===1?'y':'ies'}`:'Source-family strength is not present in this summary.',materialChange=material?title(material,'Assessment updated'):'No material transition is recorded in the current projection.',systemAction=activity?title(activity,'Monitoring current sources'):unknown?.collectionPlan?'Collection plan active':'Monitoring for a qualifying source change',nextDecision=next!=='Not provided'?next:canonical?.decisionSupport?.decision??(activity||unknown?'Reevaluate when the active collection requirement changes the incident assessment.':'Continue monitoring until a decision threshold is crossed.'),facts=[['Why it is shown',whyShown],['What is known',assessment??`Current classification: ${text(truth?.classification,incidentAssessment(canonical))}.`],['Source strength',sourceStrength],['Latest material change',materialChange],['Potential impact',risk],['Highest-impact unknown',unknown?title(unknown,'Independent confirmation required'):'No unresolved information requirement is attached.'],['What VIGIA is doing',systemAction],['Requires a person',human?title(human,'Operator decision required'):null],['Next decision',nextDecision]].filter(([,value])=>value&&value!=='Not reported');
  const backLabel=route==='global-awareness'?'results':route==='command-overview'?'priorities':route==='incidents'?'latest changes':'route brief';
  return`<section class="incident-quicklook panel-surface ${expanded?'is-expanded':''}" data-vqa="incident.quicklook" data-quicklook-incident="${esc(identifier)}" data-quicklook-data="canonical-summary" aria-live="polite" tabindex="-1">
    <header><div><small>Incident Quicklook</small><h2>${esc(incidentLabel(canonical))}</h2><p>${esc(incidentLocation(canonical))}</p></div><div class="incident-quicklook__header-actions"><button class="text-button incident-quicklook__expand" data-action="quicklook-expand" aria-pressed="${expanded}">${expanded?'Collapse':'Expand'}</button><button class="text-button" data-action="quicklook-back">Back to ${backLabel}</button></div></header>
    <div class="incident-quicklook__status">${vigiaStateLabel(incidentAssessment(canonical),{compact:true})}${vigiaStateLabel(fresh.state,{label:fresh.label,compact:true})}${lastObserved?`<span>Last observed ${esc(timeLabel(lastObserved))}</span>`:''}</div>
    <dl class="incident-quicklook__facts">${facts.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>
    <div class="incident-quicklook__actions"><button class="button button--primary" data-action="open-incident-workspace:${esc(identifier)}">Open incident workspace</button><button class="button button--ghost" data-action="open-incident-route:intelligence:${esc(identifier)}">Open Intelligence</button><button class="button button--ghost" data-action="open-incident-route:operations:${esc(identifier)}">Open Operations</button>${scene?.layers?.observations?.value?.length?`<button class="button button--ghost" data-action="map-focus-layer:observations">Show source observation</button>`:''}</div>
    <details class="technical-details"><summary>Technical provenance</summary><dl><div><dt>Incident ID</dt><dd>${esc(identifier)}</dd></div><div><dt>Exact freshness</dt><dd>${esc(lastObserved?`${timeLabel(lastObserved)} · ${relativeTimeLabel(lastObserved)}`:'Not reported')}</dd></div><div><dt>Sources</dt><dd>${esc(sources.join(' · ')||'Not reported')}</dd></div></dl></details>
  </section>`;
}

export function executiveSection({id='',eyebrow='',title,description='',aside='',body='',className=''}){
  const labelled=id?` id="${esc(id)}"`:'';
  return`<section${labelled} class="executive-section ${esc(className)}"><header><div>${eyebrow?`<small>${esc(eyebrow)}</small>`:''}<h2>${esc(title)}</h2>${description?`<p>${esc(description)}</p>`:''}</div>${aside}</header><div class="executive-section__body">${body}</div></section>`;
}

export function executiveDisclosure({title,description='',body,count=null,open=false,className=''}){
  return`<details class="executive-disclosure ${esc(className)}" ${open?'open':''}><summary><span><strong>${esc(title)}</strong>${description?`<small>${esc(description)}</small>`:''}</span>${count===null?'':`<b>${esc(count)}</b>`}${icon('chevron',14)}</summary><div class="executive-disclosure__body">${body}</div></details>`;
}
