import { badge, button, esc } from './components.js?v=2.1.0';

const human=value=>String(value??'UNAVAILABLE').replaceAll('_',' ');
const tone=value=>String(value).includes('P1')||String(value).includes('CONFLICT')?'critical':String(value).includes('P2')||String(value).includes('STALE')||String(value).includes('BLOCKING')?'warning':'teal';
const when=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString():'UNAVAILABLE';
const list=(rows,empty,render)=>rows?.length?rows.map(render).join(''):`<p class="intelligence-empty">${esc(empty)}</p>`;
const sourceId=(state,id)=>state.runtime?.intelligenceIncidents?.[id]??state.runtime?.intelligenceInbox?.items?.find(item=>String(item.incidentId)===String(id))??null;

export function incidentIntelligence(state,id=state.selectedEventId){return id?sourceId(state,id):null;}

export function overviewIntelligence(state,events=[]){
  const inbox=state.runtime?.intelligenceInbox,items=(inbox?.items??[]).slice(0,5),labels=new Map(events.map(event=>[String(event.id),event.label??event.id]));
  const current=items[0],dependency=state.runtime?.dependencies?.intelligence,stale=dependency?.state==='STALE'||items.some(item=>item.projectionState==='STALE');
  return `<section class="intelligence-inbox" aria-labelledby="intelligence-inbox-title" data-operator-answer="what-is-happening">
    <header><div><span class="eyebrow">Current operational picture</span><h1 id="intelligence-inbox-title">Intelligence inbox</h1><p>${current?esc(current.situation?.operatorStatement):'No governed intelligence projection is currently available.'}</p></div><div>${badge(stale?'STALE':dependency?.state??'UNAVAILABLE',stale?'warning':dependency?.state==='READY'?'green':'critical')}</div></header>
    ${stale?`<div class="intelligence-stale" role="status"><strong>Last-good intelligence only</strong><span>Generated ${esc(when(current?.lastGoodAt??current?.generatedAt))}. Refresh before treating it as current.</span></div>`:''}
    <div class="intelligence-inbox__grid"><section data-operator-answer="what-requires-attention"><header><span>Review next · maximum five</span><strong>${items.length}/5</strong></header>${list(items,'No attention item is available.',(item,index)=>`<button class="intelligence-attention intelligence-attention--${esc(tone(item.attention?.tier))}" data-action="select-event:${esc(item.incidentId)}" ${index===0?'data-operator-answer="top-incident"':''}><span>${badge(item.attention?.tier??'P4',tone(item.attention?.tier),true)}</span><span><strong>${esc(labels.get(String(item.incidentId))??item.incidentId)}</strong><small>${esc(human(item.situation?.state))}</small><em>${esc(human(item.attention?.reasons?.[0]??'MONITOR'))}</em></span></button>`)}</section>
      <section data-operator-answer="what-changed"><header><span>What changed</span><strong>${inbox?.materialChanges?.length??0}</strong></header>${list((inbox?.materialChanges??[]).slice(0,5),'No new external fact or material state transition.',item=>`<article class="intelligence-row"><span>${badge(item.externalFact?'EXTERNAL FACT':item.humanDecision?'HUMAN DECISION':'STATE CHANGE',item.externalFact?'green':'teal',true)}</span><strong>${esc(item.summary)}</strong><small>${esc(when(item.at))}</small></article>`)}</section>
      <section data-operator-answer="what-is-unknown"><header><span>Main unknowns</span><strong>${inbox?.decisionBlockingUnknowns?.length??0}</strong></header>${list((inbox?.decisionBlockingUnknowns??[]).slice(0,5),'No policy-proven decision blocker is returned.',item=>`<article class="intelligence-row intelligence-row--warning"><strong>${esc(item.whatIsUnknown)}</strong><small>Blocks ${esc(human(item.strongerClaimBlocked))}</small><em>${esc(item.reason)}</em></article>`)}</section>
      <section data-operator-answer="physical-versus-reported"><header><span>Physical / reported support</span><strong>${inbox?.sourceConditions?.length??0}</strong></header>${list((inbox?.sourceConditions??[]).slice(0,5),'No source condition is available.',item=>`<article class="intelligence-row"><span>${badge(item.providerHealth??'UNKNOWN',item.providerHealth==='HEALTHY'?'green':'warning',true)}</span><strong>${esc(human(item.sourceFamily))}</strong><small>${esc(human(item.performanceState))} · sample ${esc(item.sampleSize??0)}</small></article>`)}</section>
    </div></section>`;
}

export function detectIntelligence(state,event,active='now'){
  const projection=incidentIntelligence(state,event?.id);if(!projection)return'';
  const unknown=projection.unknowns?.find(item=>item.classification==='DECISION_BLOCKING'),candidate=projection.nextBestEvidence?.candidates?.[0],delta=projection.decisionDelta?.[0];
  const content={now:`<span>Situation</span><strong>${esc(human(projection.situation?.state))}</strong><p>${esc(projection.situation?.operatorStatement)}</p>`,next:`<span>Next-best evidence</span><strong>${esc(human(candidate?.candidateEvidenceType??projection.nextBestEvidence?.state))}</strong><p>${candidate?`${esc(human(candidate.eligibleSource))} · ${esc(human(candidate.availabilityState))}`:'No eligible evidence asset is configured; no task was created.'}</p>`,why:`<span>Why this assessment</span><strong>${esc(human(projection.explanationTrace?.conclusion))}</strong><p>${esc(projection.explanationTrace?.operatorCopy)}</p>`}[active];
  return `<div class="detail-inspector__hero detail-inspector__hero--intelligence">${content}</div><div class="intelligence-compact"><article><span>What changed</span><strong>${esc(delta?.summary??'No material input change')}</strong><small>${esc(human(delta?.type??'RECOMPUTED PROJECTION'))}</small></article><article><span>Decision-blocking unknown</span><strong>${esc(unknown?.whatIsUnknown??'None policy-proven')}</strong><small>${unknown?`Blocks ${esc(human(unknown.strongerClaimBlocked))}`:'No stronger claim is proven blocked.'}</small></article></div>${active==='why'?trace(projection):''}`;
}

function trace(projection){const trace=projection.explanationTrace??{};return `<details class="intelligence-details" data-intelligence-instrument="EXPLANATION_TRACE_OPENED"><summary>Why this assessment?</summary><div><dl><div><dt>Rule set</dt><dd>${esc(trace.ruleSetVersion??projection.ruleSetVersion)}</dd></div><div><dt>Evidence graph</dt><dd>${esc(projection.evidenceGraphHash)}</dd></div><div><dt>Explanation hash</dt><dd>${esc(trace.explanationHash)}</dd></div></dl><h4>Rules applied</h4>${list(trace.rulesApplied,'No rule is returned.',item=>`<code>${esc(item)}</code>`)}<h4>Supporting evidence</h4>${list(trace.supportingEvidence,'No supporting evidence ID.',item=>`<code>${esc(item)}</code>`)}<h4>Contradictions</h4>${list(trace.contradictoryEvidence,'No contradiction ID.',item=>`<code>${esc(item)}</code>`)}<h4>Excluded / stale</h4>${list(trace.excludedEvidence,'No excluded evidence.',item=>`<span>${esc(item.id)} · ${esc(item.reason)}</span>`)}</div></details>`;}

export function evidenceIntelligence(state,event){
  const projection=incidentIntelligence(state,event?.id);if(!projection)return`<section class="panel intelligence-unavailable"><strong>Intelligence projection unavailable</strong><p>Underlying evidence remains accessible. No assessment is inferred in the browser.</p></section>`;
  const blockers=projection.unknowns?.filter(item=>['DECISION_BLOCKING','DECISION_MATERIAL'].includes(item.classification))??[],candidates=projection.nextBestEvidence?.candidates??[],tdt=projection.timeToDefensibleTruth?.stages??[];
  return `<section class="panel intelligence-inspection"><header><div><span class="eyebrow">Current assessment</span><h3>${esc(human(projection.situation?.state))}</h3><p>${esc(projection.situation?.operatorStatement)}</p></div><div>${badge(projection.projectionState==='STALE'?'STALE':projection.attention?.tier??'P4',projection.projectionState==='STALE'?'warning':tone(projection.attention?.tier))}${button('Acknowledge assessment',{tone:'secondary',action:`acknowledge-intelligence:${projection.incidentId}`,disabled:projection.projectionState==='STALE'||state.runtime?.session?.mutationReady!==true})}</div></header><div class="intelligence-inspection__grid">
    <section><h4>Supporting evidence</h4>${list(projection.explanationTrace?.supportingEvidence,'No supporting evidence ID.',item=>`<code>${esc(item)}</code>`)}</section><section><h4>Contradicting evidence</h4>${list(projection.explanationTrace?.contradictoryEvidence,'No contradiction returned.',item=>`<code>${esc(item)}</code>`)}</section><section><h4>Excluded / stale evidence</h4>${list(projection.explanationTrace?.excludedEvidence,'No excluded evidence.',item=>`<span>${esc(item.id)} · ${esc(item.reason)}</span>`)}</section><section><h4>Material unknowns</h4>${list(blockers,'No material unknown returned.',item=>`<article><strong>${esc(item.whatIsUnknown)}</strong><small>${esc(human(item.classification))} · blocks ${esc(human(item.strongerClaimBlocked))}</small></article>`)}</section><section><h4>Next-best evidence</h4>${list(candidates.slice(0,5),'No eligible source or asset configured.',item=>`<article><strong>${esc(item.rank)} · ${esc(human(item.eligibleSource))}</strong><small>${esc(human(item.availabilityState))} · ${esc(human(item.addressesUnknown))}</small></article>`)}</section><section><h4>Time to defensible truth</h4>${list(tdt,'No TDT stages returned.',item=>`<article><strong>${esc(human(item.stage))}</strong><small>${item.timestamp?esc(when(item.timestamp)):'NOT REACHED · duration unavailable'}</small></article>`)}</section>
    </div>${trace(projection)}${passportDetails(projection.sourceContext)}<footer><small>Snapshot ${esc(projection.snapshotVersion)} · generated ${esc(when(projection.generatedAt))}</small></footer></section>`;
}

function passportDetails(passports=[]){return `<details class="intelligence-details" data-intelligence-instrument="SOURCE_PASSPORT_OPENED"><summary>Source performance context</summary><div class="passport-grid">${list(passports,'No contextual passport is available.',item=>`<article><header><strong>${esc(human(item.sourceFamily))}</strong>${badge(item.performanceState,item.performanceState==='STRONG_RECENT_PERFORMANCE_IN_THIS_CONTEXT'?'green':'teal',true)}</header><dl><div><dt>Provider health</dt><dd>${esc(item.providerHealth)}</dd></div><div><dt>Measured sample</dt><dd>${esc(item.sampleSize)}</dd></div><div><dt>Window</dt><dd>${esc(when(item.measurementWindow?.from))} → ${esc(when(item.measurementWindow?.to))}</dd></div><div><dt>Missing factors</dt><dd>${esc(item.missingFactors?.map(human).join(' · ')||'None')}</dd></div></dl><p>${esc(item.qualification)}</p></article>`)}</div></details>`;}

export function sourcePassportInspection(state){const projection=incidentIntelligence(state);return `<section class="panel intelligence-passports"><header><div><span class="eyebrow">Contextual source performance</span><h3>Source Performance Passport</h3></div>${projection?badge(`Incident ${projection.incidentId}`,'teal',true):badge('Select incident','warning',true)}</header>${projection?passportDetails(projection.sourceContext):'<p class="intelligence-empty">Select an incident in Detect to inspect opportunity-conditioned source performance.</p>'}</section>`;}

export function handoffIntelligence(state){const inbox=state.runtime?.intelligenceInbox,changes=(inbox?.materialChanges??[]).slice(0,10),unknowns=(inbox?.decisionBlockingUnknowns??[]).slice(0,10),rows=[...changes.map(item=>({kind:item.externalFact?'External fact':'State change',text:item.summary,state:item.type})),...unknowns.map(item=>({kind:'Decision blocker',text:item.whatIsUnknown,state:item.classification}))].slice(0,20);return `<section class="panel intelligence-handoff"><header><div><span class="eyebrow">Material intelligence transfer</span><h3>Changes and unresolved blockers</h3></div>${badge(`${rows.length}/20`,'teal')}</header>${list(rows,'No material intelligence transfer item is returned.',item=>`<article><span>${esc(item.kind)}</span><strong>${esc(item.text)}</strong><small>${esc(human(item.state))}</small></article>`)}</section>`;}

export function replayIntelligence(state,id){const projection=state.runtime?.replayIntelligence?.[id];if(!projection)return'<section class="panel intelligence-unavailable"><strong>Historical intelligence unavailable</strong><p>No current truth is substituted at the replay clock.</p></section>';const later=projection.futureEvidenceExcluded??[];return `<section class="panel replay-intelligence"><header><div><span class="eyebrow">Governed intelligence clock</span><h3>What VIGIA knew then</h3></div>${badge('HISTORICAL','teal')}</header><div><article><span>Assessment then</span><strong>${esc(human(projection.situation?.underlyingState))}</strong><small>${esc(projection.explanationTrace?.operatorCopy)}</small></article><article><span>Unknown then</span><strong>${esc(projection.unknowns?.[0]?.whatIsUnknown??'No material unknown')}</strong><small>${esc(human(projection.unknowns?.[0]?.classification??'UNAVAILABLE'))}</small></article><article><span>Recommended then</span><strong>${esc(human(projection.nextBestEvidence?.state))}</strong><small>No autonomous action created.</small></article><article><span>Changed later</span><strong>${esc(later.length)} future-visible records excluded</strong><small>Future knowledge is not present in the historical assessment.</small></article></div>${trace(projection)}</section>`;}

export function preventIntelligence(state,id){const value=state.runtime?.preventionIntelligence?.[id];return value?`<section class="prevent-intelligence"><article><span>Intelligence screening state</span><strong>${esc(human(value.screeningState))}</strong></article><article><span>Decision-blocking unknown</span><strong>${esc(value.unknown?.whatIsUnknown??'None returned')}</strong></article><article><span>Next governed evidence</span><strong>${esc(human(value.nextEvidence?.state))}</strong></article><small>Screening only · no treatment recommendation · intelligence is not evidence.</small></section>`:'';}
