import { basemapTileUrl } from './vigiaApi.js?v=2.1.0';
import { emptyCollection } from './mapRuntimeState.js?v=3.0.0';

export const mapPalette=Object.freeze({critical:'#d63a2e',available:'#2f7a52',information:'#278897',warning:'#d9a21b',candidate:'#f0b429',context:'#87909f',route:'#63b3c0',outline:'#f5f1eb'});
export const incidentMapSymbols=Object.freeze({VERIFIED_CURRENT:{fill:mapPalette.critical,stroke:mapPalette.outline,label:'Verified current'},DETECTION_CANDIDATE:{fill:'rgba(217,162,27,.18)',stroke:mapPalette.candidate,label:'Detection candidate'},NEEDS_REVALIDATION:{fill:'rgba(39,136,151,.10)',stroke:mapPalette.route,label:'Needs revalidation'},HISTORICAL_CLOSED:{fill:'rgba(101,112,133,.08)',stroke:mapPalette.context,label:'Earlier / closed'}});
export function facilityMapSymbol(availability,type=null){const labels={hospital:'Hospital',health_center:'Health centre',fire_station:'Fire station',police_station:'Police station',public_prosecutor:'Public prosecution service',civil_protection:'Civil protection',shelter_generic:'Mapped shelter',water_point:'Water point'};if(type&&!['official_wildfire_refuge','temporary_reception_center'].includes(type))return{fill:mapPalette.information,label:labels[type]??'Public facility'};return availability==='CONFIRMED_AVAILABLE'?{fill:mapPalette.available,label:'Capacity available'}:availability==='CONFIRMED_NO_AVAILABLE_CAPACITY'?{fill:mapPalette.critical,label:'No available capacity'}:{fill:mapPalette.warning,label:'Capacity unconfirmed'};}

export function mapStyle(config,{tier=3}={}) {
  const style={ version: 8, sources: {
    'vigia-imagery': { type: 'raster', tiles: [basemapTileUrl('imagery', '{z}', '{x}', '{y}')], tileSize: 256, minzoom: 1, maxzoom: 18, attribution: 'Esri World Imagery · VIGIA governed proxy' },
    'vigia-labels': { type: 'raster', tiles: [basemapTileUrl('labels', '{z}', '{x}', '{y}')], tileSize: 256, minzoom: 1, maxzoom: 18 },
    'vigia-markers': { type: 'geojson', data: config.markers ?? emptyCollection(), cluster: true, clusterMaxZoom: 13, clusterRadius: 44 },
    'vigia-operational': { type: 'geojson', data: config.features ?? emptyCollection() },
    ...(config.thermal?.url ? { 'vigia-thermal': { type: 'image', url: config.thermal.url, coordinates: config.thermal.coordinates } } : {}),
  }, layers: [
    { id: 'vigia-imagery', type: 'raster', source: 'vigia-imagery', paint: { 'raster-saturation': -.2, 'raster-contrast': .12, 'raster-brightness-max': .78, 'raster-fade-duration': 0 } },
    { id: 'vigia-terrain-fill', type: 'fill', source: 'vigia-operational', filter: ['==', ['get', 'layer'], 'terrain'], paint: { 'fill-color': '#63805f', 'fill-opacity': .18 } },
    { id: 'vigia-areas-fill', type: 'fill', source: 'vigia-operational', filter: ['in', ['get', 'layer'], ['literal', ['operationalAreas', 'stagingAreas', 'bases']]], paint: { 'fill-color': ['match', ['get', 'layer'], 'operationalAreas', mapPalette.information, 'stagingAreas', mapPalette.available, mapPalette.outline], 'fill-opacity': .2 } },
    { id: 'vigia-observed-fill', type: 'fill', source: 'vigia-operational', filter: ['==', ['get', 'layer'], 'observedGeometry'], paint: { 'fill-color': mapPalette.critical, 'fill-opacity': .28 } },
    { id: 'vigia-thermal-support-fill', type: 'fill', source: 'vigia-operational', filter: ['==', ['get', 'layer'], 'thermalSupport'], paint: { 'fill-color': '#ff8a2b', 'fill-opacity': .12 } },
    { id: 'vigia-forecast-fill', type: 'fill', source: 'vigia-operational', filter: ['==', ['get', 'layer'], 'forecastGeometry'], paint: { 'fill-color': mapPalette.warning, 'fill-opacity': .12 } },
    { id: 'vigia-response-coverage-samples', type: 'circle', source: 'vigia-operational', filter: ['==', ['get', 'layer'], 'responseCoverageSurface'], paint: { 'circle-color': ['match', ['get', 'coverageState'], 'CONFIRMED_AVAILABLE_CAPABILITY', mapPalette.available, 'ROUTED_CAPABILITY_DYNAMIC_STATE_UNKNOWN', mapPalette.warning, 'ROUTED_NO_CONFIRMED_AVAILABLE_CAPACITY', mapPalette.critical, mapPalette.context], 'circle-radius': ['interpolate', ['linear'], ['zoom'], 6, 4, 10, 8, 14, 14], 'circle-opacity': .38, 'circle-stroke-color': mapPalette.outline, 'circle-stroke-width': 1 } },
    { id: 'vigia-geometry-lines', type: 'line', source: 'vigia-operational', filter: ['in', ['get', 'layer'], ['literal', ['observedGeometry', 'thermalSupport', 'forecastGeometry', 'operationalAreas', 'controlLines', 'divisions', 'stagingAreas', 'bases', 'roads', 'responseCoverageRoutes']]], paint: { 'line-color': ['match', ['get', 'layer'], 'observedGeometry', mapPalette.outline, 'thermalSupport', '#ff8a2b', 'forecastGeometry', mapPalette.warning, 'controlLines', mapPalette.outline, 'divisions', mapPalette.warning, 'roads', mapPalette.outline, 'responseCoverageRoutes', mapPalette.route, mapPalette.route], 'line-width': ['match', ['get', 'layer'], 'observedGeometry', 2.2, 'controlLines', 2.2, 'responseCoverageRoutes', 2.6, 1.3], 'line-opacity': .92, 'line-dasharray': [3, 2] } },
    { id: 'vigia-focused-fill', type: 'fill', source: 'vigia-operational', filter: ['==', ['get', 'layer'], '__none__'], paint: { 'fill-color': '#fff1a8', 'fill-opacity': 0 } },
    { id: 'vigia-focused-line', type: 'line', source: 'vigia-operational', filter: ['==', ['get', 'layer'], '__none__'], paint: { 'line-color': '#fff1a8', 'line-width': 5, 'line-opacity': 0 } },
    ...(config.thermal?.url ? [{ id: 'vigia-thermal', type: 'raster', source: 'vigia-thermal', paint: { 'raster-opacity': .46, 'raster-fade-duration': 0 } }] : []),
    { id: 'vigia-labels', type: 'raster', source: 'vigia-labels', layout: { visibility: config.showLabels ? 'visible' : 'none' }, paint: { 'raster-opacity': .96, 'raster-brightness-min': .72, 'raster-brightness-max': 1, 'raster-contrast': .5, 'raster-fade-duration': 0 } },
    { id: 'vigia-clusters', type: 'circle', source: 'vigia-markers', filter: ['has', 'point_count'], paint: { 'circle-color': '#71869f', 'circle-radius': ['step', ['get', 'point_count'], 9, 10, 12, 50, 15], 'circle-stroke-color': mapPalette.outline, 'circle-stroke-width': 2, 'circle-opacity': .94 } },
    { id: 'vigia-unclustered', type: 'circle', source: 'vigia-markers', filter: ['!', ['has', 'point_count']], paint: { 'circle-color': ['match', ['get', 'classification'], 'VERIFIED_CURRENT', mapPalette.critical, 'DETECTION_CANDIDATE', 'rgba(217,162,27,.18)', 'NEEDS_REVALIDATION', 'rgba(39,136,151,.10)', 'HISTORICAL_CLOSED', 'rgba(101,112,133,.08)', ['match', ['get', 'tone'], 'green', mapPalette.available, 'info', mapPalette.information, 'teal', mapPalette.information, 'critical', mapPalette.critical, mapPalette.warning]], 'circle-radius': ['case', ['boolean', ['get', 'selected'], false], 11, ['match', ['get', 'classification'], 'DETECTION_CANDIDATE', 8, 'NEEDS_REVALIDATION', 9, 7]], 'circle-stroke-color': ['match', ['get', 'classification'], 'DETECTION_CANDIDATE', mapPalette.candidate, 'NEEDS_REVALIDATION', mapPalette.route, 'HISTORICAL_CLOSED', mapPalette.context, mapPalette.outline], 'circle-stroke-width': ['match', ['get', 'classification'], 'DETECTION_CANDIDATE', 3, 'NEEDS_REVALIDATION', 2.5, 'HISTORICAL_CLOSED', 1.5, 2], 'circle-opacity': ['match', ['get', 'classification'], 'HISTORICAL_CLOSED', .6, .96] } },
    { id: 'vigia-focused-points', type: 'circle', source: 'vigia-markers', filter: ['==', ['get', 'kind'], '__none__'], paint: { 'circle-color': 'rgba(0,0,0,0)', 'circle-radius': 18, 'circle-stroke-color': '#fff1a8', 'circle-stroke-width': 4, 'circle-opacity': 0 } },
  ] };
  if(tier===0){style.layers=style.layers.filter(l=>['vigia-imagery','vigia-clusters','vigia-unclustered'].includes(l.id));style.sources=Object.fromEntries(Object.entries(style.sources).filter(([id])=>['vigia-imagery','vigia-markers'].includes(id)));style.sources['vigia-markers'].data={type:'FeatureCollection',features:(config.markers?.features??[]).filter(f=>f.properties?.selected===true||f.properties?.kind==='incident')};}
  return style;
}
