import { esc } from './components.js?v=2.1.0';
import { validCoordinate } from './viewModel.js?v=2.1.0';
import { finiteNumberOrNull } from './truth.js?v=2.1.0';

const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const lon2x=(lon,z)=>((lon+180)/360)*2**z;
const lat2y=(lat,z)=>{const radians=lat*Math.PI/180;return(1-Math.asinh(Math.tan(radians))/Math.PI)/2*2**z;};
const projectPixel=(coordinate,model)=>!model||!validCoordinate(coordinate)?null:{x:(lon2x(coordinate[0],model.zoom)-model.minX)*256,y:(lat2y(coordinate[1],model.zoom)-model.minY)*256};
const markerDistance=(first,second)=>Math.hypot(first.point.x-second.point.x,first.point.y-second.point.y);
const boxesIntersect=(first,second)=>first.left<second.right&&first.right>second.left&&first.top<second.bottom&&first.bottom>second.top;

export function layoutMapMarkers(markers,model){
  if(!model)return[];
  const projected=markers.map((item,index)=>{const point=projectPixel(item.coordinate,model);return point?{...item,index,point}:null;}).filter(Boolean),selected=projected.filter(item=>item.selected===true),ordinary=projected.filter(item=>item.selected!==true),groups=[];
  for(const item of ordinary){if(!['incident','observation'].includes(item.kind??'incident')){groups.push([item]);continue;}const group=groups.find(rows=>['incident','observation'].includes(rows[0]?.kind??'incident')&&rows[0]?.kind===item.kind&&rows.some(row=>markerDistance(row,item)<=42));if(group)group.push(item);else groups.push([item]);}
  const collapsed=groups.map(group=>group.length<2?group[0]:{...group[0],point:{x:group.reduce((sum,item)=>sum+item.point.x,0)/group.length,y:group.reduce((sum,item)=>sum+item.point.y,0)/group.length},clusterCount:group.length,clusterIds:group.map(item=>item.identifier).filter(Boolean),label:`${group.length} ${group[0].kind==='observation'?'observations':'incidents'} clustered; zoom in to review`,short:'',meta:'',status:'',showLabel:false,selected:false,action:'map-zoom-in'});
  const rows=[...selected,...collapsed].sort((a,b)=>Number(b.selected)-Number(a.selected)||a.index-b.index),accepted=[];
  return rows.map(item=>{const right=item.point.x<=model.size*.68,labelBox={left:right?item.point.x+22:item.point.x-194,right:right?item.point.x+194:item.point.x-22,top:item.point.y-24,bottom:item.point.y+28},requested=item.selected===true||item.showLabel===true,showLabel=item.clusterCount?false:requested&&!accepted.some(box=>boxesIntersect(box,labelBox));if(showLabel)accepted.push(labelBox);return{...item,showLabel,labelDirection:right?'right':'left',percent:{x:item.point.x/model.size*100,y:item.point.y/model.size*100}};});
}

function projectedPath(points,model,{close=true}={}){if(!Array.isArray(points)||points.length<2)return'';const projected=points.map(point=>projectPixel(point,model)).filter(Boolean);return projected.length<2?'':`${projected.map((point,index)=>`${index?'L':'M'} ${point.x.toFixed(2)} ${point.y.toFixed(2)}`).join(' ')}${close?' Z':''}`;}
function geometryPaths(value,model){const source=value?.type==='Feature'?value.geometry:value?.geometry?.type?value.geometry:value;if(!source||typeof source!=='object')return'';if(source.type==='Polygon')return(source.coordinates??[]).map(ring=>projectedPath(ring,model)).filter(Boolean).map(d=>`<path d="${d}"/>`).join('');if(source.type==='MultiPolygon')return(source.coordinates??[]).flatMap(polygon=>polygon.map(ring=>projectedPath(ring,model))).filter(Boolean).map(d=>`<path d="${d}"/>`).join('');if(source.type==='LineString'){const d=projectedPath(source.coordinates,model,{close:false});return d?`<path d="${d}"/>`:'';}if(source.type==='MultiLineString')return(source.coordinates??[]).map(line=>projectedPath(line,model,{close:false})).filter(Boolean).map(d=>`<path d="${d}"/>`).join('');return'';}
const sceneRows=(scene,name)=>{const layer=scene?.layers?.[name];return['READY','DEGRADED'].includes(layer?.state)&&Array.isArray(layer.value)?layer.value:[];};

export function sceneOverlay(scene,model,visibleLayers=[],{strict=false}={}){
  if(!scene)return'';
  const permits=name=>(strict||visibleLayers.length)?visibleLayers.includes(name):true,geometryLayer=(name,accessor=item=>item)=>permits(name)?sceneRows(scene,name).map(item=>geometryPaths(accessor(item),model)).filter(Boolean).join(''):'';
  const observed=permits('observedGeometry')?sceneRows(scene,'observedGeometry').map((item)=>{const paths=geometryPaths(item,model),properties=item?.type==='Feature'?(item.properties??{}):{},authoritative=properties.authoritativePerimeter===true,kind=String(properties.kind??properties.geometryKind??'observed_geometry');return paths?`<g class="tile-map__incident-shape is-focused ${authoritative?'is-authoritative':'is-observation-support'}" data-authoritative-perimeter="${authoritative}" data-geometry-kind="${esc(kind)}">${paths}</g>`:'';}).join(''):'',thermal=geometryLayer('thermalSupport'),areas=geometryLayer('operationalAreas',item=>item.geometry),forecast=geometryLayer('forecastGeometry'),terrain=geometryLayer('terrain'),roads=geometryLayer('roads',item=>item.geometry),controlLines=geometryLayer('controlLines',item=>item.geometry),divisions=geometryLayer('divisions',item=>item.geometry),staging=geometryLayer('stagingAreas',item=>item.geometry),bases=geometryLayer('bases',item=>item.geometry);
  const observations=permits('observations')?sceneRows(scene,'observations').map((item,index)=>{const point=projectPixel(item.coordinate,model),uncertainty=finiteNumberOrNull(item.geolocationUncertaintyM),radius=uncertainty===null?1.7:clamp(1.7+uncertainty/350,1.7,7);return point?`<g class="tile-map__thermal-observation" data-observation-id="${esc(item.id??`observation-${index+1}`)}" data-authoritative-perimeter="false"><circle class="tile-map__thermal-uncertainty" cx="${point.x.toFixed(2)}" cy="${point.y.toFixed(2)}" r="${radius.toFixed(2)}"/><circle cx="${point.x.toFixed(2)}" cy="${point.y.toFixed(2)}" r="1.7"/></g>`:'';}).join(''):'',locations=permits('locations')?sceneRows(scene,'locations').map(item=>{const point=projectPixel(item.coordinate,model);return point?`<circle cx="${point.x.toFixed(2)}" cy="${point.y.toFixed(2)}" r="2.1"/>`:'';}).join(''):'',assets=permits('contextAssets')?sceneRows(scene,'contextAssets').map(item=>{const point=projectPixel(item.coordinate,model);return point?`<rect x="${(point.x-2).toFixed(2)}" y="${(point.y-2).toFixed(2)}" width="4" height="4"/>`:'';}).join(''):'';
  return`${terrain?`<g class="tile-map__terrain">${terrain}</g>`:''}${roads?`<g class="tile-map__roads">${roads}</g>`:''}${observed}${thermal?`<g class="tile-map__thermal-support" data-authoritative-perimeter="false">${thermal}</g>`:''}${forecast?`<g class="tile-map__forecast-geometry">${forecast}</g>`:''}${areas?`<g class="tile-map__operational-areas">${areas}</g>`:''}${divisions?`<g class="tile-map__divisions">${divisions}</g>`:''}${controlLines?`<g class="tile-map__control-lines">${controlLines}</g>`:''}${staging?`<g class="tile-map__staging-areas">${staging}</g>`:''}${bases?`<g class="tile-map__bases">${bases}</g>`:''}${observations?`<g class="tile-map__hotspots">${observations}</g>`:''}${locations?`<g class="tile-map__command-locations">${locations}</g>`:''}${assets?`<g class="tile-map__context-assets">${assets}</g>`:''}`;
}
