import { esc } from './components.js?v=2.1.0';
import { icon } from './icons.js?v=2.1.0';
import { incidentAssessment, incidentChangedAt, incidentId, incidentLabel, incidentLocation, operatorText, timeLabel } from './canonicalViewModel.js?v=3.0.0';
import { finiteNumberOrNull } from './truth.js?v=2.1.0';
import { stateLabel, stateTone } from './stateLabel.js?v=1.0.0';

const layerLabels=Object.freeze({
  basemapImagery:'Satellite imagery',basemapLabels:'Place and boundary labels',incidentPoints:'Incident locations',observedGeometry:'Observed geometry',thermalSupport:'Thermal observation footprints',observations:'Thermal observations',weather:'Weather context',wind:'Wind context',terrain:'Terrain analysis',forecastGeometry:'Forecast scenario geometry',contextAssets:'Critical assets',roads:'Road context',operationalAreas:'Operational areas',controlLines:'Control lines',divisions:'Divisions and sectors',stagingAreas:'Staging areas',bases:'Bases and helibases',resources:'Operational resources',assignments:'Assignments',locations:'Reported locations',stagedResources:'Staged resources',responseCoverageSurface:'Sampled road reachability',responseCoverageRoutes:'Road-routed response paths',responseFacilities:'Response facilities'
});
const layerGroups=Object.freeze([
  ['Incident',['incidentPoints','observedGeometry','forecastGeometry']],
  ['Observations',['thermalSupport','observations']],
  ['Environment',['weather','wind','terrain']],
  ['Operations',['operationalAreas','controlLines','divisions','stagingAreas','bases','resources','assignments','locations','stagedResources']],
  ['Response capability',['responseCoverageSurface','responseCoverageRoutes','responseFacilities']],
  ['Context',['basemapImagery','basemapLabels','contextAssets','roads']]
]);
const layerIcons=Object.freeze({basemapImagery:'map',basemapLabels:'layers',incidentPoints:'flame',observedGeometry:'map',thermalSupport:'flame',observations:'detect',weather:'cloud',wind:'wind',terrain:'map',forecastGeometry:'proof',contextAssets:'warning',roads:'map',operationalAreas:'map',controlLines:'sync',divisions:'layers',stagingAreas:'people',bases:'home',resources:'people',assignments:'file',locations:'detect',stagedResources:'people',responseCoverageSurface:'map',responseCoverageRoutes:'map',responseFacilities:'people'});

export const statusTone=stateTone;

export function vigiaStateLabel(input,{label=null,compact=false,title=''}={}){return stateLabel(input,{label:label??operatorText(input),compact,title});}
export function vigiaBadge(label,{tone='info',compact=false}={}){return`<span class="vigia-badge vigia-badge--${tone}${compact?' vigia-badge--compact':''}">${esc(label)}</span>`;}

export function vigiaSelect({id,label,value='ALL',options=[],iconName='filter',disabled=false,disabledReason='',openId=null,className=''}){
  const normalized=options.map(option=>typeof option==='string'?{value:option,label:operatorText(option)}:option).filter(option=>option&&option.value!==undefined),selected=normalized.find(option=>String(option.value)===String(value))??normalized[0]??{value:'',label:'Unavailable'},open=openId===id&&!disabled,listId=`vigia-select-${id}-list`,labelId=`vigia-select-${id}-label`;
  return`<div class="vigia-select ${open?'is-open':''} ${className}" data-vigia-select="${esc(id)}"><span class="sr-only" id="${esc(labelId)}">${esc(label)}</span><button type="button" class="vigia-select__trigger" data-action="select-toggle:${esc(id)}" data-vigia-select-trigger="${esc(id)}" role="combobox" aria-haspopup="listbox" aria-expanded="${open}" aria-controls="${esc(listId)}" aria-labelledby="${esc(labelId)}" ${disabled&&disabledReason?`title="${esc(disabledReason)}"`:''} ${disabled?'disabled':''}>${icon(iconName,15)}<span>${esc(selected.label)}</span>${selected.count!==undefined?`<small>${esc(selected.count)}</small>`:''}${icon('chevron',13)}</button>${open?`<div class="vigia-select__menu" id="${esc(listId)}" role="listbox" aria-labelledby="${esc(labelId)}">${normalized.map(option=>{const active=String(option.value)===String(selected.value);return`<button type="button" role="option" aria-selected="${active}" tabindex="${active?'0':'-1'}" data-select-value="${esc(String(option.value))}" data-action="select-option:${esc(id)}:${esc(encodeURIComponent(String(option.value)))}"><span>${esc(option.label)}</span>${option.count!==undefined?`<small>${esc(option.count)}</small>`:''}${active?icon('check',14):''}</button>`;}).join('')}</div>`:''}</div>`;
}

export function vigiaIncidentSelect({id='operation-incident',label='Incident',value='',incidents=[],openId=null,query='',inputKey='operation-incident-search',selectionAction='select-operation-incident'}){
  const selected=incidents.find(item=>incidentId(item)===String(value))??null,open=openId===id,normalized=String(query??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),matches=incidents.filter(item=>!normalized||`${incidentLabel(item)} ${incidentLocation(item)} ${incidentAssessment(item)} ${incidentId(item)}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(normalized)),selectedMatches=selected&&matches.includes(selected),visible=(selectedMatches?[selected,...matches.filter(item=>item!==selected)]:matches).slice(0,60),listId=`vigia-select-${id}-list`,labelId=`vigia-select-${id}-label`;
  return`<div class="vigia-select vigia-incident-select ${open?'is-open':''}" data-vigia-select="${esc(id)}"><span class="sr-only" id="${esc(labelId)}">${esc(label)}</span><button type="button" class="vigia-select__trigger" data-action="select-toggle:${esc(id)}" data-vigia-select-trigger="${esc(id)}" role="combobox" aria-haspopup="listbox" aria-expanded="${open}" aria-controls="${esc(listId)}" aria-labelledby="${esc(labelId)}">${icon('flame',15)}<span>${esc(selected?incidentLabel(selected):'Select incident')}</span>${icon('chevron',13)}</button>${open?`<div class="vigia-select__menu vigia-incident-select__menu"><label class="vigia-incident-select__search">${icon('search',14)}<span class="sr-only">Search incidents</span><input data-input="${esc(inputKey)}" type="search" value="${esc(query)}" placeholder="Search name, locality, or official ID" autocomplete="off"></label><div id="${esc(listId)}" role="listbox" aria-labelledby="${esc(labelId)}">${visible.length?visible.map(item=>{const identifier=incidentId(item),active=identifier===String(value),changed=incidentChangedAt(item);return`<button type="button" role="option" aria-selected="${active}" tabindex="${active?'0':'-1'}" data-action="${esc(selectionAction)}:${esc(identifier)}"><span><strong>${esc(incidentLabel(item))}</strong><small>${esc(incidentLocation(item))}${changed?` · ${esc(timeLabel(changed))}`:''}</small></span><em>${esc(operatorText(incidentAssessment(item)))}</em>${active?icon('check',14):''}</button>`;}).join(''):'<p class="vigia-select__empty">No authorized incidents match this search.</p>'}</div></div>`:''}</div>`;
}

const rows=value=>Array.isArray(value)?value:[];
const latestTime=(items)=>items.map(item=>item?.observedAt??item?.updatedAt??item?.at??item?.validAt??item?.issuedAt).filter(value=>Number.isFinite(Date.parse(value))).sort((first,second)=>Date.parse(second)-Date.parse(first))[0]??null;
export function relativeTimeLabel(input,baseline=Date.now()){const at=Date.parse(input??''),now=typeof baseline==='number'?baseline:Date.parse(baseline??'');if(!Number.isFinite(at)||!Number.isFinite(now))return'Freshness not reported';const minutes=Math.max(0,Math.round((now-at)/60_000));if(minutes<2)return'Updated just now';if(minutes<60)return`Updated ${minutes}m ago`;const hours=Math.round(minutes/60);if(hours<48)return`Updated ${hours}h ago`;return`Updated ${Math.round(hours/24)}d ago`;}
export function freshnessState(input,baseline=Date.now()){const at=Date.parse(input??''),now=typeof baseline==='number'?baseline:Date.parse(baseline??'');if(!Number.isFinite(at)||!Number.isFinite(now))return{state:'NO_RECENT_DATA',label:'No recent data',ageMs:null};const ageMs=Math.max(0,now-at),hours=ageMs/3_600_000;if(hours<.25)return{state:'LIVE',label:'Live',ageMs};if(hours<2)return{state:'FRESH',label:'Fresh',ageMs};if(hours<24)return{state:'AGING',label:'Aging',ageMs};return{state:'STALE',label:'Stale',ageMs};}
const layerState=(layer)=>{const state=String(layer?.state??'NOT_MEASURED').toUpperCase(),count=layer?.inventory?.returned??rows(layer?.value).length;if(!['READY','DEGRADED'].includes(state))return{kind:'unavailable',label:state==='NOT_MEASURED'?'Not measured':'Unavailable',count:0};if(count===0)return{kind:'empty',label:'No features',count:0};return{kind:'available',label:state==='DEGRADED'?'Source degraded':'Available',count};};

export function vigiaLayerPanel(scene,visibility={}){
  const layers=scene?.layers&&typeof scene.layers==='object'?scene.layers:{},sceneId=scene?.sceneId??'unavailable',currentness=scene?.currentness??{},declared=new Set(scene?.layerSet??Object.keys(layers));declared.add('basemapImagery');declared.add('basemapLabels');
  const synthetic={basemapImagery:{state:'NOT_MEASURED',authority:'MAP_RUNTIME_TRANSPORT',value:[],reason:'Tile transport health was not supplied to this canonical scene.'},basemapLabels:{state:'NOT_MEASURED',authority:'MAP_RUNTIME_TRANSPORT',value:[],reason:'Label-tile transport health was not supplied to this canonical scene.'}},rendered=new Set();
  const declaredNames=[...declared],availableCount=declaredNames.filter(name=>layerState(layers[name]??synthetic[name]).kind==='available').length;
  const groupHtml=layerGroups.map(([group,names])=>{const groupRows=names.filter(name=>declared.has(name)).map(name=>{rendered.add(name);const layer=layers[name]??synthetic[name],status=layerState(layer),enabled=name==='basemapLabels'?visibility[name]!==false:status.kind==='available'&&visibility[name]!==false,toggleable=name==='basemapLabels'||status.kind==='available'&&name!=='basemapImagery',fresh=latestTime(rows(layer?.value))??(name==='weather'||name==='wind'?currentness.weatherObservedAt:null)??currentness.generatedAt,reason=layer?.reason?operatorText(String(layer.reason).toUpperCase()):null;return{status,html:`<article class="vigia-layer-row vigia-layer-row--${status.kind}" data-layer-name="${esc(name)}" data-layer-state="${esc(layer?.state??'NOT_MEASURED')}"><i class="vigia-layer-row__icon">${icon(layerIcons[name]??'layers',15)}</i><span class="vigia-layer-row__copy"><strong>${esc(layerLabels[name]??operatorText(name))}</strong><small>${esc(status.kind==='unavailable'?(reason??'Not available for this incident'):`${status.count} ${status.count===1?'feature':'features'} · ${relativeTimeLabel(fresh)}`)}</small></span>${vigiaStateLabel(layer?.state??'NOT_MEASURED',{label:status.label,compact:true})}<button type="button" class="vigia-layer-switch" role="switch" aria-label="Toggle ${esc(layerLabels[name]??operatorText(name))}" aria-checked="${enabled}" data-action="map-layer-toggle:${esc(encodeURIComponent(name))}" ${toggleable?'':'disabled'}><span></span><em>${name==='basemapImagery'?'Base':enabled?'On':'Off'}</em></button></article>`};}).sort((a,b)=>({available:0,empty:1,unavailable:2}[a.status.kind]-{available:0,empty:1,unavailable:2}[b.status.kind])).map(item=>item.html).join('');return`<section class="vigia-layer-group"><header><h3>${esc(group)}</h3></header>${groupRows||`<p class="vigia-layer-group__empty">No ${esc(group.toLowerCase())} layers are declared for this scene.</p>`}</section>`;}).join('');
  const extra=Object.keys(layers).filter(name=>declared.has(name)&&!rendered.has(name)).map(name=>{const layer=layers[name],status=layerState(layer);return`<article class="vigia-layer-row vigia-layer-row--${status.kind}"><span class="vigia-layer-row__copy"><strong>${esc(layerLabels[name]??operatorText(name))}</strong><small>${esc(layer?.reason?operatorText(layer.reason):`${status.count} features`)}</small></span>${vigiaStateLabel(layer?.state,{label:status.label,compact:true})}</article>`;}).join('');
  const technical=declaredNames.flatMap(name=>{const layer=layers[name]??synthetic[name],fresh=latestTime(rows(layer?.value));return[[`${layerLabels[name]??name} authority`,layer?.authority],[`${layerLabels[name]??name} reason`,layer?.reason],[`${layerLabels[name]??name} count`,layer?.inventory?.returned??rows(layer?.value).length],[`${layerLabels[name]??name} timestamp`,fresh]];}).filter(([,value])=>value!==null&&value!==undefined&&value!=='');
  return`<div class="vigia-layer-panel" data-layer-scene="${esc(sceneId)}"><div class="vigia-layer-summary"><span><strong>${availableCount} of ${declaredNames.length} available</strong><small>${esc(operatorText(scene?.sceneType,{missing:'Map scene'}))}</small></span><span><strong>${esc(relativeTimeLabel(currentness.generatedAt))}</strong><small>${esc(currentness.generatedAt?timeLabel(currentness.generatedAt):'Exact scene time not reported')}</small></span></div><p class="overlay-intro">Available layers appear first in each operational group. Empty and unavailable products remain explicit without competing with active controls.</p>${groupHtml}${extra?`<section class="vigia-layer-group"><header><h3>Additional context</h3></header>${extra}</section>`:''}<details class="technical-details"><summary>Technical layer provenance</summary><dl><div><dt>Scene</dt><dd>${esc(sceneId)}</dd></div><div><dt>Scene type</dt><dd>${esc(scene?.sceneType??'Unavailable')}</dd></div><div><dt>Association</dt><dd>${esc(scene?.selectionAssociation?.state??'Not reported')}</dd></div><div><dt>Generated</dt><dd>${esc(currentness.generatedAt??'Not reported')}</dd></div>${technical.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl></details></div>`;
}

const measured=(value,suffix='')=>{const number=finiteNumberOrNull(value);return number===null?'Not reported':`${number.toLocaleString('en-US')}${suffix}`;};
const fact=(label,value)=>value===null||value===undefined||value===''?'':`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`;
export function vigiaArtifactInspector({layerName,layer,item=null,scene=null}){
  const values=rows(layer?.value),record=item??values[0]??null,recordProperties=record?.properties??record,label=layerLabels[layerName]??operatorText(layerName),observedAt=record?.observedAt??record?.updatedAt??record?.at??record?.validAt??recordProperties?.updatedAt??null,source=record?.platform??record?.source??record?.instrument??recordProperties?.source??layer?.authority??null,sourceLabel=typeof source==='string'&&/^[A-Z0-9-]{2,8}$/.test(source)?source:operatorText(source);
  let decision='This product is supporting context. It does not replace an admitted perimeter, forecast, or command decision.',facts='';
  if(layerName==='observations'){decision='Thermal detections can confirm observed heat at a time and location. They are not authoritative incident perimeter geometry.';facts=[fact('Platform',record?.platform??record?.source),fact('Instrument',record?.instrument),fact('Observed',observedAt?timeLabel(observedAt):null),fact('Fire radiative power',record?.frpMw===null||record?.frpMw===undefined?null:measured(record.frpMw,' MW')),fact('Brightness',record?.brightnessKelvin===null||record?.brightnessKelvin===undefined?null:measured(record.brightnessKelvin,' K')),fact('Location uncertainty',record?.geolocationUncertaintyM===null||record?.geolocationUncertaintyM===undefined?null:measured(record.geolocationUncertaintyM,' m'))].join('');}
  else if(layerName==='weather'||layerName==='wind'){decision='Use this observation to understand current environmental context. It is not a spread prediction and should be read with its observation time and source distance.';facts=[fact('Source',record?.source),fact('Observed',observedAt?timeLabel(observedAt):null),fact('Temperature',record?.temperatureC===null||record?.temperatureC===undefined?record?.temperatureF===null||record?.temperatureF===undefined?null:measured(record.temperatureF,' °F'):measured(record.temperatureC,' °C')),fact('Relative humidity',record?.humidityPercent===null||record?.humidityPercent===undefined?null:measured(record.humidityPercent,'%')),fact('Wind',record?.windSpeedKph===null||record?.windSpeedKph===undefined?record?.speedMph===null||record?.speedMph===undefined?null:measured(record.speedMph,' mph'):measured(record.windSpeedKph,' km/h')),fact('Direction',record?.windDirection??record?.bearingLabel??record?.windDirectionDeg),fact('Gust',record?.gustKph===null||record?.gustKph===undefined?record?.gustMph===null||record?.gustMph===undefined?null:measured(record.gustMph,' mph'):measured(record.gustKph,' km/h')),fact('Source distance',record?.distanceKm===null||record?.distanceKm===undefined?null:measured(record.distanceKm,' km'))].join('');}
  else if(layerName==='responseFacilities'){
    const properties=record?.properties??record??{},facilityId=properties.facilityId??record?.id,routeRecord=rows(scene?.layers?.responseCoverageRoutes?.value).find(row=>String(row?.properties?.facilityId??row?.facilityId??'')===String(facilityId??'')),route=routeRecord?.properties??routeRecord??{},association=scene?.selectionAssociation?.state??(scene?.selectedIncidentId?'SELECTED_INCIDENT':'NOT_REPORTED');
    decision='This is governed mapped response context for the selected incident. Road time is a routing estimate; mapped presence does not prove current capacity, dispatch, assignment, or arrival.';
    facts=[fact('Facility',properties.label),fact('Facility class',operatorText(properties.facilityKind)),fact('Incident association',operatorText(association)),fact('Mapped source',properties.source),fact('Source reference',properties.sourceReference),fact('Facility snapshot',properties.updatedAt?timeLabel(properties.updatedAt):'No current facility snapshot reported'),fact('Facility freshness',operatorText(properties.freshnessState)),fact('Road travel estimate',route.travelTimeMinutes!==null&&route.travelTimeMinutes!==undefined&&Number.isFinite(Number(route.travelTimeMinutes))?measured(route.travelTimeMinutes,' min'):'No governed road estimate'),fact('Route distance',route.routeDistanceKm!==null&&route.routeDistanceKm!==undefined&&Number.isFinite(Number(route.routeDistanceKm))?measured(route.routeDistanceKm,' km'):'Not reported'),fact('Route method',operatorText(route.routeMethod)),fact('Route checked',route.routeCheckedAt?timeLabel(route.routeCheckedAt):'Not reported'),fact('Route source',route.routeSource),fact('Routing confidence',operatorText(route.routeConfidenceState??properties.routeConfidenceState)),fact('Alternative route',operatorText(route.alternativeRouteState)),fact('Capacity availability',operatorText(properties.capacityAvailability)),fact('Capacity evidence',operatorText(properties.capacityState)),fact('Road closure impact',`${operatorText(route.roadClosureState)}${route.roadClosureReason?` · ${operatorText(route.roadClosureReason)}`:''}`),fact('Access constraints',`${operatorText(route.accessConstraintState)}${route.accessConstraintReason?` · ${operatorText(route.accessConstraintReason)}`:''}`),fact('Routing explanation',route.explanation)].join('');
  }
  else{facts=[fact('Source',source),fact('Observed',observedAt?timeLabel(observedAt):null),fact('Products returned',values.length),fact('Availability',operatorText(layer?.state)),fact('Reason',layer?.reason?operatorText(layer.reason):null)].join('');}
  return`<article class="vigia-artifact-inspector"><header><span>${vigiaStateLabel(layer?.state,{compact:true})}</span><p>${esc(relativeTimeLabel(observedAt??record?.properties?.updatedAt??scene?.currentness?.generatedAt))}</p></header><section><h3>Operational meaning</h3><p>${esc(decision)}</p></section>${facts?`<dl class="dialog-facts">${facts}</dl>`:''}<section><h3>Source and limits</h3><p>${esc(source?`Source: ${sourceLabel}.`:'Source was not reported for this product.')} ${esc(layer?.truthBoundary??(layer?.reason?operatorText(String(layer.reason).toUpperCase()):'No additional availability warning was returned.'))}</p></section><details class="technical-details"><summary>Technical provenance</summary><dl>${fact('Canonical layer',layerName)}${fact('Authority',layer?.authority)}${fact('Record ID',record?.id??record?.resourceId??record?.assetId??record?.properties?.facilityId)}${fact('Provider product',record?.provenance?.providerProductId)}${fact('Raw source product',record?.provenance?.rawSourceProductId)}${fact('Scene',scene?.sceneId)}</dl></details></article>`;
}
