import { finiteNumberOrNull } from './truth.js?v=2.1.0';

const CURRENT=new Set(['current','ready','healthy','operational']);
function sourceSummary(source){const state=String(source.state??'unknown').toLowerCase(),observedAt=source.raw?.latestSourceObservation??source.latestObservationAt??source.freshnessAt??null,lastSuccessAt=source.raw?.lastSuccessAt??source.lastSuccessAt??null;return{key:source.key,name:source.name,state:source.state,source:source.raw?.provider??source.raw?.origin??source.provider??source.key,lastPollAt:source.raw?.lastPollAt??source.lastPollAt??source.fetchedAt??null,lastSuccessAt,observedAt,effectiveAt:observedAt??lastSuccessAt,freshnessState:CURRENT.has(state)?'CURRENT':state==='stale'||state==='delayed'||state==='degraded'?'STALE':'UNAVAILABLE',availabilityState:CURRENT.has(state)?'AVAILABLE':state==='stale'||state==='delayed'||state==='degraded'?'LAST_KNOWN_ONLY':'UNAVAILABLE',errorPresent:source.errorPresent===true};}
function evidenceSummary(need){return{id:need.id,subjectId:need.subjectId??null,missingQuantity:need.missingQuantity??null,state:need.state??null,ownerId:need.ownerId??null,evidenceRequestId:need.evidenceRequestId??null,nextObservationAt:need.nextObservationAt??null,serviceLevel:need.serviceLevel??null};}
function requestSummary(request){return{id:request.id,evidenceNeedId:request.evidenceNeedId??null,state:request.state??null,ownerId:request.ownerId??null,dueAt:request.dueAt??null,escalation:request.escalation??null,actionDisposition:request.actionDisposition??null};}
function eventSummary(event){return{id:event.id,label:event.label??null,coordinate:event.coordinate??null,lastSeenAt:event.lastSeenAt??null,physicalOperationalState:event.physicalOperationalState??null,knowledgeState:event.knowledgeState??null,evidenceState:event.evidenceState??null,physicalFreshness:event.physicalState?.freshness??null,sourceFamilies:event.physicalSourceProfile?.families??[],missingQuantity:event.evidenceNeed?.missingQuantity??event.actionNeed?.missingQuantity??event.actionNeed?.kind??null};}
const countOrNull=(explicit,rows)=>finiteNumberOrNull(explicit)??(Array.isArray(rows)?rows.length:null);
function fieldnetSummary(fieldnet,dependency={}){if(!fieldnet)return{state:'UNAVAILABLE',source:'central_fieldnet',observedAt:null,lastSuccessAt:dependency?.lastSuccessAt??null,freshnessState:'UNAVAILABLE',availabilityState:'UNAVAILABLE'};const current=dependency?.state?dependency.state==='READY':CURRENT.has(String(fieldnet.state??fieldnet.status??'').toLowerCase());return{state:current?(fieldnet.state??fieldnet.status??'UNKNOWN'):'STALE',source:'central_fieldnet',cursor:fieldnet.cursor??null,observedAt:fieldnet.updatedAt??fieldnet.generatedAt??null,lastSuccessAt:dependency?.lastSuccessAt??fieldnet.updatedAt??fieldnet.generatedAt??null,freshnessState:current?'CURRENT':'STALE',availabilityState:current?'AVAILABLE':'LAST_KNOWN_ONLY',persistedMutations:countOrNull(fieldnet.persistedMutations,fieldnet.mutations),conflicts:countOrNull(null,fieldnet.conflicts),tasks:countOrNull(null,fieldnet.tasks),nodes:countOrNull(null,fieldnet.nodes??fieldnet.global?.nodes)};}
function optionalProjection(value,dependency,source,createdAt){const present=value!==null&&value!==undefined,current=present&&dependency?.state==='READY',observedAt=dependency?.lastSuccessAt??null,summary={source,observedAt,effectiveAt:observedAt,lastSuccessAt:dependency?.lastSuccessAt??null,freshnessState:current?'CURRENT':present?'STALE':'UNAVAILABLE',availabilityState:current?'AVAILABLE':present?'LAST_KNOWN_ONLY':'UNAVAILABLE',value:present?value:null,exportedAt:createdAt};return{current:current?summary:null,stale:present&&!current?summary:null,unavailable:!present?summary:null};}

export function buildIncidentBrief({event,operations=null,needs=[],requests=[],sources=[],changes=[],generatedAt=new Date().toISOString()}){
  if(!event)throw new Error('incident_brief_event_required');
  const eventNeeds=needs.filter(need=>String(need.subjectId??'')===String(event.id)||String(need.subjectId??'')===String(event.findingId??''));
  const needIds=new Set(eventNeeds.map(need=>need.id));
  const eventRequests=requests.filter(request=>needIds.has(request.evidenceNeedId)||String(request.targetId??'').endsWith(String(event.id)));
  const observations=event.observations??event.recentObservations??[];
  return{schemaVersion:'vigia.deterministic-incident-brief.v1',generatedAt,qualification:'Deterministic projection of canonical and explicitly unavailable state; no AI narrative.',incident:eventSummary(event),now:event.physicalOperationalState??event.knowledgeState??'UNKNOWN',next:eventNeeds[0]?.missingQuantity??event.actionNeed?.kind??'No governed next action returned',why:event.candidateAssessment?.conclusion??'No canonical assessment conclusion returned.',unknowns:[...new Set([eventNeeds[0]?.missingQuantity,event.actionNeed?.kind,!operations?'INCIDENT_COMMAND_NOT_LINKED':null].filter(Boolean))],contradictions:event.contradictions??event.evidenceContradictions??[],evidence:{observations:observations.slice(0,100).map(item=>({id:item.id??null,source:item.source??item.sourceFamily??null,instrument:item.instrument??item.satellite??null,observedAt:item.observedAt??item.at??null,provenance:item.provenance??null})),needs:eventNeeds.map(evidenceSummary),requests:eventRequests.map(requestSummary)},sourceHealth:sources.map(sourceSummary),command:operations?{state:'LINKED',incidentId:operations.incidentId??operations.id??null,objectives:operations.objectives??[],assignments:operations.assignments??[],maydays:operations.maydays??operations.mayday??null,accountability:operations.accountability??null}:{state:'NOT CONFIGURED'},whatChanged:changes.filter(item=>!item.entityId||String(item.entityId)===String(event.id)).slice(-20)};
}

export function buildHandoffSnapshot({events=[],selectedEvent=null,needs=[],requests=[],sources=[],findings=[],fieldnet=null,changes=[],operationsStatus=null,dependencies={},roster=null,resources=null,createdAt=new Date().toISOString()}){
  const sourceRows=sources.map(sourceSummary),currentSources=sourceRows.filter(item=>item.freshnessState==='CURRENT'),staleSources=sourceRows.filter(item=>item.freshnessState!=='CURRENT'),fieldnetRow=fieldnetSummary(fieldnet,dependencies.fieldnet),rosterState=optionalProjection(roster,dependencies.operationsRoster,'canonical_operations_roster',createdAt),resourceState=optionalProjection(resources,dependencies.operationsAssets,'canonical_operations_assets',createdAt);
  return{schemaVersion:'vigia.shift-handoff-snapshot.v3',createdAt,qualification:'Canonical current truth is separated from timestamped stale or unavailable optional context; no last-known value is exported as current.',activeIncidents:events.map(eventSummary),selectedIncident:selectedEvent?eventSummary(selectedEvent):null,unknowns:needs.map(evidenceSummary),evidenceWork:requests.map(requestSummary),currentContext:{sources:currentSources,fieldnet:fieldnetRow.freshnessState==='CURRENT'?fieldnetRow:null,roster:rosterState.current,resources:resourceState.current},staleContext:{sources:staleSources,fieldnet:fieldnetRow.freshnessState==='STALE'?fieldnetRow:null,roster:rosterState.stale,resources:resourceState.stale},unavailableContext:{fieldnet:fieldnetRow.freshnessState==='UNAVAILABLE'?fieldnetRow:null,roster:rosterState.unavailable,resources:resourceState.unavailable},degradedSources:staleSources,preventionReview:findings.map(finding=>({findingId:finding.findingId??finding.id,place:finding.place??finding.municipality??null,measurementState:(finding.reviewSummary?.count??0)>0?'REVIEW RECORDED':'MEASUREMENT REQUIRED',evidenceNeedId:finding.evidenceNeedId??null,evidenceRequestId:finding.evidenceRequestId??null})),fieldnet:fieldnetRow.freshnessState==='CURRENT'?fieldnetRow:{state:'UNAVAILABLE',source:'central_fieldnet',observedAt:null,lastSuccessAt:fieldnetRow.lastSuccessAt,freshnessState:'UNAVAILABLE',availabilityState:'UNAVAILABLE'},decisionChanges:changes.slice(-30),auditHead:operationsStatus?.metrics?.audit??operationsStatus?.audit??null};
}

function sortValue(value){if(Array.isArray(value))return value.map(sortValue);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,sortValue(value[key])]));return value;}
export function canonicalJson(value){return JSON.stringify(sortValue(value));}
export async function sha256(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:canonicalJson(value)),hash=await crypto.subtle.digest('SHA-256',bytes);return`sha256:${[...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}`;}
export function safeExportName(value,fallback='vigia-export'){const safe=String(value??'').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/\.+/g,'.').replace(/^[.-]+|[.-]+$/g,'').slice(0,100);return safe||fallback;}
