import { referenceMapUnavailable } from './referenceMapUnavailable.js';
const context='<section class="incident-context-switcher panel-surface"><strong>Select an incident to begin</strong><button class="button button--secondary" data-action="go-incidents">Select incident</button></section>';
export function unselectedOperations(){
 return `<section class="operations-route final-white-route">${context}<section class="executive-section" id="operations-action-board"><header><h2>Task board</h2></header><div class="operation-lanes operation-lanes--executive">${['Source Resolution','Response Operations','Protect / Recover'].map(label=>`<button class="operation-lane" disabled>${label}</button>`).join('')}</div><p class="empty-truth-state">Tasks are unavailable until an incident is selected.</p></section><section class="executive-section" id="operations-geography"><header><h2>Operational map</h2></header><div class="operations-map__canvas">${referenceMapUnavailable('Operational map',[])}</div></section></section>`;
}
export function unselectedIntelligence(){
 const brief=[['Now','No incident selected'],['Next','Select a record to check'],['Watch','Source conditions unavailable'],['Uncertainty','Evidence has not been loaded'],['Decision','No recommendation available']];
 return `<section class="intelligence-route final-white-route">${context}<section class="intelligence-reading intelligence-reading--brief panel-surface" data-vqa="intelligence.brief"><header><h2>Intelligence Brief</h2></header><div class="intelligence-brief-flow">${brief.map(([label,text])=>`<section class="intelligence-reading__block"><span>${label}</span><strong>${text}</strong></section>`).join('')}</div></section><section class="intelligence-map panel-surface"><header><h2>Evidence map</h2></header><div class="intelligence-map__canvas">${referenceMapUnavailable('Evidence map',[])}</div></section><section class="executive-section" id="intelligence-geospatial"><header><h2>Evidence and intelligence assessment</h2></header><p class="empty-truth-state">No incident evidence has been loaded.</p></section></section>`;
}
