export const PROVIDER_STATUSES=Object.freeze(['UNCONFIGURED','CREDENTIALS_REQUIRED','READY','LIVE','DEGRADED','RATE_LIMITED','UNAVAILABLE','SCHEMA_DRIFT','QUARANTINED','DISABLED']);
export const PRODUCT_MATURITIES=Object.freeze(['OPERATIONAL','PRE_OPERATIONAL','PROVISIONAL','DEMONSTRATIONAL','EXPERIMENTAL','RETIRED']);
export const DATA_LAYERS=Object.freeze(['BRONZE','SILVER','GOLD']);
export const SOURCE_CLASSES=Object.freeze(['PHYSICAL','OFFICIAL','DERIVED','WEATHER','CONTEXT','REPORT']);
export const OBSERVATION_OPPORTUNITY_STATES=Object.freeze(['VALID_POSITIVE','VALID_NEGATIVE','OBSTRUCTED','NOT_COVERED','PRODUCT_UNAVAILABLE','PROVIDER_UNAVAILABLE','NOT_YET_AVAILABLE','UNKNOWN']);
export const LABEL_TIERS=Object.freeze(['L0_UNVERIFIED_REPORT','L1_SINGLE_PHYSICAL','L2_MULTI_FAMILY_PHYSICAL','L3_OFFICIAL_INCIDENT','L4_REVIEWED_PERIMETER','L5_RETROSPECTIVE_SCIENCE']);

export function enumValue(value,allowed,code){const normalized=String(value??'').toUpperCase();if(!allowed.includes(normalized))throw new Error(code);return normalized;}
