import { immutable,semanticHash } from '../intelligence/shared.mjs';
import { PRODUCT_MATURITIES,PROVIDER_STATUSES } from './constants.mjs';

function pairs(value,output=[]){if(!Array.isArray(value))return output;if(value.length>=2&&value.slice(0,2).every(Number.isFinite)){output.push(value);return output;}for(const item of value)pairs(item,output);return output;}
function bboxOf(geometry){if(Array.isArray(geometry)&&geometry.length===4)return geometry.map(Number);const points=pairs(geometry?.type==='Point'?geometry.coordinates:geometry?.coordinates);if(!points.length)return null;return[Math.min(...points.map((p)=>p[0])),Math.min(...points.map((p)=>p[1])),Math.max(...points.map((p)=>p[0])),Math.max(...points.map((p)=>p[1]))];}
function intersects(a,b){return Boolean(a&&b&&a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1]);}
function overlaps(a,b){return(!a?.to||a.to>=b.from)&&(!a?.from||a.from<=b.to);}
export function createSourceCoverageIndex(entries=[]){
  const normalized=entries.map((item)=>({sourceId:String(item.sourceId),productId:String(item.productId),bbox:bboxOf(item.bbox),temporalCoverage:structuredClone(item.temporalCoverage),cadenceSeconds:Number(item.cadenceSeconds),expectedLatencySeconds:Number(item.expectedLatencySeconds),sourceClass:String(item.sourceClass),maturity:String(item.maturity),lineage:structuredClone(item.lineage),contractRoles:[...(item.contractRoles??[])].sort()})).sort((a,b)=>`${a.sourceId}:${a.productId}`.localeCompare(`${b.sourceId}:${b.productId}`));
  if(normalized.some((item)=>!item.sourceId||!item.productId||!item.bbox||!Number.isFinite(item.cadenceSeconds)))throw new Error('invalid_source_coverage_entry');const core={schemaVersion:'vigia.source-coverage-index.v1',entries:normalized};return immutable({...core,fingerprint:semanticHash('source-coverage-index',core)});
}
export function getEligibleSources({index,geometry,timeWindow,evidenceNeed={},health={},credentials={}}={}){
  const target=bboxOf(geometry),now=Date.now();return(index?.entries??[]).map((entry)=>{const status=health[entry.sourceId]?.status??'UNCONFIGURED',reasons=[];if(!intersects(entry.bbox,target))reasons.push('OUTSIDE_GEOGRAPHIC_COVERAGE');if(!overlaps(entry.temporalCoverage,timeWindow))reasons.push('OUTSIDE_TEMPORAL_COVERAGE');if(!PROVIDER_STATUSES.includes(status)||!['READY','LIVE','DEGRADED'].includes(status))reasons.push(`PROVIDER_${status}`);if(credentials[entry.sourceId]===false)reasons.push('CREDENTIALS_UNAVAILABLE');if(!PRODUCT_MATURITIES.includes(entry.maturity)||['EXPERIMENTAL','RETIRED'].includes(entry.maturity))reasons.push(`MATURITY_${entry.maturity}`);if(evidenceNeed.roles?.length&&!entry.contractRoles.some((role)=>evidenceNeed.roles.includes(role)))reasons.push('EVIDENCE_ROLE_MISMATCH');if(evidenceNeed.excludeOriginalObservations?.includes(entry.lineage?.originalObservation))reasons.push('CAUSAL_OBSERVATION_ALREADY_PRESENT');const nextExpectedAt=health[entry.sourceId]?.lastSuccessAt?new Date(Date.parse(health[entry.sourceId].lastSuccessAt)+entry.cadenceSeconds*1000).toISOString():null;return{...entry,status,eligible:reasons.length===0,reasons,nextExpectedAt,overdue:Boolean(nextExpectedAt&&Date.parse(nextExpectedAt)<now)};}).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||a.expectedLatencySeconds-b.expectedLatencySeconds||a.sourceId.localeCompare(b.sourceId));
}
