import {icon,brand} from './icons.js';
import {e,button} from './html.js';
import {routeURL,incidentFor} from '../data/model.js';
export const ROUTES=[
 ['command-overview','Command Overview','Portugal wildfire situational picture','home'],
 ['incidents','Incidents','Search, filter and explore all records.','file'],
 ['incident-detail','Incident Detail','Understand the incident and its latest information.','map'],
 ['intelligence','Intelligence','Check the evidence. See what still needs confirming.','target'],
 ['operations','Operations','Assign work. Track progress. Resolve blockers.','target'],
 ['reports-analytics','Reports & Analytics','Measured results and trends','chart'],
 ['national-awareness','National Awareness','Incidents, context and coverage across Portugal.','globe']
];
export function shell(route,state,content){const r=ROUTES.find(x=>x[0]===route);const title=route==='incident-detail'?incidentFor(state)?.name||'Incident Detail':route==='reports-analytics'?'Reports & Analytics':r?.[1]||'Page not found';
 const banner=state.variant==='stale'?'<strong>Last-known information.</strong><p>This preview snapshot is stale. Source timestamps have not been refreshed.</p>':state.variant==='limited'?'<strong>Information unavailable.</strong><p>This is the limited-data test. Missing information is never shown as zero.</p>':state.variant==='readonly'?'<strong>Read-only preview.</strong><p>You can inspect records. Task changes are disabled.</p>':'';
 return `<div class="mobile-shade" data-action="close-menu"></div><aside class="vg-sidebar" aria-label="Primary navigation"><a class="brand" href="#/command-overview" aria-label="Vigia home">${brand()}</a>${button('Close navigation','close-menu',{ico:'close',tone:'icon-button mobile-close'})}<nav class="vg-nav">${ROUTES.map(([path,label,,ico])=>`<a href="${routeURL(path,state.selected)}" class="nav-link ${route===path?'active':''}" ${route===path?'aria-current="page"':''}>${icon(ico)}<span>${label}</span></a>`).join('')}</nav><div class="vg-sidebar-bottom"><div class="demo-status">${icon('shield')}<span>Design preview<strong>No live emergency data</strong></span></div><div class="sidebar-user"><span class="avatar">MA</span><span><strong>Miguel Almeida</strong><small>Local review environment</small><small>Portugal mainland</small></span></div></div></aside>
 <div class="vg-main"><header class="vg-header"><div class="vg-header-left">${button('Open navigation','open-menu',{ico:'menu',tone:'icon-button mobile-menu'})}<div><h1>${e(title)}</h1><p>${e(r?.[2]||'Return to the overview.')}</p></div></div><div class="header-right"><label class="preview-control"><span class="demo-pill">DEMO</span><span class="sr-only">Preview data state</span><select data-control="variant" aria-label="Preview data state">${[['populated','Populated'],['limited','Limited data'],['stale','Last known'],['readonly','Read only']].map(([v,l])=>`<option value="${v}" ${state.variant===v?'selected':''}>${l}</option>`).join('')}</select></label><span class="header-sep"></span><div class="header-context">Portugal mainland<strong>07 Sept 2026</strong><strong>11:14 UTC</strong></div>${button('Refresh local preview','refresh-preview',{ico:'refresh',tone:'icon-button'})}</div></header><main class="vg-content" id="page-content" tabindex="-1">${banner?`<div class="state-banner">${icon('info')}<div>${banner}</div></div>`:''}${content}</main><footer class="vg-page-footer"><span>VIGIA · Interactive design preview · All incident records are fictional.</span><span>Reference map imagery · Not for navigation ${button('Reset preview','reset-preview',{tone:'small-btn'})}</span></footer></div>`;
}
