import {openDialog,closeDialog,toast} from './ui/dialog.js';
import {e,button,link,kv,badge} from './ui/html.js';
import {mapView,initMaps,changeMapZoom} from './ui/map.js';
import {BASE_INCIDENTS,QUESTIONS,REGIONS} from './data/fixtures.js';
import {incidentFor,addVerificationTask,isReadonly,timeLabel} from './data/model.js';
import {createTaskActions} from './task-actions.js';
import {createReviewActions} from './review-actions.js';
export function createActions(api){
 function expand(kind='local') {const d=openDialog(kind==='national'?'Portugal · illustrative map':'Incident · illustrative map',mapView({kind,id:'full-map',title:incidentFor(api.state)?.name||'',height:620,limited:api.state.variant==='limited',region:api.ui.region,selectRegions:kind==='national'}),{wide:true});initMaps(d);}
 function questions(id){const q=QUESTIONS.find(q=>q.id===id)||QUESTIONS[0];openDialog(q.title,`<p>${e(q.body)}</p><div class="notice">${e(q.context)}</div><dl>${kv('Would resolve this',q.resolves)}${kv('Expected information',q.source)}${kv('Next check',q.next)}</dl><p class="small">No public message is sent. The action opens or creates a task in this local preview.</p><div class="dialog-actions">${button('View source evidence','evidence-library')}${button('Request verification','request-verification',{tone:'primary',extra:`data-id="${q.id}"`,disabled:isReadonly(api.state)})}</div>`);}
 return {
 ...createTaskActions(api),...createReviewActions(api),
 navigate(el){api.navigate(el.dataset.route);},
 'open-menu'(){document.querySelector('.vg-sidebar').inert=false;document.querySelector('.vg-sidebar').classList.add('menu-open');document.querySelector('.mobile-shade').classList.add('open');document.querySelector('.vg-main').inert=true;document.body.style.overflow='hidden';document.querySelector('.mobile-close')?.focus();},
 'close-menu'(){document.querySelector('.vg-sidebar').classList.remove('menu-open');document.querySelector('.vg-sidebar').inert=innerWidth<=760;document.querySelector('.mobile-shade').classList.remove('open');document.querySelector('.vg-main').inert=false;document.body.style.overflow='';document.querySelector('.mobile-menu')?.focus();},
 'close-dialog':closeDialog,
 'refresh-preview'(){api.render();toast('Local preview refreshed. Sample source timestamps are unchanged.');},
 'reset-preview'(){openDialog('Reset local preview?',`<p>This clears only this preview’s saved task changes and returns to the original sample data.</p><p>No Vigia backend or repository files are affected.</p><div class="dialog-actions">${button('Cancel','close-dialog')}${button('Reset preview','confirm-reset',{tone:'primary'})}</div>`);},
 'confirm-reset'(){api.persist(api.provider.reset());api.ui.taskTab='all';api.ui.taskId=null;api.ui.page=1;closeDialog();api.navigate('command-overview');api.render();toast('Preview reset.');},
 'open-incident'(el){api.persist({...api.state,selected:el.dataset.id});api.navigate('incident-detail',el.dataset.id);},
 'select-incident'(el){api.persist({...api.state,selected:el.dataset.id});api.render();document.querySelector(`[data-action="select-incident"][data-id="${CSS.escape(el.dataset.id)}"]`)?.focus({preventScroll:true});if(window.innerWidth<570)document.querySelector('.incident-preview-panel')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});},
 'choose-incident'(){openDialog('Choose an incident',`<p>Select a fictional record. The incident stays selected across Detail, Intelligence, and Operations.</p><div class="rows">${BASE_INCIDENTS.map(i=>`<button class="incident-row" data-action="choose-record" data-id="${i.id}"><span class="row-main"><strong>${e(i.name)}</strong><small>${e(i.region)} · ${e(i.type)}</small></span>${badge(i.status==='confirmed'?'Exercise confirmed':'Needs review',i.status==='confirmed'?'green':'amber')}</button>`).join('')}</div>`);},
 'choose-record'(el){api.persist({...api.state,selected:el.dataset.id});closeDialog();api.navigate(api.ui.route,el.dataset.id);},
 page(el){api.ui.page=Number(el.dataset.page);api.render();},
 'clear-search'(){api.ui.incidentFilters.search='';api.ui.page=1;api.render();document.getElementById('incident-search')?.focus();},
 'reset-filters'(){api.ui.incidentFilters={search:'',status:'all',type:'all',priority:'all',region:'all'};api.ui.page=1;api.render();},
 'map-zoom'(el){const root=el.closest('.map-root');changeMapZoom(root,Number(el.dataset.delta));},
 'map-info'(el){openDialog('About this preview map','<p>The backdrop is cropped map imagery from your supplied design references. It is illustrative, not a licensed live tile feed or a geographically authoritative incident map.</p><p>Zoom and drag work locally. Some symbols and place labels are part of the reference raster. Production integration must replace this adapter with the actual mapping service.</p><div class="notice">Not for navigation, evacuation, or any real emergency decision.</div>');},
 'expand-map'(el){expand(el.dataset.kind);},
 'national-fullscreen'(){expand('national');},
 'select-region'(el){api.ui.region=el.dataset.region;const d=document.getElementById('inspector');if(d.open)closeDialog();api.render();},
 'reset-national'(){api.ui.region='Norte';api.ui.nationalLayer='incidents';api.render();toast('Portugal regional view reset.');},
 'regional-incidents'(){api.ui.incidentFilters={search:'',status:'all',type:'all',priority:'all',region:api.ui.region};api.ui.page=1;api.navigate('incidents',null,{region:api.ui.region});},
 question(el){questions(el.dataset.id);},
 'request-verification'(el){const q=QUESTIONS.find(x=>x.id===el.dataset.id);if(!q)throw new Error('Question not found.');const result=addVerificationTask(api.state,q);api.persist(result.state);api.ui.taskId=result.task.id;api.ui.taskTab='all';closeDialog();api.navigate('operations');toast(result.created?'Verification task created locally.':'Existing verification task opened. No duplicate was created.');},
 source(el){const records=[['VIIRS (NOAA-20)','Satellite heat observation','16 Aug 2026, 15:49 UTC','Not official confirmation'],['MODIS','Satellite heat observation','16 Aug 2026, 15:50 UTC','Independence not assessed'],['IPMA','Regional weather context','7 Sept 2026, 09:00 UTC','Context, not a spread forecast']];const r=records[Number(el.dataset.source)]||records[0];openDialog(r[0],`<p>Illustrative source record for the interface demonstration.</p><dl>${kv('Type',r[1])}${kv('Observation time',r[2])}${kv('Qualification',r[3])}${kv('Selected incident',incidentFor(api.state)?.name||'Not selected')}</dl><div class="notice">This preview has not fetched or verified a current observation from this provider.</div>`);},
 'evidence-library'(){openDialog('Source evidence',`<p>Inspect the illustrative source records. Observations, context, and official confirmation remain distinct.</p><div class="rows">${['VIIRS (NOAA-20)','MODIS','IPMA weather'].map((s,n)=>`<div class="row"><span class="row-main"><strong>${e(s)}</strong><p>Illustrative data · not a current live feed</p></span>${button('Inspect','source',{tone:'small-btn',extra:`data-source="${n}"`})}</div>`).join('')}</div>`);},
 'collection-plan'(){openDialog('What would resolve the questions?',`<div class="rows">${QUESTIONS.map(q=>`<div class="row"><div class="row-main"><h3>${e(q.short)}</h3><p>${e(q.resolves)}</p><small>${e(q.next)}</small></div>${button('Inspect','question',{tone:'small-btn',extra:`data-id="${q.id}"`})}</div>`).join('')}</div><p class="small" style="margin-top:18px">Requests are local preview tasks; no authority is contacted.</p>`);},
 activity(){openDialog('Recent activity',`<p>Events in the local demonstration only.</p><div class="rows">${api.state.activity.slice(0,25).map(a=>`<div class="row"><span class="small muted">${e(a.time)}</span><div class="row-main"><h3>${e(a.title)}</h3><p>${e(a.actor)}</p></div></div>`).join('')}</div>`);},
 'incident-history'(){const i=incidentFor(api.state);openDialog('Incident timeline',`<p>${e(i?.name)}</p><dl>${kv('First observation',i?timeLabel(i.observedAt):'Unavailable')}${kv('Current qualification',i?.verified?'Confirmed within the fictional exercise':'Needs independent confirmation')}${kv('Source check','Scheduled in the sample workflow')}</dl><p>Source-check completion does not automatically confirm a fire.</p>`);},
 'system-info'(){openDialog('Preview environment','<p>This frontend runs locally with no external API calls, credentials, cloud services, or model usage.</p><dl>'+kv('Incident records','Fictional demonstration data')+kv('Task changes','Saved only in this browser')+kv('Map imagery','Cropped visual-reference assets')+kv('Live emergency capability','Not connected')+'</dl><p>Use the header selector to test populated, limited-data, stale, and read-only states.</p>');}
 };
}
