import {openDialog,toast} from './ui/dialog.js';
import {e,button,kv} from './ui/html.js';
import {PERIODS} from './data/fixtures.js';
import {csv,isLimited} from './data/model.js';
export function createReviewActions(api){return {
 'report-tab'(el){api.ui.reportTab=el.dataset.tab;api.navigate('reports-analytics',null,{view:api.ui.reportTab});},
 compare(){api.ui.compare=!api.ui.compare;api.render();toast(api.ui.compare?'Illustrative period comparison enabled.':'Period comparison disabled.');},
 'export-report'(){const p=PERIODS[api.ui.period],limited=isLimited(api.state);const rows=[['VIGIA DESIGN PREVIEW — FICTIONAL DATA'],['Report view',api.ui.reportTab],['Period',p.label],['Data mode',api.state.variant],['Live emergency data','None'],['Metric','Illustrative value'],['Reviewed',limited?'Unavailable':p.reviewed],['Resolved',limited?'Unavailable':p.resolved],['Open',limited?'Unavailable':p.open],['Map render seconds',limited?'Not measured':p.mapLast],['API p95 ms',limited?'Not measured':p.apiLast],['Live outcomes','Not measured']];const url=URL.createObjectURL(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`vigia-DEMO-${api.ui.reportTab}-${api.ui.period}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Demonstration report exported.');},
 'report-records'(){const p=PERIODS[api.ui.period];openDialog('Underlying sample records',`<p>${p.reviewed} illustrative record reviews in ${e(p.label.toLowerCase())}. These are not live incident outcomes.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Period</th><th>Reviews</th></tr></thead><tbody>${p.series.map((n,i)=>`<tr><td>${e(p.labels[i])}</td><td>${n}</td></tr>`).join('')}</tbody></table></div>`);},
 'category-detail'(el){const row=PERIODS[api.ui.period].categories.find(r=>r[0]===el.dataset.name);openDialog(el.dataset.name,`<p>${row?.[1]??'No'} sample reviews are associated with this category in the selected period.</p><p>Categories are illustrative and mutually exclusive in this dataset. They are not measured reasons for real operator intervention.</p>`);},
 'category-definitions'(){openDialog('Category definitions','<dl>'+kv('Official confirmation','Review waiting for an attributable authority update.')+kv('Independent observation','Review requiring an independent, relevant observation.')+kv('Incident classification','Review of the observed event type.')+'</dl><p>These are fictional review categories, not a deployed taxonomy.</p>');},
 'outcome-requirements'(){openDialog('What an outcome needs','<p>A reviewed, time-stamped result linked to a recorded action and its intended effect.</p><dl>'+kv('Action','What was done, by whom, and when.')+kv('Observation','What was actually observed after the action.')+kv('Review','Whether the observation supports the intended result.')+'</dl><div class="notice">Task completion alone does not establish that a person was protected or a fire was contained.</div>');},
 'exercise-history'(){openDialog('Exercises are separate','<p>This build contains fictional interaction scenarios only.</p><p>There is no real exercise certification, no measured emergency outcome, and no operational deployment behind these sample screens.</p>');},
 'quality-definition'(el){openDialog(el.dataset.name,`<p>This dimension is presented independently. It must not be used to imply overall incident confidence or public safety.</p><p>The denominator is the eligible, successfully returned records. Failed data retrieval must remain unavailable, not zero.</p>`);}
 };}
