import {localId} from './data/id.js';
import {openDialog,closeDialog,toast} from './ui/dialog.js';
import {e,button,select,kv} from './ui/html.js';
import {tasksFor,updateTask,isReadonly,incidentFor} from './data/model.js';
import {OWNERS} from './data/fixtures.js';
export function createTaskActions(api){
 const active=()=>{const t=tasksFor(api.state)?.find(t=>t.id===api.ui.taskId);if(!t)throw new Error('Select a task first.');return t;};
 const commit=(next,title)=>{api.persist({...next,activity:[{id:'a-'+localId(),time:'11:14',title,actor:'Local operator · demo',type:'human'},...next.activity]});api.render();};
 return {
 'task-tab'(el){api.ui.taskTab=el.dataset.tab;api.ui.taskId=null;api.render();},
 'select-task'(el){api.ui.taskId=el.dataset.id;api.render();document.querySelector(`[data-action="select-task"][data-id="${CSS.escape(el.dataset.id)}"]`)?.focus({preventScroll:true});},
 'assign-owner'(){const t=active(),owner=document.querySelector('[data-control="task-owner"]')?.value;if(!OWNERS.includes(owner))throw new Error('Choose a valid owner.');commit(updateTask(api.state,t.id,{owner}),`${t.title}: owner changed to ${owner}`);toast('Owner updated in this local preview.');},
 'save-note'(){const t=active(),note=document.getElementById('task-note')?.value.trim();if(!note)throw new Error('Write a note before saving.');if(note.length>500)throw new Error('Keep notes under 500 characters.');commit(updateTask(api.state,t.id,{notes:[...t.notes,note]}),'A task note was saved');toast('Note saved locally.');},
 'task-transition'(el){const t=active(),status=el.dataset.status;if(isReadonly(api.state))throw new Error('Read-only preview. Task changes are disabled.');if(status==='completed'){openDialog('Complete this task?',`<p><strong>${e(t.title)}</strong></p><p>This changes a local demonstration task only. It does not confirm the incident, dispatch a resource, or notify an authority.</p><div class="dialog-actions">${button('Cancel','close-dialog')}${button('Complete demo task','confirm-task-complete',{tone:'primary',extra:`data-id="${e(t.id)}"`})}</div>`);return;}commit(updateTask(api.state,t.id,{status}),`${t.title}: moved to ${status==='progress'?'in progress':status}`);toast('Task updated in the local preview.');},
 'confirm-task-complete'(el){commit(updateTask(api.state,el.dataset.id,{status:'completed'}),'A demo task was completed');closeDialog();toast('Demo task completed. Incident verification is unchanged.');},
 'task-more'(){const t=active();openDialog('Task actions',`<p>${e(t.title)}</p><dl>${kv('Owner',t.owner)}${kv('Status',t.status)}${kv('Saved notes',t.notes.length)}</dl>${t.notes.length?`<ul>${t.notes.map(n=>`<li>${e(n)}</li>`).join('')}</ul>`:''}<div class="dialog-actions">${button('Wait for source','set-task-waiting',{extra:`data-id="${e(t.id)}"`,disabled:isReadonly(api.state)})}${button('Inspect evidence','task-evidence',{tone:'soft-blue',extra:`data-question="${e(t.question)}"`})}</div>`);},
 'set-task-waiting'(el){commit(updateTask(api.state,el.dataset.id,{status:'waiting'}),'A task is waiting on a source');closeDialog();toast('Task marked as waiting.');},
 'task-evidence'(el){closeDialog();api.navigate('intelligence',api.state.selected,{question:el.dataset.question});},
 'new-task'(){if(isReadonly(api.state))throw new Error('This view is read-only.');openDialog('Create a demo task',`<p>The task is saved in this browser only.</p><label for="new-task-title">Task title</label><input id="new-task-title" maxlength="100" placeholder="Describe the next action" autocomplete="off"><label for="new-task-reason" style="margin-top:15px">Why it matters</label><textarea id="new-task-reason" maxlength="250" placeholder="One short sentence"></textarea><div class="form-error" id="new-task-error" role="alert"></div><div class="dialog-actions">${button('Cancel','close-dialog')}${button('Create task','save-new-task',{tone:'primary',ico:'plus'})}</div>`);document.getElementById('new-task-title').focus();},
 'save-new-task'(){if(isReadonly(api.state))throw new Error('This view is read-only.');const title=document.getElementById('new-task-title').value.trim(),summary=document.getElementById('new-task-reason').value.trim();if(title.length<5){document.getElementById('new-task-error').textContent='Enter a title with at least five characters.';return;}const tasks=tasksFor(api.state),id=`${api.state.selected}:local-${localId()}`,task={id,key:id,incidentId:api.state.selected,title:title.slice(0,100),summary:summary.slice(0,250)||'Created in this local demonstration.',status:'attention',priority:'normal',owner:'Unassigned',due:null,blocker:'None recorded',question:'official',notes:[]};api.ui.taskTab='all';api.ui.taskId=id;commit({...api.state,tasks:{...api.state.tasks,[api.state.selected]:[...tasks,task]}},`Task created: ${task.title}`);closeDialog();toast('Task created locally.');}
 };
}
