#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { qualifyProductionFieldSensor } from '../../packages/domain/src/fieldnet/contracts.mjs';
import { createConflictResolutionPlan } from '../../packages/domain/src/fieldnet/reconciliation.mjs';
import { LiveShadowCampaignService } from '../../apps/api/src/modules/campaign/live-shadow-campaign-service.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),generatedAt=new Date().toISOString();
const paths={
  consensus:'data/validation/prevention/consensus-topology-evaluation-v1.json',falseNegatives:'data/validation/detection/v4-false-negative-recovery-program-v1.json',machine:'data/validation/measurement-debt/prevention-machine-validation-v1.json',debtHandoff:'data/validation/measurement-debt/measurement-debt-handoff.json',prospectiveProof:'data/validation/operations/prospective-campaign-hardening-proof.json',hardware:'data/validation/fieldnet/sensors/hardware-discovery.json',fieldnet:'data/runtime/fieldnet-central-reconciliation.json',liveCampaign:'data/runtime/live-shadow-campaign.json',pilot:'data/validation/pilot/pilot-definition.json',output:'data/validation/category-leadership/category-leadership-science-handoff.json',scienceRescue:'data/validation/category-leadership/science-rescue-handoff.json',autoclosure:'data/validation/measurement-debt/evidence-debt-autoclosure-v1.json',conflicts:'data/validation/fieldnet/conflict-resolution-plans-v1.json',sensorGate:'data/validation/fieldnet/sensors/production-gate-v1.json',pilotContract:'data/validation/pilot/design-partner-evidence-contract-v1.json'
};
const readJson=async(relative)=>JSON.parse(await readFile(path.join(root,relative),'utf8'));
const [consensus,falseNegatives,machine,debtHandoff,prospectiveProof,hardware,fieldnet,liveCampaign,pilot]=await Promise.all([paths.consensus,paths.falseNegatives,paths.machine,paths.debtHandoff,paths.prospectiveProof,paths.hardware,paths.fieldnet,paths.liveCampaign,paths.pilot].map(readJson));
const sha=(value)=>`sha256:${createHash('sha256').update(JSON.stringify(value)).digest('hex')}`;

const debtItems=machine.evidenceDebt??[],systemResolvable=debtItems.filter((item)=>item.system_resolvable),resolved=debtItems.filter((item)=>['MEASURED','RESOLVED'].includes(item.current_state)),partial=debtItems.filter((item)=>item.current_state==='PARTIALLY_MEASURED'),external=debtItems.filter((item)=>item.current_state==='EXTERNALLY_BLOCKED');
const autoclosureCore={schemaVersion:'vigia.evidence-debt-autoclosure.v1',generatedAt,openBefore:debtItems.length,systemResolvable:systemResolvable.length,attempted:systemResolvable.length,resolved:resolved.length,partiallyMeasured:partial.length,preserved:debtItems.length-resolved.length-partial.length,external:external.length,items:debtItems.map((item)=>({id:item.id,systemResolvable:item.system_resolvable,attempted:item.system_resolvable,currentState:item.current_state,currentDenominator:item.current_denominator,targetDenominator:item.target_denominator,watchState:item.watch_state,measurementPlanId:`plan:${item.id}`,closureContract:item.closure_contract,disposition:['MEASURED','RESOLVED'].includes(item.current_state)?'CLOSED_BY_CONTRACT':item.current_state==='PARTIALLY_MEASURED'?'PARTIAL_PRESERVE_REMAINDER':item.current_state==='EXTERNALLY_BLOCKED'?'PRESERVED_EXTERNAL':'PRESERVED_UNKNOWN'})),qualification:'Only contract-complete denominators close. Partial and external unknowns remain visible; no item is closed by assertion.'};
const autoclosure={...autoclosureCore,evidenceHash:sha(autoclosureCore)};

const currentConflicts=Object.values(fieldnet.conflicts??{}),observations=Object.values(fieldnet.observations??{});
const conflictPlans=currentConflicts.map((conflict)=>createConflictResolutionPlan(conflict,{observations:observations.filter((item)=>item.incidentId===conflict.incidentId),now:new Date(conflict.centralReceivedAt??fieldnet.updatedAt??generatedAt)}));
const conflictsCore={schemaVersion:'vigia.conflict-resolution-plan-collection.v1',generatedAt,conflictDenominator:currentConflicts.length,plans:conflictPlans,resolvedByNewEvidence:0,preserved:conflictPlans.length,qualification:'Plans identify evidence and responsibility; the engine selects no winner. Existing conflicts remain preserved until contract-satisfying evidence or attributable human adjudication is appended.'};
const conflictsArtifact={...conflictsCore,evidenceHash:sha(conflictsCore)};
const sensorGate=qualifyProductionFieldSensor({hardwareInventory:hardware,now:new Date(generatedAt)});

const liveCampaignService=new LiveShadowCampaignService({filePath:path.join(root,paths.liveCampaign),releaseId:liveCampaign.releaseId??'vigia-10.0.0',clock:()=>new Date(generatedAt),writer:async()=>{}});
await liveCampaignService.initialize();
const actualLive=actualLiveScorecards(liveCampaignService,generatedAt),pilotCore={
  schemaVersion:'vigia.design-partner-evidence-contract.v1',generatedAt,pilotId:pilot.pilotId,organization:pilot.organization,status:pilot.status,customerEvidenceClaimed:false,
  territory:pilot.territory,requiredOutputs:{sourceCoverage:'Prospective source checks by source family and window',physicalDetections:'Provider-time-eligible physical events only',physicalFirst:'Physical event precedes first attributable public report',multisource:'Independent source-family corroboration',assetRelation:'Mapped asset relation with source and completeness qualification',alertLatency:'Event-to-alert / alert-to-delivery / delivery-to-ack attributable timestamp pairs',evidenceDebtClosure:'Contract-based measured, partial, preserved and external states',preventConsensusZones:'Spatial support with claim state and no exact unstable point',fieldNetAvailability:'Sessions, offline minutes, sync success, conflicts and resolution results',operatorCorrections:'Append-only prospective correction records',outcomes:'Append-only attributable reference joins'},
  acceptanceGates:{partnerAssigned:false,territoryApproved:false,recipientRosterApproved:false,alertPolicyApproved:false,fieldHardwareQualified:sensorGate.physicalFamilyEligible,prospectiveBoundaryActive:true},
  currentEvidence:{liveCampaign:actualLive,consensusClaimStates:consensus.consensusTopology.claimStates,fieldSensorState:sensorGate.state,evidenceDebt:{resolved:resolved.length,partial:partial.length,external:external.length}},
  prohibitedClaims:['ROI','lives saved','fires avoided','risk reduction from consensus connectivity','customer production SLA from controlled exercise'],qualification:'This is the evidence contract a future utility, forestry or public-safety pilot would produce. No design partner or customer is fabricated.'
};
const pilotContract={...pilotCore,evidenceHash:sha(pilotCore)};

const zones=consensus.assessments??consensus.zones??[],zoneByState=consensus.consensusTopology.claimStates,failures=consensus.consensusTopology.failureTypes;
const interventionReviewCandidates=zones.filter((item)=>item.workflow?.interventionReviewEligible).length,measurementRequired=zones.filter((item)=>item.workflow?.disposition==='MEASUREMENT_REQUIRED').length;
const measurementPlans=zones.map((item)=>item.measurement_plan).filter(Boolean),consensusDebts=zones.map((item)=>item.evidence_debt).filter(Boolean);
const claims=countBy(zones.map((item)=>item.claim_level?.level).filter((value)=>value!==undefined&&value!==null));
const outcomeStates=['CONFIRMED_COMPATIBLE','REFERENCE_CONTRADICTED','REPORT_ONLY','PHYSICAL_ONLY_UNRESOLVED','IDENTITY_CONFLICT','NO_REFERENCE'];
const agent1Integration={
  required:['Consume assessment.state as the canonical science state.','Render action geometry only when assessment.workflow.interventionReviewEligible is true and assessment.intervention_geometry is non-null.','Render UNSTABLE_INTERVENTION_GEOMETRY, NO_DEFENSIBLE_INTERVENTION_ZONE and INSUFFICIENT_EVIDENCE as MEASUREMENT REQUIRED.','Use measurement_support_geometry only for evidence/measurement visualization; never reinterpret it as an intervention candidate.','Disable the expert intervention-review action for all 11 current assessments.','Show frozen retention, position, overlap and non-promotion metrics without rounding them into certainty.','Keep live versus controlled-proof scorecards visibly separated.'],
  forbidden:['Use assessment.geometry or measurement_support_geometry as an action fallback','Label any current assessment ROBUST_INTERVENTION_ZONE','Show deterministic risk reduction','Turn controlled persistence proof into a live incident/customer claim','Hide no-zone or unstable findings']
};
const externalBlockers=['No authoritative geometry-bound PREVENT negative-control corpus; false robust-zone rate is null.','No legitimate independent land-cover reference variation; ROBUST_INTERVENTION_ZONE is prohibited.','No frozen pre-event PREVENT graph corpus linked to later attributable fire geometry.','No matched fire-preceding/non-fire temporal control cohort.','No fresh untouched V5 confirmatory cohort.','No supported physical field-sensor hardware or held-out sensor validation.','No attributable expert/field PREVENT labels or post-intervention outcomes.',...(actualLive.summary.liveOutcomes?[]:['No attributable live prospective outcome has entered the current campaign window.'])];
const handoffCore={
  schemaVersion:'vigia.category-leadership-science-handoff.v2',generatedAt,status:'READY_FOR_AGENT_1_PRODUCT_INTEGRATION',
  releaseVerdict:consensus.releaseVerdict,
  criticalDelta:{before:consensus.criticalDelta.before,after:consensus.criticalDelta.after,operationsBefore:'Prospective boundary existed but lacked release identity, hash-chain, provider-time event admission and outcome joins.',operationsAfter:'Release-bound immutable hash-chain, provider-time admission, append-only outcome contract and honest 24h/7d/30d scorecards are implemented and proof-tested.'},
  consensusTopology:consensus.consensusTopology,promotionContract:{policyHash:consensus.promotionContract.policyHash,calibrationSplit:consensus.promotionContract.calibrationSplit,finalEvaluationSplit:consensus.promotionContract.finalEvaluationSplit,thresholds:consensus.promotionContract.thresholds,rationale:consensus.promotionContract.rationale},frozenConsensusEvaluation:consensus.frozenEvaluation.aggregate,
  zones:{denominator:zones.length,claimStates:zoneByState,failureTypes:failures,interventionReviewCandidates,measurementRequired,items:zones},counterfactualDistributions:consensus.counterfactualDistributions,
  historicalStructuralRelevance:consensus.historicalStructuralRelevance,matchedTemporalControls:consensus.matchedTemporalControls,
  falseNegativeRecovery:{denominator:falseNegatives.falseNegativeDenominator,recoverable:falseNegatives.recoverableWithCurrentData,clusterEvaluation:falseNegatives.recoverableClusterEvaluation,v5:falseNegatives.v5,sensingLimited:falseNegatives.sensingLimited},
  prospectiveCampaign:{implementationSchema:'vigia.live-shadow-campaign.v2',outcomeStates,retrospectiveBackfillAllowed:false,controlledPersistenceProof:prospectiveProof,liveRuntime:actualLive},prospectiveOutcomes:{contractStates:outcomeStates,liveOutcomeCount:actualLive.summary.liveOutcomes,controlledContractProof:prospectiveProof.outcomes,qualification:actualLive.summary.liveOutcomes?'Live outcomes are append-only and attributable to eligible prospective events.':'The append-only outcome contract is proven; the live campaign has no attributable external outcome yet.'},liveAlertPerformance:actualLive,
  evidenceDebtAutoclosure:autoclosure,conflictResolution:conflictsArtifact,fieldSensorGate:sensorGate,
  measurementAutopilot:{debts:consensusDebts.length,plans:measurementPlans.length,items:measurementPlans,qualification:'Every non-review-eligible assessment has an open, append-only, frozen-policy measurement plan.'},claimLevels:{counts:claims,maximumCurrent:Math.max(...zones.map((item)=>Number(item.claim_level?.level??0))),items:zones.map((item)=>({findingId:item.finding_id,claimLevel:item.claim_level,state:item.claim_state}))},
  rollingScorecards:{live:actualLive.windows,controlledContractProof:prospectiveProof.scorecards.windows},pilotEvidenceContract:pilotContract,
  agent1Integration,
  apiContracts:['/api/v10/validation/prevention-consensus','/api/v10/validation/prevention-consensus/zones','/api/v10/validation/prevention-consensus/:findingId','/api/v10/validation/false-negative-recovery','/api/v10/validation/measurement-debt','/api/v10/validation/category-leadership-science-handoff','/api/v10/validation/science-rescue-handoff','/api/v10/campaign/live-shadow','/api/v10/campaign/live-shadow/scorecards','/api/v10/campaign/live-shadow/outcomes','/api/v10/fieldnet/reconciliation/:incidentId','/api/v10/fieldnet/sensor-production-gate','/api/v10/pilot/report'],
  artifacts:{consensus:paths.consensus,falseNegativeRecovery:paths.falseNegatives,measurementDebt:paths.debtHandoff,prospectiveProof:paths.prospectiveProof,evidenceDebtAutoclosure:paths.autoclosure,conflictPlans:paths.conflicts,fieldSensorGate:paths.sensorGate,pilotEvidenceContract:paths.pilotContract,scienceRescue:paths.scienceRescue},
  externalBlockers,
  scientificClaimBoundary:'Physical-change repeatability, consensus support and modeled connectivity are decision-support evidence only. They do not prove causal prevention, fire-risk reduction, treatment efficacy, or field authorization.'
};
const handoff={...handoffCore,evidenceHash:sha(handoffCore)};
const scienceRescueCore={
  schemaVersion:'vigia.prevent-science-rescue-handoff.v1',generatedAt,status:'READY_FOR_AGENT_1_PRODUCT_INTEGRATION',releaseVerdict:consensus.releaseVerdict,criticalDelta:consensus.criticalDelta,
  consensusEnsemble:{findings:zones.length,members:consensus.consensusTopology.graphEnsembleMembers,graphRealizations:consensus.consensusTopology.graphRealizations,uncertaintyAxes:consensus.consensusTopology.uncertaintyAxes,policyHash:consensus.promotionContract.policyHash,provenanceComplete:zones.every((item)=>item.ensemble_provenance?.member_ids?.length&&item.ensemble_provenance?.graph_hashes?.length)},
  consensusStates:{counts:zoneByState,definitions:{ROBUST_INTERVENTION_ZONE:'Frozen promotion and robustness gates pass; expert review only.',MIXED_INTERVENTION_ZONE:'Spatial support exists but uncertainty remains.',UNSTABLE_INTERVENTION_GEOMETRY:'Support is not stable enough for intervention review.',NO_DEFENSIBLE_INTERVENTION_ZONE:'No defensible spatial component exists.',INSUFFICIENT_EVIDENCE:'The observation opportunity cannot support a geometry assessment.'}},
  robustZones:zones.filter((item)=>item.claim_state==='ROBUST_INTERVENTION_ZONE'),mixedZones:zones.filter((item)=>item.claim_state==='MIXED_INTERVENTION_ZONE'),unstableCases:zones.filter((item)=>item.claim_state==='UNSTABLE_INTERVENTION_GEOMETRY'),noZoneCases:zones.filter((item)=>item.claim_state==='NO_DEFENSIBLE_INTERVENTION_ZONE'),insufficientEvidence:zones.filter((item)=>item.claim_state==='INSUFFICIENT_EVIDENCE'),
  uncertainty:{frozenEvaluation:consensus.frozenEvaluation.aggregate,axes:consensus.consensusTopology.uncertaintyAxes,falseRobustZoneRate:consensus.negativeControls.falseRobustZoneRate,falseRobustZoneRateState:consensus.negativeControls.falseRobustZoneRateState},counterfactualIntervals:consensus.counterfactualDistributions,
  current11:{denominator:zones.length,interventionReviewCandidates,measurementRequired,items:zones.map((item)=>({findingId:item.finding_id,state:item.claim_state,legacyState:item.legacy_claim_state,workflow:item.workflow,failureType:item.failure_type,positionUncertainty:item.position_uncertainty,sceneSupport:item.scene_support,parameterSupport:item.parameter_support,claimLevel:item.claim_level,evidenceDebtId:item.evidence_debt?.id??null,measurementPlanId:item.measurement_plan?.id??null}))},
  falseNegativeRecovery:handoffCore.falseNegativeRecovery,sensingLimitedFailures:falseNegatives.sensingLimited,measurementAutopilot:handoffCore.measurementAutopilot,validationContract:{promotion:handoffCore.promotionContract,workflowRule:'Only interventionReviewEligible=true may expose intervention_geometry.',exactPointSuppression:consensus.exactPointSuppression,scientificClaimBoundary:handoffCore.scientificClaimBoundary},
  prospectiveCampaign:handoffCore.prospectiveCampaign,prospectiveScorecard:{live:actualLive.windows,controlledProof:prospectiveProof.scorecards.windows},fieldnetConflictPlans:conflictsArtifact,claimLevels:handoffCore.claimLevels,agent1Integration,apiContracts:handoffCore.apiContracts,artifacts:handoffCore.artifacts,externalBlockers,scientificClaimBoundary:handoffCore.scientificClaimBoundary
};
const scienceRescue={...scienceRescueCore,evidenceHash:sha(scienceRescueCore)};
for(const [relative,value] of [[paths.autoclosure,autoclosure],[paths.conflicts,conflictsArtifact],[paths.sensorGate,sensorGate],[paths.pilotContract,pilotContract],[paths.output,handoff],[paths.scienceRescue,scienceRescue]]){const target=path.join(root,relative);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,`${JSON.stringify(value,null,2)}\n`);}
console.log(JSON.stringify({output:paths.output,scienceRescue:paths.scienceRescue,verdict:handoff.releaseVerdict,claimStates:zoneByState,interventionReviewCandidates,measurementRequired,measurementPlans:measurementPlans.length,frozenEvaluation:consensus.frozenEvaluation.aggregate,evidenceDebt:{resolved:resolved.length,partial:partial.length,external:external.length},conflicts:conflictPlans.length,fieldSensor:sensorGate.state,live:actualLive.summary,evidenceHash:handoff.evidenceHash,scienceRescueEvidenceHash:scienceRescue.evidenceHash},null,2));

function actualLiveScorecards(campaignService,at){
  const campaign=campaignService.state,records=campaign.records??[],scorecards=campaignService.scorecards(),events=records.filter((record)=>record.type==='PHYSICAL_EVENT'&&record.metricEligibility==='ELIGIBLE');
  return{schemaVersion:campaign.schemaVersion,observedAt:at,prospectiveBoundaryAt:campaign.prospectiveBoundaryAt,lastCapturedAt:campaign.lastCapturedAt,recordCount:records.length,chainIntegrity:campaignService.status().chainIntegrity,summary:{sourceAcquisitions:records.filter((record)=>record.type==='SOURCE_ACQUISITION').length,cycles:records.filter((record)=>record.type==='CAMPAIGN_CYCLE').length,eligiblePhysicalEvents:events.length,unqualifiedAlerts:records.filter((record)=>record.type==='ALERT_CREATED'&&record.data?.eventProspectiveEligible!==true).length,liveOutcomes:records.filter((record)=>record.type==='OUTCOME_JOINED').length},windows:scorecards.windows,qualification:'Read-only scorecards from the governed live campaign engine. Provider-time eligibility and release-bound chain integrity are enforced identically to the runtime API.'};
}
function countBy(values){return Object.fromEntries([...new Set(values)].sort((a,b)=>Number(a)-Number(b)).map((value)=>[String(value),values.filter((item)=>item===value).length]));}
