import { createCanonicalOperationalEvent } from '../../../../../packages/domain/src/event-fabric/index.mjs';
import { createCausalLineage,normalizeQuality } from '../../../../../packages/domain/src/reality-network/index.mjs';

const hash=(product)=>String(product.checksumSha256).startsWith('sha256:')?product.checksumSha256:`sha256:${product.checksumSha256}`;
const common=({providerId,adapterVersion,providerEventId,providerRevision,sourceId,familyId,familyClass,producerId,upstreamOrigin,observedAt,publishedAt,receivedAt,coordinate,product,lineage,payload,proof,eventType,correlationKeys=[],subjectRefs=[],recordContentHash=null})=>createCanonicalOperationalEvent({eventType,hazardType:'wildfire',provider:{adapterId:`reality.${providerId}`,adapterVersion,providerEventId,providerRevision},source:{sourceId,familyId,familyClass,producerId,upstreamOrigin},clocks:{occurredAt:observedAt,observedAt,publishedAt:publishedAt??null,receivedAt,ingestedAt:null},geometry:coordinate,correlationKeys,subjectRefs:[`provider-record:${providerEventId}`,`raw-product:${product.id}`,...subjectRefs],payload:{...payload,lineage},provenance:{strength:'ATTRIBUTED',upstreamMeasurementId:lineage.originalObservation??providerEventId,rawPayloadHash:recordContentHash??hash(product),rawObjectRef:product.originalUriOrObjectKey,rawContentType:product.contentType,authority:familyClass==='OFFICIAL'?producerId:null,proofStatus:'PROVIDER_ATTRIBUTED',revocationStatus:'NOT_APPLICABLE',chain:[{providerId,endpointClass:'OFFICIAL_ALLOWLISTED_HTTPS',contentHash:hash(product)},lineage]},proof:{synthetic:false,transport:'TLS_OFFICIAL_ENDPOINT',contentHashVerified:true,providerNativeSignatureVerified:false,institutionalAuthority:familyClass==='OFFICIAL',...proof}});

export function physicalEvent(input){const lineage=createCausalLineage({sourceClass:'PHYSICAL',...input.lineage,rawContentHash:input.recordContentHash??input.product.checksumSha256}),quality=normalizeQuality({coordinate:input.coordinate,productMaturity:input.maturity,processingMode:input.processingMode,provenanceStrength:'ATTRIBUTED',native:input.native??{},requiredFields:input.requiredFields??[],providerQualityClass:input.providerQualityClass,geolocationConfidence:input.geolocationConfidence,temporalPrecision:input.temporalPrecision,obstructionState:input.obstructionState,saturation:input.saturation,viewGeometry:input.viewGeometry,algorithmFlags:input.algorithmFlags,anomalyWarnings:input.anomalyWarnings});return common({...input,familyClass:'PHYSICAL',lineage,payload:{observationState:'OBSERVED_POSITIVE',stance:'SUPPORTING',quality,...input.payload},eventType:input.eventType??'wildfire.thermal_observation'});}
export function officialEvent(input){const lineage=createCausalLineage({sourceClass:'OFFICIAL',...input.lineage,rawContentHash:input.recordContentHash??input.product.checksumSha256});return common({...input,familyClass:'OFFICIAL',lineage,payload:{observationState:input.supporting===false?'OBSERVED_UNDETERMINED':'OBSERVED_POSITIVE',stance:input.supporting===false?'IRRELEVANT':'SUPPORTING',...input.payload},eventType:input.eventType??'wildfire.official_observation'});}
export function contextEvent(input){const lineage=createCausalLineage({sourceClass:input.sourceClass??'CONTEXT',...input.lineage,rawContentHash:input.recordContentHash??input.product.checksumSha256});return common({...input,familyClass:'CONTEXT',lineage,payload:{observationState:'OBSERVED_UNDETERMINED',stance:'IRRELEVANT',...input.payload},eventType:input.eventType??'wildfire.context'});}
