import { semanticHash } from '../../../../../packages/domain/src/intelligence/shared.mjs';
import { createRealityConsumerSnapshot } from './consumer-snapshot.mjs';

const productRefs=(result)=>[result.rawProduct,...(result.rawProducts??[]),...(result.products??[]).map((item)=>item.rawProduct)].filter(Boolean).map((item)=>({id:item.id,sourceId:item.sourceId,providerProductId:item.providerProductId,checksumSha256:item.checksumSha256,byteLength:item.byteLength,sourceTimestamp:item.sourceTimestamp,licenceId:item.licenceMetadata?.licenceId??null}));
const resultSummary=(result)=>({providerId:result.providerId,status:result.status,startedAt:result.startedAt,completedAt:result.completedAt,records:result.records??result.events?.length??0,eventCount:result.events?.length??0,physicalFamilies:result.physicalFamilies??[],latencyMs:result.latencyMs??null,error:result.error??null,rawProducts:productRefs(result)});
export function createRealityRunReport({runId,startedAt,completedAt,selection,results,events,evaluation,twin,nextBest,rights,shadow,replay,replayVerification,state,coverageIndex}={}){
  const summaries=results.map(resultSummary),currentShadow=shadow.cycles.flatMap((item)=>item.outcomes??[]).filter((item)=>item.status==='SHADOW').length,historicalShadow=twin.controlPlane.actions.filter((item)=>item.status==='SHADOW').length,consumerSnapshot=createRealityConsumerSnapshot({runId,completedAt,selection,results,events,evaluation,nextBest,rights,shadow}),core={schemaVersion:'vigia.global-wildfire-reality-run.v1',runId,startedAt,completedAt,state,selection,providers:summaries,sourceSummary:{live:summaries.filter((item)=>item.status==='LIVE').length,degraded:summaries.filter((item)=>item.status==='DEGRADED').length,unavailable:summaries.filter((item)=>!['LIVE','DEGRADED'].includes(item.status)).length},evidence:{canonicalEventCount:events.length,sourceIds:[...new Set(events.map((item)=>item.source.sourceId))].sort(),familyIds:[...new Set(events.map((item)=>item.source.familyId))].sort(),physicalInstrumentFamilies:[...new Set(events.filter((item)=>item.source.familyClass==='PHYSICAL').map((item)=>item.payload.lineage?.instrumentFamily).filter(Boolean))].sort(),evaluation},twin:{projectionHash:twin.projectionHash,incidentCount:twin.incidents.length,selectedIncidentId:selection.twinIncidentId??null,sourceHealth:twin.sourceHealth.sources.map((item)=>({sourceId:item.sourceId,status:item.status,lastSuccessAt:item.lastSuccessAt,errorCode:item.errorCode}))},collection:{coverageIndexFingerprint:coverageIndex.fingerprint,eligible:nextBest.filter((item)=>item.eligible).map((item)=>item.sourceId),ineligible:nextBest.filter((item)=>!item.eligible).map((item)=>({sourceId:item.sourceId,reasons:item.reasons}))},rights,shadow:{state:shadow.state,mode:shadow.mode,wouldHaveActionCount:Math.max(currentShadow,historicalShadow),currentRunWouldHaveActionCount:currentShadow,durableShadowActionCount:historicalShadow},replay:{replayHash:replay.replayHash,valid:replayVerification.valid,reasons:replayVerification.reasons},consumerSnapshot};
  return Object.freeze({...core,runHash:semanticHash('global-wildfire-reality-run',core)});
}
