import { evidenceKind } from './situation.mjs';
const id=(item)=>String(item.id??item.observationId??'');

export function deriveDecisionDelta({previous=null,incident={},situation={},sourceStateHash=null,evidenceNeeds=[],operatorDecisions=[],fieldNetState=null,corrections=[],generatedAt=new Date().toISOString()}={}){
  const rows=[],priorIds=new Set(previous?.inputEvidenceIds??[]),observations=incident.observations??[];
  for(const item of observations.filter((entry)=>id(entry)&&!priorIds.has(id(entry)))){const kind=evidenceKind(item),type=kind==='PHYSICAL_OBSERVATION'?'NEW_PHYSICAL_OBSERVATION':kind==='REPORT'?'NEW_PUBLIC_REPORT':'NEW_EXTERNAL_FACT';rows.push({id:`delta:${type}:${id(item)}`,type,at:item.visibleAt??item.receivedAt??item.at??item.observedAt??generatedAt,externalFact:true,humanDecision:false,evidenceIds:[id(item)],summary:type.replaceAll('_',' ')});}
  if(previous?.situation?.underlyingState&&previous.situation.underlyingState!==situation.underlyingState)rows.push({id:`delta:state:${generatedAt}`,type:'RECOMPUTED_PROJECTION',at:generatedAt,externalFact:false,humanDecision:false,fromState:previous.situation.underlyingState,toState:situation.underlyingState,evidenceIds:situation.supportingEvidenceIds,summary:`Assessment changed from ${previous.situation.underlyingState} to ${situation.underlyingState}.`});
  if(previous?.sourceStateVersion&&previous.sourceStateVersion!==sourceStateHash)rows.push({id:`delta:source:${generatedAt}`,type:'SOURCE_STATE_CHANGE',at:generatedAt,externalFact:false,humanDecision:false,evidenceIds:[],summary:'Relevant source state changed.'});
  if(previous&&JSON.stringify(previous.incidentAssociation??null)!==JSON.stringify(incident.association??null))rows.push({id:`delta:association:${generatedAt}`,type:'ASSOCIATION_CHANGE',at:generatedAt,externalFact:false,humanDecision:false,evidenceIds:[],summary:'Governed incident association changed.'});
  const priorNeeds=new Set(previous?.inputEvidenceNeedIds??[]);for(const need of evidenceNeeds.filter((item)=>!priorNeeds.has(String(item.id))))rows.push({id:`delta:need:${need.id}`,type:'NEW_EVIDENCE_NEED',at:need.createdAt??generatedAt,externalFact:false,humanDecision:false,evidenceIds:[],summary:`Evidence need opened: ${String(need.missingQuantity??need.id).replaceAll('_',' ')}.`});
  const priorNeedState=new Map((previous?.inputEvidenceNeeds??[]).map((item)=>[String(item.id),String(item.state)]));for(const need of evidenceNeeds.filter((item)=>['RESOLVED','CLOSED'].includes(String(item.state??item.resolutionState).toUpperCase())&&!['RESOLVED','CLOSED'].includes((priorNeedState.get(String(item.id))??'').toUpperCase())))rows.push({id:`delta:need-resolved:${need.id}`,type:'EVIDENCE_NEED_RESOLVED',at:need.resolvedAt??generatedAt,externalFact:false,humanDecision:false,evidenceIds:need.supportingEvidenceIds??[],summary:`Evidence need resolved: ${String(need.missingQuantity??need.id).replaceAll('_',' ')}.`});
  const priorCorrections=new Set(previous?.inputCorrectionIds??[]);for(const correction of corrections.filter((item)=>!priorCorrections.has(String(item.id))))rows.push({id:`delta:correction:${correction.id}`,type:'CORRECTION',at:correction.effectiveAt??correction.createdAt??generatedAt,externalFact:false,humanDecision:false,evidenceIds:correction.evidenceIds??[],summary:`Operator correction applied: ${String(correction.reasonCode??correction.kind??correction.id).replaceAll('_',' ')}.`});
  const previousAt=Date.parse(previous?.generatedAt??'');for(const decision of operatorDecisions.filter((item)=>!Number.isFinite(previousAt)||Date.parse(item.createdAt)>previousAt))rows.push({id:`delta:decision:${decision.decisionId}`,type:'HUMAN_DECISION',at:decision.createdAt,externalFact:false,humanDecision:true,evidenceIds:[],summary:`Operator decision: ${decision.decisionType}.`});
  if(fieldNetState?.lastReconciledAt&&(!previous?.fieldNetState?.lastReconciledAt||Date.parse(fieldNetState.lastReconciledAt)>Date.parse(previous.fieldNetState.lastReconciledAt)))rows.push({id:`delta:fieldnet:${fieldNetState.lastReconciledAt}`,type:'FIELDNET_RECONCILIATION',at:fieldNetState.lastReconciledAt,externalFact:false,humanDecision:false,evidenceIds:[],summary:'FieldNet reconciliation changed incident state.'});
  if(!rows.length)rows.push({id:`delta:projection:${generatedAt}`,type:'RECOMPUTED_PROJECTION',at:generatedAt,externalFact:false,humanDecision:false,evidenceIds:[],summary:'Projection inputs are unchanged; no new external fact is asserted.'});
  return Object.freeze(rows.sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)||a.id.localeCompare(b.id)).slice(0,20).map(Object.freeze));
}
