const visibleAt=(item)=>item.knownAt??item.updatedAt??item.visibleAt??item.receivedAt??item.arrivalAt??item.effectiveAt??item.createdAt??item.lastReconciledAt??item.at??item.observedAt??null;
const visible=(item,asOf)=>{const value=Date.parse(visibleAt(item)??'');return Number.isFinite(value)&&value<=Date.parse(asOf);};
const historicalRows=(items,asOf)=>Array.isArray(items)?items.filter((item)=>visible(item,asOf)):[];
const historicalState=(state,asOf)=>Object.fromEntries(Object.entries(state??{}).filter(([,item])=>item&&typeof item==='object'&&visible(item,asOf)));
const historicalTiming=(timing,asOf)=>Object.fromEntries(Object.entries(timing??{}).filter(([,value])=>!Number.isFinite(Date.parse(value??''))||Date.parse(value)<=Date.parse(asOf)));

export function hindsightSafeInputs(input={},asOf){
  if(!Number.isFinite(Date.parse(asOf??'')))throw new Error('replay_as_of_required');
  const sourceIncident=input.incident??{},evidence=sourceIncident.observations??input.evidence??[],corrections=historicalRows(input.corrections??sourceIncident.corrections,asOf),associationCorrections=historicalRows(sourceIncident.associationCorrections,asOf),contradictions=historicalRows(sourceIncident.contradictions,asOf),evidenceContradictions=historicalRows(sourceIncident.evidenceContradictions,asOf),fusionContradictions=historicalRows(sourceIncident.evidenceFusion?.contradictions,asOf),fireContradictions=historicalRows(sourceIncident.fireEvidenceState?.contradictions,asOf);
  const incident={id:sourceIncident.id,label:sourceIncident.label??sourceIncident.name,mode:'HISTORICAL_REPLAY',district:sourceIncident.district??null,municipality:sourceIncident.municipality??null,territory:sourceIncident.territory??null,observations:evidence.filter((item)=>visible(item,asOf)),corrections,associationCorrections,contradictions,evidenceContradictions,...(fusionContradictions.length?{evidenceFusion:{contradictions:fusionContradictions}}:{}),...(fireContradictions.length?{fireEvidenceState:{contradictions:fireContradictions}}:{}),...(visible(sourceIncident.association??{},asOf)?{association:sourceIncident.association}:{}),prospectiveDetectionTiming:historicalTiming(sourceIncident.prospectiveDetectionTiming,asOf)};
  const decisions=(input.operatorDecisions??[]).filter((item)=>visible(item,asOf)),needs=(input.evidenceNeeds??[]).filter((item)=>visible(item,asOf)),requests=(input.evidenceRequests??[]).filter((item)=>visible(item,asOf)),opportunities=(input.opportunities??[]).filter((item)=>visible(item,asOf)||Date.parse(item.createdAt??'')<=Date.parse(asOf)),opportunityResults=(input.opportunityResults??[]).filter((item)=>visible(item,asOf));
  const excluded=[...evidence,...(input.corrections??sourceIncident.corrections??[]),...(sourceIncident.associationCorrections??[])].filter((item)=>!visible(item,asOf)).map((item)=>({id:item.id??null,reason:'FUTURE_AT_GOVERNED_CLOCK',visibleAt:visibleAt(item)}));
  const fieldNetState=visible(input.fieldNetState??{},asOf)?input.fieldNetState:null;
  return Object.freeze({...input,incident,evidenceNeeds:needs,evidenceRequests:requests,operatorDecisions:decisions,opportunities,opportunityResults,sourceState:historicalState(input.sourceState,asOf),fieldNetState,corrections,asOf,generatedAt:asOf,mode:'HISTORICAL_REPLAY',futureEvidenceExcluded:Object.freeze(excluded)});
}
