import { mkdir,readFile,stat,writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { signFieldRequest } from '../../packages/domain/src/fieldnet/request-auth.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const central=String(process.env.VIGIA_BASE_URL??'http://127.0.0.1:4277').replace(/\/$/,'');
const field=String(process.env.FIELDNET_BASE_URL??'http://127.0.0.1:4288').replace(/\/$/,'');
const incidentId='PT-2026-5C3C5DE25E';
const fieldControlKey=process.env.FIELDNET_CONTROL_KEY,fieldControlKeyId=process.env.FIELDNET_CONTROL_KEY_ID??'field-operator';
const files={proof:'data/validation/fieldnet/fieldnet-disconnection-proof.json',replay:'data/validation/fieldnet/fieldnet-disconnection-replay.json',pkg:'data/validation/fieldnet/real-incident-package.json',debt:'data/validation/measurement-debt/measurement-debt-handoff.json',hardware:'data/validation/fieldnet/sensors/hardware-discovery.json',geography:'data/validation/fieldnet/offline-geography/incident-geography.json',terrain:'data/validation/fieldnet/offline-geography/incident-terrain.json',pilot:'data/validation/pilot/governed-pilot-report.json',performance:'data/validation/fieldnet/fieldnet-1-1-performance.json',acceptance:'data/validation/fieldnet/fieldnet-1-1-acceptance.json',operational:'data/validation/fieldnet/fieldnet-1-1-operational-proof.json',ui:'apps/web/data/fieldnet-proof-summary.json'};
const absolute=(relative)=>path.join(root,relative);
const readJson=async(relative)=>JSON.parse(await readFile(absolute(relative),'utf8'));
const save=async(relative,value)=>{await mkdir(path.dirname(absolute(relative)),{recursive:true});await writeFile(absolute(relative),`${JSON.stringify(value,null,2)}\n`);};
const timed=async(url)=>{const started=performance.now(),parsed=new URL(url),protectedField=url.startsWith(field)&&parsed.pathname.startsWith('/api/fieldnet/'),headers=protectedField?signFieldRequest({method:'GET',path:parsed.pathname,keyId:fieldControlKeyId,key:fieldControlKey,body:null}):{};const response=await fetch(url,{headers,signal:AbortSignal.timeout(20_000)}),payload=await response.json();if(!response.ok)throw new Error(`${url}:${response.status}:${payload.error??'request_failed'}`);return {payload,durationMs:Number((performance.now()-started).toFixed(3))};};
const [proof,replay,pkg,debt,hardware]=await Promise.all([readJson(files.proof),readJson(files.replay),readJson(files.pkg),readJson(files.debt),readJson(files.hardware)]);
const fieldRoutes=['state','incidents',`incidents/${incidentId}`,`incidents/${incidentId}/observations`,`incidents/${incidentId}/tasks`,`incidents/${incidentId}/conflicts`,'devices',`incidents/${incidentId}/truth-graph`,`incidents/${incidentId}/source-freshness`,`incidents/${incidentId}/offline-map`,`incidents/${incidentId}/replay`,`incidents/${incidentId}/metrics`,'sync-queue','sensor-gateway'];
const workspaceStarted=performance.now();
const fieldResults=await Promise.all(fieldRoutes.map((route)=>timed(`${field}/api/fieldnet/${route}`)));
const workspaceLoadMs=Number((performance.now()-workspaceStarted).toFixed(3));
const byRoute=Object.fromEntries(fieldRoutes.map((route,index)=>[route,fieldResults[index]]));
const [campaign,pilotReport,centralDebt]=await Promise.all([timed(`${central}/api/v10/campaign/live-shadow/scorecards`),timed(`${central}/api/v10/pilot/report`),timed(`${central}/api/v10/validation/measurement-debt`)]);
await save(files.pilot,pilotReport.payload);
const base=pkg.offlineMap.baseLayer,packageFileBytes=(await stat(absolute(files.pkg))).size,geographyFileBytes=(await stat(absolute(files.geography))).size,terrainFileBytes=(await stat(absolute(files.terrain))).size;
const performanceEvidence={schemaVersion:'vigia.fieldnet-1-1-performance.v1',generatedAt:new Date().toISOString(),incidentId,scope:'LOCAL_CONTROLLED_PROOF',sizes:{incidentPackage:{canonicalBytes:pkg.byteLength,fileBytes:packageFileBytes},mapLibreCompatibleGeoJson:{canonicalBytes:Buffer.byteLength(JSON.stringify(base.geoJson)),derivedPrettyJsonBytes:geographyFileBytes,features:base.geoJson.features.length},terrain:{canonicalBytes:Buffer.byteLength(JSON.stringify(base.terrain)),derivedPrettyJsonBytes:terrainFileBytes,grid:[base.terrain.width,base.terrain.height]},rawArchivesNotShipped:{copernicusDemBytes:base.terrain.source.rawByteLength,osmRecords:base.geographySource.rawRecordCount},remoteTileDependencies:base.remoteTileDependencies},timingsMs:{centralOnline:proof.timingsMs.centralOnlineMs,fieldListenerReady:proof.timingsMs.reportedColdListenerReadyMs,packageImport:proof.timingsMs.packageImportMs,fieldWorkspaceApiAssembly:workspaceLoadMs,offlineMapApi:byRoute[`incidents/${incidentId}/offline-map`].durationMs,mapStartup:{state:'NOT_CAPTURED',reason:'In-app browser denied the isolated QA port; no timing is fabricated.',mapContractFetchMs:byRoute[`incidents/${incidentId}/offline-map`].durationMs},observationCommit:proof.timingsMs.firstOfflineObservationCommitMs,conflictingObservationCommit:proof.timingsMs.conflictingObservationCommitMs,taskAcknowledgement:proof.timingsMs.taskAcknowledgementCommitMs,sensorIngest:{state:'NOT_RUN',reason:'REAL_HARDWARE_NOT_PRESENT',exerciseGatewayCoveredByAutomatedTest:true},wanIsolationDetection:proof.timingsMs.wanIsolationDetectionMs,syncReconciliation:proof.timingsMs.automaticReconnectReconciliationMs,replayApi:byRoute[`incidents/${incidentId}/replay`].durationMs},qualification:'Timings are controlled local measurements, not a customer SLA. No physical sensor ingest timing exists because no real supported hardware was present.'};
await save(files.performance,performanceEvidence);
const steps=[
  ['CENTRAL ONLINE',true,'Controlled central ledger accepted health before isolation.'],['FIELD NODE ONLINE',true,'Real Field Node listener and SQLite/WAL store.'],['OFFLINE MAP LOADED',proof.offlineMap.remoteTileDependencies===0,`${proof.offlineMap.geographyFeatureCount} local features; 80×80 terrain grid.`],['WAN REMOVED',proof.transition.includes('WAN_REMOVED'),'Central server was actually closed in the harness.'],['TASK RECEIVED',proof.centralTruth.tasks===1,'Geographic verification task persisted.'],['TASK ACKNOWLEDGED',proof.afterReconciliation.acknowledgements===1,'Local acknowledgement persisted across restart.'],['HUMAN OBSERVATION',proof.dataIntegrity.actualLocalObservations===2,'Two attributable controlled-exercise reports.'],['QUALIFIED SENSOR OBSERVATION','SKIPPED_REAL_HARDWARE_NOT_PRESENT','No sensor was fabricated.'],['CONFLICT',proof.conflicts.final.some((item)=>item.state==='OPEN'),'Observation conflict remains visible.'],['EVIDENCE DEBT CREATED',Boolean(proof.evidenceDebt.createdWhileDisconnected),'Local debt record with verification plan.'],['VERIFICATION PLAN',Boolean(proof.evidenceDebt.createdWhileDisconnected?.closesWhen),'Explicit evidence and closure contract.'],['WAN RESTORED',proof.transition.includes('WAN_RESTORED'),'Controlled central dependency restarted.'],['SYNC',proof.afterReconciliation.pendingSync===0,'Acknowledged priority batches.'],['RECONCILIATION',proof.dataIntegrity.zeroDuplicateApplication,'Dropped acknowledgement and duplicates handled idempotently.'],['EVIDENCE DEBT UPDATED',proof.evidenceDebt.updatedAfterReconciliation?.revision===2,'Revision 2 replayed after reconciliation.'],['REPLAY',proof.evidenceDebt.replayVerified&&proof.audit.valid,'Persisted mutation/audit replay verified.']
].map(([step,pass,evidence])=>({step,status:pass===true?'PASS':pass,evidence}));
const acceptance={schemaVersion:'vigia.fieldnet-1-1-acceptance.v2',generatedAt:new Date().toISOString(),verdict:steps.every((item)=>item.status==='PASS'||item.status==='SKIPPED_REAL_HARDWARE_NOT_PRESENT')?'PASS':'FAIL',scope:'CONTROLLED_FIELD_EXERCISE_ONLY',steps,dataIntegrity:proof.dataIntegrity,audit:proof.audit,transport:proof.transport,evidenceDebt:proof.evidenceDebt,hardware:{status:hardware.sensorHardware,qualification:hardware.qualification},performance:performanceEvidence.timingsMs};
await save(files.acceptance,acceptance);
const operational={schemaVersion:'vigia.fieldnet-1-1-operational-proof.v1',generatedAt:new Date().toISOString(),releaseVerdict:'PASS_WITH_EXTERNAL_DEPLOYMENT_GATES',incident:{incidentId,packageId:pkg.packageId,evidenceHash:pkg.evidenceHash,physicalObservations:pkg.physicalObservations.length,sourceFamilies:[...new Set(pkg.physicalObservations.map((item)=>item.sourceFamily))]},offline:{featureCounts:base.featureCounts,terrain:base.terrain.statistics,remoteTileDependencies:base.remoteTileDependencies,packageBytes:pkg.byteLength},fieldNode:{state:byRoute.state.payload,metrics:byRoute[`incidents/${incidentId}/metrics`].payload,sensorGateway:byRoute['sensor-gateway'].payload},campaign:campaign.payload,pilot:{reportPath:files.pilot,organization:pilotReport.payload.pilot.organization,kpis:pilotReport.payload.kpis},measurementDebt:{items:debt.evidenceDebtItems.length,open:debt.openDebt.length,resolved:debt.resolvedDebt.length,plans:debt.measurementPlans.length,liveApiItems:centralDebt.payload.items?.length??centralDebt.payload.evidenceDebtItems?.length??null},acceptance:{path:files.acceptance,verdict:acceptance.verdict},performance:{path:files.performance},limitations:pilotReport.payload.limitations};
await save(files.operational,operational);
const mutation=(type,index=0)=>replay.mutations.filter((item)=>item.type===type)[index];
const frame=(id,type,title,counts={})=>{const item=mutation(type,counts.index??0);return {id,at:item?.wallClockAt??proof.generatedAt,type,title,actor:item?.actor??'FieldNet kernel',...counts,index:undefined};};
const ui={schemaVersion:'vigia.fieldnet-ui-proof-summary.v1.1',proofId:proof.proofId,generatedAt:proof.generatedAt,scope:proof.scope,incidentId,qualification:proof.qualification,evidenceDebt:proof.evidenceDebt,frames:[frame('package','INCIDENT_PACKAGE_IMPORTED','Offline geography and terrain loaded',{connectionState:'FULL',observations:0,tasks:0,conflicts:0,pendingSync:0,mapState:'LOCAL_GEOGRAPHY_AND_TERRAIN'}),frame('observation','FIELD_OBSERVATION_ADDED','First human observation committed after WAN removal',{connectionState:'REGIONAL_DISCONNECTED',observations:1,tasks:0,conflicts:0,pendingSync:4,mapState:'ONE_LOCAL_OBSERVATION'}),frame('conflict','CONFLICT_CREATED','Contradictory observations preserved geographically',{connectionState:'REGIONAL_DISCONNECTED',observations:2,tasks:1,conflicts:1,pendingSync:8,mapState:'CONFLICT_VISIBLE'}),frame('debt','EVIDENCE_DEBT_CREATED','Evidence debt and verification plan created locally',{connectionState:'REGIONAL_DISCONNECTED',observations:2,tasks:1,conflicts:1,pendingSync:9,mapState:'VERIFICATION_PLANNED'}),frame('ack','TASK_ACKNOWLEDGED','Verification task acknowledged locally',{connectionState:'LOW_BANDWIDTH',observations:2,tasks:1,conflicts:1,pendingSync:10,mapState:'TASK_ACKNOWLEDGED'}),frame('reconcile','EVIDENCE_DEBT_UPDATED','WAN restored; debt updated after reconciliation',{connectionState:'FULL',observations:2,tasks:1,conflicts:2,pendingSync:0,mapState:'CENTRAL_ACKNOWLEDGED'}),frame('resolved','CONFLICT_RESOLVED','Authorized task conflict resolution recorded',{connectionState:'FULL',observations:2,tasks:1,conflicts:1,resolvedConflicts:1,pendingSync:0,mapState:'CENTRAL_ACKNOWLEDGED'})],timingsMs:proof.timingsMs,dataIntegrity:proof.dataIntegrity,audit:proof.audit,offlineMap:{regionPackaged:true,baseLayerState:base.state,terrainState:base.terrain.state,geographyFeatureCount:base.geoJson.features.length,remoteTileDependencies:base.remoteTileDependencies,localObservationCount:2,taskCount:1}};
await save(files.ui,ui);
process.stdout.write(`${JSON.stringify({ok:true,acceptance:acceptance.verdict,performance:files.performance,operational:files.operational,pilot:files.pilot})}\n`);
