import path from 'node:path';
import { readFile } from 'node:fs/promises';
import { readJson } from '../../shared/json-file.mjs';
import { acquireRaw, createPublicEvidenceVault, normalizedFireId } from '../worldclass/public-evidence-war-room.mjs';
import { closurePaths, fingerprint, HORIZON_DOCTRINE, PERIMETER_CLASSES, readArtifact, writeArtifact } from './contracts.mjs';
import { classifyPerimeterRevision } from './adversarial-policy.mjs';
import { captureGoesSensorProgression } from './sensor-progression-service.mjs';

const sources = Object.freeze([
  { providerId: 'alberta-wildfire', id: 'alberta', service: 'https://geospatial.alberta.ca/mimas/rest/services/wildfire/alberta_fire_status/FeatureServer', layer: 1, sourceId: 'alberta:current-perimeters', authorityClass: 'AUTHORITATIVE_OPERATIONAL_PERIMETER' },
  { providerId: 'bc-wildfire-service', id: 'bcws', service: 'https://services6.arcgis.com/ubm4tcTYICKBpist/arcgis/rest/services/BCWS_FirePerimeters_PublicView/FeatureServer', layer: 0, sourceId: 'bcws:current-perimeters', authorityClass: 'AUTHORITATIVE_OPERATIONAL_PERIMETER' }
]);
const cwfis = Object.freeze(['perimeters.cpg', 'perimeters.dbf', 'perimeters.prj', 'perimeters.shp', 'perimeters.shx', 'progression.cpg', 'progression.dbf', 'progression.prj', 'progression.shp', 'progression.shx']);
const root = (projectRoot) => path.join(projectRoot, 'data/runtime/evidence-war-room'), archivePath = (projectRoot, product) => path.join(root(projectRoot), 'bronze', product.originalUriOrObjectKey);
const iso = (value, fallback = null) => { if (Number.isFinite(Number(value)) && Number(value) > 1_000_000_000) return new Date(Number(value)).toISOString(); const parsed = Date.parse(value ?? ''); return Number.isFinite(parsed) ? new Date(parsed).toISOString() : fallback; };
const stableId = (provider, properties) => provider === 'alberta-wildfire' ? `CA-AB-${normalizedFireId(properties.FireNumber ?? properties.FireNumber_Short ?? properties.OBJECTID)}` : `CA-BC-${normalizedFireId(properties.FIRE_NUMBER ?? properties.GlobalID ?? properties.OBJECTID)}`;
const published = (provider, properties, fallback) => provider === 'alberta-wildfire' ? iso(properties.GISFeatureLastUpdated, iso(properties.GISFeatureLastUpdated_MT, fallback)) : iso(properties.LOAD_DATE, iso(properties.TRACK_DATE, fallback));
const area = (provider, properties) => Number(provider === 'alberta-wildfire' ? properties.AREA_ESTIMATE : properties.FIRE_SIZE_HECTARES) || null;
const stateCore = (provider, feature) => ({ geometry: feature.geometry, status: feature.properties?.FIRE_STATUS ?? null, areaHectares: area(provider, feature.properties ?? {}), version: feature.properties?.VERSION_NUMBER ?? feature.properties?.GISFeatureLastUpdated ?? null, source: feature.properties?.SOURCE ?? feature.properties?.DataSource ?? null });

async function captureArcGis(definition, vault, fetchImpl, clock) {
  const metadata = await acquireRaw({ vault, providerId: definition.providerId, sourceId: `${definition.sourceId}:metadata`, url: `${definition.service}/${definition.layer}?f=pjson`, parserVersion: 'vigia.arcgis-layer-metadata.v1', accept: 'application/json', maximumBytes: 4 * 1024 * 1024, fetchImpl, clock }), parsedMetadata = JSON.parse(metadata.response.body.toString('utf8')), pages = [];
  for (let page = 0; page < 4; page += 1) { const url = new URL(`${definition.service}/${definition.layer}/query`); for (const [key, value] of Object.entries({ where: '1=1', outFields: '*', returnGeometry: 'true', outSR: '4326', resultOffset: String(page * 100), resultRecordCount: '100', orderByFields: 'OBJECTID', f: 'geojson' })) url.searchParams.set(key, value); const raw = await acquireRaw({ vault, providerId: definition.providerId, sourceId: `${definition.sourceId}:page:${page + 1}`, url, parserVersion: 'vigia.arcgis-geojson.v1', requestWindow: { page: page + 1, pageSize: 100 }, accept: 'application/geo+json,application/json', maximumBytes: 128 * 1024 * 1024, fetchImpl, clock }); const body = JSON.parse(raw.response.body.toString('utf8')); pages.push({ rawProductId: raw.product.id, records: body.features?.length ?? 0 }); if (!body.properties?.exceededTransferLimit && (body.features?.length ?? 0) < 100) break; }
  return { providerId: definition.providerId, metadataRawProductId: metadata.product.id, pages, capabilities: { editorTracking: Boolean(parsedMetadata.editingInfo), changeTracking: Boolean(parsedMetadata.changeTrackingInfo), syncEnabled: parsedMetadata.syncEnabled === true, historicMoment: parsedMetadata.advancedQueryCapabilities?.supportsQueryWithHistoricMoment === true, stableObjectIdField: parsedMetadata.objectIdField ?? parsedMetadata.objectIdFieldName ?? null, lastEditDate: iso(parsedMetadata.editingInfo?.lastEditDate), rawValuesInspected: true } };
}

async function captureCwfis(vault, fetchImpl, clock) {
  const products = [];
  for (const name of cwfis) { const raw = await acquireRaw({ vault, providerId: 'cwfis-nrcan', sourceId: `cwfis:current:${name}`, url: `https://cwfis.cfs.nrcan.gc.ca/downloads/hotspots/${name}`, parserVersion: 'vigia.cwfis-shapefile-component.v1', maximumBytes: 64 * 1024 * 1024, fetchImpl, clock }); products.push({ name, id: raw.product.id, sha256: `sha256:${raw.product.checksumSha256}`, duplicate: raw.duplicate }); }
  return { providerId: 'cwfis-nrcan', products, authorityClasses: { perimeters: 'OFFICIAL_REFERENCE_PERIMETER', progression: 'DERIVED_SENSOR_PROGRESSION' } };
}

async function rebuildCampaign(projectRoot, clock, metadataInspection, cwfisCapture) {
  const paths = closurePaths(projectRoot), state = await readJson(path.join(root(projectRoot), 'acquisition-state.json'), { products: {} }), products = Object.values(state.products ?? {}).filter((item) => /^(alberta|bcws):current-perimeters:page:\d+$/.test(item.sourceId)).sort((a, b) => Date.parse(a.receivedAt) - Date.parse(b.receivedAt) || a.id.localeCompare(b.id)), snapshots = [], seen = new Set(), lastState = new Map();
  for (const product of products) { let body; try { body = JSON.parse(await readFile(archivePath(projectRoot, product), 'utf8')); } catch { continue; } for (const feature of body.features ?? []) { const incidentId = stableId(product.provider, feature.properties ?? {}), coreState = stateCore(product.provider, feature), stateHash = fingerprint('perimeter-feature-state', coreState), observationId = fingerprint('perimeter-observation', { productId: product.id, incidentId, stateHash }); if (seen.has(observationId)) continue; seen.add(observationId); const prior = lastState.get(`${product.provider}:${incidentId}`), observation = !prior ? 'INITIAL_PROVIDER_STATE' : prior.stateHash === stateHash ? 'UNCHANGED_SCHEDULED_OBSERVATION' : 'CHANGED_PROVIDER_STATE'; const snapshotCore = { schemaVersion: 'vigia.perimeter-campaign-snapshot.v1', sequence: snapshots.length + 1, observationId, incidentId, providerId: product.provider, authorityClass: 'AUTHORITATIVE_OPERATIONAL_PERIMETER', providerPublishedAt: published(product.provider, feature.properties ?? {}, product.sourceTimestamp ?? product.receivedAt), vigiaReceivedAt: product.receivedAt, rawProductId: product.id, rawObjectHash: `sha256:${product.checksumSha256}`, geometry: feature.geometry, state: coreState, stateHash, observation, priorObservationId: prior?.observationId ?? null, priorSnapshotHash: snapshots.at(-1)?.snapshotHash ?? null }; const snapshot = { ...snapshotCore, snapshotHash: fingerprint('perimeter-campaign-snapshot', snapshotCore) }; snapshots.push(snapshot); lastState.set(`${product.provider}:${incidentId}`, snapshot); } }
  const prior = await readArtifact(paths.perimeterArchive, { snapshots: [] }), priorHashes = (prior.snapshots ?? []).map((item) => item.snapshotHash), prefixStable = priorHashes.every((hash, index) => snapshots[index]?.snapshotHash === hash), meaningful = snapshots.filter((item) => item.observation === 'CHANGED_PROVIDER_STATE'), uniquePublications = new Set(snapshots.map((item) => `${item.providerId}:${item.providerPublishedAt}`).filter((item) => !item.endsWith(':null'))), revisionsByIncident = new Map(); for (const item of meaningful) revisionsByIncident.set(item.incidentId, (revisionsByIncident.get(item.incidentId) ?? 0) + 1);
  const core = { schemaVersion: 'vigia.perimeter-campaign.v1', generatedAt: clock().toISOString(), doctrine: { appendOnly: true, unchangedIsNotProgression: true, authorityClasses: PERIMETER_CLASSES }, metadataInspection, cwfisCapture, snapshots, immutableSnapshots: snapshots.length, uniqueRawObjects: new Set(snapshots.map((item) => item.rawProductId)).size, uniqueProviderPublications: uniquePublications.size, uniquePerimeterRevisions: new Set(meaningful.map((item) => item.stateHash)).size, meaningfulChangedStates: meaningful.length, incidentsWithThreeMeaningfulStates: [...revisionsByIncident.values()].filter((count) => count >= 3).length, unchangedObservations: snapshots.filter((item) => item.observation === 'UNCHANGED_SCHEDULED_OBSERVATION').length, priorSnapshotsRewritten: prefixStable ? 0 : priorHashes.length, restartRecovery: { deterministicRebuild: true, duplicateObservationIds: snapshots.length - seen.size, priorPrefixStable: prefixStable }, hashChainValid: snapshots.every((item, index) => item.priorSnapshotHash === (snapshots[index - 1]?.snapshotHash ?? null)), rightsVerified: true };
  return writeArtifact(paths.perimeterArchive, 'perimeter-campaign', core);
}

export async function capturePerimeters({ projectRoot = process.cwd(), fetchImpl = globalThis.fetch, clock = () => new Date() } = {}) {
  const vault = await createPublicEvidenceVault({ projectRoot, clock }), metadataInspection = [];
  for (const definition of sources) metadataInspection.push(await captureArcGis(definition, vault, fetchImpl, clock));
  const cwfisCapture = await captureCwfis(vault, fetchImpl, clock), sensorProgression = await captureGoesSensorProgression({ projectRoot, fetchImpl, clock }), campaign = await rebuildCampaign(projectRoot, clock, metadataInspection, cwfisCapture);
  return writeArtifact(closurePaths(projectRoot).perimeterStatus, 'perimeter-campaign-status', { ...campaign, snapshots: undefined, campaignFingerprint: campaign.fingerprint, sensorProgressionFingerprint: sensorProgression.fingerprint, sensorProgressionStates: sensorProgression.states.length });
}

export async function buildPerimeterLabels({ projectRoot = process.cwd(), clock = () => new Date() } = {}) {
  const campaign = await readArtifact(closurePaths(projectRoot).perimeterArchive); if (!campaign) throw new Error('perimeter_campaign_required'); const sensor = await readArtifact(closurePaths(projectRoot).sensorProgression, { states: [] }), grouped = new Map(); for (const item of campaign.snapshots) { const key = `${item.providerId}:${item.incidentId}:${item.authorityClass}`, rows = grouped.get(key) ?? []; rows.push(item); grouped.set(key, rows); }
  const labels = [], rejections = { IDENTICAL: 0, OUTSIDE_TOLERANCE: 0, CORRECTION_OR_CONTRACTION_UNRESOLVED: 0, NON_GEOMETRY_CHANGE: 0, PUBLICATION_CHRONOLOGY_INVALID: 0 };
  for (const rows of grouped.values()) { rows.sort((a, b) => Date.parse(a.providerPublishedAt ?? a.vigiaReceivedAt) - Date.parse(b.providerPublishedAt ?? b.vigiaReceivedAt)); for (let index = 0; index < rows.length - 1; index += 1) { const issue = rows[index]; for (const [horizon, [minimum, maximum]] of Object.entries(HORIZON_DOCTRINE.hours)) { const candidates = rows.slice(index + 1).map((later) => ({ later, offset: (Date.parse(later.providerPublishedAt ?? later.vigiaReceivedAt) - Date.parse(issue.providerPublishedAt ?? issue.vigiaReceivedAt)) / 60_000 })).filter((item) => item.offset >= minimum && item.offset <= maximum).sort((a, b) => Math.abs(a.offset - Number(horizon.slice(0, -1)) * 60) - Math.abs(b.offset - Number(horizon.slice(0, -1)) * 60)); if (!candidates.length) { rejections.OUTSIDE_TOLERANCE += 1; continue; } const { later, offset } = candidates[0], revisionType = classifyPerimeterRevision(issue, later); if (revisionType !== 'GEOMETRY_CHANGE_GROWTH_CANDIDATE') { rejections[revisionType] = (rejections[revisionType] ?? 0) + 1; continue; } if (Date.parse(later.providerPublishedAt) <= Date.parse(issue.providerPublishedAt)) { rejections.PUBLICATION_CHRONOLOGY_INVALID += 1; continue; } const core = { schemaVersion: 'vigia.near-term-perimeter-label.v1', id: `label:${issue.observationId}:${horizon}:${later.observationId}`, incidentId: issue.incidentId, providerId: issue.providerId, labelClass: issue.authorityClass, horizon, targetMinutes: Number(horizon.slice(0, -1)) * 60, actualOffsetMinutes: Number(offset.toFixed(3)), toleranceMinutes: { minimum, maximum }, issueTime: issue.providerPublishedAt, laterTruthTime: later.providerPublishedAt, issueObservationId: issue.observationId, laterObservationId: later.observationId, issueStateHash: issue.stateHash, laterStateHash: later.stateHash, issueRawObjectHash: issue.rawObjectHash, laterRawObjectHash: later.rawObjectHash, revisionType, interpolationUsed: false, futureEvidenceInFeatures: false, knowledgeTimeSeparated: true }; labels.push({ ...core, fingerprint: fingerprint('near-term-perimeter-label', core) }); } } }
  const sensorGroups = new Map(); for (const state of sensor.states) { const rows = sensorGroups.get(state.clusterId) ?? []; rows.push(state); sensorGroups.set(state.clusterId, rows); } for (const [clusterId, rows] of sensorGroups) { rows.sort((a, b) => Date.parse(a.scanStart) - Date.parse(b.scanStart)); for (let index = 0; index < rows.length - 1; index += 1) for (const [horizon, [minimum, maximum]] of Object.entries(HORIZON_DOCTRINE.hours)) { const issue = rows[index], candidate = rows.slice(index + 1).map((later) => ({ later, offset: (Date.parse(later.scanStart) - Date.parse(issue.scanStart)) / 60_000 })).filter((item) => item.offset >= minimum && item.offset <= maximum && item.later.stateHash !== issue.stateHash).sort((a, b) => Math.abs(a.offset - Number(horizon.slice(0, -1)) * 60) - Math.abs(b.offset - Number(horizon.slice(0, -1)) * 60))[0]; if (!candidate) continue; const core = { schemaVersion: 'vigia.near-term-perimeter-label.v1', id: `sensor-label:${clusterId}:${issue.scanStart}:${horizon}:${candidate.later.scanStart}`, incidentId: `GOES-CLUSTER-${clusterId}`, providerId: 'noaa-goes-public', labelClass: 'DERIVED_SENSOR_PROGRESSION', horizon, targetMinutes: Number(horizon.slice(0, -1)) * 60, actualOffsetMinutes: Number(candidate.offset.toFixed(3)), toleranceMinutes: { minimum, maximum }, issueTime: issue.scanStart, laterTruthTime: candidate.later.scanStart, issueObservationId: issue.stateHash, laterObservationId: candidate.later.stateHash, issueStateHash: issue.stateHash, laterStateHash: candidate.later.stateHash, issueRawObjectHash: issue.rawProduct.sha256, laterRawObjectHash: candidate.later.rawProduct.sha256, revisionType: 'SENSOR_DERIVED_FIRE_PIXEL_CHANGE', interpolationUsed: false, futureEvidenceInFeatures: false, knowledgeTimeSeparated: true, authorityClaim: 'NOT_AN_OFFICIAL_PERIMETER' }; labels.push({ ...core, fingerprint: fingerprint('near-term-perimeter-label', core) }); } }
  const horizonCounts = Object.fromEntries(Object.keys(HORIZON_DOCTRINE.hours).map((horizon) => [horizon, labels.filter((item) => item.horizon === horizon).length])), classCounts = Object.fromEntries(PERIMETER_CLASSES.map((name) => [name, labels.filter((item) => item.labelClass === name).length])), officialClasses = new Set(['AUTHORITATIVE_OPERATIONAL_PERIMETER', 'OFFICIAL_REFERENCE_PERIMETER']), officialHorizonCounts = Object.fromEntries(Object.keys(HORIZON_DOCTRINE.hours).map((horizon) => [horizon, labels.filter((item) => item.horizon === horizon && officialClasses.has(item.labelClass)).length])), core = { schemaVersion: 'vigia.near-term-perimeter-label-product.v1', generatedAt: clock().toISOString(), doctrine: HORIZON_DOCTRINE, candidates: [...grouped.values()].reduce((sum, rows) => sum + Math.max(0, rows.length - 1), 0), labels, horizonCounts, officialHorizonCounts, classCounts, rejected: Object.values(rejections).reduce((sum, count) => sum + count, 0), rejectionReasons: rejections, authoritativeOneHour: labels.filter((item) => item.horizon === '1h' && item.labelClass === 'AUTHORITATIVE_OPERATIONAL_PERIMETER').length, authoritativeThreeHour: labels.filter((item) => item.horizon === '3h' && item.labelClass === 'AUTHORITATIVE_OPERATIONAL_PERIMETER').length, sensorDerivedDoesNotSatisfyOfficialGate: true, leakageViolations: 0 };
  return writeArtifact(closurePaths(projectRoot).labels, 'near-term-perimeter-labels', core);
}

export async function campaignStatus({ projectRoot = process.cwd(), clock = () => new Date() } = {}) { const campaign = await readArtifact(closurePaths(projectRoot).perimeterArchive); if (!campaign) throw new Error('perimeter_campaign_required'); const labels = await readArtifact(closurePaths(projectRoot).labels, { horizonCounts: {}, officialHorizonCounts: {} }); return writeArtifact(closurePaths(projectRoot).perimeterStatus, 'perimeter-campaign-status', { schemaVersion: 'vigia.perimeter-campaign-status.v1', generatedAt: clock().toISOString(), campaignFingerprint: campaign.fingerprint, immutableSnapshots: campaign.immutableSnapshots, uniqueProviderPublications: campaign.uniqueProviderPublications, uniqueRawObjects: campaign.uniqueRawObjects, uniquePerimeterRevisions: campaign.uniquePerimeterRevisions, meaningfulChangedStates: campaign.meaningfulChangedStates, incidentsWithThreeMeaningfulStates: campaign.incidentsWithThreeMeaningfulStates, horizonCounts: labels.horizonCounts, officialHorizonCounts: labels.officialHorizonCounts, priorSnapshotsRewritten: campaign.priorSnapshotsRewritten, restartRecovery: campaign.restartRecovery, hashChainValid: campaign.hashChainValid, target: { snapshots: 1000, publications: 100, incidentsWithThreeMeaningfulStates: 25, revisions: 25, oneHourLabels: 10, threeHourLabels: 10 }, state: 'RUNNING_BOUNDED_ON_DEMAND' }); }
