import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { promisify } from 'node:util';
import path from 'node:path';
import { readdir, readFile } from 'node:fs/promises';
import { closurePaths, fingerprint, writeArtifact } from './contracts.mjs';

const execute = promisify(execFile), sha = (value) => `sha256:${createHash('sha256').update(value).digest('hex')}`;
async function fileHash(root, file) { return { path: file, sha256: sha(await readFile(path.join(root, file))) }; }
async function command(binary, args, options = {}) { const result = await execute(binary, args, { timeout: options.timeout ?? 600_000, maxBuffer: options.maxBuffer ?? 64 * 1024 * 1024, cwd: options.cwd, env: { PATH: process.env.PATH, TMPDIR: path.join(options.cwd, '.tmp'), DOCKER_BUILDKIT: '1', BUILDX_CONFIG: path.join(options.cwd, '.tmp/docker-buildx') } }); return result.stdout; }
async function inspect(image, projectRoot) { return JSON.parse(await command('docker', ['image', 'inspect', image], { cwd: projectRoot }))[0]; }
async function sbom(image, projectRoot) { const output = await command('docker', ['sbom', image, '--format', 'spdx-json'], { cwd: projectRoot, timeout: 300_000, maxBuffer: 128 * 1024 * 1024 }); return JSON.parse(output.slice(output.indexOf('{'))); }

export async function buildReleaseImages({ projectRoot = process.cwd(), clock = () => new Date() } = {}) {
  const [apiDockerfile, webDockerfile, lock] = await Promise.all(['infra/Dockerfile.api', 'infra/Dockerfile.web', 'package-lock.json'].map((file) => fileHash(projectRoot, file))), seed = JSON.stringify({ apiDockerfile, webDockerfile, lock }), releaseId = `vigia-scientific-truth-${createHash('sha256').update(seed).digest('hex').slice(0, 16)}`, images = [{ name: `${releaseId}-api`, dockerfile: apiDockerfile }, { name: `${releaseId}-web`, dockerfile: webDockerfile }];
  const built = [];
  for (const image of images) { await command('docker', ['build', '--pull', '--file', image.dockerfile.path, '--tag', image.name, '--label', `org.opencontainers.image.version=${releaseId}`, '--label', 'org.opencontainers.image.source=vigia-intelligence', '.'], { cwd: projectRoot, timeout: 1_200_000 }); const details = await inspect(image.name, projectRoot), bom = await sbom(image.name, projectRoot); built.push({ name: image.name, immutableDigest: details.Id, repoDigests: details.RepoDigests ?? [], created: details.Created, platform: `${details.Os}/${details.Architecture}`, dockerfile: image.dockerfile, baseImage: image.name.endsWith('-api') ? 'node:22-bookworm-slim' : 'nginx:1.27-alpine', sbom: { format: bom.spdxVersion ?? 'SPDX', documentNamespace: bom.documentNamespace, packages: bom.packages?.length ?? 0, fingerprint: fingerprint('image-spdx-sbom', bom), document: bom } }); }
  const bases = [];
  for (const name of ['node:22-bookworm-slim', 'nginx:1.27-alpine']) { await command('docker', ['pull', name], { cwd: projectRoot, timeout: 600_000 }); const details = await inspect(name, projectRoot); bases.push({ name, immutableDigest: details.Id, repoDigests: details.RepoDigests ?? [] }); }
  const migrationDir = path.join(projectRoot, 'apps/api/src/modules/storage/migrations'), migrationNames = (await readdir(migrationDir)).filter((name) => name.endsWith('.sql')).sort(), migrations = await Promise.all(migrationNames.map((name) => fileHash(projectRoot, path.join('apps/api/src/modules/storage/migrations', name)))), dossier = await fileHash(projectRoot, 'docs/architecture/MIGRATION_COMPATIBILITY_DOSSIER.md'), core = { schemaVersion: 'vigia.scientific-truth-release-images.v1', generatedAt: clock().toISOString(), releaseId, images: built, baseImages: bases, dependencyLock: lock, migrations, migrationHead: migrationNames.at(-1), migrationCompatibility: { dossier, agent2Migration: migrationNames.includes('017-intelligence-convergence.sql'), agent1Migration018Present: migrationNames.some((name) => name.startsWith('018')), proposedSecurityMigration: 'docs/architecture/migration-019-security-compartments.sql.proposed', unresolvedMergeTimeDecision: 'Inspect the authoritative integrated migration 018 before activating or renumbering the proposed security/RLS migration.' }, provenance: { builder: 'local-authorized-docker-engine', independentAssuranceClaimed: false, dockerfiles: [apiDockerfile, webDockerfile], dependencyLockFingerprint: lock.sha256 }, reviewerBundleInputs: { immutableImageDigests: built.map((item) => item.immutableDigest), sbomFingerprints: built.map((item) => item.sbom.fingerprint), migrationChecksums: migrations.map((item) => item.sha256) } };
  return writeArtifact(closurePaths(projectRoot).release, 'scientific-truth-release-images', core);
}
