import path from 'node:path';
import { readJson } from '../../shared/json-file.mjs';
import { closurePaths, fingerprint, readArtifact, writeArtifact } from './contracts.mjs';

function splitRows(rows) {
  const groups = new Map(); for (const row of rows) { const key = row.label ?? 'UNLABELLED', values = groups.get(key) ?? []; values.push(row); groups.set(key, values); }
  const splits = { development: [], calibration: [], heldOut: [] };
  for (const values of groups.values()) { values.sort((a, b) => a.id.localeCompare(b.id)); values.forEach((row, index) => { const ratio = (index + 0.5) / values.length, name = ratio <= 0.6 ? 'development' : ratio <= 0.8 ? 'calibration' : 'heldOut'; splits[name].push(row); }); }
  return splits;
}
const splitSummary = (splits) => Object.fromEntries(Object.entries(splits).map(([name, rows]) => [name, { examples: rows.length, positives: rows.filter((item) => item.label === 'POSITIVE').length, negatives: rows.filter((item) => item.label === 'NEGATIVE').length }]));
function leakageAudit(splits) { const owners = new Map(), violations = []; for (const [name, rows] of Object.entries(splits)) for (const row of rows) { const group = row.incidentId ?? row.id, prior = owners.get(group); if (prior && prior !== name) violations.push({ group, prior, current: name }); else owners.set(group, name); if (row.featureCutoff && row.labelAvailableAt && Date.parse(row.labelAvailableAt) <= Date.parse(row.featureCutoff) && row.labelKind === 'LATER_TRUTH') violations.push({ group, reason: 'LABEL_NOT_LATER_THAN_CUTOFF' }); } return { passed: violations.length === 0, violations }; }

export async function buildScientificCorpora({ projectRoot = process.cwd(), clock = () => new Date() } = {}) {
  const paths = closurePaths(projectRoot), [binding, negatives, hard, fuel, terrain, labels] = await Promise.all([paths.binding, paths.negatives, paths.hardNegatives, paths.fuel, paths.terrain, paths.labels].map((file) => readArtifact(file, {}))), [canada, authoritativeLabels] = await Promise.all([readJson(path.join(projectRoot, 'data/validation/evidence-war-room/canada-incident-corpus.json'), { incidents: [] }), readJson(path.join(projectRoot, 'data/validation/authoritative-truth-network/authoritative-labels.json'), { labels: [], horizons: {} })]), incidentById = new Map(canada.incidents.map((item) => [item.id, item]));
  const existence = [];
  for (const row of binding.bindings ?? []) { const incident = incidentById.get(row.incidentId); if (!incident) continue; const maxFrp = Math.max(0, ...row.observations.map((item) => Number(item.frpMw) || 0)); existence.push({ id: `existence:positive:${row.incidentId}`, incidentId: row.incidentId, label: 'POSITIVE', labelAuthority: incident.officialIdentity.authority, labelKind: 'OFFICIAL_INCIDENT', featureCutoff: row.observations[0]?.observedAt, labelAvailableAt: incident.officialObservedAt, features: { qualifyingPhysicalObservation: true, observationCount: row.observationCount, observationTimes: row.uniqueObservationTimes, causalFamilies: row.causalFamilies.length, maximumFrpMw: maxFrp }, lineage: { officialRawProductId: incident.lineage.locationRawProductId, physicalRawProductIds: row.lineage.hotspotRawProductIds } }); }
  for (const packet of (negatives.packets ?? []).filter((item) => item.certified)) existence.push({ id: `existence:negative:${packet.id}`, incidentId: packet.id, label: 'NEGATIVE', labelAuthority: packet.label, labelKind: 'SENSOR_SPECIFIC_NEGATIVE', featureCutoff: packet.timeWindow.to, labelAvailableAt: packet.timeWindow.to, features: { qualifyingPhysicalObservation: false, observationCount: packet.consecutiveValidScans, observationTimes: packet.consecutiveValidScans, causalFamilies: 1, maximumFrpMw: 0 }, lineage: { rawProducts: packet.rawObjectLineage.map((item) => item.sha256) } });
  const existenceSplits = splitRows(existence), existenceLeakage = leakageAudit(existenceSplits), fuelIds = new Set((fuel.packs ?? []).filter((item) => item.coverage === 'COVERED').map((item) => item.incidentId)), terrainIds = new Set((terrain.packs ?? []).filter((item) => item.coverage === 'COVERED').map((item) => item.incidentId)), growth = [];
  for (const row of binding.bindings ?? []) { const incident = incidentById.get(row.incidentId), first = row.observations[0], finalArea = Number(incident?.finalPerimeter?.areaHectares), issueArea = Number(incident?.areaEstimateHectares); if (!incident || !first || !Number.isFinite(finalArea) || Date.parse(incident.finalPerimeter.capturedAt) <= Date.parse(first.observedAt)) continue; const label = finalArea >= 100 || finalArea - (Number.isFinite(issueArea) ? issueArea : 0) >= 50 ? 'POSITIVE' : 'NEGATIVE'; growth.push({ id: `large-growth:${row.incidentId}`, incidentId: row.incidentId, label, labelAuthority: 'Government of Alberta — Alberta Wildfire final perimeter', labelKind: 'LATER_TRUTH', featureCutoff: first.observedAt, labelAvailableAt: incident.finalPerimeter.capturedAt, features: { issueAreaHectares: Number.isFinite(issueArea) ? issueArea : null, firstObservedFrpMw: first.frpMw, fwi: first.quality?.fwi ?? null, fuelType: first.providerDerivedContext?.fuelType ?? null, elevationM: first.providerDerivedContext?.elevationM ?? null, hasOfficialFuelPack: fuelIds.has(row.incidentId), hasOfficialTerrainPack: terrainIds.has(row.incidentId) }, target: { finalAreaHectares: finalArea, threshold: 'final>=100ha OR observed growth>=50ha' } }); }
  const growthSplits = splitRows(growth), growthLeakage = leakageAudit(growthSplits), sensorProgression = (labels.labels ?? []).map((label) => ({ id: `progression:${label.id}`, incidentId: label.incidentId, label: 'POSITIVE', labelAuthority: label.labelClass, labelKind: 'LATER_TRUTH', featureCutoff: label.issueTime, labelAvailableAt: label.laterTruthTime, horizon: label.horizon, issueStateHash: label.issueStateHash, laterStateHash: label.laterStateHash })), officialProgression = (authoritativeLabels.labels ?? []).map((label) => ({ id: `progression:${label.labelId}`, incidentId: label.incidentId, label: 'POSITIVE', labelAuthority: label.authorityClass, labelKind: 'LATER_TRUTH', featureCutoff: label.issueAvailableToVigiaAt, labelAvailableAt: label.laterTruthAvailableToVigiaAt, horizon: label.horizon, issueStateHash: label.issueGeometryHash, laterStateHash: label.laterGeometryHash })), progression = [...sensorProgression, ...officialProgression], progressionSplits = splitRows(progression), progressionLeakage = leakageAudit(progressionSplits), combinedHorizonCounts = Object.fromEntries(['1h', '3h', '6h', '12h', '24h'].map((horizon) => [horizon, Number(labels.horizonCounts?.[horizon] ?? 0) + Number(authoritativeLabels.horizons?.[horizon] ?? 0)]));
  const tasks = {
    fireExistence: { schemaVersion: 'vigia.fire-existence-corpus.v1', eligibility: 'Official positive with attributable physical history, or certified sensor-specific negative with valid opportunity.', examples: existence.length, positives: existence.filter((item) => item.label === 'POSITIVE').length, negatives: existence.filter((item) => item.label === 'NEGATIVE').length, hardNegativesAvailableForAssociationTask: hard.certified ?? 0, splits: existenceSplits, splitSummary: splitSummary(existenceSplits), leakageAudit: existenceLeakage, promotionGate: 'All splits nonempty, both classes in held-out, leakage pass, calibrated comparison before any model promotion.', limitations: ['GOES negatives are sensor-specific absence claims, not absolute no-fire claims.', 'CWFIS physical inputs may incorporate NASA observations and are not independent of the originating satellite family.'] },
    largeFireGrowth: { schemaVersion: 'vigia.large-fire-growth-corpus.v1', eligibility: 'Issue-time physical observation and strictly later official area truth; retrospective context is explicitly flagged.', examples: growth.length, positives: growth.filter((item) => item.label === 'POSITIVE').length, negatives: growth.filter((item) => item.label === 'NEGATIVE').length, splits: growthSplits, splitSummary: splitSummary(growthSplits), leakageAudit: growthLeakage, promotionGate: 'Nonempty development/calibration/held-out, both held-out classes, leakage pass, no-growth and issue-area baselines.', limitations: ['Historical ECCC model runs require formal provider order; hotspot-time FWI is used where present.', 'Final perimeter area is retrospective outcome truth, never an issue-time feature.'] },
    shortHorizonProgression: { schemaVersion: 'vigia.short-horizon-progression-corpus.v1', eligibility: 'A legitimate later changed perimeter revision inside the versioned horizon tolerance.', examples: progression.length, horizonCounts: combinedHorizonCounts, authorityCounts: { official: officialProgression.length, sensorDerived: sensorProgression.length }, splits: progressionSplits, splitSummary: splitSummary(progressionSplits), leakageAudit: progressionLeakage, promotionGate: 'Official and sensor-derived label classes evaluated separately; nonempty held-out horizon cohort.', limitations: ['No interpolation.', 'Sensor-derived progression never satisfies an official-perimeter label gate.'] },
    impactExposure: { schemaVersion: 'vigia.impact-exposure-corpus.v1', eligibility: 'Versioned issue-time exposure plus attributable later impact outcome.', examples: 0, splits: { development: [], calibration: [], heldOut: [] }, splitSummary: splitSummary({ development: [], calibration: [], heldOut: [] }), leakageAudit: { passed: true, violations: [] }, promotionGate: 'Blocked until attributable impact outcomes exist.', limitations: ['No attributable Canadian impact-outcome cohort is present.'] }
  };
  const replayCore = { sourceFingerprints: { binding: binding.fingerprint, negatives: negatives.fingerprint, hard: hard.fingerprint, fuel: fuel.fingerprint, terrain: terrain.fingerprint, sensorLabels: labels.fingerprint, authoritativeLabels: authoritativeLabels.fingerprint ?? null }, taskIds: Object.fromEntries(Object.entries(tasks).map(([name, task]) => [name, Object.values(task.splits).flat().map((item) => item.id).sort()])) }, replayFingerprint = fingerprint('scientific-task-corpora-replay', replayCore), core = { schemaVersion: 'vigia.scientific-task-corpora.v1', generatedAt: clock().toISOString(), tasks, counts: { DISCOVERED: canada.discoveredIncidents ?? canada.incidents.length, BOUND: binding.physicalHistoriesBound ?? 0, COMPLETE: growth.length, ELIGIBLE: existence.length + growth.length + progression.length, REJECTED: (binding.attempted ?? 0) - (binding.physicalHistoriesBound ?? 0) }, replay: { fingerprint: replayFingerprint, verified: replayFingerprint === fingerprint('scientific-task-corpora-replay', replayCore) }, blackBoxModelTrained: false };
  return writeArtifact(paths.corpora, 'scientific-task-corpora', core);
}

function binary(rows, prediction) { let tp = 0, tn = 0, fp = 0, fn = 0; for (const row of rows) { const predicted = prediction(row), positive = row.label === 'POSITIVE'; if (predicted && positive) tp += 1; else if (predicted) fp += 1; else if (positive) fn += 1; else tn += 1; } const divide = (value, total) => total ? value / total : null; return { examples: rows.length, truePositives: tp, trueNegatives: tn, falsePositives: fp, falseNegatives: fn, accuracy: divide(tp + tn, rows.length), precision: divide(tp, tp + fp), recall: divide(tp, tp + fn), specificity: divide(tn, tn + fp), balancedAccuracy: [divide(tp, tp + fn), divide(tn, tn + fp)].every(Number.isFinite) ? (divide(tp, tp + fn) + divide(tn, tn + fp)) / 2 : null }; }
export async function evaluateScience({ projectRoot = process.cwd(), clock = () => new Date() } = {}) {
  const corpora = await readArtifact(closurePaths(projectRoot).corpora); if (!corpora) throw new Error('scientific_task_corpora_required'); const existenceHeld = corpora.tasks.fireExistence.splits.heldOut, growthHeld = corpora.tasks.largeFireGrowth.splits.heldOut, progressionHeld = corpora.tasks.shortHorizonProgression.splits.heldOut;
  const existenceReady = existenceHeld.some((item) => item.label === 'POSITIVE') && existenceHeld.some((item) => item.label === 'NEGATIVE') && corpora.tasks.fireExistence.leakageAudit.passed, growthReady = growthHeld.some((item) => item.label === 'POSITIVE') && growthHeld.some((item) => item.label === 'NEGATIVE') && corpora.tasks.largeFireGrowth.leakageAudit.passed, progressionReady = progressionHeld.length > 0 && corpora.tasks.shortHorizonProgression.leakageAudit.passed;
  const evaluations = { fireExistence: { state: existenceReady ? 'SCORED_NONVACUOUS' : 'BLOCKED', baseline: 'ATTRIBUTABLE_PHYSICAL_CORROBORATION', metrics: existenceReady ? binary(existenceHeld, (row) => row.features.qualifyingPhysicalObservation) : null, qualification: 'Corpus-consistency/corroboration evaluation, not a predictive-skill claim.' }, largeFireGrowth: { state: growthReady ? 'SCORED_NONVACUOUS' : 'BLOCKED', baselines: growthReady ? { noGrowth: binary(growthHeld, () => false), issueArea: binary(growthHeld, (row) => Number(row.features.issueAreaHectares) >= 50) } : null }, shortHorizonProgression: { state: progressionReady ? 'SCORED_NONVACUOUS' : 'BLOCKED', baselines: progressionReady ? { noGrowth: binary(progressionHeld, () => false) } : null }, impactExposure: { state: 'BLOCKED_NO_ATTRIBUTABLE_OUTCOMES', metrics: null } }, scored = Object.values(evaluations).filter((item) => item.state === 'SCORED_NONVACUOUS').length;
  const replayCore = { corporaFingerprint: corpora.fingerprint, evaluations }, replayFingerprint = fingerprint('scientific-evaluation-replay', replayCore), core = { schemaVersion: 'vigia.scientific-evaluation.v1', generatedAt: clock().toISOString(), evaluations, nonVacuousTasks: scored, decision: scored > 0 ? 'NONVACUOUS_SCIENTIFIC_EVALUATION_COMPLETE' : 'BLOCKED_BY_CORPUS', statisticalModelTrained: false, promotionGranted: false, replay: { fingerprint: replayFingerprint, verified: replayFingerprint === fingerprint('scientific-evaluation-replay', replayCore) } };
  return writeArtifact(closurePaths(projectRoot).evaluation, 'scientific-evaluation', core);
}
