import { createHmac,timingSafeEqual } from 'node:crypto';

const SHA256=/^sha256:[a-f0-9]{64}$/;
const EXPECTED_CASES=Object.freeze([
  [1,['overview-truth-first']],[2,['detect-first-event']],[3,['detect-second-event']],[4,['detect-third-event']],[5,['evidence-selected-event']],[6,['handoff-bounded-work']],[7,['prevent-real-comparator','prevent-preview-unavailable-no-substitute']],[8,['source-health-semantics']],[9,['fieldnet-truth-boundary']],[10,['replay-focus-continuity']],[11,['settings-persistence']],[12,['responsive-1600x1000']],[13,['responsive-1440x900']],[14,['responsive-1280x800']],[15,['responsive-1024x768']],[16,['responsive-768x1024']],[17,['responsive-430x932']],[18,['responsive-390x844']],[19,['responsive-320x568']]
]);
function validCases(cases,manifest,evidence){if(!Array.isArray(cases)||cases.length!==EXPECTED_CASES.length)return false;const screenshots=new Set();for(let index=0;index<EXPECTED_CASES.length;index++){const item=cases[index],[number,names]=EXPECTED_CASES[index],expectedPathPrefix=`data/validation/release/operator-console-screenshots/${String(number).padStart(2,'0')}-`;if(item?.case!==number||item?.state!=='PASS'||!names.includes(item?.viewState)||item?.releaseId!==manifest.releaseId||item?.codeStateHash!==manifest.codeStateHash||item?.frontend?.id!=='operator-console'||item?.frontend?.path!==manifest.canonicalOperatorConsole?.path||item?.frontend?.origin!==manifest.canonicalOperatorConsole?.origin||item?.frontend?.sourceHash!==manifest.canonicalOperatorConsole?.sourceHash||item?.frontend?.assetDigest!==evidence.frontend.assetDigest||!SHA256.test(item?.screenshotSha256??'')||typeof item?.screenshot!=='string'||!item.screenshot.startsWith(expectedPathPrefix)||item.screenshot!==`${expectedPathPrefix}${item.viewState}.png`||item.screenshot.includes('..')||screenshots.has(item.screenshot)||Number(item?.horizontalOverflowPx)>1||!Number.isFinite(Number(item?.viewport?.width))||!Number.isFinite(Number(item?.viewport?.height)))return false;screenshots.add(item.screenshot);}return true;}
function validScenarios(rows){if(!Array.isArray(rows)||rows.length!==24||new Set(rows.map((item)=>item?.scenario)).size!==24||!rows.every((item)=>Number.isInteger(item?.scenario)&&item.scenario>=1&&item.scenario<=24&&item?.state==='PASS'&&item?.evidence&&typeof item.evidence==='object'))return false;return rows.map((item)=>item.scenario).sort((a,b)=>a-b).every((value,index)=>value===index+1);}
function validPerformance(evidence){const intelligence=evidence?.intelligencePerformance,ui=evidence?.performanceMs;if(!intelligence||typeof intelligence!=='object'||!ui||typeof ui!=='object')return false;return Number.isFinite(Number(intelligence.cachedProjectionMaximumMs))&&Number(intelligence.cachedProjectionMaximumMs)<25&&Number.isFinite(Number(intelligence.inboxHttpMs))&&Number(intelligence.inboxHttpMs)<100&&(intelligence.projectionP95Ms===null||Number.isFinite(Number(intelligence.projectionP95Ms))&&Number(intelligence.projectionP95Ms)<75)&&Number.isFinite(Number(ui.routeSwitchMaximum))&&Number.isFinite(Number(ui.eventSelectionMaximum));}
function canonical(value){if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map((key)=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;return JSON.stringify(value);}
export function browserAttestationMac(evidence,attestationKey){const unsigned={...evidence};delete unsigned.attestationMac;return`hmac-sha256:${createHmac('sha256',attestationKey).update(canonical(unsigned)).digest('hex')}`;}
function browserPeerValid(evidence,browserRuntime){const peer=evidence?.attestation?.browserProcess;if(!browserRuntime||evidence?.browserRuntime?.schemaVersion!=='vigia.browser-certification-browser.v1'||JSON.stringify(evidence.browserRuntime)!==JSON.stringify(browserRuntime)||!Number.isInteger(peer?.pid)||peer.pid<=0||peer.executableSha256!==browserRuntime.sha256||peer.endpoint!==evidence.cdpUrl||!/^http:\/\/127\.0\.0\.1:\d{2,5}$/.test(peer.endpoint??'')||!/^[a-f0-9]{48}$/.test(peer.profileNonce??''))return false;return true;}
function attestationValid(evidence,{attestationKey,runNonce,browserRuntime}){if(typeof attestationKey!=='string'||attestationKey.length<43||typeof runNonce!=='string'||!/^[a-f0-9]{64}$/.test(runNonce)||!browserPeerValid(evidence,browserRuntime))return false;const attestation=evidence?.attestation;if(attestation?.schemaVersion!=='vigia.browser-certification-attestation.v2'||attestation.runNonce!==runNonce||!Number.isInteger(attestation.producerPid)||attestation.producerPid<=0||typeof attestation.browserVersion!=='string'||!attestation.browserVersion)return false;const supplied=String(evidence.attestationMac??''),expected=browserAttestationMac(evidence,attestationKey),left=Buffer.from(supplied),right=Buffer.from(expected);return left.length===right.length&&timingSafeEqual(left,right);}

export function browserEvidenceMatches(evidence,manifest,{attestationKey,runNonce,browserRuntime}={}){return evidence?.schemaVersion==='vigia.running-browser-certification.v6'&&evidence?.state==='PASS'&&evidence.releaseId===manifest?.releaseId&&evidence.codeStateHash===manifest?.codeStateHash&&evidence.operationalDataHash===manifest?.operationalDataHash&&evidence.certifiedRuntimeReleaseStatementHash===manifest?.releaseStatementHash&&evidence.frontend?.id==='operator-console'&&evidence.frontend?.path===manifest?.canonicalOperatorConsole?.path&&evidence.frontend?.origin===manifest?.canonicalOperatorConsole?.origin&&evidence.frontend?.sourceHash===manifest?.canonicalOperatorConsole?.sourceHash&&SHA256.test(evidence.frontend?.assetDigest??'')&&(!manifest?.canonicalOperatorConsole?.assetDigest||evidence.frontend.assetDigest===manifest.canonicalOperatorConsole.assetDigest)&&evidence.assetDigestVerified===true&&evidence.remoteAssetDigestVerified===true&&Number.isInteger(evidence.remoteAssetFiles)&&evidence.remoteAssetFiles>0&&Number.isInteger(evidence.remoteAssetBytes)&&evidence.remoteAssetBytes>0&&evidence.realPortugalEventsVerified===3&&evidence.consoleErrors===0&&evidence.unexpectedHttpErrors===0&&evidence.routeNotFoundOccurrences===0&&evidence.identityContradictions===0&&evidence.browserTransport==='CERTIFIER_OWNED_CDP'&&validCases(evidence.cases,manifest,evidence)&&validScenarios(evidence.intelligenceScenarios)&&validPerformance(evidence)&&attestationValid(evidence,{attestationKey,runNonce,browserRuntime});}

export function classifyBrowserCertificationFailure(error) {
  const diagnostic = [error?.message, error?.stderr, error?.stdout].filter(Boolean).join('\n');
  if (/MachPortRendezvousServer/i.test(diagnostic) && /Permission denied \(1100\)/i.test(diagnostic)) {
    return {
      state: 'BLOCKED',
      code: 'HOST_BROWSER_PROCESS_SANDBOX_DENIED',
      evidence: 'Chromium was terminated before page creation because macOS denied MachPortRendezvousServer registration (Permission denied 1100).',
    };
  }
  return {
    state: 'FAIL',
    code: 'BROWSER_CERTIFICATION_EXECUTION_FAILED',
    evidence: String(error?.message ?? error ?? 'unknown_browser_certification_failure').split('\n')[0].slice(0, 500),
  };
}
