import { constants } from 'node:fs';
import { chmod,lstat,mkdir,mkdtemp,open,readdir,realpath,rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileNoFollow } from './safe_artifact.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const siteRoots=Object.freeze(['playwright','playwright-1.54.0.dist-info','pyee','pyee-13.0.1.dist-info','greenlet','greenlet-3.5.4.dist-info','typing_extensions.py','typing_extensions-4.16.0.dist-info']);
const expectedStartupHooks=Object.freeze(['_virtualenv.pth']);
const runtimeLimits=Object.freeze({maximumEntries:12_000,maximumDepth:32,maximumBytes:512*1024*1024,maximumStandardLibraryBytes:128*1024*1024,maximumDependencyBytes:384*1024*1024,maximumHookBytes:256*1024,maximumFileBytes:256*1024*1024,deadlineMs:60_000});
const sha256=(value)=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
const mode=(value)=>(value&0o777).toString(8).padStart(4,'0');
const posix=(value)=>value.split(path.sep).join('/');

function deadline(existing=null){const expiresAt=existing?.expiresAt??Date.now()+runtimeLimits.deadlineMs;return{expiresAt,check(){if(Date.now()>expiresAt)throw new Error('certification_runtime_deadline_exceeded');}};}
function phaseBounds(deadlineValue){return{deadline:deadlineValue,entries:0,bytes:0,add(metadata,{depth=0,maximumBytes=runtimeLimits.maximumBytes}={}){deadlineValue.check();if(depth>runtimeLimits.maximumDepth)throw new Error('certification_runtime_depth_exceeded');this.entries+=1;this.bytes+=Number(metadata.size??0);if(this.entries>runtimeLimits.maximumEntries)throw new Error('certification_runtime_entry_limit_exceeded');if(this.bytes>runtimeLimits.maximumBytes||Number(metadata.size??0)>maximumBytes)throw new Error('certification_runtime_byte_limit_exceeded');}};}
async function hashedRegularFile(file,{maximum=runtimeLimits.maximumFileBytes,bounds=null,depth=0}={}){bounds?.deadline?.check();const descriptor=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{const metadata=await descriptor.stat();if(!metadata.isFile()||metadata.size>maximum)throw new Error(`certification_runtime_file_invalid:${file}`);bounds?.add(metadata,{depth,maximumBytes:maximum});const hash=createHash('sha256');for await(const chunk of descriptor.createReadStream({autoClose:false})){bounds?.deadline?.check();hash.update(chunk);}return{digest:`sha256:${hash.digest('hex')}`,metadata};}finally{await descriptor.close();}}
async function regularDirectory(directory){const metadata=await lstat(directory);if(metadata.isSymbolicLink()||!metadata.isDirectory())throw new Error(`certification_runtime_directory_invalid:${directory}`);}
async function collectTree(base,roots,{excludeSitePackages=false,maximumBytes=runtimeLimits.maximumBytes,bounds}={}){const entries=[],files=[];let treeBytes=0;async function visit(absolute,relative,depth){bounds.deadline.check();if(depth>runtimeLimits.maximumDepth)throw new Error('certification_runtime_depth_exceeded');const metadata=await lstat(absolute);if(metadata.isSymbolicLink())throw new Error(`certification_runtime_symlink_rejected:${relative}`);if(metadata.isDirectory()){if(path.basename(absolute)==='__pycache__'||excludeSitePackages&&relative==='site-packages')return;bounds.add({size:0},{depth});for(const child of await readdir(absolute))await visit(path.join(absolute,child),relative?path.join(relative,child):child,depth+1);return;}if(!metadata.isFile()||relative.endsWith('.pyc')||path.basename(relative)==='RECORD'&&relative.includes('.dist-info'))return;treeBytes+=metadata.size;if(treeBytes>maximumBytes)throw new Error('certification_runtime_root_byte_limit_exceeded');const hashed=await hashedRegularFile(absolute,{bounds,depth});const relativePath=posix(relative);entries.push(`${relativePath}\0${mode(hashed.metadata.mode)}\0${hashed.digest}`);files.push({source:absolute,relative:relativePath,bytes:hashed.metadata.size,mode:mode(hashed.metadata.mode),digest:hashed.digest});}for(const item of roots)await visit(path.join(base,item),item,0);entries.sort();files.sort((a,b)=>a.relative.localeCompare(b.relative));return{entryCount:entries.length,digest:sha256(entries.join('\n')),_files:files};}
async function startupHooks(sitePackages,bounds){bounds.deadline.check();const names=(await readdir(sitePackages)).filter((name)=>name.endsWith('.pth')||['sitecustomize.py','usercustomize.py'].includes(name)).sort();if(JSON.stringify(names)!==JSON.stringify(expectedStartupHooks))throw new Error(`certification_runtime_startup_hooks_invalid:${names.join(',')}`);const entries=[],files=[];let hookBytes=0;for(const name of names){const file=path.join(sitePackages,name),hashed=await hashedRegularFile(file,{maximum:64*1024,bounds});hookBytes+=hashed.metadata.size;if(hookBytes>runtimeLimits.maximumHookBytes)throw new Error('certification_runtime_hook_byte_limit_exceeded');entries.push(`${name}\0${mode(hashed.metadata.mode)}\0${hashed.digest}`);files.push({source:file,relative:name,bytes:hashed.metadata.size,mode:mode(hashed.metadata.mode),digest:hashed.digest});}return{names,entryCount:entries.length,digest:sha256(entries.join('\n')),_files:files};}
export function assertCertificationRuntimeMatches(actual,expected,label='complete'){if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(`browser_certification_runtime_lock_mismatch:${label}`);}
export function publicCertificationRuntime(runtime){const clean=(value)=>{if(Array.isArray(value))return value.map(clean);if(!value||typeof value!=='object')return value;return Object.fromEntries(Object.entries(value).filter(([key])=>!key.startsWith('_')).map(([key,item])=>[key,clean(item)]));},result=clean(runtime);for(const field of ['python','pyvenv','stdlib','sitePackages','runtimeRoot','pythonHome','sourceRuntimeDigest','snapshotRoot','lockFile'])delete result[field];return result;}

export async function inspectCertificationRuntime({projectRoot=root,runtimeRoot=null,deadlineValue=null}={}){
  const activeDeadline=deadline(deadlineValue),bounds=phaseBounds(activeDeadline);activeDeadline.check();
  const pythonVersion='3.12',venvRoot=runtimeRoot??path.join(projectRoot,'.venv'),pythonLink=path.join(venvRoot,'bin/python'),python=runtimeRoot?pythonLink:await realpath(pythonLink),pythonRoot=runtimeRoot?venvRoot:path.resolve(path.dirname(python),'..'),stdlib=path.join(pythonRoot,'lib',`python${pythonVersion}`),sitePackages=path.join(venvRoot,'lib',`python${pythonVersion}`,'site-packages'),pyvenv=path.join(venvRoot,'pyvenv.cfg');
  await Promise.all([regularDirectory(venvRoot),regularDirectory(path.join(venvRoot,'lib')),regularDirectory(path.join(venvRoot,'lib',`python${pythonVersion}`)),regularDirectory(sitePackages),regularDirectory(stdlib)]);
  const pythonFile=await hashedRegularFile(python,{maximum:64*1024*1024,bounds}),pyvenvFile=await hashedRegularFile(pyvenv,{maximum:64*1024,bounds});
  const standardLibrary=await collectTree(stdlib,['.'],{excludeSitePackages:true,maximumBytes:runtimeLimits.maximumStandardLibraryBytes,bounds}),dependencies=await collectTree(sitePackages,siteRoots,{maximumBytes:runtimeLimits.maximumDependencyBytes,bounds}),hooks=await startupHooks(sitePackages,bounds),publicStandard={entryCount:standardLibrary.entryCount,digest:standardLibrary.digest},publicDependencies={entryCount:dependencies.entryCount,digest:dependencies.digest},publicHooks={names:hooks.names,entryCount:hooks.entryCount,digest:hooks.digest};
  const copyFiles=[{source:python,relative:'bin/python',bytes:pythonFile.metadata.size,mode:mode(pythonFile.metadata.mode),digest:pythonFile.digest},{source:pyvenv,relative:'pyvenv.cfg',bytes:pyvenvFile.metadata.size,mode:mode(pyvenvFile.metadata.mode),digest:pyvenvFile.digest},...standardLibrary._files.map((item)=>({...item,relative:posix(path.join('lib',`python${pythonVersion}`,item.relative))})),...dependencies._files.map((item)=>({...item,relative:posix(path.join('lib',`python${pythonVersion}`,'site-packages',item.relative))})),...hooks._files.map((item)=>({...item,relative:posix(path.join('lib',`python${pythonVersion}`,'site-packages',item.relative))}))];
  return{schemaVersion:'vigia.browser-certification-runtime.v1',platform:process.platform,architecture:process.arch,pythonVersion,pythonExecutable:{sha256:pythonFile.digest,bytes:pythonFile.metadata.size,mode:mode(pythonFile.metadata.mode)},pyvenvConfig:{sha256:pyvenvFile.digest,bytes:pyvenvFile.metadata.size},standardLibrary:publicStandard,dependencies:{...publicDependencies,roots:[...siteRoots]},startupHooks:publicHooks,runtimeDigest:sha256(JSON.stringify({python:pythonFile.digest,pyvenv:pyvenvFile.digest,standardLibrary:publicStandard,dependencies:publicDependencies,hooks:publicHooks})),python,pyvenv,stdlib,sitePackages,_copyFiles:copyFiles};
}

export async function verifyCertificationRuntime({projectRoot=root,runtimeRoot=null,lockOverride,deadlineValue=null}={}){const activeDeadline=deadline(deadlineValue),lockFile=path.join(projectRoot,'scripts/release/browser-certification-runtime-lock.json'),lock=lockOverride??JSON.parse(await readFileNoFollow(lockFile,{root:projectRoot,encoding:'utf8',maxBytes:128*1024})),runtime=await inspectCertificationRuntime({projectRoot,runtimeRoot,deadlineValue:activeDeadline});assertCertificationRuntimeMatches(publicCertificationRuntime(runtime),lock);return{...runtime,lockFile,runtimeRoot:runtimeRoot??null};}

async function copyLockedRuntime(source,destination,deadlineValue){
  const bounds=phaseBounds(deadlineValue),base=path.resolve(destination),prefix=`${base}${path.sep}`;
  for(const item of source._copyFiles??[]){
    bounds.deadline.check();const target=path.resolve(base,item.relative);if(!target.startsWith(prefix))throw new Error('certification_runtime_copy_path_rejected');
    await mkdir(path.dirname(target),{recursive:true,mode:0o700});const input=await open(item.source,constants.O_RDONLY|constants.O_NOFOLLOW),output=await open(target,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL,0o700);let copied=0;const hash=createHash('sha256');
    try{const metadata=await input.stat();if(!metadata.isFile()||metadata.size!==item.bytes)throw new Error('certification_runtime_copy_source_changed');bounds.add(metadata,{depth:item.relative.split('/').length});for await(const chunk of input.createReadStream({autoClose:false})){bounds.deadline.check();copied+=chunk.length;hash.update(chunk);let offset=0;while(offset<chunk.length){const written=await output.write(chunk,offset,chunk.length-offset,null);if(!written.bytesWritten)throw new Error('certification_runtime_copy_write_failed');offset+=written.bytesWritten;}}if(copied!==item.bytes||`sha256:${hash.digest('hex')}`!==item.digest)throw new Error('certification_runtime_copy_source_changed');await output.sync();}
    finally{await Promise.allSettled([input.close(),output.close()]);}
    await chmod(target,Number.parseInt(item.mode,8));
  }
}

async function sealTree(directory,deadlineValue,bounds=phaseBounds(deadlineValue),depth=0){deadlineValue.check();if(depth>runtimeLimits.maximumDepth)throw new Error('certification_runtime_depth_exceeded');bounds.add({size:0},{depth});const entries=await readdir(directory,{withFileTypes:true});for(const entry of entries){deadlineValue.check();const child=path.join(directory,entry.name);if(entry.isSymbolicLink())throw new Error(`certification_runtime_snapshot_symlink_rejected:${child}`);if(entry.isDirectory()){await sealTree(child,deadlineValue,bounds,depth+1);await chmod(child,0o500);}else if(entry.isFile()){const metadata=await lstat(child);bounds.add(metadata,{depth});await chmod(child,metadata.mode&0o111?0o500:0o400);}else throw new Error(`certification_runtime_snapshot_entry_invalid:${child}`);}await chmod(directory,0o500);}
async function makeTreeRemovable(directory){const metadata=await lstat(directory).catch((error)=>error?.code==='ENOENT'?null:Promise.reject(error));if(!metadata)return;if(metadata.isDirectory()){await chmod(directory,0o700);for(const entry of await readdir(directory,{withFileTypes:true}))if(entry.isDirectory())await makeTreeRemovable(path.join(directory,entry.name));}}

export async function materializeCertificationRuntime({projectRoot=root}={}){
  const activeDeadline=deadline(),source=await verifyCertificationRuntime({projectRoot,deadlineValue:activeDeadline}),temporaryRoot=path.join(projectRoot,'.tmp/browser');activeDeadline.check();await mkdir(temporaryRoot,{recursive:true,mode:0o700});const snapshotRoot=await mkdtemp(path.join(temporaryRoot,'certification-runtime-'));
  try{await copyLockedRuntime(source,snapshotRoot,activeDeadline);const snapshot=await verifyCertificationRuntime({projectRoot,runtimeRoot:snapshotRoot,lockOverride:publicCertificationRuntime(source),deadlineValue:activeDeadline});await sealTree(snapshotRoot,activeDeadline);return{...snapshot,pythonHome:snapshotRoot,sourceRuntimeDigest:source.runtimeDigest,snapshotRoot};}catch(error){await makeTreeRemovable(snapshotRoot);await rm(snapshotRoot,{recursive:true,force:true});throw error;}
}

export async function destroyCertificationRuntimeSnapshot(runtime){if(!runtime?.snapshotRoot)return;await makeTreeRemovable(runtime.snapshotRoot);await rm(runtime.snapshotRoot,{recursive:true,force:true});}

if(path.resolve(process.argv[1]??'')===fileURLToPath(import.meta.url))process.stdout.write(`${JSON.stringify(publicCertificationRuntime(await inspectCertificationRuntime()),null,2)}\n`);
