import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runDbDoctor } from '../db_doctor.mjs';
import { refreshReleaseStatement } from './build_release_manifest.mjs';
import { certifyRequiredRoutes,resolveCertificationIncidentId } from './route_resolver.mjs';
import { signFieldRequest } from '../../packages/domain/src/fieldnet/request-auth.mjs';
import { fieldControlRequest } from '../fieldnet/control-request.mjs';
import { readBoundedResponse } from './bounded-response.mjs';
import { governedOperatorConsoleHeaders } from '../command-survival/runtime_client.mjs';
import { signOperatorProxyRequest } from '../../packages/domain/src/operator-proxy/request-auth.mjs';
import { atomicWriteNoFollow,readFileNoFollow } from './safe_artifact.mjs';
import { bindCertificationEvidence,removeCertificationEvidence } from './release_statement.mjs';
import { CERTIFICATION_REFERENCES,CERTIFICATION_SCOPES,pendingCertification } from './certification_semantics.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),manifestFile=path.join(root,'data/validation/release/current-release-manifest.json'),commandSurvivalProofFile=path.join(root,'data/validation/command-survival/controlled-exercise-proof.json'),central=String(process.env.VIGIA_BASE_URL??'http://127.0.0.1:4177').replace(/\/$/,''),field=String(process.env.FIELDNET_BASE_URL??'http://127.0.0.1:4188').replace(/\/$/,''),operatorOrigin=process.env.VIGIA_OPERATOR_CONSOLE_ORIGIN??'http://127.0.0.1:4190',operatorConsoleHeaders=governedOperatorConsoleHeaders({operatorOrigin}),operatorProxyKey=String(process.env.VIGIA_OPERATOR_PROXY_KEY??process.env.VIGIA_OPERATOR_TOKEN??'');
async function request(url,{cookie=null,timeoutMs=20_000,method='GET',body=null,headers:requestHeaders={}}={}){const started=performance.now(),parsed=new URL(url),protectedField=url.startsWith(field)&&parsed.pathname.startsWith('/api/fieldnet/')&&parsed.pathname!=='/api/fieldnet/release',intent=!['GET','HEAD'].includes(method)?'operator-console':'',signedHeaders=protectedField?signFieldRequest({method,path:parsed.pathname,keyId:process.env.FIELDNET_CONTROL_KEY_ID??'field-operator',key:process.env.FIELDNET_CONTROL_KEY,body:body?JSON.parse(body):null}):{},centralHeaders=url.startsWith(central)?{...operatorConsoleHeaders,...signOperatorProxyRequest({key:operatorProxyKey,releaseId:manifest.releaseId,method,path:`${parsed.pathname}${parsed.search}`,bodyBytes:body?Buffer.from(body):Buffer.alloc(0),intent})}:{},headers={...centralHeaders,...signedHeaders,...requestHeaders,...(intent?{'x-vigia-operator-intent':intent}:{})};if(protectedField&&process.env.FIELDNET_CONTROL_SOCKET)return fieldControlRequest({socketPath:process.env.FIELDNET_CONTROL_SOCKET,path:`${parsed.pathname}${parsed.search}`,method,headers,body,timeoutMs,logicalUrl:url});const response=await fetch(url,{method,headers,body,signal:AbortSignal.timeout(timeoutMs)}),{body:responseBody}=await readBoundedResponse(response,{maxBytes:8*1024*1024});return{url,status:response.status,ok:response.ok,body:responseBody,durationMs:Number((performance.now()-started).toFixed(3)),setCookies:response.headers.getSetCookie?.()??[]};}
function assert(value,code,details={}){if(value)return;const error=new Error(code);error.details=details;throw error;}
function cookieHeader(values){return values.map((value)=>value.split(';')[0]).join('; ');}

const manifest=JSON.parse(await readFileNoFollow(manifestFile,{root,encoding:'utf8'})),startedAt=new Date().toISOString();
const centralRelease=await request(`${central}/api/v10/release`),fieldRelease=await request(`${field}/api/fieldnet/release`);
assert(centralRelease.ok,'central_release_unavailable',centralRelease);assert(fieldRelease.ok,'fieldnode_release_unavailable',fieldRelease);
assert(centralRelease.body.runtimeProfile==='remote_shadow'&&fieldRelease.body.runtimeProfile==='remote_shadow','certification_requires_sealed_remote_shadow_runtime',{central:centralRelease.body.runtimeProfile,fieldNode:fieldRelease.body.runtimeProfile});
assert(centralRelease.body.releaseId===manifest.releaseId,'central_release_id_mismatch',{expected:manifest.releaseId,actual:centralRelease.body.releaseId});
assert(fieldRelease.body.releaseId===manifest.releaseId,'fieldnode_release_id_mismatch',{expected:manifest.releaseId,actual:fieldRelease.body.releaseId});
assert(centralRelease.body.codeStateHash===manifest.codeStateHash&&fieldRelease.body.codeStateHash===manifest.codeStateHash,'runtime_code_state_mismatch');
assert(centralRelease.body.operationalDataHash===manifest.operationalDataHash&&fieldRelease.body.operationalDataHash===manifest.operationalDataHash,'runtime_operational_data_mismatch');
assert(centralRelease.body.releaseStatementHash===manifest.releaseStatementHash&&fieldRelease.body.releaseStatementHash===manifest.releaseStatementHash,'runtime_release_statement_mismatch');
for(const key of ['databaseSchemaVersion','migrationHead','ontologyContractVersion','intelligenceRuleSetVersion']){assert(centralRelease.body[key]===manifest.contracts[key]||centralRelease.body.contracts?.[key]===manifest.contracts[key],`central_release_contract_mismatch:${key}`,{expected:manifest.contracts[key],actual:centralRelease.body[key]??centralRelease.body.contracts?.[key]});assert(fieldRelease.body.contracts?.[key]===manifest.contracts[key],`fieldnode_release_contract_mismatch:${key}`,{expected:manifest.contracts[key],actual:fieldRelease.body.contracts?.[key]});}

const sessionFirst=await request(`${central}/api/v10/session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intent:'operator-proxy-assertion'})}),cookie=cookieHeader(sessionFirst.setCookies),sessionReload=await request(`${central}/api/v10/session`);
assert(sessionFirst.ok&&sessionReload.ok,'session_route_unavailable');assert(sessionFirst.body.authenticated===true&&sessionReload.body.authenticated===true,'session_not_authenticated');
assert(sessionFirst.body.actor?.id===sessionReload.body.actor?.id&&sessionFirst.body.actor?.name===sessionReload.body.actor?.name&&sessionFirst.body.actor?.title===sessionReload.body.actor?.title,'session_reload_identity_mismatch');
assert(sessionReload.body.actor?.name==='Miguel Almeida'&&sessionReload.body.actor?.title==='Shadow Operator','unexpected_local_operator_identity');

let commandSurvivalProof=null;try{commandSurvivalProof=JSON.parse(await readFileNoFollow(commandSurvivalProofFile,{root,encoding:'utf8'}));}catch{}
let incidentResolution=null;try{incidentResolution=resolveCertificationIncidentId({proof:commandSurvivalProof});}catch(error){if(error.message!=='governed_certification_incident_unresolved')throw error;const incidentsResult=await request(`${field}/api/fieldnet/incidents`);incidentResolution=resolveCertificationIncidentId({proof:commandSurvivalProof,fieldIncidents:incidentsResult.ok?incidentsResult.body:null});}
const {incidentId}=incidentResolution,routeContext={incidentId};
const centralRouteResults=await certifyRequiredRoutes({routes:manifest.requiredRoutes.central,baseUrl:central,family:'central',context:routeContext,request,requestOptions:{cookie}}),routeResults=[...centralRouteResults];
const preventionList=await request(`${central}/api/v10/prevention/findings`,{cookie}),findingId=preventionList.body?.findings?.[0]?.findingId;assert(findingId,'prevention_finding_required_for_consensus_certification');
const preventionDetail=await request(`${central}/api/v10/prevention/findings/${encodeURIComponent(findingId)}`,{cookie}),preventionConsensus=await request(`${central}/api/v10/validation/prevention-consensus/${encodeURIComponent(findingId)}`,{cookie}),allowedConsensus=new Set(['ROBUST_INTERVENTION_ZONE','MIXED_INTERVENTION_ZONE','UNSTABLE_INTERVENTION_GEOMETRY','NO_DEFENSIBLE_INTERVENTION_ZONE','INSUFFICIENT_EVIDENCE','ROBUST_ZONE','MIXED_ZONE','UNSTABLE_GEOMETRY','NO_DEFENSIBLE_ZONE']);
assert(preventionDetail.ok&&preventionConsensus.ok,'prevention_consensus_route_failed');assert(preventionDetail.body?.consensusTopology?.state===preventionConsensus.body?.consensus?.state,'prevention_consensus_projection_mismatch');assert(allowedConsensus.has(preventionConsensus.body?.consensus?.state),'prevention_consensus_state_invalid',{state:preventionConsensus.body?.consensus?.state});
routeResults.push({id:'prevention-detail',product:'PREVENTION',family:'central-supplementary',path:`/api/v10/prevention/findings/${findingId}`,method:'GET',status:preventionDetail.status,durationMs:preventionDetail.durationMs,schemaVersion:preventionDetail.body?.consensusTopology?.schemaVersion??null},{id:'prevention-consensus',product:'VALIDATION',family:'central-supplementary',path:`/api/v10/validation/prevention-consensus/${findingId}`,method:'GET',status:preventionConsensus.status,durationMs:preventionConsensus.durationMs,schemaVersion:preventionConsensus.body?.consensus?.schemaVersion??null});
const commandBody=(await request(`${central}/api/v10/workspaces/command`,{cookie})).body,bootstrap=(await request(`${central}/api/v2/bootstrap`,{cookie})).body;
for(const [surface,actor] of [['session',sessionReload.body.actor],['command',commandBody.actor],['bootstrap',bootstrap.actor]])assert(actor?.id===sessionReload.body.actor.id&&actor?.name===sessionReload.body.actor.name&&actor?.title===sessionReload.body.actor.title,`session_identity_mismatch:${surface}`,{actor});

const fieldNodeRouteResults=await certifyRequiredRoutes({routes:manifest.requiredRoutes.fieldNode,baseUrl:field,family:'fieldNode',context:routeContext,request});routeResults.push(...fieldNodeRouteResults);

const db=await runDbDoctor({databaseUrl:process.env.VIGIA_DATABASE_URL});assert(db.classification==='READY','database_schema_not_ready',{classification:db.classification,migrations:db.migrations?.state});assert(db.migrations?.latestVersion===manifest.contracts.migrationHead,'migration_head_mismatch',{expected:manifest.contracts.migrationHead,actual:db.migrations?.latestVersion});
const completedAt=new Date().toISOString(),targets={central,fieldNode:field},certifiedRuntimeReleaseStatementHash=manifest.releaseStatementHash,routeEvidence={schemaVersion:'vigia.route-certification.v1',releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,certifiedRuntimeReleaseStatementHash,targets,startedAt,completedAt,state:'PASS',certificationIncident:{incidentId,source:incidentResolution.source},routes:routeResults,requiredRouteFamilies:{central:{required:centralRouteResults.length,passed:centralRouteResults.filter((item)=>item.status>=200&&item.status<300).length},fieldNode:{required:fieldNodeRouteResults.length,passed:fieldNodeRouteResults.filter((item)=>item.status>=200&&item.status<300).length}},required:routeResults.length,passed:routeResults.filter((item)=>item.status>=200&&item.status<300).length,maximumDurationMs:Math.max(...routeResults.map((item)=>item.durationMs))};
const sessionEvidence={schemaVersion:'vigia.session-certification.v1',releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,certifiedRuntimeReleaseStatementHash,targets,completedAt,state:'PASS',identity:{id:sessionReload.body.actor.id,name:sessionReload.body.actor.name,title:sessionReload.body.actor.title,role:sessionReload.body.actor.role},surfaces:['session','command','bootstrap'],reloadPersistent:true,httpOnlyCookieIssued:sessionFirst.setCookies.some((value)=>/HttpOnly/i.test(value)),contradictions:0};
const handshake={schemaVersion:'vigia.release-handshake.v1',releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,certifiedRuntimeReleaseStatementHash,targets,completedAt,state:'PASS',components:{web:{releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,releaseStatementHash:certifiedRuntimeReleaseStatementHash,contracts:manifest.contracts},api:centralRelease.body,fieldNode:fieldRelease.body},failures:[]};
const routeEvidenceBytes=`${JSON.stringify(routeEvidence,null,2)}\n`,sessionEvidenceBytes=`${JSON.stringify(sessionEvidence,null,2)}\n`,handshakeBytes=`${JSON.stringify(handshake,null,2)}\n`;
await Promise.all([atomicWriteNoFollow(path.join(root,'data/validation/release/route-contract-certification.json'),routeEvidenceBytes,{root}),atomicWriteNoFollow(path.join(root,'data/validation/release/session-certification.json'),sessionEvidenceBytes,{root}),atomicWriteNoFollow(path.join(root,'data/validation/release/release-handshake.json'),handshakeBytes,{root})]);
bindCertificationEvidence(manifest,{routes:routeEvidenceBytes,session:sessionEvidenceBytes,handshake:handshakeBytes});removeCertificationEvidence(manifest,['browser','screenshots']);
manifest.certification={...manifest.certification,schema:{state:'PASS',scope:CERTIFICATION_SCOPES.schema,checkedAt:db.checkedAt,evidence:CERTIFICATION_REFERENCES.schema,databaseSchemaVersion:manifest.contracts.databaseSchemaVersion,migrationHead:db.migrations.latestVersion,postgisVersion:db.postgres.postgisVersion},routes:{state:'PASS',scope:CERTIFICATION_SCOPES.routes,checkedAt:completedAt,required:routeEvidence.required,passed:routeEvidence.passed,certifiedRuntimeReleaseStatementHash,evidence:CERTIFICATION_REFERENCES.routes},session:{state:'PASS',scope:CERTIFICATION_SCOPES.session,checkedAt:completedAt,identity:sessionEvidence.identity,reloadPersistent:true,contradictions:0,certifiedRuntimeReleaseStatementHash,evidence:CERTIFICATION_REFERENCES.session},fieldNode:{state:'PASS',scope:CERTIFICATION_SCOPES.fieldNode,checkedAt:completedAt,evidence:CERTIFICATION_REFERENCES.fieldNode,releaseId:fieldRelease.body.releaseId,contractVersion:fieldRelease.body.contracts.fieldNodeContractVersion}};
manifest.certification.browser=pendingCertification(CERTIFICATION_SCOPES.browser,CERTIFICATION_REFERENCES.browser,'Route recertification changed the release statement; canonical browser certification must run against the recut release.');manifest.screenshotEvidence={state:'PENDING_ROUTE_RECERTIFICATION',entries:[]};
manifest.testEvidence={state:'ROUTE_CERTIFICATION_COMPLETE_RECUT_REQUIRED',checkedAt:completedAt,routeCount:routeEvidence.required,routePasses:routeEvidence.passed,sessionContradictions:0,handshake:'data/validation/release/release-handshake.json'};
await refreshReleaseStatement(manifest);
process.stdout.write(`${JSON.stringify({state:'RECUT_REQUIRED',releaseId:manifest.releaseId,routes:`${routeEvidence.passed}/${routeEvidence.required}`,session:sessionEvidence.identity.name,fieldNode:fieldRelease.body.contracts.fieldNodeContractVersion,migrationHead:db.migrations.latestVersion,next:'rebuild_and_redeploy_exact_release_statement'})}\n`);
