import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { constants } from 'node:fs';
import { open } from 'node:fs/promises';
import { request as httpRequest } from 'node:http';
import { request as httpsRequest } from 'node:https';
import path from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { runDbDoctor } from '../db_doctor.mjs';
import { classifyReleasePath } from './build_release_manifest.mjs';
import { readBoundedResponse } from './bounded-response.mjs';
import { CERTIFICATION_EVIDENCE_PATHS,verifyCertificationEvidenceBindings,verifyReleaseBundle } from './release_statement.mjs';
import { readFileNoFollow,verifyDirectoryChain } from './safe_artifact.mjs';

const exec=promisify(execFile),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),releaseDir=path.join(root,'data/validation/release');
const sha256=(value)=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
const assert=(value,code,details={})=>{if(value)return;throw Object.assign(new Error(code),{details});};
const base=(value,fallback)=>String(value??fallback).replace(/\/+$/,'');

async function readJson(name,maxBytes=32*1024*1024){return JSON.parse(await readFileNoFollow(path.join(releaseDir,name),{root,encoding:'utf8',maxBytes}));}
async function readEvidenceBytes(){const rows=await Promise.all(Object.entries(CERTIFICATION_EVIDENCE_PATHS).map(async([id,relativePath])=>[id,await readFileNoFollow(path.join(root,relativePath),{root,maxBytes:32*1024*1024})]));return Object.fromEntries(rows);}
async function requestJson(url,{timeoutMs=5_000,maxBytes=2*1024*1024}={}){const parsed=new URL(url),requestImpl=parsed.protocol==='http:'?httpRequest:parsed.protocol==='https:'?httpsRequest:null;assert(requestImpl,'final_release_runtime_protocol_invalid',{url,protocol:parsed.protocol});return new Promise((resolve,reject)=>{const request=requestImpl(parsed,{method:'GET',headers:{accept:'application/json'}},(response)=>{const status=Number(response.statusCode??0),declared=Number(response.headers['content-length']),chunks=[];let bytes=0,settled=false;const fail=(error)=>{if(settled)return;settled=true;request.destroy();reject(error);};if(Number.isFinite(declared)&&declared>maxBytes)return fail(Object.assign(new Error('bounded_http_response_exceeded'),{statusCode:502,details:{maxBytes}}));response.on('data',(chunk)=>{if(settled)return;bytes+=chunk.length;if(bytes>maxBytes)return fail(Object.assign(new Error('bounded_http_response_exceeded'),{statusCode:502,details:{maxBytes}}));chunks.push(chunk);});response.once('error',fail);response.once('end',()=>{if(settled)return;settled=true;try{assert(status>=200&&status<300,'final_release_runtime_unavailable',{url,status});resolve(JSON.parse(Buffer.concat(chunks,bytes).toString('utf8')));}catch(error){reject(error);}});});request.setTimeout(timeoutMs,()=>request.destroy(Object.assign(new Error('final_release_runtime_timeout'),{details:{url,timeoutMs}})));request.once('error',reject);request.end();});}
async function fetchJson(fetchImpl,url,options={}){if(!fetchImpl)return requestJson(url,options);const response=await fetchImpl(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(options.timeoutMs??5_000)}),{body}=await readBoundedResponse(response,{maxBytes:options.maxBytes??2*1024*1024});assert(response.ok,'final_release_runtime_unavailable',{url,status:response.status});return body;}
async function sourceMetadata(relativePath){const file=path.join(root,relativePath);let handle;try{handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);const metadata=await handle.stat();assert(metadata.isFile(),'final_release_source_not_regular',{relativePath});return{path:relativePath,classification:classifyReleasePath(relativePath),mode:(metadata.mode&0o111)?'0755':'0644',sha256:sha256(await handle.readFile())};}finally{await handle?.close();}}
async function verifyCurrentSource(releaseSource){const{stdout}=await exec('git',['ls-files','-co','--exclude-standard','-z'],{cwd:root,encoding:'buffer',maxBuffer:128*1024*1024}),paths=[...new Set(stdout.toString('utf8').split('\0').filter(Boolean))].filter((name)=>['SOURCE — release code','TEST','DEPLOYMENT DATA'].includes(classifyReleasePath(name))).sort(),entries=[];for(const name of paths)entries.push(await sourceMetadata(name));assert(entries.length===releaseSource.entries.length,'final_release_source_inventory_changed',{expected:releaseSource.entries.length,actual:entries.length});for(let index=0;index<entries.length;index+=1){const expected=releaseSource.entries[index],actual=entries[index];assert(expected.path===actual.path&&expected.classification===actual.classification&&expected.mode===actual.mode&&expected.sha256===actual.sha256,'final_release_source_entry_changed',{expected,actual});}return entries.length;}
function assertRuntimeIdentity(actual,manifest,component){assert(actual?.runtimeProfile==='remote_shadow',`final_release_${component}_profile_mismatch`,{actual:actual?.runtimeProfile});for(const field of ['releaseId','codeStateHash','operationalDataHash','releaseStatementHash'])assert(actual?.[field]===manifest[field],`final_release_${component}_${field}_mismatch`,{expected:manifest[field],actual:actual?.[field]});for(const[name,value]of Object.entries(manifest.contracts??{}))assert((actual?.contracts?.[name]??actual?.[name])===value,`final_release_${component}_contract_mismatch:${name}`,{expected:value,actual:actual?.contracts?.[name]??actual?.[name]});}
function assertEvidenceIdentity(value,manifest,name){assert(value?.releaseId===manifest.releaseId&&value?.codeStateHash===manifest.codeStateHash&&value?.operationalDataHash===manifest.operationalDataHash,`final_release_${name}_identity_mismatch`);assert(value?.state==='PASS',`final_release_${name}_not_pass`);}
function assertCertifiedRuntimeIdentity(actual,manifest,statementHash,component){for(const field of ['releaseId','codeStateHash','operationalDataHash'])assert(actual?.[field]===manifest[field],`final_release_${component}_${field}_mismatch`,{expected:manifest[field],actual:actual?.[field]});assert(actual?.releaseStatementHash===statementHash,`final_release_${component}_releaseStatementHash_mismatch`);for(const[name,value]of Object.entries(manifest.contracts??{}))assert((actual?.contracts?.[name]??actual?.[name])===value,`final_release_${component}_contract_mismatch:${name}`);}
function assertRequiredRoutes(routeEvidence,manifest){
  for(const[family,expectedRoutes]of Object.entries({central:manifest.requiredRoutes?.central??[],fieldNode:manifest.requiredRoutes?.fieldNode??[]})){
    const summary=routeEvidence.requiredRouteFamilies?.[family];assert(summary?.required===expectedRoutes.length&&summary?.passed===expectedRoutes.length,`final_release_${family}_route_family_incomplete`);
    for(const expected of expectedRoutes){const matches=routeEvidence.routes?.filter((item)=>item.family===family&&item.id===expected.id)??[];assert(matches.length===1&&matches[0].method===expected.method&&matches[0].product===expected.product&&matches[0].status>=200&&matches[0].status<300,`final_release_required_route_mismatch:${family}:${expected.id}`);}
  }
  assert(routeEvidence.required===routeEvidence.routes?.length&&routeEvidence.passed===routeEvidence.required&&manifest.certification.routes.required===routeEvidence.required&&manifest.certification.routes.passed===routeEvidence.passed,'final_release_route_evidence_incomplete');
}
function assertCertificationSummaries({manifest,routeEvidence,sessionEvidence,handshake,browserEvidence,screenshotEvidence}){
  const routeRuntimeHash=routeEvidence.certifiedRuntimeReleaseStatementHash,browserRuntimeHash=browserEvidence.certifiedRuntimeReleaseStatementHash;
  assert(/^sha256:[a-f0-9]{64}$/.test(routeRuntimeHash??'')&&sessionEvidence.certifiedRuntimeReleaseStatementHash===routeRuntimeHash&&handshake.certifiedRuntimeReleaseStatementHash===routeRuntimeHash,'final_release_route_runtime_statement_binding_invalid');
  assert(manifest.certification.routes.certifiedRuntimeReleaseStatementHash===routeRuntimeHash&&manifest.certification.session.certifiedRuntimeReleaseStatementHash===routeRuntimeHash,'final_release_route_runtime_statement_summary_mismatch');
  assertCertifiedRuntimeIdentity(handshake.components?.api,manifest,routeRuntimeHash,'handshake_api');assertCertifiedRuntimeIdentity(handshake.components?.fieldNode,manifest,routeRuntimeHash,'handshake_fieldnode');
  assert(/^sha256:[a-f0-9]{64}$/.test(browserRuntimeHash??'')&&screenshotEvidence.certifiedRuntimeReleaseStatementHash===browserRuntimeHash&&manifest.certification.browser.certifiedRuntimeReleaseStatementHash===browserRuntimeHash,'final_release_browser_runtime_statement_binding_invalid');
  assert(JSON.stringify(manifest.certification.session.identity)===JSON.stringify(sessionEvidence.identity)&&manifest.certification.session.reloadPersistent===sessionEvidence.reloadPersistent&&manifest.certification.session.contradictions===sessionEvidence.contradictions,'final_release_session_summary_mismatch');
  assert(manifest.certification.browser.cases===browserEvidence.cases?.length,'final_release_browser_summary_mismatch:cases');
  for(const field of ['realPortugalEventsVerified','consoleErrors','unexpectedHttpErrors','routeNotFoundOccurrences','identityContradictions'])assert(manifest.certification.browser[field]===browserEvidence[field],`final_release_browser_summary_mismatch:${field}`);
  assert(manifest.screenshotEvidence.required===screenshotEvidence.required&&manifest.screenshotEvidence.captured===screenshotEvidence.captured&&JSON.stringify(manifest.screenshotEvidence.entries)===JSON.stringify(screenshotEvidence.entries),'final_release_screenshot_summary_mismatch');
}

export async function verifyFinalRelease({env=process.env,fetchImpl=null,databaseUrl=env.VIGIA_DATABASE_URL}={}){
  await verifyDirectoryChain(root,releaseDir,{create:false});
  const[releaseSource,manifest,statement,evidenceBytes]=await Promise.all([readJson('release-source-manifest.json'),readJson('current-release-manifest.json'),readJson('release-statement.json'),readEvidenceBytes()]),evidence=Object.fromEntries(Object.entries(evidenceBytes).map(([id,bytes])=>[id,JSON.parse(bytes.toString('utf8'))])),routeEvidence=evidence.routes,sessionEvidence=evidence.session,handshake=evidence.handshake,browserEvidence=evidence.browser,screenshotEvidence=evidence.screenshots;
  const bundle=verifyReleaseBundle({releaseSource,manifest,statement,expectedStatementHash:env.VIGIA_APPROVED_RELEASE_STATEMENT_SHA256,requireExternal:true}),certificationEvidenceHashes=verifyCertificationEvidenceBindings(manifest,evidenceBytes),verifiedFiles=await verifyCurrentSource(releaseSource);
  for(const name of ['schema','routes','session','fieldNode','browser'])assert(manifest.certification?.[name]?.state==='PASS',`final_release_certification_incomplete:${name}`);
  assertEvidenceIdentity(routeEvidence,manifest,'route_evidence');assertRequiredRoutes(routeEvidence,manifest);
  assertEvidenceIdentity(sessionEvidence,manifest,'session_evidence');assert(sessionEvidence.reloadPersistent===true&&sessionEvidence.contradictions===0,'final_release_session_evidence_incomplete');
  assertEvidenceIdentity(handshake,manifest,'handshake');
  assertEvidenceIdentity(browserEvidence,manifest,'browser_evidence');assert(browserEvidence.cases?.length===19&&browserEvidence.cases.every((item)=>item.state==='PASS'),'final_release_browser_cases_incomplete');assert(browserEvidence.consoleErrors===0&&browserEvidence.unexpectedHttpErrors===0&&browserEvidence.routeNotFoundOccurrences===0&&browserEvidence.identityContradictions===0,'final_release_browser_errors_present');
  assertEvidenceIdentity(screenshotEvidence,manifest,'screenshot_evidence');assert(screenshotEvidence.required===19&&screenshotEvidence.captured===19&&screenshotEvidence.entries?.length===19,'final_release_screenshot_evidence_incomplete');
  assertCertificationSummaries({manifest,routeEvidence,sessionEvidence,handshake,browserEvidence,screenshotEvidence});
  const screenshotPaths=new Set();for(const entry of screenshotEvidence.entries){assert(entry.releaseId===manifest.releaseId&&entry.state==='PASS'&&!screenshotPaths.has(entry.path),'final_release_screenshot_entry_invalid',{path:entry.path});screenshotPaths.add(entry.path);const bytes=await readFileNoFollow(path.join(root,entry.path),{root,maxBytes:20*1024*1024});assert(sha256(bytes)===entry.sha256,'final_release_screenshot_digest_mismatch',{path:entry.path});}
  assert(manifest.canonicalOperatorConsole?.assetDigest===browserEvidence.frontend?.assetDigest&&manifest.canonicalOperatorConsole?.sourceHash===browserEvidence.frontend?.sourceHash,'final_release_operator_evidence_mismatch');
  const central=base(env.VIGIA_BASE_URL,'http://127.0.0.1:4177'),field=base(env.FIELDNET_BASE_URL,'http://127.0.0.1:4188'),operator=base(env.VIGIA_OPERATOR_URL??env.VIGIA_OPERATOR_CONSOLE_ORIGIN,manifest.canonicalOperatorConsole.origin),[apiIdentity,fieldIdentity,operatorIdentity]=await Promise.all([fetchJson(fetchImpl,`${central}/api/v10/release`),fetchJson(fetchImpl,`${field}/api/fieldnet/release`),fetchJson(fetchImpl,`${operator}/__operator/ready`)]);
  assertRuntimeIdentity(apiIdentity,manifest,'api');assertRuntimeIdentity(fieldIdentity,manifest,'fieldnode');for(const fieldName of ['releaseId','codeStateHash','operationalDataHash','releaseStatementHash'])assert(operatorIdentity?.[fieldName]===manifest[fieldName],`final_release_operator_${fieldName}_mismatch`);assert(operatorIdentity?.frontend==='operator-console'&&operatorIdentity?.path===manifest.canonicalOperatorConsole.path&&operatorIdentity?.sourceHash===manifest.canonicalOperatorConsole.sourceHash&&operatorIdentity?.assetDigest===manifest.canonicalOperatorConsole.assetDigest,'final_release_operator_identity_mismatch');
  const db=await runDbDoctor({databaseUrl,runtimeInspection:false});assert(db.classification==='READY','final_release_database_not_ready',{classification:db.classification});assert(db.migrations?.latestVersion===manifest.contracts.migrationHead&&db.migrations?.expectedLatestVersion===manifest.contracts.migrationHead,'final_release_migration_mismatch',{migrations:db.migrations});assert(db.postgres?.postgis===true,'final_release_postgis_missing');
  return{schemaVersion:'vigia.final-release-verification.v1',state:'PASS',verifiedAt:new Date().toISOString(),releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,releaseStatementHash:manifest.releaseStatementHash,manifestEvidenceHash:manifest.manifestEvidenceHash,certificationEvidenceHashes,contracts:manifest.contracts,verifiedFiles,routePasses:`${routeEvidence.passed}/${routeEvidence.required}`,browserCases:`${browserEvidence.cases.length}/19`,screenshots:`${screenshotEvidence.captured}/19`,database:{classification:db.classification,migrationHead:db.migrations.latestVersion,postgisVersion:db.postgres.postgisVersion},runtimes:{api:apiIdentity.component??'api',fieldNode:fieldIdentity.component??'fieldnode',operator:operatorIdentity.frontend},bundle};
}

if(path.resolve(process.argv[1]??'')===fileURLToPath(import.meta.url))process.stdout.write(`${JSON.stringify(await verifyFinalRelease())}\n`);
