import { createHash } from 'node:crypto';
import { constants } from 'node:fs';
import { lstat,open,readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { verifyReleaseBundle } from './release_statement.mjs';

const projectRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const hash=(value)=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
const profile=String(process.argv.find((value)=>value.startsWith('--profile='))?.split('=',2)[1]??process.argv[process.argv.indexOf('--profile')+1]??'');
const PROFILES=Object.freeze({
  api:{directories:['apps/api','apps/field-node','packages','scripts','data/config','data/reference','data/replay/corpus','data/replay/results','data/validation/measurement-debt','data/validation/fieldnet','data/validation/pilot'],files:['package.json','package-lock.json','data/validation/detection/portugal-2023-v4-confirmatory-benchmark.json','data/validation/detection/portugal-2024-small-fire-opportunity.json','data/validation/detection/sentinel3-portugal-2024-product-manifest.json','data/validation/physical-sensing/gold-specialist-handoff.json','data/validation/prevention/portugal-sentinel2-review-corpus-v3.json','data/validation/prevention/portugal-sentinel2-expert-review-pack-v1.json','data/validation/prevention/portugal-sentinel2-expert-review-key-v1.json','data/validation/prevention/consensus-topology-evaluation-v1.json'],exclude:[]},
  operator:{directories:['apps/operator-console','apps/api/src/modules/storage/migrations','apps/api/src/modules/basemap'],files:['apps/api/src/shared/fetch.mjs','apps/api/src/shared/ttl-cache.mjs','apps/api/src/shared/request-gate.mjs','apps/api/src/shared/pinned-https-fetch.mjs','scripts/release/build_release_manifest.mjs','scripts/release/release_statement.mjs','scripts/release/safe_artifact.mjs','scripts/release/verify_deployment_source.mjs','packages/domain/src/release-contract.mjs','packages/domain/src/operator-proxy/request-auth.mjs','apps/api/src/modules/storage/postgres-migration-runner.mjs','data/replay/raw/openstreetmap/portugal-thermal-context-v1/portugal-boundary.json'],exclude:['apps/operator-console/dist']}
});
if(!PROFILES[profile])throw new Error('deployment_source_profile_required');
const limits={manifestBytes:32*1024*1024,maxFiles:20_000,maxFileBytes:64*1024*1024,maxAggregateBytes:1024*1024*1024};
function relative(value){return path.relative(projectRoot,value).replaceAll(path.sep,'/');}
function excluded(value){const name=value.replaceAll(path.sep,'/');return /(?:^|\/)(?:\.cache|\.next|\.tmp|\.venv|__pycache__|node_modules|coverage|dist|build|playwright-report|test-results)(?:\/|$)|(?:^|\/)\.DS_Store$|\.(?:log|pid|sock|tmp)$/i.test(name)||PROFILES[profile].exclude.some((prefix)=>name===prefix||name.startsWith(`${prefix}/`));}
async function lockedRead(file,maxBytes=limits.maxFileBytes){let handle;try{handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);const metadata=await handle.stat();if(!metadata.isFile()||metadata.size>maxBytes)throw new Error(`deployment_source_file_invalid:${relative(file)}`);return{bytes:await handle.readFile(),metadata};}catch(error){if(error?.code==='ELOOP')throw new Error(`deployment_source_symlink_forbidden:${relative(file)}`);throw error;}finally{await handle?.close();}}
async function walk(directory,output){for(const entry of await readdir(directory,{withFileTypes:true})){const absolute=path.join(directory,entry.name),name=relative(absolute);if(excluded(name))continue;const metadata=await lstat(absolute);if(metadata.isSymbolicLink())throw new Error(`deployment_source_symlink_forbidden:${name}`);if(metadata.isDirectory()){await walk(absolute,output);continue;}if(!metadata.isFile())throw new Error(`deployment_source_entry_invalid:${name}`);output.push(absolute);if(output.length>limits.maxFiles)throw new Error('deployment_source_file_count_exceeded');}}
const manifestFile=path.join(projectRoot,'data/validation/release/release-source-manifest.json'),releaseFile=path.join(projectRoot,'data/validation/release/current-release-manifest.json'),statementFile=path.join(projectRoot,'data/validation/release/release-statement.json'),manifest=JSON.parse((await lockedRead(manifestFile,limits.manifestBytes)).bytes.toString('utf8')),release=JSON.parse((await lockedRead(releaseFile,limits.manifestBytes)).bytes.toString('utf8')),statement=JSON.parse((await lockedRead(statementFile,limits.manifestBytes)).bytes.toString('utf8'));
const bundle=verifyReleaseBundle({releaseSource:manifest,manifest:release,statement,expectedStatementHash:process.env.VIGIA_APPROVED_RELEASE_STATEMENT_SHA256,requireExternal:true});
const selected=(name)=>PROFILES[profile].files.includes(name)||PROFILES[profile].directories.some((prefix)=>name===prefix||name.startsWith(`${prefix}/`))&&!excluded(name),expected=new Map((manifest.entries??[]).filter((item)=>selected(item.path)).map((item)=>[item.path,item]));
const actual=[];for(const directory of PROFILES[profile].directories)await walk(path.join(projectRoot,directory),actual);for(const file of PROFILES[profile].files)actual.push(path.join(projectRoot,file));
let aggregateBytes=0;const seen=new Set();for(const file of actual.sort()){const name=relative(file);if(seen.has(name))continue;seen.add(name);const expectedEntry=expected.get(name);if(!expectedEntry)throw new Error(`deployment_source_unexpected_file:${name}`);const{bytes,metadata}=await lockedRead(file);aggregateBytes+=bytes.length;if(aggregateBytes>limits.maxAggregateBytes)throw new Error('deployment_source_aggregate_bytes_exceeded');const mode=(metadata.mode&0o111)?'0755':'0644';if(mode!==expectedEntry.mode||hash(bytes)!==expectedEntry.sha256)throw new Error(`deployment_source_digest_mismatch:${name}`);}
for(const name of expected.keys())if(!seen.has(name))throw new Error(`deployment_source_missing_file:${name}`);
process.stdout.write(`${JSON.stringify({state:'PASS',profile,...bundle,profileVerifiedFiles:seen.size,verifiedBytes:aggregateBytes})}\n`);
