import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,incidentCounts,taskCounts,filterIncidents,incidentsFor,tasksFor,updateTask,addVerificationTask,parseRoute,routeURL,csv,incidentFor} from '../src/data/model.js';
import {BASE_INCIDENTS,QUESTIONS,PERIODS} from '../src/data/fixtures.js';
import {createDemoProvider,assertLiveAdapter} from '../src/data/provider.js';
import {escapeHTML} from '../src/ui/html.js';
test('fixture incident IDs are unique',()=>assert.equal(new Set(BASE_INCIDENTS.map(x=>x.id)).size,BASE_INCIDENTS.length));
test('incident categories reconcile to the dataset',()=>{const c=incidentCounts(BASE_INCIDENTS);assert.equal(c.total,c.candidate+c.confirmed+c.monitored);assert.equal(c.candidate,11);assert.equal(c.confirmed,3);});
test('unavailable incident counts remain null',()=>assert.equal(incidentCounts(null),null));
test('unavailable task counts remain null',()=>assert.equal(taskCounts(null),null));
test('successfully empty task counts are zero',()=>assert.deepEqual(taskCounts([]),{attention:0,progress:0,waiting:0,completed:0,total:0}));
test('limited state does not return a fabricated empty collection',()=>{const s={...initialState(),variant:'limited'};assert.equal(incidentsFor(s),null);assert.equal(tasksFor(s),null);});
test('search filters by location case-insensitively',()=>assert.equal(filterIncidents(BASE_INCIDENTS,{search:'LEVER'})[0].id,'lever'));
test('status and regional filters compose',()=>{const r=filterIncidents(BASE_INCIDENTS,{region:'Norte',status:'candidate'});assert.equal(r.length,3);assert.ok(r.every(x=>x.region==='Norte'&&x.status==='candidate'));});
test('no search matches stays empty',()=>assert.equal(filterIncidents(BASE_INCIDENTS,{search:'no-such-record-000'}).length,0));
test('task counts reconcile without including invented response actions',()=>{const c=taskCounts(tasksFor(initialState()));assert.equal(c.total,4);assert.equal(c.attention+c.progress+c.waiting+c.completed,c.total);});
test('tasks are scoped to their selected incident',()=>{const a=tasksFor(initialState());const b=tasksFor({...initialState(),selected:'valongo'});assert.ok(a.every(t=>t.incidentId==='lever'));assert.ok(b.every(t=>t.incidentId==='valongo'));assert.notEqual(a[0].id,b[0].id);});
test('updating ownership does not mutate the prior state',()=>{const s=initialState(),id=tasksFor(s)[0].id;const n=updateTask(s,id,{owner:'Duty analyst'});assert.equal(tasksFor(n)[0].owner,'Duty analyst');assert.equal(tasksFor(s)[0].owner,'Exercise Controller');});
test('read-only state rejects task mutation',()=>assert.throws(()=>updateTask({...initialState(),variant:'readonly'},'lever:official',{status:'progress'}),/read-only/));
test('limited state rejects task mutation',()=>assert.throws(()=>updateTask({...initialState(),variant:'limited'},'lever:official',{status:'progress'}),/read-only/));
test('unknown task cannot be changed',()=>assert.throws(()=>updateTask(initialState(),'other:official',{status:'progress'}),/Select a task/));
test('invalid state transition value is rejected',()=>assert.throws(()=>updateTask(initialState(),'lever:official',{status:'dispatch'}),/Invalid/));
test('task completion does not change incident verification',()=>{const s=initialState(),n=updateTask(s,'lever:official',{status:'completed'});assert.equal(incidentFor(n).verified,false);});
test('verification request reuses existing active task',()=>{const result=addVerificationTask(initialState(),QUESTIONS[0]);assert.equal(result.created,false);assert.equal(tasksFor(result.state).length,4);});
test('verification request creates a new task only when needed',()=>{const result=addVerificationTask(initialState(),QUESTIONS[3]);assert.equal(result.created,true);assert.equal(tasksFor(result.state).length,5);assert.equal(result.task.owner,'Unassigned');});
test('global awareness URL retains a compatible alias',()=>assert.equal(parseRoute('#/global-awareness').route,'national-awareness'));
test('selected incident IDs are preserved in route URLs',()=>{const r=parseRoute(routeURL('intelligence','test:id'));assert.equal(r.params.get('id'),'test:id');});
test('region query is retained on the incident list',()=>assert.equal(parseRoute('#/incidents?region=Norte').params.get('region'),'Norte'));
test('unrecognized incident is not silently substituted',()=>assert.equal(incidentFor(initialState(),'missing'),null));
test('HTML escaping handles injected markup',()=>assert.equal(escapeHTML('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;'));
test('CSV export quotes commas and newlines safely',()=>assert.equal(csv([['a,b','x\ny']]),'"a,b","x\ny"'));
test('CSV export neutralizes spreadsheet formulas',()=>assert.equal(csv([['=2+2']]),'"\'=2+2"'));
test('period review totals are internally consistent',()=>{for(const p of Object.values(PERIODS)){assert.equal(p.reviewed,p.resolved+p.open);assert.equal(p.reviewed,p.series.reduce((a,b)=>a+b,0));assert.equal(p.reviewed,p.categories.reduce((a,b)=>a+b[1],0));}});
test('provider persists and restores preview state in an injected store',()=>{const m=new Map(),store={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};const p=createDemoProvider(store);p.write({...p.read(),selected:'valongo'});assert.equal(createDemoProvider(store).read().selected,'valongo');});
test('provider handles denied storage without crashing',()=>{const p=createDemoProvider({getItem(){throw new Error('denied');},setItem(){throw new Error('denied');}});assert.equal(p.read().version,1);assert.equal(p.write(p.read()),false);});
test('provider rejects malformed saved state',()=>{const p=createDemoProvider({getItem:()=>'{bad json'});assert.equal(p.read().selected,'lever');});
test('reset restores the initial demo data',()=>{const p=createDemoProvider(null);p.write({...p.read(),selected:'valongo'});assert.equal(p.reset().selected,'lever');});
test('live adapter never silently falls back to demo',()=>{assert.throws(()=>assertLiveAdapter(null),/not configured/);assert.throws(()=>assertLiveAdapter(createDemoProvider(null)),/not configured/);});
test('unknown incident has no task collection',()=>assert.equal(tasksFor({...initialState(),selected:'__proto__'}),null));
