const arr=(...values)=>values.find(Array.isArray)??[];
const object=(...values)=>values.find((value)=>value&&typeof value==='object'&&!Array.isArray(value))??{};
const values=(value)=>Array.isArray(value)?value:Object.values(value??{});
const human=(value)=>String(value??'').replaceAll('_',' ');
const outside=(state)=>['OUT','REHABILITATION','DEMOBILIZED'].includes(state);
const finding=(advisories,crewId)=>advisories.filter((item)=>item.affectedCrewId===crewId);

function normalizePerson(person,crews,assignments){
  const crew=crews.find((item)=>item.crewId===person.currentCrewId),assignment=assignments.find((item)=>item.assignmentId===crew?.assignmentId),accountability=person.accountability??{};
  return{...person,status:person.status??person.operationalState,crewId:person.crewId??person.currentCrewId,assignment:person.assignment??assignment?.text??assignment?.objectiveId,operationalArea:person.operationalArea??person.location?.operationalAreaId??crew?.operationalAreaId,entryAt:person.entryAt??accountability.entryTime,lastContactAt:person.lastContactAt??person.location?.observedAt,exitConfirmed:person.exitConfirmed??outside(person.operationalState),inHazardZone:person.inHazardZone??!outside(person.operationalState)};
}

function normalizeCrew(crew,advisories,assignments){
  const warnings=finding(advisories,crew.crewId).length?finding(advisories,crew.crewId):(crew.advisories??[]),rules=warnings.map((item)=>item.rule??item.type),assignment=assignments.find((item)=>item.assignmentId===crew.assignmentId);
  const integrity=rules.includes('CREW_SEPARATION')?'SEPARATION_ADVISORY':rules.includes('EVACUATION_NOT_ALL_OUTSIDE')?'MEMBER_NOT_CONFIRMED_OUTSIDE':rules.includes('CONTACT_OR_MOVEMENT_LOST')?'MEMBER_LOCATION_STALE':warnings.length?'EXCEPTION':'ALL_TOGETHER';
  return{...crew,state:crew.state??crew.operationalState,operationalArea:crew.operationalArea??crew.operationalAreaId,memberCount:crew.memberCount??crew.memberIds?.length,assignment:crew.assignment??assignment?.text??assignment?.objectiveId,lastProgressAt:crew.lastProgressAt??assignment?.lastProgressAt,progressReportState:crew.progressReportState??(rules.includes('PROGRESS_REPORT_OVERDUE')?'OVERDUE':'CURRENT'),integrityState:crew.integrityState??integrity,advisories:warnings};
}

function normalizeOrder(order,crews,people){
  const intended=order.intendedRecipients??[],recipients=(order.recipients?.length?order.recipients:intended.map((id)=>{const crew=crews.find((item)=>item.crewId===id),delivered=(order.deliveries??[]).some((item)=>[item.receiver,item.recipientId,item.crewId].includes(id))||(intended.length===1&&(order.deliveries??[]).length>0),acknowledged=(order.acknowledgements??[]).some((item)=>[item.recipientId,item.crewId].includes(id))||(intended.length===1&&(order.acknowledgements??[]).length>0),members=(crew?.memberIds??[]).map((personId)=>people.find((person)=>person.personId===personId)).filter(Boolean);return{crewId:id,name:crew?.name??id,deliveryState:delivered?'DELIVERED':'UNCONFIRMED',acknowledgementState:acknowledged?'ACKNOWLEDGED':'UNCONFIRMED',membersOutside:members.filter((person)=>person.exitConfirmed).length,totalMembers:crew?.memberIds?.length,parState:'PAR UNCONFIRMED'};}))??[];
  return{...order,type:order.type??order.orderType,title:order.title??order.text??order.orderType,recipients};
}

const consequence=(type)=>({PUMP_ENGAGED_NO_FLOW:'Pump engagement is not delivering water to committed crews.',WATER_SUPPLY_DEGRADED:'Sustainable suppression capability may be below current demand.',COMMUNICATIONS_LOST:'Closed-loop orders and welfare checks may be delayed.',ESCAPE_ROUTE_THREATENED:'Affected crews may lose their planned egress.'}[type]??'The change may alter the current tactical decision.');
const required=(type)=>({PUMP_ENGAGED_NO_FLOW:'Confirm backup water or withdraw exposed crews.',WATER_SUPPLY_DEGRADED:'Confirm sustainable secondary supply.',COMMUNICATIONS_LOST:'Establish alternate communications and verify affected crews.',ESCAPE_ROUTE_THREATENED:'Confirm another viable egress route.'}[type]??'Owner must verify the condition and record the decision.');
function normalizeChange(item){return{...item,id:item.id??item.criticalChangeId,changeId:item.changeId??item.criticalChangeId,title:item.title??human(item.type),severity:item.severity??'CRITICAL',whatChanged:item.whatChanged??item.scope??human(item.type),whyItMatters:item.whyItMatters??consequence(item.type),affected:item.affected??[...(item.affectedCrewIds??[]),...(item.affectedOperationalAreaIds??[])],requiredAction:item.requiredAction??required(item.type),verification:item.verification??item.verificationState,audience:item.audience??item.targeting?.rationale?.commandRoles};}
function normalizeWater(states,sources){const water=states.at(-1)??{};return{...water,primarySource:water.primarySource??water.waterSourceId??sources[0]?.waterSourceId,secondarySource:water.secondarySource??sources[1]?.waterSourceId,pumpEngaged:water.pumpEngaged??water.pumpState==='ENGAGED',flowConfirmed:water.flowConfirmed??water.flowState==='FLOWING',flowSource:water.flowSource??water.source,sustainableCapability:water.sustainableCapability??water.sustainableState??'UNVERIFIED',demandGap:water.demandGap??'UNVERIFIED'};}
function normalizeTimer(timer,now){const type=timer.type??({acknowledgement:'ACKNOWLEDGEMENT',locationConfirmation:'LOCATION_CONFIRMATION',rescueTeamAssignment:'RESCUE_ASSIGNMENT',rescueSupervisorAssignment:'RESCUE_SUPERVISOR_ASSIGNMENT',rescueTeamEntry:'RESCUE_ENTRY',fireControlProtection:'FIRE_CONTROL_PROTECTION',parCompletion:'PAR',physicalRecovery:'PHYSICAL_RECOVERY'}[timer.kind]??human(timer.kind).toUpperCase()),elapsedMs=timer.startAt?Math.max(0,Date.parse(timer.completedAt??now)-Date.parse(timer.startAt)):null,elapsed=elapsedMs===null?timer.elapsed:new Date(elapsedMs).toISOString().slice(11,19);return{...timer,type,elapsed:timer.elapsed??elapsed};}
function exceptionRows({base,changes,advisories,maydays,evacuations,par}){return[...base,
  ...maydays.filter((item)=>item.pinned!==false&&item.state!=='PHYSICALLY_RECOVERED').map((item)=>({id:item.maydayId,type:'MAYDAY',title:'Mayday active',severity:'P0_LIFE_SAFETY',whatChanged:item.emergencyTraffic??'A member declared Mayday.',whyItMatters:'The distressed member remains a life-safety priority until physically recovered.',affected:[item.personId,item.crewId].filter(Boolean),source:item.source,observedAt:item.activatedAt,verification:item.verificationState,requiredAction:'Maintain Rescue Group, fire-control protection, PAR and physical-recovery accountability.',owner:item.responsibleOwner})),
  ...advisories.map((item)=>({id:item.advisoryId,type:item.rule,title:human(item.rule),severity:'CRITICAL',whatChanged:human(item.rule),whyItMatters:'Crew integrity or accountability requires attributable verification.',affected:[item.affectedCrewId],source:'INCIDENT COMMAND ADVISORY',observedAt:item.createdAt,verification:'RULE_EVIDENCE',requiredAction:item.requiredVerification,owner:item.owner})),
  ...evacuations.filter((item)=>item.state!=='COMPLETE').map((item)=>({id:item.evacuationId,type:'EVACUATION_INCOMPLETE',title:'Evacuation incomplete',severity:'CRITICAL',whatChanged:`Evacuation is ${human(item.state)}.`,whyItMatters:'Acknowledgement does not prove every member is outside, reunited, and PAR-confirmed.',affected:item.crewIds,source:item.source,observedAt:item.observedAt,verification:item.verificationState,requiredAction:'Confirm every member at an attributable exit checkpoint, reunite the crew, then complete PAR.',owner:item.responsibleOwner})),
  ...par.filter((item)=>item.state!=='COMPLETE').map((item)=>({id:item.parRequestId,type:'PAR_INCOMPLETE',title:'PAR incomplete',severity:'WARNING',whatChanged:'PAR remains open.',whyItMatters:'Unresponsive crews and individual exceptions remain unresolved.',affected:item.subjectIds,source:item.source,observedAt:item.requestedAt??item.observedAt,verification:item.verificationState,requiredAction:'Obtain and verify every scoped response.',owner:item.requestedBy??item.responsibleOwner})),...changes];}

export function commandModel(raw={},requestedRole='INCIDENT_COMMAND'){
  const wrapper=raw.projection??raw.data?.projection??raw,state=wrapper.state??wrapper.snapshot?.state,value=state?{...state,role:requestedRole,generatedAt:raw.generatedAt??new Date().toISOString()}:wrapper;
  const incident=object(value.incident,value.commandIncident,value.snapshot?.incident),command=object(value.command,value.commandState,incident.command),conditions={...object(value.conditions,value.operationalConditions,incident.conditions),hazards:values(value.hazards??object(value.conditions).hazards)};
  const assignments=values(value.assignments),advisories=arr(value.advisories,value.crewIntegrityAdvisories),rawCrews=values(value.crews??(value.crew?[value.crew]:[])),crews=rawCrews.map((item)=>normalizeCrew(item,advisories,assignments));
  const rawPeople=values(value.people??value.persons??value.members??value.distressedPersons??(value.person?[value.person]:[])),people=rawPeople.map((item)=>normalizePerson(item,crews,assignments));
  const maydays=values(value.maydays),orders=values(value.orders).map((item)=>normalizeOrder(item,crews,people)),par=values(value.par??value.parRequests),evacuations=values(value.evacuations),changes=values(value.criticalChanges).map(normalizeChange),waterStates=values(value.waterStates??(value.water?[value.water]:[])),waterSources=values(value.waterSources),baseExceptions=values(value.exceptions??value.exceptionBoard??value.decisionsDue);
  const local=Boolean(state),connection=local?{...object(raw.connection,raw.fieldNet),state:raw.connectionState??'FIELDNET_LOCAL',lastSyncAt:raw.lastSyncAt??raw.exportedAt,pendingSync:raw.localMutations?.length??0,centralSourceState:'STALE',localState:'AVAILABLE'}:{state:'CENTRAL_CONFIRMED',lastSyncAt:value.generatedAt,pendingSync:0,...object(value.connection,value.offline,value.fieldNet,value.fieldnet)};
  const role=value.role??value.projectionRole??requestedRole,rolePersonId=value.person?.personId??value.distressedPersons?.[0]?.personId,roleCrewId=value.crew?.crewId??value.person?.currentCrewId,rescue=object(value.rescue,value.rescueOrganization,values(value.rescueOrganizations)[0]),rescueTeams=arr(value.rescueTeams,rescue.teams).length?arr(value.rescueTeams,rescue.teams):(rescue.rescueCrewIds??[]).map((id)=>crews.find((crew)=>crew.crewId===id)??{crewId:id,name:id,state:'ASSIGNED'}),timers=arr(value.timers,value.maydayTimers,...maydays.map((item)=>item.timers)).map((item)=>normalizeTimer(item,value.generatedAt??new Date().toISOString()));
  return{schemaVersion:value.schemaVersion??raw.schemaVersion??'UNVERSIONED',generatedAt:value.generatedAt??raw.generatedAt??null,role,incident:{...incident,incidentId:incident.incidentId??value.incidentId??raw.incidentId,name:incident.name??incident.label??value.incidentName??'Active incident',mode:incident.mode??value.mode??incident.universe??'OPERATIONAL',strategy:incident.strategy??command.strategy??'STRATEGY NOT REPORTED',objective:incident.objective??command.primaryObjective??values(value.objectives)[0]?.text??'OBJECTIVE NOT REPORTED'},actor:object(value.actor,value.user),command,conditions,connection,accountability:object(value.accountability,value.accountabilityState),exceptions:exceptionRows({base:baseExceptions,changes,advisories,maydays,evacuations,par}),criticalChanges:changes,unknowns:values(value.unknowns),people,crews,assignments,orders,par,evacuations,resources:values(value.resources),resourceRequests:values(value.resourceRequests),water:normalizeWater(waterStates,waterSources),communications:object(value.communications,conditions.communications),rit:object(value.rit,value.rescueReadiness,conditions.rit),maydays,rescue,rescueTeams,timers,tacticalMarkers:values(value.tacticalMarkers),timeline:arr(value.timeline,value.events,raw.events),roleData:{...object(value.roleData,value.myAssignment),personId:rolePersonId,crewId:roleCrewId,assignment:value.assignment,advisories:value.advisories},release:object(value.release,value.releaseIdentity),fallback:object(value.fallback),releaseGates:object(value.releaseGates),controlled:value.controlled===true||incident.universe==='SHADOW'||incident.mode==='SHADOW_CONTROLLED'||String(value.exerciseId??'').startsWith('CSX-')};
}

export function personById(model,id){return model.people.find((person)=>String(person.personId??person.id)===String(id));}
export function crewById(model,id){return model.crews.find((crew)=>String(crew.crewId??crew.id)===String(id));}
export function activeMayday(model){return model.maydays.find((item)=>item.pinned!==false&&item.state!=='PHYSICALLY_RECOVERED')??null;}
export function rolePerson(model){const id=model.roleData.personId??model.actor.personId;return personById(model,id)??model.people[0]??{};}
export function roleCrew(model){const person=rolePerson(model),id=model.roleData.crewId??person.crewId??model.actor.crewId;return crewById(model,id)??model.crews[0]??{};}
