import{commandModel,rolePerson}from'./model.js';
import{renderFireground,renderFiregroundError,renderFiregroundLoading}from'./render.js';
import{controlledHarness}from'./controlled-harness.js';
import{AtlasMap}from'../../map/atlas-map.js';

const shell=document.querySelector('[data-fireground-shell]'),app=document.querySelector('#app'),fieldnet=document.querySelector('[data-fieldnet-shell]');
const CONTROLLED_INCIDENT='CSX-20260814174314-PT-2026-5C3C5DE25E',BASE='/api/v10/incident-command',FIELD_BASE='http://127.0.0.1:4188/api/fieldnet';
const SUBJECTS={FIREFIGHTER:'person:alpha-officer',COMPANY_OFFICER:'crew:alpha'};
const ROLES=new Set(['FIREFIGHTER','COMPANY_OFFICER','DIVISION_SUPERVISOR','INCIDENT_COMMAND','DISPATCH_EOC','ACCOUNTABILITY','MAYDAY_RESCUE']);
const PANELS=new Set(['overview','people','assignments','par','evacuation','changes','resources','mayday','fieldnet','timeline','fallback','transfer','handoff','afteraction']);
let model=null,route=null,refreshTimer=null,holdTimer=null,tacticalMap=null;
const panelFilters={};

installEntry();
addEventListener('hashchange',activateFromHash);
shell?.addEventListener('click',handleClick);
shell?.addEventListener('input',handleFilterInput);
shell?.addEventListener('change',handleFilterInput);
shell?.addEventListener('pointerdown',startHold);
for(const event of ['pointerup','pointercancel','pointerleave'])shell?.addEventListener(event,cancelHold);
shell?.addEventListener('keydown',(event)=>{if(event.target.closest('[data-fg-hold="mayday"]')&&['Enter',' '].includes(event.key)){event.preventDefault();startHold(event);}});
shell?.addEventListener('keyup',cancelHold);
activateFromHash();

function installEntry(){const actions=document.querySelector('.gt-top-actions');if(!actions||actions.querySelector('[data-active-incident-entry]'))return;const button=document.createElement('button');button.type='button';button.className='incident-route';button.dataset.activeIncidentEntry='';button.textContent='Active incident';button.addEventListener('click',()=>openRoute({incidentId:document.querySelector('#app')?.dataset.commandIncidentId??CONTROLLED_INCIDENT,role:'INCIDENT_COMMAND',panel:'overview',exercise:true}));actions.prepend(button);}

function readRoute(){if(!location.hash.startsWith('#active-incident='))return null;const params=new URLSearchParams(location.hash.slice(1)),incidentId=params.get('active-incident');if(!incidentId)return null;const requestedRole=params.get('role')??'INCIDENT_COMMAND',requestedPanel=params.get('panel')??'overview';return{incidentId,role:ROLES.has(requestedRole)?requestedRole:'INCIDENT_COMMAND',panel:PANELS.has(requestedPanel)?requestedPanel:'overview',exercise:params.get('exercise')==='1'};}
function openRoute(next){const params=new URLSearchParams({'active-incident':next.incidentId,role:next.role,panel:next.panel});if(next.exercise)params.set('exercise','1');location.hash=params.toString();}

async function activateFromHash(){route=readRoute();clearInterval(refreshTimer);if(!route){shell.hidden=true;app.hidden=false;return;}app.hidden=true;if(fieldnet)fieldnet.hidden=true;shell.hidden=false;renderFiregroundLoading(shell);await load();refreshTimer=setInterval(()=>load({quiet:true}),15_000);}
async function load({quiet=false}={}){if(!route)return;try{const raw=await fetchProjection(route),next=commandModel(raw,route.role);model=next;if(next.controlled!==true&&route.exercise)throw new Error('controlled_exercise_contract_missing');renderFireground(shell,next,{panel:route.panel});renderTacticalMap(next);applyPanelFilters();}catch(error){if(!quiet)renderFiregroundError(shell,error,route.incidentId);}}

async function fetchProjection(current){if(current.exercise&&current.incidentId===CONTROLLED_INCIDENT)return controlledHarness(current.role);const subject=SUBJECTS[current.role],query=subject?`?subjectId=${encodeURIComponent(subject)}`:'',path=`/incidents/${encodeURIComponent(current.incidentId)}/projections/${encodeURIComponent(current.role)}${query}`;let centralError=null;try{return await request(`${BASE}${path}`);}catch(error){centralError=error;}try{return await request(`${FIELD_BASE}/incidents/${encodeURIComponent(current.incidentId)}/command-survival`,{timeoutMs:4_000});}catch(localError){throw new Error(`Central projection unavailable (${centralError.message}); FieldNet local state unavailable (${localError.message}).`);}}
async function request(url,{method='GET',body=null,timeoutMs=8_000,actor=null}={}){const headers=body?{'content-type':'application/json'}:{};if(actor)headers['x-field-actor']=actor;const response=await fetch(url,{method,credentials:url.startsWith('/')?'same-origin':'omit',headers,body:body?JSON.stringify(body):null,signal:AbortSignal.timeout(timeoutMs)}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??payload.message??`HTTP ${response.status}`);return payload;}

function handleClick(event){const missionLink=event.target.closest('[data-fg-mission]'),roleButton=event.target.closest('[data-fg-role]'),panelButton=event.target.closest('[data-fg-panel]'),mapAction=event.target.closest('[data-fg-map-action]'),timelineFilter=event.target.closest('[data-fg-timeline-filter]'),sortButton=event.target.closest('[data-fg-sort]'),printKind=event.target.closest('[data-fg-print-kind]'),action=event.target.closest('[data-fg-action]');if(missionLink){event.preventDefault();const view=missionLink.dataset.fgMission;location.hash='';requestAnimationFrame(()=>document.querySelector(`[data-view-button="${view}"]`)?.click());return;}if(roleButton){openRoute({...route,role:roleButton.dataset.fgRole,panel:'overview'});return;}if(panelButton){openRoute({...route,panel:panelButton.dataset.fgPanel});return;}if(timelineFilter){panelFilters.timeline=timelineFilter.dataset.fgTimelineFilter;applyPanelFilters();return;}if(sortButton){sortPeople(sortButton);return;}if(mapAction){const type=mapAction.dataset.fgMapAction;if(type==='zoom-in')tacticalMap?.zoomIn();if(type==='zoom-out')tacticalMap?.zoomOut();if(type==='home')tacticalMap?.flyTo(model?.incident?.coordinate??[-6.500135217154487,37.54135667405967],10.8);if(type==='layers')openRoute({...route,panel:'fieldnet'});return;}if(printKind){shell.dataset.printKind=printKind.dataset.fgPrintKind;openRoute({...route,panel:printKind.dataset.fgPrintKind==='mayday'?'mayday':printKind.dataset.fgPrintKind==='accountability'?'people':printKind.dataset.fgPrintKind==='resources'||printKind.dataset.fgPrintKind==='water'?'resources':printKind.dataset.fgPrintKind==='assignments'?'assignments':'overview'});setTimeout(()=>print(),80);return;}if(!action)return;const type=action.dataset.fgAction;if(type==='print'){print();return;}if(type==='retry'){load();return;}void runAction(type,action.dataset);}

function handleFilterInput(event){const control=event.target.closest?.('[data-fg-filter]');if(!control)return;panelFilters[control.dataset.fgFilter]=control.value;applyPanelFilters();}
function matches(value,query){return!query||String(value??'').toLowerCase().includes(String(query).toLowerCase());}
function setVisibleCount(cards){const count=cards.filter((card)=>!card.hidden).length,target=shell.querySelector('[data-fg-filter-count]');if(target)target.textContent=`${count} shown`;}
function applyPanelFilters(){for(const control of shell.querySelectorAll('[data-fg-filter]'))if(panelFilters[control.dataset.fgFilter]!==undefined)control.value=panelFilters[control.dataset.fgFilter];const people=[...shell.querySelectorAll('[data-fg-person-card]')],peopleSearch=panelFilters['people-search']??'',peopleArea=panelFilters['people-area']??'',peopleStatus=panelFilters['people-status']??'';for(const card of people)card.hidden=!(matches(`${card.dataset.name} ${card.dataset.role}`,peopleSearch)&&matches(card.dataset.area,peopleArea)&&matches(card.dataset.status,peopleStatus));for(const area of shell.querySelectorAll('[data-fg-people-area]'))area.hidden=![...area.querySelectorAll('[data-fg-person-card]')].some((card)=>!card.hidden);if(people.length)setVisibleCount(people);const assignmentCards=[...shell.querySelectorAll('[data-fg-assignment-card]')],assignmentSearch=panelFilters['assignments-search']??'',assignmentLane=panelFilters['assignments-lane']??'';for(const card of assignmentCards)card.hidden=!(matches(card.dataset.assignmentSearch,assignmentSearch)&&matches(card.dataset.assignmentStatus,assignmentLane));for(const lane of shell.querySelectorAll('[data-fg-assignment-lane]'))lane.hidden=Boolean(assignmentLane&&lane.dataset.fgAssignmentLane!==assignmentLane);if(assignmentCards.length)setVisibleCount(assignmentCards);const resources=[...shell.querySelectorAll('[data-fg-resource-card]')],resourceState=panelFilters['resources-state']??'';for(const card of resources)card.hidden=!matches(card.dataset.resourceState,resourceState);const timeline=panelFilters.timeline??'ALL';for(const button of shell.querySelectorAll('[data-fg-timeline-filter]'))button.classList.toggle('is-active',button.dataset.fgTimelineFilter===timeline);for(const item of shell.querySelectorAll('[data-fg-timeline-item]'))item.hidden=timeline!=='ALL'&&item.dataset.timelineCategory!==timeline;}
function sortPeople(button){const grids=[...shell.querySelectorAll('.fg-people-grid-v2')],mode=button.dataset.sortMode==='role'?'name':'role';button.dataset.sortMode=mode;button.setAttribute('aria-pressed',String(mode==='role'));for(const grid of grids){const cards=[...grid.querySelectorAll('[data-fg-person-card]')].sort((a,b)=>String(a.dataset[mode]).localeCompare(String(b.dataset[mode])));for(const card of cards)grid.append(card);}}

function renderTacticalMap(current){tacticalMap?.destroy();tacticalMap=null;const container=shell.querySelector('[data-fg-tactical-map]');if(!container)return;const center=current.incident.coordinate??current.tacticalMarkers.find((item)=>Array.isArray(item.coordinate))?.coordinate;if(!Array.isArray(center)){container.innerHTML='<p class="fg-map-unavailable">Tactical positions are unavailable. Open FieldNet for packaged local geography.</p>';return;}const markers=current.tacticalMarkers.filter((item)=>Array.isArray(item.coordinate)),points=markers.filter((item)=>item.state==='MAYDAY').map((item)=>({type:'Feature',geometry:{type:'Point',coordinates:item.coordinate},properties:{kind:'incident',id:item.id,label:`${item.label} · ${item.state}`,stage:'reported',freshness:'current',selected:true}})),assets=markers.filter((item)=>item.state!=='MAYDAY').map((item)=>({type:'Feature',geometry:{type:'Point',coordinates:item.coordinate},properties:{kind:'asset',id:item.id,label:`${item.label} · ${item.state}`}}));tacticalMap=new AtlasMap(container,{onSelect:()=>{}});tacticalMap.setMode('command');tacticalMap.setData({points:{type:'FeatureCollection',features:points},assets:{type:'FeatureCollection',features:assets}});tacticalMap.flyTo(center,10.8);}

async function runAction(type,dataset={}){if(!model||!route)return;const person=rolePerson(model),personId=person.personId??person.id,crewId=person.crewId??model.roleData.crewId,actorId=model.actor.actorId??model.actor.id??globalThis.__VIGIA_SESSION__?.actor?.id??'shadow-operator',now=new Date().toISOString();let path=`/incidents/${encodeURIComponent(route.incidentId)}/commands`,event={type:'PERSON_UPSERTED',payload:{personId,operationalState:person.status??'WORKING',statusReportedAt:now}},body=event;
  if(type==='acknowledge-order'&&dataset.orderId){path=`/incidents/${encodeURIComponent(route.incidentId)}/orders/${encodeURIComponent(dataset.orderId)}/transitions`;body={state:'ACKNOWLEDGED',recipientId:crewId??personId,acknowledgement:{actor:actorId,meaning:'ORDER_RECEIVED_NOT_COMPLETE'}};event={type:'ORDER_TRANSITIONED',payload:{...body,orderId:dataset.orderId}};}
  if(type==='withdrawing'){event={type:'PERSON_STATE_TRANSITIONED',payload:{personId,state:'WITHDRAWING'}};body=event;}
  if(type==='out'){event={type:'PERSON_STATE_TRANSITIONED',payload:{personId,state:'OUT',exitCheckpointEvidence:{actor:actorId,method:'MEMBER_SELF_REPORT_RADIO_AUGMENT',reportedAt:now}}};body=event;}
  if(type==='progress'){event={type:'CREW_UPSERTED',payload:{crewId,lastProgressAt:now,progressReportedBy:actorId}};body=event;}
  if(type==='withdraw-crew'){event={type:'CREW_UPSERTED',payload:{crewId,operationalState:'WITHDRAWING',withdrawalReportedBy:actorId}};body=event;}
  if(type==='location'){path=`/incidents/${encodeURIComponent(route.incidentId)}/locations`;body={personId,verificationState:'REPORTED',operationalAreaId:person.operationalArea,source:'MEMBER_RADIO_AUGMENT',observerId:actorId};event={type:'LOCATION_REPORTED',payload:body};}
  if(type==='resource-status'){const resource=model.resources[0]??{};event={type:'RESOURCE_UPSERTED',payload:{resourceId:resource.resourceId,state:resource.state,statusReportedAt:now}};body=event;}
  if(type==='acknowledge-change'){event={type:'DECISION_RECORDED',payload:{decisionId:`decision:${dataset.changeId}:${Date.now()}`,criticalChangeId:dataset.changeId,decision:'ACKNOWLEDGED_FOR_REVIEW',owner:actorId}};body=event;}
  if(type==='par'){const current=model.par.find((item)=>item.state!=='COMPLETE');if(current){path=`/incidents/${encodeURIComponent(route.incidentId)}/par/${encodeURIComponent(current.parRequestId)}/responses`;body={subjectId:crewId??personId,accounted:true,condition:'ALL_ACCOUNTED',observedAt:now};event={type:'PAR_RESPONDED',payload:{...body,parRequestId:current.parRequestId}};}else{const parRequestId=`par:${Date.now()}`;path=`/incidents/${encodeURIComponent(route.incidentId)}/par`;body={parRequestId,subjectIds:[crewId??personId],requestedBy:actorId,requestedAt:now};event={type:'PAR_REQUESTED',payload:body};}}
  if(type==='mayday'){path=`/incidents/${encodeURIComponent(route.incidentId)}/maydays`;body={personId,crewId,declaredBy:actorId,source:'FIREGROUND_ROLE_VIEW'};event={type:'MAYDAY_ACTIVATED',payload:{...body,maydayId:`mayday:${personId}:${Date.now()}`,timers:{}}};}
  if(type==='mayday-recovered'){path=`/incidents/${encodeURIComponent(route.incidentId)}/maydays/${encodeURIComponent(dataset.maydayId)}/transitions`;body={state:'PHYSICALLY_RECOVERED',physicalRecoveryEvidence:{confirmedBy:actorId,method:'PHYSICAL_CONTACT_AND_HANDOFF'}};event={type:'MAYDAY_TRANSITIONED',payload:{...body,maydayId:dataset.maydayId}};}
  try{await mutate(path,body,event,actorId);renderFireground(shell,model,{panel:route.panel,message:'Action recorded. Refreshing incident truth…'});await load({quiet:true});}catch(error){renderFireground(shell,model,{panel:route.panel,message:`Action remains unresolved: ${error.message}`});}}
async function mutate(path,body,event,actor){try{return await request(`${BASE}${path}`,{method:'POST',body});}catch(centralError){try{return await request(`${FIELD_BASE}/incidents/${encodeURIComponent(route.incidentId)}/command-survival/events`,{method:'POST',body:{event,actor},actor,timeoutMs:4_000});}catch(localError){throw new Error(`central ${centralError.message}; FieldNet ${localError.message}`);}}}

function startHold(event){const button=event.target.closest?.('[data-fg-hold="mayday"]');if(!button||holdTimer)return;button.classList.add('is-holding');button.setAttribute('aria-label','Keep holding to declare Mayday');holdTimer=setTimeout(()=>{holdTimer=null;button.classList.remove('is-holding');void runAction('mayday');},2_000);}
function cancelHold(event){if(!holdTimer)return;clearTimeout(holdTimer);holdTimer=null;const button=event.target.closest?.('[data-fg-hold="mayday"]')??shell.querySelector('[data-fg-hold="mayday"].is-holding');button?.classList.remove('is-holding');button?.setAttribute('aria-label','Hold for Mayday');}
