export const PRODUCT_MATURITY = Object.freeze(['OPERATIONAL', 'PROVISIONAL', 'RETROSPECTIVE']);
export const CONTRACT_STATES = Object.freeze(['ACCEPTED', 'ACCEPTED_WITH_WARNINGS', 'QUARANTINED', 'REJECTED', 'SCHEMA_DRIFT', 'RIGHTS_BLOCKED', 'KNOWLEDGE_TIME_INVALID']);
export const TASK_STATES = Object.freeze(['PLANNED', 'READY', 'RUNNING', 'WAITING', 'RETRYABLE', 'BLOCKED', 'QUARANTINED', 'COMPLETED', 'FAILED', 'CANCELLED', 'SUPERSEDED']);
export const TERMINAL_TASK_STATES = Object.freeze(['BLOCKED', 'QUARANTINED', 'COMPLETED', 'FAILED', 'CANCELLED', 'SUPERSEDED']);
export const PIPELINE_EVENTS = Object.freeze(['DATA_PRODUCT_ACQUIRED', 'DATA_PRODUCT_QUARANTINED', 'DATA_PRODUCT_SUPERSEDED', 'SCHEMA_DRIFT_DETECTED', 'QUALITY_GATE_FAILED', 'DATA_GAP_OPENED', 'DATA_GAP_CLOSED', 'FORECAST_INPUT_PACKAGE_READY', 'CORPUS_EXAMPLE_CREATED', 'CORPUS_READINESS_CHANGED', 'RIGHTS_BLOCKED']);
export const GAP_STATES = Object.freeze(['OPEN', 'PLANNED', 'BLOCKED_EXTERNAL_ACCESS', 'CLOSED', 'SUPERSEDED']);
export const OPPORTUNITY_OUTCOMES = Object.freeze(['VALID_OBSERVATION_OPPORTUNITY', 'OBSERVED_POSITIVE', 'OBSERVED_NEGATIVE', 'NOT_COVERED', 'PRODUCT_UNAVAILABLE', 'PROVIDER_UNAVAILABLE', 'QUALITY_INSUFFICIENT', 'UNKNOWN']);
export const PRODUCT_KINDS = Object.freeze(['RAW_ARTIFACT', 'CANONICAL_DATASET', 'MATERIALIZED_DATASET', 'DATASET_SLICE', 'FORECAST_INPUT_PACKAGE', 'CORPUS_EXAMPLE', 'CORPUS_SPLIT', 'EVALUATION', 'REPLAY_RECEIPT']);
