import { immutable, semanticHash } from '../intelligence/shared.mjs';
import { validateCorpusGeometry } from '../forecast-corpus/geometry-qa.mjs';

const center = (bbox) => bbox ? [(bbox[0] + bbox[2]) / 2, (bbox[1] + bbox[3]) / 2] : null;
const distance = (left, right) => left && right ? Math.hypot((left[0] - right[0]) * 92, (left[1] - right[1]) * 111) : null;
export function assessProgressionSequence(incident = {}) {
  const rows = [...(incident.perimeterStates ?? [])].sort((a, b) => Date.parse(a.clocks?.observedAt) - Date.parse(b.clocks?.observedAt)), states = rows.map((row, index) => { const qa = validateCorpusGeometry({ geometry: row.geometry }), prior = rows[index - 1], cadenceHours = prior ? (Date.parse(row.clocks.observedAt) - Date.parse(prior.clocks.observedAt)) / 3_600_000 : null, priorQa = prior ? validateCorpusGeometry({ geometry: prior.geometry }) : null, areaRatio = priorQa?.approximateAreaKm2 > 0 ? qa.approximateAreaKm2 / priorQa.approximateAreaKm2 : null, centroidDisplacementKm = distance(center(priorQa?.bbox), center(qa.bbox)); return { id: row.id, revision: row.revision, observedAt: row.clocks?.observedAt, availableToVigiaAt: row.clocks?.availableToVigiaAt, geometryValid: qa.passed, geometryHash: row.originalGeometryHash, cadenceHours, areaKm2: qa.approximateAreaKm2, areaRatio, centroidDisplacementKm, flags: [areaRatio != null && areaRatio < .25 ? 'IMPOSSIBLE_AREA_COLLAPSE_OR_CORRECTION' : null, centroidDisplacementKm > 50 ? 'LARGE_GEOMETRY_DISCONTINUITY' : null, Date.parse(row.clocks?.observedAt) > Date.parse(row.clocks?.availableToVigiaAt) ? 'KNOWLEDGE_CLOCK_NONCAUSAL' : null].filter(Boolean) }; });
  const duplicateSnapshots = states.length - new Set(states.map((item) => item.geometryHash)).size, cadences = states.map((item) => item.cadenceHours).filter(Number.isFinite).sort((a, b) => a - b), horizonCoverage = Object.fromEntries([1, 3, 6, 12, 24].map((horizon) => [horizon, states.some((left) => states.some((right) => Date.parse(right.observedAt) > Date.parse(left.observedAt) && Math.abs(Date.parse(right.observedAt) - Date.parse(left.observedAt) - horizon * 3_600_000) <= Math.max(1_800_000, horizon * 900_000)))]));
  const core = { schemaVersion: 'vigia.progression-quality.v1', incidentId: incident.id, classification: incident.perimeterSourceClass, revisionCount: states.length, distinctRevisionCount: new Set(states.map((item) => item.geometryHash)).size, duplicateSnapshots, medianCadenceHours: cadences.length ? cadences[Math.floor(cadences.length / 2)] : null, geometryValidityRate: states.length ? states.filter((item) => item.geometryValid).length / states.length : 0, correctionEvents: states.filter((item) => item.flags.length).length, knowledgeTimeIntegrity: states.every((item) => !item.flags.includes('KNOWLEDGE_CLOCK_NONCAUSAL')), horizonCoverage, sourceComplete: states.every((item) => item.id && item.geometryHash), states };
  return immutable({ ...core, eligibleSequence: ['ARCHIVED_OPERATIONAL_SNAPSHOT', 'DERIVED_PROGRESS_SEQUENCE', 'OFFICIAL_PROGRESS_SEQUENCE'].includes(core.classification) && core.distinctRevisionCount >= 3 && core.geometryValidityRate === 1, fingerprint: semanticHash('progression-quality', core) });
}

export function constructFutureLabels(incident = {}, horizons = [1, 3, 6, 12, 24]) {
  const states = (incident.perimeterStates ?? []).filter((state) => Date.parse(state.clocks?.observedAt) <= Date.parse(state.clocks?.availableToVigiaAt)).sort((a, b) => Date.parse(a.clocks.observedAt) - Date.parse(b.clocks.observedAt)), labels = [];
  for (const issue of states) for (const horizonHours of horizons) { const target = Date.parse(issue.clocks.observedAt) + horizonHours * 3_600_000, toleranceMs = Math.max(1_800_000, horizonHours * 900_000), label = states.filter((state) => Date.parse(state.clocks.availableToVigiaAt) > Date.parse(issue.clocks.availableToVigiaAt)).sort((a, b) => Math.abs(Date.parse(a.clocks.observedAt) - target) - Math.abs(Date.parse(b.clocks.observedAt) - target))[0]; if (label && Math.abs(Date.parse(label.clocks.observedAt) - target) <= toleranceMs) labels.push({ id: semanticHash('future-label', { issueId: issue.id, labelId: label.id, horizonHours }), incidentId: incident.id, issueStateId: issue.id, horizonHours, targetTime: new Date(target).toISOString(), labelStateId: label.id, labelSource: incident.perimeterSourceClass, labelPublicationTime: label.clocks.availableToVigiaAt, labelMaturity: 'PROVISIONAL', horizonDifferenceMinutes: Math.round((Date.parse(label.clocks.observedAt) - target) / 60_000), toleranceMinutes: toleranceMs / 60_000, correctionState: 'NOT_OFFICIALLY_CERTIFIED', quality: 'USABLE_ARCHIVED_SNAPSHOT' }); }
  return immutable(labels.sort((a, b) => a.id.localeCompare(b.id)));
}
