import { escapeHtml } from '../utils/html.js';
import { statusLabel } from '../utils/format.js';
import { avoidanceFor } from '../views/prevention-connectivity.js';

export function settingsHtml(state){
  const actor=state.bootstrap?.actor??{},sensorAssets=state.bootstrap?.sources?.sensorAssets??{},handoff=state.bootstrap?.operationsHandoff,endpointCount=handoff?.apiEndpoints?.length??0,assetCount=Number(handoff?.territoryAndAssets?.importedAssetCount??sensorAssets.count??sensorAssets.assets?.length??0);
  const engineState=handoff?.status??'NOT HANDED OFF',engineDetail=endpointCount?`${endpointCount} live operations endpoint${endpointCount===1?'':'s'} declared.`:'No live operations endpoint is declared; alert and asset controls remain unavailable.';
  return `<div class="settings-ledger"><nav aria-label="Settings categories"><button type="button" class="is-active">Operational display</button><button type="button">Data &amp; sources</button><button type="button">Integrations</button><button type="button">Account &amp; system</button></nav><div class="settings-grid"><section><span>MONITORED TERRITORY</span><h3>Portugal Shadow Territory</h3><dl><div><dt>Operating mode</dt><dd>Shadow operational performance</dd></div><div><dt>Coverage boundary</dt><dd>Portugal mainland</dd></div><div><dt>Reference monitored assets</dt><dd>${assetCount}</dd></div><div><dt>Asset truth</dt><dd>${assetCount?'OSM-derived reference assets · not connected devices':'No attributable monitored assets configured'}</dd></div></dl><details><summary>Territory evidence boundary</summary><p>Reference proximity supplies decision context only. It does not claim a customer deployment or connected sensor estate.</p></details></section><section><span>OPERATOR SESSION</span><h3>${escapeHtml(actor.name??'Public read-only')}</h3><dl><div><dt>Title</dt><dd>${escapeHtml(actor.title??'Unauthenticated')}</dd></div><div><dt>Role</dt><dd>${escapeHtml(statusLabel(actor.role??'public_viewer'))}</dd></div><div><dt>Boundary</dt><dd>${escapeHtml(actor.authentication?.mode??'public_read_only')}</dd></div><div><dt>Expiry</dt><dd>${state.session?.expiresAt?escapeHtml(new Date(state.session.expiresAt).toLocaleString()):'No authenticated session'}</dd></div></dl></section><section><span>OPERATIONS ENGINE</span><h3>${escapeHtml(statusLabel(engineState))}</h3><dl><div><dt>Declared endpoints</dt><dd>${endpointCount}</dd></div><div><dt>Integration state</dt><dd>${escapeHtml(engineDetail)}</dd></div></dl><details><summary>Known integration boundaries</summary><p>${escapeHtml((handoff?.remainingBlockers??[]).join(' ')||'No backend handoff artifact is available.')}</p></details></section><section class="settings-danger"><span>PROTECTED ACTIONS</span><h3>Operational reset and source changes</h3><p>Destructive or provider-changing actions require an authenticated administrator and explicit confirmation.</p><button type="button" disabled>Administrator confirmation required</button></section></div></div>`;
}

export function tourHtml(state){
  const summary=state.live?.summary??{},findings=state.bootstrap?.prevention?.findings??[],event=(state.live?.events??[]).find((item)=>item.physicalSourceProfile?.twoPhysicalSourceFamilies===true)??(state.live?.events??[]).find((item)=>item.evidenceState==='satellite-only')??state.live?.events?.[0];
  const finding=findings[0],avoidance=finding?avoidanceFor(finding):{},candidate=avoidance.candidate,reviewed=findings.reduce((sum,item)=>sum+Number(item.reviewSummary?.domainExpert??0),0);
  const operations=state.operationsState==='ready'?'READY':state.operationsState==='partially_available'?'PARTIALLY AVAILABLE':'DEGRADED';
  const steps=[
    ['01','PHYSICAL-FIRST DETECTION',`${summary.activeCurrentPhysicalEvents??summary.currentPhysicalEvents??0} current physical · ${summary.currentPhysicalCandidates??0} physical-first`,'Begin with provider observation and provenance, never a public report requirement.','home'],
    ['02','INDEPENDENT CORROBORATION',event?`${event.label} · ${event.physicalSourceProfile?.familyCount??0} physical families`:'No independently corroborated incident at this governed clock.','Separate VIIRS, Sentinel-3 and fusion performance instead of hiding source weakness.',null],
    ['03','EVIDENCE AUTOPILOT',`${state.bootstrap?.operations?.systemActionability?.systemCompleted??'UNMEASURED'} system-completed actions · ${operations}`,'See what the evidence system closed and what remains human, field or externally blocked.','work'],
    ['04','OBSERVED PREVENTION CHANGE',`${findings.length} real Sentinel-2 scene-pair finding${findings.length===1?'':'s'}`,'Open exact native before/after pixels and the detector provenance boundary.','tour-prevention'],
    ['05','FUEL CONNECTIVITY GRAPH',finding?`${avoidance.graph?.edges?.length??0} geometry-bound links · ${finding.structuresWithinPolicyRadius??0} mapped structure paths`:'No eligible graph in the current corpus.','Inspect topology derived from persisted observed component geometry.','tour-prevention'],
    ['06','CONSENSUS MEASUREMENT',candidate?`${candidate.affectedAssetPaths.before} → ${candidate.affectedAssetPaths.after} nominal modeled asset-connected paths`:'No graph candidate in the current corpus.','Inspect ensemble support, position dispersion and the repeat-scene closure plan; no exact intervention location is implied.','tour-prevention'],
    ['07','EXTERNAL VALIDATION GATE',`${reviewed} qualified review${reviewed===1?'':'s'} recorded`,'Stable cases remain externally gated; unstable and no-zone cases remain measurement work.','tour-prevention'],
    ['08','POST-INTERVENTION VERIFICATION','Contract defined · outcome unmeasured','A mission can claim verified change only after attributable mitigation evidence and a real post-intervention optical observation.','validation']
  ];
  return `<div class="product-tour"><p>One operating narrative: detect physical change, preserve the evidence boundary, route the next decision, and measure whether the system closed uncertainty.</p>${steps.map(([index,label,value,detail,action])=>`<article><span>${index}</span><div><strong>${escapeHtml(label)}</strong><b>${escapeHtml(value)}</b><p>${escapeHtml(detail)}</p></div>${action?`<button type="button" data-action="${escapeHtml(action)}">Open</button>`:event?`<button type="button" data-select-kind="event" data-select-id="${escapeHtml(event.id)}">Open</button>`:''}</article>`).join('')}</div>`;
}
