import { escapeHtml } from '../utils/html.js';
import { dateTime, statusLabel } from '../utils/format.js';
import { actions, metric, nextAction, pill } from '../components/primitives.js';

export function consequenceSummary(state) {
  const incidents = state.bootstrap.detection.incidents;
  const eligible = incidents.filter((item) => ['corroborated','verified'].includes(item.truthStage) && item.freshness?.state !== 'stale');
  return `<div class="summary-hero"><strong>${eligible.length}</strong><span>incidents eligible for consequence screening</span></div><p class="summary-note">Only independently supported incidents enter this workspace. Reported-only and stale records remain locked.</p><div class="summary-grid"><div><strong>${state.bootstrap.detection.summary.verifiedCount}</strong><span>verified</span></div><div><strong>${state.bootstrap.detection.summary.corroboratedCount}</strong><span>supported</span></div><div><strong>${incidents.length - eligible.length}</strong><span>locked</span></div></div>`;
}
function exposureBlock(state) {
  if (state.exposureLoading) return `<div class="status-card exposure-state"><header><strong>Loading mapped exposure</strong><span>In progress</span></header><p>Started ${escapeHtml(dateTime(state.exposureStartedAt))}. Spread screening remains available while OpenStreetMap resolves.</p></div>`;
  const exposure=state.exposure;if(!exposure)return`<div class="status-card exposure-state"><header><strong>Exposure not requested</strong><span>Idle</span></header><p>Mapped exposure runs independently from spread geometry.</p></div>`;
  const horizon=exposure.byEnvelope?.find((item)=>item.minutes===[15,30,60][state.timelineIndex??1])??exposure.byEnvelope?.[state.timelineIndex??1];
  const sensitivities=horizon?`<div class="exposure-quantiles"><div><span>LOW SCALE</span><strong>${horizon.low.buildings}</strong><small>sampled buildings</small></div><div><span>CENTRAL SCALE</span><strong>${horizon.central.buildings}</strong><small>sampled buildings</small></div><div><span>HIGH SCALE</span><strong>${horizon.high.buildings}</strong><small>sampled buildings</small></div></div>`:'';
  const count=Number.isFinite(Number(exposure.buildingCountWithin3Km))?`${exposure.buildingCountWithin3Km} mapped buildings within source query radius`:'Building census count unavailable';
  const assets=horizon?.high?.assets??exposure.assets??[];
  return `<div class="status-card exposure-state ${exposure.state==='unavailable'?'is-error':''}"><header><strong>${escapeHtml(statusLabel(exposure.state))}</strong><span>${escapeHtml(exposure.provider??'Exposure service')}</span></header><p>${escapeHtml(count)}. ${escapeHtml(exposure.limitation??'')}</p>${sensitivities}${horizon?`<small>Counts use ${horizon.sampledBuildingPoints} sampled building geometries and deterministic parameter scales; they are not probabilities or population counts.</small>`:''}</div>${assets.slice(0,5).map((asset)=>`<div class="status-card"><strong>${escapeHtml(asset.label)}</strong><p>${escapeHtml(statusLabel(asset.kind))}</p></div>`).join('')}`;
}
export function consequenceInspector(state) {
  const response = state.consequence; const incident = response?.incident;
  if (state.consequenceLoading) return { kicker: 'CONSEQUENCE', content: '<section class="inspector-section"><h2>Checking the truth gate…</h2><p class="deck">No scenario geometry is generated until the incident state is eligible.</p></section>', actions: '' };
  if (!response || !incident) return { kicker: 'CONSEQUENCE', content: '<section class="inspector-section"><h2>Choose an eligible incident.</h2><p class="deck">The queue contains only independently supported, non-stale incidents.</p></section>', actions: '' };
  if (!response.gate.allowed) return { kicker: 'CONSEQUENCE LOCKED', content: `<section class="inspector-section"><div class="detail-kicker"><span>TRUTH GATE</span>${pill('reported','Locked')}</div><h2>${escapeHtml(incident.municipality)}</h2><p class="deck">${escapeHtml(response.gate.reason)}</p></section><section class="inspector-section"><div class="evidence-ladder"><div class="done"><i>✓</i><span>Public report</span><small>Present</small></div><div><i>○</i><span>Independent support</span><small>Required</small></div><div><i>○</i><span>Local verification</span><small>Optional for planning</small></div></div></section>${nextAction(response.nextAction)}`, actions: actions([{ action:'request-incident-evidence', label:'Assign confirmation', kind:'primary' },{ action:'back-to-incidents', label:'Back to incident truth' }]) };
  const envelope=response.spread?.envelopes?.[state.timelineIndex??1];const validated=response.spread?.validated===true;const central=envelope?.central,high=envelope?.high??envelope?.outer;const horizon=state.exposure?.byEnvelope?.find((item)=>item.minutes===envelope?.minutes);const highBuildings=horizon?.high?.buildings;
  return { kicker: validated ? 'CONSEQUENCE · APPROVED PROVIDER' : 'CONSEQUENCE · HYPOTHETICAL', content: `<section class="inspector-section"><div class="detail-kicker"><span>${validated?'MODEL AUTHORITY: APPROVED PROVIDER':'MODEL AUTHORITY: UNVALIDATED SCREENING'}</span><span class="evidence-chip">INCIDENT SUPPORT · ${escapeHtml(statusLabel(incident.truthStage))}</span></div><h2>${escapeHtml(incident.municipality)}</h2><p class="deck">${escapeHtml(response.meta.notice)}</p></section><div class="metric-row">${metric(`${envelope?.minutes??30} min`,'scenario horizon')}${metric(central?.properties?.downwindKm?`${Number(central.properties.downwindKm).toFixed(1)} km`:'—','central scale reach')}${metric(highBuildings??'—','high-scale sampled buildings')}</div><section class="inspector-section"><div class="section-label">DETERMINISTIC SENSITIVITY ENVELOPES</div><div class="trust-banner">${validated?'Provider validation scope governs operational use.':'Low, central and high shapes are deterministic input scales. They are not probabilities, quantiles, a certified wildfire forecast, evacuation order or dispatch instruction.'}</div></section><section class="inspector-section"><div class="section-label">WHAT MAY BE EXPOSED</div>${exposureBlock(state)}</section>${nextAction(response.nextAction)}`, actions: actions([{action:'timeline-15',label:'15 min'},{action:'timeline-30',label:'30 min',kind:'primary'},{action:'timeline-60',label:'60 min'},{action:'refresh-exposure',label:state.exposureLoading?'Loading…':'Refresh exposure',disabled:state.exposureLoading}]) };
}
