import { escapeHtml } from '../utils/html.js';
import { coordinateLabel, dateTime, evidenceDateTime, statusLabel } from '../utils/format.js';
import { avoidanceWorkbench, connectivityOverlay, preventionDisposition } from './prevention-connectivity.js';

export function observeSummary(state) {
  const prevention = state.bootstrap.prevention,dispositions=(prevention.findings??[]).map(preventionDisposition),measurement=dispositions.filter((item)=>item.kind==='measurement').length,stable=dispositions.filter((item)=>item.kind==='external_validation').length;
  return `<div class="prevention-queue-summary"><div><strong>${prevention.summary.screeningFindings??0}</strong><span>Physical changes</span></div><div><strong>${measurement}</strong><span>Measurement required</span></div><div><strong>${stable}</strong><span>Stable consensus · externally gated</span></div></div><p class="summary-note">Candidates are not hazards. ${stable===0?'No robust consensus zone is promoted in the current governed corpus.':'Stable zones still require attributable external validation.'}</p>`;
}
export function observeIntro() { return ''; }
export const observeFilters = [['all','All'],['urgent','Urgent'],['open','With requests']];
function preventionLane(active='evidence'){return `<nav class="prevention-lane" aria-label="Prevention review steps"><span>Queue</span><span class="${active==='evidence'?'is-active':''}">Before / after</span><span class="${active==='decision'?'is-active':''}">Decision</span></nav>`;}

function sensorDescription(sensor) {
  if (sensor === 'Sentinel-1') return 'SAR radar · all-weather · day/night';
  if (sensor === 'Sentinel-2') return 'multispectral optical · 10 m nominal bands';
  if (String(sensor).includes('VIIRS')) return 'broad optical/thermal context · separate sensor';
  return sensor ?? 'Sensor not reported';
}
function suitability(primary, { visual = false } = {}) {
  const value = primary?.suitability; if (!value) return '';
  const title = visual ? 'SELECTED SCENE QUALITY' : 'SCENE METADATA QUALITY';
  const visibleProduct = primary.evidenceBinding?.pixelVerified ? 'Native COG · pixel binding verified server-side' : primary.renderProduct === 'metadata_only' ? 'Metadata only' : 'Pixels not integrity-verified';
  return `<div class="observation-suitability"><strong>${title} · ${escapeHtml(statusLabel(value.level))}</strong><div><span>Freshness</span><b>${escapeHtml(value.ageHours === null ? 'Unknown' : `${Math.round(value.ageHours)} h`)}</b></div><div><span>Cloud cover</span><b>${escapeHtml(value.cloudCover === null ? (primary.sensor === 'Sentinel-1' ? 'Not applicable' : 'Not reported') : `${Math.round(value.cloudCover)}%`)}</b></div><div><span>Sensor nominal resolution</span><b>${escapeHtml(primary.resolutionMeters ? `${primary.resolutionMeters} m` : 'Not reported')}</b></div><div><span>On-screen product</span><b>${escapeHtml(visibleProduct)}</b></div><div><span>Footprint</span><b>${primary.coversSelection ? 'Covers selected place' : 'Rejected'}</b></div></div>`;
}
function timeline(observation, primary) {
  const scenes = [...new Map([observation.comparable,...(observation.timeline??[])].filter(Boolean).map((scene)=>[scene.id,scene])).values()].filter((scene) => scene.evidenceBinding?.renderAllowed && scene.visualCogUrl && scene.id !== primary.id);
  if (!scenes.length) return '';
  return `<div class="observation-timeline" data-observation-timeline><div class="timeline-title"><span>COMPARABLE PRIOR</span><strong>Choose an attributable scene</strong></div><div class="timeline-scenes">${scenes.map((scene) => `<button type="button" class="${scene.id === observation.comparable?.id ? 'is-active' : ''}" data-observation-scene data-scene-id="${escapeHtml(scene.id)}" data-cog-url="${escapeHtml(scene.visualCogUrl ?? '')}" data-red-url="${escapeHtml(scene.redCogUrl ?? '')}" data-nir-url="${escapeHtml(scene.nirCogUrl ?? '')}" data-swir-url="${escapeHtml(scene.swir16CogUrl ?? '')}" data-date-label="${escapeHtml(evidenceDateTime(scene.acquiredAt))}"><b>${escapeHtml(scene.sensor)}</b><span>${escapeHtml(evidenceDateTime(scene.acquiredAt))}</span>${scene.cloudCover === null || scene.cloudCover === undefined ? '' : `<i>${Math.round(scene.cloudCover)}% cloud</i>`}</button>`).join('')}</div></div>`;
}
function findingSurface(observation, item) {
  const model = item.detectorFindings ?? [];
  if (model.length) {
    const shapes = model.filter((finding) => Array.isArray(finding.imagePolygonPct)).map((finding) => `<polygon points="${finding.imagePolygonPct.map((point) => point.join(',')).join(' ')}" data-finding-id="${escapeHtml(finding.id)}"></polygon>`).join('');
    return `<svg class="observation-finding-layer" data-finding-layer data-observation-transform viewBox="0 0 100 100" preserveAspectRatio="none">${shapes}</svg><div class="finding-label"><span>MODEL SCREENING FINDING</span><strong>${escapeHtml(model[0].label)}</strong><small>Screening output · human review required · not a confirmed hazard</small></div>`;
  }
  if (!observation.changeScreening?.eligible) return '';
  return `<svg class="observation-finding-layer optical-change-layer" data-finding-layer data-observation-transform viewBox="0 0 100 100" preserveAspectRatio="none"></svg><div class="finding-label optical-change-summary" data-finding-summary><span>OPTICAL CHANGE SCREENING</span><strong>Running native-band server screening…</strong><small>Uncalibrated spectral candidate · never a confirmed hazard or fire probability</small></div>`;
}
function rationale(observation) {
  const reason = observation.selectionReason; if (!reason) return '';
  return `<details class="observation-rationale"><summary>Why this observation?</summary><div><strong>Selected because</strong><ul>${reason.selected.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>${reason.rejected.length ? `<strong>Other candidates</strong><ul>${reason.rejected.slice(0,3).map((item) => `<li>${escapeHtml(item.sensor ?? item.id)} · ${escapeHtml(item.reason)}</li>`).join('')}</ul>` : ''}</div></details>`;
}
function visualAccess(observation, primary) {
  const visual = observation.visual;
  return `<div class="observation-suitability observation-access-state"><strong>VISUAL ACCESS</strong><div><span>Selected scene metadata</span><b>${observation.access?.metadata === 'available' ? 'Available' : 'Unavailable'}</b></div><div><span>Selected scene pixels</span><b class="${primary.evidenceBinding?.renderAllowed ? '' : 'status-warn'}">${primary.evidenceBinding?.pixelVerified ? 'Native raster · pixel verified' : 'Unavailable / rejected'}</b></div><div><span>Pixels on screen</span><b>${escapeHtml(visual?.sensor ?? 'None')}</b></div><div><span>Physical confirmation</span><b class="status-warn">Human / attributable evidence</b></div></div>`;
}
function fallbackView(observation, item) {
  const primary = observation.primary, fallback = observation.fallbackVisual;
  if (!fallback?.imageUrl) return metadataOnly(observation, item);
  return `<div class="observation-frame observation-fallback-frame" data-observation-frame data-change-screening="off" data-bbox="${escapeHtml((fallback.bbox ?? []).join(','))}"><div class="fallback-context-window"><div class="observation-transform" data-observation-transform><img src="${escapeHtml(fallback.imageUrl)}" alt="${escapeHtml(fallback.sensor)} broad visual context for ${escapeHtml(item.municipality)}"></div></div><div class="observation-shade"></div></div>
    <div class="observation-identity sensor-warning"><span>${escapeHtml(primary.sensor).toUpperCase()} PIXELS UNAVAILABLE · SHOWING ${escapeHtml(fallback.sensor).toUpperCase()} CONTEXT</span><h2>${escapeHtml(item.municipality)}${item.district ? ` · ${escapeHtml(item.district)}` : ''}</h2><p>${escapeHtml(coordinateLabel(item.coordinate))} · broad context only</p></div>
    <div class="observation-meta">${visualAccess(observation, primary)}<div class="observation-binding"><span>VISIBLE SENSOR</span><strong>${escapeHtml(fallback.sensor)}</strong><span>VISIBLE DATE</span><strong>${escapeHtml(fallback.acquiredDate)}</strong><span>SELECTED SCENE</span><strong>${escapeHtml(primary.sensor)} · ${escapeHtml(dateTime(primary.acquiredAt))}</strong><span>SELECTED SCENE ID</span><strong>${escapeHtml(primary.id)}</strong></div>${rationale(observation)}</div>
    <div class="observation-toolbar"><button type="button" data-studio-action="zoom-out" aria-label="Zoom out">−</button><button type="button" data-studio-action="zoom-in" aria-label="Zoom in">+</button><button type="button" data-studio-action="fit">Fit</button></div>
    <div class="observation-readout"><strong data-pointer-coordinate>${escapeHtml(coordinateLabel(item.coordinate))}</strong><span>Broad context is capped at low zoom to avoid manufactured detail</span></div>
    <div class="observation-foot"><div class="observation-quality fallback-warning"><strong>Detailed visual inspection unavailable.</strong><p>${escapeHtml(fallback.resolutionNotice)} Request a renderable high-resolution scene or attributable field evidence.</p></div><div class="observation-actions"><button type="button" data-action="request-evidence">Assign field verification</button><button type="button" data-action="show-baseline">Historical baseline</button></div></div>`;
}
function metadataOnly(observation, item) {
  const primary = observation.primary;
  return `<div class="observation-empty observation-metadata-only"><span class="eyebrow">PIXEL ACCESS UNAVAILABLE</span><h3>${escapeHtml(primary.sensor)} metadata exists for ${escapeHtml(item.municipality)}, but visual inspection cannot be performed.</h3><p>VIGIA will not substitute unrelated pixels and call them the selected observation.</p>${visualAccess(observation, primary)}<div class="observation-binding"><span>ACQUIRED</span><strong>${escapeHtml(dateTime(primary.acquiredAt))}</strong><span>SENSOR</span><strong>${escapeHtml(sensorDescription(primary.sensor))}</strong><span>SOURCE</span><strong>${escapeHtml(primary.source)}</strong><span>SCENE</span><strong>${escapeHtml(primary.id)}</strong></div><div class="action-grid"><button type="button" class="primary-action" data-action="request-evidence">Assign field verification</button><button type="button" class="secondary-action" data-action="show-baseline">Historical context</button></div></div>`;
}

function selectionMarker(coordinate, bbox) {
  if (!Array.isArray(coordinate) || !Array.isArray(bbox) || bbox.length !== 4) return '';
  const [lon, lat] = coordinate.map(Number), [west, south, east, north] = bbox.map(Number);
  if (![lon,lat,west,south,east,north].every(Number.isFinite) || east === west || north === south) return '';
  const left = Math.max(0, Math.min(100, ((lon - west) / (east - west)) * 100));
  const top = Math.max(0, Math.min(100, ((north - lat) / (north - south)) * 100));
  return `<div class="observation-location-marker" style="left:${left.toFixed(2)}%;top:${top.toFixed(2)}%" aria-label="Selected location within source scene"><i></i><span>Selected place</span></div>`;
}
function valueOrUnmeasured(value, suffix='') { return value === null || value === undefined || !Number.isFinite(Number(value)) ? 'UNMEASURED' : `${Math.round(Number(value))}${suffix}`; }
function decimalOrUnmeasured(value, suffix='') { return value === null || value === undefined || !Number.isFinite(Number(value)) ? 'UNMEASURED' : `${Number(value).toFixed(2)}${suffix}`; }
function reviewLab(state,item,primary,comparable) {
  if(item.kind!=='FUEL_CONTINUITY_CHANGE')return'';
  const priority=item.attentionPriority??{},reviews=item.reviewSummary??{},rationale=item.rationale??{},quality=item.sourceQuality??{};
  const disposition=preventionDisposition(item),action='measurement-plan',actionLabel=disposition.nextAction;
  const latest=reviews.latest?`${statusLabel(reviews.latest.decision)} · ${statusLabel(reviews.latest.reviewerType)}`:'UNREVIEWED';
  const change=Number.isFinite(Number(item.newFuelFraction))?`${Math.round(Number(item.newFuelFraction)*100)}% newly observable`:'New-fuel fraction unmeasured';
  const slope=item.terrainContext?.slopeDegrees?.median,land=item.landCoverContext?.dominantClass;
  return `<section class="review-lab-panel"><header><div><span>PREVENTION MEASUREMENT WORKSPACE</span><strong>${escapeHtml(disposition.label)}</strong></div><b>${escapeHtml(latest)}</b></header><div class="review-lab-grid"><article class="review-priority"><span>MEASUREMENT PRIORITY · NOT PROBABILITY</span><strong>${valueOrUnmeasured(priority.score)}</strong><p>${escapeHtml(statusLabel(priority.band??'unmeasured'))} · ${escapeHtml(change)}</p></article><article><span>SCENE PAIR</span><strong>${escapeHtml(evidenceDateTime(comparable?.acquiredAt))} → ${escapeHtml(evidenceDateTime(primary?.acquiredAt))}</strong><p>Current/prior split remains spatially synchronized.</p></article><article><span>PHYSICAL CONTINUITY</span><strong>${decimalOrUnmeasured(item.affectedAreaHa,' ha')} · ${valueOrUnmeasured(item.corridorLengthM,' m')} span</strong><p>${valueOrUnmeasured(item.nearestStructureM,' m')} to nearest mapped structure · ${valueOrUnmeasured(item.structuresWithinPolicyRadius)} within 150 m.</p></article><article><span>REAL MEASUREMENT CONTEXT</span><strong>${escapeHtml(statusLabel(land??'unmeasured'))} · ${valueOrUnmeasured(item.roadCrossings)} road intersections</strong><p>Copernicus DEM median slope ${valueOrUnmeasured(slope,'°')} · nearest mapped critical asset ${valueOrUnmeasured(item.criticalAssetProximityM,' m')}. Static context informs measurement; it is not a hazard label.</p></article></div><footer><span data-observation-view-legend>Natural colour · native pixels · geometry-bound context</span><div><button type="button" data-action="${action}">${escapeHtml(actionLabel)}</button></div></footer></section>`;
}
export function renderObservation(state, item) {
  const observation = state.observation; if (!item) return '';
  if (state.observationLoading) return `${preventionLane()}<div class="observation-empty"><h3>Resolving current observations…</h3><p>Checking recent optical, radar and attributable evidence for ${escapeHtml(item.municipality)}.</p></div>`;
  if (!observation?.primary) return `${preventionLane()}<div class="observation-empty"><h3>No defensible current observation.</h3><p>Assign field verification rather than substituting historical imagery.</p><button type="button" class="primary-action" data-action="request-evidence">Assign field verification</button></div>`;
  if (!observation.primary.evidenceBinding?.renderAllowed) return preventionLane()+fallbackView(observation, item);
  if (!observation.primary.imageUrl && !observation.primary.visualCogUrl) return preventionLane()+fallbackView(observation, item);
  const primary = observation.primary, history = (observation.timeline ?? []).find((scene) => (scene.visualCogUrl || scene.imageUrl) && scene.id !== primary.id);
  const preferredComparable = observation.comparable && (observation.comparable.visualCogUrl || observation.comparable.imageUrl) ? observation.comparable : null;
  const comparable = preferredComparable ?? history ?? primary, bbox = observation.viewportBbox ?? primary.bbox ?? comparable.bbox ?? [], canScreen = observation.changeScreening?.eligible === true;
  const analysisRadiusKm=item.kind==='FUEL_CONTINUITY_CHANGE'?3:9;
  const indexReady=[primary.redCogUrl,primary.nirCogUrl,primary.swir16CogUrl,comparable.redCogUrl,comparable.nirCogUrl,comparable.swir16CogUrl].every(Boolean);
  const viewTools=item.kind==='FUEL_CONTINUITY_CHANGE'?`<button type="button" class="is-active" data-studio-action="natural">Natural</button><button type="button" data-studio-action="vegetation" ${indexReady?'':'disabled'}>Vegetation</button><button type="button" data-studio-action="moisture" ${indexReady?'':'disabled'}>Moisture</button>`:'';
  const lab=item.kind==='FUEL_CONTINUITY_CHANGE'?avoidanceWorkbench(state,item):reviewLab(state,item,primary,comparable),findingClass=item.kind==='FUEL_CONTINUITY_CHANGE'?' has-review-lab has-avoidance-intelligence':'';
  return `${preventionLane()}<div class="observation-frame${findingClass}" data-observation-frame data-render-product="${escapeHtml(primary.visualCogUrl && comparable.visualCogUrl ? 'native_cog_available' : primary.renderProduct ?? 'unknown')}" data-change-screening="${canScreen ? 'on' : 'off'}" data-bbox="${escapeHtml(bbox.join(','))}" data-coordinate="${escapeHtml(item.coordinate.join(','))}" data-radius-km="${analysisRadiusKm}" data-primary-id="${escapeHtml(primary.id)}" data-comparable-id="${escapeHtml(comparable.id)}"><div class="observation-transform" data-observation-transform><canvas class="observation-cog" data-cog-before data-cog-url="${escapeHtml(comparable.visualCogUrl ?? '')}" data-red-url="${escapeHtml(comparable.redCogUrl ?? '')}" data-nir-url="${escapeHtml(comparable.nirCogUrl ?? '')}" data-swir-url="${escapeHtml(comparable.swir16CogUrl ?? '')}"></canvas><img data-observation-before hidden alt="Comparable ${escapeHtml(comparable.sensor)} observation for ${escapeHtml(item.municipality)}"></div><div class="observation-after" data-observation-after-wrap><div class="observation-transform" data-observation-transform><canvas class="observation-cog" data-cog-after data-cog-url="${escapeHtml(primary.visualCogUrl ?? '')}" data-red-url="${escapeHtml(primary.redCogUrl ?? '')}" data-nir-url="${escapeHtml(primary.nirCogUrl ?? '')}" data-swir-url="${escapeHtml(primary.swir16CogUrl ?? '')}"></canvas><img data-observation-after hidden alt="Latest ${escapeHtml(primary.sensor)} observation for ${escapeHtml(item.municipality)}"></div></div>${findingSurface(observation,item)}${connectivityOverlay(item,bbox)}${selectionMarker(item.coordinate,bbox)}<input data-observation-slider class="observation-slider" type="range" min="0" max="100" value="50" aria-label="Drag to compare current and earlier observation"><span class="observation-divider" data-observation-divider><i>↔</i></span><div class="observation-shade"></div></div>
    <div class="observation-identity"><span>${escapeHtml(primary.sensor).toUpperCase()} · SELECTED OBSERVATION</span><h2>${escapeHtml(item.municipality)}${item.district ? ` · ${escapeHtml(item.district)}` : ''}</h2><p>${escapeHtml(coordinateLabel(item.coordinate))} · ${escapeHtml(sensorDescription(primary.sensor))}</p></div>
    <div class="observation-meta">${suitability(primary,{visual:true})}<div class="observation-binding"><span>ACQUIRED</span><strong>${escapeHtml(dateTime(primary.acquiredAt))}</strong><span>SOURCE</span><strong>${escapeHtml(primary.source)}</strong><span>SCENE</span><strong>${escapeHtml(primary.id)}</strong><span>GEOGRAPHIC BINDING</span><strong>${escapeHtml(primary.evidenceBinding?.state ?? 'unverified')} · ${escapeHtml(primary.evidenceBinding?.bindingHash?.slice(0,12) ?? 'no proof')}</strong></div>${rationale(observation)}</div>
    <div class="observation-dates"><div><span>COMPARISON</span><strong data-before-date>${escapeHtml(evidenceDateTime(comparable.acquiredAt))}</strong></div><div><span>LATEST USABLE</span><strong>${escapeHtml(evidenceDateTime(primary.acquiredAt))}</strong></div></div>
    <div class="observation-toolbar"><button type="button" data-studio-action="zoom-out" aria-label="Zoom out">−</button><button type="button" data-studio-action="zoom-in" aria-label="Zoom in">+</button><button type="button" data-studio-action="fit">Fit</button><button type="button" data-studio-action="flicker">Flicker</button><button type="button" data-studio-action="findings" ${canScreen || item.detectorFindings?.length ? 'class="is-active"' : 'disabled'}>Physical change</button>${item.kind==='FUEL_CONTINUITY_CHANGE'?'<button type="button" class="is-active" data-studio-action="connectivity">Fuel graph</button><button type="button" class="is-active" data-studio-action="assets">Asset connections</button><button type="button" class="is-active" data-studio-action="consensus">Consensus zone</button><button type="button" disabled title="Structures are shown as measured context when geometry is unavailable">Structures</button><button type="button" disabled title="Roads are shown as measured context when geometry is unavailable">Roads</button><button type="button" disabled title="Terrain is shown as measured context when geometry is unavailable">Terrain</button>':''}${viewTools}</div>
    <div class="observation-readout"><strong data-pointer-coordinate>${escapeHtml(coordinateLabel(item.coordinate))}</strong><span>Wheel to zoom · drag to pan · split comparison remains synchronized</span></div>${timeline(observation,primary)}
    ${lab||`<div class="observation-foot"><div class="observation-quality"><strong>${escapeHtml(observation.safety)}</strong><p>${escapeHtml(observation.notice)} ${escapeHtml(observation.changeScreening?.reason ?? '')}</p></div><div class="observation-actions"><button type="button" data-action="request-evidence">Assign field verification</button><button type="button" data-action="show-baseline">Historical baseline</button></div></div>`}`;
}
