import { systemValidationHtml } from '../app/action-handler.js';
import { escapeHtml } from '../utils/html.js';
import { avoidanceFor } from './prevention-connectivity.js';

export const validationFilters=Object.freeze([]);

const number=(value)=>value===null||value===undefined||value===''?'UNMEASURED':Number(value).toLocaleString();
const percent=(value)=>value===null||value===undefined||!Number.isFinite(Number(value))?'UNMEASURED':`${(Number(value)*100).toFixed(1)}%`;

function domainCard({id,label,state='limited',proven,limited,debt,metrics=[]}){
  return `<article class="validation-proof-card validation-domain-card is-${escapeHtml(state)}" id="validation-proof-${escapeHtml(id)}"><header><span>${escapeHtml(label)}</span><strong>${escapeHtml(state.replaceAll('_',' '))}</strong></header><dl class="validation-domain-verdict"><div><dt>PROVEN</dt><dd>${escapeHtml(proven)}</dd></div><div><dt>LIMITED</dt><dd>${escapeHtml(limited)}</dd></div><div><dt>OPEN MEASUREMENT DEBT</dt><dd>${escapeHtml(debt)}</dd></div></dl><dl>${metrics.map(([name,value])=>`<div><dt>${escapeHtml(name)}</dt><dd>${escapeHtml(String(value))}</dd></div>`).join('')}</dl></article>`;
}

function proofGrid(state){
  const benchmark=state.detectionBenchmark??{},headline=benchmark.headline??{},active=headline.metrics??benchmark.v4??benchmark.v3??{},s3=benchmark.physicalSensing?.sentinel3??{},live=state.live?.summary??{},prevention=benchmark.prevention?.inventory??{},preventState=state.bootstrap?.prevention??{},preventValidation=preventState.validation??{},operations=state.operationsMetrics??{},findings=preventState.findings??[],derivedAvoidance=findings.map(avoidanceFor),fuelGraphCount=preventValidation.fuelGraphCount??derivedAvoidance.filter((item)=>item.graph?.edges?.length).length,interventionCandidateCount=preventValidation.interventionCandidateCount??derivedAvoidance.filter((item)=>item.candidate).length,expertCount=prevention.domainExpertReviewed??preventValidation.domainExpertReviewCount??0,debtItems=benchmark.measurementDebt?.items??[],fieldReport=benchmark.pilotReport?.fieldNetResilience??{};
  const cards=[
    domainCard({id:'detection',label:'DETECTION',state:Object.keys(active).length?'proven':'unavailable',proven:Object.keys(active).length?`${number(active.eligibleCases??active.cases)} frozen confirmatory cases`:'Benchmark artifact unavailable',limited:'Performance is conditional on governed observation opportunity and cohort eligibility.',debt:`${number((benchmark.falseNegativeTaxonomy?.cases??[]).length||debtItems.filter((item)=>String(item.id).includes('detect')).length)} detection debts / cases remain inspectable`,metrics:[['Precision · conditional',percent(active.precision)],['Recall · given signal',percent(active.recall)],['False positives',number(active.falsePositives)]]}),
    domainCard({id:'prevent',label:'PREVENT',state:interventionCandidateCount>0?'limited':'unavailable',proven:`${number(fuelGraphCount)} physical fuel graphs · ${number(interventionCandidateCount)} graph-bound candidates`,limited:`${number(expertCount)} attributable expert labels; no efficacy or autonomous treatment claim`,debt:`${number(debtItems.filter((item)=>String(item.id).includes('prevent')).length)} open measurement contracts`,metrics:[['Consensus promotion','NOT PROMOTED'],['Exact breakpoints','SUPPRESSED'],['Field outcomes','UNMEASURED']]}),
    domainCard({id:'fieldnet',label:'FIELDNET',state:fieldReport.exerciseVerdict?'limited':'unavailable',proven:fieldReport.exerciseVerdict?`Controlled offline exercise: ${fieldReport.exerciseVerdict}`:'Controlled resilience artifact unavailable',limited:'Local incident operation is proven separately from regional connectivity or a live customer deployment.',debt:'Prospective field denominators and external deployment remain open.',metrics:[['Controlled delivery',fieldReport.messageDelivery?`${number(fieldReport.messageDelivery.numerator)} / ${number(fieldReport.messageDelivery.denominator)}`:'UNMEASURED'],['Zero lost evidence',fieldReport.zeroLostEvidence===true?'VERIFIED CONTROLLED':'UNMEASURED'],['Live partner','UNASSIGNED']]}),
    domainCard({id:'operations',label:'OPERATIONS',state:state.operationsState==='ready'?'proven':state.operationsState==='partially_available'?'limited':'unavailable',proven:state.operationsState==='ready'?`${number(operations.denominators?.alerts)} persisted alerts`:'PostGIS operations not currently measurable',limited:'Lifecycle persistence does not prove response effectiveness or external adjudication.',debt:'Acknowledgement, closure yield and operational outcome denominators remain explicit.',metrics:[['Deliveries',number(operations.denominators?.deliveries)],['Ack sample',number(operations.latency?.alert_to_acknowledgement?.sampleCount)],['Two-family events',number(s3.twoFamilyEvents??live.viirsSentinel3Events)] ]})
  ];
  return `<section class="validation-proof-grid validation-domain-grid" aria-label="Validation domains">${cards.join('')}</section>`;
}

function finiteState(state){
  const value=state.validationState??(state.validationLoading?'loading':state.detectionBenchmark?'ready':'idle');
  if(value==='loading')return '<div class="validation-state-banner is-loading" role="status"><span>LOADING</span><strong>Resolving independent validation artifacts</strong><p>Command and physical evidence remain usable while this bounded request completes.</p></div>';
  if(value==='error'||value==='unavailable')return `<div class="validation-state-banner is-error" role="alert"><span>${value==='error'?'ERROR':'UNAVAILABLE'}</span><strong>Governed validation evidence could not be resolved</strong><p>${escapeHtml(state.validationError??'The independent benchmark endpoint is unavailable.')}</p><button type="button" data-action="retry-validation">Retry validation</button></div>`;
  if(value==='partially_available')return '<div class="validation-state-banner is-partial"><span>PARTIALLY AVAILABLE</span><strong>Primary benchmark loaded; one supporting domain is unavailable</strong><p>Measured artifacts remain visible and unavailable domains stay explicit.</p></div>';
  if(value==='ready')return `<div class="validation-state-banner is-ready"><span>READY</span><strong>Independent validation artifacts resolved</strong><p>${state.validationUpdatedAt?`Checked ${escapeHtml(new Date(state.validationUpdatedAt).toLocaleString())}`:'Current governed evidence is shown below.'}</p></div>`;
  return '<div class="validation-state-banner"><span>AVAILABLE ON OPEN</span><strong>Validation loads independently from Command</strong><p>This surface never waits on Alert or PostGIS operations.</p></div>';
}

function denominatorMetric(label,value,measured,target,note){
  const available=Number(measured)>0&&value!==null&&value!==undefined;
  return `<article class="machine-science-metric is-${available?'measured':'program'}"><header><span>${escapeHtml(label)}</span><strong>${available?'MEASURED':'MEASUREMENT PROGRAM'}</strong></header><h3>${available?escapeHtml(String(value)):Number(target)>0?`${number(measured)} / ${number(target)} measured`:'NO OBSERVED CASES'}</h3><p>${escapeHtml(note)}</p></article>`;
}

function machineScience(state){
  const evidence=state.detectionBenchmark?.machineEvidence,metrics=evidence?.metrics??{},debt=state.detectionBenchmark?.measurementDebt,items=debt?.items??[];
  if(!evidence||!debt)return '';
  const debtFor=(id)=>items.find((item)=>item.id===id)??{};
  const cards=[
    denominatorMetric('REFERENCE CONCORDANCE',metrics.landCover?.medianConcordance==null?null:percent(metrics.landCover.medianConcordance),metrics.landCover?.measured,metrics.denominatorFindings,'ESA WorldCover geometry binding; disagreement and unmapped fractions retained.'),
    denominatorMetric('REPEAT-SCENE STABILITY',metrics.repeatScene?.medianCandidateSurvival==null?null:percent(metrics.repeatScene.medianCandidateSurvival),metrics.repeatScene?.measured,debtFor('debt:prevent:repeat-scene').target_denominator,'Comparable no-leakage Sentinel-2 scene pairs are required before stability exists.'),
    denominatorMetric('BREAKPOINT ROBUSTNESS',metrics.counterfactual?.medianRetention==null?null:percent(metrics.counterfactual.medianRetention),metrics.counterfactual?.measured,metrics.denominatorFindings,'101 deterministic graph-uncertainty trials per finding; retention is not efficacy.'),
    denominatorMetric('GRAPH STABILITY',metrics.graph?.medianNodeStability==null?null:percent(metrics.graph.medianNodeStability),metrics.graph?.measured,debtFor('debt:prevent:threshold-stability').target_denominator,'Node and edge stability remain unmeasured until the bounded parameter campaign yields valid cases.'),
    denominatorMetric('NEGATIVE-CONTROL PERFORMANCE',evidence.negativeControls?.specificity==null?null:percent(evidence.negativeControls.specificity),evidence.negativeControls?.authoritativeNegativeLabels,100,'Decision-audit samples are not true negatives. Authoritative management-change labels are still required.'),
    denominatorMetric('RETROSPECTIVE RELEVANCE',null,evidence.retrospectiveAlignment?.denominator,50,evidence.retrospectiveAlignment?.reason??'A frozen pre-event corpus is required before later perimeters may be consulted.')
  ];
  const expert=metrics.expertValidation??{};
  return `<section class="machine-science" id="validation-machine-science"><header><div><span>MACHINE-VERIFIED SCIENCE</span><h2>Measured without pretending it is field truth.</h2></div><p>${escapeHtml(evidence.scientificClaimBoundary)}</p></header><div class="machine-science-grid">${cards.join('')}</div><aside class="human-validation-boundary"><div><span>HUMAN / FIELD VALIDATION</span><strong>${escapeHtml(String(expert.state??'NOT_PERFORMED').replaceAll('_',' '))}</strong></div><p>${number(expert.labels)} attributable labels · precision and recall remain UNMEASURED. Machine evidence does not authorize intervention.</p></aside></section>`;
}

function evidenceDebt(state){
  const debt=state.detectionBenchmark?.measurementDebt;if(!debt)return '';
  const summary=debt.summary??{},campaigns=state.detectionBenchmark?.measurementCampaigns?.campaigns??[],open=(debt.items??[]).filter((item)=>!['MEASURED','RESOLVED'].includes(item.current_state));
  const summaryItems=[['OPEN',summary.open],['SYSTEM-RESOLVABLE',summary.systemResolvable],['WATCHING',summary.watching],['CAMPAIGNS',summary.measurementCampaigns],['FIELD-REQUIRED',summary.fieldRequired],['EXTERNALLY BLOCKED',summary.externallyBlocked]];
  const cards=open.map((item)=>{
    const campaign=campaigns.find((value)=>(value.remainingDebt??[]).includes(item.id)),progress=campaign?.progress,percentComplete=item.target_denominator?Math.min(100,Math.round(Number(item.current_denominator??0)/Number(item.target_denominator)*100)):0;
    return `<article class="evidence-debt-card is-${escapeHtml(item.current_state.toLowerCase())}"><header><div><span>${escapeHtml(item.current_state.replaceAll('_',' '))}</span><strong>${escapeHtml(item.owner_class.replaceAll('_',' '))}</strong></div><b>${number(item.current_denominator)} / ${number(item.target_denominator)}</b></header><h3>${escapeHtml(item.quantity_question)}</h3><div class="debt-progress"><i style="width:${percentComplete}%"></i></div><dl><div><dt>What we do not know</dt><dd>${escapeHtml(item.why_unknown)}</dd></div><div><dt>Why it matters</dt><dd>${escapeHtml(item.why_it_matters)}</dd></div><div><dt>How we can know</dt><dd>${escapeHtml((item.evidence_required??[]).join(' · '))}</dd></div><div><dt>What VIGIA is doing</dt><dd>${escapeHtml(campaign?`${campaign.objective} · ${progress?.completed??0}/${progress?.denominator??item.target_denominator}`:item.watch_state==='NOT_ARMED'?'Measurement plan defined; acquisition not armed.':item.watch_state.replaceAll('_',' '))}</dd></div><div><dt>When we expect an answer</dt><dd>${escapeHtml(item.next_opportunity??(item.system_resolvable?'After the governed measurement campaign reaches its denominator.':'External authority has not supplied a date.'))}</dd></div><div><dt>What closes it</dt><dd>${escapeHtml(item.closure_contract)}</dd></div></dl></article>`;
  }).join('');
  return `<section class="evidence-debt-workspace" id="validation-evidence-debt"><header><div><span>EVIDENCE DEBT</span><h2>Unknown becomes owned measurement work.</h2></div><p>${escapeHtml(debt.scientificClaimBoundary)}</p></header><div class="evidence-debt-summary">${summaryItems.map(([name,value])=>`<div><strong>${number(value)}</strong><span>${escapeHtml(name)}</span></div>`).join('')}</div><div class="evidence-debt-list">${cards}</div></section>`;
}

function failureClusters(state){
  const taxonomy=state.detectionBenchmark?.falseNegativeTaxonomy;if(!taxonomy)return '';
  const clusters=Object.entries(taxonomy.taxonomy??{}),recovery=taxonomy.recovery??{};
  return `<section class="failure-clusters" id="validation-failure-clusters"><header><div><span>FAILURE CLUSTERS · 18 FROZEN CASES</span><h2>Fix recoverable policy errors. Name sensor limits.</h2></div><p>${escapeHtml(taxonomy.reason??'')}</p></header><div class="failure-cluster-grid">${clusters.map(([name,value])=>`<article><span>${escapeHtml(name.replaceAll('_',' '))}</span><strong>${number(value.count)}</strong><p>${percent(value.percentage)} of false negatives</p></article>`).join('')}<article class="is-recoverable"><span>RECOVERABLE WITH CURRENT DATA</span><strong>${number(recovery.RECOVERABLE_WITH_CURRENT_DATA?.count)}</strong><p>Policy-recoverable · ${percent(recovery.RECOVERABLE_WITH_CURRENT_DATA?.percentage)}</p></article><article class="is-sensing"><span>REQUIRES NEW SENSING</span><strong>${number(recovery.REQUIRES_NEW_SENSING?.count)}</strong><p>Sensor-limited · ${percent(recovery.REQUIRES_NEW_SENSING?.percentage)}</p></article></div></section>`;
}

const scoreValue=(metric)=>metric?.state==='MEASURED'?(metric.unit==='ratio'?percent(metric.value):number(metric.value)):'NO OBSERVED CASES';
function liveCampaign(state){
  const scorecards=state.detectionBenchmark?.liveCampaignScorecards;if(!scorecards)return '';
  const metrics=[['SOURCE AVAILABILITY','sourceAvailability'],['PHYSICAL CANDIDATES','physicalCandidates'],['PHYSICAL-FIRST','physicalFirst'],['MULTISOURCE','multisource'],['ALERT DELIVERY','alertsDelivered'],['ACKNOWLEDGED','acknowledged'],['EVIDENCE DEBT CLOSED','evidenceDebtsSystemResolved'],['FIELDNET SYNC','syncSuccess']];
  return `<section class="live-shadow-campaign" id="validation-live-campaign"><header><div><span>VIGIA LIVE SHADOW CAMPAIGN</span><h2>Prospective from ${escapeHtml(new Date(scorecards.campaign.prospectiveBoundaryAt).toLocaleString())}.</h2></div><p>${escapeHtml(scorecards.campaign.qualification)} Retrospective backfill is disabled.</p></header><div class="campaign-windows">${scorecards.windows.map((window)=>`<article><header><span>${escapeHtml(window.label.replaceAll('_',' '))}</span><strong>${number(window.prospectiveRecordCount)} records</strong></header><dl>${metrics.map(([labelName,key])=>`<div><dt>${escapeHtml(labelName)}</dt><dd class="is-${escapeHtml(window.metrics[key]?.state?.toLowerCase()??'unknown')}">${escapeHtml(scoreValue(window.metrics[key]))}</dd></div>`).join('')}</dl></article>`).join('')}</div></section>`;
}

function pilotInBox(state){
  const pilot=state.detectionBenchmark?.pilotDefinition,report=state.detectionBenchmark?.pilotReport;if(!pilot||!report)return '';
  const roleCount=(pilot.usersAndRoles??[]).reduce((sum,item)=>sum+Number(item.assigned??0),0),kpis=report.kpis??{};
  const kpiRows=[['Source availability',kpis.sourceAvailability],['Physical-first share',kpis.physicalFirst],['Multisource corroboration',kpis.multisourceCorroboration],['Alert acknowledgement',kpis.alertToAcknowledgementLatency],['EvidenceDebt closure',kpis.evidenceDebtClosure],['Offline uptime',kpis.offlineUptime]];
  return `<section class="pilot-in-box" id="validation-pilot"><header><div><span>PILOT-IN-A-BOX</span><h2>${escapeHtml(pilot.organization)}</h2></div><a href="/api/v10/pilot/report" target="_blank" rel="noopener">EXPORT GOVERNED PILOT REPORT</a></header><div class="pilot-contract"><article><span>TERRITORY</span><strong>${escapeHtml(pilot.territory.kind.replaceAll('_',' '))}</strong><p>${number(pilot.territory.bufferKm)} km bounded cell · ${number(report.territory.offlineGeography?.road)} roads/trails · ${number(report.territory.packageBytes)} byte offline package</p></article><article><span>PEOPLE + POLICY</span><strong>${number(roleCount)} assigned</strong><p>${escapeHtml(pilot.schedule.state.replaceAll('_',' '))} · alert policy ${escapeHtml(pilot.alertPolicies.state.replaceAll('_',' '))}</p></article><article><span>FIELDNET CONTRACT</span><strong>${escapeHtml(report.fieldNetResilience.exerciseVerdict)}</strong><p>${number(report.fieldNetResilience.messageDelivery.numerator)} / ${number(report.fieldNetResilience.messageDelivery.denominator)} controlled messages · zero lost evidence ${report.fieldNetResilience.zeroLostEvidence?'verified':'not verified'}</p></article></div><div class="pilot-kpis">${kpiRows.map(([labelName,metric])=>`<div><span>${escapeHtml(labelName)}</span><strong>${escapeHtml(metric?.state?.startsWith('MEASURED_CONTROLLED')?metric.state.replaceAll('_',' '):scoreValue(metric))}</strong></div>`).join('')}</div><p class="pilot-boundary">No fake customer, ROI, lives saved or fires avoided. Partner territory, users, dates and policies must be assigned before a live pilot.</p></section>`;
}

const when=(value)=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString():'UNAVAILABLE';
const sourceState=(source)=>String(source?.state??source?.selected?.state??'unavailable').replaceAll('_',' ').toUpperCase();
const sourceTone=(source)=>source?.state==='current'?'proven':source?.state==='stale'?'partial':['empty','catalogue_available','planner_ready'].includes(source?.state)?'controlled':'unavailable';

function evidenceSourceRows(state){
  const sources=state.live?.sources??state.bootstrap?.sources??{};
  const ordered=[['firms','VIIRS','NASA FIRMS'],['sentinel3Pixels','SENTINEL-3 / SLSTR','Copernicus / EUMETSAT'],['fires','PUBLIC REPORTS','ICNF / SGIF'],['weather','WEATHER CONTEXT','IPMA'],['copernicus','PREVENT IMAGERY','Copernicus catalogue']];
  return ordered.map(([id,labelName,provider])=>{const source=sources[id]??{},latest=source.latestSourceObservation??source.upstreamAt??source.selected?.latestTime??source.lastSuccessAt,count=source.accepted??source.count??source.selected?.count;return `<button type="button" class="evidence-source-row is-${sourceTone(source)}" data-action="sources"><span class="evidence-source-mark"></span><span><strong>${escapeHtml(labelName)}</strong><small>${escapeHtml(source.provider??source.origin??provider)}</small></span><b>${escapeHtml(sourceState(source))}</b><span><small>LATEST</small><strong>${escapeHtml(when(latest))}</strong></span><span><small>ACCEPTED</small><strong>${count==null?'UNMEASURED':number(count)}</strong></span></button>`;}).join('');
}

function evidencePreview(state){
  const events=state.live?.events??[],event=events.find((item)=>item.physicalSourceProfile?.twoPhysicalSourceFamilies===true)??events.find((item)=>item.observations?.length)??events[0];
  if(!event)return `<section class="evidence-preview is-empty"><header><span>EVIDENCE PREVIEW</span><strong>No attributable event selected</strong></header><p>The live evidence graph is empty or unavailable. No observation, confidence, or provenance is inferred.</p></section>`;
  const observations=(event.observations??[]).filter((item)=>item.type==='thermal'),latest=observations.slice().sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))[0],families=event.physicalSourceProfile?.families??event.fireEvidenceState?.physicalSourceFamilies??[],association=event.association?.state??event.associationState??'UNRESOLVED';
  return `<section class="evidence-preview"><header><div><span>EVIDENCE PREVIEW</span><strong>${escapeHtml(event.label??event.id)}</strong></div><b>${escapeHtml(String(event.physicalState?.freshness??'unknown').toUpperCase())}</b></header><div class="evidence-preview-body"><div class="evidence-preview-map" aria-label="Evidence location summary"><span>${escapeHtml(event.coordinate?.length?`${Number(event.coordinate[1]).toFixed(4)}°N · ${Math.abs(Number(event.coordinate[0])).toFixed(4)}°W`:'LOCATION UNAVAILABLE')}</span><i></i><strong>${latest?.frpMw!=null?`${number(latest.frpMw)} MW`:'FRP UNMEASURED'}</strong><small>${escapeHtml(latest?.platform??latest?.source??'SOURCE UNAVAILABLE')}</small></div><dl><div><dt>PHYSICAL FAMILIES</dt><dd>${families.length?families.map((item)=>escapeHtml(String(item).replaceAll('_',' '))).join(' + '):'UNMEASURED'}</dd></div><div><dt>ASSOCIATION</dt><dd>${escapeHtml(String(association).replaceAll('_',' ').toUpperCase())}</dd></div><div><dt>FIRST PHYSICAL</dt><dd>${escapeHtml(when(event.physicalState?.firstAt??observations.at(-1)?.at))}</dd></div><div><dt>LATEST PHYSICAL</dt><dd>${escapeHtml(when(event.physicalState?.lastAt??latest?.at))}</dd></div><div><dt>PUBLIC REPORT</dt><dd>${escapeHtml(String(event.reportState?.sourceActivity??'NO REPORT').replaceAll('_',' ').toUpperCase())}</dd></div><div><dt>RAW PRODUCT</dt><dd>${latest?.rawProductArchived?'ARCHIVED':'NOT PROVEN'}</dd></div></dl></div></section>`;
}

function evidenceAudit(state){
  const event=(state.live?.events??[]).find((item)=>item.observations?.length)??state.live?.events?.[0],timeline=(event?.timeline??[]).slice(-7).reverse();
  return `<section class="evidence-audit"><header><span>AUDIT TRAIL</span><strong>${timeline.length} attributable entries shown</strong></header>${timeline.length?timeline.map((item)=>`<article><time>${escapeHtml(when(item.at??item.observedAt))}</time><span><strong>${escapeHtml(item.label??item.type??'EVIDENCE STATE CHANGE')}</strong><small>${escapeHtml(item.source??item.actor??'SOURCE UNAVAILABLE')}</small></span><b>${escapeHtml(String(item.verification??item.state??'RECORDED').replaceAll('_',' ').toUpperCase())}</b></article>`).join(''):'<p>No attributable audit entry is available for the selected evidence graph.</p>'}</section>`;
}

export function validationSummary(state){const events=state.live?.events??[],physical=events.filter((item)=>item.physicalState?.firstAt).length;return `<div class="validation-route-summary"><strong>${number(physical)}</strong><span>Physical event graphs with attributable provenance</span></div>`;}

export function systemProofSummary(state){const value=state.validationState??(state.validationLoading?'loading':state.detectionBenchmark?'ready':'idle');return `<div class="validation-route-summary"><strong>${escapeHtml(value.replaceAll('_',' ').toUpperCase())}</strong><span>Release, runtime, benchmark, and operational proof boundaries</span></div>`;}

export function validationWorkbench(state){
  const method=state.detectionBenchmark?`${proofGrid(state)}${systemValidationHtml(state)}`:'';
  return `<div class="evidence-workspace"><header><div><span>EVIDENCE · PROVENANCE</span><h1>Source chain and decision evidence</h1></div><p>Attributable source state first. Technical method stays behind disclosure.</p></header>${finiteState(state)}<div class="evidence-layout"><section class="evidence-source-chain"><header><span>SOURCE CHAIN</span><strong>Provider → observation → event</strong></header>${evidenceSourceRows(state)}</section>${evidencePreview(state)}${evidenceAudit(state)}</div><details class="evidence-method"><summary>Evidence boundaries and technical method</summary><p>Provider observations, public reports, associations, benchmark labels, and operator decisions retain separate provenance. A report is not treated as ignition truth; stale physical evidence is not presented as current.</p>${method}</details></div>`;
}

export function systemProofWorkbench(state){
  const detail=state.detectionBenchmark?systemValidationHtml(state):'';
  const chapter=(index,label,description,body,open=false)=>body?`<details class="validation-chapter" ${open?'open':''}><summary><span>${index}</span><div><strong>${label}</strong><small>${description}</small></div><b>${open?'CURRENT':'OPEN'}</b></summary>${body}</details>`:'';
  const sourceCurrent=Object.values(state.live?.sources??{}).filter((item)=>item?.state==='current').length,release=state.bootstrap?.meta?.releaseId??state.bootstrap?.release?.releaseId??'UNAVAILABLE',events=state.live?.events??[],physical=events.reduce((sum,item)=>sum+Number(item.observations?.filter((observation)=>observation.type==='thermal').length??0),0),benchmark=state.detectionBenchmark?.availability?.state??state.validationState??'UNAVAILABLE';
  const proofs=[['APPLICATION HEALTH',state.bootstrap?'PROVEN':'NOT PROVEN','Command projection resolved'],['DATABASE / OPERATIONS',state.operationsState==='ready'?'PROVEN':state.operationsState==='partially_available'?'PARTIAL':'NOT PROVEN','PostGIS-backed operational state'],['RELEASE IDENTITY',release==='UNAVAILABLE'?'NOT PROVEN':'PROVEN',release],['PROVIDER INGESTION',sourceCurrent?'PROVEN':'PARTIAL',`${sourceCurrent} current provider source${sourceCurrent===1?'':'s'}`],['PERSISTED PHYSICAL EVIDENCE',physical?'PROVEN':'PARTIAL',`${number(physical)} thermal observations in current projection`],['DETECTION BENCHMARK',String(benchmark).toUpperCase()==='READY'?'PROVEN':'PARTIAL',String(benchmark).replaceAll('_',' ')],['FIELDNET',state.detectionBenchmark?.pilotReport?.fieldNetResilience?.exerciseVerdict?'CONTROLLED SOFTWARE PROOF':'NOT PROVEN','No regional mesh or customer deployment claim']];
  return `<div class="validation-workspace system-proof-workspace"><header><div><span>SYSTEM PROOF · RELEASE BOUNDARY</span><h1>What VIGIA can defend now</h1></div><p>Production truth, controlled proof, partial evidence, and unsupported claims remain visibly separate.</p></header>${finiteState(state)}<section class="system-proof-grid">${proofs.map(([labelName,status,detailText])=>`<article class="is-${escapeHtml(status.toLowerCase().replaceAll(' ','-'))}"><span>${escapeHtml(labelName)}</span><strong>${escapeHtml(status)}</strong><p>${escapeHtml(String(detailText))}</p></article>`).join('')}</section>${state.detectionBenchmark?proofGrid(state):''}${chapter('02','FAILURE CLUSTERS','Count, share, recoverability and next engineering strategy',failureClusters(state))}${chapter('03','MEASUREMENT DEBT','Denominator, owner, campaign and closure contract',evidenceDebt(state))}${chapter('PREVENT','MACHINE-VERIFIED SCIENCE','Separate from human and field validation',machineScience(state))}${chapter('LIVE','PROSPECTIVE CAMPAIGN','24 hour, 7 day and 30 day denominators',liveCampaign(state))}${chapter('PILOT','PILOT-IN-A-BOX','Governed design-partner measurement contract',pilotInBox(state))}${detail?`<details class="validation-case-drilldown"><summary><span>04</span><div><strong>INDIVIDUAL CASES + METHOD</strong><small>Governed evidence ledger and technical method</small></div><b>OPEN</b></summary>${detail}</details>`:''}</div>`;
}
