import path from 'node:path';
import { analyzeGapImpact } from '../../../../../packages/domain/src/data-foundry/index.mjs';
import { compileCrisisDecisionState, createDecisionReplayRecord, verifyDecisionReplay } from '../../../../../packages/domain/src/decision-foundry/index.mjs';
import { semanticHash, uniqueSorted } from '../../../../../packages/domain/src/intelligence/shared.mjs';
import { readJson, writeJsonAtomic } from '../../shared/json-file.mjs';
import { corpusPaths } from '../forecast-corpus/corpus-paths.mjs';
import { buildDataFoundryCatalog } from '../data-foundry/catalog-builder.mjs';
import { dataFoundryPaths } from '../data-foundry/foundry-paths.mjs';
import { FileIntelligenceRepository } from '../intelligence/file-intelligence-repository.mjs';
import { decisionFoundryPaths } from './decision-foundry-paths.mjs';
import { materializeDecisionObjectSetProjection } from './object-set-projection.mjs';
import { signDecisionPacket } from './proof-service.mjs';
import { invalidateDecisionObjectSetCache } from './query-service.mjs';

function evidenceFacts(incident, knowledgeTime) {
  const at = (value) => value ?? knowledgeTime, facts = [{ id: `incident:${incident.id}`, kind: 'OFFICIAL_WILDFIRE_INCIDENT', availableToVigiaAt: at(incident.discoveryTime), sourceClass: 'OFFICIAL', causalFamilyId: 'WFIGS', qualityState: 'ACCEPTED', rightsState: 'READY' }, { id: `report:${incident.id}`, kind: 'PUBLIC_OR_OFFICIAL_REPORT', availableToVigiaAt: at(incident.discoveryTime), sourceClass: 'REPORT', causalFamilyId: 'WFIGS', qualityState: 'ACCEPTED', rightsState: 'READY' }];
  for (const observation of incident.physicalObservations ?? []) facts.push({ id: observation.id, kind: 'PHYSICAL_THERMAL_OBSERVATION', availableToVigiaAt: at(observation.availableToVigiaAt ?? observation.observedAt), sourceClass: 'PHYSICAL', causalFamilyId: observation.causalFamily ?? observation.instrument ?? 'VIIRS', qualityState: 'ACCEPTED', rightsState: 'READY' });
  if ((incident.perimeterStates?.length ?? 0) >= 3) facts.push({ id: `progression:${incident.id}`, kind: 'PERIMETER_PROGRESSION', availableToVigiaAt: at(incident.perimeterStates.at(-1)?.clocks?.availableToVigiaAt), sourceClass: 'OFFICIAL', causalFamilyId: 'WFIGS', qualityState: 'ACCEPTED', rightsState: 'READY' }, { id: `moving:${incident.id}`, kind: 'MOVING_PERIMETER_PROGRESSION', availableToVigiaAt: at(incident.perimeterStates.at(-1)?.clocks?.availableToVigiaAt), sourceClass: 'OFFICIAL', causalFamilyId: 'WFIGS', qualityState: 'ACCEPTED', rightsState: 'READY' });
  if (new Set(incident.causalFamilies ?? []).size >= 2) facts.push({ id: `independent:${incident.id}`, kind: 'INDEPENDENT_PHYSICAL_CORROBORATION', availableToVigiaAt: knowledgeTime, sourceClass: 'PHYSICAL', causalFamilyId: 'MULTI_FAMILY', qualityState: 'ACCEPTED', rightsState: 'READY' });
  if ((incident.causalFamilies ?? []).includes('VIIRS') && incident.fedsProgression) facts.push({ id: `duplicate:feds:${incident.id}`, kind: 'CAUSAL_DUPLICATE', availableToVigiaAt: knowledgeTime, sourceClass: 'LINEAGE', causalFamilyId: 'VIIRS', qualityState: 'ACCEPTED', rightsState: 'READY' });
  return facts;
}

function productKinds(incident, examples) { const values = ['PROGRESSION_SEQUENCE']; if (incident.weatherRuns?.some((item) => item.valuesDecoded && item.qualityState === 'CERTIFIED')) values.push('DECODED_WEATHER'); if (incident.fuelPack) values.push('FUEL_PACK'); if (incident.terrainPack) values.push('TERRAIN_PACK'); for (const horizon of new Set(examples.map((item) => item.horizonHours))) values.push(`FUTURE_LABEL_${horizon}H`); if (incident.perimeterStates?.length) values.push('OFFICIAL_OR_ACCEPTABLE_PERIMETER'); return uniqueSorted(values); }
function blockerFor(action, gap, incident) { const values = []; if (action.blocker) values.push(action.blocker); if (gap.requirement === 'FUTURE_LABEL' && [1, 3].includes(gap.horizonHours) && incident.id === '2025-AZGCP-000597') values.push('NO_VALID_OBSERVATION_OPPORTUNITY', action.provider === 'nasa-feds' ? 'KNOWLEDGE_TIME_PUBLICATION_RECEIPT_MISSING' : 'ARCHIVE_EXHAUSTED_NO_HORIZON_COMPATIBLE_REVISION'); return uniqueSorted(values); }
function candidateRows(catalog, incident) {
  const impact = new Map(analyzeGapImpact(catalog.gaps, catalog.gold.rejections).map((item) => [item.gapId, item])), gaps = new Map(catalog.gaps.map((item) => [item.id, item]));
  const rows = catalog.plan.actions.filter((item) => item.incidentId === incident.id).map((action) => { const gap = gaps.get(action.gapId), measured = impact.get(action.gapId), blockers = blockerFor(action, gap, incident); return { id: action.id, incidentId: incident.id, provider: action.provider, requirement: action.requirement, gapId: action.gapId, requirementsClosed: [action.requirement, `${action.requirement}_${gap.horizonHours}H`], decisionsAffected: [`MATERIALIZE_FORECAST_EVALUATION_PACKAGE_${gap.horizonHours}H`], contractsPotentiallySatisfied: [`FORECAST_INPUT_${gap.horizonHours}H`], hypothesesSeparated: [], forecastExamplesUnlocked: measured?.candidateExamplesUnlocked ?? 0, horizonsUnlocked: [gap.horizonHours], negativeGateContribution: 0, independentFamilyGained: false, incidentUrgency: gap.horizonHours <= 3 ? 7 : 4, sourceAvailability: action.factors.providerAvailable ? 'AVAILABLE' : 'BLOCKED', sourceHealth: action.factors.providerAvailable ? 'HEALTHY' : 'DEGRADED', coverage: Boolean(action.factors.coverage), rights: action.factors.rightsReady ? 'READY' : 'BLOCKED', qualityExpectation: 'ADEQUATE', existingPartialData: Boolean(action.factors.existingPartialData), retryAttempts: action.factors.retryReady ? 0 : 3, maximumRetryAttempts: 3, expectedBytes: action.factors.expectedBytes, expectedLatencyMs: action.factors.expectedLatencyMs, estimatedCostUnits: 0, causalDuplicationRisk: action.provider === 'nasa-feds' ? 'HIGH' : 'LOW', blockingConditions: blockers, fallback: action.provider === 'nasa-feds' ? 'Use a source with historical publication receipts.' : 'Use another authoritative progression source.' }; });
  if (!new Set(incident.causalFamilies ?? []).has('GOES_ABI')) rows.push({ id: `candidate:${incident.id}:goes-abi-independent`, incidentId: incident.id, provider: 'noaa-goes-abi', requirement: 'INDEPENDENT_PHYSICAL_FAMILY', requirementsClosed: ['INDEPENDENT_PHYSICAL_CORROBORATION'], decisionsAffected: ['OPEN_INDEPENDENT_PHYSICAL_EVIDENCE_WORK', 'PROPOSE_OFFICIAL_WARNING'], criticalDecisionsPotentiallyUnblocked: 0, contractsPotentiallySatisfied: ['INDEPENDENT_PHYSICAL_FAMILY'], hypothesesSeparated: ['WILDFIRE:ACTIVE_WILDFIRE', 'WILDFIRE:SENSOR_OR_ALGORITHM_ARTEFACT'], forecastExamplesUnlocked: 0, horizonsUnlocked: [], independentFamilyGained: true, incidentUrgency: 8, sourceAvailability: 'AVAILABLE', sourceHealth: 'HEALTHY', coverage: incident.region === 'western-us', rights: 'READY', qualityExpectation: 'HIGH', expectedBytes: 12 * 1024 * 1024, expectedLatencyMs: 20_000, estimatedCostUnits: 0, causalDuplicationRisk: 'LOW', blockingConditions: ['NO_VALID_OBSERVATION_OPPORTUNITY'], fallback: 'Use another independently rooted physical source with a provable observation opportunity.' });
  return rows;
}

export async function loadDecisionCompilerInput({ projectRoot = process.cwd(), incidentId = '2025-AZGCP-000597', knowledgeTime = null } = {}) {
  const corpus = corpusPaths(projectRoot), foundry = dataFoundryPaths(projectRoot), catalog = await buildDataFoundryCatalog({ projectRoot }), gold = catalog.gold, incident = gold.incidents.find((item) => item.id === incidentId); if (!incident) throw new Error('decision_foundry_incident_not_found');
  const examples = gold.examples.filter((item) => item.incidentId === incidentId), cutoff = knowledgeTime ?? [...(incident.perimeterStates ?? []).map((item) => item.clocks?.availableToVigiaAt), ...examples.map((item) => item.informationCutoff)].filter(Boolean).sort().at(-1) ?? incident.discoveryTime, graph = await readJson(foundry.lineage, { nodes: [], edges: [], verification: {} }), registry = catalog.registry, incidentVersions = new Set(registry.incidentProducts[incident.id]?.dataProductVersionIds ?? []), facts = ['INCIDENT_EXISTS']; if (incident.perimeterStates?.length) facts.push('PERIMETER_AVAILABLE'); if (new Set(incident.causalFamilies ?? []).size >= 2) facts.push('INDEPENDENT_PHYSICAL_CORROBORATION');
  const currentPolicies = [{ id: 'MISSING_INDEPENDENT_CORROBORATION', version: '1.0.0' }, { id: 'CONSEQUENTIAL_WARNING_GUARD', version: '1.0.0' }].map((policy) => ({ ...policy, fingerprint: semanticHash('decision-policy', policy) }));
  return { compilerVersion: '1.0.0', incident: { id: incident.id, region: incident.region, season: incident.season, discoveryTime: incident.discoveryTime, perimeterSourceClass: incident.perimeterSourceClass }, knowledgeTime: cutoff, currentSituation: { state: 'HISTORICAL_OPERATIONAL_SNAPSHOT', sourceClassification: incident.perimeterSourceClass, perimeterRevisionCount: incident.perimeterStates?.length ?? 0, physicalObservationCount: incident.physicalObservations?.length ?? 0, causalFamilies: uniqueSorted(incident.causalFamilies) }, evidenceFacts: evidenceFacts(incident, cutoff), facts, dataProducts: productKinds(incident, examples), authorityContext: { PROPOSE_OFFICIAL_WARNING: false }, trustContext: {}, decisionRights: {}, decisionSourceHealth: {}, policyContext: {}, openDataGaps: catalog.gaps.filter((item) => item.incidentId === incident.id), forecastReadiness: gold.readiness, candidateAcquisitions: candidateRows(catalog, incident), existingTaskCandidateIds: [], completedCandidateIds: [], maximumSelections: 1, evidenceNeedIds: new Set(incident.causalFamilies ?? []).size < 2 ? [`evidence-need:${incident.id}:independent-physical-family`] : [], currentPolicies, lineage: { graphFingerprint: graph.verification?.fingerprint, productVersionIds: [...incidentVersions].sort(), valid: graph.verification?.passed === true }, rights: gold.rights, quality: { leakagePassed: gold.leakage?.passed === true, corpusDecision: gold.readiness?.decision }, proofReferences: [], causingDataProductIds: [...incidentVersions].sort(), governedWork: [], sourceContributions: [{ sourceId: 'nasa-firms-viirs', sourceFamily: 'VIIRS', contributions: (incident.physicalObservations ?? []).map((item) => ({ rootMeasurementId: item.rootMeasurementId ?? item.id, sourceFamily: 'VIIRS' })), ablation: { decisionsLost: ['PHYSICAL_SUPPORT'], hypothesesChanged: ['WILDFIRE:ACTIVE_WILDFIRE'], examplesLost: 0, independentFamilyLost: true } }, { sourceId: 'nasa-feds', sourceFamily: 'VIIRS', contributions: [{ rootMeasurementId: 'VIIRS_DERIVED_FAMILY', sourceFamily: 'VIIRS', independent: false, republished: true }], ablation: { decisionsLost: [], hypothesesChanged: [], examplesLost: 0, independentFamilyLost: false } }, { sourceId: 'nifc-wfigs', sourceFamily: 'OFFICIAL', contributions: [{ rootMeasurementId: `WFIGS:${incident.id}`, sourceFamily: 'OFFICIAL' }], ablation: { decisionsLost: ['RUN_INTERNAL_ASSET_IMPACT_ASSESSMENT'], hypothesesChanged: ['WILDFIRE:ACTIVE_WILDFIRE'], examplesLost: examples.length, independentFamilyLost: true } }] };
}

export async function compileAndPersistDecisionPacket({ projectRoot = process.cwd(), incidentId, knowledgeTime } = {}) {
  const input = await loadDecisionCompilerInput({ projectRoot, incidentId, knowledgeTime }), packet = compileCrisisDecisionState(input), signed = await signDecisionPacket(packet, { projectRoot }), paths = decisionFoundryPaths(projectRoot), proofReferences = [signed.proof.fingerprint], signedPacket = { ...packet, proofReferences, proof: signed.proof, proofVerification: signed.verification, integrityState: signed.verification.status === 'VALID' ? 'SIGNED_AND_VERIFIED' : 'PROOF_INVALID', signedFingerprint: semanticHash('signed-crisis-decision-packet', { packetFingerprint: packet.replayFingerprint, proofFingerprint: signed.proof.fingerprint }) }, replay = createDecisionReplayRecord({ compilerInput: input, packet, compilerVersion: input.compilerVersion, proofFingerprint: signed.proof.fingerprint });
  await Promise.all([writeJsonAtomic(path.join(paths.packets, `${incidentId}.json`), signedPacket), writeJsonAtomic(path.join(paths.replays, `${incidentId}.json`), replay)]);
  const repository = new FileIntelligenceRepository({ filePath: path.join(paths.runtime, 'semantic-repository.json') }); await repository.initialize(); await repository.persistDecisionPacket(signedPacket, { rights: signedPacket.rights });
  const projection = await materializeDecisionObjectSetProjection({ projectRoot, affectedIncidentIds: [incidentId], reason: 'DECISION_PACKET_COMPILED' }); invalidateDecisionObjectSetCache(projectRoot);
  return { input, packet: signedPacket, replay, projection };
}

export async function replayDecisionPacket({ projectRoot = process.cwd(), incidentId = '2025-AZGCP-000597' } = {}) {
  const paths = decisionFoundryPaths(projectRoot), record = await readJson(path.join(paths.replays, `${incidentId}.json`), null); if (!record) throw new Error('decision_replay_not_found'); const rebuilt = compileCrisisDecisionState(record.compilerInput), packet = await readJson(path.join(paths.packets, `${incidentId}.json`), null), verification = verifyDecisionReplay(record, rebuilt, { proofFingerprint: packet?.proof?.fingerprint }); return { rebuilt, record, verification };
}
