import { randomUUID } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import { assertCan,assertIncidentScope,incidentInScope } from '../../../../../packages/domain/src/authorization.mjs';
import { hashValue } from '../../../../../packages/domain/src/intelligence/contract.mjs';
import { projectIncidentIntelligence } from '../../../../../packages/domain/src/intelligence/kernel.mjs';
import { hindsightSafeInputs } from '../../../../../packages/domain/src/intelligence/replay.mjs';
import { createOperatorDecision } from '../../../../../packages/domain/src/intelligence/operator-decision.mjs';
import { IncidentProjectionQueue } from '../../../../../packages/domain/src/intelligence/queue.mjs';
import { RequestGate,SingleFlight } from '../../shared/request-gate.mjs';

const activeNeed=(item)=>!['RESOLVED','CLOSED','CANCELLED','SUPERSEDED'].includes(String(item.state??item.status??'').toUpperCase());
const incidentBinding=(item,id)=>String(item.subjectId??item.incidentId??item.targetId??'').replace(/^(event|incident):/,'')===String(id).replace(/^(event|incident):/,'');
const failureClass=(error)=>error?.dependency==='postgis'||String(error?.code??error?.message??error).toLowerCase().includes('postgis')?'POSTGIS_FAILURE':String(error?.message??error).includes('not_found')?'INPUT_NOT_FOUND':'COMPUTATION_FAILURE';
const TIER={P1:0,P2:1,P3:2,P4:3};
const INBOX_PROJECTION_CONCURRENCY=8;
const INBOX_COMPUTATION_CONCURRENCY=4;
const INBOX_CACHE_TTL_MS=10_000;
const DETAIL_CACHE_TTL_MS=60_000;
function percentile(rows,p){if(!rows.length)return null;const sorted=[...rows].sort((a,b)=>a-b),index=Math.min(sorted.length-1,Math.floor(sorted.length*p));return Number(sorted[index].toFixed(3));}
function fieldNetContext(raw,incidentId){if(!raw)return null;const collections=['mutations','observations','tasks','acknowledgements','conflicts'],rows=collections.flatMap((name)=>(raw[name]??[]).map((item)=>({name,id:String(item.id??item.mutationId??item.observationId??item.taskId??item.acknowledgementId??item.conflictId??''),state:String(item.state??item.type??''),at:item.centralReceivedAt??item.receivedAt??item.updatedAt??item.createdAt??item.observedAt??null}))),times=rows.map((item)=>item.at).filter((value)=>Number.isFinite(Date.parse(value))).sort(),counts=Object.fromEntries(collections.map((name)=>[name,Number(raw.collectionTotals?.[name]??raw[name]?.length??0)])),lastReconciledAt=times.at(-1)??raw.retention?.archiveCheckpoint?.updatedAt??raw.updatedAt??null;return{schemaVersion:'vigia.intelligence-fieldnet-context.v1',incidentId:String(incidentId),state:'AVAILABLE',lastReconciledAt,counts,openConflicts:(raw.conflicts??[]).filter((item)=>!['RESOLVED','CLOSED'].includes(String(item.state).toUpperCase())).length,inputHash:hashValue({incidentId,counts,lastReconciledAt,rows:rows.map(({name,id,state})=>[name,id,state])})};}
async function boundedMap(values,worker,limit=INBOX_PROJECTION_CONCURRENCY){const results=new Array(values.length);let cursor=0;const run=async()=>{while(cursor<values.length){const index=cursor;cursor+=1;results[index]=await worker(values[index],index);}};await Promise.all(Array.from({length:Math.min(limit,values.length)},run));return results;}
class BoundedWorkQueue{
  #active=0;#pending=[];#rejected=0;#maximumActive=0;
  constructor({maxConcurrent=INBOX_PROJECTION_CONCURRENCY,maxQueued=64}={}){this.maxConcurrent=Math.max(1,Number(maxConcurrent)||INBOX_PROJECTION_CONCURRENCY);this.maxQueued=Math.max(0,Number(maxQueued)||64);}
  run(work){if(this.#active<this.maxConcurrent)return this.#start(work);if(this.#pending.length>=this.maxQueued){this.#rejected+=1;throw Object.assign(new Error('intelligence_projection_capacity_exhausted'),{statusCode:503});}return new Promise((resolve,reject)=>this.#pending.push({work,resolve,reject}));}
  #start(work,deferred=null){this.#active+=1;this.#maximumActive=Math.max(this.#maximumActive,this.#active);const settled=Promise.resolve().then(work).finally(()=>{this.#active-=1;const next=this.#pending.shift();if(next)this.#start(next.work,next);});if(deferred)void settled.then(deferred.resolve,deferred.reject);return settled;}
  status(){return{active:this.#active,queued:this.#pending.length,rejected:this.#rejected,maxConcurrent:this.maxConcurrent,maxQueued:this.maxQueued,maximumActive:this.#maximumActive};}
}

export class IntelligenceService{
  constructor({snapshotRepository,operationalEventService,evidenceNeedService,stateRepository,replayService,preventionFindingService,centralFieldNetService,clock=()=>new Date(),mutationRetryMs=1_000,inboxGate=new RequestGate({maxConcurrent:INBOX_COMPUTATION_CONCURRENCY,maxConcurrentPerClient:1,maxRequestsPerWindow:120}),decisionGate=new RequestGate({maxConcurrent:4,maxConcurrentPerClient:1,maxRequestsPerWindow:60}),projectionWorkQueue=new BoundedWorkQueue()}={}){Object.assign(this,{snapshotRepository,operationalEventService,evidenceNeedService,stateRepository,replayService,preventionFindingService,centralFieldNetService,clock,inboxGate,decisionGate,projectionWorkQueue});this.mutationRetryMs=Math.max(10,Math.min(30_000,Number(mutationRetryMs)||1_000));this.lastGood=new Map();this.inboxDetailCache=new Map();this.inboxCache=new Map();this.inboxSingleFlight=new SingleFlight({maxKeys:64});this.inboxGeneration=0;this.inputGenerations=new Map();this.activeInputMutations=new Map();this.inputMutationTokens=new Map();this.durableInputMutationTokens=new Map();this.mutationRecoveryTimers=new Map();this.mutationFences=new Map();this.dirtyIncidents=new Set();this.timings={projection:[],cachedRead:[],inbox:[]};this.queue=new IncidentProjectionQueue({worker:async(incidentId)=>{try{const result=await this.#project(incidentId,{persist:true}),authority=await this.#authority(incidentId);if(result?.projectionState!=='STALE'&&!authority.dirty&&!authority.activeMutations)this.dirtyIncidents.delete(String(incidentId));}catch{}finally{this.inboxDetailCache.delete(String(incidentId));this.inboxCache.clear();}}});}
  async initialize(){return this.snapshotRepository?.initialize?.()??{state:'not_configured'};}
  status(){const repository=this.snapshotRepository?.status?.()??{state:'not_configured'};return{schemaVersion:'vigia.intelligence-runtime-status.v1',state:repository.state==='ready'?'READY':'DEGRADED',repository,queue:this.queue.status(),projectionAdmission:this.projectionWorkQueue.status(),mutationRecovery:{durableLeases:this.durableInputMutationTokens.size,scheduled:this.mutationRecoveryTimers.size,retryMs:this.mutationRetryMs},cache:{inboxes:this.inboxCache.size,details:this.inboxDetailCache.size,maxInboxes:64,maxDetails:256,ttlMs:INBOX_CACHE_TTL_MS,detailTtlMs:DETAIL_CACHE_TTL_MS},noIdleInference:true,modelCalls:0,autonomousAgents:0,timings:{projectionP95Ms:percentile(this.timings.projection,.95),cachedReadP95Ms:percentile(this.timings.cachedRead,.95),inboxP95Ms:percentile(this.timings.inbox,.95),samples:{projection:this.timings.projection.length,cachedRead:this.timings.cachedRead.length,inbox:this.timings.inbox.length}}};}
  inputGeneration(incidentId){return this.inputGenerations.get(String(incidentId))??0;}
  isDirty(incidentId){return this.dirtyIncidents.has(String(incidentId));}
  markDirty(incidentId){const id=String(incidentId??'');if(!id)return 0;const generation=this.inputGeneration(id)+1;this.inputGenerations.set(id,generation);this.dirtyIncidents.add(id);this.inboxGeneration+=1;this.inboxDetailCache.delete(id);this.inboxCache.clear();return generation;}
  #applyAuthority(incidentId,authority){const id=String(incidentId),generation=Number(authority?.generation??0),activeMutations=Number(authority?.activeMutations??0),dirty=Boolean(authority?.dirty),changed=this.inputGeneration(id)!==generation||(this.activeInputMutations.get(id)??0)!==activeMutations||this.isDirty(id)!==(dirty||Boolean(activeMutations));this.inputGenerations.set(id,generation);this.activeInputMutations.set(id,activeMutations);if(dirty||activeMutations)this.dirtyIncidents.add(id);else this.dirtyIncidents.delete(id);if(changed){this.inboxGeneration+=1;this.inboxDetailCache.delete(id);this.inboxCache.clear();}return{generation,dirty,activeMutations};}
  async #authority(incidentId){const id=String(incidentId),localActive=this.activeInputMutations.get(id)??0;if(this.mutationFences.has(id)||localActive>0)return{generation:this.inputGeneration(id),dirty:true,activeMutations:Math.max(1,localActive)};if(this.snapshotRepository?.status?.().state==='ready'&&typeof this.snapshotRepository.inputGeneration==='function')return this.#applyAuthority(id,await this.snapshotRepository.inputGeneration(id));return{generation:this.inputGeneration(id),dirty:this.isDirty(id),activeMutations:localActive};}
  #mutationFence(incidentId,work){const id=String(incidentId),prior=this.mutationFences.get(id)??Promise.resolve(),next=prior.catch(()=>undefined).then(work);this.mutationFences.set(id,next);void next.finally(()=>{if(this.mutationFences.get(id)===next)this.mutationFences.delete(id);}).catch(()=>undefined);return next;}
  #releaseMutationToken(incidentId,token){const id=String(incidentId),tokens=this.inputMutationTokens.get(id);tokens?.delete(token);if(!tokens?.size)this.inputMutationTokens.delete(id);this.durableInputMutationTokens.delete(token);const timer=this.mutationRecoveryTimers.get(token);if(timer)clearTimeout(timer);this.mutationRecoveryTimers.delete(token);}
  #queueMutationRecomputation(incidentId,authority,state='QUEUED'){try{this.queue.enqueue(incidentId,authority.generation);return{...authority,recomputation:{state}};}catch{return{...authority,recomputation:{state:'DEFERRED_UNTIL_NEXT_READ'}};}}
  #retryableMutationError(error){return error?.statusCode===503||error?.retryable===true||error?.details?.retryable===true||error?.dependency==='postgis'||String(error?.code??'').startsWith('08')||String(error?.message??'').includes('postgis');}
  #scheduleMutationRecovery(token){if(this.mutationRecoveryTimers.has(token)||!this.durableInputMutationTokens.has(token))return;const timer=setTimeout(()=>{this.mutationRecoveryTimers.delete(token);const lease=this.durableInputMutationTokens.get(token);if(!lease)return;void this.finishInputMutation(lease.incidentId,{committed:lease.committed,mutationToken:token}).catch(()=>{if(this.durableInputMutationTokens.has(token))this.#scheduleMutationRecovery(token);});},this.mutationRetryMs);timer.unref?.();this.mutationRecoveryTimers.set(token,timer);}
  beginInputMutation(incidentId){const id=String(incidentId),mutationToken=randomUUID(),generation=this.markDirty(id),tokens=this.inputMutationTokens.get(id)??new Set();tokens.add(mutationToken);this.inputMutationTokens.set(id,tokens);this.activeInputMutations.set(id,tokens.size);return this.#mutationFence(id,async()=>{try{if(this.snapshotRepository?.status?.().state==='ready'&&typeof this.snapshotRepository.beginInputMutation==='function'){const durable=await this.snapshotRepository.beginInputMutation(id,{mutationToken});this.durableInputMutationTokens.set(mutationToken,{incidentId:id,expiresAt:durable.expiresAt??new Date(this.clock().getTime()+2*60_000).toISOString(),committed:true});return{...this.#applyAuthority(id,durable),mutationToken,expiresAt:durable.expiresAt};}return{generation,dirty:true,activeMutations:tokens.size,mutationToken};}catch(error){this.#releaseMutationToken(id,mutationToken);this.activeInputMutations.set(id,tokens.size);throw error;}});}
  finishInputMutation(incidentId,{committed=true,mutationToken=null}={}){const id=String(incidentId),token=String(mutationToken??''),tokens=this.inputMutationTokens.get(id);if(!token||!tokens?.has(token))throw Object.assign(new Error('intelligence_mutation_token_invalid'),{statusCode:409,details:{incidentId:id}});return this.#mutationFence(id,async()=>{if(!tokens.has(token))throw Object.assign(new Error('intelligence_mutation_token_invalid'),{statusCode:409,details:{incidentId:id}});const durableLease=this.durableInputMutationTokens.get(token);let authority;if(durableLease){durableLease.committed=committed;try{if(this.snapshotRepository?.status?.().state!=='ready')await this.snapshotRepository?.initialize?.();if(this.snapshotRepository?.status?.().state!=='ready')throw Object.assign(new Error('intelligence_postgis_unavailable'),{statusCode:503,retryable:true,dependency:'postgis'});authority=this.#applyAuthority(id,await this.snapshotRepository.finishInputMutation(id,{committed,mutationToken:token}));}catch(error){const expired=Date.parse(durableLease.expiresAt)<=this.clock().getTime();if(expired&&error?.statusCode===409){try{if(this.snapshotRepository?.status?.().state!=='ready')await this.snapshotRepository?.initialize?.();if(this.snapshotRepository?.status?.().state!=='ready')throw Object.assign(new Error('intelligence_postgis_unavailable'),{statusCode:503,retryable:true,dependency:'postgis'});authority=this.#applyAuthority(id,await this.snapshotRepository.inputGeneration(id));this.#releaseMutationToken(id,token);this.activeInputMutations.set(id,authority.activeMutations);return this.#queueMutationRecomputation(id,authority,'EXPIRED_LEASE_RECOVERED');}catch(recoveryError){if(!this.#retryableMutationError(recoveryError))throw recoveryError;}}
        if(!this.#retryableMutationError(error)&&!expired)throw error;this.#scheduleMutationRecovery(token);return{generation:this.inputGeneration(id),dirty:true,activeMutations:Math.max(1,this.activeInputMutations.get(id)??tokens.size),recomputation:{state:'DURABLE_COMPLETION_RETRY_QUEUED'}};}}
      else{tokens.delete(token);authority={generation:this.inputGeneration(id),dirty:true,activeMutations:tokens.size};this.activeInputMutations.set(id,tokens.size);}this.#releaseMutationToken(id,token);this.activeInputMutations.set(id,authority.activeMutations);return this.#queueMutationRecomputation(id,authority);});}
  abortInputMutation(incidentId,mutationToken){return this.finishInputMutation(incidentId,{committed:false,mutationToken});}
  invalidateInput(incidentId){const id=String(incidentId);return this.#mutationFence(id,async()=>{let authority;if(this.snapshotRepository?.status?.().state==='ready'&&typeof this.snapshotRepository.invalidateInput==='function')authority=this.#applyAuthority(id,await this.snapshotRepository.invalidateInput(id));else authority={generation:this.markDirty(id),dirty:true,activeMutations:this.activeInputMutations.get(id)??0};try{this.queue.enqueue(id,authority.generation);return{...authority,recomputation:{state:'QUEUED'}};}catch{return{...authority,recomputation:{state:'DEFERRED_UNTIL_NEXT_READ'}};}});}
  recompute(incidentId){const id=String(incidentId??'');return this.queue.enqueue(id,this.inputGeneration(id));}
  schedule(incidentId){const id=String(incidentId??'');const generation=this.markDirty(id);return this.queue.enqueue(id,generation);}
  #requests(incidentId){const state=this.stateRepository?.snapshotFields?.(['evidenceRequests'])??this.stateRepository?.snapshot?.()??{};return(state.evidenceRequests??[]).filter((item)=>incidentBinding(item,incidentId));}
  async #inputs(incidentId,{asOf=null,mode='LIVE',authoritativeInputGeneration=0}={}){const repositoryReady=this.snapshotRepository?.status?.().state==='ready',[cached,command,decisions]=await Promise.all([this.operationalEventService.operatorEvent(incidentId),this.operationalEventService.commandSnapshot(),repositoryReady?this.snapshotRepository.decisions(incidentId):Promise.resolve([])]),event=cached?.event??command.events?.find((item)=>String(item.id)===String(incidentId))??null;if(!event)throw Object.assign(new Error('intelligence_incident_not_found'),{statusCode:404});const needs=this.evidenceNeedService.snapshot().filter((item)=>incidentBinding(item,incidentId)),requests=this.#requests(incidentId),fieldNet=fieldNetContext(this.centralFieldNetService?.snapshot?.(incidentId)??null,incidentId),opportunities=event.observationPlan?.opportunitiesV2??event.observationPlan?.options??[],generatedAt=asOf??this.clock().toISOString(),base={incident:event,evidenceNeeds:needs,evidenceRequests:requests,opportunities,opportunityResults:event.observationPlan?.opportunityResults??[],sourceState:command.sources??{},operatorDecisions:decisions,fieldNetState:fieldNet,corrections:event.corrections??event.associationCorrections??[],authoritativeInputGeneration,mode,generatedAt,...(asOf?{asOf}: {})};return asOf?hindsightSafeInputs(base,asOf):base;}
  #remember(value){this.lastGood.set(value.incidentId,value);return value;}
  #recordDuration(kind,duration){const rows=this.timings[kind];rows.push(duration);if(rows.length>100)rows.shift();}
  #recordTiming(kind,started){this.#recordDuration(kind,performance.now()-started);}
  async #latest(incidentId){if(this.snapshotRepository?.status?.().state==='ready')return this.snapshotRepository.latest(incidentId);return this.lastGood.get(incidentId)??null;}
  #stale(last,error,started){return{...last,projectionState:'STALE',lastGoodAt:last.generatedAt,computation:{state:'FAILED_RETAINED_LAST_GOOD',failureClass:failureClass(error),durationMs:Number((performance.now()-started).toFixed(3))}};}
  async #project(incidentId,options={}){return this.projectionWorkQueue.run(()=>this.#projectAdmitted(incidentId,options));}
  async #projectAdmitted(incidentId,{asOf=null,mode='LIVE',persist=true}={}){
    const started=performance.now();let previous;try{previous=await this.#latest(incidentId);}catch(error){const last=this.lastGood.get(incidentId);if(!last)throw error;return this.#stale(last,error,started);}
    const repositoryState=this.snapshotRepository?.status?.().state??'not_configured',known=this.lastGood.get(incidentId)??previous,authority=await this.#authority(incidentId);if(authority.activeMutations){const error=Object.assign(new Error('intelligence_authoritative_mutation_active'),{statusCode:409});if(!known)throw error;return this.#stale(known,error,started);}if(persist&&repositoryState!=='ready'&&repositoryState!=='not_configured'&&known)return this.#stale(known,Object.assign(new Error('intelligence_postgis_unavailable'),{dependency:'postgis'}),started);
    let candidate,kernelDuration=0;try{const inputs=await this.#inputs(incidentId,{asOf,mode,authoritativeInputGeneration:authority.generation}),kernelStarted=performance.now();candidate=projectIncidentIntelligence({...inputs,previousSnapshot:previous});kernelDuration=performance.now()-kernelStarted;}catch(error){const last=this.lastGood.get(incidentId)??previous;if(!last)throw error;return this.#stale(last,error,started);}
    if(previous?.inputHash===candidate.inputHash){this.#recordTiming('cachedRead',started);return this.#remember({...previous,computation:{state:'CACHED',durationMs:Number((performance.now()-started).toFixed(3))}});}if(!persist||repositoryState!=='ready'){this.#recordDuration('projection',kernelDuration);return this.#remember({...candidate,computation:{state:persist?'CURRENT_NOT_PERSISTED':'RECONSTRUCTED',durationMs:Number((performance.now()-started).toFixed(3))}});}
    try{const saved=await this.snapshotRepository.save(candidate),result=saved.snapshot;await this.#authority(incidentId);this.#recordDuration(saved.duplicate?'cachedRead':'projection',saved.duplicate?performance.now()-started:kernelDuration);return this.#remember({...result,computation:{state:saved.duplicate?'CACHED':'CURRENT_PERSISTED',durationMs:Number((performance.now()-started).toFixed(3))}});}catch(error){const last=this.lastGood.get(incidentId)??previous;if(!last)throw error;return this.#stale(last,error,started);}
  }
  async #inboxProjections(visible){
    const project=async(item)=>{try{return await this.#project(item.id);}catch(error){if([429,503].includes(error?.statusCode))throw error;return null;}};
    if(this.snapshotRepository?.status?.().state!=='ready'||typeof this.snapshotRepository.latestMany!=='function')return boundedMap(visible,project);
    const started=performance.now();let persisted;
    try{persisted=await this.snapshotRepository.latestMany(visible.map((item)=>item.id));}catch{return boundedMap(visible,project);}
    const duration=performance.now()-started,amortized=Number((duration/Math.max(1,persisted.length)).toFixed(3)),queue=this.queue.status(),pending=new Set([...this.dirtyIncidents,queue.activeIncident,...queue.incidents].filter(Boolean).map(String)),byIncident=new Map(persisted.map((item)=>[String(item.incidentId),item]));
    this.#recordDuration('cachedRead',duration);
    return boundedMap(visible,async(item)=>{const existing=byIncident.get(String(item.id));if(!existing)return project(item);if(pending.has(String(item.id)))return this.#remember({...existing,projectionState:'STALE',lastGoodAt:existing.generatedAt,computation:{state:'PENDING_RECOMPUTATION_LAST_GOOD',durationMs:amortized,batchReadDurationMs:Number(duration.toFixed(3)),batchSize:persisted.length}});return this.#remember({...existing,computation:{state:'CACHED',durationMs:amortized,batchReadDurationMs:Number(duration.toFixed(3)),batchSize:persisted.length}});});
  }
  async incident(actor,incidentId,options={}){assertCan(actor,'read:evidence');assertIncidentScope(actor,incidentId);const started=performance.now(),key=String(incidentId),cached=this.inboxDetailCache.get(key);if(!options.asOf&&options.persist!==false&&cached&&cached.expiresAt>Date.now()&&!this.isDirty(key)){this.#recordTiming('cachedRead',started);return this.#remember({...cached.snapshot,computation:{state:'CACHED',durationMs:Number((performance.now()-started).toFixed(3))}});}if(cached)this.inboxDetailCache.delete(key);const result=await this.#project(incidentId,options);return this.isDirty(key)?{...result,projectionState:'STALE',lastGoodAt:result.generatedAt??null,computation:{state:'PENDING_RECOMPUTATION_LAST_GOOD',durationMs:result.computation?.durationMs??Number((performance.now()-started).toFixed(3))}}:result;}
  async inbox(actor,{limit=5}={}){assertCan(actor,'read:evidence');const started=performance.now(),now=Date.now();for(const[key,value]of this.inboxCache)if(value.expiresAt<=now)this.inboxCache.delete(key);for(const[key,value]of this.inboxDetailCache)if(value.expiresAt<=now)this.inboxDetailCache.delete(key);const boundedLimit=Math.max(1,Math.min(5,Number(limit)||5)),cacheKey=hashValue({principalId:actor.id??null,incidentScopes:[...(actor.incidentScopes??[])].map(String).sort(),limit:boundedLimit}),cached=this.inboxCache.get(cacheKey);if(cached&&cached.expiresAt>now){this.#recordTiming('inbox',started);return cached.response;}if(cached)this.inboxCache.delete(cacheKey);const generation=this.inboxGeneration,flightKey=`${generation}:${cacheKey}`;return this.inboxSingleFlight.run(flightKey,()=>this.inboxGate.run(actor.id??actor.agencyId??'operator',async()=>{const refreshed=this.inboxCache.get(cacheKey),admittedNow=Date.now();if(refreshed&&refreshed.expiresAt>admittedNow){this.#recordTiming('inbox',started);return refreshed.response;}const snapshot=await this.operationalEventService.commandSnapshot(),visible=(snapshot.events??[]).filter((item)=>incidentInScope(actor,item.id)).slice(0,40),results=await this.#inboxProjections(visible),ranked=results.filter(Boolean).sort((a,b)=>(TIER[a.attention.tier]??9)-(TIER[b.attention.tier]??9)||Date.parse(b.generatedAt)-Date.parse(a.generatedAt)||a.incidentId.localeCompare(b.incidentId)),top=ranked.slice(0,boundedLimit),expiresAt=Date.now()+INBOX_CACHE_TTL_MS,detailExpiresAt=Date.now()+DETAIL_CACHE_TTL_MS;this.#recordTiming('inbox',started);const response={schemaVersion:'vigia.intelligence-inbox.v1',generatedAt:this.clock().toISOString(),mode:snapshot.meta?.mode??'LIVE',items:top,totalRanked:ranked.length,primaryLimit:5,materialChanges:top.flatMap((item)=>item.decisionDelta.filter((delta)=>delta.type!=='RECOMPUTED_PROJECTION').map((delta)=>({...delta,incidentId:item.incidentId}))).slice(0,20),decisionBlockingUnknowns:top.flatMap((item)=>item.unknowns.filter((unknown)=>unknown.classification==='DECISION_BLOCKING').map((unknown)=>({...unknown,incidentId:item.incidentId}))).slice(0,20),sourceConditions:top.flatMap((item)=>item.sourceContext).filter((item,index,rows)=>rows.findIndex((row)=>row.sourceFamily===item.sourceFamily)===index),runtime:this.status()};if(generation===this.inboxGeneration){for(const item of ranked)this.inboxDetailCache.set(String(item.incidentId),{snapshot:item,expiresAt:detailExpiresAt});while(this.inboxDetailCache.size>256)this.inboxDetailCache.delete(this.inboxDetailCache.keys().next().value);this.inboxCache.set(cacheKey,{response,expiresAt});while(this.inboxCache.size>64)this.inboxCache.delete(this.inboxCache.keys().next().value);}return response;}));}
  async history(actor,incidentId,options={}){assertCan(actor,'read:evidence');assertIncidentScope(actor,incidentId);if(this.snapshotRepository?.status?.().state!=='ready'){const last=this.lastGood.get(incidentId);return{schemaVersion:'vigia.intelligence-history-page.v1',incidentId,snapshots:last?[last]:[],page:{cursor:null,nextCursor:null,hasMore:false,limit:1,returned:last?1:0},persistenceState:'UNAVAILABLE'};}return this.snapshotRepository.history(incidentId,options);}
  async decisionContexts(actor,incidentId,{asOf}={}){assertCan(actor,'read:evidence');assertIncidentScope(actor,incidentId);if(this.snapshotRepository?.status?.().state!=='ready'||typeof this.snapshotRepository.decisionContexts!=='function')throw Object.assign(new Error('intelligence_decision_history_unavailable'),{statusCode:503});return this.snapshotRepository.decisionContexts(incidentId,{asOf});}
  async decide(actor,incidentId,input){assertCan(actor,'review:incident');assertIncidentScope(actor,incidentId);return this.decisionGate.run(`${actor.id??actor.agencyId??'operator'}:${incidentId}`,async()=>{
    const admitted=await this.#authority(incidentId);if(admitted.dirty||admitted.activeMutations)throw this.#decisionStale(null);const current=await this.#project(incidentId),queue=this.queue.status(),pending=queue.activeIncident===String(incidentId)||queue.incidents.includes(String(incidentId)),currentAuthority=await this.#authority(incidentId);
    if(currentAuthority.dirty||currentAuthority.activeMutations||currentAuthority.generation!==admitted.generation||pending||current.projectionState==='STALE'||current.computation?.state==='FAILED_RETAINED_LAST_GOOD'||Number(current.authoritativeInputGeneration)!==currentAuthority.generation)throw this.#decisionStale(current);
    if(input.snapshotVersion!==current.snapshotVersion||input.evidenceGraphVersion!==current.evidenceGraphHash)throw Object.assign(new Error('intelligence_decision_snapshot_changed'),{statusCode:409,details:{refreshRequired:true}});
    const decision=createOperatorDecision({...input,incidentId,authoritativeInputGeneration:currentAuthority.generation},actor,this.clock().toISOString()),saved=await this.snapshotRepository.recordDecision(decision);
    if(saved.duplicate)return{...saved,recomputation:{state:'NOT_REQUIRED_DUPLICATE',durableDecision:true}};
    const authority=this.#applyAuthority(incidentId,{generation:saved.nextInputGeneration,dirty:true,activeMutations:0});try{const queued=this.queue.enqueue(String(incidentId),authority.generation);return{...saved,recomputation:{state:queued?.state??'QUEUED',durableDecision:true}};}catch(error){return{...saved,recomputation:{state:'DEFERRED_UNTIL_NEXT_READ',durableDecision:true,reason:String(error?.message??error).slice(0,120)}};}
  });}
  #decisionStale(current){return Object.assign(new Error('intelligence_decision_projection_stale'),{statusCode:409,details:{refreshRequired:true,lastGoodAt:current?.lastGoodAt??current?.generatedAt??null,failureClass:current?.computation?.failureClass??null,inputGenerationChanged:true}});}
  async replay(actor,caseId,{asOf}={}){assertCan(actor,'read:replay');const detail=await this.replayService.caseDetail(caseId),clock=asOf??detail.controlledClock?.endAt;if(!detail.controlledClock?.steps?.includes(clock))throw Object.assign(new Error('intelligence_replay_clock_invalid'),{statusCode:400});const incident={id:`replay:${caseId}`,label:detail.case?.name??caseId,mode:'HISTORICAL_REPLAY',observations:(detail.evidence??[]).map((item)=>({...item,type:item.kind,at:item.observedAt,receivedAt:item.visibleAt}))},inputs=hindsightSafeInputs({incident,evidenceNeeds:[],evidenceRequests:[],opportunities:[],opportunityResults:[],sourceState:{},operatorDecisions:[],fieldNetState:null},clock);return projectIncidentIntelligence({...inputs,generatedAt:clock,asOf:clock,previousSnapshot:null});}
  prevent(actor,findingId){assertCan(actor,'review:prevention');const finding=this.preventionFindingService.find(findingId,actor);if(!finding)throw Object.assign(new Error('prevention_finding_not_found'),{statusCode:404});const measured=Number(finding.reviewSummary?.count??0)>0||Boolean(finding.currentObservationId&&finding.comparisonObservationId),unknown=measured?null:{id:`prevent-unknown:${findingId}`,classification:'DECISION_BLOCKING',whatIsUnknown:'Governed prevention measurement',affectsClaim:'PREVENT screening state',strongerClaimBlocked:'Reviewed prevention finding',reason:'PREVENT findings cannot advance without attributable measurement or review.'};return{schemaVersion:'vigia.prevent-intelligence.v1',findingId,mode:'LIVE',screeningState:measured?'MEASUREMENT_RECORDED':'MEASUREMENT_REQUIRED',unknown,nextEvidence:measured?{state:'OPERATOR_REVIEW_REQUIRED'}:{state:finding.evidenceRequestId?'ACTIVE_EVIDENCE_REQUEST':'NO_ELIGIBLE_ASSET_CONFIGURED',evidenceNeedId:finding.evidenceNeedId??null,evidenceRequestId:finding.evidenceRequestId??null},treatmentRecommendation:null,intelligenceIsEvidence:false,generatedAt:this.clock().toISOString(),inputHash:hashValue({findingId,reviewVersion:finding.reviewVersion??null,measurement:measured})};}
}
