import { ellipsePolygon,normalizeBearing } from '../geo.mjs';
import { semanticHash } from '../intelligence/shared.mjs';
import { CONTOUR_PROBABILITIES,FORECAST_HORIZONS_HOURS } from './constants.mjs';
import { polygonAreaKm2,polygonCentroid,polygonFeature } from './geometry.mjs';

const probabilityScale=(probability)=>1.48-probability*.52;
const validAt=(issuedAt,hours)=>new Date(Date.parse(issuedAt)+hours*60*60_000).toISOString();
const contour=(probability,geometry)=>({probability,geometry:polygonFeature(geometry,{probability}),meaning:'Uncalibrated baseline progression threshold; not a probability claim until calibrated.'});
function ellipse(initialPerimeter,{hours,radialGrowthKmH,bearingDeg=0,alignment=0}){const area=polygonAreaKm2(initialPerimeter),radius=Math.max(.05,Math.sqrt(area/Math.PI)),growth=Math.max(0,Number(radialGrowthKmH))*hours,origin=polygonCentroid(initialPerimeter);return CONTOUR_PROBABILITIES.map((probability)=>{const scale=probabilityScale(probability),downwind=radius+growth*scale*(1+alignment),upwind=radius+growth*scale*(1-alignment*.55),crosswind=radius+growth*scale*(1-alignment*.25);return contour(probability,ellipsePolygon({origin,downwindKm:downwind,upwindKm:upwind,crosswindKm:crosswind,bearingDeg,points:72}));});}
function member({modelId,version='1.0.0',issuedAt,initialPerimeter,horizonsHours=FORECAST_HORIZONS_HOURS,build,inputs={}}){const horizons=horizonsHours.map((hours)=>{const contours=build(hours);return{hours,validAt:validAt(issuedAt,hours),contours,expectedPerimeter:contours.find((item)=>item.probability===.5).geometry};}),core={schemaVersion:'vigia.forecast-baseline-member.v1',modelId,version,forecastTask:'PERIMETER_PROGRESSION',issuedAt,deterministic:true,calibrated:false,inputs,horizons};return{...core,fingerprint:semanticHash('forecast-baseline-member',core)};}
export function noGrowthPersistence({issuedAt,initialPerimeter,horizonsHours}={}){const geometry=polygonFeature(initialPerimeter);return member({modelId:'NO_GROWTH_PERSISTENCE',issuedAt,initialPerimeter,horizonsHours,inputs:{doctrine:'Future perimeter equals the issue-time perimeter.'},build:()=>CONTOUR_PROBABILITIES.map((probability)=>contour(probability,geometry))});}
export function recentGrowthPersistence({issuedAt,initialPerimeter,horizonsHours,areaGrowthKm2PerHour=0}={}){const radiusRate=Math.sqrt(Math.max(0,Number(areaGrowthKm2PerHour))/Math.PI);return member({modelId:'RECENT_GROWTH_PERSISTENCE',issuedAt,initialPerimeter,horizonsHours,inputs:{areaGrowthKm2PerHour},build:(hours)=>ellipse(initialPerimeter,{hours,radialGrowthKmH:radiusRate})});}
export function windAlignedProgression({issuedAt,initialPerimeter,horizonsHours,boundaryVelocityKmH=.1,windDirectionDeg=0,windSpeedMs=0}={}){const alignment=Math.min(.6,Math.max(0,Number(windSpeedMs))/50),bearingDeg=normalizeBearing(Number(windDirectionDeg)+180);return member({modelId:'WIND_ALIGNED_PROGRESSION',issuedAt,initialPerimeter,horizonsHours,inputs:{boundaryVelocityKmH,windDirectionDeg,bearingDeg,windSpeedMs},build:(hours)=>ellipse(initialPerimeter,{hours,radialGrowthKmH:boundaryVelocityKmH,bearingDeg,alignment})});}
export function observationKinematicProgression({issuedAt,initialPerimeter,horizonsHours,boundaryVelocityKmH=.1,recentBearingDeg=0,sourceIds=[]}={}){return member({modelId:'OBSERVATION_KINEMATIC_PROGRESSION',issuedAt,initialPerimeter,horizonsHours,inputs:{boundaryVelocityKmH,recentBearingDeg,sourceIds:[...sourceIds].sort(),lineage:'Observed progression remains a model input and never becomes forecast evidence.'},build:(hours)=>ellipse(initialPerimeter,{hours,radialGrowthKmH:boundaryVelocityKmH,bearingDeg:normalizeBearing(recentBearingDeg),alignment:.35})});}
