import { haversineKm } from '../geo.mjs';

const finitePoint=(point)=>Array.isArray(point)&&point.length>=2&&point.slice(0,2).every(Number.isFinite);
export function polygonRing(value){const ring=value?.type==='Feature'?value.geometry?.coordinates?.[0]:value?.type==='Polygon'?value.coordinates?.[0]:value?.geometry?.type==='Polygon'?value.geometry.coordinates?.[0]:null;if(!Array.isArray(ring)||ring.length<4||!ring.every(finitePoint))throw new Error('forecast_polygon_invalid');const closed=ring[0][0]===ring.at(-1)[0]&&ring[0][1]===ring.at(-1)[1]?ring:ring.concat([ring[0]]);return closed.map((point)=>point.slice(0,2).map(Number));}
export function polygonFeature(value,properties={}){return{type:'Feature',properties:{...properties},geometry:{type:'Polygon',coordinates:[polygonRing(value)]}};}
export function polygonBbox(value){const ring=polygonRing(value),xs=ring.map((point)=>point[0]),ys=ring.map((point)=>point[1]);return[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)];}
export function polygonCentroid(value){const ring=polygonRing(value).slice(0,-1),sum=ring.reduce((out,point)=>[out[0]+point[0],out[1]+point[1]],[0,0]);return[sum[0]/ring.length,sum[1]/ring.length];}
export function polygonAreaKm2(value){const ring=polygonRing(value),lat=polygonCentroid(value)[1]*Math.PI/180,scaleX=111.320*Math.cos(lat),scaleY=110.574;let sum=0;for(let index=0;index<ring.length-1;index+=1){const a=ring[index],b=ring[index+1];sum+=(a[0]*scaleX)*(b[1]*scaleY)-(b[0]*scaleX)*(a[1]*scaleY);}return Math.abs(sum)/2;}
function orientation(a,b,c){return Math.sign((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]));}
function intersects(a,b,c,d){const o1=orientation(a,b,c),o2=orientation(a,b,d),o3=orientation(c,d,a),o4=orientation(c,d,b);return o1!==o2&&o3!==o4;}
export function polygonSelfIntersects(value){const ring=polygonRing(value);for(let i=0;i<ring.length-1;i+=1)for(let j=i+1;j<ring.length-1;j+=1){if(Math.abs(i-j)<=1||i===0&&j===ring.length-2)continue;if(intersects(ring[i],ring[i+1],ring[j],ring[j+1]))return true;}return false;}
function signedArea(ring){let sum=0;for(let i=0;i<ring.length-1;i+=1)sum+=ring[i][0]*ring[i+1][1]-ring[i+1][0]*ring[i][1];return sum/2;}
function lineIntersection(a,b,c,d){const x1=a[0],y1=a[1],x2=b[0],y2=b[1],x3=c[0],y3=c[1],x4=d[0],y4=d[1],den=(x1-x2)*(y3-y4)-(y1-y2)*(x3-x4);if(Math.abs(den)<1e-12)return b;return[((x1*y2-y1*x2)*(x3-x4)-(x1-x2)*(x3*y4-y3*x4))/den,((x1*y2-y1*x2)*(y3-y4)-(y1-y2)*(x3*y4-y3*x4))/den];}
export function convexIntersection(first,second){let output=polygonRing(first).slice(0,-1),clip=polygonRing(second),clockwise=signedArea(clip)<0;for(let i=0;i<clip.length-1;i+=1){const input=output;output=[];const a=clip[i],b=clip[i+1],inside=(point)=>clockwise?orientation(a,b,point)<=0:orientation(a,b,point)>=0;for(let j=0;j<input.length;j+=1){const current=input[j],previous=input[(j+input.length-1)%input.length],currentInside=inside(current),previousInside=inside(previous);if(currentInside){if(!previousInside)output.push(lineIntersection(previous,current,a,b));output.push(current);}else if(previousInside)output.push(lineIntersection(previous,current,a,b));}if(!output.length)break;}if(output.length<3)return null;return polygonFeature({type:'Polygon',coordinates:[[...output,output[0]]]});}
export function polygonIou(first,second){const intersection=convexIntersection(first,second),intersectionArea=intersection?polygonAreaKm2(intersection):0,union=polygonAreaKm2(first)+polygonAreaKm2(second)-intersectionArea;return union?intersectionArea/union:1;}
export function boundaryDistances(first,second){const left=polygonRing(first).slice(0,-1),right=polygonRing(second).slice(0,-1),nearest=(point,ring)=>Math.min(...ring.map((candidate)=>haversineKm(point,candidate))),a=left.map((point)=>nearest(point,right)),b=right.map((point)=>nearest(point,left)),all=[...a,...b].sort((x,y)=>x-y);return{meanKm:all.reduce((sum,value)=>sum+value,0)/all.length,hausdorffKm:all.at(-1),robustP95Km:all[Math.min(all.length-1,Math.floor(all.length*.95))]};}
export function validateProbabilityContours(contours){if(!Array.isArray(contours)||!contours.length)throw new Error('forecast_contours_required');const sorted=[...contours].sort((a,b)=>a.probability-b.probability);let priorArea=Infinity;for(const contour of sorted){if(!Number.isFinite(contour.probability)||contour.probability<=0||contour.probability>=1)throw new Error('forecast_probability_invalid');if(polygonSelfIntersects(contour.geometry))throw new Error('forecast_contour_self_intersection');const area=polygonAreaKm2(contour.geometry);if(area>priorArea+1e-6)throw new Error('forecast_contours_non_monotonic');priorArea=area;}return sorted;}
