import test from 'node:test';
import assert from 'node:assert/strict';
import {
  aggregateSpreadEvaluation,combineForecastMembers,createForecast,createForecastAssimilationState,createForecastInputManifest,createForecastModelEntry,
  createForecastPolicyInput,createForecastReceipt,createNegativeOpportunity,decideForecastAbstention,detectForecastLeakage,evaluateForecastPromotion,
  evaluateImpactForecast,evaluateProbabilityCalibration,forecastAssetExposure,noGrowthPersistence,polygonAreaKm2,
  recentGrowthPersistence,scoreIssuedForecast,summarizeForecastCorpus,validateProbabilityContours,verifyForecastReplay,windAlignedProgression
} from '../../src/forecasting/index.mjs';

const issuedAt='2026-08-24T12:00:00.000Z',square=(size=.01)=>({type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[-121,47],[-121+size,47],[-121+size,47+size],[-121,47+size],[-121,47]]]}}),input=(id,kind='PHYSICAL_OBSERVATION',knowledgeTime='2026-08-24T11:55:00.000Z')=>({id,kind,version:'1',sourceClass:'PHYSICAL',knowledgeTime,contentHash:`sha256:${id}`,processingMode:'NRT'});
function manifest(){return createForecastInputManifest({incidentId:'incident:1',forecastIssuedAt:issuedAt,informationCutoff:'2026-08-24T11:59:00Z',initialPerimeter:{...input('perimeter','INITIAL_PERIMETER'),sourceClass:'OFFICIAL'},inputs:[input('abi')],weatherMembers:[{model:'IFS',run:'20260824T00',member:'control',issueTime:'2026-08-24T06:00:00Z',steps:[12,18],contentHash:'sha256:weather'}],modelVersion:'1.0.0',policyVersion:'1.0.0'});}
function model(){return createForecastModelEntry({modelId:'NO_GROWTH_PERSISTENCE',version:'1.0.0',forecastTask:'PERIMETER_PROGRESSION',codeVersion:'test',features:['initial_perimeter'],promotionState:'RESEARCH',geographicApplicability:['CONUS'],forecastHorizonsHours:[1,3,6,12,24],knownFailureModes:['growth']});}
function forecastFrom(member,inputManifest=manifest()){return createForecast({incidentId:'incident:1',forecastType:'PERIMETER_PROGRESSION',state:'ISSUED',qualityState:'RESEARCH_ONLY',issuedAt,informationCutoff:inputManifest.informationCutoff,model:{id:member.modelId,version:member.version,fingerprint:model().fingerprint},inputManifestHash:inputManifest.semanticHash,initialPerimeterRef:'perimeter',horizons:member.horizons,limitations:['Uncalibrated research baseline.']});}

test('issue-time manifest rejects future weather, future observations, and final-perimeter features',()=>{
  assert.ok(manifest().semanticHash.startsWith('forecast-input-manifest:sha256:'));
  assert.throws(()=>createForecastInputManifest({incidentId:'1',forecastIssuedAt:issuedAt,informationCutoff:'2026-08-24T11:59:00Z',initialPerimeter:input('p','FINAL_PERIMETER'),modelVersion:'1',policyVersion:'1'}),/label_leakage/);
  assert.throws(()=>createForecastInputManifest({incidentId:'1',forecastIssuedAt:issuedAt,informationCutoff:'2026-08-24T11:59:00Z',initialPerimeter:input('p'),inputs:[input('late','PHYSICAL_OBSERVATION','2026-08-24T12:01:00Z')],modelVersion:'1',policyVersion:'1'}),/future_information/);
  assert.throws(()=>createForecastInputManifest({incidentId:'1',forecastIssuedAt:issuedAt,informationCutoff:'2026-08-24T11:59:00Z',initialPerimeter:input('p'),weatherMembers:[{model:'IFS',run:'later',member:'0',issueTime:'2026-08-24T12:01:00Z',contentHash:'x'}],modelVersion:'1',policyVersion:'1'}),/later_weather/);
});

test('negative controls require a real healthy observation opportunity and authoritative no-incident doctrine',()=>{
  const base={id:'negative:1',category:'INDUSTRIAL_HEAT',region:'CONUS',season:'2025',informationCutoff:issuedAt,providerId:'goes',providerStatus:'HISTORICALLY_VERIFIED',observationOpportunity:true,productExists:true,qualityState:'ADEQUATE',geometryCovered:true,timeCovered:true,noIncidentEvidence:{authoritative:true,knowledgeTime:'2026-08-24T11:00:00Z'},hardNegative:true},valid=createNegativeOpportunity(base),outage=createNegativeOpportunity({...base,id:'negative:2',category:'PROVIDER_OUTAGE',providerStatus:'UNAVAILABLE'}),summary=summarizeForecastCorpus({cases:[{id:'case:1',incidentId:'1',region:'CONUS',season:'2025',split:'train'}],negativeOpportunities:[valid,outage]});
  assert.equal(valid.classification,'VALID_NEGATIVE');assert.equal(outage.classification,'EXCLUDED_CONTROL');assert.equal(summary.negativeControls,1);assert.equal(summary.excludedControls,1);
});

test('forecast leakage detects incident/upstream split crossing and later information',()=>{
  const rows=[{id:'a',incidentId:'i',split:'train',informationCutoff:issuedAt,upstreamObservationIds:['pixel'],inputs:[input('p')]},{id:'b',incidentId:'i',split:'test',informationCutoff:issuedAt,upstreamObservationIds:['pixel'],inputs:[input('future','PHYSICAL_OBSERVATION','2026-08-24T12:01:00Z')]}],report=detectForecastLeakage(rows);
  assert.equal(report.passed,false);assert.deepEqual(new Set(report.violations.map((item)=>item.code)),new Set(['INCIDENT_SPLIT_LEAKAGE','UPSTREAM_OBSERVATION_SPLIT_LEAKAGE','FUTURE_INFORMATION_LEAKAGE']));
});

test('strong deterministic baselines emit ordered immutable research contours and a transparent ensemble',()=>{
  const initial=square(),persistence=noGrowthPersistence({issuedAt,initialPerimeter:initial}),recent=recentGrowthPersistence({issuedAt,initialPerimeter:initial,areaGrowthKm2PerHour:.5}),wind=windAlignedProgression({issuedAt,initialPerimeter:initial,boundaryVelocityKmH:.2,windDirectionDeg:270,windSpeedMs:10}),ensemble=combineForecastMembers({members:[recent,wind]});
  assert.equal(persistence.horizons.length,5);assert.ok(polygonAreaKm2(recent.horizons.at(-1).contours[0].geometry)>polygonAreaKm2(recent.horizons[0].contours[0].geometry));assert.deepEqual(ensemble.horizons.map((item)=>item.hours),[1,3,6,12,24]);assert.equal(ensemble.state,'MULTI_MEMBER');assert.equal(ensemble.members.length,2);assert.equal(Object.isFrozen(ensemble),true);
});

test('forecast objects can never become evidence or authority',()=>{const value=forecastFrom(noGrowthPersistence({issuedAt,initialPerimeter:square()}));assert.equal(value.epistemicType,'FORECAST');assert.equal(value.evidenceEligible,false);assert.equal(value.authorityEligible,false);assert.ok(value.forecastId.startsWith('fire-forecast:sha256:'));});

test('spread, calibration, and impact metrics remain separate and inspectable',()=>{
  const member=noGrowthPersistence({issuedAt,initialPerimeter:square()}),spread=aggregateSpreadEvaluation(member.horizons.map((forecastHorizon)=>({forecastHorizon,observedPerimeter:square()}))),calibration=evaluateProbabilityCalibration([{probability:.8,outcome:1},{probability:.2,outcome:0}]),forecast=forecastFrom(member),impact=forecastAssetExposure({forecast,assets:[{id:'hospital',type:'HOSPITAL',coordinate:[-120.995,47.005],populationEstimate:10}]}),impactMetrics=evaluateImpactForecast({predictions:impact.exposures,labels:[{assetId:'hospital',exposed:true,arrivalHours:1}]});
  assert.equal(spread.horizons[1].meanIou,1);assert.ok(calibration.brierScore<.1);assert.equal(impact.exposures[0].earliestPlausibleHours,1);assert.equal(impactMetrics.assetExposureRecall,1);
});

test('abstention is first-class when current inputs are incomplete',()=>{const value=decideForecastAbstention({initialPerimeter:square(),perimeterHistoryCount:1,weatherMemberCount:1,fuelAvailable:false,terrainAvailable:false,calibrationAvailable:false});assert.equal(value.state,'ABSTAINED');assert.ok(value.reasons.includes('INSUFFICIENT_PERIMETER_HISTORY'));assert.ok(value.reasons.includes('WEATHER_ENSEMBLE_UNAVAILABLE'));});

test('forecast replay detects model substitution and validates an identical issue',()=>{const inputManifest=manifest(),entry=model(),forecast=forecastFrom(noGrowthPersistence({issuedAt,initialPerimeter:square()}),inputManifest),receipt=createForecastReceipt({forecast,inputManifest,modelEntry:entry}),valid=verifyForecastReplay({forecast,inputManifest,modelEntry:entry,receipt,reissuedForecast:createForecast(forecast)}),substituted=verifyForecastReplay({forecast,inputManifest,modelEntry:{...entry,fingerprint:'forecast-model:sha256:other'},receipt});assert.equal(valid.valid,true);assert.equal(valid.identical,true);assert.equal(substituted.valid,false);assert.ok(substituted.reasons.includes('MODEL_SUBSTITUTED'));});

test('fixed promotion gates fail closed for the inherited single-region positive-only corpus',()=>{const decision=evaluateForecastPromotion({corpus:{negativeControls:0,regions:['Portugal'],seasons:['2024']},leakage:{passed:true,violations:[]},evaluation:{incidentSplitIsolation:true,upstreamObservationSplitIsolation:true,horizons:{},baselineWins:[]},replay:{valid:true,identical:true},ablations:{complete:false}});assert.equal(decision.decision,'DO_NOT_ADVANCE');assert.ok(decision.failedGates.includes('NEGATIVE_CONTROLS_PRESENT'));assert.ok(decision.failedGates.includes('TWO_REGIONS_PRESENT'));});

test('assimilation rejects future revisions and exposes contradictory official geometry',()=>{const revisions=[{id:'a',observedAt:'2026-08-24T10:00:00Z',knowledgeTime:'2026-08-24T10:30:00Z',contentHash:'sha256:a',geometry:square()},{id:'b',observedAt:'2026-08-24T10:00:00Z',knowledgeTime:'2026-08-24T11:00:00Z',contentHash:'sha256:b',geometry:square(.02)}],state=createForecastAssimilationState({incidentId:'i',informationCutoff:'2026-08-24T11:59:00Z',perimeterRevisions:revisions});assert.equal(state.state,'CONTRADICTED');assert.equal(state.contradictions.length,1);assert.throws(()=>createForecastAssimilationState({incidentId:'i',informationCutoff:'2026-08-24T10:59:00Z',perimeterRevisions:revisions}),/future_information/);});
test('scoring requires a future label at a declared horizon and preserves tail underprediction',()=>{const forecast=forecastFrom(noGrowthPersistence({issuedAt,initialPerimeter:square()})),score=scoreIssuedForecast({forecast,observation:{id:'later-perimeter',observedAt:'2026-08-24T13:00:00Z',knowledgeTime:'2026-08-24T13:05:00Z',contentHash:'sha256:later',geometry:square(.03)}});assert.equal(score.horizonHours,1);assert.ok(score.metrics.underpredictionAreaKm2>0);assert.throws(()=>scoreIssuedForecast({forecast,observation:{id:'early',observedAt:issuedAt,knowledgeTime:issuedAt,contentHash:'x',geometry:square()}}),/not_future/);});
test('forecast policy boundary blocks consequential action attempts',()=>{const forecast=forecastFrom(noGrowthPersistence({issuedAt,initialPerimeter:square()})),input=createForecastPolicyInput({forecast,requestedActions:['PRIORITIZE_MONITORING','EVACUATE','SHELL_COMMAND']});assert.deepEqual(input.allowedActions,['PRIORITIZE_MONITORING']);assert.deepEqual(input.blockedActions.map((item)=>item.reason),['CONSEQUENTIAL_ACTION_FORBIDDEN','ACTION_NOT_ALLOWLISTED']);assert.equal(input.consequentialExecution,'DISABLED');});
test('adversarial geometry, confidence, stale data, domain mismatch, wind, and contradiction fail closed',()=>{const bow={type:'Polygon',coordinates:[[[-121,47],[-120.99,47.01],[-121,47.01],[-120.99,47],[-121,47]]]},outer=square(.01),inner=square(.03);assert.throws(()=>validateProbabilityContours([{probability:1.1,geometry:outer}]),/probability_invalid/);assert.throws(()=>validateProbabilityContours([{probability:.1,geometry:outer},{probability:.9,geometry:inner}]),/non_monotonic/);assert.throws(()=>validateProbabilityContours([{probability:.5,geometry:bow}]),/self_intersection/);const single=combineForecastMembers({members:[noGrowthPersistence({issuedAt,initialPerimeter:square()})]}),abstained=decideForecastAbstention({initialPerimeter:square(),perimeterHistoryCount:2,weatherMemberCount:1,fuelAvailable:true,terrainAvailable:true,calibrationAvailable:true,geographyApplicable:false,fuelApplicable:true,windSpeedMs:60,inputAgeMs:7*60*60_000,contradictionUnresolved:true});assert.equal(single.state,'DEGRADED_SINGLE_MEMBER');assert.ok(abstained.reasons.includes('OUTSIDE_MODEL_GEOGRAPHY'));assert.ok(abstained.reasons.includes('MODEL_EXTRAPOLATION'));assert.ok(abstained.reasons.includes('INPUT_DATA_STALE'));assert.ok(abstained.reasons.includes('SOURCE_CONTRADICTION_UNRESOLVED'));});
