import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import {
  createCausalLineage,createDatasetManifest,createSourceCoverageIndex,detectDatasetLeakage,evaluateCausalIndependence,
  evaluateIncidentCorpus,evaluateObservationOpportunity,getEligibleSources,sourceAblations,verifyProviderManifest
} from '../../src/reality-network/index.mjs';
import { PROVIDER_MANIFESTS } from '../../../../apps/api/src/modules/reality-network/provider-portfolio.mjs';

const fixture=JSON.parse(await readFile(new URL('../fixtures/reality-network/historical-incidents.json',import.meta.url),'utf8'));
const lineage=(originalObservation,instrumentFamily='VIIRS')=>createCausalLineage({sourceClass:'PHYSICAL',publisher:'NASA',institution:'NASA',processingCenter:'MODAPS',satellitePlatform:'S-NPP',instrument:instrumentFamily,instrumentFamily,algorithmProduct:'NRT',originalObservation,physicalModality:instrumentFamily==='ABI'?'GEOSTATIONARY_THERMAL':'POLAR_THERMAL'});

test('provider manifests are versioned, immutable, and integrity bound',()=>{assert.equal(PROVIDER_MANIFESTS.length,9);for(const manifest of PROVIDER_MANIFESTS){assert.equal(verifyProviderManifest(manifest),true);assert.equal(Object.isFrozen(manifest),true);assert.ok(manifest.budgets.maxRequestsPerRun>0);}});
test('hierarchical independence removes republished original observations',()=>{const a=lineage('pixel-1'),broker={...structuredClone(a),transportProvider:'broker-b',lineageId:'broker-copy'},abi=lineage('pixel-2','ABI'),result=evaluateCausalIndependence({lineages:[a,broker,abi],requirements:{originalObservation:2,instrumentFamily:2,institution:1}});assert.equal(result.satisfied,true);assert.equal(result.physicalStatements,3);assert.equal(result.uniqueOriginalObservations,2);assert.equal(result.counts.instrumentFamily,2);});
test('zero rows are negative only after a valid observation opportunity',()=>{const unknown=evaluateObservationOpportunity({source:{sourceId:'goes',status:'LIVE'},productAvailability:{state:'AVAILABLE'},coverage:{applicable:true},quality:{validObservation:false},detections:[]}),negative=evaluateObservationOpportunity({source:{sourceId:'goes',status:'LIVE'},productAvailability:{state:'AVAILABLE',productId:'p1'},coverage:{applicable:true},quality:{validObservation:true},detections:[]});assert.equal(unknown.state,'OBSTRUCTED');assert.equal(negative.state,'VALID_NEGATIVE');});
test('coverage eligibility respects geography, health, maturity, and role',()=>{const index=createSourceCoverageIndex([{sourceId:'goes:g19',productId:'FDCC',bbox:[-135,0,-5,70],temporalCoverage:{from:'2020-01-01T00:00:00Z'},cadenceSeconds:300,expectedLatencySeconds:600,sourceClass:'PHYSICAL',maturity:'OPERATIONAL',lineage:{originalObservation:'scan'},contractRoles:['INDEPENDENT_PHYSICAL_CORROBORATION']}]),rows=getEligibleSources({index,geometry:{type:'Point',coordinates:[-121,47]},timeWindow:{from:'2026-08-24T00:00:00Z',to:'2026-08-24T01:00:00Z'},evidenceNeed:{roles:['INDEPENDENT_PHYSICAL_CORROBORATION']},health:{'goes:g19':{status:'LIVE'}},credentials:{'goes:g19':true}});assert.equal(rows[0].eligible,true);});
test('leakage detector blocks incident, upstream, future, and final-perimeter leakage',()=>{const report=detectDatasetLeakage([{id:'a',incidentId:'i1',originalObservation:'o1',split:'TRAIN',knowledgeTime:'2024-01-01T00:00:00Z',featurePublishedAt:'2024-01-02T00:00:00Z',operationalMode:'NRT',processingMode:'STANDARD',featureKind:'FINAL_PERIMETER',targetKind:'LIVE_DETECTION'},{id:'b',incidentId:'i1',originalObservation:'o1',split:'TEST'}]);assert.equal(report.passed,false);assert.deepEqual(new Set(report.violations.map((item)=>item.code)),new Set(['INCIDENT_CROSSES_SPLITS','UPSTREAM_OBSERVATION_CROSSES_SPLITS','FUTURE_INFORMATION_FEATURE','REPROCESSED_PRODUCT_IN_NRT','FINAL_PERIMETER_LIVE_FEATURE']));});
test('historical evaluation and ablations are deterministic',()=>{const result=evaluateIncidentCorpus(fixture),repeat=evaluateIncidentCorpus([...fixture].reverse()),ablations=sourceAblations(fixture,['firms:viirs','goes:g19']);assert.equal(result.metrics.incidents,4);assert.equal(result.metrics.opportunityAdjustedRecall,1);assert.equal(result.metrics.falseIncidentRate,0);assert.equal(result.evaluationHash,repeat.evaluationHash);assert.ok(ablations['WITHOUT:firms:viirs'].independentCorroborationRate<ablations.ALL.independentCorroborationRate);});
test('dataset manifests hash semantic inputs independently of creation time',()=>{const input={datasetId:'reality-eval',version:'1',sourceProducts:[{providerId:'nasa-firms',productId:'VIIRS',version:'2024',rawObjectHashes:['b','a']}],queryRegions:[{id:'pt'}],timeRanges:[{from:'2023-01-01',to:'2024-12-31'}],canonicalSchemaVersion:'v1',featureCodeVersion:'git:test',labelSources:['ICNF'],splitDefinition:{method:'incident'},licenceIds:['NASA-FIRMS-TERMS'],creationTime:'2026-08-24T00:00:00Z'};const manifest=createDatasetManifest(input),later=createDatasetManifest({...input,creationTime:'2026-08-25T00:00:00Z'});assert.equal(manifest.semanticHash,later.semanticHash);});
