import test from 'node:test';
import assert from 'node:assert/strict';
import { realWorldValue } from '../../src/operational-twin/real-world-value.mjs';
import { weatherMetrics, thermalMetrics, airMetrics, placeMetrics } from '../../src/operational-twin/physical-conditions.mjs';
import { projectPhysicalWorld, physicalChanges } from '../../src/operational-twin/physical-world.mjs';
import { parseOperatorQuestion, answerOperatorQuestion, getRoadContext } from '../../src/operational-twin/operator-questions.mjs';

const asOf='2026-09-08T12:00:00.000Z',observedAt='2026-09-08T11:52:00.000Z',receivedAt='2026-09-08T11:59:00.000Z';
const station={id:'test-station',stationId:'test-station',name:'Fixture ridge',stationName:'Fixture ridge',source:'IPMA',coordinate:[-8.4,40.2],observedAt,receivedAt,temperatureC:28,windSpeedKph:32,windDirection:'NW',humidityPercent:18,precipitationMm:0,provenance:{synthetic:false,provider:'IPMA',rawSourceProductId:'fixture:weather'}};
const point=[-8,40.2];
const heat={id:'heat',instrument:'VIIRS',source:'NASA FIRMS',sourceFamily:'viirs',independenceGroup:'viirs_snpp',coordinate:[-8.01,40.2],observedAt,receivedAt,frpMw:37,scanKm:.4,trackKm:.6,provenance:{synthetic:false,provider:'NASA FIRMS'}};
const actor={incidentScopes:['*']};
function incident(kind){
  const id='incident:'+kind,good=kind==='current',stale=kind==='stale';
  const observation={id:'official:'+kind,sourceId:'authority',observedAt:good?observedAt:'2026-09-01T10:00:00Z',receivedAt,location:{geometry:{type:'Point',coordinates:point}},value:{officialIncidentStatus:'ACTIVE',cap:{status:'Actual',scope:'Public',identifier:'warning:'+kind,event:'Wind warning',sent:good?observedAt:'2026-09-01T10:00:00Z',effective:good?'2026-09-08T11:00:00Z':'2026-09-01T10:00:00Z',expires:good?'2026-09-08T18:00:00Z':'2026-09-02T10:00:00Z',areaDescription:'Fixture incident area'}}};
  return {incident:{id,label:'Fixture '+kind,location:{geometry:{type:'Point',coordinates:point}}},evidenceGraph:{sources:[{id:'authority',label:'Fixture official authority',familyId:'official'}],sourceFamilies:[{id:'official',familyClass:'OFFICIAL'}],observations:good||stale?[observation]:[]},
    spatialTruth:good?{officialPerimeter:{geometry:{type:'Polygon',coordinates:[[[-8.02,40.19],[-7.98,40.19],[-8,40.22],[-8.02,40.19]]]},authority:'OFFICIAL'}}:{},
    roads:good?[{id:'road',label:'Fixture access road',source:'Fixture road authority',state:'CLOSED',statusEvidenceId:'road:notice',observedAt,effective:observedAt,expires:'2026-09-08T18:00:00Z',direction:'Both directions'}]:[]};
}
function scenario(kind){const item=incident(kind),fresh=kind==='current',old='2026-09-08T06:00:00Z',world={meta:{mode:'production',generatedAt:asOf},directWeather:kind==='none'?[]:[{...station,observedAt:fresh?observedAt:old}],thermalDetections:kind==='none'?[]:[{...heat,observedAt:fresh?observedAt:old}],sources:{ipmaWeather:{state:fresh?'current':kind==='stale'?'unavailable':'current',error:kind==='stale'?'timeout':null,lastSuccessAt:receivedAt},firms:{origin:'NASA FIRMS',state:fresh?'current':kind==='stale'?'unavailable':'current',error:kind==='stale'?'timeout':null,lastSuccessAt:receivedAt}}};return projectPhysicalWorld({twin:{asOf,incidents:[item]},actor,incidentId:item.incident.id,world,asOf}).incidents[0];}

test('recalculation and receipt never reset an eighty-minute-old observation',()=>{const value=realWorldValue({id:'wind',label:'Wind',value:32,unit:'km/h',record:{...station,observedAt:'2026-09-08T10:40:00Z'},asOf,ttlMs:3600000});assert.equal(value.ageMinutes,80);assert.equal(value.observedAt,'2026-09-08T10:40:00.000Z');assert.equal(value.receivedAt,receivedAt);assert.equal(value.calculatedAt,asOf);assert.equal(value.freshnessState,'STALE');});
test('valid distant station is regional, never current local temperature',()=>{const c=weatherMetrics([station],asOf,{location:point,subjectId:'incident:test'});assert.equal(c.temperature.validity,'VALID_VALUE');assert.equal(c.temperature.measurementType,'OBSERVED_REGIONAL');assert.ok(c.stationDistance>30);assert.deepEqual(c.temperature.sourceLocation.coordinate,station.coordinate);assert.match(c.limitations[0],/regional context/);});
test('a physical situation without a supplied incident name retains coordinate context in its answer',()=>{const item=incident('none');delete item.incident.label;const c=projectPhysicalWorld({twin:{asOf,incidents:[item]},actor,incidentId:item.incident.id,asOf}).incidents[0];assert.equal(c.locationLabel,'Incident near 40.2000, -8.0000');assert.match(answerOperatorQuestion(c,{type:'SITUATION'}).primaryAnswer,/40\.2000, -8\.0000/);});
test('one fresh suitable station wins over a stale nearer station; fields never mix',()=>{const c=weatherMetrics([{...station,stationId:'near-old',coordinate:point,observedAt:'2026-09-08T06:00:00Z',temperatureC:99},station],asOf,{location:point});assert.equal(c.station.id,station.stationId);assert.equal(c.temperature.value,28);assert.equal(c.wind.observedAt,c.humidity.observedAt);});
test('daily maximum and modeled gust cannot populate current measured gust',()=>{assert.equal(weatherMetrics([{...station,gustKph:90,gustStatistic:'daily maximum'}],asOf).gust.value,null);assert.equal(weatherMetrics([{...station,gustKph:90,model:'IFS'}],asOf).gust.value,null);});
test('a missing gust explains the absent field',()=>{const g=weatherMetrics([station],asOf).gust;assert.equal(g.missingReason,'FIELD_NOT_PROVIDED');assert.ok(g.limitations.some(x=>x.includes('Gusts are not provided')));});
test('deduplicated upstream sensor does not become independent confirmation',()=>{const t=thermalMetrics([heat,{...heat,id:'transport-copy',source:'Mirror'}],point,asOf);assert.equal(t.detections.length,1);assert.equal(t.latestThermalDetection.definition.pixelFootprintKm[0],.4);});
test('one recent thermal observation produces one physical event, without an additional aggregate event',()=>{const c=scenario('current');assert.equal(c.changes.filter(e=>e.type==='Fire detection').length,1);});
test('thermal points and derived observation extent cannot become an official perimeter',()=>{const item=incident('none');item.spatialTruth={officialPerimeter:{geometry:{type:'Point',coordinates:point}},derivedBoundary:{geometry:{type:'Polygon',coordinates:[]}}};const c=projectPhysicalWorld({twin:{asOf,incidents:[item]},actor,incidentId:item.incident.id}).incidents[0];assert.equal(c.questions.fire.fireActivity.observedGeometry,null);});
test('healthy empty thermal result means zero returned observations; failure remains unknown',()=>{const state={state:'current',lastSuccessAt:receivedAt};assert.equal(thermalMetrics([],point,asOf,null,state).metrics.find(m=>m.id==='thermal60').value,0);assert.equal(thermalMetrics([],point,asOf,null,{...state,state:'unavailable',error:'timeout'}).metrics.find(m=>m.id==='thermal60').value,null);});
test('retrieved road geometry is not a dated restriction or safe route',()=>{const places=placeMetrics([],[{id:'r',state:'CLOSED',retrievedAt:receivedAt,source:'OSM'}],asOf),q=getRoadContext({asOf,places});assert.equal(q.restrictions.length,0);assert.match(q.primaryAnswer,/Road status unknown/);assert.equal(places.roadMetrics[0].value,null);});
test('a reported road restriction without current validity remains last known',()=>{const q=getRoadContext({asOf,places:{roads:[{id:'r',state:'CLOSED',observedAt:'2026-08-01T00:00:00Z',statusEvidenceId:'old'}]}});assert.equal(q.restrictions.length,0);assert.equal(q.missingReason,'SOURCE_STALE');});
test('missing or modeled AQ never becomes Good air quality',()=>{const a=airMetrics([{kind:'MODELLED_SMOKE',model:'model',pm25UgM3:3}],point,asOf);assert.equal(a.metrics.find(m=>m.id==='aqCategory').value,null);assert.equal(a.metrics[0].missingReason,'CAPABILITY_NOT_CONNECTED');});
test('weather display significance remains configurable and never supplies severity',()=>{const weather=weatherMetrics([{...station,observedAt:'2026-09-08T10:52:00Z',windSpeedKph:18},station],asOf);const changes=physicalChanges({weather,air:{metrics:[]},thermal:{detections:[]},warnings:{warnings:[]}},asOf);assert.equal(changes[0].material,true);assert.equal(changes[0].severity,undefined);const configured=physicalChanges({weather,air:{metrics:[]},thermal:{detections:[]},warnings:{warnings:[]}},asOf,{version:'test-explicit-policy',physicalThresholds:{wind:{minimumDelta:10,windowMinutes:60}}});assert.equal(configured[0].material,true);const suppressed=physicalChanges({weather,air:{metrics:[]},thermal:{detections:[]},warnings:{warnings:[]}},asOf,{version:'high-display-threshold',physicalThresholds:{wind:{minimumDelta:50,windowMinutes:60}}});assert.equal(suppressed[0].material,false);});

for(const kind of ['current','stale','none'])test('operator question acceptance: '+kind,()=>{
  const c=scenario(kind),q=c.questions;
  assert.deepEqual(c.location,point,'where');assert.equal(q.conditions.asOf,asOf,'answer clock');
  assert.match(q.fire.primaryAnswer,kind==='none'?/No matching thermal detection/:/Latest.*thermal|Latest VIIRS/,'what is happening');
  assert.match(q.conditions.primaryAnswer,kind==='none'?/Current weather is unknown/:/Wind 32 km\/h NW/,'conditions');
  if(kind!=='none')assert.equal(q.conditions.currentConditions.wind.ageMinutes,kind==='current'?8:360,'observation age');
  assert.match(q.official.primaryAnswer,kind==='none'?/status is unknown/:/ACTIVE/,'official status');
  assert.equal(q.changes.primaryAnswer,kind==='current'?'Fixture official authority issued Wind warning for Fixture incident area.':'No dated material change was returned in this period.','what changed');
  if(kind==='current')assert.ok(q.changes.events.some(e=>e.type==='Fire detection'),'thermal observation remains a dated material event');
  assert.ok(q.unknowns.unknowns.includes(kind==='none'?'No suitable station observation is available to determine gusts.':'Current gust measurement is not supplied by the selected station feed.'),'specific missingness');
  assert.match(q.attention.primaryAnswer,kind==='current'?/Review current official instructions/:/Verify road access/,'next useful investigation');
  if(kind==='stale'){assert.match(q.conditions.primaryAnswer,/Last known/);assert.ok(q.unknowns.stale.some(m=>m.id==='wind'));}
  if(kind==='none'){assert.match(q.warnings.primaryAnswer,/unknown/);assert.doesNotMatch(q.warnings.primaryAnswer,/safe|all.clear/i);}
  for(const text of ['What are conditions there?','When was the latest fire detection?','How far away was it detected?','What official warnings apply?','Which roads have reported restrictions?','What places are exposed?','What changed in the last hour?','What data is stale?',"What don't we know?",'What should I investigate next?','Why are you showing this wind value?','What source produced this reading?']){const intent=parseOperatorQuestion(text);assert.ok(intent,text);assert.ok(answerOperatorQuestion(c,intent)?.primaryAnswer,text);}
});
