import { dateStamp, html, label, observationTitle } from '../format.js';

function version(item, index) {
  const values = item.values ?? item, claim = item.payload?.claimValue ?? values.claimValue ?? values.state ?? observationTitle(item), observer = item.actor ?? item.observerIdentity?.displayName ?? item.observerIdentity;
  return `<article><span>VERSION ${index + 1} · ${html(label(item.origin ?? item.sourceIdentity?.kind ?? 'field observation'))}</span><strong>${html(claim)}</strong><dl><div><dt>Time</dt><dd>${html(dateStamp(item.observedAt ?? item.createdAt))}</dd></div><div><dt>Operator</dt><dd>${html(observer ?? 'Attributable identity retained in evidence')}</dd></div><div><dt>Location</dt><dd>${item.horizontalUncertaintyM != null ? `GPS ±${html(item.horizontalUncertaintyM)} m` : 'See underlying evidence'}</dd></div></dl></article>`;
}

export function conflictsView(model) {
  const conflicts = model.conflicts.filter((item) => item.state === 'OPEN');
  return `<section class="fieldnet-conflict-workspace"><header><div><span>TRUTH CONFLICTS</span><h2>VIGIA refuses to guess.</h2></div><p>Both versions remain immutable evidence until a human-authorized resolution or independent verification exists.</p></header>${conflicts.length ? conflicts.map(conflictCard).join('') : '<div class="fieldnet-no-conflict"><strong>No open evidence conflict</strong><p>Resolved versions remain available in replay and the decision ledger.</p></div>'}</section>`;
}

function conflictCard(conflict) {
  const versions = conflict.versions ?? [];
  const plan = conflict.resolutionPlan ?? {};
  return `<article class="fieldnet-conflict"><header><div><span>WHAT WE DO NOT KNOW</span><strong>${html(label(conflict.subjectType))} · ${html(conflict.subjectId)}</strong></div><b>UNRESOLVED</b></header><div class="fieldnet-conflict-versions">${versions.length ? versions.map(version).join('') : '<article><strong>Independent observations remain separate</strong><p>Open the evidence inspection for original records.</p></article>'}</div><section><span>HOW WE CAN KNOW</span><strong>${html(plan.recommendedVerificationTask ?? label(conflict.causalRelationship ?? 'spatial temporal evidence conflicts'))}</strong><p>${html((plan.possibleResolutionEvidence ?? conflict.recommendedMergePossibilities ?? []).map(label).join(' · ') || 'Contradictory claims require field verification.')}</p><dl class="fieldnet-resolution-metrics"><div><dt>Spatial</dt><dd>${html(label(plan.spatialOverlap ?? 'not computable'))}${plan.spatialSeparationM != null ? ` · ${html(plan.spatialSeparationM)} m` : ''}</dd></div><div><dt>Time apart</dt><dd>${plan.timeSeparationMs != null ? `${Math.round(plan.timeSeparationMs / 1000)} seconds` : 'Not computable'}</dd></div><div><dt>Closes when</dt><dd>${html(plan.closesWhen ?? conflict.resolutionRequirement)}</dd></div></dl></section><footer><div><span>WHAT VIGIA DID NEXT</span><strong>${html(plan.responsibility?.system ? `${label(plan.responsibility.system)} · verification task available` : 'Evidence preserved · human authority required')}</strong></div><button type="button" data-map-frame-kind="CONFLICT" data-map-frame-id="${html(conflict.conflictId)}">Show on map</button>${conflict.subjectType === 'FIELD_TASK' ? `<button type="button" data-fieldnet-resolve="KEEP_CURRENT" data-conflict-id="${html(conflict.conflictId)}">Keep current</button><button type="button" data-fieldnet-resolve="ACCEPT_OFFLINE" data-conflict-id="${html(conflict.conflictId)}">Accept offline version</button>` : `<button type="button" data-fieldnet-panel="tasks">Open verification task</button>`}</footer></article>`;
}
