import { elapsed, html, label, shortId } from '../format.js';

export function joinView(model, baseUrl) {
  const localUrl = `${baseUrl}/`, active = model.devices.filter((item) => item.active !== false), currentDeviceId = localStorage.getItem('vigia.fieldnet.device-id'), joined = model.devices.some((item) => item.deviceId === currentDeviceId);
  const gateway = model.sensorGateway, hardware = gateway?.hardware;
  return `<div class="fieldnet-join-grid"><section class="fieldnet-join"><header><span>JOIN FIELDNET</span><h2>Connect to the local incident node.</h2><p>The local address contains no credential or secret. Operator identity and device registration remain explicit.</p></header>
    <div class="fieldnet-join-address"><span>LOCAL NODE URL</span><strong>${html(localUrl)}</strong><button type="button" data-copy-fieldnet-url="${html(localUrl)}">Copy address</button><button type="button" data-fieldnet-join ${joined ? 'disabled' : ''}>${joined ? 'This browser is joined' : 'Register this field device'}</button></div>
    <dl><div><dt>Incident</dt><dd>${html(model.incident?.incidentState?.label ?? model.incidentId)}</dd></div><div><dt>Node identity</dt><dd>${html(model.node.nodeId)}</dd></div><div><dt>Security</dt><dd>Local session · operator attribution required</dd></div><div><dt>QR</dt><dd>Unavailable until the Field Node exposes an unsigned join payload; no fake code is displayed.</dd></div></dl>
    <section class="fieldnet-sensor-gateway"><header><span>FIELD SENSOR GATEWAY</span><strong>${html(gateway?.productionGateway ?? 'UNAVAILABLE')}</strong></header><div class="fieldnet-hardware-state is-${hardware?.status === 'NOT_PRESENT' ? 'absent' : 'present'}"><span>REAL HARDWARE</span><strong>${html(label(hardware?.status ?? 'not inspected'))}</strong><p>${html(hardware?.qualification ?? 'Hardware discovery report unavailable.')}</p></div><dl><div><dt>Ready now</dt><dd>${html(Object.entries(gateway?.adapters ?? {}).filter(([, adapter]) => adapter.state === 'READY').map(([name]) => label(name)).join(' · ') || 'No adapter ready')}</dd></div><div><dt>Qualified</dt><dd>${gateway?.registeredSensors?.filter((sensor) => sensor.physicalFamilyEligible).length ?? 0} physical sensor families</dd></div><div><dt>Guardrail</dt><dd>Exercise sensors never count as production physical evidence.</dd></div></dl></section>
  </section><section class="fieldnet-devices"><header><span>KNOWN DEVICES</span><strong>${active.length} active</strong></header>${model.devices.length ? model.devices.map(deviceCard).join('') : '<p class="fieldnet-empty">No registered local device.</p>'}</section></div>`;
}

function deviceCard(device) {
  const sensor = device.schemaVersion === 'vigia.field-sensor-registration.v1';
  return `<article><header><div><span>${html(label(device.deviceType))}</span><strong>${html(sensor ? device.sensorFamily : device.ownerOperator)}</strong></div><b>${sensor ? html(label(device.currentQualification)) : device.active === false ? 'INACTIVE' : 'KNOWN'}</b></header><dl><div><dt>Identity</dt><dd>${html(shortId(device.deviceId))}</dd></div><div><dt>Last seen</dt><dd>${html(elapsed(device.lastSeenAt))} ago</dd></div><div><dt>Location</dt><dd>${html(label(device.locationQuality ?? 'unknown'))}</dd></div><div><dt>Clock</dt><dd>${html(label(device.timeQuality ?? 'unknown'))}</dd></div><div><dt>Capability</dt><dd>${html((device.capabilities ?? []).map(label).join(' + ') || 'No capability claimed')}</dd></div>${sensor ? `<div><dt>Measurement</dt><dd>${html(label(device.measurementType))} · ${html(device.unit)}</dd></div><div><dt>Evidence</dt><dd>${device.physicalFamilyEligible ? 'Eligible physical family' : html((device.qualificationBlockers ?? []).map(label).join(' · '))}</dd></div>` : ''}<div><dt>Sync</dt><dd>${device.active === false ? 'Not participating' : 'Available to local node'}</dd></div></dl></article>`;
}
