import {icon} from '../ui/icons.js';
import {e,badge,button,link,panel,empty} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {incidentFor,isLimited,timeLabel} from '../data/model.js';
import {DEMO_TIME} from '../data/fixtures.js';
export function detail(state){const i=incidentFor(state),limited=isLimited(state);if(!i)return empty('Incident not found','The selected incident is not present in this preview.',button('Browse incidents','navigate',{extra:'data-route="incidents"'}));
 const age=Math.round((new Date(DEMO_TIME)-new Date(i.observedAt))/86400000);
 return `<div class="route-stack"><div class="incident-context"><span>${badge(limited?'Information unavailable':i.verified?'Confirmed · exercise':'Needs verification',i.verified?'green':'amber')}</span>${button('Change incident','choose-incident',{ico:'down'})}</div>
 <div class="fact-strip"><div><span>Observed</span><strong>${limited?'Unavailable':e(timeLabel(i.observedAt))}</strong></div><div><span>Observation age</span><strong>${limited?'Unavailable':age>0?`${age} days ago`:'Today'}</strong></div><div><span>Operational class</span><strong>${limited?'Unavailable':i.verified?'Exercise incident':'Wildfire candidate'}</strong></div><div><span>Source coverage</span><strong>${limited?'Unavailable':i.verified?'Exercise confirmation':'No official confirmation'}</strong></div></div>
 <div class="detail-primary">${panel('Latest observation',`<div class="detail-map-pad">${mapView({id:'detail-map',title:i.name,height:326,limited})}</div>`,{action:button('Expand incident map','expand-map',{ico:'expand',tone:'icon-button',extra:'data-kind="local"'})})}
 <div class="detail-findings">${panel('What we know',limited?empty('Information unavailable','The incident summary could not be loaded.'):`<ul class="fact-list"><li><i class="dot amber"></i>${e(i.type)} recorded in the demonstration dataset.</li><li><i class="dot amber"></i>Location context: ${e(i.name)}.</li><li><i class="dot"></i>${i.verified?'Exercise confirmation is recorded.':'Current fire presence is not independently confirmed.'}</li></ul>`)}
 ${panel('What remains uncertain',`<ul class="fact-list"><li><i class="dot amber"></i>Has an official source confirmed the incident?</li><li><i class="dot amber"></i>Is there more recent activity?</li><li><i class="dot amber"></i>What is the affected area?</li></ul><div class="detail-actions">${button('Investigate evidence','navigate',{tone:'soft-blue',extra:'data-route="intelligence"'})}${button('Manage work','navigate',{tone:'primary',ico:'arrow',extra:'data-route="operations"'})}</div>`)}</div></div>
 <div class="equal-col">${panel('Recent timeline',limited?empty('Timeline unavailable','No observation history was returned.'):`<div class="rows"><div class="row timeline-row">${icon('clock')}<time>${e(timeLabel(i.observedAt))}</time><span>${e(i.type)} recorded</span></div><div class="row timeline-row">${icon('file')}<time>7 Sept 2026, 11:08 UTC</time><span>Source review scheduled</span></div><div class="row timeline-row">${icon('info')}<time>Current view</time><span>${i.verified?'Exercise status retained':'Confirmation still needed'}</span></div></div><div class="panel-foot">${link('View full timeline','incident-history')}</div>`)}
 ${panel('Nearby context',`<div class="nearby-rows"><div>${icon('pin')}<span>${e(i.region)}</span><small>Region</small></div><div>${icon('map')}<span>Mapped surroundings</span><small>Location context</small></div><div>${icon('info')}<span>Affected area</span><small>Not established</small></div></div><div class="context-notice">Nearby does not mean affected. No shelter, safe route, or response availability is inferred.</div>`)}</div></div>`;
}
