import {icon} from '../ui/icons.js';
import {e,badge,button,link,panel,empty,select,kv} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {incidentsFor,filterIncidents,incidentFor,isLimited,timeLabel} from '../data/model.js';
export function incidents(state,ui){const list=incidentsFor(state),filtered=filterIncidents(list,ui.incidentFilters),size=7,pages=Math.max(1,Math.ceil(filtered.length/size));ui.page=Math.min(ui.page,pages);const page=filtered.slice((ui.page-1)*size,ui.page*size),selected=incidentFor(state),limited=isLimited(state);
 return `<div class="route-stack"><div class="search-box">${icon('search')}<input id="incident-search" type="search" aria-label="Search incidents" placeholder="Search by name, location, or ID…" value="${e(ui.incidentFilters.search)}" data-control="incident-search">${ui.incidentFilters.search?button('Clear search','clear-search',{tone:'icon-button',ico:'close'}):''}</div>
 <div class="filter-row">${select('Incident status','incident-status',[['all','All statuses'],['candidate','Needs verification'],['confirmed','Confirmed · exercise'],['monitored','Monitored']],ui.incidentFilters.status)}${select('Incident type','incident-type',[['all','All types'],['heat','Heat detections'],['other','Other reports']],ui.incidentFilters.type)}${select('Incident priority','incident-priority',[['all','All priorities'],['high','High priority'],['normal','Normal priority']],ui.incidentFilters.priority)}${button('Reset filters','reset-filters',{ico:'filter'})}</div>
 ${ui.incidentFilters.region!=='all'?`<div class="filter-applied">Region: <strong>${e(ui.incidentFilters.region)}</strong> ${link('Clear regional filter','reset-filters')}</div>`:''}
 <div class="incidents-workspace">${panel(limited?'Incidents unavailable':`${filtered.length} incidents`,limited?empty('Incident list unavailable','No records have been returned in this limited-data test.'):page.length?`<div class="incident-list" aria-label="Incident records">${page.map(i=>`<button class="incident-row ${i.id===state.selected?'selected':''}" data-action="select-incident" data-id="${i.id}" aria-pressed="${i.id===state.selected}"><span class="flame-tile ${i.priority==='high'?'high':i.status}">${icon('flame')}</span><span class="row-main"><strong>${e(i.name)}</strong><span>${e(i.type)} · ${i.status==='confirmed'?'Exercise confirmed':i.status==='monitored'?'Monitoring':'Needs verification'}</span><small>${e(timeLabel(i.observedAt))}</small></span>${icon('chevron')}</button>`).join('')}</div><div class="pagination"><span>${(ui.page-1)*size+1}–${Math.min(ui.page*size,filtered.length)} of ${filtered.length}</span><div>${button('Previous page','page',{ico:'chevron',tone:'icon-button previous',extra:`data-page="${ui.page-1}"`,disabled:ui.page===1})}${Array.from({length:pages},(_,x)=>button(String(x+1),'page',{tone:`small-btn ${ui.page===x+1?'page-active':''}`,extra:`data-page="${x+1}" aria-label="Page ${x+1}" ${ui.page===x+1?'aria-current="page"':''}`})).join('')}${button('Next page','page',{ico:'chevron',tone:'icon-button',extra:`data-page="${ui.page+1}"`,disabled:ui.page===pages})}</div></div>`:empty('No matching incidents','Try a different search or reset the filters.',button('Reset filters','reset-filters')),{cls:'inbox-list-panel',action:!limited?'<span class="small muted">Source order</span>':''})}
 ${panel('Incident preview',limited?empty('Preview unavailable','Choose a record when incident data returns.'):selected?`<div class="incident-preview-body">${!filtered.some(x=>x.id===selected.id)?'<p class="small preview-outside">Selected record is outside the current filters.</p>':''}${mapView({id:'incident-preview-map',title:selected.name,height:208,legend:false})}<div class="preview-heading">${badge(selected.verified?'Confirmed · exercise':'Needs verification',selected.verified?'green':'amber')}<h2>${e(selected.name)}</h2><strong>${e(selected.type)}</strong><p>${e(timeLabel(selected.observedAt))}</p></div><dl class="preview-fields">${kv('Location',`${selected.lat.toFixed(4)}° N, ${Math.abs(selected.lon).toFixed(4)}° W`)}${kv('Operational class',selected.verified?'Exercise incident':'Detection candidate')}${kv('Source coverage',selected.verified?'Exercise controller confirmation':'No official confirmation')}${kv('Key context',selected.region+' · illustrative records')}</dl>${button('Open incident','open-incident',{tone:'primary wide',ico:'arrow',extra:`data-id="${selected.id}"`})}<p class="preview-disclaimer">Fictional record. Not a live fire report.</p></div>`:empty('Choose an incident','Select a record from the list.'),{cls:'incident-preview-panel'})}</div></div>`;
}
