import {e,badge,button,link,panel,empty} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {QUESTIONS} from '../data/fixtures.js';
import {incidentFor,isLimited} from '../data/model.js';
export function intelligence(state){const i=incidentFor(state),limited=isLimited(state);if(!i)return empty('Incident not found','Choose an incident to investigate.',button('Choose incident','choose-incident'));
 const items=[['NOW',limited?'Information unavailable':i.verified?'Exercise confirmed':'Needs verification'],['NEXT',limited?'Check unavailable':'Source check · 12:00 UTC'],['WATCH','New observations'],['UNCERTAINTY',limited?'Questions unavailable':'4 key questions'],['DECISION','No public recommendation']];
 const evidence=[['VIIRS (NOAA-20)','Satellite','16 Aug, 15:49','Heat observation','Not confirmed'],['MODIS','Satellite','16 Aug, 15:50','Heat observation','Not confirmed'],['IPMA','Weather','7 Sept, 09:00','17.6 °C · 6.8 km/h wind','Context only']];
 return `<div class="route-stack"><div class="brief-strip">${items.map(([l,v],n)=>`<div class="brief-item ${n===0?'now':''}"><span>${l}</span><strong>${e(v)}</strong></div>`).join('')}</div>
 <div class="intel-primary">${panel(`Key questions${limited?'':' (4)'}`,limited?empty('Questions unavailable','No investigation state was returned.'):`<div class="question-list">${QUESTIONS.map((q,n)=>`<button type="button" class="question-row" data-action="question" data-id="${q.id}"><span class="question-number">${n+1}</span><span><strong>${e(q.title)}</strong><small>${e(q.body)}</small></span></button>`).join('')}</div>`,{cls:'questions-panel'})}
 ${panel('Evidence map',`<div class="evidence-map-pad">${mapView({id:'intelligence-map',title:i.name,height:313,limited})}</div>`,{action:button('Expand evidence map','expand-map',{ico:'expand',tone:'icon-button',extra:'data-kind="local"'})})}</div>
 ${panel(`Source evidence${limited?'':' (3)'}`,limited?empty('Source evidence unavailable','No current source records were returned. This is not a zero-source result.'):`<div class="table-wrap"><table class="data-table evidence-table"><caption class="sr-only">Illustrative source evidence. Heat observations do not establish official incident status.</caption><thead><tr><th>Source</th><th>Type</th><th>Time (UTC)</th><th>Finding</th><th>Qualification</th><th><span class="sr-only">Inspect</span></th></tr></thead><tbody>${evidence.map((r,n)=>`<tr>${r.slice(0,4).map(v=>`<td>${e(v)}</td>`).join('')}<td>${badge(r[4],'amber')}</td><td>${link('Inspect','source',`data-source="${n}"`)}</td></tr>`).join('')}</tbody></table></div><div class="panel-foot"><span>Illustrative observations. No evacuation instruction or fire perimeter.</span>${link('View all evidence','evidence-library')}</div>`)}
 <div class="intelligence-footer">${link('What would resolve these questions?','collection-plan')}<span>Evidence review does not automatically change an incident’s status.</span></div></div>`;
}
