import {icon} from '../ui/icons.js';
import {e,badge,button,link,panel,empty,select} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {REGIONS} from '../data/fixtures.js';
import {incidentsFor,incidentCounts,isLimited} from '../data/model.js';
export function national(state,ui){const list=incidentsFor(state),limited=isLimited(state),region=ui.region;const regionList=(list||[]).filter(i=>i.region===region);const counts=incidentCounts(limited?null:regionList);
 return `<div class="route-stack"><div class="national-controls">${select('Region','region',REGIONS.map(r=>[r,r]),region)}${select('National layer','national-layer',[['incidents','Incident records'],['weather','Weather context'],['coverage','Information coverage']],ui.nationalLayer)}${button('Reset Portugal view','reset-national',{ico:'refresh'})}${button('Full-screen map','national-fullscreen',{ico:'expand'})}</div>
 <div class="national-main">${panel('Portugal map',`<div class="national-map-pad">${mapView({kind:'national',id:'national-map',height:534,limited,region,selectRegions:true})}</div>`,{cls:'national-map-panel',sub:'Reference geography; use the region selector to inspect sample records.'})}
 <div class="national-sidebar">${panel('Region details',limited?empty('Region data unavailable','No regional records were returned.'):`<div class="region-summary"><div class="region-name"><h2>${e(region)}</h2><div><strong>${counts.total}</strong><span>records</span></div></div>${ui.nationalLayer==='incidents'?`<div class="region-stats"><p><i class="dot amber"></i><strong>${counts.candidate}</strong> detection candidates</p><p><i class="dot green"></i><strong>${counts.confirmed}</strong> confirmed in exercise</p><p><i class="dot"></i><strong>${counts.monitored}</strong> monitored records</p></div>`:ui.nationalLayer==='weather'?`<div class="regional-weather">${icon('cloud')}<div><strong>Weather context only</strong><p>Sample regional conditions are not a spread forecast.</p><span>22 °C · light wind · illustrative</span></div></div>`:`<div class="region-stats"><p>${badge('Partial information','amber')}</p><p>Official-source connection unavailable in this demo.</p><p>Coverage gaps do not indicate safety.</p></div>`}${button('View regional incidents','regional-incidents',{tone:'soft-blue wide',ico:'arrow'})}</div>`)}
 ${panel('Key information',`<div class="regional-info"><div>${icon('clock')}<span><strong>Latest observation</strong><small>${limited?'Unavailable':'Sample snapshot · 7 Sept 2026'}</small></span></div><div>${icon('cloud')}<span><strong>Weather context</strong><small>${limited?'Unavailable':'Regional context · not incident evidence'}</small></span></div><div>${icon('database')}<span><strong>Source coverage</strong><small>${limited?'Unavailable':'Partial · official confirmation missing'}</small></span></div><div>${icon('alert')}<span><strong>Interpretation</strong><small>Markers are not fire perimeters or evacuation zones.</small></span></div></div>`)}</div></div>
 <div class="region-pills" aria-label="Regional selection">${REGIONS.map(r=>`<button type="button" data-action="select-region" data-region="${r}" class="region-pill ${r===region?'selected':''}" aria-pressed="${r===region}">${e(r)}<span>${limited?'—':list.filter(i=>i.region===r).length}</span></button>`).join('')}</div></div>`;
}
