import {icon} from '../ui/icons.js';
import {e,badge,button,link,panel,empty,select} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {tasksFor,taskCounts,incidentFor,isLimited,isReadonly} from '../data/model.js';
import {OWNERS} from '../data/fixtures.js';
const labels={all:'All tasks',attention:'Needs attention',progress:'In progress',waiting:'Waiting',completed:'Completed'};
const tones={attention:'red',progress:'blue',waiting:'neutral',completed:'green'};
export function operations(state,ui){const incident=incidentFor(state),tasks=tasksFor(state),counts=taskCounts(tasks),limited=isLimited(state),readonly=isReadonly(state);if(!incident)return empty('Incident not found','Choose an incident to manage.',button('Choose incident','choose-incident'));
 const shown=(tasks||[]).filter(t=>ui.taskTab==='all'||t.status===ui.taskTab);if(!shown.some(t=>t.id===ui.taskId))ui.taskId=shown[0]?.id||null;const selected=shown.find(t=>t.id===ui.taskId);
 return `<div class="route-stack"><div class="operations-metrics">${[['Information tasks',counts?.total],['Response actions',limited?null:0],['Protect / Recover',limited?null:0],['Decisions to review',counts?.attention]].map(([name,n])=>`<article><strong class="num">${n??'—'}</strong><span>${name}</span></article>`).join('')}</div>
 <div class="operations-main"><section class="panel task-list-panel"><div class="tabs" role="tablist" aria-label="Task status">${Object.entries(labels).map(([key,label])=>`<button type="button" role="tab" aria-selected="${key===ui.taskTab}" tabindex="${key===ui.taskTab?0:-1}" class="tab ${key===ui.taskTab?'active':''}" data-action="task-tab" data-tab="${key}">${label}<span class="tab-count">${counts?(key==='all'?counts.total:counts[key]):'—'}</span></button>`).join('')}</div><div class="panel-head"><h2>Tasks</h2><span class="small muted">${limited?'Unavailable':`${shown.length} ${shown.length===1?'item':'items'}`}</span></div>
 ${limited?empty('Tasks could not be loaded','Unknown task counts are not treated as zero.'):shown.length?`<div class="task-list">${shown.map((t,n)=>`<button type="button" class="task-row ${t.id===ui.taskId?'selected':''}" data-action="select-task" data-id="${e(t.id)}" aria-pressed="${t.id===ui.taskId}"><span class="task-number">${n+1}</span><span class="task-copy"><strong>${e(t.title)}</strong><small>${t.priority==='high'?'High priority':'Normal priority'} · ${t.due?'Due '+e(t.due)+' UTC':'No deadline'}</small><small>Assigned: ${e(t.owner)}</small></span>${badge(labels[t.status],tones[t.status])}${icon('chevron')}</button>`).join('')}</div>`:empty('No tasks in this status','Switch to another status to see the incident’s work.')}
 <div class="task-list-footer">${button('New task','new-task',{ico:'plus',tone:'small-btn',disabled:readonly})}<span>Changes stay in this local preview.</span></div></section>
 ${panel(selected?selected.title:'Task details',selected?`<div class="task-inspector"><div class="inspector-status">${badge(selected.priority==='high'?'High priority':'Normal priority',selected.priority==='high'?'red':'neutral')}${badge(labels[selected.status],tones[selected.status])}</div><p class="task-summary">${e(selected.summary)}</p><dl class="task-facts"><div>${icon('user')}<dt>Owner</dt><dd>${e(selected.owner)}</dd></div><div>${icon('clock')}<dt>Due</dt><dd>${selected.due?'7 Sept 2026, '+e(selected.due)+' UTC':'Not recorded'}</dd></div><div>${icon('alert')}<dt>Blocker</dt><dd>${e(selected.blocker)}</dd></div><div>${icon('pin')}<dt>Related incident</dt><dd>${e(incident.name)}</dd></div></dl>
 <div class="owner-editor"><label for="owner-select">Assign to</label>${select('Task owner','task-owner',OWNERS.map(o=>[o,o]),selected.owner)}${button('Update owner','assign-owner',{tone:'small-btn',disabled:readonly})}</div>
 <div class="task-note-area"><label for="task-note">Task note</label><textarea id="task-note" placeholder="Add a brief update…" maxlength="500" ${readonly?'disabled':''}></textarea>${selected.notes.length?`<p class="small">${selected.notes.length} saved ${selected.notes.length===1?'note':'notes'}</p>`:''}${readonly?'<p class="small muted">Read-only — note changes disabled.</p>':link('Save note','save-note')}</div>
 <div class="inspector-actions">${selected.status==='completed'?badge('Completed in preview','green'):button(selected.status==='progress'?'Mark as complete':selected.status==='waiting'?'Resume task':'Mark as in progress','task-transition',{tone:'primary',disabled:readonly,extra:`data-status="${selected.status==='progress'?'completed':'progress'}"`})}${button('More actions','task-more',{ico:'down'})}</div></div>`:empty('Select a task','The inspector shows the owner, blocker, and permitted next action.'),{cls:'task-inspector-panel'})}</div>
 <div class="operations-bottom">${panel('Recent activity',limited?empty('Activity unavailable','No timestamped activity was returned.'):`<div class="rows">${state.activity.slice(0,3).map(a=>`<div class="row activity-row">${icon('clock')}<time>${e(a.time)}</time><div class="row-main"><strong>${e(a.title)}</strong><small>${e(a.actor)}</small></div></div>`).join('')}</div><div class="panel-foot">${link('View full activity','activity')}</div>`)}
 ${panel('Task map',`<div class="task-map-pad">${mapView({id:'operations-map',title:incident.name,height:160,limited,legend:false})}</div>`,{action:button('Expand task map','expand-map',{ico:'expand',tone:'icon-button',extra:'data-kind="local"'})})}</div></div>`;
}
