import {icon} from '../ui/icons.js';
import {e,badge,button,link,panel,empty} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {incidentsFor,incidentCounts,isLimited} from '../data/model.js';
export function overview(state){const list=incidentsFor(state),counts=incidentCounts(list),limited=isLimited(state);
 const priorities=(list||[]).filter(i=>['lever','valongo','coelhoso','vinhais'].includes(i.id));
 const metrics=[['Detection candidates',counts?.candidate,'Need verification','red'],['Active exercise incidents',counts?.confirmed,'Confirmed in sample data','green'],['Escalations',counts?.high,'Need review','amber'],['Source outage',limited?null:1,'Official-source access','blue']];
 return `<div class="route-stack"><div class="metrics">${metrics.map(([label,n,sub,tone])=>`<article class="metric ${tone}"><div class="value num">${n??'—'}</div><h3>${label}</h3><p>${limited?'Information unavailable':sub}</p></article>`).join('')}</div>
 <div class="overview-main">${panel('Priority incidents',priorities.length?`<div class="rows">${priorities.map(i=>`<div class="row priority-row"><span class="flame-tile ${i.priority==='high'?'high':i.status}">${icon('flame')}</span><div class="row-main"><h3>${e(i.name)}</h3><p>${e(i.type)} · ${i.status==='monitored'?'No recent update':'Needs verification'}</p><small>${i.id==='lever'?'Observed 16 Aug 2026, 15:49 UTC':'Sample observation · 7 Sept 2026'}</small></div>${button('Review','open-incident',{tone:'soft-red small-btn',extra:`data-id="${e(i.id)}"`})}</div>`).join('')}</div>`:empty('Priorities unavailable','No incident records were returned.'),{action:link('View all','navigate','data-route="incidents"')})}
 ${panel('Portugal map',`<div class="overview-map-pad">${mapView({kind:'national',id:'overview-map',height:322,limited})}</div>`,{action:button('Expand national view','navigate',{tone:'icon-button',ico:'expand',extra:'data-route="national-awareness"'})})}</div>
 <div class="overview-bottom">${panel('Recent activity',limited?empty('Activity unavailable','No event timeline is available.'): `<div class="rows">${state.activity.slice(0,3).map(a=>`<div class="row activity-row"><span class="clock-dot">${icon('clock')}</span><time class="activity-time">${e(a.time)}</time><span>${e(a.title)}</span></div>`).join('')}</div>`,{action:link('View activity','activity')})}
 ${panel('System health',`<div class="panel-pad"><div class="health-part"><div class="stat-line"><span>Demo data sources</span><span>${limited?'Unavailable':'3/4'}</span></div><div class="progress-track"><div class="progress-fill" style="width:${limited?0:75}%"></div></div><p class="small">${limited?'No provider status was returned.':'One sample source is awaiting access.'}</p></div><div class="health-part"><div class="stat-line"><span>Preview application</span>${badge('Running locally','green')}</div><p class="small" style="margin-top:8px">This is not live operational health.</p></div></div>`,{action:link('Details','system-info')})}</div></div>`;
}
