import {e,badge,button,link,panel,empty,select} from '../ui/html.js';
import {sparkline,barChart} from '../ui/charts.js';
import {PERIODS} from '../data/fixtures.js';
import {isLimited} from '../data/model.js';
const tabs=[['decisions','Decision Summary'],['outcomes','Outcome Analysis'],['performance','System Performance'],['quality','Situation Quality']];
function performance(period,limited,compare){
 const cards=[['Map render time','1.4','s','Target < 3.0 s',sparkline(period.map,{label:'Sample map render time series'}),'−0.4 s vs comparison'],['API response p95','850','ms','Target < 1,000 ms',sparkline(period.api,{label:'Sample API response time series'}),'−90 ms vs comparison'],['Page availability',`${Math.round(period.successful/period.checks*1000)/10}`,'%','Successful preview route checks',`<div class="large-progress"><span style="width:${period.successful/period.checks*100}%"></span></div><p class="small muted">${period.successful} of ${period.checks} illustrative checks succeeded</p>`,'No live uptime is measured'],['Data freshness','2.1','h','Target < 4 h · sample source age','<div class="large-progress"><span style="width:52.5%"></span></div><p class="small muted">Sample median age · not a safety threshold</p>','−0.3 h vs comparison']];
 return `<div class="performance-grid">${cards.map(([title,value,unit,target,chart,delta])=>`<section class="panel performance-card"><div class="performance-card-head"><h2>${title}</h2>${badge(limited?'Not measured':'On target',limited?'neutral':'green')}</div><div class="performance-value">${limited?'—':value}<span>${limited?'':unit}</span></div><p>${limited?'Measurement unavailable':target}</p>${limited?'<div class="metric-unavailable">No samples returned.</div>':chart}${compare&&!limited?`<div class="comparison-note">${delta}</div>`:''}</section>`).join('')}</div>
 ${panel('Service status',`<div class="service-grid">${[['Event feeds','Operational'],['Map transport','Reference asset'],['Source availability','Degraded'],['Outcome service','Not connected']].map(([name,status])=>`<div><span>${name}</span>${badge(limited?'Unavailable':status,limited?'neutral':status==='Operational'?'green':status==='Degraded'?'red':'neutral')}</div>`).join('')}</div>`,{sub:'Illustrative service states. These are not measurements of your Vigia backend.'})}`;
}
function decisions(period,limited){if(limited)return panel('Decision activity',empty('Period results unavailable','No dated records were returned. No trend or zero result has been inferred.'));
 return `<div class="report-summary"><div><span class="eyebrow">PERIOD REVIEW</span><h2>${period.reviewed} reviews. ${period.open} still open.</h2><p>Illustrative workflow results—not measured protection outcomes.</p></div><div class="review-counts"><div><strong>${period.reviewed}</strong><span>Reviewed</span></div><div><strong>${period.resolved}</strong><span>Resolved</span></div><div><strong>${period.open}</strong><span>Open</span></div></div></div><div class="report-main">${panel('Reviews over time',barChart(period.series,period.labels)+`<div class="panel-foot"><span>${period.reviewed} sample reviews · ${e(period.label)}</span>${link('Inspect records','report-records')}</div>`,{sub:'Number of record reviews. Not confirmed incident outcomes.'})}${panel('Key insights',`<div class="insight-list"><div><i class="dot green"></i><strong>${period.resolved} reviews were resolved.</strong><p>These are workflow results in the demonstration dataset.</p></div><div><i class="dot amber"></i><strong>Confirmation remains a constraint.</strong><p>Official-source review is the largest illustrated category.</p></div><div><i class="dot"></i><strong>No live outcomes are measured.</strong><p>Review completion does not establish people protected.</p></div></div>`)}</div>
 ${panel('Why records needed review',`<div class="category-rows">${period.categories.map(([name,n])=>`<button type="button" data-action="category-detail" data-name="${e(name)}" class="category-row"><span>${e(name)}</span><div class="category-track"><i style="width:${n/period.reviewed*100}%"></i></div><strong>${n}</strong></button>`).join('')}</div>`,{action:link('Definitions','category-definitions')})}`;
}
function outcomes(limited){return panel('Measured live outcomes',`<div class="outcome-empty"><span class="outcome-icon">◎</span><div><h2>${limited?'Outcome data unavailable':'No live outcomes are measured in this preview.'}</h2><p>${limited?'No outcome response was returned. This is not a zero-outcome result.':'This standalone build demonstrates the interface. It is not connected to emergency operations or outcome measurements.'}</p><div class="outcome-actions">${button('Review measurement requirements','outcome-requirements',{tone:'soft-blue'})}${link('View exercise history','exercise-history')}</div></div></div><div class="outcome-stages"><span>Recorded action</span><b>→</b><span>Observed result</span><b>→</b><span>Reviewed outcome</span></div><div class="panel-foot">Exercise results and live results must remain separate.</div>`);}
function quality(limited){const qs=[['Freshness coverage','11 / 18',61,'Records with a recent sample observation.'],['Official confirmation','3 / 18',17,'Fictional exercise confirmations only.'],['Independent observation','Not measured',0,'Source independence has not been evaluated.'],['Affected-area geometry','Not established',0,'No incident perimeter is represented.']];return panel('Information quality',`<div class="quality-grid">${qs.map(([l,v,p,d])=>`<article><h3>${l}</h3><strong>${limited?'Unavailable':v}</strong><div class="progress-track"><div class="progress-fill" style="width:${limited?0:p}%;background:#3b80ba"></div></div><p>${limited?'No measurement returned.':d}</p>${link('Review definition','quality-definition',`data-name="${e(l)}"`)}</article>`).join('')}</div><div class="panel-foot">No composite confidence score. Missing coverage never means safe.</div>`);}
export function reports(state,ui){const p=PERIODS[ui.period]||PERIODS['24h'],limited=isLimited(state);return `<div class="route-stack"><div class="report-controls">${select('Report period','report-period',Object.entries(PERIODS).map(([k,v])=>[k,v.label]),ui.period)}${button(ui.compare?'Comparing periods':'Compare','compare',{ico:'compare',tone:ui.compare?'soft-blue':'',extra:`aria-pressed="${ui.compare}"`})}${button('Export','export-report',{ico:'download'})}</div><div class="tabs report-tabs" role="tablist" aria-label="Report views">${tabs.map(([k,l])=>`<button class="tab ${ui.reportTab===k?'active':''}" type="button" data-action="report-tab" data-tab="${k}" role="tab" aria-selected="${ui.reportTab===k}" tabindex="${ui.reportTab===k?0:-1}">${l}</button>`).join('')}</div><div class="report-view route-stack" data-report-view="${e(ui.reportTab)}">${ui.reportTab==='performance'?performance(p,limited,ui.compare):ui.reportTab==='decisions'?decisions(p,limited):ui.reportTab==='outcomes'?outcomes(limited):quality(limited)}</div><div class="report-notice">Illustrative metrics for frontend review. No live performance, response outcome, or safety claim is made.</div></div>`;}
