import { projectLocation } from './location-truth.mjs';
import { stableId } from './contracts.mjs';

const outside=(person)=>['OUT','REHABILITATION','DEMOBILIZED'].includes(person?.operationalState);
const advisory=(rule,crew,inputs,owner,verification,now)=>({schemaVersion:'vigia.crew-integrity-advisory.v1',advisoryId:stableId('crew-advisory',rule,crew.crewId,inputs),rule,affectedCrewId:crew.crewId,inputs,age:inputs.ageMs??null,uncertainty:inputs.uncertainty??null,requiredVerification:verification,owner:owner??crew.supervisorId??crew.leaderId??null,state:'OPEN',createdAt:now.toISOString(),suppression:null});

export function crewIntegrityAdvisories(state,{now=new Date(),separationThresholdM=150,separationThresholdMs=120_000,locationStaleMs=300_000,progressOverdueMs=600_000,entryDurationMs=1_800_000,airUpdateMs=900_000}={}){
  const result=[];
  for(const crew of Object.values(state.crews??{})){
    const members=(crew.memberIds??[]).map((id)=>state.persons[id]).filter(Boolean),officer=state.persons[crew.leaderId],notOutside=members.filter((person)=>!outside(person));
    if(outside(officer)&&notOutside.length)result.push(advisory('OFFICER_EXITED_MEMBER_UNCONFIRMED',crew,{officerId:officer.personId,unconfirmedMemberIds:notOutside.map((p)=>p.personId)},crew.supervisorId,'Attributable exit-checkpoint confirmation for every member.',now));
    const projected=members.map((person)=>({person,raw:state.locations?.[person.personId]??null,location:projectLocation(state.locations?.[person.personId],{now,staleAfterMs:locationStaleMs})}));
    const stale=projected.filter(({raw,location})=>raw&&['STALE','UNKNOWN'].includes(location.verificationState));if(stale.length)result.push(advisory('CONTACT_OR_MOVEMENT_LOST',crew,{personIds:stale.map(({person})=>person.personId),ageMs:Math.max(...stale.map(({location})=>location.ageMs??0)),uncertainty:stale.map(({location})=>location.uncertainty),sources:stale.map(({raw})=>raw.source)},crew.leaderId,'Attributable radio, officer, checkpoint, or qualified device location update.',now));
    for(let left=0;left<projected.length;left+=1)for(let right=left+1;right<projected.length;right+=1){const a=projected[left],b=projected[right],ac=a.location.geometry?.coordinates,bc=b.location.geometry?.coordinates;if(!Array.isArray(ac)||!Array.isArray(bc))continue;const mean=(ac[1]+bc[1])*Math.PI/360,distance=Math.round(Math.hypot((ac[0]-bc[0])*111_320*Math.cos(mean),(ac[1]-bc[1])*111_320)),uncertaintyM=(a.raw?.horizontalUncertaintyM??0)+(b.raw?.horizontalUncertaintyM??0),minimumSeparationM=Math.max(0,distance-uncertaintyM);if(minimumSeparationM>separationThresholdM&&Math.min(a.location.ageMs??Infinity,b.location.ageMs??Infinity)<separationThresholdMs)result.push(advisory('CREW_SEPARATION',crew,{personIds:[a.person.personId,b.person.personId],distanceM:distance,minimumSeparationM,thresholdM:separationThresholdM,uncertainty:[a.location.uncertainty,b.location.uncertainty]},crew.leaderId,'Officer confirmation of crew integrity or corrected location reports.',now));}
    const evacuation=Object.values(state.evacuations??{}).find((item)=>item.crewIds?.includes(crew.crewId)&&['CREW_ACKNOWLEDGED','CREW_WITHDRAWING','MEMBERS_EXIT_CONFIRMED'].includes(item.state));if(evacuation&&notOutside.length)result.push(advisory('EVACUATION_NOT_ALL_OUTSIDE',crew,{evacuationId:evacuation.evacuationId,acknowledged:true,unconfirmedMemberIds:notOutside.map((p)=>p.personId)},crew.supervisorId,'Each member must cross an attributable exit checkpoint; acknowledgement is not exit.',now));
    const assignment=state.assignments?.[crew.assignmentId];if(assignment&&crew.operationalAreaId&&assignment.operationalAreaId&&crew.operationalAreaId!==assignment.operationalAreaId)result.push(advisory('AREA_CHANGE_WITHOUT_ASSIGNMENT',crew,{assignmentId:assignment.assignmentId,assignedOperationalAreaId:assignment.operationalAreaId,reportedOperationalAreaId:crew.operationalAreaId},assignment.supervisorId,'Supervisor confirmation and attributable assignment update.',now));if(assignment?.lastProgressAt&&now-Date.parse(assignment.lastProgressAt)>progressOverdueMs)result.push(advisory('PROGRESS_REPORT_OVERDUE',crew,{assignmentId:assignment.assignmentId,ageMs:now-Date.parse(assignment.lastProgressAt),intervalMs:progressOverdueMs},assignment.supervisorId,'Attributable progress report.',now));
    for(const person of members){const entry=state.accountability?.[person.personId]?.entryTime;if(entry&&now-Date.parse(entry)>entryDurationMs)result.push(advisory('ENTRY_DURATION_EXCEEDED',crew,{personId:person.personId,ageMs:now-Date.parse(entry),policyMs:entryDurationMs},crew.leaderId,'Officer verification of location, welfare, air, and withdrawal plan.',now));const air=state.accountability?.[person.personId]?.airStatusAt;if(air&&now-Date.parse(air)>airUpdateMs)result.push(advisory('AIR_STATUS_OVERDUE',crew,{personId:person.personId,ageMs:now-Date.parse(air),policyMs:airUpdateMs},crew.leaderId,'Attributable air-status update where air tracking is configured.',now));}
  }
  return result;
}

export function commandOrganizationAdvisories(state,{now=new Date(),maxDirectReports=7}={}){
  const organization=state.organization??{},roles=Array.isArray(organization.commandRoles)?organization.commandRoles:Object.values(organization.commandRoles??{}),result=[];
  for(const role of roles){const directReportIds=role.directReportIds??[];if(directReportIds.length<=maxDirectReports)continue;result.push({schemaVersion:'vigia.command-organization-advisory.v1',advisoryId:stableId('command-advisory','SPAN_OF_CONTROL_WARNING',role.commandRoleId??role.role,role.directReportIds),rule:'SPAN_OF_CONTROL_WARNING',affectedCrewId:null,affectedCommandRoleId:role.commandRoleId??role.role??null,inputs:{directReportIds,count:directReportIds.length,policyMaximum:maxDirectReports},age:null,uncertainty:null,requiredVerification:'Incident Commander review of the command organization and supervisory capacity.',owner:role.supervisorId??organization.incidentCommanderId??null,state:'OPEN',createdAt:now.toISOString(),suppression:null});}
  return result;
}

export function maydayTimers(mayday,{now=new Date()}={}){return Object.entries(mayday?.timers??{}).map(([kind,timer])=>({...timer,kind,overdue:!timer.completedAt&&Date.parse(timer.dueAt)<now.getTime(),state:timer.completedAt?'COMPLETED':Date.parse(timer.dueAt)<now.getTime()?'OVERDUE':'OPEN'}));}
