import { member,ROLES } from './contracts.mjs';
import { commandOrganizationAdvisories,crewIntegrityAdvisories,maydayTimers } from './advisories.mjs';
import { projectLocation } from './location-truth.mjs';
import { maydayPriorityContract } from './targeting.mjs';

const values=(map)=>Object.values(map??{});
export function roleProjection(state,role,{subjectId=null,now=new Date()}={}){
  member(role,ROLES,'invalid_incident_command_role');
  const locations=Object.fromEntries(Object.entries(state.locations??{}).map(([personId,report])=>[personId,projectLocation(report,{now})]));
  const advisories=[...crewIntegrityAdvisories(state,{now}),...commandOrganizationAdvisories(state,{now})],maydays=values(state.maydays).map((item)=>({...item,timers:maydayTimers(item,{now})})),priority=maydayPriorityContract(state,role);
  const common={schemaVersion:'vigia.incident-command-role-projection.v1',incidentId:state.incidentId,role,generatedAt:now.toISOString(),dataFreshness:{lastUpdatedAt:state.lastUpdatedAt,ageMs:state.lastUpdatedAt?Math.max(0,now-Date.parse(state.lastUpdatedAt)):null},operatingState:state.operatingState,priority,maydays,criticalChanges:values(state.criticalChanges),unknowns:advisories.map((item)=>({rule:item.rule,crewId:item.affectedCrewId,owner:item.owner,requiredVerification:item.requiredVerification}))};
  if(role==='FIREFIGHTER'){const person=state.persons?.[subjectId],crew=person?state.crews?.[person.currentCrewId]:null,recipientIds=[subjectId,crew?.crewId].filter(Boolean);return{...common,person:person?{...person,accountability:state.accountability?.[subjectId],location:locations[subjectId]}:null,crew,location:subjectId?locations[subjectId]:null,assignment:crew?state.assignments?.[crew.assignmentId]:null,orders:values(state.orders).filter((order)=>(order.intendedRecipients??[]).some((id)=>recipientIds.includes(id))),evacuations:values(state.evacuations).filter((item)=>item.crewIds?.includes(crew?.crewId)),hazards:values(state.hazards).filter((item)=>!item.operationalAreaId||item.operationalAreaId===crew?.operationalAreaId),criticalChanges:values(state.criticalChanges).filter((item)=>(item.targeting?.recipients??[]).some((id)=>recipientIds.includes(id)))};}
  if(role==='COMPANY_OFFICER'){const crew=state.crews?.[subjectId];return{...common,crew,members:(crew?.memberIds??[]).map((id)=>({...state.persons[id],accountability:state.accountability?.[id],location:locations[id]})),assignment:crew?state.assignments?.[crew.assignmentId]:null,advisories:advisories.filter((item)=>item.affectedCrewId===subjectId),orders:values(state.orders).filter((order)=>(order.intendedRecipients??[]).includes(subjectId)),evacuations:values(state.evacuations).filter((item)=>item.crewIds?.includes(subjectId)),parRequests:values(state.parRequests),hazards:values(state.hazards).filter((item)=>!item.operationalAreaId||item.operationalAreaId===crew?.operationalAreaId)};}
  if(role==='MAYDAY_RESCUE')return{...common,rescueOrganizations:values(state.rescueOrganizations),distressedPersons:maydays.map((item)=>({...state.persons[item.personId],accountability:state.accountability?.[item.personId],location:locations[item.personId],maydayId:item.maydayId})),searchSectors:values(state.searchSectors),resources:values(state.resources).filter((item)=>item.assignmentKind==='RESCUE'||item.qualification?.includes?.('RIT')),persons:values(state.persons).map((person)=>({...person,location:locations[person.personId]})),parRequests:values(state.parRequests),evacuations:values(state.evacuations)};
  if(role==='ACCOUNTABILITY')return{...common,persons:values(state.persons).map((person)=>({...person,location:locations[person.personId],accountability:state.accountability?.[person.personId]})),crews:values(state.crews),parRequests:values(state.parRequests),evacuations:values(state.evacuations),advisories};
  if(role==='DISPATCH_EOC')return{...common,organization:state.organization,resources:values(state.resources),resourceRequests:values(state.resourceRequests),orders:values(state.orders),waterStates:values(state.waterStates)};
  return{...common,incident:state.incident,organization:state.organization,objectives:values(state.objectives),assignments:values(state.assignments),areas:values(state.areas),persons:values(state.persons).map((person)=>({...person,accountability:state.accountability?.[person.personId],location:locations[person.personId]})),crews:values(state.crews),resources:values(state.resources),resourceRequests:values(state.resourceRequests),orders:values(state.orders),parRequests:values(state.parRequests),evacuations:values(state.evacuations),advisories,hazards:values(state.hazards),waterSources:values(state.waterSources),waterStates:values(state.waterStates),rescueOrganizations:values(state.rescueOrganizations),decisions:values(state.decisions)};
}
