import { EVACUATION_STATES,MAYDAY_STATES,ORDER_STATES,PERSON_STATES,RESOURCE_STATES,member,required } from './contracts.mjs';

const order={CREATED:['AUTHORIZED','CANCELLED','EXPIRED'],AUTHORIZED:['SENT','CANCELLED','EXPIRED'],SENT:['DELIVERED','FAILED','CANCELLED','EXPIRED'],DELIVERED:['ACKNOWLEDGED','FAILED','CANCELLED','EXPIRED'],ACKNOWLEDGED:['ACTION_UNDERWAY','FAILED','CANCELLED','EXPIRED'],ACTION_UNDERWAY:['COMPLETED','FAILED','CANCELLED','EXPIRED'],COMPLETED:[],FAILED:[],CANCELLED:[],EXPIRED:[]};
const resource={REQUESTED:['APPROVED','OUT_OF_SERVICE'],APPROVED:['DISPATCHED','OUT_OF_SERVICE'],DISPATCHED:['EN_ROUTE','OUT_OF_SERVICE'],EN_ROUTE:['ARRIVED','OUT_OF_SERVICE'],ARRIVED:['CHECKED_IN','OUT_OF_SERVICE'],CHECKED_IN:['STAGED','ASSIGNED','AVAILABLE','OUT_OF_SERVICE'],STAGED:['ASSIGNED','AVAILABLE','DEMOBILIZED'],ASSIGNED:['WORKING','REASSIGNED','OUT_OF_SERVICE'],WORKING:['REHABILITATION','AVAILABLE','REASSIGNED','OUT_OF_SERVICE'],REHABILITATION:['AVAILABLE','OUT_OF_SERVICE'],AVAILABLE:['ASSIGNED','REASSIGNED','DEMOBILIZED','OUT_OF_SERVICE'],OUT_OF_SERVICE:['AVAILABLE','DEMOBILIZED'],REASSIGNED:['ASSIGNED','STAGED','OUT_OF_SERVICE'],DEMOBILIZED:[]};
const mayday={ACTIVE:['ACKNOWLEDGED'],ACKNOWLEDGED:['RESCUE_ASSIGNED'],RESCUE_ASSIGNED:['RESCUE_ENTRY'],RESCUE_ENTRY:['PHYSICALLY_RECOVERED'],PHYSICALLY_RECOVERED:[]};
const evacuation={ORDER_AUTHORIZED:['ORDER_SENT'],ORDER_SENT:['ORDER_DELIVERED'],ORDER_DELIVERED:['CREW_ACKNOWLEDGED'],CREW_ACKNOWLEDGED:['CREW_WITHDRAWING'],CREW_WITHDRAWING:['MEMBERS_EXIT_CONFIRMED'],MEMBERS_EXIT_CONFIRMED:['CREW_REUNITED'],CREW_REUNITED:['PAR_CONFIRMED'],PAR_CONFIRMED:['COMPLETE'],COMPLETE:[]};

function transition(current,next,graph,code){required(current,`${code}_current_required`);required(next,`${code}_next_required`);if(!(graph[current]??[]).includes(next))throw new Error(`invalid_${code}_transition:${current}:${next}`);return next;}
export function transitionOrder(current,next,{completionEvidence}={}){member(current,ORDER_STATES,'invalid_order_state');member(next,ORDER_STATES,'invalid_order_state');if(next==='COMPLETED'&&!completionEvidence)throw new Error('order_completion_evidence_required');return transition(current,next,order,'order');}
export function transitionResource(current,next){member(current,RESOURCE_STATES,'invalid_resource_state');return transition(current,next,resource,'resource');}
export function transitionMayday(current,next,{physicalRecoveryEvidence}={}){member(current,MAYDAY_STATES,'invalid_mayday_state');if(next==='PHYSICALLY_RECOVERED'&&(!physicalRecoveryEvidence?.checkpointId||!physicalRecoveryEvidence?.confirmedBy))throw new Error('mayday_physical_recovery_evidence_required');return transition(current,next,mayday,'mayday');}
export function transitionEvacuation(current,next,{allMembersExited,crewReunited,parConfirmed}={}){member(current,EVACUATION_STATES,'invalid_evacuation_state');if(next==='MEMBERS_EXIT_CONFIRMED'&&!allMembersExited)throw new Error('all_member_exit_confirmation_required');if(next==='CREW_REUNITED'&&!crewReunited)throw new Error('crew_reunion_evidence_required');if(next==='PAR_CONFIRMED'&&!parConfirmed)throw new Error('par_confirmation_required');return transition(current,next,evacuation,'evacuation');}
export function transitionPerson(current,next,{exitCheckpointEvidence}={}){member(current,PERSON_STATES,'invalid_person_state');member(next,PERSON_STATES,'invalid_person_state');if(next==='OUT'&&!exitCheckpointEvidence)throw new Error('attributable_exit_checkpoint_required');if(current==='MAYDAY'&&next!=='OUT')throw new Error('mayday_person_must_recover_through_exit');return next;}
export const transitionGraphs={order,resource,mayday,evacuation};
