import { mkdir,writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { operatorOpen } from '../operator_open.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),base='http://127.0.0.1:4177';
async function json(url){const response=await fetch(url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(5_000)});if(!response.ok)throw new Error(`rehearsal_preflight_http_${response.status}:${new URL(url).pathname}`);return response.json();}
const [health,release]=await Promise.all([json(`${base}/api/v10/health`),json(`${base}/api/v10/release`)]),preparedAt=new Date().toISOString(),directory=path.join(root,'.tmp/operator-rehearsal',preparedAt.replace(/[:.]/g,'-'));
const pack={schemaVersion:'vigia.supervised-operator-rehearsal.v1',preparedAt,release:{releaseId:release.releaseId,codeStateHash:release.codeStateHash,contracts:release.contracts},mode:'SUPERVISED_SHADOW_READ_ONLY',truthBoundary:['Live cases retain their canonical live labels.','Historical cases are used only through Replay and remain explicitly historical.','No fixture, simulated participant, or facilitator observation is recorded as live evidence.'],participants:['incident command','dispatch/EOC','wildfire intelligence','prevention/fuels','utility or regional emergency management'],tasks:[{id:'top-incident',route:'Overview',prompt:'Identify the incident requiring attention first.',targetSeconds:60},{id:'situation',route:'Detect',prompt:'Explain the current Situation.'},{id:'truth-boundary',route:'Detect',prompt:'Distinguish physical evidence from report-only evidence.'},{id:'main-unknown',route:'Detect',prompt:'Identify the decision-blocking unknown.'},{id:'next-evidence',route:'Detect',prompt:'Identify the Next-Best Evidence.'},{id:'what-changed',route:'Overview',prompt:'Explain What Changed.'},{id:'provenance',route:'Evidence',prompt:'Open provenance and explain why the assessment is bounded.',targetSeconds:90},{id:'handoff',route:'Handoff',prompt:'Create and review a Shift Handoff.',targetSeconds:300},{id:'degraded-recovery',route:'Detect',prompt:'Recover the task when the map or a source is explicitly degraded.'}],gate:{requiredSessions:5,requiredDomainPractitioners:3,minimumCriticalCompletionRate:0.8,maximumDangerousMisinterpretations:0,maximumMedianTopIncidentSeconds:60,maximumMedianWhySeconds:90,maximumHandoffSeconds:300,minimumAverageClarity:4,minimumAverageShadowTrust:4},resultState:'AWAITING_REAL_PARTICIPANTS',healthAtPreparation:{ok:health.ok??true,releaseId:health.releaseId??release.releaseId},facilitator:['Open Settings → Supervised operator rehearsal.','Start a pilot session before the first task.','Use one explicit task marker per task.','Record only direct participant behavior and ratings.','Export both JSON and CSV before ending the session.','Stop and label any dangerous truth confusion; do not coach through it as a pass.']};
await mkdir(directory,{recursive:true});await writeFile(path.join(directory,'session-pack.json'),`${JSON.stringify(pack,null,2)}\n`,{mode:0o600});const opened=await operatorOpen();console.log(JSON.stringify({state:'READY_FOR_REAL_SUPERVISED_SESSION',releaseId:release.releaseId,pack:path.relative(root,path.join(directory,'session-pack.json')),operator:opened.origin}));
