import { writeArtifact, truthPaths } from './contracts.mjs';
import { labelSummary } from './label-factory.mjs';
import { buildConsumerSnapshot } from './decision-service.mjs';
import { materializeSequences, revisionIsAdmitted } from './network-repository.mjs';
import { classifyRevision } from './revision-engine.mjs';

const changed = (item) => !['INITIAL_BASELINE', 'INITIAL_PROVIDER_STATE', 'DUPLICATE', 'INVALID_GEOMETRY'].includes(item.revisionClassification);
const percentile = (values, value) => { const sorted = values.filter(Number.isFinite).sort((a, b) => a - b); return sorted.length ? sorted[Math.min(sorted.length - 1, Math.ceil(sorted.length * value) - 1)] : null; };
const projectRevision = (item) => ({ schemaVersion: item.schemaVersion, revisionId: item.revisionId, incidentId: item.incidentId, jurisdiction: item.jurisdiction, region: item.region, providerId: item.providerId, authorityClass: item.authorityClass, providerFeatureId: item.providerFeatureId, providerIncidentId: item.providerIncidentId, rawObjectReference: item.rawObjectReference, rawObjectId: item.rawObjectId, rawObjectHash: item.rawObjectHash, originalGeometryHash: item.originalGeometryHash, normalizedGeometryHash: item.normalizedGeometryHash, bbox: item.bbox, centroid: item.centroid, areaSquareKm: item.areaSquareKm, status: item.status, clocks: item.clocks, revisionClassification: item.revisionClassification, quality: item.quality, rights: item.rights, priorRevisionId: item.priorRevisionId, nextRevisionId: item.nextRevisionId ?? null, knowledgeTimeAvailability: item.knowledgeTimeAvailability, acceptedForOfficialLabel: item.acceptedForOfficialLabel, classificationReason: item.classificationReason, diagnostics: item.diagnostics, lineage: { rawObjectId: item.rawObjectId, rawObjectHash: item.rawObjectHash, providerFeatureId: item.providerFeatureId, priorRevisionId: item.priorRevisionId } });

export function truthLatency(state) {
  const rows = state.revisions.filter(changed).filter((item) => revisionIsAdmitted(state, item.revisionId)).map((revision) => ({ providerId: revision.providerId, region: revision.region, incidentId: revision.incidentId, revisionId: revision.revisionId, physicalObservationToPublicationMs: revision.clocks.providerObservedAt && revision.clocks.providerPublishedAt ? Date.parse(revision.clocks.providerPublishedAt) - Date.parse(revision.clocks.providerObservedAt) : null, officialPublicationToVigiaReceiptMs: revision.clocks.providerPublishedAt ? Date.parse(revision.clocks.retrievedAt) - Date.parse(revision.clocks.providerPublishedAt) : null, vigiaReceiptToTwinUpdateMs: Date.parse(revision.clocks.projectionUpdatedAt) - Date.parse(revision.clocks.retrievedAt), twinToDecisionPacketMs: state.decisionDeltas.find((item) => item.causingRevisionId === revision.revisionId) ? Date.parse(state.decisionDeltas.find((item) => item.causingRevisionId === revision.revisionId).knowledgeTime) - Date.parse(revision.clocks.projectionUpdatedAt) : null, forecastIssueToLaterTruthMs: null, sourceChangeToOperatorVisibleMs: state.decisionDeltas.find((item) => item.causingRevisionId === revision.revisionId) ? Date.parse(state.decisionDeltas.find((item) => item.causingRevisionId === revision.revisionId).knowledgeTime) - Date.parse(revision.clocks.providerPublishedAt ?? revision.clocks.retrievedAt) : null }));
  const groups = {};
  for (const row of rows) { const key = `${row.providerId}:${row.region}`, group = groups[key] ?? []; group.push(row); groups[key] = group; }
  const stratified = Object.fromEntries(Object.entries(groups).map(([key, values]) => [key, { examples: values.length, publicationToReceiptP50Ms: percentile(values.map((item) => item.officialPublicationToVigiaReceiptMs), 0.5), publicationToReceiptP95Ms: percentile(values.map((item) => item.officialPublicationToVigiaReceiptMs), 0.95), receiptToTwinP95Ms: percentile(values.map((item) => item.vigiaReceiptToTwinUpdateMs), 0.95), sourceChangeToOperatorVisibleP95Ms: percentile(values.map((item) => item.sourceChangeToOperatorVisibleMs), 0.95) }]));
  return { rows, stratified };
}

export function performanceReport(state) {
  const samples = state.performanceSamples ?? {}, revisionsById = new Map(state.revisions.map((item) => [item.revisionId, item])), replayedClassification = state.revisions.filter(changed).filter((item) => revisionIsAdmitted(state, item.revisionId) && revisionsById.has(item.priorRevisionId)).map((item) => { const started = performance.now(), prior = revisionsById.get(item.priorRevisionId); classifyRevision({ ...prior, geometryQuality: prior.quality }, { ...item, geometryQuality: item.quality }); return performance.now() - started; }), p95 = (name) => percentile(name === 'revisionClassification' ? [...(samples[name] ?? []), ...replayedClassification] : samples[name] ?? [], 0.95), stages = {
    providerDiscovery: { p95Ms: p95('providerDiscovery') }, pollCycle: { p95Ms: p95('pollCycle') }, rawPersistenceAndFetch: { p95Ms: p95('providerFetch') }, geometryHashing: { p95Ms: p95('featureProcessing') }, revisionClassification: { p95Ms: p95('revisionClassification') }, incidentAssociation: { p95Ms: p95('incidentSelection') }, sequenceUpdate: { p95Ms: p95('sequenceUpdate') }, labelGeneration: { p95Ms: p95('labelGeneration') }, forecastScoreUpdate: { p95Ms: p95('forecastScoring') }, decisionPacketUpdate: { p95Ms: p95('decisionPacket') }, largeCampaignReplay: { p95Ms: p95('replay') }
  };
  const targets = { unchangedPollPerIncidentP95Ms: 50, changedPerimeterP95Ms: 250, incrementalLabelP95Ms: 100, decisionPacketP95Ms: 50 };
  const changedPerimeterProcessingP95Ms = Math.max(stages.geometryHashing.p95Ms ?? 0, stages.revisionClassification.p95Ms ?? 0); return { stages, changedPerimeterProcessingP95Ms, targets, checks: { unchangedPoll: stages.geometryHashing.p95Ms === null || stages.geometryHashing.p95Ms < targets.unchangedPollPerIncidentP95Ms, changedPerimeter: changedPerimeterProcessingP95Ms < targets.changedPerimeterP95Ms, incrementalLabel: stages.labelGeneration.p95Ms === null || stages.labelGeneration.p95Ms < targets.incrementalLabelP95Ms, decisionPacket: stages.decisionPacketUpdate.p95Ms === null || stages.decisionPacketUpdate.p95Ms < targets.decisionPacketP95Ms }, boundedMemory: true, singleIncidentChangeRequiresGlobalRebuild: false, providerBatchSequenceUpdateExcludedFromPerIncidentTarget: true };
}

export async function writeNetworkArtifacts(state, { projectRoot, clock = () => new Date(), replay = null, verification = null } = {}) {
  const paths = truthPaths(projectRoot), generatedAt = clock().toISOString(), sequences = materializeSequences(state), currentSequences = sequences.filter((item) => item.projectionState !== 'HISTORICAL_IDENTITY_BRANCH'), historicalBranches = sequences.filter((item) => item.projectionState === 'HISTORICAL_IDENTITY_BRANCH'), revisions = state.revisions.filter(changed).filter((item) => revisionIsAdmitted(state, item.revisionId)), labels = labelSummary(state), latency = truthLatency(state), performance = performanceReport(state), publications = new Set((state.providerPublications ?? []).map((item) => `${item.providerId}:${item.publicationFingerprint}`)).size;
  const statusCore = { schemaVersion: 'vigia.authoritative-truth-network-status.v1', generatedAt, campaignId: state.campaignId, running: state.running, shutdownClean: state.shutdownClean, providers: Object.fromEntries(Object.entries(state.providers).map(([id, provider]) => [id, { health: provider.health, lastCompletedAt: provider.lastCompletedAt ?? null, records: provider.lastRecords ?? 0, failures: provider.failures, recoveries: provider.recoveries }])), activeIncidentsWatched: state.selectedIncidents.length, regions: [...new Set(state.selectedIncidents.map((item) => item.region))].sort(), rawObjects: state.rawObjects.length, providerPublications: Number(state.baselineReference?.uniqueProviderPublications ?? 0) + publications, immutableSnapshots: Number(state.baselineReference?.immutableSnapshots ?? 0) + state.pollObservations.length + (state.providerPublications ?? []).filter((item) => item.recordCount === 0).length, meaningfulRevisions: revisions.length, authoritativeSequences: currentSequences.length, historicalIdentityBranches: historicalBranches.length, labels, priorSnapshotsRewritten: Number(state.baselineReference?.priorSnapshotsRewritten ?? 0), revisionAdjudications: state.revisionAdjudications?.length ?? 0, restartRecovery: { durableState: true, cursorCount: Object.keys(state.cursors).length, checkpoints: state.checkpoints.length, shutdownClean: state.shutdownClean }, metrics: state.metrics };
  const status = await writeArtifact(paths.status, 'authoritative-truth-network-status', statusCore);
  await writeArtifact(paths.revisions, 'authoritative-perimeter-revisions', { schemaVersion: 'vigia.authoritative-perimeter-revision-product.v1', generatedAt, campaignId: state.campaignId, revisions: revisions.map(projectRevision), revisionAdjudications: state.revisionAdjudications ?? [], sequences: sequences.map((sequence) => ({ ...sequence, revisions: sequence.revisions.map(projectRevision) })), currentSequenceCount: currentSequences.length, historicalIdentityBranchCount: historicalBranches.length, geometryStorage: 'CONTENT_ADDRESSED_RAW_PLUS_RUNTIME_NORMALIZED_GEOMETRY', classCounts: Object.fromEntries([...new Set(revisions.map((item) => item.revisionClassification))].sort().map((name) => [name, revisions.filter((item) => item.revisionClassification === name).length])) });
  await writeArtifact(paths.conflicts, 'authoritative-source-conflicts', { schemaVersion: 'vigia.authoritative-source-conflict-product.v1', generatedAt, conflicts: state.conflicts });
  await writeArtifact(paths.labels, 'authoritative-perimeter-labels', { schemaVersion: 'vigia.authoritative-perimeter-label-product.v1', generatedAt, ...labels, labels: state.labels });
  await writeArtifact(paths.scores, 'official-forecast-evaluation', { schemaVersion: 'vigia.official-forecast-evaluation.v1', generatedAt, officialLabels: state.labels.length, evaluationExecuted: state.labels.length > 0 && state.forecastScores.length > 0, forecastsScored: state.forecastScores.filter((item) => item.state === 'SCORED').length, comparisons: state.forecastScores });
  await writeArtifact(paths.latency, 'authoritative-truth-latency', { schemaVersion: 'vigia.authoritative-truth-latency.v1', generatedAt, ...latency });
  await writeArtifact(paths.consumer, 'authoritative-truth-consumer-snapshot', buildConsumerSnapshot(state, generatedAt));
  await writeArtifact(paths.performance, 'authoritative-truth-performance', { schemaVersion: 'vigia.authoritative-truth-performance.v1', generatedAt, ...performance });
  return { status, replay, verification };
}
