import { fingerprint } from './contracts.mjs';
import { sequenceFor } from './identity.mjs';
import { revisionIsAdmitted } from './network-repository.mjs';

const byId = (state) => new Map(state.revisions.map((item) => [item.revisionId, item]));
const labelsFor = (state, revisionId) => state.labels.filter((item) => item.issueRevisionId === revisionId || item.laterRevisionId === revisionId);

function decisionPacket(state, revision, prior, at) {
  const labels = labelsFor(state, revision.revisionId), sequence = sequenceFor(state, revision.providerId, revision.incidentId), conflict = state.conflicts.find((item) => item.objects.some((object) => object.incidentId === revision.incidentId));
  const facts = [{ kind: 'OFFICIAL_PERIMETER', revisionId: revision.revisionId, authorityClass: revision.authorityClass, geometryHash: revision.normalizedGeometryHash, availableToVigiaAt: revision.clocks.availableToVigiaAt }], evidenceDebt = [];
  if (!labels.length) evidenceDebt.push('NEAR_TERM_OFFICIAL_LABEL_UNAVAILABLE'); if (conflict?.resolutionState === 'ABSTAIN_UNRESOLVED') evidenceDebt.push('OFFICIAL_SOURCE_CONFLICT_UNRESOLVED');
  const core = { schemaVersion: 'vigia.authoritative-truth-decision-packet.v1', incidentId: revision.incidentId, knowledgeTime: at, currentOfficialPerimeter: facts[0], perimeterAuthority: revision.providerId, priorOfficialPerimeterRevisionId: prior?.revisionId ?? null, facts, evidenceDebt, hypotheses: [{ id: 'OFFICIAL_PERIMETER_CURRENT', state: 'SUPPORTED' }, { id: 'ACTIVE_GEOMETRY_PROGRESSION', state: revision.revisionClassification === 'NORMAL_PROGRESSION' ? 'SUPPORTED' : 'UNKNOWN' }], forecastReadiness: sequence.revisionIds.length >= 2 && !conflict ? 'SHADOW_EVALUATION_READY' : 'INSUFFICIENT_OR_CONFLICTED_TRUTH', impactChanges: 'RECALCULATION_REQUIRED', decisionsUnblocked: labels.length ? ['SCORE_PREISSUED_SHADOW_FORECAST'] : [], decisionsBlocked: ['PUBLIC_WARNING', 'RESOURCE_DISPATCH', 'EVACUATION_ORDER', 'ROAD_CLOSURE', 'LEGAL_STATUS_CHANGE'], actionsSuperseded: [], operatorAttention: ['CORRECTION', 'MERGE', 'SPLIT', 'INCIDENT_REASSOCIATION', 'UNKNOWN_CHANGE'].includes(revision.revisionClassification), authorityBoundary: 'NO_CONSEQUENTIAL_EXTERNAL_ACTION', causingRevisionId: revision.revisionId, conflictId: conflict?.conflictId ?? null };
  return { ...core, fingerprint: fingerprint('authoritative-truth-decision-packet', core) };
}

export function updateDecisionPackets(state, revisions, at) {
  const revisionsById = byId(state), deltas = [];
  for (const revision of revisions.filter((item) => !['INITIAL_BASELINE', 'INITIAL_PROVIDER_STATE', 'DUPLICATE', 'INVALID_GEOMETRY', 'CLOCK_ANOMALY'].includes(item.revisionClassification))) {
    if (!revisionIsAdmitted(state, revision.revisionId)) continue; const prior = revisionsById.get(revision.priorRevisionId), before = prior ? decisionPacket(state, prior, revisionsById.get(prior.priorRevisionId), prior.clocks.projectionUpdatedAt) : null, after = decisionPacket(state, revision, prior, at), core = { schemaVersion: 'vigia.authoritative-truth-decision-delta.v1', incidentId: revision.incidentId, knowledgeTime: at, causingRevisionId: revision.revisionId, priorSituation: before, newOfficialTruth: after.currentOfficialPerimeter, hypothesisChanges: [{ hypothesisId: 'ACTIVE_GEOMETRY_PROGRESSION', from: before?.hypotheses.find((item) => item.id === 'ACTIVE_GEOMETRY_PROGRESSION')?.state ?? null, to: after.hypotheses.find((item) => item.id === 'ACTIVE_GEOMETRY_PROGRESSION').state }], evidenceDebtChanges: { before: before?.evidenceDebt ?? [], after: after.evidenceDebt }, forecastReadinessChange: { before: before?.forecastReadiness ?? null, after: after.forecastReadiness }, impactChanges: after.impactChanges, decisionsUnblocked: after.decisionsUnblocked, decisionsBlocked: after.decisionsBlocked, actionsSuperseded: after.actionsSuperseded, operatorAttentionChanged: before?.operatorAttention !== after.operatorAttention, externalConsequentialActions: 0, automaticDoctrineModification: false, packet: after };
    const delta = { ...core, deltaId: fingerprint('authoritative-truth-decision-delta', core) }; if (!state.decisionDeltas.some((item) => item.deltaId === delta.deltaId)) { state.decisionDeltas.push(delta); deltas.push(delta); }
  }
  return deltas;
}

export function buildConsumerSnapshot(state, at) {
  const revisions = byId(state), incidents = state.selectedIncidents.map((selected) => { const sequence = sequenceFor(state, selected.providerId, selected.incidentId), current = sequence ? revisions.get(sequence.revisionIds.at(-1)) : null, history = sequence?.revisionIds.map((id) => revisions.get(id)).filter((item) => item && revisionIsAdmitted(state, item.revisionId)) ?? [], labels = state.labels.filter((item) => item.incidentId === selected.incidentId), scores = state.forecastScores.filter((item) => item.incidentId === selected.incidentId), conflicts = state.conflicts.filter((item) => item.objects.some((object) => object.incidentId === selected.incidentId)), delta = [...state.decisionDeltas].reverse().find((item) => item.incidentId === selected.incidentId && revisionIsAdmitted(state, item.causingRevisionId) && !['INVALID_GEOMETRY', 'CLOCK_ANOMALY'].includes(revisions.get(item.causingRevisionId)?.revisionClassification)); return { incidentId: selected.incidentId, currentOfficialPerimeter: current && revisionIsAdmitted(state, current.revisionId) && current.quality?.valid ? { revisionId: current.revisionId, geometryHash: current.normalizedGeometryHash, geometryReference: `authoritative-revision:${current.revisionId}`, rawObjectReference: current.rawObjectReference, bbox: current.bbox, centroid: current.centroid } : null, perimeterAuthority: current?.providerId ?? selected.providerId, lastProviderPublication: current?.clocks.providerPublishedAt ?? null, lastVigiaReceipt: current?.clocks.retrievedAt ?? null, lastMeaningfulGeometryChange: [...history].reverse().find((item) => !['INITIAL_BASELINE', 'INITIAL_PROVIDER_STATE', 'DUPLICATE', 'INVALID_GEOMETRY', 'CLOCK_ANOMALY'].includes(item.revisionClassification))?.clocks.providerPublishedAt ?? null, revisionClassification: current?.revisionClassification ?? null, perimeterHistory: history.map((item) => ({ revisionId: item.revisionId, classification: item.revisionClassification, geometryHash: item.normalizedGeometryHash, rawObjectReference: item.rawObjectReference, providerPublishedAt: item.clocks.providerPublishedAt, availableToVigiaAt: item.clocks.availableToVigiaAt })), sourceConflicts: conflicts.map((item) => item.conflictId), officialLabelAvailability: Object.fromEntries(['1h', '3h', '6h', '12h', '24h'].map((horizon) => [horizon, labels.filter((item) => item.horizon === horizon).length])), forecastScoringState: scores.length ? 'EVALUATED' : 'NOT_SCOREABLE', truthLatency: current ? { publicationToReceiptMs: current.clocks.providerPublishedAt ? Date.parse(current.clocks.retrievedAt) - Date.parse(current.clocks.providerPublishedAt) : null, receiptToProjectionMs: Date.parse(current.clocks.projectionUpdatedAt) - Date.parse(current.clocks.retrievedAt) } : null, decisionDelta: delta ?? null, qualityWarnings: current?.quality?.valid ? [] : ['CURRENT_GEOMETRY_INVALID'], rights: current?.rights ?? null, replayReference: state.stateFingerprint ?? null }; });
  const core = { schemaVersion: 'vigia.authoritative-truth-operator-consumer-snapshot.v1', generatedAt: at, frontendCalculationRequired: false, incidents }; return { ...core, fingerprint: fingerprint('authoritative-truth-consumer-snapshot', core) };
}
