import { performance } from 'node:perf_hooks';
import { readJson } from '../../shared/json-file.mjs';
import { readNetworkState, truthPaths, writeArtifact } from './contracts.mjs';
import { doctorTruthNetwork, watchTruthNetwork } from './watcher-service.mjs';
import { replayTruthNetwork } from './replay-service.mjs';
import { revisionIsAdmitted } from './network-repository.mjs';

export async function demoAuthoritativeTruthNetwork({ projectRoot = process.cwd(), fetchImpl = globalThis.fetch, clock = () => new Date() } = {}) {
  const started = performance.now(), doctor = await doctorTruthNetwork({ projectRoot, fetchImpl, clock }), before = await readNetworkState(projectRoot, null), first = await watchTruthNetwork({ projectRoot, fetchImpl, clock, once: true, allActive: true }), middle = await readNetworkState(projectRoot), second = await watchTruthNetwork({ projectRoot, fetchImpl, clock, once: true, allActive: true, resume: middle.campaignId }), after = await readNetworkState(projectRoot), replay = await replayTruthNetwork({ projectRoot, clock, state: after }), status = await readJson(truthPaths(projectRoot).status, {}), beforeIds = new Set((before?.revisions ?? []).map((item) => item.revisionId)), newRevisionRows = after.revisions.filter((item) => !beforeIds.has(item.revisionId) && revisionIsAdmitted(after, item.revisionId) && !['INITIAL_PROVIDER_STATE', 'INVALID_GEOMETRY', 'DUPLICATE', 'CLOCK_ANOMALY'].includes(item.revisionClassification)), newRevisions = newRevisionRows.length, unchanged = after.pollObservations.filter((item) => item.snapshotClass === 'NO_PROVIDER_CHANGE').length - (before?.pollObservations.filter((item) => item.snapshotClass === 'NO_PROVIDER_CHANGE').length ?? 0), newLabels = after.labels.length - (before?.labels.length ?? 0), newDeltas = after.decisionDeltas.length - (before?.decisionDeltas.length ?? 0);
  const core = { schemaVersion: 'vigia.authoritative-truth-network-demo.v1', generatedAt: clock().toISOString(), steps: { providerDiscovery: { passed: doctor.passed, providers: doctor.providers.length }, multiIncidentSelection: { watched: status.activeIncidentsWatched }, realOfficialFetch: { rawObjects: status.rawObjects, providerPublications: status.providerPublications }, immutableRawPersistence: { uniqueBytes: after.metrics.uniqueBytesStored, duplicates: after.metrics.rawDuplicates }, unchangedVersusChanged: { unchanged, newRevisions }, realRevisionDetectedIfAvailable: { available: newRevisions > 0, fabricated: false }, revisionSemantics: { classes: [...new Set(newRevisionRows.map((item) => item.revisionClassification))].sort() }, authoritativeSequences: { count: status.authoritativeSequences }, nearTermLabel: { created: newLabels, fabricated: false }, forecastScoring: { comparisons: after.forecastScores.length }, decisionPacketRecompiled: { deltas: newDeltas }, decisionDelta: { count: newDeltas }, exactReplay: { passed: replay.passed, fingerprint: replay.fingerprint }, fingerprintVerification: { state: after.stateFingerprint, replay: replay.exactFingerprint } }, campaign: { campaignId: after.campaignId, state: second.state, resumeCommand: second.resumeCommand, noBackgroundProcess: after.running === false, shutdownClean: after.shutdownClean }, qualification: newRevisions ? 'REAL_OFFICIAL_REVISION_OBSERVED' : 'REAL_UNCHANGED_STATE_AND_RESUMABILITY_DEMONSTRATED_NO_REVISION_FABRICATED', durationMs: Number((performance.now() - started).toFixed(3)), passed: doctor.passed && first.replayPassed && second.replayPassed && replay.passed && after.shutdownClean };
  return writeArtifact(truthPaths(projectRoot).demo, 'authoritative-truth-demo', core);
}
