import { readNetworkState, truthPaths, writeArtifact } from './contracts.mjs';
import { readJson } from '../../shared/json-file.mjs';

export async function evaluateAuthoritativeTruthGate({ projectRoot = process.cwd(), clock = () => new Date() } = {}) {
  const paths = truthPaths(projectRoot), [state, labels, scores, replay, verification] = await Promise.all([readNetworkState(projectRoot), readJson(paths.labels, {}), readJson(paths.scores, {}), readJson(paths.replay, {}), readJson(paths.verification, {})]); if (!state) throw new Error('authoritative_truth_state_required');
  const oneHour = Number(labels.horizons?.['1h'] ?? 0), threeHour = Number(labels.horizons?.['3h'] ?? 0), officialLabels = labels.labels ?? [], completeChronology = officialLabels.length > 0 && officialLabels.every((item) => item.issueTime && item.issueAvailableToVigiaAt && item.laterTruthTime && item.laterTruthAvailableToVigiaAt && Date.parse(item.laterTruthAvailableToVigiaAt) > Date.parse(item.issueAvailableToVigiaAt)), validAuthority = officialLabels.length > 0 && officialLabels.every((item) => item.authorityClass === 'AUTHORITATIVE_OPERATIONAL_PERIMETER'), scoredRevisionIds = new Set(officialLabels.map((item) => item.laterRevisionId)), packetUpdated = state.decisionDeltas.some((item) => scoredRevisionIds.has(item.causingRevisionId));
  const checks = { legitimateOfficialOneHourLabel: oneHour >= 1, legitimateOfficialThreeHourLabel: threeHour >= 1, completeChronology, validAuthorityClass: validAuthority, forecastEvaluationExecuted: scores.evaluationExecuted === true, decisionPacketUpdated: packetUpdated, fullReplayPassed: replay.passed === true, zeroNewRegressions: verification.passed === true && verification.newRegressions === 0 }, passed = Object.values(checks).every(Boolean), blocker = !checks.legitimateOfficialOneHourLabel || !checks.legitimateOfficialThreeHourLabel ? 'TIME_ACCUMULATION_REQUIRED' : !checks.completeChronology || !checks.validAuthorityClass ? 'SCIENTIFIC_INTEGRITY_BLOCKED' : !checks.forecastEvaluationExecuted || !checks.decisionPacketUpdated ? 'WORKFLOW_INTEGRATION_BLOCKED' : !checks.fullReplayPassed || !checks.zeroNewRegressions ? 'VERIFICATION_BLOCKED' : null;
  return writeArtifact(paths.gate, 'authoritative-crisis-truth-gate', { schemaVersion: 'vigia.authoritative-crisis-truth-gate.v1', generatedAt: clock().toISOString(), checks, officialLabels: { oneHour, threeHour }, passed, decision: passed ? 'AUTHORITATIVE_CRISIS_TRUTH_GATE_PASSED' : 'AUTHORITATIVE_CRISIS_TRUTH_GATE_NOT_PASSED', preciseRemainingBlocker: blocker, strongerScientificPromotionGate: { separate: true, oneHourLabels: 10, threeHourLabels: 10, independentDevelopmentCalibrationHeldOutRequired: true } });
}
