import { performance } from 'node:perf_hooks';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fingerprint, readNetworkState, truthPaths, writeArtifact } from './contracts.mjs';
import { buildIncrementalOfficialLabels } from './label-factory.mjs';

export async function replayTruthNetwork({ projectRoot = process.cwd(), clock = () => new Date(), state: provided = null } = {}) {
  const started = performance.now(), state = provided ?? await readNetworkState(projectRoot); if (!state) throw new Error('authoritative_truth_state_required'); const revisions = new Map(state.revisions.map((item) => [item.revisionId, item])), failures = [];
  for (const [incidentId, sequence] of Object.entries(state.sequences)) for (let index = 0; index < sequence.revisionIds.length; index += 1) { const revision = revisions.get(sequence.revisionIds[index]); if (!revision) failures.push(`revision_missing:${incidentId}:${sequence.revisionIds[index]}`); else { const core = structuredClone(revision); delete core.revisionId; if (fingerprint('authoritative-perimeter-revision', core) !== revision.revisionId) failures.push(`revision_fingerprint:${revision.revisionId}`); if (revision.priorRevisionId !== (sequence.revisionIds[index - 1] ?? null)) failures.push(`revision_chain:${revision.revisionId}`); } }
  for (const raw of state.rawObjects) try { const bytes = await readFile(path.resolve(projectRoot, raw.binaryReference)); if (raw.sha256 !== `sha256:${(await import('node:crypto')).createHash('sha256').update(bytes).digest('hex')}`) failures.push(`raw_hash:${raw.id}`); } catch { failures.push(`raw_missing:${raw.id}`); }
  const rebuilt = structuredClone(state); rebuilt.labels = []; rebuilt.internalEvents = []; buildIncrementalOfficialLabels(rebuilt, [...new Set(Object.values(rebuilt.sequences).map((item) => item.incidentId))], state.updatedAt); const expectedLabels = state.labels.map((item) => item.labelId).sort(), replayedLabels = rebuilt.labels.map((item) => item.labelId).sort(); if (JSON.stringify(expectedLabels) !== JSON.stringify(replayedLabels)) failures.push('label_replay_mismatch');
  const backup = JSON.parse(JSON.stringify(state)), backupRestore = fingerprint('truth-backup', backup) === fingerprint('truth-backup', state), durationMs = Number((performance.now() - started).toFixed(3)), replayCore = { stateFingerprint: state.stateFingerprint, revisionIds: [...revisions.keys()].sort(), labelIds: expectedLabels, rawObjectHashes: state.rawObjects.map((item) => item.sha256).sort() }, core = { schemaVersion: 'vigia.authoritative-truth-replay.v1', generatedAt: clock().toISOString(), campaignId: state.campaignId, exactFingerprint: fingerprint('authoritative-truth-replay-state', replayCore), revisionChainsVerified: !failures.some((item) => item.startsWith('revision_')), rawObjectsVerified: !failures.some((item) => item.startsWith('raw_')), labelReplayVerified: !failures.includes('label_replay_mismatch'), backupRestorePassed: backupRestore, restartRecoveryPassed: state.shutdownClean === true && state.checkpoints.length > 0, priorSnapshotsRewritten: Number(state.baselineReference?.priorSnapshotsRewritten ?? 0), failures, durationMs, passed: failures.length === 0 && backupRestore && state.shutdownClean === true };
  state.performanceSamples ??= {}; (state.performanceSamples.replay ??= []).push(durationMs); return writeArtifact(truthPaths(projectRoot).replay, 'authoritative-truth-replay', core);
}
