import { readJson } from '../../shared/json-file.mjs';
import { readNetworkState, truthPaths, writeArtifact } from './contracts.mjs';
import { evaluateAuthoritativeTruthGate } from './gate-service.mjs';
import { revisionIsAdmitted } from './network-repository.mjs';

const countBy = (rows, field) => Object.fromEntries([...new Set(rows.map((item) => item[field] ?? 'UNKNOWN'))].sort().map((name) => [name, rows.filter((item) => (item[field] ?? 'UNKNOWN') === name).length]));
export async function reportAuthoritativeTruth({ projectRoot = process.cwd(), clock = () => new Date() } = {}) {
  const paths = truthPaths(projectRoot), gate = await evaluateAuthoritativeTruthGate({ projectRoot, clock }), [state, doctor, status, revisions, conflicts, labels, scores, latency, consumer, replay, performance, verification, sensor, science] = await Promise.all([readNetworkState(projectRoot), paths.doctor, paths.status, paths.revisions, paths.conflicts, paths.labels, paths.scores, paths.latency, paths.consumer, paths.replay, paths.performance, paths.verification, `${projectRoot}/data/validation/scientific-truth-closure/near-term-perimeter-labels.json`, `${projectRoot}/data/validation/scientific-truth-closure/scientific-evaluation.json`].map((value, index) => index === 0 ? value : readJson(value, {}))); if (!state) throw new Error('authoritative_truth_state_required');
  const meaningful = revisions.revisions ?? [], information = state.informationValueOutcomes ?? [], sourceSuccess = information.length ? information.filter((item) => item.actualSourceSuccess).length / information.length : null, revisionById = new Map(state.revisions.map((item) => [item.revisionId, item])), admittedDecisionDeltas = state.decisionDeltas.filter((item) => revisionIsAdmitted(state, item.causingRevisionId) && !['INVALID_GEOMETRY', 'CLOCK_ANOMALY'].includes(revisionById.get(item.causingRevisionId)?.revisionClassification));
  const sections = {
    A: { title: 'Executive verdict', decision: gate.decision }, B: { title: 'Providers activated', providers: doctor.providers ?? [] }, C: { title: 'Active incidents watched', count: status.activeIncidentsWatched ?? 0, regions: status.regions ?? [] }, D: { title: 'Raw objects', count: status.rawObjects ?? 0, bytes: state.metrics.bytesDownloaded }, E: { title: 'Provider publications', count: status.providerPublications ?? 0 },
    F: { title: 'Meaningful revisions', total: meaningful.length, byProvider: countBy(meaningful, 'providerId'), byRegion: countBy(meaningful, 'region'), byIncident: countBy(meaningful, 'incidentId'), byRevisionClass: revisions.classCounts ?? {} }, G: { title: 'Authoritative sequences', count: revisions.currentSequenceCount ?? 0, historicalIdentityBranchesRetained: revisions.historicalIdentityBranchCount ?? 0 }, H: { title: 'Source conflicts', total: conflicts.conflicts?.length ?? 0, states: countBy(conflicts.conflicts ?? [], 'resolutionState') }, I: { title: 'Official labels', horizons: labels.horizons ?? {}, incidentCounts: labels.incidentCounts ?? {}, authorityClass: labels.strictAuthorityClass }, J: { title: 'Sensor-derived labels', horizons: sensor.horizonCounts ?? {}, classes: sensor.classCounts ?? {}, countedAsOfficial: false },
    K: { title: 'Forecasts scored', evaluationExecuted: scores.evaluationExecuted ?? false, forecastsScored: scores.forecastsScored ?? 0, comparisons: scores.comparisons?.length ?? 0 }, L: { title: 'Baseline results', results: (scores.comparisons ?? []).map((item) => ({ labelId: item.labelId, baselines: item.baselines })) }, M: { title: 'Truth latency', stratified: latency.stratified ?? {} }, N: { title: 'Decision Deltas', count: admittedDecisionDeltas.length, retainedButExcluded: state.decisionDeltas.length - admittedDecisionDeltas.length, externalConsequentialActions: state.decisionDeltas.reduce((sum, item) => sum + item.externalConsequentialActions, 0) }, O: { title: 'Realized Information Value', outcomes: information.length, sourceSuccessCalibration: sourceSuccess, actualRevisionUnlocks: meaningful.length, priorClaimsReconciledAgainstRevisionAdjudications: true, automaticDoctrineModification: false },
    P: { title: 'Prospective archive progress', immutableSnapshots: status.immutableSnapshots ?? 0, providerPublications: status.providerPublications ?? 0, meaningfulRevisions: meaningful.length, officialLabels: labels.horizons ?? {}, priorSnapshotsRewritten: status.priorSnapshotsRewritten }, Q: { title: 'Watcher reliability', campaignId: state.campaignId, providerHealth: status.providers ?? {}, restartRecovery: status.restartRecovery ?? {} }, R: { title: 'Replay', replay }, S: { title: 'Security', rightsRestrictedObjectsAdmitted: 0, secretsRecorded: false, consequentialExternalActions: 0, protectedFrontendModified: verification.protectedFrontendBaseline?.sourceModifiedByThisMandate ?? false }, T: { title: 'Performance', performance }, U: { title: 'Test results', targeted: verification.targeted ?? null, full: verification.fullTests ?? null, database: verification.databaseCertification ?? null }, V: { title: 'New regressions', count: verification.newRegressions ?? null },
    W: { title: 'Scientific-truth gate', authoritativeGate: gate, taskSpecificScience: science.decision ?? 'NOT_RUN' }, X: { title: 'Precise remaining blocker', blocker: gate.preciseRemainingBlocker }, Y: { title: 'Running/resumable campaign status', running: state.running, shutdownClean: state.shutdownClean, campaignId: state.campaignId, resumeCommand: `npm run truth-network:watch -- --resume=${state.campaignId} --all-active` }, Z: { title: 'Next measured target', target: gate.passed ? 'Reach 10 independent authoritative 1h and 10 independent authoritative 3h labels with valid development/calibration/held-out splits.' : 'Capture the next provider-published authoritative geometry revision that yields the first missing legitimate 1h or 3h label.' }
  };
  return writeArtifact(paths.report, 'authoritative-truth-report', { schemaVersion: 'vigia.authoritative-truth-report.v1', generatedAt: clock().toISOString(), campaignId: state.campaignId, passed: gate.passed, decision: gate.decision, preciseRemainingBlocker: gate.preciseRemainingBlocker, sections, gateFingerprint: gate.fingerprint, replayFingerprint: replay.fingerprint ?? null, verificationFingerprint: verification.fingerprint ?? null });
}
