import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readJson } from '../../shared/json-file.mjs';
import { truthPaths, writeArtifact } from './contracts.mjs';

const execute = promisify(execFile);
async function run(command, args, projectRoot, timeout = 300_000) { try { const result = await execute(command, args, { cwd: projectRoot, timeout, maxBuffer: 64 * 1024 * 1024, env: { ...process.env, TMPDIR: `${projectRoot}/.tmp/test` } }); return { exitCode: 0, output: `${result.stdout}${result.stderr}` }; } catch (error) { return { exitCode: Number(error.code) || 1, output: `${error.stdout ?? ''}${error.stderr ?? ''}` }; } }
const count = (output, name) => Number(output.match(new RegExp(`(?:#|ℹ) ${name} (\\d+)`, 'g'))?.at(-1)?.match(/\d+/)?.[0] ?? 0);
const compact = (result) => ({ exitCode: result.exitCode, tests: count(result.output, 'tests'), pass: count(result.output, 'pass'), fail: count(result.output, 'fail'), skipped: count(result.output, 'skipped'), durationMs: count(result.output, 'duration_ms'), tail: result.output.split('\n').slice(-35).join('\n') });

export async function verifyAuthoritativeTruthNetwork({ projectRoot = process.cwd(), clock = () => new Date() } = {}) {
  const targeted = await run('node', ['--test', 'apps/api/test/authoritative-truth-network.test.mjs'], projectRoot), check = await run('npm', ['run', 'check'], projectRoot), full = await run('npm', ['test'], projectRoot, 600_000), database = await run('npm', ['run', 'db:certify-intelligence'], projectRoot, 600_000), smoke = await run('npm', ['run', 'smoke'], projectRoot), frontendDiff = await run('git', ['diff', '--quiet', '--', 'apps/web/src/v2/release-compatibility.js'], projectRoot), replay = await readJson(truthPaths(projectRoot).replay, {}), performance = await readJson(truthPaths(projectRoot).performance, {});
  const knownFull = full.exitCode !== 0 && count(full.output, 'fail') === 1 && frontendDiff.exitCode === 0 && full.output.includes('release-contract-governance.test.mjs') && full.output.includes('doesNotMatch') && full.output.includes('vigia-postgis-014'), knownSmoke = smoke.exitCode !== 0 && smoke.output.includes('/src/main.js'), newRegressions = Number(targeted.exitCode !== 0) + Number(check.exitCode !== 0) + Number(full.exitCode !== 0 && !knownFull) + Number(database.exitCode !== 0) + Number(smoke.exitCode !== 0 && !knownSmoke) + Number(replay.passed !== true) + Number(Object.values(performance.checks ?? {}).some((value) => value !== true));
  const core = { schemaVersion: 'vigia.authoritative-truth-verification.v1', generatedAt: clock().toISOString(), targeted: compact(targeted), staticCheck: { exitCode: check.exitCode, tail: check.output.split('\n').slice(-20).join('\n') }, fullTests: { ...compact(full), knownProtectedFrontendFailure: knownFull }, databaseCertification: { exitCode: database.exitCode, tail: database.output.split('\n').slice(-30).join('\n') }, productionSmoke: { exitCode: smoke.exitCode, knownProtectedFrontendFailure: knownSmoke, tail: smoke.output.split('\n').slice(-30).join('\n') }, replay: { passed: replay.passed, fingerprint: replay.fingerprint }, performance: { checks: performance.checks, fingerprint: performance.fingerprint }, protectedFrontendBaseline: { path: 'apps/web/src/v2/release-compatibility.js', sourceModifiedByThisMandate: frontendDiff.exitCode !== 0 }, newRegressions, passed: newRegressions === 0 };
  return writeArtifact(truthPaths(projectRoot).verification, 'authoritative-truth-verification', core);
}
