import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { signOperatorProxyRequest } from '../../packages/domain/src/operator-proxy/request-auth.mjs';

const root=process.cwd(),apiOrigin='http://127.0.0.1:4177',operatorOrigin='http://127.0.0.1:4190',periodId='operational-period:field-deployment-rehearsal-v5',incidentId='incident:exercise:portugal-mainland-field-deployment-001',workflowId='protect:field-deployment-rehearsal-v6';
const manifest=JSON.parse(await readFile(path.join(root,'data/validation/release/current-release-manifest.json'),'utf8')),key=String(await readFile(path.join(root,'.tmp/release/operator-token'),'utf8')).trim(),artifactRoot=path.join(root,'.artifacts/operational-proof-field-deployment/final/eoc-exercise');
const quartet={releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,releaseStatementHash:manifest.releaseStatementHash};

async function request(route,{method='GET',body=null}={}){const bodyBytes=body===null?Buffer.alloc(0):Buffer.from(JSON.stringify(body)),intent=['GET','HEAD','OPTIONS'].includes(method)?'':'operator-console',headers={accept:'application/json',origin:operatorOrigin,'sec-fetch-site':'same-origin','x-vigia-ui-proxy':'mission-dark-realdata-2.0',...(body!==null?{'content-type':'application/json'}:{}),...signOperatorProxyRequest({key,releaseId:manifest.releaseId,method,path:route,bodyBytes,intent})};const response=await fetch(`${apiOrigin}${route}`,{method,headers,body:body===null?undefined:bodyBytes,signal:AbortSignal.timeout(30_000)}),payload=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(`${route}:${response.status}:${payload?.message??payload?.error??'request_failed'}`),{status:response.status,payload});return payload;}
const post=(route,body)=>request(route,{method:'POST',body});
const periodRoute=`/api/v10/operator/operational-periods/${encodeURIComponent(periodId)}`;
const protectionBase=`/api/v10/incident-command/incidents/${encodeURIComponent(incidentId)}/protection-workflows`;

await mkdir(artifactRoot,{recursive:true});
const portfolio=await request('/api/v10/operator/operational-periods'),existing=portfolio.periods?.find(item=>item.periodId===periodId);
if(existing?.state==='CLOSED'){
  const audit=await request(`${periodRoute}/audit-bundle`),afterActionPackage=audit.afterActionPackage??null,period=audit.period??existing,assignments=afterActionPackage?.assignments??period.assignments??[],actions=afterActionPackage?.actions??period.actions??[],proof={schemaVersion:'vigia.controlled-eoc-exercise-proof.v1',generatedAt:new Date().toISOString(),releaseIdentity:quartet,period,afterActionPackage,capDraft:null,protectionState:(afterActionPackage?.protectionItems??period.protectionItems??[]).find(item=>item.workflowId===workflowId)?.state??'NOT_RECORDED',externalSends:0,productionTruthAffected:false,humanUsability:{state:'NOT_RUN',reason:'This persisted record is an authenticated automated release rehearsal. The required named human role-play remains external work.'},metrics:{exerciseWallClockMs:null,operatorBacktracking:{state:'NOT_MEASURED_AUTOMATED_REHEARSAL'},missedAcknowledgements:assignments.filter(item=>!item.acknowledgements?.length).length+actions.filter(item=>!item.acknowledgements?.length).length},evidenceReuse:{state:'REBOUND_FROM_PERSISTED_AUDIT',auditFingerprint:audit.fingerprint??null},truthBoundary:'This artifact rebinds the persisted workflow proof to the current release without replaying external effects. It is not a completed human exercise and is never counted as a live incident, live response operation, production outcome, or public alert.'};await Promise.all([writeFile(path.join(artifactRoot,'exercise-proof.json'),`${JSON.stringify(proof,null,2)}\n`),writeFile(path.join(artifactRoot,'audit-bundle.json'),`${JSON.stringify({...audit,releaseIdentity:quartet},null,2)}\n`)]);process.stdout.write(`${JSON.stringify({state:'ALREADY_COMPLETED',periodId,participantType:existing.exerciseDeclaration?.participantType,releaseIdentity:quartet},null,2)}\n`);process.exit(0);
}
const startedAt=existing?.startsAt?new Date(existing.startsAt):new Date(),endsAt=existing?.endsAt??new Date(startedAt.getTime()+4*3_600_000).toISOString(),roles=['Incident Commander','Intelligence Lead','Operations Lead','Protection / Alert Authority','Field / Resource Operator','Observer / Auditor'];
if(!existing)await post('/api/v10/operator/operational-periods',{periodId,exerciseMode:true,executionMode:'AUTOMATED_RELEASE_REHEARSAL',participantType:'AUTOMATED_RELEASE_OPERATOR',facilitator:'Codex release operator',shift:'Field-deployment controlled rehearsal',commander:'Exercise commander',startsAt:startedAt.toISOString(),endsAt,roles:roles.map((role,index)=>({role,person:`Simulated role ${index+1}`,organization:'VIGIA controlled exercise'})),authorityMatrix:[{role:'Incident Commander',capability:'Approve internal exercise assignments',scope:'CONTROLLED_EOC_EXERCISE',limit:'No external dispatch'},{role:'Protection / Alert Authority',capability:'Approve exercise-only CAP draft',scope:'CONTROLLED_EOC_EXERCISE',limit:'External transport disabled'}],incidentOwners:[{incidentId,owner:'Exercise intelligence lead',organization:'VIGIA controlled exercise'}],objectives:[{objectiveId:'objective:field-deployment',statement:'Assess a retained candidate signal, perform an isolated field-verification workflow, and exercise the fail-closed protection path.',owner:'Exercise commander',dueAt:endsAt}]});

const existingProtection=await request(protectionBase),hasWorkflow=existingProtection.workflows?.find(item=>item.workflowId===workflowId);
if(!hasWorkflow)await post(protectionBase,{workflowId,universe:'EXERCISE',targetPopulationOrArea:{areaId:'community:exercise-only',areaDesc:'Controlled exercise area; not a real warning target',geocode:[{valueName:'exercise-zone',value:'PT-VIGIA-EXERCISE-ONLY'}]},exposureAssessment:'A synthetic exercise candidate is associated with point-based community context; no real exposure is asserted.',protectionThreshold:'Exercise controller inject: a protection-authority review is required.',recommendation:'Prepare and validate an exercise-only CAP draft. Do not send.',authorityRequirement:'Exercise protection-authority approval',authorityOwner:'Simulated Protection / Alert Authority',authorityValidUntil:endsAt,expiresAt:endsAt,expectedPostcondition:'A valid exercise CAP draft and explicit external-send-disabled receipt are retained.',provenanceRefs:['exercise-inject:field-deployment-001','governed-context:point-based-only']});
for(const state of ['REVIEW','APPROVED','DISPATCH_ELIGIBLE','EXTERNAL_SEND_DISABLED'])await post(`${protectionBase}/${encodeURIComponent(workflowId)}/transitions`,{state,note:'Controlled exercise progression; no external system invoked.'});
const capDraft=await post(`${protectionBase}/${encodeURIComponent(workflowId)}/cap-draft`,{sender:'exercise-authority@vigia.local',status:'Exercise',msgType:'Alert',scope:'Restricted',event:'Wildfire exercise protection review',urgency:'Expected',severity:'Moderate',certainty:'Observed',headline:'EXERCISE — VIGIA controlled field-deployment rehearsal',instruction:'Exercise only. Do not take public action or dispatch resources.'});

const record=(body)=>post(`${periodRoute}/records`,body);
await record({kind:'OBJECTIVE_ACKNOWLEDGEMENT',objectiveId:'objective:field-deployment',note:'Acknowledged for the isolated automated release rehearsal.'});
await record({kind:'TACTIC',tacticId:'tactic:field-verification',incidentId,objectiveId:'objective:field-deployment',statement:'Request and record one attributable exercise field observation.',owner:'Exercise operations lead'});
await record({kind:'AUTHORITY_DECISION',decisionId:'decision:exercise-protection',incidentId,statement:'Approve validation of an exercise-only CAP draft while external transport remains disabled.',owner:'Simulated Protection / Alert Authority',authority:'CONTROLLED_EOC_EXERCISE',dueAt:endsAt,acknowledged:true,state:'APPROVED'});
await record({kind:'ASSIGNMENT',assignmentId:'assignment:field-verification',incidentId,tacticId:'tactic:field-verification',assignee:'Simulated Field / Resource Operator',resourceIds:['resource:exercise-field-unit-01'],authorityDecisionId:'decision:exercise-protection',dueAt:endsAt,state:'COMPLETED'});
await record({kind:'RESOURCE_STATUS',resource:'resource:exercise-field-unit-01',assigned:1,available:0,state:'EXERCISE_ASSIGNED'});
await record({kind:'ACTION',actionId:'action:field-verification',assignmentId:'assignment:field-verification',incidentId,statement:'Submit an attributable controlled-exercise field update.',owner:'Simulated Field / Resource Operator',source:'CONTROLLED_EOC_EXERCISE operator record',authorityDecisionId:'decision:exercise-protection',dueAt:endsAt,expectedPostcondition:'An attributable exercise field-update record is persisted.',completionCriteria:'Assignment acknowledgement and exercise update receipt are present.',state:'COMPLETED'});
await record({kind:'ACKNOWLEDGEMENT',targetType:'ASSIGNMENT',targetId:'assignment:field-verification',role:'Field / Resource Operator',note:'Exercise assignment accepted.'});
await record({kind:'ACKNOWLEDGEMENT',targetType:'ACTION',targetId:'action:field-verification',role:'Operations Lead',note:'Exercise completion receipt reviewed.'});
await record({kind:'PROTECTION_ITEM',workflowId,incidentId,state:'EXTERNAL_SEND_DISABLED',owner:'Simulated Protection / Alert Authority',dueAt:endsAt});
await record({kind:'POSTCONDITION',postconditionId:'postcondition:exercise-field-update',incidentId,actionId:'action:field-verification',statement:'The attributable exercise field update and no-send protection receipt are retained.',observedState:'OBSERVED_IN_EXERCISE',source:'Operational-period and protection-workflow ledgers',observedAt:new Date().toISOString()});
await record({kind:'OUTCOME',outcomeId:'outcome:field-deployment-rehearsal',incidentId,actionId:'action:field-verification',postconditionId:'postcondition:exercise-field-update',classification:'INDETERMINATE',statement:'The governed workflow completed, but an automated rehearsal cannot establish human usability or real-world protection impact.',causalClaim:'NOT_ESTABLISHED',evidenceIds:['postcondition:exercise-field-update',workflowId]});
await record({kind:'AFTER_ACTION_FINDING',statement:'Run the same package with named human participants before a government pilot go decision.',owner:'Pilot lead',dueAt:endsAt,state:'OPEN'});
await post(`${periodRoute}/handoff`,{from:'Exercise commander',to:'Incoming exercise commander',acknowledgedBy:'Incoming exercise commander'});
const closed=await post(`${periodRoute}/close`,{summary:'Automated controlled EOC rehearsal completed end to end. External dispatch remained disabled; human usability and real operational outcomes were not claimed.'}),audit=await request(`${periodRoute}/audit-bundle`),completedAt=new Date();
const proof={schemaVersion:'vigia.controlled-eoc-exercise-proof.v1',generatedAt:completedAt.toISOString(),releaseIdentity:quartet,period:closed.period,afterActionPackage:closed.afterActionPackage,capDraft,protectionState:'EXTERNAL_SEND_DISABLED',externalSends:0,productionTruthAffected:false,humanUsability:{state:'NOT_RUN',reason:'This was an authenticated automated release rehearsal. The required named human role-play remains external work.'},metrics:{exerciseWallClockMs:completedAt-startedAt,operatorBacktracking:{state:'NOT_MEASURED_AUTOMATED_REHEARSAL'},missedAcknowledgements:closed.period.assignments.filter(item=>!item.acknowledgements?.length).length+closed.period.actions.filter(item=>!item.acknowledgements?.length).length},truthBoundary:'This artifact proves persisted workflow mechanics and fail-closed isolation. It is not a completed human exercise and is never counted as a live incident, live response operation, production outcome, or public alert.'};
await writeFile(path.join(artifactRoot,'exercise-proof.json'),`${JSON.stringify(proof,null,2)}\n`);await writeFile(path.join(artifactRoot,'audit-bundle.json'),`${JSON.stringify({...audit,releaseIdentity:quartet},null,2)}\n`);process.stdout.write(`${JSON.stringify({state:'COMPLETED_AUTOMATED_REHEARSAL',periodId,workflowId,externalSends:0,humanUsability:'NOT_RUN',releaseIdentity:quartet},null,2)}\n`);
