import { DatabaseSync } from 'node:sqlite';import { chmodSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { canonical, createFieldTask, priorityDisposition, sha256, sourceFreshness, stableId, verifyIncidentPackage } from '../../../packages/domain/src/fieldnet/contracts.mjs';
import { compareTaskMutation, observationRelationship, sanitizeTaskChanges } from '../../../packages/domain/src/fieldnet/reconciliation.mjs';
import { isLifeSafetyIncidentCommandType } from '../../../packages/domain/src/incident-command/contracts.mjs';import { applyIncidentCommandEvent, emptyIncidentState, replayIncidentCommand } from '../../../packages/domain/src/incident-command/reducer.mjs';
import { compactAcknowledgedMutations } from './mutation-retention.mjs';
import { assertSqliteWriteCapacity, configureSqliteHardLimit, prepareSqliteWrite, recoverSqliteWal, sqliteLogicalBytes, sqliteStorageBytes } from './sqlite-capacity.mjs';
import { boundedSyncCursor } from './bounded-central-response.mjs';const parse = (value) => value ? JSON.parse(value) : null,text = (value) => JSON.stringify(value),iso = (clock) => clock().toISOString();
import { withResolutionPlan } from './sqlite-conflict-plan.mjs';
import { initializeFieldNodeSchema } from './sqlite-schema.mjs';
import { projectPersistedTaskLifecycle } from './sqlite-task-lifecycle.mjs';
const p0ReserveUsage=({total,p0,base})=>Math.max(0,p0-Math.max(0,base-(total-p0)));
export class FieldNodeStore {
  constructor({ filePath, nodeId, clock = () => new Date(), maxPayloadBytes = 262_144, maxPending = 10_000, maxDatabaseBytes = 256*1024*1024, maxRetainedMutations = 2_000, priorityMutationReserve = 256, maxHistoryRows = 2_000, maxHistoryBytes = 8*1024*1024 } = {}) {
    if (!filePath || !nodeId) throw new Error('field_store_configuration_required');
    mkdirSync(path.dirname(filePath), { recursive: true,mode:0o700 });chmodSync(path.dirname(filePath),0o700); this.filePath = filePath; this.nodeId = nodeId; this.clock = clock; this.maxPayloadBytes = maxPayloadBytes; this.maxPending = maxPending;this.maxDatabaseBytes=maxDatabaseBytes;this.storageReserveBytes=Math.min(Math.floor(maxDatabaseBytes/4),Math.max(1024*1024,maxPayloadBytes*4));this.transactionReserveBytes=Math.max(64*1024,Math.min(this.storageReserveBytes,maxPayloadBytes*4));this.maxRetainedMutations=maxRetainedMutations;this.priorityMutationReserve=Math.max(1,priorityMutationReserve);this.maxHistoryRows=maxHistoryRows;this.maxHistoryBytes=maxHistoryBytes;
    this.db = new DatabaseSync(filePath); this.db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;'); this.#schema();this.#secureFiles();configureSqliteHardLimit(this.db,this.maxDatabaseBytes);this.#repairConflictVerificationInvariant();
  }
  close() { this.#secureFiles();this.db.close();this.#secureFiles(); }
  readiness() {
    try {
      this.db.exec('BEGIN IMMEDIATE; ROLLBACK;');
      return { opened:true,writable:true,state:'ready',mode:'SQLITE_WAL_FULL_SYNC',databasePath:this.filePath };
    } catch (error) {
      try { this.db.exec('ROLLBACK;'); } catch {}
      return { opened:true,writable:false,state:'failed',mode:'SQLITE_WAL_FULL_SYNC',databasePath:this.filePath,error:String(error?.code??error?.message??'storage_probe_failed').slice(0,160) };
    }
  }
  #secureFiles(){for(const target of [this.filePath,`${this.filePath}-wal`,`${this.filePath}-shm`])if(existsSync(target))chmodSync(target,0o600);}
  #schema() { initializeFieldNodeSchema({ db: this.db, clock: this.clock, nodeId: this.nodeId, getMeta: (key) => this.#meta(key), setMeta: (key, value) => this.#setMeta(key, value) }); }
  #boundedRows(sql,args=[],code='field_history_capacity_exceeded'){const count=Number(this.db.prepare(`SELECT count(*) count FROM (${sql}) field_rows`).get(...args).count);if(count>this.maxHistoryRows)throw Object.assign(new Error(code),{statusCode:413,details:{rows:count,maxRows:this.maxHistoryRows}});return this.db.prepare(sql).all(...args);}
  #boundedPayloadRows(sql,args=[],code='field_history_capacity_exceeded'){const stats=this.db.prepare(`SELECT count(*) count,COALESCE(sum(length(payload)),0) bytes FROM (${sql}) field_payload_rows`).get(...args),count=Number(stats.count),bytes=Number(stats.bytes);if(count>this.maxHistoryRows||bytes>this.maxHistoryBytes)throw Object.assign(new Error(code),{statusCode:413,details:{rows:count,bytes,maxRows:this.maxHistoryRows,maxBytes:this.maxHistoryBytes}});return this.db.prepare(sql).all(...args);}
  #transaction(work,{protectedWrite=false,estimatedBytes=this.transactionReserveBytes}={}) { const limit=prepareSqliteWrite({db:this.db,filePath:this.filePath,maxDatabaseBytes:this.maxDatabaseBytes,reserveBytes:this.storageReserveBytes,protectedWrite,estimatedBytes});this.db.exec('BEGIN IMMEDIATE'); try { const result = work();assertSqliteWriteCapacity({db:this.db,filePath:this.filePath,maxDatabaseBytes:this.maxDatabaseBytes,limit}); this.db.exec('COMMIT');this.#secureFiles(); return result; } catch (error) { try{this.db.exec('ROLLBACK');}finally{recoverSqliteWal(this.db);this.#secureFiles();} throw error; } }
  #meta(key) { return this.db.prepare('SELECT value FROM meta WHERE key=?').get(key)?.value ?? null; }
  #setMeta(key, value) { this.db.prepare('INSERT INTO meta(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').run(key, String(value), iso(this.clock)); }
  state() { const retained=this.db.prepare("SELECT count(*) total,sum(CASE WHEN priority='P0_LIFE_SAFETY' THEN 1 ELSE 0 END) p0,sum(CASE WHEN priority='P1_COMMAND' THEN 1 ELSE 0 END) p1 FROM mutation").get(),pending=this.db.prepare("SELECT count(*) total,sum(CASE WHEN priority='P0_LIFE_SAFETY' THEN 1 ELSE 0 END) p0,sum(CASE WHEN priority='P1_COMMAND' THEN 1 ELSE 0 END) p1 FROM sync_queue WHERE state IN ('PENDING','RETRY_EXHAUSTED')").get(),retainedTotal=Number(retained.total),retainedP0=Number(retained.p0),pendingTotal=Number(pending.total),pendingP0=Number(pending.p0),retainedReserveUsed=p0ReserveUsage({total:retainedTotal,p0:retainedP0,base:this.maxRetainedMutations}),pendingReserveUsed=p0ReserveUsage({total:pendingTotal,p0:pendingP0,base:this.maxPending});return { nodeId: this.nodeId, connectionState: this.#meta('connection_state'), syncCursor: this.#meta('sync_cursor'), databasePath: this.filePath, storage: 'SQLITE_WAL_FULL_SYNC',capacity:{databaseBytes:sqliteStorageBytes(this.filePath),logicalDatabaseBytes:sqliteLogicalBytes(this.db),maxDatabaseBytes:this.maxDatabaseBytes,ordinaryWriteLimitBytes:this.maxDatabaseBytes-this.storageReserveBytes,emergencyStorageReserveBytes:this.storageReserveBytes,transactionReserveBytes:this.transactionReserveBytes,retainedMutations:retainedTotal,maxRetainedMutations:this.maxRetainedMutations,maxPending:this.maxPending,pendingMutations:pendingTotal,p0RetainedMutations:retainedP0,p1RetainedMutations:Number(retained.p1),p0PendingMutations:pendingP0,p1PendingMutations:Number(pending.p1),priorityMutationReserve:this.priorityMutationReserve,priorityMutationReserveAccounting:{priority:'P0_LIFE_SAFETY',retainedUsed:retainedReserveUsed,retainedAvailable:Math.max(0,this.priorityMutationReserve-retainedReserveUsed),retainedNonP0Overcommit:Math.max(0,retainedTotal-retainedP0-this.maxRetainedMutations),pendingUsed:pendingReserveUsed,pendingAvailable:Math.max(0,this.priorityMutationReserve-pendingReserveUsed),pendingNonP0Overcommit:Math.max(0,pendingTotal-pendingP0-this.maxPending)},compactionCheckpoints:Number(this.db.prepare('SELECT count(*) count FROM mutation_compaction_checkpoint').get().count),maxHistoryRows:this.maxHistoryRows,maxHistoryBytes:this.maxHistoryBytes} }; }
  setConnectionState(state, actor = 'fieldnet-connection-monitor') { const prior = this.#meta('connection_state'); if (prior === state) return { prior, state, changed: false }; return this.#transaction(() => { this.#setMeta('connection_state', state); this.#audit(null, 'CONNECTION_STATE_CHANGED', actor, { prior, state }); return { prior, state, changed: true }; }); }
  #audit(incidentId, recordType, actor, payload) { const prior = this.db.prepare('SELECT sequence,record_hash FROM audit ORDER BY sequence DESC LIMIT 1').get(), createdAt = iso(this.clock), sequence = Number(prior?.sequence ?? 0) + 1, payloadHash = sha256(payload), id = stableId('field-audit', this.nodeId, sequence, recordType, payloadHash), material = { id, sequence, incidentId, recordType, actor, payloadHash, previousHash: prior?.record_hash ?? null, createdAt }, recordHash = sha256(material); this.db.prepare('INSERT INTO audit(sequence,id,incident_id,record_type,actor,payload_hash,previous_hash,record_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(sequence, id, incidentId, recordType, actor, payloadHash, prior?.record_hash ?? null, recordHash, createdAt); return { ...material, recordHash }; }
  #pendingCount() { return Number(this.db.prepare("SELECT count(*) count FROM sync_queue WHERE state IN ('PENDING','RETRY_EXHAUSTED')").get().count); }
  #mutation({ id, incidentId, type, actor, payload, priority = 'P3_TASK', causalMetadata = {}, clockQuality = 'SYNCED', queue = true,reserveEligible=false }) {
    const encoded = canonical(payload), bytes = Buffer.byteLength(encoded); if (bytes > this.maxPayloadBytes) { const error = new Error(`field_payload_too_large:${bytes}`); error.statusCode = 413; throw error; }
    const existing = this.db.prepare('SELECT payload_hash FROM mutation WHERE id=?').get(id); const payloadHash = sha256(encoded); if (existing) { if (existing.payload_hash !== payloadHash) throw new Error('mutation_id_payload_conflict'); return { id, duplicate: true }; }
    const emergencyEligible=reserveEligible===true&&priority==='P0_LIFE_SAFETY',storedPriority=emergencyEligible?'P0_LIFE_SAFETY':priority==='P0_LIFE_SAFETY'?'P1_COMMAND':priority,retainedState=this.db.prepare("SELECT count(*) total,sum(CASE WHEN priority='P0_LIFE_SAFETY' THEN 1 ELSE 0 END) p0 FROM mutation").get(),retained=Number(retainedState.total),retainedP0=Number(retainedState.p0),retainedReserveUsed=p0ReserveUsage({total:retained,p0:retainedP0,base:this.maxRetainedMutations});
    if((emergencyEligible&&retainedReserveUsed>=this.priorityMutationReserve)||(!emergencyEligible&&retained>=this.maxRetainedMutations))throw Object.assign(new Error('field_retained_mutation_capacity_reached'),{statusCode:507,details:{retained,p0RetainedMutations:retainedP0,maxRetainedMutations:this.maxRetainedMutations,priorityMutationReserve:this.priorityMutationReserve,priorityMutationReserveUsed:retainedReserveUsed,reservePriority:'P0_LIFE_SAFETY',reserveEligible:emergencyEligible,priority:storedPriority}});
    if (queue) { const pendingState=this.db.prepare("SELECT count(*) total,sum(CASE WHEN priority='P0_LIFE_SAFETY' THEN 1 ELSE 0 END) p0 FROM sync_queue WHERE state IN ('PENDING','RETRY_EXHAUSTED')").get(),pending=Number(pendingState.total),pendingP0=Number(pendingState.p0),pendingReserveUsed=p0ReserveUsage({total:pending,p0:pendingP0,base:this.maxPending}),queueLimit=this.maxPending+(emergencyEligible?this.priorityMutationReserve:0);if((emergencyEligible&&pendingReserveUsed>=this.priorityMutationReserve)||(!emergencyEligible&&pending>=this.maxPending)){const error=new Error('field_sync_queue_capacity_reached');error.statusCode=507;error.details={priority:storedPriority,pending,p0PendingMutations:pendingP0,queueLimit,protectedReserve:emergencyEligible?this.priorityMutationReserve:0,priorityMutationReserveUsed:pendingReserveUsed,reservePriority:'P0_LIFE_SAFETY',reserveEligible:emergencyEligible};throw error;} }
    const localSequence = Number(this.#meta('local_sequence')??0)+1, wallClockAt = iso(this.clock), syncState = queue ? 'PENDING' : 'ACKNOWLEDGED';this.#setMeta('local_sequence',localSequence);
    const mutation = { schemaVersion: 'vigia.field-mutation.v1', id, incidentId, originNode: this.nodeId, actor, type, localSequence, wallClockAt, clockQuality, causalMetadata: { ...causalMetadata, nodeSequence: localSequence }, payloadHash, payload, syncState, priority:storedPriority };
    this.db.prepare('INSERT INTO mutation(id,incident_id,origin_node,actor,type,priority,local_sequence,wall_clock_at,clock_quality,causal_metadata,payload_hash,payload,sync_state) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id, incidentId, this.nodeId, actor, type, storedPriority, localSequence, wallClockAt, clockQuality, text(mutation.causalMetadata), payloadHash, text(payload), syncState);
    if (queue) this.db.prepare("INSERT INTO sync_queue(id,mutation_id,priority,payload_bytes,state,created_at,updated_at) VALUES(?,?,?,?, 'PENDING',?,?)").run(stableId('sync-item', id), id, storedPriority, bytes, wallClockAt, wallClockAt);
    this.#audit(incidentId, type, actor, { mutationId: id, payloadHash, priority:storedPriority }); return mutation;
  }
  importPackage(pkg, actor = 'regional-vigia') {
    verifyIncidentPackage(pkg);return this.#transaction(() => {
      compactAcknowledgedMutations({db:this.db,nodeId:this.nodeId,clock:this.clock,maxRetainedMutations:this.maxRetainedMutations,priorityMutationReserve:this.priorityMutationReserve});
      const existing = this.db.prepare('SELECT payload_hash,payload FROM incident WHERE id=?').get(pkg.incidentId);
      const importedAt = iso(this.clock);
      if (existing) {
        const prior = parse(existing.payload);
        if (existing.payload_hash === pkg.evidenceHash) return { incident: prior, duplicate: true, upgraded: false };
        if (Date.parse(pkg.createdAt) <= Date.parse(prior.createdAt)) throw new Error('incident_package_version_not_newer');
        this.db.prepare('UPDATE incident SET package_id=?,payload_hash=?,payload=?,imported_at=?,last_sync_cursor=? WHERE id=?').run(pkg.packageId, pkg.evidenceHash, text(pkg), importedAt, pkg.lastSyncCursor, pkg.incidentId);
        this.#seedEvidenceDebt(pkg);
        this.#mutation({ id: stableId('field-mutation', pkg.packageId, 'upgrade'), incidentId: pkg.incidentId, type: 'INCIDENT_PACKAGE_UPDATED', actor, payload: { priorPackageId: prior.packageId, packageId: pkg.packageId, evidenceHash: pkg.evidenceHash, preservedLocalState: true }, priority: 'P3_TASK', queue: false });
        return { incident: pkg, duplicate: false, upgraded: true, priorPackageId: prior.packageId };
      }
      this.db.prepare('INSERT INTO incident(id,package_id,payload_hash,payload,imported_at,last_sync_cursor) VALUES(?,?,?,?,?,?)').run(pkg.incidentId, pkg.packageId, pkg.evidenceHash, text(pkg), importedAt, pkg.lastSyncCursor);
      this.#seedEvidenceDebt(pkg);
      this.#mutation({ id: stableId('field-mutation', pkg.packageId, 'import'), incidentId: pkg.incidentId, type: 'INCIDENT_PACKAGE_IMPORTED', actor, payload: { packageId: pkg.packageId, evidenceHash: pkg.evidenceHash }, priority: 'P3_TASK', queue: false });
      return { incident: pkg, duplicate: false, upgraded: false };
    });
  }
  incident(id) { const row = this.db.prepare('SELECT payload,imported_at,last_sync_cursor FROM incident WHERE id=?').get(id); return row ? { ...parse(row.payload), importedAt: row.imported_at, localSyncCursor: row.last_sync_cursor } : null; }
  incidents() { return this.#boundedPayloadRows('SELECT payload FROM incident ORDER BY imported_at').map((row) => parse(row.payload)); }
  commandSurvival(incidentId) {
    const incident=this.incident(incidentId);if(!incident)throw new Error('incident_not_found');
    const rows=this.#boundedPayloadRows("SELECT payload,sync_state syncState FROM mutation WHERE incident_id=? AND type='COMMAND_SURVIVAL_EVENT' ORDER BY local_sequence",[incidentId]),base=incident.commandSurvival?.events??[],local=rows.map((row)=>({event:parse(row.payload).event,syncState:row.syncState})),events=[...base,...local.map((item)=>item.event)];
    return{schemaVersion:'vigia.field-command-survival-state.v1',incidentId,state:events.length?replayIncidentCommand(events):emptyIncidentState(incidentId),events,localMutations:local,audit:this.verifyAudit()};
  }
  appendCommandSurvival(event,actor) { const incident=this.incident(event.incidentId);if(!incident)throw new Error('incident_not_found');applyIncidentCommandEvent(this.commandSurvival(event.incidentId).state,event);const reserveEligible=isLifeSafetyIncidentCommandType(event.type);return this.#transaction(() => { applyIncidentCommandEvent(this.commandSurvival(event.incidentId).state,event);const priority=reserveEligible?'P0_LIFE_SAFETY':'P1_COMMAND',mutation=this.#mutation({id:stableId('field-command-survival',event.eventId),incidentId:event.incidentId,type:'COMMAND_SURVIVAL_EVENT',actor,payload:{event},priority,reserveEligible,causalMetadata:{commandEventId:event.eventId,commandEventType:event.type}});return{event,mutation,duplicate:mutation.duplicate===true,state:this.commandSurvival(event.incidentId).state};},{protectedWrite:reserveEligible}); }
  #seedEvidenceDebt(pkg) {
    const updatedAt = iso(this.clock);
    for (const item of pkg.measurementDebt ?? []) {
      const payload = { ...item, incidentId:pkg.incidentId, revision:Number(item.revision ?? 1), source:'REGIONAL_INCIDENT_PACKAGE', updatedAt:item.updatedAt ?? updatedAt };
      this.db.prepare('INSERT OR IGNORE INTO evidence_debt(id,incident_id,state,revision,payload_hash,payload,updated_at) VALUES(?,?,?,?,?,?,?)').run(payload.id, pkg.incidentId, payload.currentState ?? 'OPEN', payload.revision, sha256(payload), text(payload), payload.updatedAt);
    }
  }
  evidenceDebt(incidentId) { return this.#boundedPayloadRows('SELECT payload FROM evidence_debt WHERE incident_id=? ORDER BY updated_at,id',[incidentId]).map((row)=>parse(row.payload)); }
  upsertEvidenceDebt(incidentId, item, actor) {
    return this.#transaction(() => {
      if (!this.incident(incidentId)) throw new Error('incident_not_found');
      if (!item?.id || !item?.question || !item?.currentState || !item?.closesWhen) throw new Error('evidence_debt_contract_required');
      const priorRow=this.db.prepare('SELECT payload_hash,payload,revision FROM evidence_debt WHERE id=?').get(item.id), prior=priorRow?parse(priorRow.payload):null;
      if (prior && prior.incidentId !== incidentId) throw new Error('evidence_debt_incident_identity_mismatch');
      const updatedAt=iso(this.clock), revision=Number(priorRow?.revision??0)+1;
      const payload={...prior,...item,id:item.id,incidentId,revision,updatedAt,lastActor:actor,source:prior?.source??'FIELDNET_LOCAL'};
      const payloadHash=sha256(payload);
      if (priorRow?.payload_hash===payloadHash) return { item:prior,duplicate:true,created:false };
      this.db.prepare('INSERT INTO evidence_debt(id,incident_id,state,revision,payload_hash,payload,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,revision=excluded.revision,payload_hash=excluded.payload_hash,payload=excluded.payload,updated_at=excluded.updated_at').run(payload.id,incidentId,payload.currentState,revision,payloadHash,text(payload),updatedAt);
      const type=prior?'EVIDENCE_DEBT_UPDATED':'EVIDENCE_DEBT_CREATED';
      const mutation=this.#mutation({id:stableId('field-mutation',payload.id,revision,payloadHash),incidentId,type,actor,payload,priority:'P3_TASK',causalMetadata:{evidenceDebtRevision:revision}});
      return {item:payload,mutation,duplicate:false,created:!prior};
    });
  }
  registerDevice(device, actor) { return this.#transaction(() => { const hash = sha256(device), existing = this.db.prepare('SELECT payload_hash,payload FROM device WHERE id=?').get(device.deviceId), incidentId = this.incidents()[0]?.incidentId ?? 'FIELDNET_REGISTRY'; if (existing) { const prior = parse(existing.payload); if (prior.hardwareIdentity !== device.hardwareIdentity || prior.deviceType !== device.deviceType || prior.ownerOperator !== device.ownerOperator) throw new Error('device_identity_conflict'); if (existing.payload_hash === hash) return { device: prior, duplicate: true, reconnected: true }; const updated = { ...prior, ...device, capabilities: [...new Set([...(prior.capabilities ?? []), ...(device.capabilities ?? [])])] }; this.db.prepare('UPDATE device SET payload_hash=?,payload=?,updated_at=? WHERE id=?').run(sha256(updated), text(updated), iso(this.clock), device.deviceId); this.#mutation({ id: stableId('field-mutation', device.deviceId, 'reconnected', updated.lastSeenAt), incidentId, type: 'DEVICE_RECONNECTED', actor, payload: updated, priority: 'P2_POSITION' }); return { device: updated, duplicate: false, reconnected: true }; } this.db.prepare('INSERT INTO device(id,payload_hash,payload,updated_at) VALUES(?,?,?,?)').run(device.deviceId, hash, text(device), iso(this.clock)); this.#mutation({ id: stableId('field-mutation', device.deviceId, hash), incidentId, type: 'DEVICE_REGISTERED', actor, payload: device, priority: 'P2_POSITION' }); return { device, duplicate: false, reconnected: false }; }); }
  device(id) { const row=this.db.prepare('SELECT payload FROM device WHERE id=?').get(id);return row?parse(row.payload):null; }
  devices() { return this.#boundedPayloadRows('SELECT payload FROM device ORDER BY id').map((row) => parse(row.payload)); }
  #edge(incidentId, fromId, toId, relation, payload = {}) { const id = stableId('truth-edge', incidentId, fromId, toId, relation); this.db.prepare('INSERT OR IGNORE INTO truth_edge(id,incident_id,from_id,to_id,relation,payload,created_at) VALUES(?,?,?,?,?,?,?)').run(id, incidentId, fromId, toId, relation, text(payload), iso(this.clock)); return id; }
  #verificationTask(conflict){return createFieldTask({taskId:stableId('field-task',conflict.conflictId,'verify'),incidentId:conflict.incidentId,subject:{conflictId:conflict.conflictId,subjectId:conflict.subjectId,geometry:conflict.versions?.find((item)=>item.geometry)?.geometry??null,reason:conflict.resolutionPlan?.recommendedVerificationTask},requiredAction:'Verify the preserved conflict with attributable independent evidence.',owner:null,priority:'P1_COMMAND',requiredEvidence:['INDEPENDENT_FIELD_CHECK','OBSERVER_AND_DEVICE_IDENTITY','GEOLOCATED_EVIDENCE'],createdAt:conflict.createdAt},{now:this.clock()});}
  #createTaskRecord(task,actor){if(!this.incident(task.incidentId))throw new Error('incident_not_found');const hash=sha256(task),existing=this.db.prepare('SELECT payload_hash,payload FROM task WHERE id=?').get(task.taskId);if(existing){if(existing.payload_hash!==hash)throw new Error('task_id_payload_conflict');return{task:parse(existing.payload),duplicate:true};}const now=iso(this.clock);this.db.prepare('INSERT INTO task(id,incident_id,version,state,payload_hash,payload,updated_at) VALUES(?,?,?,?,?,?,?)').run(task.taskId,task.incidentId,task.version,task.state,hash,text(task),now);const mutationId=stableId('field-mutation',task.taskId,'created');this.db.prepare('INSERT INTO task_version(task_id,version,mutation_id,actor,payload,created_at) VALUES(?,?,?,?,?,?)').run(task.taskId,task.version,mutationId,actor,text(task),now);this.#mutation({id:mutationId,incidentId:task.incidentId,type:'TASK_CREATED',actor,payload:task,priority:task.priority});if(task.owner)this.#mutation({id:stableId('field-mutation',task.taskId,'assigned',task.owner),incidentId:task.incidentId,type:'TASK_ASSIGNED',actor,payload:{taskId:task.taskId,owner:task.owner,taskVersion:task.version},priority:task.priority,causalMetadata:{taskVersion:task.version}});return{task,duplicate:false};}
  #conflict(conflict, actor = 'fieldnet-truth-engine', priority='P1_COMMAND') { const now = iso(this.clock),planned=withResolutionPlan({ ...conflict, createdAt: conflict.createdAt ?? now }),verificationTask=this.#verificationTask(planned),payload={...planned,verificationTaskId:verificationTask.taskId};const existing=this.db.prepare('SELECT payload FROM conflict WHERE id=?').get(payload.conflictId);if(existing){const prior=withResolutionPlan(parse(existing.payload)),storedTask=this.task(prior.verificationTaskId??verificationTask.taskId),task=storedTask?{task:storedTask,duplicate:true}:this.#createTaskRecord(verificationTask,'fieldnet-truth-engine');return{...prior,verificationTaskId:prior.verificationTaskId??verificationTask.taskId,verificationTask:task.task,verificationTaskDuplicate:task.duplicate};}const task=this.#createTaskRecord(verificationTask,'fieldnet-truth-engine');this.db.prepare('INSERT INTO conflict(id,incident_id,subject_type,subject_id,state,payload_hash,payload,created_at) VALUES(?,?,?,?,?,?,?,?)').run(payload.conflictId,payload.incidentId,payload.subjectType,payload.subjectId,payload.state,sha256(payload),text(payload),now);this.#mutation({id:stableId('field-mutation',payload.conflictId,'created'),incidentId:payload.incidentId,type:'CONFLICT_CREATED',actor,payload,priority});return{...payload,verificationTask:task.task,verificationTaskDuplicate:task.duplicate};}
  #repairConflictVerificationInvariant(){const rows=this.db.prepare("SELECT id,payload FROM conflict WHERE state='OPEN'").all();if(!rows.length)return;this.#transaction(()=>{for(const row of rows){const conflict=withResolutionPlan(parse(row.payload)),task=this.#verificationTask(conflict),payload=conflict.verificationTaskId?conflict:{...conflict,verificationTaskId:task.taskId};if(!this.task(payload.verificationTaskId))this.#createTaskRecord(task,'fieldnet-truth-engine');if(payload!==conflict)this.db.prepare('UPDATE conflict SET payload_hash=?,payload=? WHERE id=?').run(sha256(payload),text(payload),row.id);}return rows.length;});}
  addObservation(observation, actor) { return this.#transaction(() => { if (!this.incident(observation.incidentId)) throw new Error('incident_not_found'); const device = this.db.prepare('SELECT payload FROM device WHERE id=?').get(observation.deviceId); if (!device) throw new Error('device_not_registered'); const hash = sha256(observation), existing = this.db.prepare('SELECT payload_hash,payload FROM observation WHERE id=?').get(observation.observationId); if (existing) { if (existing.payload_hash !== hash) throw new Error('observation_id_payload_conflict'); return { observation: parse(existing.payload), duplicate: true, conflicts: [] }; }
    const subjectKey = observation.payload?.subjectKey ?? null, claimField = observation.payload?.claimField ?? null, claimValue = observation.payload?.claimValue === undefined ? null : canonical(observation.payload.claimValue);
    this.db.prepare('INSERT INTO observation(id,incident_id,device_id,observed_at,received_at,observation_type,subject_key,claim_field,claim_value,payload_hash,payload,sync_state) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(observation.observationId, observation.incidentId, observation.deviceId, observation.observedAt, observation.receivedAt, observation.observationType, subjectKey, claimField, claimValue, hash, text(observation), 'PENDING');
    const mutation = this.#mutation({ id: stableId('field-mutation', observation.observationId, hash), incidentId: observation.incidentId, type: 'FIELD_OBSERVATION_ADDED', actor, payload: observation, priority: ['ROAD_OBSTRUCTION','ACCESS_CONDITION','VISUAL_FLAME','VISUAL_SMOKE','ROAD_ACCESS','FIRE_SMOKE','FIELD_BOUNDARY_POINT'].includes(observation.observationType) ? 'P2_POSITION' : 'P4_TELEMETRY', causalMetadata: observation.causalMetadata, clockQuality: observation.deviceClockQuality });
    this.#edge(observation.incidentId, observation.observationId, `claim:${subjectKey ?? observation.observationId}`, 'SUPPORTS', { claimField, claimValue: observation.payload?.claimValue });
    const prior = this.db.prepare('SELECT payload FROM observation WHERE incident_id=? AND id<>? AND subject_key=? ORDER BY received_at DESC').all(observation.incidentId, observation.observationId, subjectKey).map((row) => parse(row.payload)), conflicts = [],verificationTasks=[];
    for (const other of prior) { const relation = observationRelationship(observation, other); if (relation === 'UNRELATED') continue; this.#edge(observation.incidentId, observation.observationId, other.observationId, relation); if (relation === 'CONTRADICTS') { this.#edge(observation.incidentId, other.observationId, observation.observationId, relation); const conflictId = stableId('reconciliation-conflict', observation.incidentId, ...[observation.observationId, other.observationId].sort()), conflict = this.#conflict({ schemaVersion: 'vigia.reconciliation-conflict.v1', conflictId, incidentId: observation.incidentId, subjectType: 'FIELD_OBSERVATION', subjectId: subjectKey, versions: [other, observation], causalRelationship: 'INDEPENDENT_OBSERVATIONS', conflictingFields: [claimField], recommendedMergePossibilities: ['VERIFY_IN_FIELD','MARK_CONTEXT_DEPENDENT','SUPERSEDE_WITH_CALIBRATED_EVIDENCE'], resolutionRequirement: 'HUMAN_OR_NEW_EVIDENCE_REQUIRED', state: 'OPEN' }); conflicts.push(conflict);verificationTasks.push({task:conflict.verificationTask,duplicate:conflict.verificationTaskDuplicate}); } }
    return { observation, duplicate: false, mutation, conflicts,verificationTasks }; }); }
  observations(incidentId) { return this.#boundedPayloadRows('SELECT payload,sync_state FROM observation WHERE incident_id=? ORDER BY received_at,id',[incidentId]).map((row) => ({ ...parse(row.payload), syncState: row.sync_state })); }
  createTask(task, actor) { return this.#transaction(() => this.#createTaskRecord(task,actor)); }
  task(id) { const row = this.db.prepare('SELECT payload FROM task WHERE id=?').get(id); return row ? parse(row.payload) : null; }
  taskLifecycle(id) { const task=this.task(id);return task?projectPersistedTaskLifecycle({db:this.db,task,clock:this.clock}):null; }
  tasks(incidentId) { return this.#boundedPayloadRows('SELECT payload FROM task WHERE incident_id=? ORDER BY updated_at,id',[incidentId]).map((row) => parse(row.payload)); }
  taskAcknowledgements(taskId) { return this.#boundedRows('SELECT a.*,m.sync_state mutation_sync_state FROM acknowledgement a LEFT JOIN mutation m ON m.id=a.id WHERE a.task_id=? ORDER BY a.created_at,a.id',[taskId]).map((row)=>({...((row.payload?parse(row.payload):({schemaVersion:'vigia.field-acknowledgement.v1',acknowledgementId:row.id,taskId:row.task_id,incidentId:row.incident_id,actor:row.actor,taskVersion:row.task_version,nodeId:row.node_id,note:row.note,acknowledgedAt:row.created_at}))),syncState:row.mutation_sync_state??'ACKNOWLEDGED'})); }
  acknowledgeTask(taskId, input) { return this.#transaction(() => {
    const { actor, note = null, taskVersion }=input,task=this.task(taskId);if(!task)throw new Error('task_not_found');
    const version=Number(taskVersion??task.version),structured=input.schemaVersion==='vigia.field-task-acknowledgement.v1',acknowledgementId=input.acknowledgementId??stableId('field-ack',taskId,actor,version),existing=this.db.prepare('SELECT * FROM acknowledgement WHERE id=?').get(acknowledgementId),{actor:_ackActor,...structuredAck}=input;
    const acknowledgedAt=structured?input.acknowledgedAt:iso(this.clock),ack=structured?{...structuredAck,nodeId:this.nodeId}:{schemaVersion:'vigia.field-acknowledgement.v1',acknowledgementId,taskId,incidentId:task.incidentId,actor,taskVersion:version,nodeId:this.nodeId,note,acknowledgedAt};
    if(existing){if(structured&&existing.payload_hash!==sha256(ack))throw new Error('acknowledgement_id_payload_conflict');return{acknowledgement:existing.payload?parse(existing.payload):ack,duplicate:true,task:this.task(taskId)};}
    if(version!==task.version)throw new Error('task_version_changed');
    const disposition=structured?ack.disposition:'ACCEPTED',nextState=disposition==='ACCEPTED'?(task.state==='OPEN'||task.state==='ASSIGNED'?'ACKNOWLEDGED':task.state):'BLOCKED',updated={...task,state:nextState,acknowledgedAt,version:task.version+1,lastActor:actor,lastAcknowledgement:{acknowledgementId,disposition,safetyState:ack.safetyState??null,acknowledgedAt}};
    this.db.prepare('UPDATE task SET version=?,state=?,payload_hash=?,payload=?,updated_at=? WHERE id=?').run(updated.version,updated.state,sha256(updated),text(updated),acknowledgedAt,taskId);
    this.db.prepare('INSERT INTO task_version(task_id,version,mutation_id,actor,payload,created_at) VALUES(?,?,?,?,?,?)').run(taskId,updated.version,acknowledgementId,actor,text(updated),acknowledgedAt);
    this.db.prepare('INSERT INTO acknowledgement(id,task_id,incident_id,actor,task_version,node_id,note,created_at,payload_hash,payload) VALUES(?,?,?,?,?,?,?,?,?,?)').run(acknowledgementId,taskId,task.incidentId,actor,version,this.nodeId,note,acknowledgedAt,sha256(ack),text(ack));
    const mutation=this.#mutation({id:acknowledgementId,incidentId:task.incidentId,type:'TASK_ACKNOWLEDGED',actor,payload:ack,priority:task.priority,causalMetadata:{taskVersion:version,disposition}}),stateMutation=disposition==='ACCEPTED'?null:this.#mutation({id:stableId('field-mutation',acknowledgementId,'blocked'),incidentId:task.incidentId,type:'TASK_UPDATED',actor,payload:{taskId,baseVersion:version,changes:{state:'BLOCKED'},applied:true,outcome:'APPLY',acknowledgementId,reason:disposition},priority:task.priority,causalMetadata:{taskVersion:version,acknowledgementId,disposition}});
    return{acknowledgement:ack,duplicate:false,task:updated,mutation,stateMutation};
  }); }
  completeTask(taskId, input) { return this.#transaction(()=>{
    const task=this.task(taskId);if(!task)throw new Error('task_not_found');if(task.taskType!=='FIELD_VERIFICATION')throw new Error('field_verification_task_required');
    if(task.lastCompletion?.completionId===input.completionId){if(task.lastCompletion.completionHash!==input.completionHash)throw new Error('field_task_completion_id_payload_conflict');return{completion:task.lastCompletion,duplicate:true,task};}
    if(Number(input.taskVersion)!==task.version)throw new Error('task_version_changed');
    const accepted=this.taskAcknowledgements(taskId).some((ack)=>ack.disposition===undefined||ack.disposition==='ACCEPTED');if(!accepted)throw new Error('field_task_accepted_acknowledgement_required');
    const evidence=(input.evidenceObservationIds??[]).map((id)=>{const row=this.db.prepare('SELECT payload FROM observation WHERE id=?').get(id),observation=row?parse(row.payload):null;if(!observation)throw new Error('field_task_completion_observation_not_found');if(observation.incidentId!==task.incidentId)throw new Error('field_task_completion_incident_mismatch');if(observation.causalMetadata?.linkedTaskId!==taskId)throw new Error('field_task_completion_evidence_not_linked');return observation;});
    if(task.expectedReportTypes?.length&&!evidence.some((observation)=>task.expectedReportTypes.includes(observation.reportType??observation.observationType)))throw new Error('field_task_completion_expected_report_missing');
    const updatedAt=input.completedAt,{actor:_completionActor,...completionInput}=input,completion={...completionInput,nodeId:this.nodeId,syncState:'PENDING'},updated={...task,state:'COMPLETED',version:task.version+1,lastActor:input.actor,completedAt:updatedAt,completionEvidence:evidence.map((observation)=>({observationId:observation.observationId,reportType:observation.reportType??observation.observationType,rawEvidenceHash:observation.rawEvidenceHash})),lastCompletion:completion};
    this.db.prepare('UPDATE task SET version=?,state=?,payload_hash=?,payload=?,updated_at=? WHERE id=?').run(updated.version,updated.state,sha256(updated),text(updated),updatedAt,taskId);
    this.db.prepare('INSERT INTO task_version(task_id,version,mutation_id,actor,payload,created_at) VALUES(?,?,?,?,?,?)').run(taskId,updated.version,input.completionId,input.actor,text(updated),updatedAt);
    const mutation=this.#mutation({id:input.completionId,incidentId:task.incidentId,type:'TASK_UPDATED',actor:input.actor,payload:{taskId,baseVersion:input.taskVersion,changes:{state:'COMPLETED'},applied:true,outcome:'APPLY',completion},priority:task.priority,causalMetadata:{taskVersion:input.taskVersion,evidenceObservationIds:input.evidenceObservationIds}});
    return{completion,duplicate:false,task:updated,mutation};
  }); }
  acknowledgeAlert(incidentId, alertId, { actor, note = null, alertVersion = 1 }) { return this.#transaction(() => { const incident = this.incident(incidentId); if (!incident) throw new Error('incident_not_found'); const alert = (incident.currentAlerts ?? []).find((item) => item.id === alertId); if (!alert) throw new Error('alert_not_found'); const version = Number(alertVersion), expectedVersion = Number(alert.version ?? 1); if (version !== expectedVersion) throw new Error('alert_version_changed'); const acknowledgementId = stableId('field-alert-ack', incidentId, alertId, actor, version), existing = this.db.prepare('SELECT * FROM alert_acknowledgement WHERE id=?').get(acknowledgementId); if (existing) return { acknowledgement: { acknowledgementId, alertId, incidentId, actor, alertVersion: version, nodeId: existing.node_id, note: existing.note, acknowledgedAt: existing.created_at }, duplicate: true }; const acknowledgedAt = iso(this.clock), acknowledgement = { schemaVersion: 'vigia.field-alert-acknowledgement.v1', acknowledgementId, alertId, incidentId, actor, alertVersion: version, nodeId: this.nodeId, note, acknowledgedAt }; this.db.prepare('INSERT INTO alert_acknowledgement(id,alert_id,incident_id,actor,alert_version,node_id,note,created_at,payload_hash) VALUES(?,?,?,?,?,?,?,?,?)').run(acknowledgementId, alertId, incidentId, actor, version, this.nodeId, note, acknowledgedAt, sha256(acknowledgement)); this.#mutation({ id: acknowledgementId, incidentId, type: 'LOCAL_ALERT_ACKNOWLEDGED', actor, payload: acknowledgement, priority: 'P1_COMMAND', causalMetadata: { alertVersion: version } }); return { acknowledgement, duplicate: false }; }); }
  mutateTask(taskId, { mutationId, actor, baseVersion, changes, causalMetadata = {} }) { return this.#transaction(() => { const task = this.task(taskId); if (!task) throw new Error('task_not_found'); const comparison = compareTaskMutation({ task, baseVersion, changes, actor, mutationId }),safeChanges=comparison.changes;if(['P0_LIFE_SAFETY','P1_COMMAND'].includes(task.priority))throw Object.assign(new Error('protected_task_mutation_requires_command_semantic'),{statusCode:403});if (comparison.outcome === 'CONFLICT') { const conflict = this.#conflict(comparison.conflict, actor,'P3_TASK'); const mutation = this.#mutation({ id: mutationId, incidentId: task.incidentId, type: 'TASK_UPDATED', actor, payload: { taskId, baseVersion, changes:safeChanges, applied: false, conflictId: conflict.conflictId }, priority: 'P3_TASK', causalMetadata }); return { outcome: 'CONFLICT', task, conflict, mutation }; }
    const now = iso(this.clock), updated = { ...comparison.applied, lastActor: actor, updatedAt: now }; this.db.prepare('UPDATE task SET version=?,state=?,payload_hash=?,payload=?,updated_at=? WHERE id=?').run(updated.version, updated.state, sha256(updated), text(updated), now, taskId); this.db.prepare('INSERT INTO task_version(task_id,version,mutation_id,actor,payload,created_at) VALUES(?,?,?,?,?,?)').run(taskId, updated.version, mutationId, actor, text(updated), now); const mutation = this.#mutation({ id: mutationId, incidentId: task.incidentId, type: 'TASK_UPDATED', actor, payload: { taskId, baseVersion, changes:safeChanges, applied: true, outcome: comparison.outcome }, priority: updated.priority, causalMetadata }); return { outcome: comparison.outcome, task: updated, mutation }; }); }
  addAnnotation({ mutationId, incidentId, actor, subjectId, body, priority = 'P3_TASK', causalMetadata = {} }) { return this.#transaction(() => { if (!this.incident(incidentId)) throw new Error('incident_not_found');const safePriority=['P3_TASK','P4_TELEMETRY','P5_THUMBNAIL','P6_BULK_MEDIA'].includes(priority)?priority:'P3_TASK'; return { outcome: 'AUTO_MERGE', mutation: this.#mutation({ id: mutationId, incidentId, type: 'ANNOTATION_ADDED', actor, payload: { subjectId, body }, priority:safePriority, causalMetadata }) }; }); }
  conflicts(incidentId, state = null) { return this.#boundedPayloadRows('SELECT payload FROM conflict WHERE incident_id=? AND (? IS NULL OR state=?) ORDER BY created_at,id',[incidentId,state,state]).map((row) => withResolutionPlan(parse(row.payload))); }
  conflict(id) { const row=this.db.prepare('SELECT payload FROM conflict WHERE id=?').get(id);return row?withResolutionPlan(parse(row.payload)):null; }
  resolveConflict(conflictId, { actor, strategy, values = {} }) { return this.#transaction(() => { const row = this.db.prepare('SELECT payload FROM conflict WHERE id=?').get(conflictId); if (!row) throw new Error('conflict_not_found'); const conflict = parse(row.payload); if (conflict.state === 'RESOLVED') return { conflict, duplicate: true }; let task = null,safeValues={}; if (conflict.subjectType === 'FIELD_TASK') { task = this.task(conflict.subjectId); const selected = strategy === 'ACCEPT_OFFLINE' ? conflict.versions.find((item) => item.origin === 'OFFLINE_MUTATION')?.values : strategy === 'KEEP_CURRENT' ? conflict.versions.find((item) => item.origin === 'CURRENT_LOCAL')?.values : values; if (!selected) throw new Error('conflict_resolution_values_required'); safeValues=sanitizeTaskChanges(selected); const now = iso(this.clock); task = { ...task, ...safeValues,taskId:task.taskId,incidentId:task.incidentId,schemaVersion:task.schemaVersion, version: task.version + 1, lastActor: actor, updatedAt: now }; this.db.prepare('UPDATE task SET version=?,state=?,payload_hash=?,payload=?,updated_at=? WHERE id=?').run(task.version, task.state, sha256(task), text(task), now, task.taskId); this.db.prepare('INSERT INTO task_version(task_id,version,mutation_id,actor,payload,created_at) VALUES(?,?,?,?,?,?)').run(task.taskId, task.version, stableId('field-mutation', conflictId, 'resolved'), actor, text(task), now); }
    const resolvedAt = iso(this.clock), resolved = { ...conflict, state: 'RESOLVED', resolution: { strategy, values:safeValues, actor, resolvedAt } }; this.db.prepare('UPDATE conflict SET state=?,payload_hash=?,payload=?,resolved_at=? WHERE id=?').run('RESOLVED', sha256(resolved), text(resolved), resolvedAt, conflictId); this.#mutation({ id: stableId('field-mutation', conflictId, 'resolved'), incidentId: conflict.incidentId, type: 'CONFLICT_RESOLVED', actor, payload: { conflictId, strategy, values:safeValues, task }, priority: 'P1_COMMAND' }); return { conflict: resolved, task, duplicate: false }; }); }
  truthGraph(incidentId) { const incident = this.incident(incidentId); if (!incident) throw new Error('incident_not_found'); const observations = this.observations(incidentId), regionalObservations = incident.physicalObservations ?? [], devices = this.devices(), tasks = this.tasks(incidentId), conflicts = this.conflicts(incidentId), regionalSources = Object.values(incident.sourceFreshness ?? {}).map((item) => sourceFreshness(item, { now: this.clock() })); const persistedEdges = this.#boundedPayloadRows('SELECT id,from_id fromId,to_id toId,relation,payload,created_at createdAt FROM truth_edge WHERE incident_id=? ORDER BY created_at,id',[incidentId]).map((row) => ({ ...row, payload: parse(row.payload) })), regionalEdges = [...regionalObservations.map((item) => ({ id: stableId('truth-edge', incidentId, item.observationId, incidentId, 'SUPPORTS'), fromId: item.observationId, toId: incidentId, relation: 'SUPPORTS', payload: { sourceFamily: item.sourceFamily, qualification: 'CACHED_REGIONAL_PHYSICAL_EVIDENCE' }, createdAt: incident.createdAt })), ...regionalSources.map((item) => ({ id: stableId('truth-edge', incidentId, `source:${item.sourceFamily}`, incidentId, 'SUPPORTS'), fromId: `source:${item.sourceFamily}`, toId: incidentId, relation: 'SUPPORTS', payload: { freshnessState: item.state, qualification: item.qualification }, createdAt: incident.createdAt }))]; return { schemaVersion: 'vigia.field-truth-graph.v1', incidentId, generatedAt: iso(this.clock), nodes: [{ id: incidentId, kind: 'INCIDENT', payload: incident.incidentState }, ...regionalObservations.map((item) => ({ id: item.observationId, kind: 'REGIONAL_PHYSICAL_OBSERVATION', payload: item })), ...regionalSources.map((item) => ({ id: `source:${item.sourceFamily}`, kind: 'SOURCE_FRESHNESS', payload: item })), ...observations.map((item) => ({ id: item.observationId, kind: 'OBSERVATION', payload: item })), ...devices.map((item) => ({ id: item.deviceId, kind: 'DEVICE', payload: item })), ...tasks.map((item) => ({ id: item.taskId, kind: 'TASK', payload: item })), ...conflicts.map((item) => ({ id: item.conflictId, kind: 'CONFLICT', payload: item }))], edges: [...regionalEdges, ...persistedEdges], currentOperationalInterpretation: { state: conflicts.some((item) => item.state === 'OPEN') ? 'CONFLICT_REQUIRES_VERIFICATION' : 'LOCAL_EVIDENCE_AVAILABLE', openConflictCount: conflicts.filter((item) => item.state === 'OPEN').length, regionalSourceFreshness: regionalSources.map(({ sourceFamily, state, ageMs }) => ({ sourceFamily, state, ageMs })), localObservationCount: observations.length }, notice: 'Conflicting observations remain separate; cached regional sources are never CURRENT_LOCAL; human reports are not promoted to production physical sensor families.' }; }
  pendingSync({ mode = this.#meta('connection_state'), limit = 100, maxBytes = 1_000_000,incidentId=null } = {}) { let used = 0;const scope=incidentId?String(incidentId):null,boundedLimit=Math.max(1,Math.min(1000,limit)); const rows = this.db.prepare("SELECT q.*,m.payload mutation_payload,m.payload_hash,m.incident_id,m.origin_node,m.actor,m.type,m.local_sequence,m.wall_clock_at,m.clock_quality,m.causal_metadata FROM sync_queue q JOIN mutation m ON m.id=q.mutation_id WHERE q.state IN ('PENDING','RETRY_EXHAUSTED') AND (q.next_attempt_at IS NULL OR q.next_attempt_at<=?) AND (? IS NULL OR m.incident_id=?) ORDER BY CASE q.priority WHEN 'P0_LIFE_SAFETY' THEN 0 WHEN 'P1_COMMAND' THEN 1 WHEN 'P2_POSITION' THEN 2 WHEN 'P3_TASK' THEN 3 WHEN 'P4_TELEMETRY' THEN 4 WHEN 'P5_THUMBNAIL' THEN 5 ELSE 6 END,m.local_sequence LIMIT ?").all(iso(this.clock),scope,scope,boundedLimit); const items = []; for (const row of rows) { const disposition = priorityDisposition(row.priority, mode); if (!['SEND_IMMEDIATELY','BATCH'].includes(disposition) || used + row.payload_bytes > maxBytes) continue; used += row.payload_bytes; items.push({ queueId: row.id, mutationId: row.mutation_id, priority: row.priority, disposition, payloadBytes: row.payload_bytes, attemptCount:Number(row.attempts??0),nextAttempt:row.next_attempt_at??null,lastError:row.last_error??null,createdAt:row.created_at,updatedAt:row.updated_at,mutation: { id: row.mutation_id, incidentId: row.incident_id, originNode: row.origin_node, actor: row.actor, type: row.type, priority: row.priority, localSequence: row.local_sequence, wallClockAt: row.wall_clock_at, clockQuality: row.clock_quality, causalMetadata: parse(row.causal_metadata), payloadHash: row.payload_hash, payload: parse(row.mutation_payload) } }); } const pendingTotal=scope?Number(this.db.prepare("SELECT count(*) count FROM sync_queue q JOIN mutation m ON m.id=q.mutation_id WHERE q.state IN ('PENDING','RETRY_EXHAUSTED') AND m.incident_id=?").get(scope).count):this.#pendingCount();return { mode, items, totalBytes: used, pendingTotal }; }
  recordSyncAttempt(items, error = null) { return this.#transaction(() => {
    const now = iso(this.clock);
    for (const item of items) {
      const row = this.db.prepare('SELECT attempts FROM sync_queue WHERE id=?').get(item.queueId), attempts = Number(row?.attempts ?? 0) + 1, failed = Boolean(error), exhausted = failed && attempts >= 5, state = exhausted ? 'RETRY_EXHAUSTED' : failed ? 'PENDING' : 'SENT', next = failed ? new Date(this.clock().getTime() + Math.min(60_000, 1000 * (2 ** Math.min(attempts,16)))).toISOString() : null;
      this.db.prepare('UPDATE sync_queue SET state=?,attempts=?,next_attempt_at=?,last_error=?,updated_at=? WHERE id=?').run(state, attempts, next, error ? String(error).slice(0, 200) : null, now, item.queueId);
      if (!error) { this.db.prepare("UPDATE mutation SET sync_state='ACKNOWLEDGED' WHERE id=?").run(item.mutationId); this.db.prepare("UPDATE observation SET sync_state='ACKNOWLEDGED' WHERE id IN (SELECT json_extract(payload,'$.observationId') FROM mutation WHERE id=?)").run(item.mutationId);if(item.mutation?.type==='TASK_UPDATED'&&item.mutation?.payload?.completion){const taskId=item.mutation.payload.taskId,task=this.task(taskId);if(task){const updated={...task,lastCompletion:{...task.lastCompletion,syncState:'ACKNOWLEDGED_CENTRAL',centralReconciledAt:now}};this.db.prepare('UPDATE task SET payload_hash=?,payload=?,updated_at=? WHERE id=?').run(sha256(updated),text(updated),now,taskId);}} }
    }
    const compaction=error?{compacted:0,checkpointId:null}:compactAcknowledgedMutations({db:this.db,nodeId:this.nodeId,clock:this.clock,maxRetainedMutations:this.maxRetainedMutations,priorityMutationReserve:this.priorityMutationReserve});
    this.#audit(items[0]?.mutation?.incidentId ?? null, error ? 'SYNC_FAILED' : 'SYNC_ACKNOWLEDGED', 'fieldnet-sync-engine', { mutationIds: items.map((item) => item.mutationId), error: error ? String(error).slice(0, 100) : null,compaction });
    return { attempted: items.length, error: error ? String(error) : null,compaction };
  }); }
  applyInbound(updates = []) { if(!Array.isArray(updates))throw new Error('central_updates_array_required');const encodedBytes=Buffer.byteLength(JSON.stringify(updates)),estimatedBytes=Math.max(this.transactionReserveBytes,encodedBytes*8+updates.length*16_384);return this.#transaction(() => { const compaction=compactAcknowledgedMutations({db:this.db,nodeId:this.nodeId,clock:this.clock,maxRetainedMutations:this.maxRetainedMutations,priorityMutationReserve:this.priorityMutationReserve});let merged = 0, duplicate = 0; for (const update of updates) { if(update?.type!=='CENTRAL_EVENT_SNAPSHOT')throw new Error('central_update_type_invalid');if(!update.id||!update.incidentId)throw new Error('central_update_identity_required');if (!this.incident(update.incidentId)) throw new Error('central_update_incident_identity_mismatch'); const id = update.id; const existing = this.db.prepare('SELECT 1 FROM mutation WHERE id=?').get(id); if (existing) { duplicate += 1; continue; } if(!update.payload||typeof update.payload!=='object'||Array.isArray(update.payload))throw new Error('central_update_payload_invalid');this.#mutation({ id, incidentId: update.incidentId, type: 'CENTRAL_EVENT_SNAPSHOT', actor: 'regional-vigia', payload: update.payload, priority: 'P3_TASK', causalMetadata: {}, queue: false }); merged += 1; } return { merged, duplicate,compaction }; },{estimatedBytes}); }
  updateCursor(cursor) { const safe=boundedSyncCursor(cursor);return this.#transaction(()=>{this.#setMeta('sync_cursor',safe);return safe;}); }
  audit(incidentId = null) { return this.#boundedRows('SELECT sequence,id,incident_id incidentId,record_type recordType,actor,payload_hash payloadHash,previous_hash previousHash,record_hash recordHash,created_at createdAt FROM audit WHERE (? IS NULL OR incident_id=?) ORDER BY sequence',[incidentId,incidentId]); }
  verifyAudit() { let previous = null,afterSequence=0,records=0;const pageSize=Math.max(1,Math.min(this.maxHistoryRows,512)),statement=this.db.prepare('SELECT sequence,id,incident_id incidentId,record_type recordType,actor,payload_hash payloadHash,previous_hash previousHash,record_hash recordHash,created_at createdAt FROM audit WHERE sequence>? ORDER BY sequence LIMIT ?');while(true){const rows=statement.all(afterSequence,pageSize);for(const row of rows){const material={id:row.id,sequence:row.sequence,incidentId:row.incidentId,recordType:row.recordType,actor:row.actor,payloadHash:row.payloadHash,previousHash:row.previousHash,createdAt:row.createdAt};if(row.previousHash!==previous||sha256(material)!==row.recordHash)return{valid:false,failedSequence:row.sequence};previous=row.recordHash;afterSequence=row.sequence;records+=1;}if(rows.length<pageSize)break;}return{valid:true,records,headHash:previous}; }
  replay(incidentId) { return { schemaVersion: 'vigia.fieldnet-disconnection-replay.v2', incidentId, generatedAt: iso(this.clock), offlineMap:this.offlineMap(incidentId), evidenceDebt:this.evidenceDebt(incidentId), audit: this.audit(incidentId), mutations: this.#boundedPayloadRows('SELECT id,origin_node originNode,actor,type,local_sequence localSequence,wall_clock_at wallClockAt,clock_quality clockQuality,causal_metadata causalMetadata,payload_hash payloadHash,payload,sync_state syncState FROM mutation WHERE incident_id=? ORDER BY local_sequence',[incidentId]).map((row) => ({ ...row, causalMetadata: parse(row.causalMetadata), payload: parse(row.payload) })), conflicts: this.conflicts(incidentId) }; }
  offlineMap(incidentId) {
    const incident = this.incident(incidentId);
    if (!incident) return null;
    const observations = this.observations(incidentId), conflicts = this.conflicts(incidentId);
    const anchorGeometry = incident.offlineMap?.incidentAnchor ? { type: 'Point', coordinates: incident.offlineMap.incidentAnchor.coordinates } : null;
    const conflictGeometry = (conflict) => conflict?.versions?.find((version) => version.geometry)?.geometry ?? null;
    const tasks = this.tasks(incidentId).map((task) => {
      const linkedConflict = conflicts.find((conflict) => conflict.conflictId === task.subject?.conflictId);
      const geometry = task.geometry ?? task.subject?.geometry ?? conflictGeometry(linkedConflict) ?? anchorGeometry;
      return { ...task, geometry, locationQualification: task.geometry || task.subject?.geometry ? 'TASK_LOCATION' : linkedConflict ? 'INFERRED_FROM_CONFLICT_EVIDENCE' : 'INCIDENT_ANCHOR_FALLBACK' };
    });
    const mappedConflicts = conflicts.map((conflict) => {
      const linkedTask = tasks.find((task) => task.taskId === conflict.subjectId || task.subject?.conflictId === conflict.conflictId);
      return { ...conflict, geometry: conflictGeometry(conflict) ?? linkedTask?.geometry ?? anchorGeometry };
    });
    return {
      schemaVersion: 'vigia.fieldnet-offline-map.v1',
      incidentId,
      region: incident.offlineMap?.region ?? incident.offlineMap,
      incidentAnchor: incident.offlineMap?.incidentAnchor ?? null,
      baseLayer: incident.offlineMap?.baseLayer ?? { state: 'NOT_PACKAGED', qualification: 'Local vector overlays remain available without WAN; raster/terrain tiles are not claimed.' },
      layers: {
        regionalPhysicalObservations: incident.physicalObservations,
        monitoredAssets: (incident.monitoredAssets ?? []).map((asset) => ({ ...asset, displayName: asset.name ?? 'Unidentified reference feature' })),
        localObservations: observations,
        tasks,
        conflicts: mappedConflicts,
        annotations: this.#boundedPayloadRows("SELECT payload FROM mutation WHERE incident_id=? AND type='ANNOTATION_ADDED' ORDER BY local_sequence",[incidentId]).map((row) => parse(row.payload))
      }
    };
  }
  metrics(incidentId) { const one = (sql, ...args) => Number(this.db.prepare(sql).get(...args).count); return { incidents: one('SELECT count(*) count FROM incident'), observations: one('SELECT count(*) count FROM observation WHERE incident_id=?', incidentId), tasks: one('SELECT count(*) count FROM task WHERE incident_id=?', incidentId), acknowledgements: one('SELECT count(*) count FROM acknowledgement WHERE incident_id=?', incidentId), alertAcknowledgements: one('SELECT count(*) count FROM alert_acknowledgement WHERE incident_id=?', incidentId), evidenceDebt:one('SELECT count(*) count FROM evidence_debt WHERE incident_id=?',incidentId), openEvidenceDebt:one("SELECT count(*) count FROM evidence_debt WHERE incident_id=? AND state NOT IN ('MEASURED','RESOLVED')",incidentId), mutations: one('SELECT count(*) count FROM mutation WHERE incident_id=?', incidentId), openConflicts: one("SELECT count(*) count FROM conflict WHERE incident_id=? AND state='OPEN'", incidentId), resolvedConflicts: one("SELECT count(*) count FROM conflict WHERE incident_id=? AND state='RESOLVED'", incidentId), pendingSync: one("SELECT count(*) count FROM sync_queue WHERE state IN ('PENDING','RETRY_EXHAUSTED')"), failedSync: one("SELECT count(*) count FROM sync_queue WHERE state='RETRY_EXHAUSTED'"), sentSync: one("SELECT count(*) count FROM sync_queue WHERE state='SENT'"), duplicateIncidents: 0, audit: this.verifyAudit() }; }
}
