import {icon} from '../ui/icons.js';
import {e,badge,button,link,panel,empty,select,kv} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {PhysicalInline} from '../ui/physical.js';
import {incidentsFor,filterIncidents,incidentFor,isLimited,timeLabel} from '../data/model.js';
export function incidents(state,ui){const list=incidentsFor(state),filtered=filterIncidents(list,ui.incidentFilters),size=7,pages=Math.max(1,Math.ceil(filtered.length/size));ui.page=Math.min(ui.page,pages);const page=filtered.slice((ui.page-1)*size,ui.page*size),selected=incidentFor(state),limited=isLimited(state);
 return `<div class="route-stack incidents-route approved-route ${state.runtime.approvedMobilePreview?'mobile-preview-open':''}"><div class="search-box search-field">${icon('search')}<input id="incident-search" type="search" aria-label="Search incidents" placeholder="Search by name, location, or ID…" value="${e(ui.incidentFilters.search)}" data-input="incident-search">${ui.incidentFilters.search?button('Clear search','clear-search',{tone:'icon-button',ico:'close'}):''}</div>
 <details class="incident-filter-options" data-responsive-disclosure="incident-filters" open><summary>Filter incidents</summary><div class="filter-row">${select('Incident status','incident-status',state.statusOptions,ui.incidentFilters.status)}${select('Incident type','incident-type',state.typeOptions,ui.incidentFilters.type)}${select('Incident priority','incident-priority',state.priorityOptions,ui.incidentFilters.priority)}${button('Reset filters','reset-filters',{ico:'filter'})}</div></details>
 ${ui.incidentFilters.region!=='ALL'?`<div class="filter-applied incident-filter-notice">Region: <strong>${e(ui.incidentFilters.region)}</strong> ${link('Clear regional filter','reset-filters')}</div>`:''}
 <div class="mobile-preview-nav">${button('Incident list','incident-preview-close',{tone:state.runtime.approvedMobilePreview?'':'soft-blue'})}${button('Selected preview','incident-preview-open',{tone:state.runtime.approvedMobilePreview?'soft-blue':'',disabled:!selected})}</div><div class="incidents-workspace incidents-layout">${panel(limited?'Incidents unavailable':`${filtered.length} incidents`,limited?empty('Incident list unavailable','The authenticated incident inventory was not returned.'):page.length?`<div class="incident-list" aria-label="Incident records">${page.map(i=>`<button class="incident-row ${i.id===state.selected?'selected':''}" data-action="select-incident" data-id="${e(i.id)}" aria-pressed="${i.id===state.selected}"><span class="flame-tile ${i.priority==='high'?'high':i.status}">${icon('flame')}</span><span class="row-main"><strong>${e(i.name)}</strong><span>${e(i.statusLabel)} · ${e(i.type)}</span><time datetime="${e(i.observedAt??'')}">Incident observed ${e(timeLabel(i.observedAt))}</time>${PhysicalInline(i.physical)}</span>${icon('chevron')}</button>`).join('')}</div><div class="pagination"><span>${(ui.page-1)*size+1}–${Math.min(ui.page*size,filtered.length)} of ${filtered.length}</span><div>${button('Previous page','page',{ico:'chevron',tone:'icon-button previous',extra:`data-page="${ui.page-1}"`,disabled:ui.page===1})}${Array.from({length:pages},(_,x)=>x).filter(x=>Math.abs(x+1-ui.page)<=2).map(x=>button(String(x+1),'page',{tone:`small-btn ${ui.page===x+1?'page-active':''}`,extra:`data-page="${x+1}" aria-label="Page ${x+1}" ${ui.page===x+1?'aria-current="page"':''}`})).join('')}${button('Next page','page',{ico:'chevron',tone:'icon-button',extra:`data-page="${ui.page+1}"`,disabled:ui.page===pages})}</div></div>`:empty('No matching incidents','Try a different search or reset the filters.',button('Reset filters','reset-filters')),{cls:'inbox-list-panel incident-inventory',action:!limited?'<span class="small muted">Current first · then latest observation</span>':''})}
 ${panel('Incident preview',limited?empty('Preview unavailable','Choose a record when incident data returns.'):selected?`<div class="incident-preview-body">${!filtered.some(x=>x.id===selected.id)?'<p class="small preview-outside">Selected record is outside the current filters.</p>':''}${mapView({state,id:'incident-preview-map',title:selected.name,height:320,legend:false})}<div class="preview-heading">${badge(selected.statusLabel,selected.verified?'red':selected.status==='DETECTION_CANDIDATE'?'amber':'neutral')}<h2>${e(selected.name)}</h2><strong>${e(selected.type)}</strong><p>${e(timeLabel(selected.observedAt))}</p></div><dl class="preview-fields">${kv('Location',selected.coordinate?`${selected.lat.toFixed(4)}, ${selected.lon.toFixed(4)}`:'Not reported')}${selected.coverage!=='Source coverage not returned'?kv('Source coverage',selected.coverage):''}${kv('Key context',selected.region)}</dl>${button('Open incident','open-incident',{tone:'primary wide',ico:'arrow',extra:`data-id="${e(selected.id)}"`})}<p class="preview-disclaimer">An observation alone does not establish a verified current fire.</p></div>`:empty('Choose an incident','Select a record from the list.'),{cls:'incident-preview-panel'})}</div></div>`;
}
