import {NationalSignalStrip} from '../ui/signals.js';
import {icon} from '../ui/icons.js';
import {e,button,select} from '../ui/html.js';
import {mapView} from '../ui/map.js';
import {regionalPriorities,namedArea} from '../data/hierarchy.js';
import {measured,dated} from '../data/field.js';

export function national(state,ui) {
 const ranked=regionalPriorities(state),selected=ranked.find(r=>r.name===ui.region),shown=ranked.slice(0,6);
 if(selected&&!shown.includes(selected))shown.push(selected);
 const now=Date.parse(state.generatedAt)||Date.now(),unnamed=(state.incidents??[]).filter(i=>i.coordinate&&!namedArea(i.region)).length;
 const warnings=(state.physicalNotices??[]).filter(w=>w.state==='ACTIVE'&&dated(w.effective)&&dated(w.expires)&&Date.parse(w.effective)<=now&&Date.parse(w.expires)>now);
 const age=at=>{const min=Math.floor((now-Date.parse(at))/60000);return min<60?Math.max(0,min)+' min ago':min<1440?Math.floor(min/60)+'h ago':Math.floor(min/1440)+'d ago';};
 return `<div class="national-priority-page" data-vqa="national-priority">
 <section class="national-situation"><div class="national-situation-heading"><h2>National situation</h2><p>Portugal · returned official records and measured conditions</p></div>${NationalSignalStrip(state)}${warnings.length?`<div class="national-warning-brief"><strong>${warnings.length} active weather notices</strong>${warnings.slice(0,3).map(w=>`<span>${e(w.type??w.event??w.awarenessTypeName??'Weather notice')} · ${e(w.area??w.areaName??w.headline??w.title??'Portugal warning area')}</span>`).join('')}${button('View notices','national-notices',{tone:'small-btn'})}</div>`:''}</section>
 <div class="mobile-priority national-leading-area">${ranked[0]?`<span>Leading reported area</span>${button(ranked[0].name,'select-region',{ico:'arrow',extra:`data-region="${e(ranked[0].name)}" aria-pressed="${ranked[0].name===ui.region}"`})}<small>${ranked[0].current?ranked[0].current+' current / candidate records':ranked[0].recent?ranked[0].recent+' records observed in 24h':ranked[0].earlier+' earlier records'}</small>`:''}</div><div class="national-main national-priority-workspace">
 <section class="national-map-panel panel"><header class="national-map-heading"><div><h2>Portugal map</h2><p>${e(selected?selected.name:'National view')} · incident locations, not fire boundaries</p></div><div>${button('Reset Portugal view','reset-national',{ico:'refresh',tone:'small-btn'})}${button('Full-screen map','national-fullscreen',{ico:'expand',tone:'small-btn'})}</div></header><details class="national-filter-disclosure" data-responsive-disclosure="national-filters" open><summary>Filter map</summary><div class="national-map-filters">${select('Region / incident area','region',state.regions,ui.region)}${select('Incident type','national-type',state.typeOptions??[['ALL','All types']],ui.nationalType??'ALL')}${select('Map context','national-layer',[['incidents','Incident records'],['weather','Weather context'],['coverage','Information coverage']],ui.nationalLayer)}${button('Map layers','map-layers',{ico:'layers',tone:'small-btn'})}</div></details>${mapView({state,id:'national-map',height:460,title:selected?selected.name+' incident area':'Portugal incident areas',legend:false,caption:false})}${selected?`<section class="selected-region-context" data-vqa="selected-region-context"><div><h2>${e(selected.name)} · selected area</h2><p>${selected.incidents.length} returned records · ${state.geolocated} mapped</p></div>${button('View regional incidents','regional-incidents',{tone:'small-btn'})}<details class="physical-detail"><summary>Selected region details and source context</summary><ul>${selected.incidents.map(i=>`<li><button type="button" data-action="open-incident" data-id="${e(i.id)}">${e(i.name)}</button>${i.observedAt?` · <time datetime="${e(i.observedAt)}">${e(measured(i.observedAt))}</time>`:''}</li>`).join('')}</ul><p>Earlier observations remain dated. Regional counts are not current confirmed wildfire counts.</p></details></section>`:''}</section>
 <aside class="regional-priority" data-vqa="regional-priority"><header><h2>Regional priority</h2><p>Named incident areas · current records first, then recent observations</p></header><ol>${shown.map((r,n)=>`<li><button type="button" data-action="select-region" data-region="${e(r.name)}" aria-pressed="${r.name===ui.region}"><span class="regional-rank">${n+1}</span><span class="regional-copy"><strong>${e(r.name)}</strong><span>${r.current?r.current+' current / candidate records':r.recent?r.recent+' records observed in 24h':r.earlier+' earlier records'}</span>${r.latest?`<small>Latest incident observation · ${e(age(r.latest))}</small>`:''}</span><span class="region-select-arrow" aria-hidden="true">${icon('arrow')}</span></button></li>`).join('')}</ol><p class="regional-ranking-note">Area labels come from returned incident records. This ranking does not measure danger or establish active fire.${unnamed?' '+unnamed+' other mapped records have no area name; inspect their map markers.':''}</p></aside></div>
 </div>`;
}
