import {e,button,link} from './html.js';
import {icon} from './icons.js';

const kinds={'Fire detection':['flame','red'],'Official update':['info','blue'],Weather:['cloud','blue'],Road:['map','amber'],'Air quality':['cloud','blue'],'Field report':['user','blue'],Operations:['target','green'],'System failure':['layers','amber'],'Internal audit':['layers','neutral']};
const clean=value=>typeof value==='string'?value.replace(/[_-]+/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').trim():'';
export function activityRecord(item,index=0) {
 const raw=item.raw??item,at=raw.observedAt??raw.acquiredAt??raw.at??raw.updatedAt??raw.changedAt;
 const date=new Date(at),valid=Number.isFinite(date.getTime());
 const structured=[raw.eventType,raw.type,raw.kind,raw.subjectType,raw.category].map(clean).join(' ');
 const type=Object.hasOwn(kinds,raw.type)?raw.type:/detect|thermal|heat/i.test(structured)?'Fire detection':/weather|ipma/i.test(structured)?'Weather':/official|warning/i.test(structured)?'Official update':/road|restriction/i.test(structured)?'Road':/air quality|pm25|pm10/i.test(structured)?'Air quality':/field|manual/i.test(structured)?'Field report':/task|assign|operation|workflow/i.test(structured)?'Operations':/failure|outage|source unavailable/i.test(structured)?'System failure':'Internal audit';
 const explicit=[raw.text,raw.title,raw.label,raw.summary,raw.reason].find(v=>typeof v==='string'&&v.trim()&&!/^Recorded change$/i.test(v.trim()));
 const subject=clean(raw.subject?.label??raw.subject?.name??raw.incidentName??raw.incident);
 const incidentUpdate=subject&&raw.updatedAt&&!structured.trim()&&!raw.title;
 const eventLabel=[raw.eventType,raw.type,raw.kind,raw.category,raw.subjectType].map(clean).find(Boolean);
 const description=incidentUpdate?`${subject} · Incident record updated`:explicit??(eventLabel?`${eventLabel}${subject?' · '+subject:''}`:'System update recorded');
 const source=clean(raw.source?.label??raw.source?.name??raw.source??raw.provider?.label??raw.provider??raw.sourceFamily)||(incidentUpdate?'VIGIA':'Source not reported');
 const context=clean(raw.where??raw.context??raw.actor?.name??raw.actor)||(incidentUpdate?clean(raw.summary?.split(/(?<=\.)\s/)[0]):'');
 const family=clean(raw.source?.family??raw.sourceFamily)||(incidentUpdate?'System':'');
 return {raw,key:String(index),at:valid?date.toISOString():null,day:valid?date.toISOString().slice(0,10):'undated',date:valid?date.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}):'Undated',dayLabel:valid?date.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}):'Time unavailable',time:valid?date.toISOString().slice(11,16):'—',type,description,source,family,context,incidentId:raw.incidentId??raw.subject?.incidentId};
}
export function activityRecords(items,{type='All types',days='7',now,includeInternal=false}={}) {
 const end=Number.isFinite(Date.parse(now))?Date.parse(now):Date.now();
 return items.map(activityRecord).filter(r=>(includeInternal||r.type!=='Internal audit')&&(type==='All types'||r.type===type)&&(days==='all'||r.at&&Date.parse(r.at)<=end&&Date.parse(r.at)>=end-Number(days)*86400000)).sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0));
}
function TypeBadge(type){const [symbol,tone]=kinds[type];return `<span class="activity-type ${tone}">${icon(symbol)}${e(type)}</span>`;}
export function ActivityFeed(items,{type='All types',days='7',now,limit=5}={}) {
 const records=activityRecords(items,{type,days,now});
 return `<div class="activity-feed" data-vqa="activity-feed"><header class="activity-feed-header"><div><h2>Recent activity</h2><p>Physical observations, official reports and operational changes.</p></div>${link('View all activity','activity')}<div class="activity-filters" aria-label="Activity filters">${['All types','Fire detection','Official update','Weather','Road','Air quality','Field report','Operations','System failure'].map(t=>`<button type="button" class="btn small-btn ${t===type?'soft-blue':''}" data-action="activity-filter" data-type="${t}" aria-pressed="${t===type}">${t}</button>`).join('')}<label class="activity-range"><span class="sr-only">Date range</span><select aria-label="Date range" data-control="activity-range"><option value="7" ${days==='7'?'selected':''}>Last 7 days</option><option value="1" ${days==='1'?'selected':''}>Last 24 hours</option><option value="all" ${days==='all'?'selected':''}>All returned history</option></select></label></div></header><div class="activity-columns" aria-hidden="true"><span>Time (UTC)</span><span>Type</span><span>Description</span><span>Source</span><span>Action</span></div>${records.length?records.slice(0,limit).map(r=>`<article class="activity-entry"><time datetime="${e(r.at??'')}">${icon('clock')}<span>${e(r.date)}</span><span>${e(r.time)}</span></time>${TypeBadge(r.type)}<div class="activity-description"><strong title="${e(r.description)}">${e(r.description)}</strong>${r.context?`<p title="${e(r.context)}">${e(r.context)}</p>`:''}</div><span class="activity-source"><span class="activity-source-icon">${icon(r.family==='Satellite'?'map':r.family==='Weather'?'cloud':r.family==='User'?'user':'globe')}</span><span><strong title="${e(r.source)}">${e(r.source)}</strong><small>${e(r.family)}</small></span></span><div class="activity-actions">${button('View','activity-view',{tone:'small-btn',extra:`data-id="${e(r.key)}"`})}<details class="activity-overflow"><summary aria-label="More event options">•••</summary><div>${button('Event details','activity-view',{tone:'small-btn',extra:`data-id="${e(r.key)}"`})}</div></details></div></article>`).join(''):'<p class="panel-pad">No returned events match this type and date range.</p>'}${records.length>limit?`<div class="activity-more panel-pad"><span>Showing ${limit} of ${records.length} matching events</span>${button('Show more','activity-more',{tone:'small-btn'})}</div>`:''}</div>`;
}
export function ActivityTimeline(items,options={}) {
 const records=activityRecords(items,{...options,days:options.days??'all'}),groups=new Map();
 for(const r of records){if(!groups.has(r.day))groups.set(r.day,[]);groups.get(r.day).push(r);}
 return `<div class="activity-timeline" data-vqa="activity-timeline">${groups.size?[...groups.values()].map(group=>`<section class="timeline-day"><h3>${e(group[0].dayLabel)}</h3><div class="timeline-rail">${group.map(r=>`<article class="timeline-event ${kinds[r.type][1]} ${options.selectedKey===r.key?'is-selected':''}"><time datetime="${e(r.at??'')}">${e(r.time)}</time>${TypeBadge(r.type)}<div class="timeline-event-copy"><p title="${e(r.description)}">${e(r.description)}</p><small>${e(r.source)}${r.context?' · '+e(r.context):''}</small></div><details class="event-provenance"><summary aria-label="Event provenance">•••</summary><div>${r.incidentId?button('Open incident',`open-incident-workspace:${r.incidentId}`,{tone:'small-btn'}):''}<strong>${e(r.description)}</strong><p>${e(r.source)} · ${e(r.date)} · ${e(r.time)}</p><details class="ux-disclosure"><summary>Original event record</summary><pre>${e(JSON.stringify(r.raw,null,2))}</pre></details></div></details></article>`).join('')}</div></section>`).join(''):'<p>No dated activity was returned.</p>'}</div>`;
}
