import {e,button,select} from './html.js';
import {consequenceSection} from './operational-consequence.js';
import {teamRequest} from '../../vigiaApi.js';
import {FieldTeamStore} from '../../field-team-store.js';
import {datedTeamView} from '../../field-team-offline.js';
import {identity,seal,open} from '../../../../../packages/domain/src/fieldnet/team-protocol.mjs';
import {DurableOutbox,LocalNetworkTransport} from '../../../../../packages/domain/src/fieldnet/team-transports.mjs';

const labels={ROAD_BLOCKED:'Road blocked',ROAD_PARTIAL:'Road partially blocked',FIRE:'Fire observed',SMOKE:'Smoke observed',DAMAGE:'Damaged infrastructure',WATER_AVAILABLE:'Water available',WATER_UNAVAILABLE:'Water unavailable',RECEPTION:'Reception centre status',FACILITY_UNAVAILABLE:'Facility unavailable',COMMS:'Communications problem',CUSTOM:'Custom observation'};
const services={emergency_hospital:'Emergency healthcare',fire_response:'Fire response',designated_reception:'Reception'};
const date=v=>v&&Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date(v))+' UTC':'Not yet received';
const timeInput=()=>new Date().toISOString().slice(0,16);
const btn=(label,cmd,id='',primary=false)=>`<button class="btn ${primary?'primary':''}" type="button" data-team="${e(cmd)}" data-id="${e(id)}">${e(label)}</button>`;
const status=s=>`<span class="mc-state mc-${e(s.toLowerCase())}">${e(s)}</span>`;
const field=(name,label,type='text',value='',extra='')=>`<label>${e(label)}<input name="${e(name)}" type="${type}" value="${e(value)}" ${extra}></label>`;
const direction=r=>r?.direction==='FACILITY_TO_SETTLEMENT'?'Facility to community':r?.direction==='COMMUNITY_TO_FACILITY'?'Community to facility':'Facility to incident';
const route=r=>r?`<div class="mc-route"><div><h3>${e(r.name)}</h3><p>${e(r.roads.join(' → ')||'Road names not returned')}</p></div><strong>${e(Math.round(r.minutes))}<span> min</span></strong></div><p class="mc-meta">${e(direction(r))} · calculated ${e(date(r.calculatedAt))}</p>`:'<p>No current route is stored.</p>';
const verification=r=>r.verification?.state==='FIELD_CONFIRMED'?'Confirmed by two or more responders':r.verification?.state==='CONFLICTING_REPORTS'?'Conflicting reports — check required':'Not yet confirmed';
export function MissionSlot(){return '<section class="mission-command" data-mission-command aria-label="Missions and field team"><h2>Watching</h2><p role="status">Reading team objectives…</p></section>';}
export function commandMarkup(view,{section='home',selected=null,offline=false,pending=[],senderId='',canManage=false,feedbackMessage=''}={}){
  view={
    ...(view??{}),
    group:{
      ...(view?.group??{}),
      members:Array.isArray(view?.group?.members)?view.group.members:[]
    },
    missions:(Array.isArray(view?.missions)?view.missions:[]).map(m=>({
      ...m,
      watchers:Array.isArray(m?.watchers)?m.watchers:[],
      relevantReports:Array.isArray(m?.relevantReports)?m.relevantReports:[]
    })),
    reports:(Array.isArray(view?.reports)?view.reports:[]).map(r=>({
      ...r,
      missions:Array.isArray(r?.missions)?r.missions:[],
      media:Array.isArray(r?.media)?r.media:[],
      routeUses:Array.isArray(r?.routeUses)?r.routeUses:[],
      verification:{
        ...(r?.verification??{}),
        responses:Array.isArray(r?.verification?.responses)?r.verification.responses:[]
      }
    })),
    messages:(Array.isArray(view?.messages)?view.messages:[]).map(m=>({
      ...m,
      relayedBy:Array.isArray(m?.relayedBy)?m.relayedBy:[],
      delivery:{
        ...(m?.delivery??{}),
        label:m?.delivery?.label??'Delivery pending',
        received:Array.isArray(m?.delivery?.received)?m.delivery.received:[],
        waiting:Array.isArray(m?.delivery?.waiting)?m.delivery.waiting:[]
      }
    })),
    receipts:Array.isArray(view?.receipts)?view.receipts:[],
    requests:Array.isArray(view?.requests)?view.requests:[],
    timeline:Array.isArray(view?.timeline)?view.timeline:[],
    people:Array.isArray(view?.people)?view.people:[],
    envelopes:Array.isArray(view?.envelopes)?view.envelopes:[],
    context:{
      ...(view?.context??{}),
      catalog:Array.isArray(view?.context?.catalog)?view.context.catalog:[]
    },
    consequences:view?.consequences??null,
    hub:view?.hub??{}
  };
  pending=Array.isArray(pending)?pending:[];
  const g=view.group,m=view.missions.find(m=>m.id===selected),r=view.reports.find(r=>r.id===selected);
  const header=`${g.lane==='CONTROLLED_FIELD_TEST'?'<p class="mc-test">CONTROLLED FIELD TEST · separate from operational history</p>':''}<header class="mc-heading"><div><h2>${e(section==='home'?'Important now':section==='mission'?'Watched objective':section==='report'?'Field report':section==='chat'?g.name:section==='timeline'?'What changed':section==='people'?'People and team':'New '+section)}</h2><p>${e(g.name)}</p></div>${section==='home'?btn('Team','chat'):btn('Back','home')}</header><div class="mc-connection" role="status"><strong>${offline?'WAITING FOR CONNECTION':view.hub.state==='INTERNET_OFFLINE'?'INTERNET OFFLINE · LOCAL VIGIA ACTIVE':'LOCAL VIGIA ACTIVE'}</strong><span>${offline?'Saved on this device. Delivery waits for a connection.':view.hub.localPeople+' people active locally · '+(view.hub.lastCentralSync?'last central sync '+date(view.hub.lastCentralSync):view.hub.centralConfigured?'central sync pending':'central sync not configured')}</span></div>`;
  let body='';
  if(section==='home'){
    const important=view.reports.filter(r=>r.missions.length).slice(0,2);
    // Derived operational consequences lead Important Now. The existing report
    // list stays below them unchanged, so nothing that worked before is lost.
    const derived=consequenceSection(view.consequences,{btn});
    body=derived+(important.length?important.map(r=>`<article class="mc-important"><h3>${e(labels[r.type])} · ${e(r.locationName)}</h3><p>${e(r.reason)}</p>${r.missions.map(m=>`<p>${e(m.subjectName)}${m.currentMinutes!==null?' · '+Math.round(m.currentMinutes)+' min':''}${m.alternativeMinutes!==null?' → '+Math.round(m.alternativeMinutes)+' min alternative':''}</p>`).join('')}<p class="mc-meta">${e(r.senderName)} · observed ${e(date(r.observedAt))} · ${e(verification(r))}</p>${btn('View report','report',r.id)}</article>`).join(''):`<p class="mc-quiet">${view.missions.some(m=>m.state==='PROBLEM')?'A watched objective needs attention below.':'No new report affecting a watched route has been received.'}</p>`)+
    `<div class="mc-heading"><h2>Watching</h2>${canManage?btn('New mission','new-mission'):''}</div><div class="mc-watching">${view.missions.filter(m=>m.lifecycle==='ACTIVE').slice(0,5).map(m=>`<button class="mc-watch-row" data-team="mission" data-id="${e(m.id)}"><span><strong>${e(m.subjectName)} → ${e(services[m.service])}</strong><small>${e(m.reason)}</small></span>${status(m.state)}</button>`).join('')||'<p>Choose a place and service to keep in view.</p>'}</div><nav class="mc-actions" aria-label="Field actions">${btn('Report from the field','new-report','',true)}${btn('People','people')}${btn('What changed','timeline')}</nav><h3>Recent</h3>${pending.filter(p=>p.envelope.kind==='REPORT'&&!view.reports.some(r=>r.id===p.envelope.id)).map(p=>'<p class="mc-recent"><strong>'+e(p.text??'Outgoing field report')+'</strong><span>'+e(p.state==='REJECTED'?'NOT SENT — '+p.error:p.state==='EXPIRED'?'EXPIRED — report again with a new observation':p.state==='ACCEPTED'?'SENT FROM THIS DEVICE — waiting for team update':'WAITING FOR CONNECTION')+'</span></p>').join('')}${view.timeline.slice(0,3).map(t=>`<p class="mc-recent"><time>${e(date(t.at))}</time><span>${e(t.text)}</span></p>`).join('')||'<p>No team activity received yet.</p>'}<details><summary>Team and earlier missions</summary>${view.missions.filter(m=>m.lifecycle!=='ACTIVE').map(m=>btn(m.objective,'mission',m.id)).join('')}${btn('Change team','teams')}${btn('Prepare this device for offline use','prepare-offline')}</details>`;
  }else if(section==='mission'&&m){
    body=`<div class="mc-heading"><h2>${e(m.objective)}</h2>${status(m.state)}</div><p>Until ${e(date(m.endAt))} · ${e(m.lifecycle==='ENDED'?'Ended':m.subjectName)}</p><p class="mc-answer">${e(m.reason)}</p><h3>Current stored route</h3>${route(m.currentRoute)}<h3>Another route</h3>${route(m.fallback)}${m.fallback?'<p>Condition of the alternative is not confirmed.</p>':'<p>No other current route is stored.</p>'}<p class="mc-meta">Calculated routes do not establish safe access. ${e(m.routeDirection==='FACILITY_TO_SETTLEMENT'?'These times describe travel from the facility to the community, not the reverse trip.':'')}</p><div class="mc-actions">${m.relevantReports.map(r=>btn('View '+labels[r.type].toLowerCase(),'report',r.id)).join('')}${btn('Report a change','new-report')}${btn('Compare routes','routes',m.id)}${btn('Show stored routes on map','show-routes',m.id)}</div><details><summary>Why did this change?</summary>${view.timeline.filter(t=>t.missionId===m.id).slice(0,8).map(t=>`<p><time>${e(date(t.at))}</time> ${e(t.text)}${t.previous?`<br>Previous: ${e(t.previous.state)}. Current: ${e(t.current.state)}.`:''}</p>`).join('')}</details><p class="mc-meta">Last checked ${e(date(m.lastCheckedAt))}</p>${btn(m.watchers.includes(senderId)?'Stop watching':'Watch this objective','watch',m.id)}<p class="mc-meta">Watching: ${m.watchers.map(id=>e(g.members.find(p=>p.id===id)?.name??id)).join(', ')}</p>${canManage&&m.lifecycle==='ACTIVE'?btn('End mission','end-mission',m.id):''}`;
  }else if(section==='routes'&&m){body=`<h2>${e(m.subjectName)} · route comparison</h2><h3>Current</h3>${route(m.currentRoute)}<h3>Alternative</h3>${route(m.fallback)}<p>Alternative conditions are unconfirmed. Neither calculation accounts for live traffic or guarantees safe passage.</p>${canManage&&m.fallback?btn('Use as watched route','select-alternative',m.id):''}${btn('Back to mission','mission',m.id)}`;
  }else if(section==='report'&&r){
    body=`<h2>${e(labels[r.type])}</h2><p class="mc-answer">${e(r.locationName)}</p><p>${e(r.note)}</p><div class="mc-clock"><span>${e(r.senderName)}</span><span>Observed ${e(date(r.observedAt))}</span><span>Received ${e(date(r.receivedAt))}</span></div><p><strong>${e(verification(r))}</strong></p><p class="mc-meta">Field observations are separate from official restrictions.${Date.parse(r.validUntil)<=Date.parse(view.at)?' This observation needs a new check.':''}</p>${r.media.map(a=>a.type.startsWith('image/')?`<img class="mc-photo" alt="Photo attached to the field report" src="data:${e(a.type)};base64,${e(a.data)}">`:`<audio controls data-team-audio="${e(a.data)}" data-type="${e(a.type)}"></audio>`).join('')}<h3>This location is used to reach</h3>${(r.routeUses??[]).map(u=>'<p>'+e(u.facility)+' · '+e(u.place)+' · '+e(u.service)+'</p>').join('')||'<p>No stored route match established.</p>'}<h3>Why this matters</h3>${r.missions.map(m=>`<p>${e(m.subjectName)} · ${e(services[m.service])}${m.facility?' via '+e(m.facility):''}. ${m.alternativeMinutes!==null?'Another stored route: '+Math.round(m.alternativeMinutes)+' min.':'No other current route stored.'}</p>${btn('View objective','mission',m.id)}`).join('')||'<p>No watched route match is established for this report.</p>'}<div class="mc-actions">${btn('Ask someone to confirm','request-confirmation',r.id,true)}${r.senderId!==senderId?btn('Respond to this report','confirm',r.id):''}</div>${r.verification.responses.map(c=>`<p>${e(c.senderName)} · ${e({CONFIRM:'Confirmed',NOT_BLOCKED:'Not blocked',PARTIALLY_BLOCKED:'Partially blocked',CANT_VERIFY:'Could not verify'}[c.answer])} · observed ${e(date(c.observedAt))}</p>`).join('')}<details><summary>Exact location</summary><p>${e(r.coordinate.join(', '))} · accuracy ${e(r.accuracyM)} m</p></details>`;
  }else if(section==='confirm'&&r){body=`<h2>Check ${e(r.locationName)}</h2><p>Only describe what you personally observed.</p><form data-team-form="confirm"><input type="hidden" name="reportId" value="${e(r.id)}">${field('observedAt','Observed time (UTC)','datetime-local',timeInput(),'required')}<label>Your observation<select name="answer"><option value="CONFIRM">Confirm report</option><option value="NOT_BLOCKED">Not blocked</option><option value="PARTIALLY_BLOCKED">Partially blocked</option><option value="CANT_VERIFY">Can’t verify</option></select></label><button class="btn primary" type="submit">Send response</button></form>`;
  }else if(section==='chat'){
    body=`<div class="mc-chat" role="log" aria-label="Team messages">${view.messages.map(m=>`<article class="mc-message"><div><strong>${e(m.senderName)}</strong><time>${e(date(m.createdAt))}</time></div><p>${e(m.text)}</p><small>${e(m.delivery.label)}</small>${m.delivery.received.length?`<p class="mc-meta">Received by ${m.delivery.received.map(id=>e(g.members.find(p=>p.id===id)?.name??id)).join(', ')}${m.delivery.waiting.length?'. Waiting for '+m.delivery.waiting.map(id=>e(g.members.find(p=>p.id===id)?.name??id)).join(', '):''}</p>`:''}${m.relayedBy.length?`<p class="mc-meta">Passed through ${m.relayedBy.map(id=>e(g.members.find(p=>p.id===id)?.name??id)).join(', ')}</p>`:''}<details><summary>Delivery details</summary>${view.receipts.filter(r=>r.messageId===m.id).map(r=>`<p>Delivered to ${e(g.members.find(p=>p.id===r.recipientId)?.name??r.recipientId)} · ${e(date(r.recipientReceivedAt))}</p>`).join('')||'<p>No recipient acknowledgement yet.</p>'}</details></article>`).join('')}${pending.filter(p=>p.envelope.kind==='MESSAGE'&&!view.messages.some(m=>m.id===p.envelope.id)).map(p=>`<article class="mc-message mc-pending"><strong>You</strong><p>${e(p.text??'Encrypted outgoing message')}</p><small>${p.state==='REJECTED'?'NOT SENT — '+e(p.error):p.state==='EXPIRED'?'EXPIRED — review before sending again':p.state==='ACCEPTED'?'SENT FROM THIS DEVICE':'WAITING FOR CONNECTION'}</small></article>`).join('')}</div><form data-team-form="message"><label>Message to ${e(g.name)}<textarea name="text" rows="3" maxlength="2000" required placeholder="Tell the team what you observed or need…"></textarea></label><button type="submit" class="btn primary">Send to team</button></form><div class="mc-actions">${btn('Retry connection','retry')}${btn('People and delivery','people')}${canManage?btn('Sync with central VIGIA','sync-central'):''}</div>${view.requests.slice(-3).map(r=>`<p>Confirmation requested ${e(date(r.receivedAt))} · ${e(r.delivery.label)} ${btn('View report','report',r.reportId)}</p>`).join('')}`;
  }else if(section==='timeline'){body=view.timeline.map(t=>`<article class="mc-timeline"><time>${e(date(t.at))}</time><div><p>${e(t.text)}</p>${t.observedAt?`<small>Observed ${e(date(t.observedAt))}</small>`:''}${t.reportId?btn('View report','report',t.reportId):''}${t.missionId?btn('View mission','mission',t.missionId):''}</div></article>`).join('')||'<p>No team changes received yet.</p>';
  }else if(section==='people'){body=view.people.map(p=>`<div class="mc-person"><strong>${e(p.name)}</strong><span>${p.online?'Active locally':'No recent connection'}</span><p>${e(p.status??'No status shared')}</p>${p.location?`<p>${e(p.location.name)} · shared ${e(date(p.location.observedAt))}</p>`:''}<small>Last seen ${e(date(p.lastSeenAt))}</small></div>`).join('')+`<form data-team-form="presence">${field('status','Your team status','text','','maxlength="160"')}<label><input type="checkbox" name="shareLocation"> Share the location I enter below</label>${field('locationName','Location name')}${field('longitude','Longitude','number','','step="any" min="-180" max="180"')}${field('latitude','Latitude','number','','step="any" min="-90" max="90"')}<button class="btn primary" type="submit">Update my status</button><p class="mc-meta">Location is only shared when you choose it. An update with sharing off removes your previous location.</p></form>`;
  }else if(section==='new-mission'){body=`<form data-team-form="mission">${field('objective','What should we keep available?','text','','required maxlength="240" placeholder="Keep this community connected to emergency healthcare"')}<label>Place<select name="subjectId">${view.context.catalog.map(c=>`<option value="${e(c.id)}">${e(c.name)}</option>`).join('')}</select></label><label>Protected service<select name="service">${Object.entries(services).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label>${field('startAt','Start (UTC)','datetime-local',timeInput(),'required')}${field('endAt','Until (UTC)','datetime-local',new Date(Date.now()+90*60000).toISOString().slice(0,16),'required')}<p class="mc-meta">Uses this place’s stored qualified routes. If none exist, the mission starts UNKNOWN.</p><button type="submit" class="btn primary" ${!view.context.catalog.length?'disabled':''}>Start watching</button>${!view.context.catalog.length?'<p>No named place has been retained yet. Open Operational Picture to inspect available context.</p>':''}</form>`;
  }else if(section==='new-report'){body=`<form data-team-form="report">${view.context.exercise?'<p class="mc-test">Exercise location: '+e(view.context.exercise.reportPoint.join(', '))+' · 10 m accuracy. These are synthetic test coordinates.</p>':''}<label>Report type<select name="type">${Object.entries(labels).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label>${field('locationName','Road, place or facility name','text',view.context.exercise?.locationName??'','required maxlength="240"')}${field('observedAt','Observed time (UTC)','datetime-local',timeInput(),'required')}<label>What did you see?<textarea name="note" rows="3" maxlength="1200"></textarea></label><fieldset><legend>Report location</legend>${btn('Choose location on map','pick-location')}<p>Enter the location of the observation. VIGIA does not guess or share your current location.</p><div class="mc-coordinate">${field('longitude','Longitude','number',view.context.exercise?.reportPoint[0]??'','required step="any" min="-180" max="180"')}${field('latitude','Latitude','number',view.context.exercise?.reportPoint[1]??'','required step="any" min="-90" max="90"')}${field('accuracyM','Accuracy (metres)','number',view.context.exercise?.accuracyM??'','required min="0" max="10000"')}</div></fieldset><label>Related facility (optional)<select name="facilityId"><option value="">No facility selected</option>${[...new Map(view.context.catalog.flatMap(c=>c.services.flatMap(s=>s.routes.map(r=>[r.facilityId,r.name])))).entries()].map(([id,name])=>`<option value="${e(id)}">${e(name)}</option>`).join('')}</select></label><label>Photo or voice note (up to 400 KB each)<input type="file" name="media" accept="image/jpeg,image/png,image/webp,audio/webm,audio/mp4,audio/ogg" multiple></label><button class="btn primary" type="submit">Send field report</button></form>`;
  }
  return header+body+`<p class="mc-feedback" role="status" aria-live="polite">${e(feedbackMessage)}</p>`;
}

export function installMissionCommand({state,activeMap}){
  const store=new FieldTeamStore();let root=null,incident=null,senderId=null,device=null,groups=[],view=null,section='home',selected=null,offline=false,canManage=false,busy=false,serial=0,pending=[],feedbackMessage='',portfolioReadOnly=null;
  const transport=new LocalNetworkTransport(body=>teamRequest('envelopes',body));
  let lastCentralAttempt=0;
  let outbox=null,audioUrls=[],drafts=new Map(),draftTail=Promise.resolve(),paintedDraft=null;
  const draftKey=()=>senderId+':draft:'+incident+':'+(view?.group.id??'new')+':'+section+':'+(selected??'');
  async function detectPortfolioReadOnly(){if(portfolioReadOnly!==null)return portfolioReadOnly;try{const response=await fetch('/__operator/ready',{credentials:'same-origin',cache:'no-store',headers:{accept:'application/json'}}),payload=await response.json().catch(()=>null);portfolioReadOnly=response.ok&&payload?.isolatedDemo===true&&payload?.readOnly===true;}catch{portfolioReadOnly=false;}return portfolioReadOnly;}
  function saveDraft(){const form=root?.querySelector('[data-team-form]');if(!form||!paintedDraft||form.dataset.teamForm==='offline')return;const key=paintedDraft,values=[...form.elements].filter(el=>el.name&&el.type!=='file').map(el=>({name:el.name,value:el.value,checked:el.checked}));const files=[...form.querySelectorAll('input[type=file]')].flatMap(el=>[...el.files].map(file=>({name:el.name,file}))).slice(0,2);drafts.set(key,{values,files});draftTail=draftTail.then(async()=>{const media=[];for(const item of files){if(item.file.size>400000)continue;media.push({name:item.name,type:item.file.type,filename:item.file.name,bytes:[...new Uint8Array(await item.file.arrayBuffer())]});}await store.cache(key,{values,media});}).catch(()=>{});}
  async function restoreDraft(){const key=draftKey();if(!drafts.has(key)){const saved=await store.cached(key);if(saved)drafts.set(key,{values:saved.values,files:(saved.media??[]).map(m=>({name:m.name,file:new File([new Uint8Array(m.bytes)],m.filename,{type:m.type})}))});}}
  const scopedStore={get:id=>store.get(senderId+':'+id),put:(id,v)=>store.put(senderId+':'+id,v),all:prefix=>store.all(senderId+':'+prefix)};
  const valid=()=>root?.isConnected&&incident===state.selectedIncidentId;
  const feedback=message=>{
    feedbackMessage=String(message??'');
    if(incident!==state.selectedIncidentId)return;
    const target=root?.isConnected?root:document.querySelector('[data-mission-command]');
    const node=target?.querySelector('.mc-feedback');
    if(node)node.textContent=feedbackMessage;
  };
  const readPending=async()=>{pending=outbox?await scopedStore.all('outbox:'):[];for(const p of pending)if(p.envelope.groupId===view?.group.id&&['MESSAGE','REPORT'].includes(p.envelope.kind)){try{const payload=await open(p.envelope,view.group.key);p.text=p.envelope.kind==='REPORT'?(labels[payload.type]??'Field report')+' · '+payload.locationName:payload.text;}catch{p.text='Encrypted message from an earlier team membership';}}pending=pending.filter(p=>p.envelope.groupId===view?.group.id);};
  async function queue(kind,payload,recipients){if(!device||!view)throw Error('Connect once to register this device and load your team.');const envelope=await seal({group:view.group,device,senderId,kind,payload,recipients});await outbox.enqueue(envelope);await readPending();return envelope;}
  function paint(){if(!valid())return;saveDraft();const focused=root.contains(document.activeElement)?document.activeElement:null;const focusName=focused?.getAttribute('name'),focusCmd=focused?.dataset.team;
    for(const url of audioUrls)URL.revokeObjectURL(url);audioUrls=[];
    if(portfolioReadOnly)root.innerHTML='<header class="mc-heading"><h2>Watching and field team</h2></header><p>This public portfolio demo is read-only. Field-team registration, messaging and reports are disabled here.</p><p class="mc-meta">The operational FieldNet workflow remains separate from this bounded demo and no device is registered by viewing this page.</p>';
    else if(view)root.innerHTML=commandMarkup(view,{section,selected,offline,pending,senderId,canManage,feedbackMessage});
    else root.innerHTML=`<header class="mc-heading"><h2>Watching and field team</h2></header><p>Keep an objective in view and share reports with your incident team.</p>${groups.map(g=>btn(g.name,'group',g.id)).join('')}${canManage?`<details open><summary>Create a private team</summary><form data-team-form="group">${field('name','Team name','text','','required maxlength="120"')}${field('memberIds','Other members’ VIGIA account IDs','text','','placeholder="Comma-separated account IDs"')}<p class="mc-meta">Only these authenticated accounts can access this team. Leave blank to start with yourself.</p><label><input type="checkbox" name="exercise"> Controlled field exercise (synthetic routes and times)</label><button class="btn primary" type="submit">Create team</button></form></details>`:''}<p class="mc-feedback" role="status" aria-live="polite">${e(feedbackMessage)}</p>${btn('Retry connection','retry')}`;
    paintedDraft=draftKey();const draft=drafts.get(paintedDraft);if(draft){for(const v of draft.values){const el=root.querySelector('[name='+CSS.escape(v.name)+']');if(el){el.value=v.value;if(el.type==='checkbox')el.checked=v.checked;}}for(const input of root.querySelectorAll('input[type=file]')){const transfer=new DataTransfer();for(const item of draft.files.filter(f=>f.name===input.name))transfer.items.add(item.file);input.files=transfer.files;}}
    for(const audio of root.querySelectorAll('[data-team-audio]')){const bytes=Uint8Array.from(atob(audio.dataset.teamAudio),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:audio.dataset.type}));audioUrls.push(url);audio.src=url;}
    if(focusName)root.querySelector(`[name="${CSS.escape(focusName)}"]`)?.focus({preventScroll:true});else if(focusCmd)root.querySelector(`[data-team="${CSS.escape(focusCmd)}"]`)?.focus({preventScroll:true});
  }
  async function refresh(){
    const n=serial,id=incident;
    try{
      if(await detectPortfolioReadOnly()){senderId=null;device=null;groups=[];view=null;canManage=false;offline=false;outbox=null;pending=[];if(n===serial)paint();return;}
      if(senderId){const account=await teamRequest('incidents/'+encodeURIComponent(id)+'/groups');if(n!==serial)return;if(account.senderId!==senderId)throw Object.assign(Error('Account changed.'),{status:403});}
      if(!senderId){const r=await teamRequest('incidents/'+encodeURIComponent(id)+'/groups');if(n!==serial)return;senderId=r.senderId;store.authorize(senderId);groups=r.groups;canManage=r.canManage;await store.cache('session:'+id,{senderId,groups,canManage});device=await store.get('device:'+senderId);if(!device){device=await identity();await store.put('device:'+senderId,device);}await teamRequest('devices',{incidentId:id,deviceId:device.deviceId,publicKey:device.publicKey});outbox=new DurableOutbox({store:scopedStore});}
      if(!view&&groups.length){const saved=await store.get('selected-group:'+id);view={group:groups.find(g=>g.id===saved)??groups[0]};}
      if(view){await outbox.flush(transport);const next=await teamRequest('groups/'+encodeURIComponent(view.group.id));if(n!==serial||id!==incident)return;if(next.senderId!==senderId)throw Object.assign(Error('Account changed.'),{status:401});view=next;await store.cache(senderId+':view:'+view.group.id,view);await store.put('selected-group:'+id,view.group.id);await store.put('offline-incident',id);await store.updateOffline({incident:id,session:{senderId,groups,canManage},view});await readPending();
        // A receipt means this intended device durably stored the decrypted
        // payload. It is not generated by the relay or the central server.
        for(const item of view.envelopes.filter(e=>e.envelope.kind!=='ACK')){const key=senderId+':ack:'+item.envelope.id;if(await store.get(key))continue;const ack=await queue('ACK',{messageId:item.envelope.id,messageHash:item.hash,recipientReceivedAt:new Date().toISOString()},[item.envelope.senderId]);await store.put(key,ack.id);}
        void outbox.flush(transport);
      }
      offline=false;if(view?.hub?.centralConfigured&&canManage&&Date.now()-lastCentralAttempt>60000){lastCentralAttempt=Date.now();void teamRequest('groups/'+encodeURIComponent(view.group.id)+'/sync',{}).catch(()=>{});}
    }catch(error){offline=true;
      if(error.status===401||error.status===403){await store.lock();view=null;groups=[];senderId=null;paint();feedback('Sign in with an authorized team account. Cached private team content is locked.');return;}
      if(!senderId){const session=await store.cached('session:'+id);if(session){({senderId,groups,canManage}=session);device=await store.get('device:'+senderId);outbox=new DurableOutbox({store:scopedStore});}}
      const groupId=view?.group?.id??await store.get('selected-group:'+id);const cached=senderId&&groupId?await store.cached(senderId+':view:'+groupId):null;if(cached)view=datedTeamView(cached);else if(!view?.missions)view=null;await readPending();
      if(!view){paint();feedback('Team connection unavailable. Retry when the local service is reachable.');return;}
    }
    if(n===serial){await restoreDraft();if(root.querySelector('[data-team-form=offline]'))return;if(root.querySelector('form')&&view&&paintedDraft===draftKey()){const template=document.createElement('template');template.innerHTML=commandMarkup(view,{section,selected,offline,pending,senderId,canManage});for(const selector of ['.mc-chat','.mc-connection']){const old=root.querySelector(selector),next=template.content.querySelector(selector);if(old&&next){const scroll=old.scrollTop;old.replaceWith(next);next.scrollTop=scroll;}}}else paint();}
  }
  async function submit(form){const f=new FormData(form),v=Object.fromEntries(f),kind=form.dataset.teamForm;
    if(kind==='offline'){if(!('serviceWorker'in navigator))throw Error('This browser cannot prepare an offline shell.');await store.prepareOffline(v.passphrase,{incident,session:{senderId,groups,canManage},view});await navigator.serviceWorker.register('/field-team-sw.js');await navigator.serviceWorker.ready;form.reset();section='home';paint();feedback('Offline workspace prepared. Your passphrase is required to unlock retained private information.');return;}
    if(kind==='group'){const g=await teamRequest('groups',{incidentId:incident,name:v.name,lane:f.has('exercise')?'CONTROLLED_FIELD_TEST':'OPERATIONAL',memberIds:v.memberIds.split(',').map(s=>s.trim()).filter(Boolean)});groups.push(g);view={group:g};section='home';root.replaceChildren();paintedDraft=null;await refresh();return;}
    const utc=x=>new Date(x+'Z').toISOString();
    if(kind==='message')await queue('MESSAGE',{text:v.text});
    else if(kind==='mission')await queue('MISSION',{objective:v.objective,subjectId:v.subjectId,service:v.service,startAt:utc(v.startAt),endAt:utc(v.endAt)});
    else if(kind==='confirm')await queue('CONFIRMATION',{reportId:v.reportId,answer:v.answer,observedAt:utc(v.observedAt)});
    else if(kind==='presence')await queue('PRESENCE',{status:v.status,shareLocation:f.has('shareLocation'),location:f.has('shareLocation')?{name:v.locationName,coordinate:[Number(v.longitude),Number(v.latitude)],observedAt:new Date().toISOString()}:null});
    else if(kind==='report'){const media=[];for(const file of f.getAll('media').filter(f=>f.size)){if(file.size>400000||media.length>=2)throw Error('Use up to two attachments, 400 KB each.');const bytes=new Uint8Array(await file.arrayBuffer());let data='';for(const n of bytes)data+=String.fromCharCode(n);media.push({type:file.type,data:btoa(data)});}await queue('REPORT',{type:v.type,note:v.note,locationName:v.locationName,coordinate:[Number(v.longitude),Number(v.latitude)],accuracyM:Number(v.accuracyM),observedAt:utc(v.observedAt),facilityId:v.facilityId||null,media});}
    const sentKey=paintedDraft;drafts.delete(sentKey);await draftTail;await store.remove('cache:'+sentKey);paintedDraft=null;form.reset();section=kind==='message'?'chat':'home';paint();await refresh();feedback(offline?'Saved on this device. Waiting for connection.':'Saved. Recipient delivery is shown only after their device acknowledges.');
  }
  async function action(t){const cmd=t.dataset.team,id=t.dataset.id;
    if(cmd==='pick-location'){const {pickFieldReportPoint}=await import('../../mapRuntime.js?v=3.0.0');const point=await pickFieldReportPoint(activeMap?.());root.querySelector('[name=longitude]').value=point[0];root.querySelector('[name=latitude]').value=point[1];saveDraft();feedback('Location selected. Enter the place name and your estimated accuracy before sending.');root.querySelector('[name=locationName]')?.focus();return;}
    if(cmd==='show-routes'){const m=view.missions.find(m=>m.id===id),subject=view.context.catalog.find(s=>s.id===m.subjectId),features=[m.currentRoute,m.fallback].filter(r=>r?.geometry).map((r,n)=>({type:'Feature',geometry:r.geometry,properties:{kind:'route',state:n===0&&m.state==='PROBLEM'?'lost':'retained',name:r.name}}));if(subject?.coordinate)features.push({type:'Feature',geometry:{type:'Point',coordinates:subject.coordinate},properties:{kind:'community',name:subject.name}});const {showSituationMapScene}=await import('../../mapRuntime.js?v=3.0.0');const shown=showSituationMapScene(activeMap?.(),{incident:{coordinate:subject?.coordinate},routes:[],facilities:[]},{mode:view.group.lane==='CONTROLLED_FIELD_TEST'?'SCENARIO':'OPERATIONAL',picture:{features},label:(view.group.lane==='CONTROLLED_FIELD_TEST'?'CONTROLLED FIELD TEST · ':'')+'Stored mission routes · conditions unconfirmed'});if(!shown)throw Error('Map not ready. Route details remain available here.');return;}
    if(cmd==='retry'){await refresh();return;}
    if(cmd==='group'){saveDraft();serial++;view={group:groups.find(g=>g.id===id)};section='home';await refresh();return;}
    if(cmd==='teams'){saveDraft();serial++;view=null;paint();return;}
    if(cmd==='request-confirmation'){await queue('REQUEST_CONFIRMATION',{reportId:id});feedback('Confirmation request saved for the team. Delivery appears in the team conversation.');await refresh();feedback('Confirmation request saved for the team. Delivery appears in the team conversation.');return;}
    if(cmd==='select-alternative'){const m=view.missions.find(m=>m.id===id);await queue('MISSION_UPDATE',{missionId:id,currentRouteId:m.fallback.id});section='mission';await refresh();return;}
    if(cmd==='watch'){const m=view.missions.find(m=>m.id===id);await queue('WATCH',{missionId:id,watching:!m.watchers.includes(senderId)});await refresh();return;}
    if(cmd==='sync-central'){const result=await teamRequest('groups/'+encodeURIComponent(view.group.id)+'/sync',{});await refresh();feedback(result.state==='NOT_CONFIGURED'?'Central sync is not configured on this local installation.':result.state==='INTERNET_OFFLINE'?'Internet offline. Local team work remains available.':result.lastBatch.reports+' reports and '+result.lastBatch.messages+' messages synced; '+result.lastBatch.duplicates+' duplicate retries ignored.');return;}
    if(cmd==='end-mission'){await queue('MISSION_END',{missionId:id});await refresh();return;}
    if(cmd==='prepare-offline'){saveDraft();paintedDraft=null;root.innerHTML='<h2>Prepare this trusted device</h2><p>Choose a passphrase to unlock private maps and team information offline. Keep it separate from your VIGIA password.</p><form data-team-form="offline"><label>Offline passphrase<input name="passphrase" type="password" autocomplete="new-password" minlength="12" required></label><button class="btn primary" type="submit">Prepare device</button></form>'+btn('Back','home')+'<p class="mc-feedback" role="status"></p>';return;}

    saveDraft();section=cmd;selected=id;await restoreDraft();paint();root.querySelector('h2')?.setAttribute('tabindex','-1');root.querySelector('h2')?.focus({preventScroll:true});
  }
  function mount(){const slot=document.querySelector('[data-mission-command]');if(!slot||slot===root)return;if(incident!==state.selectedIncidentId){serial++;incident=state.selectedIncidentId;senderId=null;device=null;view=null;groups=[];section='home';selected=null;feedbackMessage='';}root=slot;
    root.addEventListener('click',ev=>{const t=ev.target.closest('[data-team]');if(!t)return;ev.stopPropagation();if(busy)return;busy=true;void action(t).catch(e=>feedback(e.message)).finally(()=>busy=false);});
    root.addEventListener('input',saveDraft);root.addEventListener('change',saveDraft);
    root.addEventListener('submit',ev=>{const f=ev.target.closest('[data-team-form]');if(!f)return;ev.preventDefault();ev.stopPropagation();if(busy)return;busy=true;f.querySelector('button[type="submit"]').disabled=true;void submit(f).catch(e=>feedback(e.message)).finally(()=>{busy=false;if(f.isConnected)f.querySelector('button[type="submit"]').disabled=false;});});
    if(view)paint();else if(incident)void refresh().catch(e=>feedback(e.message));else{root.innerHTML='<h2>Watching</h2><p>Select an incident to open its missions and field team.</p>'+button('Choose incident','choose-incident');}
  }
  new MutationObserver(mount).observe(document.getElementById('app')??document.body,{childList:true,subtree:true});
  const poll=setInterval(()=>{if(valid()&&!busy&&senderId)void refresh().catch(()=>{});},15000);poll.unref?.();
  window.addEventListener('online',()=>{if(valid()&&!busy)void refresh().catch(()=>{});});mount();
}
