import {e,button} from './html.js';
import {DetailRows,TechnicalDetails} from './measurement-panel.js';
const date=v=>v&&Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date(v))+' UTC':'Time not reported';
const action=(label,key,extra='')=>button(label,'situation-'+key,{extra});
const list=rows=>rows.length?`<ul class="situation-list">${rows.map(r=>`<li>${r}</li>`).join('')}</ul>`:'';
const category=id=>({emergency_hospital:'Emergency healthcare',fire_response:'Fire response',civil_protection:'Civil protection',designated_reception:'Designated reception'}[id]??id);
const option=o=>o?`${o.name} · ${Math.round(o.minutes)} min calculated`:'No current qualified route retained';
export function SupportRows(groups=[]){return groups.filter(g=>g.primary&&['emergency_hospital','fire_response','civil_protection','designated_reception'].includes(g.id)).map(g=>`<section class="situation-support-row"><h4>${e(category(g.id))}</h4><div><p><strong>${e(option(g.primary))}</strong></p>${g.secondary?`<p>Alternative: ${e(option(g.secondary))}</p>`:''}${TechnicalDetails('Route and source',DetailRows([['Alternative',!g.secondary?'No retained alternative calculated option':null],['Significant roads',g.primary.roads.join(' → ')||'No significant road named'],['Calculated',date(g.primary.calculatedAt)],['Road source checked',date(g.primary.roadInformation?.checkedAt)],['Shared by both options',g.sharedSegments?.length?g.sharedSegments.join(', '):null]])+action('Inspect facility','facility',`data-entity="${e(g.primary.facilityId)}"`))}</div></section>`).join('');}
export function CoverageMarkup(rows=[]){return rows.map(c=>`<h4>${e(category(c.category))}</h4><p>${c.relationships.length} retained calculated paths · ${c.bands.join(' / ')} minute bands</p>${action('Show this category on map','coverage',`data-category="${e(c.category)}"`)}${TechnicalDetails('Gaps in the retained set',list(c.gaps.slice(0,12).map(g=>`<strong>${e(g.name)}</strong><p>${e(g.text)}</p>`))+`<p>${e(c.limitation)}</p>`)}`).join('');}
export function CommunitiesMarkup(rows=[]){return rows.length?list(rows.slice(0,20).map(c=>{const primary=c.groups.find(g=>g.id==='emergency_hospital')?.primary;return `${action(c.name,'community',`data-entity="${e(c.id)}"`)}<p>${primary?e(option(primary)):'No qualified healthcare route retained'}</p>`})):'<p>No retained community matches this question.</p>';}
export function SupportMarkup(s){if(!s?.groups)return'';return `<section aria-label="Operational support"><h3>Operational support</h3>${SupportRows(s.groups)}${!s.groups.some(g=>g.primary)?'<p>No current qualified support route is retained. Facility details remain available from the map.</p>':''}<p>Facility-to-incident estimates · partial road information.</p>${s.notices?.length?list(s.notices.map(n=>`<strong>${e(n.title)}</strong><p>${e(n.text)}</p>`)):''}${s.corridors?.length?TechnicalDetails('Shared roads',list(s.corridors.slice(0,6).map(c=>`${action(c.road,'road',`data-road="${e(c.road)}"`)} <span>${c.routeCount} retained route relationships</span>`))):''}${s.communities?.length?TechnicalDetails('Nearby communities',list(s.communities.slice(0,12).map(c=>`${action(c.name,'community',`data-entity="${e(c.id)}"`)}${Number.isFinite(c.distanceKm)?`<p>${c.distanceKm.toFixed(1)} km from the reported incident point</p>`:''}`))):''}${TechnicalDetails('Operational coverage',`<p>Inspect one category of retained facility-to-community routes. These are calculated paths, not continuous coverage boundaries.</p><div class="situation-controls">${[['emergency_hospital','Healthcare'],['fire_response','Fire response'],['designated_reception','Reception']].map(([id,label])=>action(label,'coverage',`data-category="${id}"`)).join('')}</div>`)}<p>${e(s.limitation)}</p></section>`;}
export function CommunityMarkup(c){if(!c)return'<p>This community is not in the retained incident context.</p>';return `<h3>${e(c.name)}</h3>${DetailRows([['From reported incident point',Number.isFinite(c.distanceKm)?c.distanceKm.toFixed(1)+' km':null],['Municipality',c.municipality],['Population context',c.population?`${c.population.value.toLocaleString('en-GB')} residents · Census ${c.population.referenceYear}`:null]])}${c.population?'<p>Census population is not the number of people currently present.</p>':''}<h3>Support for this community</h3>${SupportRows(c.groups)}${!c.groups.some(g=>g.primary)?'<p>No current qualified support route is retained for this community.</p>':''}<p>Facility-to-community calculated routes. No evacuation need is inferred from proximity.</p>${c.nearbyDesignations.length?`<h4>Designated reception within 8 km</h4>${list(c.nearbyDesignations.map(f=>`<strong>${e(f.name)}</strong><p>${f.distanceKm.toFixed(1)} km straight line · ${f.activationConfirmed?'Current activation record retained':'No current activation confirmed'}</p>`))}`:''}${TechnicalDetails('Location and population sources',DetailRows([['Location source',c.source],['Received',date(c.receivedAt)],['Census reference year',c.population?.referenceYear],['Population geographic unit',c.population?'Settlement':null]])+(c.population?`<a href="${e(c.population.sourceUrl)}" target="_blank" rel="noopener noreferrer">INE Census source</a>`:''))}`;}
export function RoadDependenciesMarkup(road,s){const c=s?.corridors?.find(c=>c.road===road);return c?`<h3>${e(road)} dependencies</h3><p>${c.routeCount} distinct retained calculated routes use this corridor. This does not identify a single surveyed road segment.</p>${list(c.relationships.map(r=>{const group=s.groups.find(g=>g.id===r.category),f=group?.options.find(o=>o.facilityId===r.facilityId)??s.communities.flatMap(c=>c.groups).flatMap(g=>g.options).find(o=>o.facilityId===r.facilityId),community=s.communities.find(c=>c.id===r.subjectId);return `<strong>${e(f?.name??'Retained facility')}</strong><p>${e(category(r.category))}${community?' · '+e(community.name):' · incident support'}</p><p>Calculated ${e(date(r.calculatedAt))} · road source checked ${e(date(r.roadCheckedAt))}</p>${action('Inspect facility','facility',`data-entity="${e(r.facilityId)}"`)}`}))}`:'<p>No current qualified route dependency is retained for this road.</p>';}
export function SupportComparisonMarkup(value,snapshot){return value?.changes?.length?`<h3>Support and access changes</h3>${list(value.changes.map(c=>`<strong>${e(c.subjectName??snapshot?.places?.find(p=>p.id===c.subjectId)?.name??snapshot?.incident?.name??"Incident support")} · ${e(category(c.category))}</strong>${DetailRows([['Primary',`${c.previous.primaryName??'None retained'} → ${c.current.primaryName??'None retained'}`],['Calculated minutes',`${c.previous.minutes??'—'} → ${c.current.minutes??'—'}`],['Retained options',`${c.previous.options} → ${c.current.options}`]])}`))}`:'';}
export function CausalMarkup(events=[]){return events.length?TechnicalDetails('Why support changed',list(events.slice(0,5).map(c=>`<strong>${e(({CAPABILITY_CHANGED:'Verified capability changed',ROUTE_CHANGED:'Road access changed',RECEPTION_ACTIVATION_CHANGED:'Reception activation changed'}[c.triggerKind])??'Operational relationship changed')}</strong><p>${e(date(c.knownAt))}</p>${list(c.supportChanges.map(x=>`${e(category(x.category))}: ${x.previous.options} → ${x.current.options} retained options`))}`))):'';}
