import {e,button} from './html.js';
import {situationRequest} from '../../vigiaApi.js';
import {showSituationMapScene} from '../../mapRuntime.js?v=3.0.0';
import {CommunityMarkup,SupportComparisonMarkup} from './operational-support.js';
import {MaterialChanges} from './situation-intelligence.js';
import {IntelligenceGapsMarkup,KnowledgeChangesMarkup,KnowledgeImpactMarkup,RequirementDetailMarkup,RequirementSourcesMarkup} from './collection-intelligence.js';
import {collectionRequest} from '../../vigiaApi.js';

const date=v=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date(v))+' UTC':'Time unavailable';
const btn=(label,cmd,attrs='',primary=false)=>button(label,'op-'+cmd,{tone:primary?'primary':'',extra:attrs});
const names={emergency_hospital:'Emergency healthcare',fire_response:'Fire response',civil_protection:'Civil protection',designated_reception:'Reception'};
const qualification=id=>({emergency_hospital:'Verified emergency department',fire_response:'Verified fire-response capability',civil_protection:'Qualified civil protection',designated_reception:'Officially designated · activation separately verified'}[id]);
const row=(g)=>`<section class="op-support-row"><h3>${e(names[g.id])}</h3>${g.primary?`<div class="op-option"><button class="op-name" data-action="op-facility" data-id="${e(g.primary.facilityId)}">${e(g.primary.name)}</button><strong>${Math.round(g.primary.minutes)} <span>min</span></strong></div><p>${e(qualification(g.id))}</p><p>${g.secondary?'Alternative: '+e(g.secondary.name)+' · '+Math.round(g.secondary.minutes)+' min':'Only retained qualified option'}</p><div class="op-road-links">${g.primary.roads.map(r=>btn(r,'road',`data-road="${e(r)}"`)).join('')}</div><p class="op-meta">Calculated ${e(date(g.primary.calculatedAt))} · facility to incident</p>`:'<p>No current qualified route retained.</p>'}</section>`;
export function OperationalSlot(){return '<section class="op-workspace" data-operational-slot aria-label="Operational intelligence"><h2>Operational support</h2><p role="status">Reading retained support…</p></section>';}

export function installOperationalPicture({state,activeMap,showOverlay}){
 let busy=false,epoch=0,lastContent=null,baselineModel=null,restoreTimer=null;let model=null,incident=null,pending=null,serial=0,selection={},failures=[],section='support',times=[],index=0,timer=null,active=false,root=null,contextRoad=null;
 let collection=null;
 const query=async(part,params={})=>{const id=incident,n=epoch;const result=await situationRequest(id,part,params);if(id!==incident||n!==epoch)throw Error('stale_selection');return result;};
 // Collection intelligence is additive: if it is unavailable the gaps section
 // still renders exactly what it rendered before.
 const collectionQuery=async(part,params={})=>{const id=incident,n=epoch;const result=await collectionRequest(id,part,params);if(id!==incident||n!==epoch)throw Error('stale_selection');return result;};
 const loadCollection=async()=>{try{collection=await collectionQuery('tasks',{...selection.at?{at:selection.at}:{},limit:'6'});}catch(error){if(error?.message==='stale_selection')throw error;collection={unavailableReason:'Collection intelligence is unavailable for this incident.'};}return collection;};
 const markBusy=()=>{if(root){root.setAttribute('aria-busy',String(busy));root.querySelectorAll('button').forEach(b=>b.disabled=busy);}};
 const stop=()=>{clearTimeout(timer);timer=null;};
 const restoreMap=()=>{if(restoreTimer||!active||!valid())return;let attempts=0;const retry=()=>{restoreTimer=null;if(!active||!valid())return;if(activeMap()?.dataset.situationMode)return;if(!showMap()&&++attempts<40)restoreTimer=setTimeout(retry,250);};restoreTimer=setTimeout(retry,0);};
 const valid=()=>root?.isConnected&&incident===state.selectedIncidentId;
 const options=()=>({...selection,...failures.length?{failures:JSON.stringify(failures)}:{}});
 function showMap(){if(!valid()||!model?.features)return false;const mode=failures.length?'SCENARIO':selection.at?'HISTORICAL':'OPERATIONAL',label=failures.length?'Scenario — not observed reality · dashed: lost · blue: retained':selection.at?'Historical replay · '+date(model.knownAt):selection.category?names[selection.category]+' · retained point/path coverage':'Operational Picture · qualified support and communities';
  const shown=showSituationMapScene(activeMap(),{incident:model.incident,facilities:[],routes:[]},{mode,picture:model,label});if(shown)active=true;return shown;
 }
 const facilityName=id=>[...baselineModel?.support.groups??[],...model?.support.groups??[],...model?.communities.flatMap(c=>c.groups)??[]].flatMap(g=>g.options).find(f=>f.facilityId===id)?.name??'Selected facility';
 function head(){return `<div class="op-heading"><h2>${section==='support'?'Operational support':section==='road'?selection.road:section==='community'?'Community intelligence':section==='communities'?'Communities':section==='facility'?'Qualified support':section==='replay'?'Mission Replay':section==='stress'?'Operational Stress Test':section==='gaps'?'Intelligence gaps':section==='knowledge'?'What VIGIA learned':'Causal timeline'}</h2>${btn('Operational Picture','picture','',true)}</div><p class="op-meta">Retained at ${e(date(model?.knownAt))} · evaluated ${e(date(model?.evaluatedAt))}</p><nav class="op-tools" aria-label="Operational views">${[['support','Support'],['communities','Communities'],['timeline','What changed'],['knowledge','What VIGIA learned'],['replay','Replay incident'],['stress','Stress test'],['gaps',`${model?.gaps?.length??0} gaps`]].map(([v,l])=>btn(l,'section',`data-section="${v}" aria-pressed="${section===v}"`)).join('')}</nav>${failures.length?`<div class="op-assumption"><strong>Scenario — not observed reality</strong><p>${failures.map(f=>e(f.kind==='ROAD_UNAVAILABLE'?f.entityId:facilityName(f.entityId))+' unavailable').join(' + ')}</p>${btn('Add failure','add')}${btn('Exit scenario','clear')}</div>`:''}<div class="op-coverage" aria-label="Coverage mode">${[['','All support'],['emergency_hospital','Healthcare'],['fire_response','Fire response'],['designated_reception','Reception']].map(([v,l])=>btn(l,'coverage',`data-category="${v}" aria-pressed="${(selection.category??'')===v}"`)).join('')}</div>${selection.category?`<p class="op-meta">${selection.category==='fire_response'?'≤10 / 10–20 / >20 min or no retained route':selection.category==='emergency_hospital'?'≤15 / 15–30 / >30 min or no retained route':'Designated nearby · activation confirmed or unconfirmed'}. Points and calculated paths only.</p>`:''}`;}
 function support(){return model.support.groups.filter(g=>['emergency_hospital','fire_response','designated_reception'].includes(g.id)).map(row).join('')+`<section class="op-support-row"><h3>Shared access</h3>${model.support.corridors.slice(0,3).map(c=>`<div class="op-corridor">${btn(c.road,'road',`data-road="${e(c.road)}"`)}<span>${c.routeCount} retained support relationships</span>${btn('Test unavailable','fail',`data-kind="ROAD_UNAVAILABLE" data-id="${e(c.road)}"`)}</div>`).join('')||'<p>No current shared corridor established.</p>'}</section>${model.support.notices.slice(0,3).map(n=>`<p class="op-notice"><strong>${e(n.title)}</strong> ${e(n.text)}</p>`).join('')}<p class="op-meta">Partial road coverage. Calculated routes do not establish safe access.</p>`;}
 function communities(){return `${btn('Show communities with limited redundancy','limited')}<div class="op-community-list">${model.communities.slice(0,20).map(c=>`<article>${btn(c.name,'community',`data-id="${e(c.id)}"`)}<p>${c.population?e(c.population.value)+' residents · Census '+e(c.population.referenceYear)+' · ':''}${Number.isFinite(c.distanceKm)?c.distanceKm.toFixed(1)+' km from incident point':''}</p><p>${e(c.resilience.reasons[0]??'Qualified support retained')}</p></article>`).join('')}</div>`;}
 function road(){const c=model.support.corridors.find(c=>c.road===selection.road);return `<p>Shared operational corridor</p><p>${c?.roadInformation?.restrictions?.length?'Published restrictions reference this road':'No matched restriction in partial retained coverage'} · checked ${e(date(c?.roadInformation?.checkedAt))}</p><p>${c?.routeCount??0} retained route relationships. Whole calculated paths are highlighted; this is not a surveyed road segment.</p><div class="op-tools">${btn('Show dependencies','picture')}${btn('Test unavailable','fail',`data-kind="ROAD_UNAVAILABLE" data-id="${e(selection.road)}"`,true)}${btn('Ask VIGIA about this road','ask-road')}</div>${c?.relationships.map(r=>`<article class="op-dependency"><strong>${e(facilityName(r.facilityId))}</strong><p>${e(names[r.category]??r.category)}${model.communities.find(c=>c.id===r.subjectId)?' · '+e(model.communities.find(c=>c.id===r.subjectId).name):' · incident support'}</p><p class="op-meta">Road source checked ${e(date(r.roadCheckedAt))} · calculated ${e(date(r.calculatedAt))}</p></article>`).join('')??'<p>No current qualified dependency retained.</p>'}`;}
 function coverageKey(){const c=selection.category;if(!c||c==='designated_reception')return '';const bands=c==='fire_response'?[10,20]:[15,30];return `<div class="op-coverage-key" aria-label="Map categories"><span class="near">≤${bands[0]} min</span><span class="middle">${bands[0]}–${bands[1]} min</span><span class="long">>${bands[1]} min</span><span class="unknown">No retained route</span></div>`;}
 function selectedCommunity(){const c=model.communities.find(c=>c.id===selection.communityId);return c?`${btn('Show support network','network')}${btn('Test access loss','community-loss')}${btn('Show coverage','coverage','data-category="emergency_hospital"')}${CommunityMarkup(c)}<h3>Support resilience</h3><ul>${c.resilience.reasons.map(r=>`<li>${e(r)}</li>`).join('')}</ul>`:'<p>Community not retained.</p>';}
 function paint(body=null){if(!valid()||!model?.support)return;const focused=document.activeElement?.dataset?.action;lastContent=body;root.innerHTML=head()+coverageKey()+`<div data-op-body>${body??(section==='support'?support():section==='communities'?communities():section==='road'?road():section==='community'?selectedCommunity():'')}</div><form class="op-ask"><label for="op-question">Ask the map</label><div><input id="op-question" name="question" maxlength="240" placeholder="What depends on EM527?" required><button class="btn" type="submit">Ask</button></div></form><p class="op-feedback" role="status" aria-live="polite"></p>`;markBusy();if(focused)root.querySelector(`[data-action="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});}
 async function load(){const n=++serial,id=incident;const next=await query('picture',options());if(n!==serial||id!==state.selectedIncidentId||!valid())return false;if(!next.support)throw Error('No retained operational picture is available.');model=next;if(!failures.length)baselineModel=next;return true;}
 async function refresh(){if(await load()){paint(['facility','replay','timeline','gaps','knowledge','stress'].includes(section)?lastContent:null);if(active)showMap();}}
 async function navigate(next){stop();lastContent=null;section=next;
  if(next==='support'||next==='communities'){selection={...selection,entityId:undefined,road:undefined,communityId:undefined};await refresh();return;}
  if(next==='gaps'){root.querySelector('[data-op-body]').textContent='Reading information requirements…';await loadCollection();if(!valid())return;paint(IntelligenceGapsMarkup(model.gaps,collection));return;}
  if(next==='knowledge'){root.querySelector('[data-op-body]').textContent='Reading knowledge changes…';const r=await collectionQuery('knowledge-changes');if(!valid())return;paint(KnowledgeChangesMarkup(r));return;}
  if(next==='timeline'){const r=await query('tool/getCausalTimeline',selection.at?{at:selection.at}:{});if(!valid())return;paint((r.result?.causalEvents??[]).filter(c=>c.supportChanges.length).slice(0,8).map(c=>`<article class="op-dependency"><h3>${e(({ROUTE_CHANGED:'Calculated access changed',CAPABILITY_CHANGED:'Qualified support changed',RECEPTION_ACTIVATION_CHANGED:'Reception activation changed'})[c.triggerKind]??'Access picture changed')}</h3><p>${e(date(c.knownAt))}</p>${c.supportChanges.map(x=>`<p>${e(x.subjectName??model.communities.find(v=>v.id===x.subjectId)?.name??model.incident.name)} · ${e(names[x.category]??x.category)}: ${x.previous.options} → ${x.current.options} retained options</p>`).join('')}${btn('Show change on map','change',`data-at="${e(c.knownAt)}"`)}</article>`).join('')||'<p>No material causal change retained in this interval.</p>');return;}
  if(next==='stress'){root.querySelector('[data-op-body]').textContent='Testing bounded failure assumptions…';const r=await query('stress',selection.at?{at:selection.at}:{});if(!valid())return;paint(`<p>Scenario analysis · ${r.results?.length??0} failure combinations · assumptions only.</p>${(r.results??[]).map((c,i)=>`<article class="op-dependency"><h3>${i===0?'Most consequential retained dependency':c.failures.length===1?'Single failure':'Combined failure'}</h3><p>${c.failures.map(f=>e(f.kind==='ROAD_UNAVAILABLE'?f.entityId:facilityName(f.entityId))).join(' + ')}</p><p>${c.affectedRelationships} affected relationships · ${c.noAlternative.length} support groups lose their retained option</p>${btn('Inspect consequences','stress-result',`data-failures="${e(JSON.stringify(c.failures))}"`)}</article>`).join('')}`);return;}
  if(next==='replay'){const r=await query('times');if(!valid())return;times=[...r.times].sort((a,b)=>Date.parse(a.knownAt)-Date.parse(b.knownAt));index=0;replayControls();}
 }
 function replayControls(extra=''){paint(times.length?`<p><strong>Historical replay</strong> · retained captures only. Gaps between captures are unknown.</p><label class="situation-field">Retained time<select data-op-time aria-label="Retained time">${times.map((t,i)=>`<option value="${i}" ${i===index?'selected':''}>${e(date(t.knownAt))}</option>`).join('')}</select></label><div class="op-tools">${btn(timer?'Pause':'Play',timer?'pause':'play')}${btn('Step','step')}${btn('Compare with now','compare-now')}${btn('Return to now','now')}</div><div data-op-comparison>${extra}</div>`:'<p>No retained snapshots available for replay.</p>');}
 async function frame(){selection={at:times[index].knownAt};failures=[];if(await load()){active=true;showMap();replayControls(`<p>Showing ${e(date(model.knownAt))}</p>${['temperature','windSpeed','humidity'].map(k=>model.weather?.[k]).filter(m=>Number.isFinite(m?.value)).map(m=>`<p>${e(m.label??'Weather')}: ${e(m.value)} ${e(m.unit??'')} · measured ${e(date(m.observedAt))}</p>`).join('')}${MaterialChanges(model.changes??[])}${support()}`);}}
 async function play(){if(!valid())return stop();await frame();if(!valid())return stop();if(index<times.length-1){index++;timer=setTimeout(()=>void play().catch(feedback),2000);root.querySelector('[data-action="op-play"]')?.setAttribute('data-action','op-pause');const b=root.querySelector('[data-action="op-pause"]');if(b)b.textContent='Pause';}else{stop();replayControls('<p>End of retained history.</p>'+support());}}
 function feedback(error){if(error?.message==='stale_selection')return;if(valid())root.querySelector('.op-feedback').textContent=error?.message??String(error);}
 async function select(kind,id){stop();lastContent=null;selection={...selection,road:undefined,entityId:undefined,communityId:undefined};if(kind==='road'){selection.road=id;contextRoad=id;section='road';}else if(kind==='community'){selection.communityId=id;section='community';}else{selection.entityId=id;section='facility';}active=true;if(!await load())return;showMap();if(kind==='community'){paint();}else if(kind==='facility'){const g=model.support.groups.find(g=>g.options.some(o=>o.facilityId===id)),o=g?.options.find(o=>o.facilityId===id);paint(`<h3>${e(o?.name??'Qualified support facility')}</h3><p>${e(qualification(g?.id)??'Retained facility relationship')}</p><p>${o?Math.round(o.minutes)+' min calculated · '+e(o.roads.join(' → ')):'No current qualified route retained'}</p>${btn('Show support network','network')}${btn('Test unavailability','fail',`data-kind="FACILITY_UNAVAILABLE" data-id="${e(id)}"`,true)}<p>${g?.secondary?'Retained alternative: '+e(g.secondary.name):'No retained qualified alternative'}</p>`);}else paint();}
 async function fail(assumption){stop();if(!failures.some(f=>f.kind===assumption.kind&&f.entityId===assumption.entityId))failures=[...failures,assumption].slice(0,8);active=true;section='support';if(await load()){showMap();paint(`<h3>What changes under this assumption</h3>${SupportComparisonMarkup(model.consequences)}${MaterialChanges(model.changes??[])}${support()}`);}}
 async function ask(question){const q=/what if it closes|e se fechar/i.test(question)&&contextRoad?'What if '+contextRoad+' is unavailable?':question;const answer=await query('ask',{question:q,...selection.at?{at:selection.at}:{}});if(!valid())return;const call=answer.toolCalls?.[0];if(call?.name==='getRoadDependencies'&&call.args.road)await select('road',call.args.road);else if(call?.name==='runScenario'){failures=call.args.failures?JSON.parse(call.args.failures):[{kind:call.args.kind??'ROAD_UNAVAILABLE',entityId:call.args.road??call.args.entityId}];active=true;if(await load()){showMap();paint(SupportComparisonMarkup(model.consequences)+support());}}else if(call?.name==='getCommunitySupport'){selection={...selection,filter:call.args.filter,road:call.args.road,communityId:call.args.entityId};active=true;section='communities';await refresh();}else if(call?.name==='getOperationalCoverage'){selection.category=call.args.type??'emergency_hospital';active=true;await refresh();}feedback(answer.answer);}
 async function handle(target){const cmd=target.dataset.action.slice(3);if(cmd!=='play'&&cmd!=='pause')stop();
  if(cmd==='retry'){root=null;mount();return;}
  if(cmd==='picture'){active=true;if(Date.now()-Date.parse(model.evaluatedAt)>15000)await refresh();showMap();activeMap()?.scrollIntoView({block:'nearest'});}
  else if(cmd==='network'){selection={...selection,category:undefined,limited:undefined,filter:undefined};active=true;if(selection.communityId)await select('community',selection.communityId);else if(selection.entityId)await select('facility',selection.entityId);else await refresh();}
  else if(cmd==='section')await navigate(target.dataset.section);
  else if(['road','community','facility'].includes(cmd))await select(cmd,target.dataset.road??target.dataset.id);
  else if(cmd==='fail')await fail({kind:target.dataset.kind,entityId:target.dataset.id});
  else if(cmd==='clear'){failures=[];await refresh();}
  else if(cmd==='coverage'){selection.category=target.dataset.category||undefined;active=true;await refresh();}
  else if(cmd==='limited'){selection.limited='true';active=true;await refresh();}
  else if(cmd==='community-loss'){const c=model.communities.find(c=>c.id===selection.communityId),r=c?.resilience.sharedRoads[0]??c?.groups.find(g=>g.primary)?.primary.roads[0];if(r)await fail({kind:'ROAD_UNAVAILABLE',entityId:r});else feedback('No current significant access road is retained for this community.');}
  else if(cmd==='ask-road')await ask('What depends on '+selection.road+'?');
  else if(cmd==='stress-result'){failures=JSON.parse(target.dataset.failures);active=true;section='support';if(await load()){showMap();paint(SupportComparisonMarkup(model.consequences)+support());}}
  else if(cmd==='add'){paint(`<h3>Add failure</h3><div class="op-tools">${(baselineModel??model).support.corridors.map(c=>btn(c.road,'fail',`data-kind="ROAD_UNAVAILABLE" data-id="${e(c.road)}"`)).join('')}${(baselineModel??model).support.groups.filter(g=>g.primary).map(g=>btn(g.primary.name,'fail',`data-kind="FACILITY_UNAVAILABLE" data-id="${e(g.primary.facilityId)}"`)).join('')}</div><p>Choose another retained object. Up to eight simultaneous assumptions.</p>`);}
  else if(cmd==='step'){index=Math.min(index+1,times.length-1);await frame();}
  else if(cmd==='play')await play();
  else if(cmd==='pause'){stop();replayControls(support());}
  else if(cmd==='now'){selection={};failures=[];section='support';await refresh();}
  else if(cmd==='compare-now'){const r=await query('compare',{from:times[index].knownAt,to:new Date().toISOString()});if(valid())replayControls(MaterialChanges(r.material??r.changes)+SupportComparisonMarkup(r.support));}
  else if(cmd==='change'){const at=target.dataset.at,from=new Date(Date.parse(at)-1).toISOString(),r=await query('compare',{from,to:at});selection={at};active=true;if(await load()){showMap();paint(MaterialChanges(r.material??r.changes)+SupportComparisonMarkup(r.support)+btn('Show before','before',`data-at="${e(from)}"`)+btn('Show after','before',`data-at="${e(at)}"`));}}
  else if(cmd==='before'){selection={at:target.dataset.at};if(await load())showMap();}
  else if(cmd==='requirement'){const r=await collectionQuery('requirements/'+encodeURIComponent(target.dataset.requirement),selection.at?{at:selection.at}:{});if(valid())paint(RequirementDetailMarkup(r));}
  else if(cmd==='requirement-sources'){const r=await collectionQuery('requirements/'+encodeURIComponent(target.dataset.requirement)+'/sources',selection.at?{at:selection.at}:{});if(valid())paint(RequirementSourcesMarkup(r));}
  else if(cmd==='preview'){const detail=await collectionQuery('requirements/'+encodeURIComponent(target.dataset.requirement),selection.at?{at:selection.at}:{});const request=detail.availablePreview;if(!request){if(valid())paint(RequirementDetailMarkup(detail));return;}
   const r=await collectionQuery('preview',{...request,...selection.at?{at:selection.at}:{}});if(valid())paint(KnowledgeImpactMarkup(r));}
  else if(cmd==='preview-map'){const intent=JSON.parse(target.dataset.intent);
   // Validated map intents reuse the existing picture selection. The renderer is
   // not touched by this branch.
   if(intent.type==='SHOW_COVERAGE'){selection.category=intent.category;section='support';active=true;await refresh();showMap();}
   else if(intent.type==='FOCUS_ROAD')await select('road',intent.road);}
 }
 function mount(){const slot=document.querySelector('[data-operational-slot]');if(!slot||slot===root)return;if(incident!==state.selectedIncidentId){stop();serial++;epoch++;busy=false;model=null;selection={};failures=[];active=false;section='support';incident=state.selectedIncidentId;pending=null;}root=slot;
  root.addEventListener('click',ev=>{const t=ev.target.closest('[data-action^="op-"]');if(!t)return;ev.stopPropagation();if(busy)return;busy=true;epoch++;markBusy();void handle(t).catch(feedback).finally(()=>{busy=false;markBusy();});});
  root.addEventListener('submit',ev=>{ev.preventDefault();if(busy)return;busy=true;epoch++;markBusy();void ask(new FormData(ev.target).get('question')).catch(feedback).finally(()=>{busy=false;markBusy();});});
  root.addEventListener('change',ev=>{if(ev.target.matches('[data-op-time]')&&!busy){stop();busy=true;epoch++;markBusy();index=Number(ev.target.value);void frame().catch(feedback).finally(()=>{busy=false;markBusy();});}});
  if(model){paint(lastContent);if(active)restoreMap();return;}
  if(!pending)pending=load().finally(()=>pending=null);void pending.then(()=>{paint();}).catch(error=>{if(valid())root.innerHTML=`<h2>Operational support</h2><p role="alert">${e(error.message)}</p>${btn('Retry','retry')}`;});
 }
 new MutationObserver(()=>{if(root&&!root.isConnected)stop();mount();restoreMap();}).observe(document.getElementById('app')??document.body,{childList:true,subtree:true});
 document.addEventListener('vigia:current-map',()=>{if(!valid())return;stop();epoch++;active=false;selection={};failures=[];section='support';busy=true;markBusy();void refresh().catch(feedback).finally(()=>{busy=false;markBusy();});});
 document.addEventListener('vigia:operational-select',ev=>{if(valid()&&!busy&&ev.detail?.kind!=='incident')void select(ev.detail.kind==='community'?'community':ev.detail.kind==='road'?'road':'facility',ev.detail.road??ev.detail.entityId).catch(feedback);});
 document.addEventListener('vigia:ask-map',ev=>{if(!valid()||ev.detail.incidentId!==incident||busy)return;const command=ev.detail.answer?.uiIntents?.[0];if(!command)return;epoch++;if(command.type==='FOCUS_ROAD')void select('road',command.road).catch(feedback);else if(command.type==='SHOW_COVERAGE'){selection.category=command.category;active=true;void refresh().catch(feedback);}else if(command.type==='SHOW_COMMUNITIES'){selection={filter:command.filter,road:command.road};section='communities';active=true;void refresh().catch(feedback);}else if(command.type==='ENTER_SCENARIO'){failures=[command.failures].flat();active=true;void refresh().catch(feedback);}else if(command.type==='SHOW_HISTORICAL_SNAPSHOT'){selection={at:command.at};active=true;void refresh().catch(feedback);}});
 document.addEventListener('click',ev=>{if(ev.target.closest('[data-action="operational-picture"]')){active=true;mount();if(model)showMap();root?.scrollIntoView({block:'nearest'});}});
 mount();
}
