import {icon,brand} from './icons.js';
import {e,button} from './html.js';
import {routeProjectionDependency,timeLabel} from '../../canonicalViewModel.js';
import {routeURL,incidentFor} from '../data/model.js';
export const ROUTES=[
 ['command-overview','Command Overview','Portugal wildfire situational picture','home'],
 ['incidents','Incidents','Search, filter and explore all records.','file'],
 ['incident-detail','Incident Detail','Understand the incident and its latest information.','map'],
 ['intelligence','Fire Activity','What is happening around this fire, and what has changed.','flame'],
 ['operations','Response & Access','Access, surrounding places and mapped response facilities.','target'],
 ['national-awareness','National Awareness','Incidents, context and coverage across Portugal.','globe']
];
export function shell(route,state,content){const r=ROUTES.find(x=>x[0]===route);const title=['incident-detail'].includes(route)?incidentFor(state)?.name||r?.[1]:route==='reports-analytics'?'Reports & Analytics':r?.[1]||'Page not found';

 const field=['intelligence','operations'].includes(route);
 const root=state.runtime, session=root.runtime.session, actor=session?.actor, projection=routeProjectionDependency(root,route==='national-awareness'?'global-awareness':route), current=projection.state==='READY', loading=['UNINITIALIZED','BOOTSTRAPPING'].includes(root.runtime.resourceState)&&!projection.retained, status=current?'Connected':loading?'Connecting':projection.state==='STALE'?'Last known':projection.state==='FAILED'?(field?'Connection interrupted':'Unavailable'):projection.state==='DEGRADED'?'Source degraded':'Updating';
 let banner=current?'':loading?'<strong>Connecting to incident services.</strong><p>Waiting for the latest available information.</p>':projection.state==='STALE'?'<strong>Last known information</strong><p>Retained values below are not current. '+(projection.lastGoodAt?'Last received '+e(timeLabel(projection.lastGoodAt))+'. ':'')+'Refresh does not imply new observation.</p>':projection.state==='FAILED'?'<strong>Information unavailable</strong><p>No retained information is available for this view.</p>':'<strong>Limited information.</strong><p>Source timestamps and missing measurements remain explicit.</p>';
 if(field&&projection.state==='FAILED')banner='<strong>Connection interrupted</strong><p>Refresh to reconnect to incident services.</p>';
 const validTime=Number.isFinite(Date.parse(state.generatedAt??''));
 return `<a class="skip-link" href="#main-content">Skip to content</a><div class="mobile-shade" data-action="nav-close"></div><aside id="primary-navigation" class="vg-sidebar" aria-label="Primary navigation"><a class="brand" href="#/command-overview" aria-label="Vigia home">${brand()}</a>${button('Close navigation','nav-close',{ico:'close',tone:'icon-button mobile-close'})}<nav class="vg-nav">${ROUTES.map(([path,label,,ico])=>`<a href="${routeURL(path,state.selected)}" class="nav-link ${route===path?'active':''}" ${route===path?'aria-current="page"':''}>${icon(ico)}<span>${label}</span></a>`).join('')}</nav><div class="vg-sidebar-bottom"><div class="sidebar-user"><span class="avatar">${e((actor?.name??actor?.id??"Operator").slice(0,2).toUpperCase())}</span><span><strong>${e(actor?.name??actor?.id??"Operator")}</strong><small>${e(session?.authenticated?actor?.role??"Authenticated":"Admission required")}</small><small>${e(actor?.region??"Authorized scope")}</small></span></div></div></aside>
 <div class="vg-main app-frame ${field?'field-shell':''}"><header class="vg-header"><div class="vg-header-left">${button('Open navigation','nav-toggle',{ico:'menu',tone:'icon-button mobile-menu'})}<div><h1>${e(title)}</h1><p>${e(r?.[2]||'Return to the overview.')}</p></div></div><div class="header-right"><span class="preview-control"><span class="demo-pill" data-projection-state="${e(projection.state)}">${e(status)}</span></span><span class="header-sep"></span><div class="header-context">${e(actor?.region??"Authorized scope")}<strong>${e(validTime?new Date(state.generatedAt).toLocaleDateString("en-GB",{timeZone:"UTC"}):"Time not reported")}</strong><strong>${e(validTime?new Date(state.generatedAt).toISOString().slice(11,16)+" UTC":"")}</strong></div>${button('Refresh data','refresh-runtime',{ico:'refresh',tone:'icon-button'})}</div></header><main class="vg-content" data-route-projection-state="${e(projection.state)}" id="main-content" tabindex="-1">${banner?`<div class="state-banner">${icon('info')}<div>${banner}</div></div>`:''}${content}</main><footer class="vg-page-footer"><span>VIGIA · Operational situation</span><span>${field?'Source time and location accompany each reading.':'Source observations ≠ official confirmation'}</span></footer></div><div class="toast-region" role="status" aria-live="polite"></div>`;
}
