import { randomUUID } from 'node:crypto';
import { readFile,writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createFieldIncidentPackage } from '../../packages/domain/src/fieldnet/contracts.mjs';
import { createRuntimeClient,governedIncidentCommandActorAuthorized } from './runtime_client.mjs';

const central=(process.env.COMMAND_SURVIVAL_API_URL??'http://127.0.0.1:4197').replace(/\/$/,''),field=(process.env.COMMAND_SURVIVAL_FIELD_URL??'http://127.0.0.1:4198').replace(/\/$/,''),proofFile=path.join(process.cwd(),'data/validation/command-survival/controlled-exercise-proof.json'),proof=JSON.parse(await readFile(proofFile,'utf8')),incidentId=proof.incidentId;
const client=createRuntimeClient({central,field}),session=await client.establishGovernedSession();
async function drainHistory(firstResponse,{maxPages=64}={}){
  const responses=[firstResponse];let current=firstResponse,tailCursor=current.body?.page?.nextCursor??null;
  while(current.body?.page?.hasMore===true){
    if(responses.length>=maxPages)throw new Error('command_survival_history_page_limit_reached');
    if(typeof tailCursor!=='string'||!tailCursor)throw new Error('command_survival_history_cursor_missing');
    const next=await client.centralRequest(`/api/v10/incident-command/incidents/${encodeURIComponent(incidentId)}/events?afterCursor=${encodeURIComponent(tailCursor)}&limit=250`);
    if(!next.ok)throw new Error(`command_survival_history_page_failed:${next.status}`);
    const nextCursor=next.body?.page?.nextCursor??null;
    if(next.body?.page?.hasMore===true&&nextCursor===tailCursor)throw new Error('command_survival_history_cursor_stalled');
    responses.push(next);current=next;tailCursor=nextCursor??tailCursor;
  }
  return{responses,tailCursor,events:responses.flatMap((item)=>item.body?.events??[])};
}
const routes=[];
for(const route of [`/api/v10/incident-command/incidents/${encodeURIComponent(incidentId)}`,`/api/v10/incident-command/incidents/${encodeURIComponent(incidentId)}/events`,...['FIREFIGHTER','COMPANY_OFFICER','DIVISION_SUPERVISOR','INCIDENT_COMMAND','DISPATCH_EOC','ACCOUNTABILITY','MAYDAY_RESCUE'].map((role)=>`/api/v10/incident-command/incidents/${encodeURIComponent(incidentId)}/projections/${role}`),`/api/v10/incident-command/incidents/${encodeURIComponent(incidentId)}/fallback/ACCOUNTABILITY_ROSTER`])routes.push(await client.centralRequest(route));
const eventStream=routes[1].body,initialHistory=await drainHistory(routes[1]),fieldPackage=createFieldIncidentPackage({incidentId,createdAt:new Date().toISOString(),incidentState:{canonicalEventId:proof.physicalAnchor.eventId},physicalObservations:[{observationId:proof.physicalAnchor.eventId,sourceFamily:proof.physicalAnchor.sourceFamilies[0],observedAt:proof.physicalAnchor.lastObservedAt}],commandSurvival:{events:eventStream.events,exportedAt:new Date().toISOString()}});
routes.push(await client.fieldRequest('/api/fieldnet/incidents/import',{method:'POST',body:JSON.stringify({package:fieldPackage,actor:'exercise:runtime-verifier'})}));
const verificationRunId=randomUUID(),runtimeEventId=`${proof.exerciseId}:runtime-route-observation:${verificationRunId}`,runtimeObservationId=`observation:${proof.exerciseId}:runtime:${verificationRunId}`,observation={eventId:runtimeEventId,type:'OBSERVATION_RECORDED',payload:{observationId:runtimeObservationId,kind:'ROUTE_CONTRACT_PROOF',source:'CONTROLLED_EXERCISE',owner:'exercise:runtime-verifier'},observedAt:new Date().toISOString(),receivedAt:new Date().toISOString(),exercise:true};
routes.push(await client.fieldRequest(`/api/fieldnet/incidents/${encodeURIComponent(incidentId)}/command-survival/events`,{method:'POST',body:JSON.stringify({event:observation,actor:'exercise:runtime-verifier'})}));
routes.push(await client.fieldRequest(`/api/fieldnet/incidents/${encodeURIComponent(incidentId)}/command-survival`));
routes.push(await client.fieldRequest('/api/fieldnet/sync',{method:'POST',body:'{}'}));
const finalQuery=initialHistory.tailCursor?`?afterCursor=${encodeURIComponent(initialHistory.tailCursor)}&limit=250`:'?limit=250';
routes.push(await client.centralRequest(`/api/v10/incident-command/incidents/${encodeURIComponent(incidentId)}/events${finalQuery}`));
const finalHistory=await drainHistory(routes.at(-1)),appliedEvents=finalHistory.events.filter((event)=>event.eventId===runtimeEventId),allResponses=[...routes,...initialHistory.responses.slice(1),...finalHistory.responses.slice(1)],checks={sessionAuthenticated:session.reloaded.body?.authenticated===true,sessionActorAuthorized:session.actor?.name==='Miguel Almeida'&&session.actor?.title==='Shadow Operator'&&governedIncidentCommandActorAuthorized(session.actor),sessionReloadPersistent:session.issued.body?.sessionId===session.reloaded.body?.sessionId,sessionCookieHttpOnly:session.issued.setCookies.some((value)=>/HttpOnly/i.test(value))&&Boolean(session.cookie),allRoutesHttpSuccess:allResponses.every((item)=>item.ok),sevenRoleProjections:routes.slice(2,9).every((item)=>item.body?.schemaVersion==='vigia.incident-command-role-projection.v1'),fallbackAvailable:routes[9].body?.schemaVersion==='vigia.manual-fallback-export.v1',fieldPackageImported:routes[10].body?.incident?.incidentId===incidentId,fieldCommandLocallyApplied:routes[11].body?.state?.observations?.[runtimeObservationId]?.kind==='ROUTE_CONTRACT_PROOF',fieldCommandReadableOffline:routes[12].body?.state?.incidentId===incidentId,syncAcknowledged:Number(routes[13].body?.pending)===0,centralCommandApplied:appliedEvents.length===1,centralAuditValid:finalHistory.responses.every((item)=>item.body?.verification?.valid===true),envelopeHashPresent:appliedEvents.length===1&&appliedEvents.every((event)=>typeof event.envelopeHash==='string')};
const failures=Object.entries(checks).filter(([,value])=>value!==true).map(([key])=>key),artifact={schemaVersion:'vigia.command-survival-runtime-verification.v1',verifiedAt:new Date().toISOString(),verificationRunId,incidentId,central,field,session:{authenticated:session.reloaded.body.authenticated,actor:session.actor,reloadPersistent:checks.sessionReloadPersistent,httpOnlyCookieRetained:checks.sessionCookieHttpOnly},history:{initialPages:initialHistory.responses.length,postSyncPages:finalHistory.responses.length,initialTailCursor:initialHistory.tailCursor},checks,failures,verdict:failures.length?'FAIL':'PASS',routes:allResponses.map((item)=>({url:item.url,status:item.status,durationMs:item.durationMs,schemaVersion:item.body?.schemaVersion??null,error:item.ok?null:item.body}))};await writeFile(path.join(process.cwd(),'data/validation/command-survival/runtime-verification.json'),`${JSON.stringify(artifact,null,2)}\n`);process.stdout.write(`${JSON.stringify(artifact,null,2)}\n`);if(failures.length)process.exitCode=1;
