import{mkdir,readFile,writeFile}from'node:fs/promises';
import path from'node:path';
import{fileURLToPath}from'node:url';
import{controlledHarness}from'../../apps/web/src/v2/fireground/controlled-harness.js';
import{commandModel}from'../../apps/web/src/v2/fireground/model.js';
import{dispatchView}from'../../apps/web/src/v2/fireground/views/specialized.js';
import{divisionView,firefighterView,incidentCommandView,officerView}from'../../apps/web/src/v2/fireground/views/roles.js';
import{evacuationPanel,fieldnetPanel,parPanel,resourcesPanel}from'../../apps/web/src/v2/fireground/views/panels.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=path.join(root,'data/validation/command-survival/fireground-product-proof.json');
const plain=(html)=>html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim(),model=(role)=>commandModel(controlledHarness(role),role),includes=(html,answers)=>answers.every((answer)=>plain(html).toLowerCase().includes(answer.toLowerCase()));
const cases=[
  {role:'FIREFIGHTER',answers:['Withdraw Alpha through west checkpoint','Alpha','Fire below crew','West checkpoint','Evacuate Alpha'],wrong:['regional coordination','candidate robustness'],render:firefighterView},
  {role:'COMPANY_OFFICER',answers:['Alpha','MEMBER NOT CONFIRMED OUTSIDE','MEMBER LOCATION STALE','Alpha Two'],wrong:['scientific proof'],render:officerView},
  {role:'DIVISION_SUPERVISOR',answers:['North flank','OVERDUE','Backup water + relief engine'],wrong:['detector','confidence score'],render:divisionView},
  {role:'INCIDENT_COMMAND',answers:['MAYDAY','EVACUATION INCOMPLETE','PUMP ENGAGED NO FLOW','PAR INCOMPLETE'],wrong:['precision','candidate robustness'],render:incidentCommandView},
  {role:'DISPATCH_EOC',answers:['Backup water supply','UNKNOWN','LOW','West access'],wrong:['Alpha Two','north flank uncertainty'],render:dispatchView}
];
const retrieval=cases.map((item)=>{const html=item.render(model(item.role));return{role:item.role,complete:includes(html,item.answers),wrongAnswer:item.wrong.some((word)=>plain(html).toLowerCase().includes(word.toLowerCase())),answerCount:item.answers.length,renderedCharacters:html.length};});
const roles=['FIREFIGHTER','COMPANY_OFFICER','DIVISION_SUPERVISOR','INCIDENT_COMMAND','DISPATCH_EOC','ACCOUNTABILITY','MAYDAY_RESCUE'],samples=[];for(let run=0;run<250;run+=1)for(const item of cases){const start=performance.now();item.render(model(item.role));samples.push(performance.now()-start);}samples.sort((a,b)=>a-b);const percentile=(p)=>Number(samples[Math.min(samples.length-1,Math.floor(samples.length*p))].toFixed(3));
const ic=model('INCIDENT_COMMAND'),par=plain(parPanel(ic)),evacuation=plain(evacuationPanel(ic)),resources=plain(resourcesPanel(ic)),offline=plain(fieldnetPanel(ic));
const css=await readFile(path.join(root,'apps/web/styles/v2/fireground-responsive.css'),'utf8'),files=['components.js','controlled-harness.js','format.js','model.js','render.js','runtime.js','views/panels.js','views/roles.js','views/specialized.js','../../../styles/v2/fireground.css','../../../styles/v2/fireground-responsive.css'],bytes={};for(const relative of files){const base=relative.startsWith('..')?path.join(root,'apps/web/src/v2/fireground'):path.join(root,'apps/web/src/v2/fireground');const file=path.resolve(base,relative);bytes[path.relative(root,file)]=(await readFile(file)).byteLength;}
const invariants={sevenDistinctRoleViews:roles.length===7,retrievalAllComplete:retrieval.every((item)=>item.complete),retrievalWrongAnswersZero:retrieval.every((item)=>!item.wrongAnswer),acknowledgementNotOutside:/ACKNOWLEDGED ≠ OUTSIDE/.test(evacuation)&&/PHYSICAL EXIT \/ REUNION \/ PAR STILL UNRESOLVED/.test(evacuation),parMakesUnresponsiveVisible:/Unresponsive 1/.test(par),maydayPinned:ic.maydays.some((item)=>item.pinned)&&ic.connection.state==='FIELDNET_LOCAL',offlineEssentialActions:['Report status','Submit PAR','Report location','Resource status'].every((item)=>offline.includes(item)),waterTruthSeparated:['Pump ENGAGED','Water flowing NO CONFIRMED FLOW','Sustainable NOT CONFIRMED','Demand gap One charged protection line'].every((item)=>resources.includes(item)),mobileBreakpoints:['max-width:1200px','max-width:800px','max-width:440px'].every((item)=>css.includes(item)),criticalControls:/min-height:64px/.test(css),controlledOnly:ic.controlled&&ic.incident.mode==='SHADOW_CONTROLLED'};
const failures=Object.entries(invariants).filter(([,passed])=>!passed).map(([name])=>name),proof={schemaVersion:'vigia.fireground-product-proof.v1',generatedAt:new Date().toISOString(),verdict:failures.length?'FAIL':'PASS',universe:'SHADOW',productionTruthExcluded:true,beforeAfter:{dedicatedActiveIncidentShell:{before:0,after:1},roleSpecificViews:{before:0,after:7},deterministicRetrievalCases:{before:0,after:5},deterministicRetrievalPassed:{before:0,after:retrieval.filter((item)=>item.complete).length},wrongAnswers:{before:null,after:retrieval.filter((item)=>item.wrongAnswer).length},closedLoopVisibleStages:{before:0,after:5},locationVerificationStates:{before:0,after:5},essentialOfflineActions:{before:0,after:4},dedicatedParEvacuationBoards:{before:0,after:2}},retrieval,performance:{renderSamples:samples.length,p50Ms:percentile(.5),p95Ms:percentile(.95),maxMs:percentile(1),sourceBytes:Object.values(bytes).reduce((sum,value)=>sum+value,0),files:bytes},responsive:{viewports:[1440,1280,1024,768,390],breakpoints:[1200,800,440],horizontalOverflow:'CSS_STRUCTURAL_ASSERTION_ONLY_BROWSER_POLICY_BLOCKED'},invariants,failures,externalBlockers:['PostGIS 55432 unreachable; Docker Desktop backend cannot launch within managed filesystem permissions.','Fresh in-app browser screenshots blocked by localhost navigation safety policy.'],artifacts:{handoff:'data/validation/command-survival/command-survival-handoff.json',productTest:'apps/api/test/fireground-product.test.mjs'}};
await mkdir(path.dirname(out),{recursive:true});await writeFile(out,`${JSON.stringify(proof,null,2)}\n`);process.stdout.write(`${JSON.stringify(proof,null,2)}\n`);if(failures.length)process.exitCode=1;
