import { randomUUID } from 'node:crypto';
import {
  combineForecastMembers,createForecast,createForecastAssimilationState,createForecastInputManifest,
  createForecastPolicyInput,createForecastReceipt,decideForecastAbstention,forecastAssetExposure,
  observationKinematicProgression,recentGrowthPersistence,verifyForecastReplay,windAlignedProgression
} from '../../../../../packages/domain/src/forecasting/index.mjs';
import { semanticHash } from '../../../../../packages/domain/src/intelligence/shared.mjs';
import { writeJsonAtomic } from '../../shared/json-file.mjs';
import { createForecastConsumerSnapshot } from './forecast-consumer-snapshot.mjs';
import { ForecastScoringController } from './forecast-scoring-controller.mjs';
import { loadCurrentForecastInputs } from './current-input-loader.mjs';
import { loadConfiguredContextPacks } from './context-pack-loader.mjs';

const polygonArea=(geometry)=>{const ring=geometry.coordinates[0],lat=ring.reduce((sum,item)=>sum+item[1],0)/ring.length*Math.PI/180,sx=111.32*Math.cos(lat),sy=110.574;let area=0;for(let i=0;i<ring.length-1;i+=1)area+=(ring[i][0]*sx)*(ring[i+1][1]*sy)-(ring[i+1][0]*sx)*(ring[i][1]*sy);return Math.abs(area)/2;};
export class ForecastRuntime{
  constructor({config,store,registry,runner,clock=()=>new Date()}={}){if(!config||!store||!registry||!runner)throw new Error('forecast_runtime_dependencies_required');Object.assign(this,{config,store,registry,runner,clock});this.scoring=new ForecastScoringController({store});}
  async initialize(){await this.store.initialize();return this.status();}
  status(){return{schemaVersion:'vigia.forecast-runtime-status.v1',store:this.store.status(),registryFingerprint:this.registry.fingerprint};}
  async runOnce(){
    await this.initialize();
    const runId=randomUUID(),startedAt=this.clock().toISOString(),source=await loadCurrentForecastInputs({realityReportFile:this.config.realityReportFile,realityRuntimeDir:this.config.realityRuntimeDir}),issuedAt=this.clock().toISOString(),modelEntry=this.registry.models.find((item)=>item.modelId==='VIGIA_TRANSPARENT_SPREAD_ENSEMBLE'),weather=source.weatherMembers[0]?.values??{},prior=this.store.latest(source.incidentId),revisions=source.perimeterHistory.map((item,index)=>({id:item.product.id??`perimeter:${index}`,observedAt:item.revisionTime,knowledgeTime:item.knowledgeTime,contentHash:`sha256:${item.product.checksumSha256}`,geometry:item.geometry,sourceClass:'OFFICIAL'})),assimilation=createForecastAssimilationState({incidentId:source.incidentId,informationCutoff:source.informationCutoff,perimeterRevisions:revisions,physicalObservationIds:source.inputs.map((item)=>item.id),priorForecast:prior}),physicalRunner=await this.runner.doctor(),physicalRunnerAvailable=physicalRunner.models.some((item)=>item.status==='READY'),contextPacks=await loadConfiguredContextPacks({config:this.config,informationCutoff:source.informationCutoff,bbox:[source.coordinate[0],source.coordinate[1],source.coordinate[0],source.coordinate[1]]}),inputAgeMs=Date.parse(issuedAt)-Date.parse(source.initialPerimeterMetadata.observedAt),abstention=decideForecastAbstention({initialPerimeter:source.initialPerimeter,perimeterHistoryCount:source.perimeterHistory.length,weatherMemberCount:source.weatherMembers.length,fuelAvailable:Boolean(contextPacks.fuel),terrainAvailable:Boolean(contextPacks.terrain),calibrationAvailable:false,associationCertain:Boolean(source.report.selection?.twinIncidentId),contradictionUnresolved:assimilation.state==='CONTRADICTED',geographyApplicable:true,fuelApplicable:Boolean(contextPacks.fuel),windSpeedMs:weather.windSpeedMs,inputAgeMs,physicalRunnerAvailable,requirePhysicalRunner:false}),inputManifest=createForecastInputManifest({incidentId:source.incidentId,forecastIssuedAt:issuedAt,informationCutoff:source.informationCutoff,initialPerimeter:source.initialPerimeterMetadata,inputs:source.inputs,weatherMembers:source.weatherMembers,fuelDataset:contextPacks.fuel?.dataset,terrainDataset:contextPacks.terrain?.dataset,modelVersion:modelEntry.version,policyVersion:'fire-spread-shadow-policy-v1'});
    const latestRevision=source.perimeterHistory.at(-1),scoreUpdate=latestRevision?await this.scoring.observe({incidentId:source.incidentId,observation:{id:`official-perimeter:${latestRevision.revisionTime}`,observedAt:latestRevision.revisionTime,knowledgeTime:latestRevision.knowledgeTime,contentHash:`sha256:${latestRevision.product.checksumSha256}`,geometry:latestRevision.geometry,maturity:'NRT'}}):null;
    let ensemble=null,horizons=[];
    if(abstention.state==='AVAILABLE'){
      const history=source.perimeterHistory,first=history[0],last=history.at(-1),durationHours=Math.max(1,(Date.parse(last.revisionTime)-Date.parse(first.revisionTime))/3_600_000),growth=Math.max(0,(polygonArea(last.geometry)-polygonArea(first.geometry))/durationHours),velocity=Math.sqrt(growth/Math.PI),members=[recentGrowthPersistence({issuedAt,initialPerimeter:source.initialPerimeter,areaGrowthKm2PerHour:growth}),windAlignedProgression({issuedAt,initialPerimeter:source.initialPerimeter,boundaryVelocityKmH:velocity,windDirectionDeg:weather.windDirectionDeg,windSpeedMs:weather.windSpeedMs}),observationKinematicProgression({issuedAt,initialPerimeter:source.initialPerimeter,boundaryVelocityKmH:velocity,recentBearingDeg:weather.windDirectionDeg,sourceIds:source.inputs.map((item)=>item.id)})];
      ensemble=combineForecastMembers({members});horizons=ensemble.horizons;
    }
    const forecast=createForecast({incidentId:source.incidentId,forecastType:'PERIMETER_PROGRESSION',state:abstention.state==='AVAILABLE'?'ISSUED':'ABSTAINED',qualityState:abstention.state==='AVAILABLE'?'RESEARCH_ONLY':'UNAVAILABLE',issuedAt,informationCutoff:source.informationCutoff,model:{id:modelEntry.modelId,version:modelEntry.version,ensembleId:ensemble?.ensembleId??null,fingerprint:modelEntry.fingerprint},inputManifestHash:inputManifest.semanticHash,weatherRun:source.weatherMembers[0]?.run??null,initialPerimeterRef:source.initialPerimeterMetadata.id,calibrationRef:null,horizons,abstention,qualityWarnings:['Forecast is SHADOW-only.','No calibrated forecast may replace observed fire evidence.'],limitations:['A single deterministic weather member is not an ensemble.',...contextPacks.errors.map((item)=>`${item.kind} context unavailable: ${item.reason}.`),'No forecast calibration corpus is available.']}),impact=forecastAssetExposure({forecast,assets:source.assets}),requestedActions=forecast.state==='ISSUED'?['PREFETCH_CONTEXT','PRIORITIZE_MONITORING']:['RECORD_ABSTENTION','REQUEST_MISSING_INPUTS'],policyInput=createForecastPolicyInput({forecast,impact,requestedActions}),receipt=createForecastReceipt({forecast,inputManifest,modelEntry}),reissued=createForecast(forecast),replay=verifyForecastReplay({forecast,inputManifest,modelEntry,receipt,reissuedForecast:reissued}),eventCore={schemaVersion:'vigia.forecast-event.v1',type:forecast.state==='ABSTAINED'?'FORECAST_ABSTAINED':'FORECAST_ISSUED',at:issuedAt,incidentId:source.incidentId,forecastId:forecast.forecastId,epistemicType:'FORECAST',evidenceEligible:false,authorityEligible:false},event={...eventCore,eventId:semanticHash('forecast-event',eventCore)},shadow={mode:'SHADOW',consequentialExecution:'DISABLED',wouldHaveNonConsequentialActions:policyInput.allowedActions,blockedActions:policyInput.blockedActions,externalActionsExecuted:0},consumerSnapshot=createForecastConsumerSnapshot({forecast,inputManifest,impact,shadow,replay,priorForecast:prior}),completedAt=this.clock().toISOString(),core={schemaVersion:'vigia.spread-shadow-run.v1',runId,startedAt,completedAt,state:replay.valid?'COMPLETED':'REPLAY_INVALID',sourceRealityRunId:source.sourceRunId,incident:{id:source.incidentId,providerIncidentId:source.providerIncidentId,name:source.incidentName,coordinate:source.coordinate},inputManifest,contextPacks:{fuel:contextPacks.fuel?{dataset:contextPacks.fuel.dataset,totalBytes:contextPacks.fuel.totalBytes}:null,terrain:contextPacks.terrain?{dataset:contextPacks.terrain.dataset,totalBytes:contextPacks.terrain.totalBytes}:null,errors:contextPacks.errors},assimilation,scoreUpdate,applicability:abstention,forecast,ensemble,impact,policyInput,shadow,replay,receipt,consumerSnapshot,physicalRunner},report={...core,runHash:semanticHash('spread-shadow-run',core)};
    await this.store.append({forecast,receipt,event,report});await writeJsonAtomic(this.config.forecastReportFile,report);return report;
  }
}
