import { createHash, createPrivateKey, createPublicKey, sign, verify } from 'node:crypto';
import { execFile } from 'node:child_process';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
import { calibrateInformationValue } from '../../../../../packages/domain/src/decision-foundry/index.mjs';
import { immutable, semanticHash, uniqueSorted } from '../../../../../packages/domain/src/intelligence/shared.mjs';
import { classifyReleasePath, isReleaseSourcePath } from '../../../../../packages/domain/src/release-path-policy.mjs';
import { authorizeCompartment, certifyDoctrineScenarioCoverage, certifyHaEvidence, createAccessContext, createForecastEvaluationProtocol, createResourceMarking, evaluateErrorBudgets, WORLDCLASS_SLOS } from '../../../../../packages/domain/src/worldclass/index.mjs';
import { readJson, writeJsonAtomic } from '../../shared/json-file.mjs';
import { loadMigrations } from '../storage/postgres-migration-runner.mjs';
import { PartnerCapGateway, readPartnerCapReplay } from './partner-cap-gateway.mjs';

const exec = promisify(execFile), sha256 = (value) => `sha256:${createHash('sha256').update(value).digest('hex')}`;
const validationDirectory = (root) => path.join(root, 'data/validation/worldclass');
const artifactPath = (root, name) => path.join(validationDirectory(root), name);
async function artifact(root, name, core) { const report = core.fingerprint ? core : { ...core, fingerprint: semanticHash(name.replace(/\.json$/, ''), core) }; await writeJsonAtomic(artifactPath(root, name), report); return report; }
async function fileHash(file) { return sha256(await readFile(file)); }
async function git(root, args) { return (await exec('git', args, { cwd: root, timeout: 30_000, maxBuffer: 16 * 1024 * 1024 })).stdout.trim(); }
async function currentCodeState(projectRoot) {
  const raw = (await exec('git', ['ls-files', '-co', '--exclude-standard', '-z'], { cwd: projectRoot, encoding: 'buffer', timeout: 30_000, maxBuffer: 64 * 1024 * 1024 })).stdout;
  const sourceFiles = raw.toString('utf8').split('\0').filter(Boolean).filter(isReleaseSourcePath);
  const files = [...new Set(sourceFiles)].sort(), entries = [];
  for (const file of files) try { entries.push({ path: file, classification: classifyReleasePath(file), sha256: await fileHash(path.join(projectRoot, file)) }); } catch {}
  return { codeStateHash: sha256(entries.map((item) => `${item.path}\0${item.sha256}`).join('\n')), entries };
}

export async function certifyCompartments({ projectRoot = process.cwd(), environment = process.env } = {}) {
  const at = '2026-01-01T00:00:00.000Z', marking = createResourceMarking({ organizationId: 'org-a', regionId: 'region-west', incidentId: 'incident-1', resourceId: 'decision-packet-1', classification: 'SENSITIVE', rights: { view: ['packet:read'], export: ['packet:export'], lineage: ['lineage:read'], execute: ['action:warn'] }, actionClasses: ['PROPOSE_WARNING'], propertyMarkings: { protectedLocation: { classification: 'RESTRICTED', view: ['location:read'], export: ['location:export'] } } });
  const context = (overrides = {}) => createAccessContext({ principalId: 'principal-a', deviceId: 'device-a', sessionId: 'session-a', organizations: ['org-a'], regions: ['region-west'], incidents: ['incident-1'], resources: ['decision-packet-1'], rights: ['packet:read', 'packet:export', 'lineage:read', 'action:warn'], actionClasses: ['PROPOSE_WARNING'], clearance: 'RESTRICTED', validFrom: '2025-01-01T00:00:00.000Z', validUntil: '2027-01-01T00:00:00.000Z', ...overrides });
  const cases = [
    ['authorized-read', context(), 'READ', null, null, true],
    ['cross-organization', context({ organizations: ['org-b'] }), 'READ', null, null, false],
    ['cross-incident', context({ incidents: ['incident-2'] }), 'READ', null, null, false],
    ['rights-bypass', context({ rights: [] }), 'EXPORT', null, null, false],
    ['property-clearance', context({ clearance: 'SENSITIVE' }), 'READ_PROPERTY', 'protectedLocation', null, false],
    ['privilege-laundering', context({ actionClasses: ['*'], rights: [] }), 'EXECUTE_ACTION', null, 'PROPOSE_WARNING', false],
    ['stale-authority', context({ validUntil: '2025-12-31T23:59:59.000Z' }), 'READ', null, null, false],
    ['revoked-authority', context({ revokedAt: '2025-12-01T00:00:00.000Z' }), 'READ', null, null, false],
    ['export-leakage', context({ rights: ['packet:read'] }), 'EXPORT', null, null, false],
    ['lineage-leakage', context({ rights: ['packet:read'] }), 'EXPLORE_LINEAGE', null, null, false],
  ].map(([id, access, operation, property, actionClass, expected]) => { const decision = authorizeCompartment({ context: access, marking, operation, property, actionClass, at }); return { id, expected, actual: decision.allowed, passed: decision.allowed === expected, reasons: decision.reasons }; });
  const rls = { state: 'BLOCKED_PENDING_AGENT1_MIGRATION_018', proposedMigration: 'docs/architecture/migration-019-security-compartments.sql.proposed', reason: 'Migration 019 cannot become the active DAG head until Agent 1 migration 018 is integrated and checksummed.' }, kms = { abstraction: 'READY', adapterContract: 'packages/domain/src/worldclass/key-management.mjs', externalProvider: environment.VIGIA_KMS_PROVIDER ? 'CONFIGURED_REQUIRES_LIVE_VALIDATION' : 'NOT_CONFIGURED', keyMaterialRecorded: false }, externalAssurance = { state: 'NOT_EXECUTED', requirement: 'Independent security assessor must run cross-tenant, RLS-bypass, privilege-laundering, stale-authority, and export-leakage tests against the deployed canonical stack.' };
  const passed = cases.every((item) => item.passed) && rls.state === 'PASS' && kms.externalProvider === 'LIVE_VALIDATED' && externalAssurance.state === 'PASS';
  return artifact(projectRoot, 'security-compartments.json', { schemaVersion: 'vigia.security-compartment-certification.v1', abac: { passed: cases.every((item) => item.passed), dimensions: ['organization', 'region', 'incident', 'resource', 'classification', 'rights', 'actionClass', 'principal', 'device', 'session'], cases }, enforcement: { api: 'READY', queryService: 'READY', ontologyObjects: 'READY', propertyAccess: 'READY', actions: 'READY', exports: 'READY', lineage: 'READY', postgresRls: rls }, kms, supplyChain: { sbom: 'READY_IN_CLEAN_ROOM_MANIFEST', containerSigning: 'BLOCKED_IMAGE_DIGESTS_AND_EXTERNAL_SIGNER', containerScanning: 'NOT_EXECUTED_AGAINST_RELEASE_IMAGES', secretScanning: 'REQUIRES_INDEPENDENT_RELEASE_SCAN', externalAuditAnchoring: 'NOT_CONFIGURED' }, externalAssurance, unresolvedHigh: null, unresolvedMediumCanonical: null, vulnerabilityQualification: 'No independent deployed-stack assessment has run; zero unresolved findings is not claimed.', passed, state: passed ? 'PASS' : 'BLOCKED' });
}

export async function doctrineCoverage({ projectRoot = process.cwd() } = {}) { return artifact(projectRoot, 'doctrine-coverage.json', certifyDoctrineScenarioCoverage()); }

function corpusCriteria(gold) {
  const counts = gold.readiness?.counts ?? {}, horizons = counts.horizonCounts ?? {}, splits = counts.splitCounts ?? gold.splits?.counts ?? {}, eligibleIncidents = Number(counts.eligibleIncidents ?? new Set((gold.examples ?? []).map((item) => item.incidentId)).size), regions = Number(counts.regions ?? new Set((gold.examples ?? []).map((item) => item.region)).size), seasons = Number(counts.seasons ?? new Set((gold.examples ?? []).map((item) => item.season)).size);
  return { regions: { actual: regions, required: 2, passed: regions >= 2 }, seasons: { actual: seasons, required: 2, passed: seasons >= 2 }, eligibleIncidents: { actual: eligibleIncidents, required: 100, passed: eligibleIncidents >= 100 }, validNegatives: { actual: Number(counts.validNegatives ?? 0), required: 100, passed: Number(counts.validNegatives ?? 0) >= 100 }, hardNegatives: { actual: Number(counts.hardNegatives ?? 0), required: 25, passed: Number(counts.hardNegatives ?? 0) >= 25 }, developmentSplit: { actual: Number(splits.development ?? 0), required: 1, passed: Number(splits.development ?? 0) > 0 }, calibrationSplit: { actual: Number(splits.calibration ?? 0), required: 1, passed: Number(splits.calibration ?? 0) > 0 }, heldoutSplit: { actual: Number(splits['held-out-test'] ?? splits.heldout ?? 0), required: 1, passed: Number(splits['held-out-test'] ?? splits.heldout ?? 0) > 0 }, nearTermExamples: { actual: Number(horizons['1'] ?? horizons['1h'] ?? 0) + Number(horizons['3'] ?? horizons['3h'] ?? 0), required: 1, passed: Number(horizons['1'] ?? horizons['1h'] ?? 0) + Number(horizons['3'] ?? horizons['3h'] ?? 0) > 0 }, scoreableHorizons: { actual: Object.values(horizons).filter((value) => Number(value) > 0).length, required: 3, passed: Object.values(horizons).filter((value) => Number(value) > 0).length >= 3 }, knowledgeTimeAudit: { actual: Number(gold.leakage?.rowsInspected ?? gold.leakage?.cases ?? gold.leakage?.checked ?? 0), required: 1, passed: Number(gold.leakage?.rowsInspected ?? gold.leakage?.cases ?? gold.leakage?.checked ?? 0) > 0 && gold.leakage?.passed === true }, sourceAblations: { actual: gold.baselines?.sourceAblations?.length ?? 0, required: 1, passed: (gold.baselines?.sourceAblations?.length ?? 0) > 0 }, deterministicReplay: { actual: gold.replayVerification?.identical === true, required: true, passed: gold.replayVerification?.identical === true } };
}
export async function corpusWorldclassGate({ projectRoot = process.cwd() } = {}) {
  const gold = await readJson(path.join(projectRoot, 'data/runtime/forecast-corpus/gold/forecast-corpus.json'), {}), criteria = corpusCriteria(gold), failures = Object.entries(criteria).filter(([, value]) => !value.passed).map(([name]) => name), core = { schemaVersion: 'vigia.corpus-worldclass-gate.v1', sourceFingerprint: gold.replay?.corpusFingerprint ?? gold.fingerprint ?? null, criteria, failures, passed: failures.length === 0, state: failures.length ? 'CORPUS_NOT_READY' : 'PASS', modelTrainingAuthorized: failures.length === 0 };
  return artifact(projectRoot, 'corpus-worldclass-gate.json', core);
}

export async function forecastEvaluation({ projectRoot = process.cwd() } = {}) {
  const protocol = createForecastEvaluationProtocol(), corpus = await corpusWorldclassGate({ projectRoot }), passed = corpus.passed === true;
  return artifact(projectRoot, 'forecast-evaluation.json', { schemaVersion: 'vigia.forecast-worldclass-evaluation.v1', protocol, corpusGateFingerprint: corpus.fingerprint, state: passed ? 'READY_FOR_EVALUATION_ROWS' : 'BLOCKED_BY_CORPUS', trainingExecuted: false, promotionExecuted: false, evaluatedModels: [], measuredMetrics: Object.fromEntries(protocol.metrics.map((item) => [item, null])), blocker: passed ? 'Scoreable preregistered evaluation rows have not been supplied.' : 'Scientific corpus promotion gates are not satisfied; model training and promotion remain forbidden.', passed: false });
}

async function repositoryState(projectRoot) { return readJson(path.join(projectRoot, 'data/runtime/decision-foundry/semantic-repository.json'), { objects: [] }); }
export async function adjudicateOutcomes({ projectRoot = process.cwd() } = {}) {
  const state = await repositoryState(projectRoot), shadow = await readJson(path.join(projectRoot, 'data/validation/evidence-war-room/historical-shadow-decision-memory.json'), null), repositoryOutcomes = state.objects.filter((item) => item.kind === 'INFORMATION_VALUE_OUTCOME').map((item) => item.payload), outcomes = [...repositoryOutcomes, ...(shadow?.informationValueOutcomes ?? [])], repositoryDecisions = state.objects.filter((item) => item.kind === 'DECISION_OUTCOME').length, decisionOutcomes = repositoryDecisions + Number(shadow?.adjudicableDecisionOutcomes ?? 0), calibration = calibrateInformationValue(outcomes), passed = outcomes.length >= 25 && decisionOutcomes >= 25;
  return artifact(projectRoot, 'outcome-adjudication.json', { schemaVersion: 'vigia.outcome-adjudication-gate.v1', informationValueOutcomes: outcomes.length, decisionOutcomes, sources: { semanticRepository: repositoryOutcomes.length, historicalShadowExternalReality: shadow?.informationValueOutcomes?.length ?? 0, historicalShadowFingerprint: shadow?.fingerprint ?? null }, calibration, automaticDoctrineMutation: false, reviewerApprovalRequired: true, minimumOutcomePairs: 25, state: passed ? 'PASS' : 'INSUFFICIENT_REALIZED_OUTCOMES', passed });
}

export async function regionalShadowArchive({ projectRoot = process.cwd(), evidenceFile = null } = {}) {
  const state = await repositoryState(projectRoot), snapshots = state.objects.filter((item) => item.kind === 'PROSPECTIVE_ARCHIVE_SNAPSHOT'), publicCampaign = await readJson(path.join(projectRoot, 'data/validation/evidence-war-room/prospective-campaign.json'), null), evidence = evidenceFile ? await readJson(path.resolve(projectRoot, evidenceFile), null) : null, effective = evidence ?? (publicCampaign ? { durationHours: (Date.parse(publicCampaign.lastCapturedAt) - Date.parse(publicCampaign.startedAt)) / 3_600_000, incidents: publicCampaign.incidents, providerSourceClasses: publicCampaign.providerSourceClasses, immutableSnapshots: publicCampaign.immutableSnapshots, restartRecovery: false, backupRestore: false, rightsEnforcement: (publicCampaign.snapshots ?? []).every((item) => item.rights?.state === 'READY'), replayVerified: false, priorSnapshotsRewritten: publicCampaign.priorSnapshotsRewritten } : null), checks = effective ? { duration: Number(effective.durationHours) >= 168, incidents: Number(effective.incidents) >= 25, providers: Number(effective.providerSourceClasses) >= 3, snapshots: Number(effective.immutableSnapshots) >= 1_000, restartRecovery: effective.restartRecovery === true, backupRestore: effective.backupRestore === true, rights: effective.rightsEnforcement === true, replay: effective.replayVerified === true, appendOnly: effective.priorSnapshotsRewritten === 0 } : {}, passed = effective && Object.values(checks).every(Boolean);
  return artifact(projectRoot, 'regional-shadow-archive.json', { schemaVersion: 'vigia.regional-shadow-campaign.v1', supportedModes: ['ONCE', 'BOUNDED_DURATION', 'INCIDENT_WATCH', 'REGIONAL_SHADOW'], boundedCampaign: { durationDays: 7, incidents: 25, providerSourceClasses: 3, immutableSnapshots: 1_000, cadenceSeconds: 300, maximumConcurrentRequests: 3, maximumBytesPerResponse: 5 * 1024 * 1024, backgroundProcess: false }, preservedFields: ['raw provider object', 'provider publication time', 'VIGIA receipt time', 'source health', 'perimeter revision', 'physical observations', 'weather run', 'Evidence State', 'Evidence Debt', 'hypotheses', 'Decision Packet', 'shadow actions', 'later outcomes', 'rights', 'lineage'], currentEvidence: { snapshots: snapshots.length + Number(publicCampaign?.immutableSnapshots ?? 0), incidents: Math.max(new Set(snapshots.map((item) => item.incidentId)).size, Number(publicCampaign?.incidents ?? 0)), providerSourceClasses: publicCampaign?.providerSourceClasses ?? 0, campaignFingerprint: publicCampaign?.fingerprint ?? null, rawBytes: snapshots.reduce((sum, item) => sum + Number(item.payload?.rawBytes ?? 0), 0) }, importedEvidence: effective ? { checks, fingerprint: sha256(JSON.stringify(effective)) } : null, state: passed ? 'PASS' : 'TIME_ACCUMULATION_REQUIRED', passed: Boolean(passed), remainingBlockerClass: passed ? null : 'TIME_ACCUMULATION_REQUIRED', runningCommand: 'npm run evidence:prospective:capture' });
}

export async function haCertification({ projectRoot = process.cwd(), evidenceFile = null } = {}) {
  let result = null, error = null; const local = await readJson(path.join(projectRoot, 'data/validation/evidence-war-room/local-ha-certification.json'), null);
  if (evidenceFile) try { result = certifyHaEvidence(await readJson(path.resolve(projectRoot, evidenceFile), {})); } catch (cause) { error = String(cause.message ?? cause); }
  return artifact(projectRoot, 'ha-certification.json', { schemaVersion: 'vigia.ha-certification-envelope.v1', requiredTopology: { regionalPrimary: true, synchronousCrossZoneStandby: true, asynchronousCrossRegionRecovery: true, independentlyDeployableStacks: 3, trafficRouting: true, splitBrainFencing: true }, targets: { zoneRtoSecondsExclusiveMaximum: 60, zoneRpoAcknowledgedTransactions: 0, regionRtoSecondsExclusiveMaximum: 300, regionRpo: 'EXPLICITLY_MEASURED', automatedCycles: 100, splitBrainWrites: 0, duplicateActions: 0 }, result, error, localEngineeringEvidence: local ? { passed: local.passed, fingerprint: local.fingerprint, evidenceClass: local.evidenceClass, cycles: local.summary?.cycles, splitBrainWrites: local.summary?.splitBrainWrites, acknowledgedActionsLost: local.summary?.acknowledgedActionsLost } : null, actualCloudEvidence: Boolean(result?.passed), singleNodeDockerAccepted: false, state: result?.passed ? 'PASS' : local?.passed ? 'LOCAL_ENGINEERING_PASS_CREDENTIAL_REQUIRED_FOR_REAL_CLOUD' : 'CREDENTIAL_REQUIRED', remainingBlockerClass: result?.passed ? null : 'CREDENTIAL_REQUIRED', passed: result?.passed === true });
}

export async function prepareOperatorEvaluation({ projectRoot = process.cwd(), resultsFile = null } = {}) {
  const tasks = ['identify top incident', 'explain assessment', 'distinguish physical/report evidence', 'identify contradiction', 'identify decision blocker', 'explain source selection', 'complete handoff', 'recover from degraded state', 'review authority boundary', 'perform replay'].map((name, index) => ({ id: `TASK-${String(index + 1).padStart(2, '0')}`, name, critical: true, completeTraceRequired: true, environmentOutcomeRequired: true })), results = resultsFile ? await readJson(path.resolve(projectRoot, resultsFile), null) : null, sessions = results?.sessions ?? [], practitioners = new Set(sessions.filter((item) => item.emergencyPractitioner === true).map((item) => item.participantId)), perspectives = new Set(sessions.map((item) => item.operationalPerspective).filter(Boolean)), trials = sessions.flatMap((item) => item.trials ?? []), critical = trials.filter((item) => item.critical === true), median = (values) => { const ordered = values.filter(Number.isFinite).sort((a, b) => a - b), middle = Math.floor(ordered.length / 2); return ordered.length ? ordered.length % 2 ? ordered[middle] : (ordered[middle - 1] + ordered[middle]) / 2 : null; }, duration = (taskId) => median(trials.filter((item) => item.taskId === taskId).map((item) => Number(item.durationSeconds))), traceComplete = trials.every((item) => item.traceComplete === true && item.environmentOutcomeRecorded === true), metrics = { sessions: sessions.length, emergencyPractitioners: practitioners.size, operationalPerspectives: perspectives.size, criticalTaskCompletion: critical.length ? critical.filter((item) => item.completed === true).length / critical.length : null, dangerousMisinterpretations: trials.filter((item) => item.dangerousMisinterpretation === true).length, medianTopIncidentSeconds: duration('TASK-01'), medianWhySeconds: duration('TASK-02'), medianHandoffSeconds: duration('TASK-07'), clarityTrust: sessions.length ? sessions.reduce((sum, item) => sum + Number(item.clarityTrustScore ?? 0), 0) / sessions.length : null, traceComplete }, passed = metrics.sessions >= 10 && metrics.emergencyPractitioners >= 5 && metrics.operationalPerspectives >= 3 && metrics.criticalTaskCompletion >= .9 && metrics.dangerousMisinterpretations === 0 && metrics.medianTopIncidentSeconds < 45 && metrics.medianWhySeconds < 75 && metrics.medianHandoffSeconds < 240 && metrics.clarityTrust >= 4 && metrics.traceComplete && sessions.every((item) => item.consentRecorded === true && item.deidentified === true);
  return artifact(projectRoot, 'operator-evaluation-package.json', { schemaVersion: 'vigia.external-operator-evaluation.v1', tasks, design: { requiredSessions: 10, requiredEmergencyPractitioners: 5, requiredOperationalPerspectives: 3, graders: ['task-completion grader', 'dangerous-misinterpretation safety grader', 'trace completeness grader', 'environment outcome grader'], consent: { required: true, withdrawalSupported: true }, deidentification: { required: true, directIdentifiersProhibited: true }, exportSchema: 'vigia.operator-evaluation-results.v1' }, successCriteria: { criticalTaskCompletionMinimum: .9, dangerousMisinterpretationsMaximum: 0, medianTopIncidentSecondsExclusiveMaximum: 45, medianWhySecondsExclusiveMaximum: 75, medianHandoffSecondsExclusiveMaximum: 240, clarityTrustMinimum: 4 }, metrics, simulatedParticipants: false, state: passed ? 'PASS' : 'BLOCKED_REAL_PRACTITIONER_SESSIONS_REQUIRED', passed });
}

export async function partnerGatewayDoctor({ projectRoot = process.cwd(), environment = process.env, fetchImpl = globalThis.fetch } = {}) {
  const endpoint = environment.VIGIA_CAP_PARTNER_URL, token = environment.VIGIA_CAP_PARTNER_TOKEN ?? '', allowedHosts = String(environment.VIGIA_CAP_PARTNER_ALLOWED_HOSTS ?? '').split(',').map((item) => item.trim()).filter(Boolean);
  if (!endpoint) { const publicCap = await readJson(path.join(projectRoot, 'data/validation/evidence-war-room/government-cap-integration.json'), null); if (publicCap?.passed) return artifact(projectRoot, 'partner-gateway-doctor.json', { schemaVersion: 'vigia.partner-gateway-doctor.v1', integration: 'OFFICIAL_PUBLIC_GOVERNMENT_CAP', state: 'PASS', providers: ['NOAA/NWS', 'ECCC/MSC'], authentication: 'PUBLIC', rawMessages: publicCap.totals.rawMessages, lifecycleChains: publicCap.totals.lifecycleChains, cancellations: publicCap.totals.cancellations, twinIncidents: publicCap.twin.incidents, replayVerified: publicCap.replay.verified, ingestionFingerprint: publicCap.fingerprint, secretsRecorded: false, passed: true }); return artifact(projectRoot, 'partner-gateway-doctor.json', { schemaVersion: 'vigia.partner-gateway-doctor.v1', integration: 'OFFICIAL_CAP_FEED', state: 'PRIVILEGED_PARTNER_REQUIRED', endpointConfigured: false, authentication: 'NOT_CONFIGURED', secretsRecorded: false, preparedAdapter: 'apps/api/src/modules/worldclass/partner-cap-gateway.mjs', remainingBlockerClass: 'PRIVILEGED_PARTNER_REQUIRED', passed: false }); }
  try { const report = await new PartnerCapGateway({ endpoint, token, allowedHosts, projectRoot, fetchImpl }).poll(); return artifact(projectRoot, 'partner-gateway-doctor.json', { schemaVersion: 'vigia.partner-gateway-doctor.v1', integration: 'OFFICIAL_CAP_FEED', state: report.committedEvents > 0 ? 'PASS' : 'BLOCKED_EMPTY_FEED', endpointOrigin: new URL(endpoint).origin, authentication: token ? 'PRESENT_REDACTED' : 'PUBLIC', ingestionFingerprint: report.fingerprint, secretsRecorded: false, passed: report.committedEvents > 0 }); }
  catch (error) { return artifact(projectRoot, 'partner-gateway-doctor.json', { schemaVersion: 'vigia.partner-gateway-doctor.v1', integration: 'OFFICIAL_CAP_FEED', state: 'BLOCKED_ENDPOINT_VALIDATION_FAILED', endpointOrigin: (() => { try { return new URL(endpoint).origin; } catch { return null; } })(), authentication: token ? 'PRESENT_REDACTED' : 'PUBLIC', error: String(error.message ?? error), secretsRecorded: false, passed: false }); }
}

async function releaseControl({ projectRoot, environment, action, releaseId, fetchImpl = globalThis.fetch }) {
  const endpoint = environment.VIGIA_RELEASE_CONTROL_URL, token = environment.VIGIA_RELEASE_CONTROL_TOKEN;
  const plan = { schemaVersion: `vigia.release-${action}.v1`, action, releaseId: releaseId ?? null, canary: { trafficPercent: 5, observationMinutes: 15, minimumRequests: 100, promotionRequires: ['all error budgets within budget', 'zero new HIGH/MEDIUM security findings', 'zero schema/replay drift', 'health checks pass'], automaticRollbackOn: ['error budget exhausted', 'health failure', 'schema drift', 'replay fingerprint mismatch'] }, uncontrolledBackgroundProcesses: false };
  if (!endpoint || !token || !releaseId) return artifact(projectRoot, `release-${action}.json`, { ...plan, state: 'BLOCKED_RELEASE_CONTROL_CONFIGURATION_REQUIRED', endpointConfigured: Boolean(endpoint), credential: token ? 'PRESENT_REDACTED' : 'ABSENT', passed: false });
  try { const url = new URL(`./${action}`, endpoint.endsWith('/') ? endpoint : `${endpoint}/`); if (url.protocol !== 'https:') throw new Error('release_control_https_required'); const response = await fetchImpl(url, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', 'Idempotency-Key': sha256(`${action}:${releaseId}`) }, body: JSON.stringify(plan), signal: AbortSignal.timeout(30_000) }), body = await response.json(); if (!response.ok) throw new Error(`release_control_http_${response.status}`); const passed = ['PASS', 'PROMOTED', 'ROLLED_BACK'].includes(body.state); return artifact(projectRoot, `release-${action}.json`, { ...plan, state: body.state, controlReceiptId: body.receiptId ?? null, endpointOrigin: url.origin, credential: 'PRESENT_REDACTED', passed }); }
  catch (error) { return artifact(projectRoot, `release-${action}.json`, { ...plan, state: 'BLOCKED_RELEASE_CONTROL_FAILED', error: String(error.message ?? error), credential: 'PRESENT_REDACTED', passed: false }); }
}
export const releaseCanary = (options = {}) => releaseControl({ ...options, action: 'canary' });
export const releaseRollback = (options = {}) => releaseControl({ ...options, action: 'rollback' });

async function buildSbom(projectRoot) { const packageValue = await readJson(path.join(projectRoot, 'package.json'), {}), lock = await readJson(path.join(projectRoot, 'package-lock.json'), {}), dependencies = Object.entries(packageValue.dependencies ?? {}).sort(([a], [b]) => a.localeCompare(b)).map(([name, version]) => ({ type: 'library', name, version: lock.packages?.[`node_modules/${name}`]?.version ?? version.replace(/^[^0-9]*/, ''), purl: `pkg:npm/${encodeURIComponent(name)}@${lock.packages?.[`node_modules/${name}`]?.version ?? version.replace(/^[^0-9]*/, '')}` })), core = { bomFormat: 'CycloneDX', specVersion: '1.5', version: 1, metadata: { component: { type: 'application', name: packageValue.name, version: packageValue.version } }, components: dependencies }; return { ...core, serialNumber: `urn:uuid:${sha256(JSON.stringify(core)).slice(7, 39)}` }; }
async function inventoryFiles(directory, root) { const result = []; for (const name of (await readdir(directory, { withFileTypes: true }).catch(() => [])).sort((a, b) => a.name.localeCompare(b.name))) { const file = path.join(directory, name.name); if (name.isDirectory()) result.push(...await inventoryFiles(file, root)); else result.push({ path: path.relative(root, file), sha256: await fileHash(file) }); } return result; }

export async function cleanRoomCertification({ projectRoot = process.cwd(), reviewerAttestationFile = null } = {}) {
  const [commit, branch, codeState, migrations, sbom, replayHistories] = await Promise.all([git(projectRoot, ['rev-parse', 'HEAD']), git(projectRoot, ['branch', '--show-current']), currentCodeState(projectRoot), loadMigrations(), buildSbom(projectRoot), inventoryFiles(path.join(projectRoot, 'data/runtime/decision-foundry/replays'), projectRoot)]), releaseId = `vigia-decision-os-${codeState.codeStateHash.slice(7, 23)}`, imageDigests = (() => { try { return JSON.parse(process.env.VIGIA_RELEASE_IMAGE_DIGESTS ?? '[]'); } catch { return []; } })();
  const core = { schemaVersion: 'vigia.clean-room-manifest.v1', releaseIdentity: { releaseId, commit, branch, codeStateHash: codeState.codeStateHash, sourceEntries: codeState.entries.length }, dockerImageDigests: imageDigests, sbom, migrations: migrations.map((item) => ({ version: item.version, name: item.name, checksum: item.checksum })), testManifest: { commands: ['npm run test:intelligence', 'npm run test:event-fabric', 'npm run test:control-plane', 'npm run test:proof-plane', 'npm run test:reality-network', 'npm run test:forecasting', 'npm run test:forecast-corpus', 'npm run test:data-foundry', 'npm run test:decision-foundry', 'npm run test:backend-convergence', 'npm run test:worldclass'] }, propertyTestSeeds: ['vigia-worldclass-0001', 'vigia-worldclass-0042', 'vigia-worldclass-0100'], databaseFixtures: ['scripts/certify_intelligence_postgis.mjs'], replayHistories, expectedFingerprints: { doctrine: certifyDoctrineScenarioCoverage().fingerprint, partner: (await readPartnerCapReplay(projectRoot))?.replayFingerprint ?? null }, benchmarks: ['npm run benchmark:backend-convergence', 'npm run corpus:benchmark', 'npm run benchmark:data-foundry'], threatModel: { assets: ['evidence chain', 'decision authority', 'tenant data', 'release identity'], threats: ['cross-tenant access', 'rights bypass', 'stale authority', 'split brain', 'supply-chain substitution', 'replay drift'], trustBoundaries: ['public provider', 'partner endpoint', 'API', 'query service', 'Postgres', 'release controller', 'KMS/HSM'] }, rubric: { critical: ['all focused tests pass', 'PostGIS head and checksums reproduce', 'replays match', 'compartment adversarial suite passes', 'no unresolved canonical HIGH/MEDIUM', 'reviewer is independent'], passRule: 'Every critical condition must pass; one failure blocks certification.' } };
  const manifest = { ...core, fingerprint: semanticHash('clean-room-manifest', core) }, privateKeyFile = path.join(projectRoot, 'data/runtime/decision-foundry/proof-keys/private.pem'); let signature = null;
  try { const privateKey = createPrivateKey(await readFile(privateKeyFile)), publicKey = createPublicKey(privateKey).export({ type: 'spki', format: 'pem' }).toString(), bytes = Buffer.from(JSON.stringify(manifest)); signature = { schemaVersion: 'vigia.release-signature.v1', algorithm: 'Ed25519', keyId: sha256(publicKey).slice(0, 32), publicKey, signature: sign(null, bytes, privateKey).toString('base64url'), verified: verify(null, bytes, publicKey, sign(null, bytes, privateKey)), qualification: 'Implementation-key integrity signature; not independent reviewer attestation.' }; } catch (error) { signature = { state: 'BLOCKED_SIGNING_KEY_UNAVAILABLE', error: String(error.message ?? error) }; }
  await artifact(projectRoot, 'clean-room-manifest.json', manifest); await artifact(projectRoot, 'release-signature.json', signature);
  const attestation = reviewerAttestationFile ? await readJson(path.resolve(projectRoot, reviewerAttestationFile), null) : null, attestationValid = attestation?.releaseId === releaseId && attestation?.manifestFingerprint === manifest.fingerprint && attestation?.reviewerIndependent === true && attestation?.criticalChecksPassed === true && attestation?.reviewerId && attestation.reviewerId !== 'implementation-agent', blockers = [];
  if (!imageDigests.length) blockers.push('DOCKER_IMAGE_DIGESTS_MISSING'); if (signature?.verified !== true) blockers.push('RELEASE_SIGNATURE_MISSING'); if (!attestationValid) blockers.push('INDEPENDENT_REVIEWER_ATTESTATION_MISSING_OR_INVALID');
  return artifact(projectRoot, 'clean-room-certification.json', { schemaVersion: 'vigia.clean-room-certification.v1', releaseId, manifestFingerprint: manifest.fingerprint, signatureVerified: signature?.verified === true, independentAttestation: attestationValid ? { reviewerId: attestation.reviewerId, executedAt: attestation.executedAt, evidenceFingerprint: sha256(JSON.stringify(attestation)) } : null, blockers, state: blockers.length ? 'BLOCKED' : 'PASS', passed: blockers.length === 0 });
}

export async function worldclassDoctor({ projectRoot = process.cwd() } = {}) {
  const [corpus, outcomes, doctrine, security, operator, partner, ha, cleanRoom] = await Promise.all([corpusWorldclassGate({ projectRoot }), adjudicateOutcomes({ projectRoot }), doctrineCoverage({ projectRoot }), certifyCompartments({ projectRoot }), prepareOperatorEvaluation({ projectRoot }), partnerGatewayDoctor({ projectRoot }), haCertification({ projectRoot }), cleanRoomCertification({ projectRoot })]), foundry = await readJson(path.join(projectRoot, 'data/validation/data-foundry/benchmarks/data-foundry-benchmark.json'), {}), errorBudgets = evaluateErrorBudgets({});
  const checks = { corpus: corpus.passed, outcomes: outcomes.passed, doctrine: doctrine.passed, security: security.passed, operator: operator.passed, partner: partner.passed, ha: ha.passed, cleanRoom: cleanRoom.passed, foundryMemory: Number(foundry.peakMemoryBytes) < 512 * 1024 * 1024, foundryIncremental: Number(foundry.workloads?.incrementalMaterialization?.elapsedMs) < 100 };
  return artifact(projectRoot, 'worldclass-doctor.json', { schemaVersion: 'vigia.worldclass-doctor.v1', checks, slos: WORLDCLASS_SLOS, errorBudgets, state: Object.values(checks).every(Boolean) ? 'PASS' : 'BLOCKED', passed: Object.values(checks).every(Boolean) });
}

const SCORECARD = Object.freeze([
  ['scientific corpus', 3.5, 7.0, 3.5, '100 eligible incidents, 100 negatives, 25 hard negatives, valid splits and horizons', 'Current legitimate corpus remains below the preregistered gate.'],
  ['predictive validity', 2.0, 8.0, 2.0, 'Preregistered ladder passes held-out calibration and tail-risk limits', 'Training and evaluation are correctly blocked by corpus readiness.'],
  ['decision learning', 0.0, 8.0, 0.0, 'At least 25 real paired acquisition and decision outcomes', 'No realized outcomes have been adjudicated.'],
  ['prospective history', 1.0, 8.0, 1.0, 'Seven days, 25 incidents, 3 source classes, 1,000 immutable snapshots', 'The real regional shadow campaign has not run.'],
  ['multi-region resilience', 0.0, 7.5, 0.0, '100 measured failover cycles on three real failure domains', 'No multi-region deployment evidence exists.'],
  ['security compartmentation', 1.5, 7.0, 1.5, 'Merged Postgres RLS, live KMS/HSM, and independent adversarial assessment', 'Migration 018 must merge before proposed 019; no independent security assessment.'],
  ['release cleanliness', 5.0, 7.0, 5.0, 'One migration DAG, zero unexplained failures, signed images, canary and rollback receipts', 'Agent 1 migration 018 and frontend-owned inherited failure remain external to this branch; no deployment controller.'],
  ['doctrine coverage', 2.0, 9.0, 6.5, '100-state suite plus operational review of high-consequence doctrine', 'Engineering coverage passes; practitioner/agency operational review is absent.'],
  ['Data Foundry efficiency', 4.5, 9.0, 6.5, '<512 MiB representative build plus sustained historical workload', 'Measured retained workload passes; larger sustained production history is not yet available.'],
  ['operator validation', 0.0, 8.0, 0.0, '10 real sessions, 5 practitioners, 3 perspectives, all outcome thresholds', 'No real practitioner sessions have run.'],
  ['agency integration', 2.0, 8.0, 2.0, 'Configured real CAP authority endpoint passes ingestion, lifecycle, outage, replay, and visible-effect tests', 'No real allowlisted CAP endpoint or credential is configured.'],
  ['independent assurance', 0.0, 8.0, 0.0, 'Independent clean-room run reproduces critical results for signed image digests', 'No independent reviewer attestation or image digests exist.'],
]);
export async function sub75Report({ projectRoot = process.cwd() } = {}) {
  const [canada, negatives, labels, shadow, cap, campaign, localHa, localHsm, operator, cleanRoom] = await Promise.all(['canadian-evidence-catalogue.json', 'negative-opportunities.json', 'near-term-labels.json', 'historical-shadow-decision-memory.json', 'government-cap-integration.json', 'prospective-campaign.json', 'local-ha-certification.json', 'local-softhsm-certification.json', '../worldclass/operator-evaluation-package.json', '../worldclass/clean-room-certification.json'].map((name) => readJson(path.join(projectRoot, 'data/validation/evidence-war-room', name), null))), row = (category, baseline, engineeringReadiness, realWorldEvidence, exitGateEvidence, remainingBlockerClass, remainingBlocker, evidenceFingerprint = null) => ({ category, baseline, engineeringReadiness, realWorldEvidence, finalDefensibleScore: Math.min(engineeringReadiness, realWorldEvidence), exitGateEvidence, remainingBlockerClass, remainingBlocker, evidenceFingerprint }), categories = [
    row('scientific corpus', 3.5, 7.0, canada?.incidents?.discovered >= 500 ? 4.5 : 3.5, '100 forecast-eligible incidents, 100 valid negatives, 25 hard negatives, valid near-term horizons', negatives?.validNegatives ? 'TIME_ACCUMULATION_REQUIRED' : 'CREDENTIAL_REQUIRED', `${canada?.incidents?.discovered ?? 0} incidents discovered; ${canada?.incidents?.forecastEligible ?? 0} eligible, ${negatives?.validNegatives ?? 0} valid negatives, ${labels?.labelCandidates?.length ?? 0} near-term labels.`, canada?.fingerprint),
    row('predictive validity', 2.0, 8.0, labels?.labelCandidates?.length ? 3.0 : 2.0, 'Preregistered ladder on held-out scoreable rows', 'TIME_ACCUMULATION_REQUIRED', 'Training/evaluation remains blocked because legitimate 1h/3h labels are not yet accumulated.', labels?.fingerprint),
    row('decision learning', 0.0, 8.0, shadow?.informationValueOutcomes?.length >= 25 ? 7.5 : 0.0, 'At least 25 real paired acquisition and decision outcomes', shadow?.passed ? null : 'PUBLIC_EVIDENCE_EXHAUSTED', `${shadow?.episodes?.length ?? 0} historical shadow episodes and ${shadow?.informationValueOutcomes?.length ?? 0} realized information-value outcomes.`, shadow?.fingerprint),
    row('prospective history', 1.0, 8.0, campaign?.immutableSnapshots >= 100 && campaign?.providerSourceClasses >= 3 ? 4.5 : 2.0, 'Seven days, 25 incidents, 3 source classes, 1,000 immutable snapshots', 'TIME_ACCUMULATION_REQUIRED', `${campaign?.immutableSnapshots ?? 0} snapshots across ${campaign?.incidents ?? 0} incidents and ${campaign?.providerSourceClasses ?? 0} source classes; seven days/1,000 not yet reached.`, campaign?.fingerprint),
    row('multi-region resilience', 0.0, localHa?.passed ? 7.5 : 4.0, localHa?.passed ? 2.5 : 0.0, '100 failovers on an authorized real multi-region cloud deployment', 'CREDENTIAL_REQUIRED', localHa?.passed ? '100 local three-failure-domain cycles pass; no repository-scoped cloud credential was discovered.' : 'Local engineering certification incomplete.', localHa?.fingerprint),
    row('security compartmentation', 1.5, localHsm?.passed ? 7.0 : 5.0, localHsm?.passed ? 4.5 : 1.5, 'Merged RLS migration, live cloud KMS/HSM, independent adversarial assessment', 'CROSS_BRANCH_INTEGRATION_REQUIRED', localHsm?.passed ? 'SoftHSM lifecycle passes; migration 018/019 integration, live cloud KMS, and independent assessment remain.' : 'Local HSM lifecycle incomplete.', localHsm?.fingerprint),
    row('release cleanliness', 5.0, 7.0, 5.0, 'One merged migration DAG, signed image digests, canary/rollback receipts', 'CROSS_BRANCH_INTEGRATION_REQUIRED', 'Migration 018 and the protected frontend release must be integrated without changing this branch; image digests/deployment receipts are absent.', cleanRoom?.fingerprint),
    row('doctrine coverage', 2.0, 9.0, 6.5, '100-state engineering suite plus practitioner/agency operational review', 'REAL_HUMAN_REQUIRED', 'Engineering doctrine coverage passes; high-consequence operational review requires real practitioners.'),
    row('Data Foundry efficiency', 4.5, 9.0, 6.5, '<512 MiB representative build plus sustained production history', 'TIME_ACCUMULATION_REQUIRED', 'Measured retained workload passes; sustained production-scale history must accumulate.'),
    row('operator validation', 0.0, 8.0, operator?.passed ? 8.0 : 0.0, '10 real sessions, 5 practitioners, 3 perspectives, all thresholds', 'REAL_HUMAN_REQUIRED', `Study kit and runner ready; ${operator?.metrics?.sessions ?? 0} real sessions recorded.`, operator?.fingerprint),
    row('agency integration', 2.0, 8.0, cap?.passed && cap?.totals?.cancellations > 0 ? 7.5 : 2.0, 'Real official CAP ingestion, lifecycle, Twin effect, outage recovery, and replay', cap?.passed ? null : 'PUBLIC_EVIDENCE_EXHAUSTED', cap?.passed ? `${cap.totals.rawMessages} NWS/ECCC messages, ${cap.totals.lifecycleChains} reference chains, ${cap.totals.cancellations} cancellations, replay verified.` : 'Government CAP integration incomplete.', cap?.fingerprint),
    row('independent assurance', 0.0, 8.0, cleanRoom?.independentAttestation ? 8.0 : 2.5, 'Different reviewer reproduces the bundle against signed image digests', 'REAL_HUMAN_REQUIRED', 'Immutable reviewer bundle exists; different-agent attestation and image digests are absent.', cleanRoom?.fingerprint)
  ], passed = categories.every((item) => item.finalDefensibleScore >= 7.5), movements = categories.map((item) => ({ category: item.category, baseline: item.baseline, revised: item.finalDefensibleScore, delta: Number((item.finalDefensibleScore - item.baseline).toFixed(1)) })), core = { schemaVersion: 'vigia.sub-75-worldclass-report.v2', generatedAt: new Date().toISOString(), scoringRule: 'FINAL_DEFENSIBLE_SCORE=min(ENGINEERING_READINESS, REAL_WORLD_EVIDENCE); weakest critical sub-gate caps the category.', categories, movements, passed, decision: passed ? 'WORLD_CLASS_BACKEND_GATE_PASSED' : 'WORLD_CLASS_BACKEND_GATE_NOT_PASSED' };
  return artifact(projectRoot, 'sub-75-scorecard.json', core);
}
