import {readFile,writeFile} from 'node:fs/promises';
const directory=process.argv[2];if(!directory)throw Error('Provide the benchmark artifact directory');
const stats=values=>{const rows=values.filter(Number.isFinite).sort((a,b)=>a-b);return{samples:values.length,measured:rows.length,failures:values.length-rows.length,p50:rows.length?(rows[Math.floor((rows.length-1)*.5)]+rows[Math.ceil((rows.length-1)*.5)])/2:null,p95:rows[Math.min(rows.length-1,Math.ceil(rows.length*.95)-1)]??null,max:rows.at(-1)??null};};
const report={metric:'All requested imagery tiles loaded followed by a current visible map render; conservative proxy for first useful frame',limitations:['Not the earliest partially visible tile.','Baseline has two complete browser contexts; a third document navigation exceeded 30 seconds.','Three after contexts requested. Missing results and timeouts remain failures.','PostGIS calls were not correlated per browser request; separate scoped SQL/service measurements are retained.','Local backend and provider cache are shared; fresh browser does not mean cold provider cache.','Small sample p95 is the observed tail, not a statistically established production percentile.'],lanes:{}};
for(const [phase,file]of [['before','before-final-map.json'],['after','after-accepted-map.json']]){
 const data=JSON.parse(await readFile(directory+'/'+file,'utf8')),r=data.results;
 report.lanes[phase]={browser:data.browser,viewport:data.viewport,contexts:new Set(r.map(x=>x.sample)).size,errors:data.errors,cases:Object.fromEntries([...new Set(r.map(x=>x.case))].map(name=>{const rows=r.filter(x=>x.case===name);return[name,{frameMs:stats(rows.map(x=>x.firstUsefulFrameMs)),interactiveMs:stats(rows.map(x=>x.interactiveMs)),requests:stats(rows.map(x=>x.requests)),bytes:stats(rows.map(x=>x.bytes)),tileRequests:stats(rows.map(x=>x.tiles)),apiCalls:stats(rows.map(x=>x.apiCalls)),instances:[...new Set(rows.map(x=>x.instanceId))],layers:[...new Set(rows.map(x=>x.layerCount))]}];}))};
}
await writeFile('docs/handoffs/acceleration/map-performance.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
