#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCsv } from '../apps/api/src/shared/csv.mjs';
import { normalizeFirmsRows } from '../apps/api/src/modules/world/firms-normalizer.mjs';
import { haversineKm } from '../packages/domain/src/geo.mjs';
import { buildFireEvents } from '../packages/domain/src/fire-event-tracker.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const physicalDirectory=path.join(root,'data/validation/physical-sensing');
const viirsPath=path.join(physicalDirectory,'viirs-small-fire-opportunity.json');
const sentinelPath=path.join(physicalDirectory,'sentinel3-physical-corpus.json');
const sentinelManifestPath=path.join(root,'data/validation/detection/sentinel3-portugal-2024-product-manifest.json');
const activeCorpusPath=path.join(root,'data/validation/detection/portugal-2024-active-fire-corpus.json');
const handoffPath=path.join(physicalDirectory,'gold-specialist-handoff.json');
const outputPath=path.join(physicalDirectory,'small-fire-science-analysis.json');
const multisensorCorpusPath=path.join(physicalDirectory,'multisensor-validation-corpus.json');
const firmsSources=[
  {path:path.join(root,'data/replay/raw/nasa-firms/viirs-jpss1_2024_Portugal.csv'),sourceKey:'VIIRS_NOAA20_ARCHIVE'},
  {path:path.join(root,'data/replay/raw/nasa-firms/viirs-snpp_2024_Portugal.csv'),sourceKey:'VIIRS_SNPP_ARCHIVE'}
];
const sha=(value)=>createHash('sha256').update(value).digest('hex');
const ratio=(numerator,denominator)=>denominator?Number((numerator/denominator).toFixed(4)):null;
const percent=(numerator,denominator)=>denominator?Number((100*numerator/denominator).toFixed(2)):null;
const distribution=(rows,selector)=>Object.fromEntries([...new Set(rows.map(selector))].sort().map((key)=>[key,rows.filter((row)=>selector(row)===key).length]));
function quantile(values,q){const sorted=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!sorted.length)return null;return Number(sorted[Math.min(sorted.length-1,Math.max(0,Math.round((sorted.length-1)*q)))].toFixed(2));}
const TIME_BINS=['≤30 min','30–60 min','1–3 h','3–6 h','6–12 h','>12 h'];
function timeBin(value){return value<=.5?'≤30 min':value<=1?'30–60 min':value<=3?'1–3 h':value<=6?'3–6 h':value<=12?'6–12 h':'>12 h';}
function zenithBin(value){const angle=Math.abs(Number(value));return angle<=30?'≤30°':angle<=50?'30–50°':angle<=65?'50–65°':'>65°';}
function confidenceLabel(value){return({7:'low',8:'nominal',9:'high'})[Number(value)]??'unknown';}
function signalBand(value){return value<2?'<2 MW':value<10?'2–10 MW':'≥10 MW';}
function matchPlatform(label){return label==='VIIRS S-NPP'?'VIIRS S-NPP':'VIIRS NOAA-20';}

const [viirsBody,sentinelBody,sentinelManifestBody,activeCorpusBody]=await Promise.all([readFile(viirsPath),readFile(sentinelPath),readFile(sentinelManifestPath),readFile(activeCorpusPath)]),viirs=JSON.parse(viirsBody),sentinel=JSON.parse(sentinelBody),sentinelManifest=JSON.parse(sentinelManifestBody),activeCorpus=JSON.parse(activeCorpusBody);
const assignedCaseByObservation=new Map();for(const item of activeCorpus.cases)for(const observation of item.observations??[])assignedCaseByObservation.set(observation.id,item.caseId);
const archiveObservations=[],sourceArtifacts=[];
for(const source of firmsSources){const body=await readFile(source.path,'utf8'),rows=normalizeFirmsRows(parseCsv(body),source.sourceKey,{rawSourceProductId:path.relative(root,source.path),checksumSha256:sha(body),providerProductId:path.basename(source.path)});archiveObservations.push(...rows);sourceArtifacts.push({path:path.relative(root,source.path),checksumSha256:sha(body),rows:rows.length});}
const archiveByPlatform=new Map();for(const observation of archiveObservations){const rows=archiveByPlatform.get(observation.satellite)??[];rows.push(observation);archiveByPlatform.set(observation.satellite,rows);}

const signalPasses=[];
for(const item of viirs.cases)for(const opportunity of item.opportunities.filter((row)=>row.evaluation?.nativeFireSignal)){
  const native=opportunity.evaluation.nearestFirePixel,platform=matchPlatform(opportunity.platform),candidates=archiveByPlatform.get(platform)??[],ranked=candidates.map((observation)=>({observation,timeSeparationMinutes:Math.abs(Date.parse(observation.observedAt)-Date.parse(opportunity.startAt))/60_000,pixelSeparationKm:haversineKm(observation.coordinate,native.coordinate),referenceSeparationKm:haversineKm(observation.coordinate,item.coordinate)})).filter((row)=>row.timeSeparationMinutes<=10).sort((a,b)=>a.pixelSeparationKm-b.pixelSeparationKm||a.timeSeparationMinutes-b.timeSeparationMinutes),match=ranked.find((row)=>row.pixelSeparationKm<=.75)??null;
  signalPasses.push({caseId:item.caseId,platform,nativeId:opportunity.nativeId,startAt:opportunity.startAt,referenceCoordinate:item.coordinate,nativePixel:native,directArchiveMatch:match?{observationId:match.observation.id,coordinate:match.observation.coordinate,observedAt:match.observation.observedAt,confidence:match.observation.confidence,frpMw:match.observation.frpMw,hotspotType:match.observation.hotspotType,hotspotClass:match.observation.hotspotClass,exclusiveReferenceAssignment:assignedCaseByObservation.get(match.observation.id)??null,timeSeparationMinutes:Number(match.timeSeparationMinutes.toFixed(2)),pixelSeparationKm:Number(match.pixelSeparationKm.toFixed(3)),referenceSeparationKm:Number(match.referenceSeparationKm.toFixed(3)),insideReferenceTimeWindow:Date.parse(match.observation.observedAt)>=Date.parse(item.timeWindow.start)&&Date.parse(match.observation.observedAt)<=Date.parse(item.timeWindow.end)}:null,archiveRowsInPassWindow:ranked.length,nearestArchiveCandidate:ranked[0]?{observationId:ranked[0].observation.id,hotspotType:ranked[0].observation.hotspotType,hotspotClass:ranked[0].observation.hotspotClass,timeSeparationMinutes:Number(ranked[0].timeSeparationMinutes.toFixed(2)),pixelSeparationKm:Number(ranked[0].pixelSeparationKm.toFixed(3)),referenceSeparationKm:Number(ranked[0].referenceSeparationKm.toFixed(3))}:null});
}
const passesByCase=new Map();for(const row of signalPasses){const values=passesByCase.get(row.caseId)??[];values.push(row);passesByCase.set(row.caseId,values);}
const signalCases=viirs.cases.filter((item)=>item.fireSignal),priorUnknown=signalCases.filter((item)=>!item.providerRetained),reconciliation=[];
for(const item of signalCases){
  const passes=passesByCase.get(item.caseId)??[],matches=passes.filter((row)=>row.directArchiveMatch),vegetationMatches=matches.filter((row)=>row.directArchiveMatch.hotspotType===0),newMatch=!item.providerRetained&&matches.length>0;
  let classification='MATCHED RETAINED';
  if(newMatch&&!vegetationMatches.length)classification='FILTERED BY DOCUMENTED PROVIDER SEMANTICS — NON-VEGETATION HOTSPOT TYPE';
  else if(newMatch&&!vegetationMatches.some((row)=>row.directArchiveMatch.insideReferenceTimeWindow))classification='TIME/PRODUCT MISALIGNMENT — SCIENCE PASS OUTSIDE REFERENCE WINDOW';
  else if(newMatch&&vegetationMatches.every((row)=>row.directArchiveMatch.exclusiveReferenceAssignment&&row.directArchiveMatch.exclusiveReferenceAssignment!==item.caseId))classification='REFERENCE/MATCHING DEFECT — COMPETING REPORT ASSIGNMENT';
  else if(newMatch)classification=matches.some((row)=>row.directArchiveMatch.referenceSeparationKm>3)?'REFERENCE/MATCHING DEFECT — RETAINED PIXEL OUTSIDE CASE RADIUS':'REFERENCE/MATCHING DEFECT — DIRECT PIXEL MATCH MISSED';
  else if(!item.providerRetained&&!matches.length)classification=passes.some((row)=>row.archiveRowsInPassWindow>0)?'UNKNOWN — PROVIDER TRANSFORMATION/RETENTION SEMANTICS':'UNKNOWN — EMPTY ARCHIVE PASS WINDOW';
  reconciliation.push({caseId:item.caseId,priorProviderRetained:item.providerRetained,archiveRowIdentityFound:matches.length>0,reconciledProviderVegetationFireRetained:item.providerRetained||vegetationMatches.length>0,classification,directMatches:matches.map((row)=>row.directArchiveMatch),nativePasses:passes.map((row)=>({platform:row.platform,nativeId:row.nativeId,startAt:row.startAt,nativeConfidence:row.nativePixel.confidence,nativeFrpMw:row.nativePixel.frpMw,archiveRowsInPassWindow:row.archiveRowsInPassWindow,nearestArchiveCandidate:row.nearestArchiveCandidate}))});
}
const resolved=reconciliation.filter((row)=>!row.priorProviderRetained&&row.archiveRowIdentityFound),remaining=reconciliation.filter((row)=>!row.priorProviderRetained&&!row.archiveRowIdentityFound),reconciledRetained=reconciliation.filter((row)=>row.reconciledProviderVegetationFireRetained),semanticExclusions=reconciliation.filter((row)=>row.classification.startsWith('FILTERED BY DOCUMENTED PROVIDER SEMANTICS'));
const retentionTaxonomy=distribution(reconciliation,(row)=>row.classification);
const signalConfidence=Object.fromEntries(['low','nominal','high','unknown'].map((label)=>{const passes=signalPasses.filter((row)=>confidenceLabel(row.nativePixel.confidence)===label),matched=passes.filter((row)=>row.directArchiveMatch);return[label,{nativePasses:passes.length,directArchiveMatches:matched.length,directMatchRate:ratio(matched.length,passes.length)}];}));
const signalFrp=Object.fromEntries(['<2 MW','2–10 MW','≥10 MW'].map((label)=>{const passes=signalPasses.filter((row)=>signalBand(row.nativePixel.frpMw)===label),matched=passes.filter((row)=>row.directArchiveMatch);return[label,{nativePasses:passes.length,directArchiveMatches:matched.length,directMatchRate:ratio(matched.length,passes.length)}];}));

const granuleByNativeId=new Map(viirs.granules.map((item)=>[item.active.nativeId,item])),validNoSignal=viirs.cases.filter((item)=>item.validOpportunity&&!item.fireSignal),noSignalRows=validNoSignal.map((item)=>{
  const valid=item.opportunities.filter((row)=>row.evaluation?.validOpportunity).sort((a,b)=>a.timeSeparationHours-b.timeSeparationHours),nearest=valid[0],granule=granuleByNativeId.get(nearest.nativeId);
  return{caseId:item.caseId,burnedAreaHa:item.burnedAreaHa,sizeBand:item.sizeBand,regionBand:item.regionBand,platform:nearest.platform,dayNight:String(granule?.product?.['Day/Night/Both']??'Unknown').toUpperCase(),timeSeparationHours:nearest.timeSeparationHours,timeBin:timeBin(nearest.timeSeparationHours),sensorZenithDeg:nearest.evaluation.sensorZenithDeg,zenithBin:zenithBin(nearest.evaluation.sensorZenithDeg),fireMaskLabel:nearest.evaluation.fireMaskLabel,geolocationDistanceKm:nearest.evaluation.geolocationDistanceKm,referenceGeometry:'ICNF report point + governed 3 km matching radius; not a fire perimeter',cloudAtNearestValidPixel:nearest.evaluation.fireMaskLabel==='cloud'};
});
const noSignalScience={cases:validNoSignal.length,majorityFinding:{classification:'ACTUAL_CLEAR-LAND_NO-SIGNAL_AT_VALID_PASS',count:noSignalRows.filter((row)=>row.fireMaskLabel==='clear_land').length,percent:percent(noSignalRows.filter((row)=>row.fireMaskLabel==='clear_land').length,noSignalRows.length),interpretation:'The native fire mask classified the report-point pixel as clear land during a valid pass and no fire pixel existed within the governed 3 km radius. This is a real no-signal-at-pass result, not proof that no fire occurred; the ICNF alert time is not ignition time and the report point is not a perimeter.'},sizeBands:distribution(noSignalRows,(row)=>row.sizeBand),platforms:distribution(noSignalRows,(row)=>row.platform),dayNight:distribution(noSignalRows,(row)=>row.dayNight),timeRelativeToReport:{bins:distribution(noSignalRows,(row)=>row.timeBin),medianHours:quantile(noSignalRows.map((row)=>row.timeSeparationHours),.5),p25Hours:quantile(noSignalRows.map((row)=>row.timeSeparationHours),.25),p75Hours:quantile(noSignalRows.map((row)=>row.timeSeparationHours),.75)},scanGeometry:distribution(noSignalRows,(row)=>row.zenithBin),pixelClasses:distribution(noSignalRows,(row)=>row.fireMaskLabel),geolocationDistanceKm:{median:quantile(noSignalRows.map((row)=>row.geolocationDistanceKm),.5),p95:quantile(noSignalRows.map((row)=>row.geolocationDistanceKm),.95)},referenceGeometryLimitation:{pointOnlyCases:noSignalRows.length,perimeterCases:0,explanation:'Reference extent cannot be measured from an ICNF point plus matching radius; sub-pixel fire placement and point/perimeter mismatch remain possible.'}};

function performance(rows,signal=(row)=>row.signal){const detected=rows.filter(signal).length;return{opportunities:rows.length,nativeSignals:detected,detectionRate:ratio(detected,rows.length),detectionPercent:percent(detected,rows.length)};}
const validPassRows=viirs.cases.flatMap((item)=>item.opportunities.filter((row)=>row.evaluation?.validOpportunity).map((opportunity)=>{const granule=granuleByNativeId.get(opportunity.nativeId);return{caseId:item.caseId,sizeBand:item.sizeBand,regionBand:item.regionBand,platform:opportunity.platform,dayNight:String(granule?.product?.['Day/Night/Both']??'Unknown').toUpperCase(),timeSeparationHours:opportunity.timeSeparationHours,timeBin:timeBin(opportunity.timeSeparationHours),zenithBin:zenithBin(opportunity.evaluation.sensorZenithDeg),signal:opportunity.evaluation.nativeFireSignal};}));
const nearestPassRows=viirs.cases.filter((item)=>item.validOpportunity).map((item)=>{const opportunity=item.opportunities.filter((row)=>row.evaluation?.validOpportunity).sort((a,b)=>a.timeSeparationHours-b.timeSeparationHours)[0],granule=granuleByNativeId.get(opportunity.nativeId);return{caseId:item.caseId,sizeBand:item.sizeBand,regionBand:item.regionBand,platform:opportunity.platform,dayNight:String(granule?.product?.['Day/Night/Both']??'Unknown').toUpperCase(),timeSeparationHours:opportunity.timeSeparationHours,timeBin:timeBin(opportunity.timeSeparationHours),zenithBin:zenithBin(opportunity.evaluation.sensorZenithDeg),signal:opportunity.evaluation.nativeFireSignal,anyValidPassSignal:item.fireSignal};});
const by=(rows,labels,selector,signal)=>Object.fromEntries(labels.map((label)=>[label,performance(rows.filter((row)=>selector(row)===label),signal)]));
const caseRows=viirs.cases.filter((item)=>item.validOpportunity).map((item)=>({caseId:item.caseId,sizeBand:item.sizeBand,signal:item.fireSignal}));
const nearAlert=nearestPassRows.filter((row)=>row.timeSeparationHours<=3),farAlert=nearestPassRows.filter((row)=>row.timeSeparationHours>12),nearRate=ratio(nearAlert.filter((row)=>row.signal).length,nearAlert.length),farRate=ratio(farAlert.filter((row)=>row.signal).length,farAlert.length);
const temporalPerformance={label:'SENSOR OBSERVATION RELATIVE TO REFERENCE ALERT',qualification:'The reference alert is neither ignition time nor a guaranteed active-burning timestamp. Pass-level analysis treats every valid science pass independently. Nearest-pass analysis selects the closest valid pass without using its signal result; aggregate case-level detection remains any native signal across all valid passes.',aggregateCaseAnyValidPass:performance(caseRows),passLevel:{overall:performance(validPassRows),byTime:by(validPassRows,TIME_BINS,(row)=>row.timeBin),byPlatform:by(validPassRows,[...new Set(validPassRows.map((row)=>row.platform))].sort(),(row)=>row.platform),byDayNight:by(validPassRows,[...new Set(validPassRows.map((row)=>row.dayNight))].sort(),(row)=>row.dayNight),byScanAngle:by(validPassRows,['≤30°','30–50°','50–65°','>65°'],(row)=>row.zenithBin)},nearestValidPass:{overall:performance(nearestPassRows),byTime:by(nearestPassRows,TIME_BINS,(row)=>row.timeBin),medianSeparationHours:quantile(nearestPassRows.map((row)=>row.timeSeparationHours),.5)},sizeConditionedCaseAnyPass:by(caseRows,['<1 ha','1–5 ha','5–10 ha'],(row)=>row.sizeBand),sizeByNearestTime:Object.fromEntries(['<1 ha','1–5 ha','5–10 ha'].map((size)=>[size,by(nearestPassRows.filter((row)=>row.sizeBand===size),TIME_BINS,(row)=>row.timeBin)])),finding:{nearestPassWithin3Hours:performance(nearAlert),nearestPassBeyond12Hours:performance(farAlert),rateRatioNearVsBeyond12Hours:farRate?Number((nearRate/farRate).toFixed(2)):null,interpretation:'Detection is materially higher when the nearest valid pass is within three hours of the reference alert, while burned-area strata also matter strongly. The available evidence supports both temporal mismatch and sub-pixel fire size as dominant contributors; it cannot identify ignition or active-burning duration.'}};

const retention={prior:{signalCases:signalCases.length,caseAssignedRetainedSignals:signalCases.filter((item)=>item.providerRetained).length,unknownCases:viirs.errorTaxonomy?.UNKNOWN??priorUnknown.length,lowSignalUnresolvedCases:viirs.errorTaxonomy?.['LOW SIGNAL']??0,retentionRate:ratio(signalCases.filter((item)=>item.providerRetained).length,signalCases.length)},after:{signalCases:signalCases.length,archiveRowIdentityFoundCases:reconciliation.filter((row)=>row.archiveRowIdentityFound).length,vegetationFireRetainedCases:reconciledRetained.length,competingReferenceAssignments:reconciliation.filter((row)=>row.classification.includes('COMPETING REPORT ASSIGNMENT')).length,providerNonVegetationSemanticExclusions:semanticExclusions.length,resolvedPreviouslyUnknown:resolved.length,remainingUnknownCases:remaining.length,vegetationFireRetentionRate:ratio(reconciledRetained.length,signalCases.length),archiveIdentityRate:ratio(reconciliation.filter((row)=>row.archiveRowIdentityFound).length,signalCases.length),policyEligibleCaseAssignedSignals:viirs.cascade.providerRetained,policyAccepted:viirs.cascade.vigiaAccepted,policyRecallGivenCaseAssignedSignal:viirs.cascade.policyRecallGivenRetainedSignal},matchingContract:{samePlatform:true,maximumAcquisitionTimeSeparationMinutes:10,maximumNativePixelSeparationKm:.75,caseRadiusKm:3,priorCaseAssignment:'Each provider pixel was assigned exclusively to its nearest eligible ICNF report before the 626-case opportunity cohort was evaluated.'},taxonomy:retentionTaxonomy,byNativeConfidence:signalConfidence,byNativeFrp:signalFrp,providerSemanticsEvidence:{archiveReplacement:'FIRMS states NRT archive data are replaced with standard science-quality data when available.',hotspotTypes:{0:'presumed vegetation fire',1:'active volcano',2:'other static land source',3:'offshore detection'},conclusion:'Every native signal case has a direct Type-0 standard-archive pixel identity. The prior 41 UNKNOWN and two LOW SIGNAL retention outcomes were caused by an exclusive competing-report assignment in the benchmark corpus, not provider loss. They do not become policy rejections: policy recall remains defined on the 41 case-assigned signals.',officialSources:['https://firms.modaps.eosdis.nasa.gov/content/active_fire/','https://www.earthdata.nasa.gov/s3fs-public/imported/VIIRS_activefire_User_Guide.pdf']},records:reconciliation};

const targetCaseIds=new Set(sentinel.productionAssociation.targetCaseIds),targetCases=activeCorpus.cases.filter((item)=>targetCaseIds.has(item.caseId)),viirsFoundation=[...new Map(targetCases.flatMap((item)=>item.observations??[]).map((item)=>[item.id,item])).values()],latestFoundationAt=[...viirsFoundation,...sentinel.canonicalObservations].map((item)=>Date.parse(item.observedAt??item.at)).filter(Number.isFinite).sort((a,b)=>a-b).at(-1),foundationEvents=buildFireEvents({fires:targetCases.map((item)=>({id:item.caseId,coordinate:item.geometry.coordinates,startedAt:item.alertAt,updatedAt:item.alertAt,municipality:item.region?.municipality,district:item.region?.district,parish:item.region?.parish,burnedAreaHa:item.burnedAreaHa,status:'known_reference_fire',provenance:{synthetic:false,provider:'ICNF SGIF',rawSourceProductId:item.evidenceProvenance?.rawSourceProductId??item.caseId}})),thermalDetections:[...viirsFoundation,...sentinel.canonicalObservations]},{now:new Date(latestFoundationAt+5*60_000)});
function eventFamilies(event){return new Set(event.observations.filter((observation)=>observation.type==='thermal').map((observation)=>observation.sourceFamily));}
const s3Foundation=foundationEvents.filter((event)=>eventFamilies(event).has('sentinel-3-slstr')),twoFamilyFoundation=foundationEvents.filter((event)=>eventFamilies(event).has('sentinel-3-slstr')&&eventFamilies(event).has('viirs')),viirsOnlyFoundation=foundationEvents.filter((event)=>eventFamilies(event).has('viirs')&&!eventFamilies(event).has('sentinel-3-slstr'));
if(s3Foundation.length!==sentinel.metrics.sentinel3Events||twoFamilyFoundation.length!==sentinel.metrics.twoFamilyEvents)throw new Error('multisensor_foundation_rebuild_mismatch');
const duplicateCanonicalObservations=sentinel.canonicalObservations.length-new Set(sentinel.canonicalObservations.map((item)=>item.id)).size;
const multisensor={sentinel3PositiveProducts:sentinel.metrics.nativePositiveProducts,sentinel3PhysicalObservations:sentinel.metrics.canonicalAccepted,sentinel3SupportedEvents:sentinel.metrics.sentinel3Events,sentinel3SupportedOfficialFires:s3Foundation.filter((event)=>event.incidentIds.length>0).length,sentinel3OnlyEvents:s3Foundation.filter((event)=>!eventFamilies(event).has('viirs')).length,viirsOnlyEvents:viirsOnlyFoundation.length,viirsAndSentinel3Events:sentinel.metrics.twoFamilyEvents,associationAttempts:sentinel.metrics.canonicalAccepted,associationSuccess:sentinel.metrics.associatedObservations,associationSuccessRate:ratio(sentinel.metrics.associatedObservations,sentinel.metrics.canonicalAccepted),abstentions:sentinel.metrics.ambiguousObservations,unassigned:sentinel.metrics.unassignedObservations,duplicateCanonicalObservations,deduplicatedReplayProducts:sentinel.products.filter((item)=>item.reusedByChecksum).length,restartConsistency:{rerunProducts:sentinel.metrics.downloadedProducts,rerunFailures:sentinel.metrics.downloadFailures,stableEvidenceHash:sentinel.evidenceHash}};

function first(rows){return[...rows].sort((a,b)=>Date.parse(a.at??a.observedAt)-Date.parse(b.at??b.observedAt))[0]??null;}
function observationSummary(item){return{id:item.id,observedAt:item.at??item.observedAt,coordinate:item.coordinate,frpMw:item.frpMw??null,sourceFamily:item.sourceFamily,satellite:item.satellite??null,rawSourceProductId:item.provenance?.rawSourceProductId??null,providerProductId:item.provenance?.providerProductId??null,checksumSha256:item.provenance?.checksumSha256??null,qualityFlags:item.qualityFlags??[]};}
const multisensorRecords=twoFamilyFoundation.map((event)=>{const viirsRows=event.observations.filter((item)=>item.type==='thermal'&&item.sourceFamily==='viirs'),s3Rows=event.observations.filter((item)=>item.type==='thermal'&&item.sourceFamily==='sentinel-3-slstr'),firstViirs=first(viirsRows),firstS3=first(s3Rows),pairs=viirsRows.flatMap((viirsObservation)=>s3Rows.map((s3Observation)=>({viirsObservation,s3Observation,spatialSeparationKm:haversineKm(viirsObservation.coordinate,s3Observation.coordinate),temporalSeparationMinutes:Math.abs(Date.parse(viirsObservation.at)-Date.parse(s3Observation.at))/60_000}))).sort((a,b)=>a.spatialSeparationKm-b.spatialSeparationKm||a.temporalSeparationMinutes-b.temporalSeparationMinutes),nearest=pairs[0],reports=event.observations.filter((item)=>item.type==='report');const sourceOrdering=Date.parse(firstViirs.at)<Date.parse(firstS3.at)?'VIIRS_FIRST':Date.parse(firstS3.at)<Date.parse(firstViirs.at)?'SENTINEL3_FIRST':'SIMULTANEOUS';return{canonicalEventId:event.id,officialIncidentIds:event.incidentIds,coordinate:event.coordinate,viirsObservations:viirsRows.map(observationSummary),sentinel3Observations:s3Rows.map(observationSummary),firstViirs:observationSummary(firstViirs),firstSentinel3:observationSummary(firstS3),sourceOrdering,nearestCrossFamily:{viirsObservationId:nearest.viirsObservation.id,sentinel3ObservationId:nearest.s3Observation.id,spatialSeparationKm:Number(nearest.spatialSeparationKm.toFixed(3)),temporalSeparationMinutes:Number(nearest.temporalSeparationMinutes.toFixed(2))},frpRelationship:{viirsMaxMw:Math.max(...viirsRows.map((item)=>item.frpMw)),sentinel3MaxMw:Math.max(...s3Rows.map((item)=>item.frpMw)),ratioOfMaxima:Number((Math.max(...s3Rows.map((item)=>item.frpMw))/Math.max(...viirsRows.map((item)=>item.frpMw))).toFixed(3)),qualification:'Cross-sensor FRP values have different retrieval physics/resolution and are descriptive, not interchangeable calibration.'},reportState:{present:reports.length>0,firstReportAt:first(reports)?.at??null,reportIds:reports.map((item)=>item.incidentId)},associationRationale:(event.associationDecisions??[]).filter((item)=>['associated','ambiguous'].includes(item.state)),ambiguity:{state:event.associationState,abstentions:(event.ambiguousAssociations??[]).length},rawProvenance:{viirsRawProducts:[...new Set(viirsRows.map((item)=>item.provenance?.rawSourceProductId).filter(Boolean))],sentinel3RawProducts:[...new Set(s3Rows.map((item)=>item.provenance?.rawSourceProductId).filter(Boolean))]}};});
const fragmentationByIncident=Object.fromEntries([...new Set(multisensorRecords.flatMap((item)=>item.officialIncidentIds))].map((incidentId)=>[incidentId,multisensorRecords.filter((item)=>item.officialIncidentIds.includes(incidentId)).length]));
const multisensorCorpus={schema:'vigia.multisensor-validation-corpus.v1',generatedAt:new Date().toISOString(),scope:'Seven governed production-policy events containing independent VIIRS and Sentinel-3 SLSTR physical observations. This is a supported-case corpus, not a universal accuracy sample.',inputs:{sentinel3Corpus:{path:path.relative(root,sentinelPath),checksumSha256:sha(sentinelBody)},activeFireCorpus:{path:path.relative(root,activeCorpusPath),checksumSha256:sha(activeCorpusBody)}},metrics:{knownSupportedCases:multisensorRecords.length,associationSuccess:multisensorRecords.filter((item)=>item.officialIncidentIds.length>0&&item.ambiguity.abstentions===0).length,abstention:multisensorRecords.reduce((sum,item)=>sum+item.ambiguity.abstentions,0),fragmentedKnownIncidents:Object.values(fragmentationByIncident).filter((count)=>count>1).length,duplicateCanonicalObservations,stableOnRestart:sentinel.metrics.downloadFailures===0&&sentinel.products.every((item)=>item.reusedByChecksum),sourceOrdering:distribution(multisensorRecords,(item)=>item.sourceOrdering)},fragmentationByIncident,events:multisensorRecords};multisensorCorpus.evidenceHash=`sha256:${sha(JSON.stringify(multisensorCorpus))}`;

const productById=new Map(sentinelManifest.products.map((item)=>[item.id,item])),s3ByProduct=new Map();for(const observation of sentinel.canonicalObservations){const productId=String(observation.provenance?.providerProductId??'').replace(/:FRP_(?:in|an)$/,'');const rows=s3ByProduct.get(productId)??[];rows.push(observation);s3ByProduct.set(productId,rows);}
function bboxContains(bbox,coordinate){return Array.isArray(bbox)&&coordinate[0]>=bbox[0]&&coordinate[0]<=bbox[2]&&coordinate[1]>=bbox[1]&&coordinate[1]<=bbox[3];}
function unionRecord(item,{strict}){const products=sentinelManifest.products.filter((product)=>bboxContains(product.bbox,item.coordinate)&&Date.parse(product.observedAt)>=Date.parse(item.timeWindow.start)&&Date.parse(product.observedAt)<=Date.parse(item.timeWindow.end)&&(!strict||(product.targetCaseIds??[]).includes(item.caseId))),s3Observations=products.flatMap((product)=>s3ByProduct.get(product.id)??[]).filter((observation)=>Date.parse(observation.observedAt)>=Date.parse(item.timeWindow.start)&&Date.parse(observation.observedAt)<=Date.parse(item.timeWindow.end)&&haversineKm(observation.coordinate,item.coordinate)<=3),viirsDetected=item.fireSignal,s3Detected=s3Observations.length>0;return{caseId:item.caseId,sizeBand:item.sizeBand,viirsDetected,sentinel3Detected:s3Detected,bothDetected:viirsDetected&&s3Detected,eitherDetected:viirsDetected||s3Detected,neitherDetected:!viirsDetected&&!s3Detected,sentinel3OpportunityProducts:products.map((product)=>product.id),sentinel3ObservationIds:s3Observations.map((observation)=>observation.id)};}
function unionMetrics(rows){return{dualOpportunityCases:rows.length,viirsDetected:rows.filter((item)=>item.viirsDetected).length,sentinel3Detected:rows.filter((item)=>item.sentinel3Detected).length,bothDetected:rows.filter((item)=>item.bothDetected).length,viirsOnly:rows.filter((item)=>item.viirsDetected&&!item.sentinel3Detected).length,sentinel3Only:rows.filter((item)=>!item.viirsDetected&&item.sentinel3Detected).length,eitherDetected:rows.filter((item)=>item.eitherDetected).length,neitherDetected:rows.filter((item)=>item.neitherDetected).length,viirsDetectionRate:ratio(rows.filter((item)=>item.viirsDetected).length,rows.length),sentinel3DetectionRate:ratio(rows.filter((item)=>item.sentinel3Detected).length,rows.length),unionDetectionRate:ratio(rows.filter((item)=>item.eitherDetected).length,rows.length),twoFamilyCorroborationRate:ratio(rows.filter((item)=>item.bothDetected).length,rows.length),incrementalCasesFromSentinel3:rows.filter((item)=>!item.viirsDetected&&item.sentinel3Detected).length};}
const strictUnionRecords=viirs.cases.filter((item)=>item.validOpportunity&&targetCaseIds.has(item.caseId)).map((item)=>unionRecord(item,{strict:true})).filter((item)=>item.sentinel3OpportunityProducts.length),exploratoryUnionRecords=viirs.cases.filter((item)=>item.validOpportunity).map((item)=>unionRecord(item,{strict:false})).filter((item)=>item.sentinel3OpportunityProducts.length);
const smallFireMultisensorUnion={strictGovernedTarget:{...unionMetrics(strictUnionRecords),qualification:'Denominator is limited to small-fire cases explicitly targeted by the governed Sentinel-3 acquisition manifest and having a valid VIIRS per-pixel opportunity. It is the defensible union result for this run.',records:strictUnionRecords},catalogueBboxScreening:{...unionMetrics(exploratoryUnionRecords),qualification:'Exploratory only. Sentinel-3 product bounding-box/time intersection is weaker than VIIRS per-pixel valid-opportunity proof because the archived sparse FRP file has no full swath-quality mask. Do not use this broader result as an accuracy denominator.',records:exploratoryUnionRecords},conclusion:strictUnionRecords.some((item)=>!item.viirsDetected&&item.sentinel3Detected)?'Sentinel-3 added strictly governed small-fire detections beyond VIIRS.':'Sentinel-3 added no incremental detection in the strict governed small-fire denominator; all strict S3 detections were already detected by VIIRS. Broad catalogue-bbox screening contains additional S3-proximate signals but is not a defensible accuracy denominator.'};
const qualityErrors=viirs.errors.filter((item)=>item.type==='QUALITY FAILURE'),cloudQualityErrors=qualityErrors.filter((item)=>item.quality?.some((quality)=>quality.fireMaskLabel==='cloud')).length;
const reconciledErrorTaxonomy={'NO NATIVE SIGNAL':validNoSignal.length,'LOW SIGNAL':viirs.signalStrata?.['low (<2 MW)']?.knownFires??0,'QUALITY':qualityErrors.length,'CLOUD / OBSCURATION':cloudQualityErrors,'EDGE OF SWATH':viirs.errorTaxonomy?.['EDGE OF SWATH']??0,'GEOLOCATION':viirs.errorTaxonomy?.['GEOLOCATION FAILURE']??0,'REFERENCE TIMING':0,'REFERENCE/MATCHING — COMPETING REPORT ASSIGNMENT':retention.after.competingReferenceAssignments,'PROVIDER RETENTION UNKNOWN':remaining.length,'POLICY REJECTION':viirs.errorTaxonomy?.['SIGNAL / VIGIA REJECTED']??0,'SOURCE FAILURE':viirs.granuleSummary?.activeFireGranulesFailed??0,'UNKNOWN':remaining.length};
const artifact={schema:'vigia.small-fire-science-analysis.v2',generatedAt:new Date().toISOString(),inputs:{viirsOpportunity:{path:path.relative(root,viirsPath),checksumSha256:sha(viirsBody)},sentinel3Corpus:{path:path.relative(root,sentinelPath),checksumSha256:sha(sentinelBody)},sentinel3Manifest:{path:path.relative(root,sentinelManifestPath),checksumSha256:sha(sentinelManifestBody)},activeFireCorpus:{path:path.relative(root,activeCorpusPath),checksumSha256:sha(activeCorpusBody)},firmsArchives:sourceArtifacts},multisensor,temporalPerformance,smallFireMultisensorUnion,noSignalScience,retention,errorTaxonomy:{prior:viirs.errorTaxonomy,reconciled:reconciledErrorTaxonomy,countsAreNonExclusive:true},scientificUnknowns:[{scope:'VIIRS provider transformation/retention',cases:remaining.length,reason:remaining.length?'No direct same-platform/time/native-pixel row is present in the acquired standard FIRMS archive, and the archive does not expose a per-pixel exclusion reason.':'Resolved for this cohort: every native signal has a direct Type-0 archive-row identity.'},{scope:'VIIRS fire-to-report association for competing references',cases:retention.after.competingReferenceAssignments,reason:'The physical pixel is real and retained, but one pixel near multiple ICNF report points cannot establish which report generated the radiance without perimeter/ignition evidence.'},{scope:'VIIRS valid-pass no-signal causality',cases:validNoSignal.length,reason:'The pass proves no native signal within 3 km at that time; point/perimeter error, ignition timing, short fire duration, sub-pixel radiance, and fire behavior cannot be separated with the available reference geometry.'},{scope:'Sentinel-3 small-fire opportunity',strictCases:strictUnionRecords.length,reason:'The strict denominator is small because only explicitly targeted acquisitions provide governed S3 opportunity evidence. Product-bbox intersection alone lacks per-pixel no-fire quality evidence.'},{scope:'Sentinel-3 association',ambiguousObservations:sentinel.metrics.ambiguousObservations,unassignedObservations:sentinel.metrics.unassignedObservations,reason:'Production association safeguards abstain or create unassigned physical events when report-anchor evidence is insufficient.'}]};
artifact.evidenceHash=`sha256:${sha(JSON.stringify(artifact))}`;await Promise.all([writeFile(outputPath,`${JSON.stringify(artifact,null,2)}\n`),writeFile(multisensorCorpusPath,`${JSON.stringify(multisensorCorpus,null,2)}\n`)]);

const handoff=JSON.parse(await readFile(handoffPath,'utf8'));delete handoff.evidenceHash;handoff.schema='vigia.physical-sensing-gold-handoff.v3';handoff.generatedAt=new Date().toISOString();handoff.multisensorFoundation=multisensor;handoff.multisensorCorpus={path:path.relative(root,multisensorCorpusPath),evidenceHash:multisensorCorpus.evidenceHash,metrics:multisensorCorpus.metrics};const priorErrorRecords=handoff.viirs?.errorRecords??[];handoff.viirs={...(handoff.viirs??{}),errorRecords:undefined,errorRecordIds:priorErrorRecords.length?priorErrorRecords.map((item)=>item.id):(handoff.viirs?.errorRecordIds??[]),retentionReconciliation:{prior:retention.prior,after:retention.after,matchingContract:retention.matchingContract,taxonomy:retention.taxonomy,byNativeConfidence:retention.byNativeConfidence,byNativeFrp:retention.byNativeFrp},unknowns:{originalUnknownCount:viirs.errorTaxonomy?.UNKNOWN??41,originalLowSignalCount:viirs.errorTaxonomy?.['LOW SIGNAL']??2,resolvedByDirectArchiveEvidence:resolved.length,semanticExclusions:semanticExclusions.length,count:remaining.length,state:remaining.length?'PER_PIXEL_PROVIDER_TRANSFORMATION_CAUSALITY_UNAVAILABLE':'RESOLVED'},noSignalScience,temporalPerformance,smallFireMultisensorUnion,errorTaxonomy:artifact.errorTaxonomy};if(Array.isArray(handoff.sentinel3?.unassignedAssociations)){handoff.sentinel3.unassignedObservationIds=handoff.sentinel3.unassignedAssociations.map((item)=>item.observationId);delete handoff.sentinel3.unassignedAssociations;}handoff.scientificUnknowns=artifact.scientificUnknowns;const additions=[...(handoff.apiDomainAdditions??[]),{kind:'native-parser',path:'apps/api/src/modules/world/sentinel3/parse_sentinel3_frp.py'},{kind:'live-source',path:'apps/api/src/modules/world/live-physical-intelligence-service.mjs'},{kind:'live-api',path:'/api/v10/physical-sensing/live'},{kind:'corpus-runner',path:'scripts/acquire_sentinel3_physical_corpus.mjs'},{kind:'science-analysis',path:'scripts/analyze_physical_sensing_science.mjs'}];handoff.apiDomainAdditions=[...new Map(additions.map((item)=>[`${item.kind}:${item.path??item.field}`,item])).values()];handoff.artifacts={...(handoff.artifacts??{}),smallFireScience:path.relative(root,outputPath),multisensorCorpus:path.relative(root,multisensorCorpusPath)};handoff.remainingBlockers=(handoff.remainingBlockers??[]).filter((item)=>!/41 native VIIRS|provider transformation\/retention causality/i.test(item));if(remaining.length)handoff.remainingBlockers.push(`${remaining.length} native VIIRS signal cases still lack a direct same-platform/time/pixel identity in the standard FIRMS archive; per-pixel provider exclusion causality is unavailable.`);handoff.evidenceHash=`sha256:${sha(JSON.stringify(handoff))}`;await writeFile(handoffPath,`${JSON.stringify(handoff,null,2)}\n`);
console.log(JSON.stringify({outputPath,multisensorCorpusPath,handoffPath,evidenceHash:artifact.evidenceHash,temporalPerformance,smallFireMultisensorUnion:{strictGovernedTarget:{...smallFireMultisensorUnion.strictGovernedTarget,records:undefined},catalogueBboxScreening:{...smallFireMultisensorUnion.catalogueBboxScreening,records:undefined},conclusion:smallFireMultisensorUnion.conclusion},retention:{prior:retention.prior,after:retention.after,taxonomy:retention.taxonomy},multisensor,multisensorCorpus:multisensorCorpus.metrics},null,2));
