#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCsv } from '../apps/api/src/shared/csv.mjs';
import { normalizeFirmsRows } from '../apps/api/src/modules/world/firms-normalizer.mjs';
import { THERMAL_CANDIDATE_POLICY_VERSION, THERMAL_CANDIDATE_THRESHOLD_VERSION, THERMAL_CANDIDATE_V2_CANDIDATE_VERSION, THERMAL_CANDIDATE_V2_CANDIDATE_THRESHOLD_VERSION } from '../packages/domain/src/thermal-candidate-policy.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),directory=path.join(root,'data/validation/detection');
const sourcePath=path.join(directory,'portugal-2024-active-fire-corpus.json'),outputPath=path.join(directory,'portugal-2024-area-time-corpus.json'),lockPath=path.join(directory,'portugal-2024-area-time-policy-lock.json');
const viirsSources=[['data/replay/raw/nasa-firms/viirs-jpss1_2024_Portugal.csv','VIIRS_NOAA20_ARCHIVE'],['data/replay/raw/nasa-firms/viirs-snpp_2024_Portugal.csv','VIIRS_SNPP_ARCHIVE']];
const DAY=86_400_000,WINDOW_DAYS=7,AREA_KM2=100,sha=(value)=>createHash('sha256').update(value).digest('hex'),iso=(value)=>new Date(value).toISOString(),round=(value,digits=6)=>Number(Number(value).toFixed(digits));
const split=(id)=>{const bucket=parseInt(sha(id).slice(0,8),16)%10;return bucket<2?'FROZEN_CONFIRMATORY':bucket<4?'VALIDATION':'DEVELOPMENT';};
const masked=(item)=>({...item,type:'thermal',at:item.observedAt??item.at,receivedAt:null,hotspotType:null,hotspotClass:null,referenceOnlyFieldsMasked:true});
const week=(value)=>Math.floor((Date.parse(value)-Date.UTC(2024,0,1))/(WINDOW_DAYS*DAY));
const grid=(coordinate)=>`${Math.floor(coordinate[0]/.09)}:${Math.floor(coordinate[1]/.09)}`;
function bbox(coordinate){const halfLat=5/111,halfLon=5/(111*Math.cos(coordinate[1]*Math.PI/180));return[round(coordinate[0]-halfLon),round(coordinate[1]-halfLat),round(coordinate[0]+halfLon),round(coordinate[1]+halfLat)];}
function centre(rows,fallback){if(!rows.length)return fallback;return[round(rows.reduce((sum,item)=>sum+item.coordinate[0],0)/rows.length),round(rows.reduce((sum,item)=>sum+item.coordinate[1],0)/rows.length)];}
function range(anchor){const start=Date.parse(anchor)-DAY/2;return{start:iso(start),end:iso(start+WINDOW_DAYS*DAY)};}
function geometry(coordinate){return{type:'Polygon',coordinates:[[bbox(coordinate).slice(0,2),[bbox(coordinate)[2],bbox(coordinate)[1]],bbox(coordinate).slice(2),[bbox(coordinate)[0],bbox(coordinate)[3]],bbox(coordinate).slice(0,2)]],bbox:bbox(coordinate),qualification:'Governed approximate 10 × 10 km evaluation cell; not a fire perimeter.'};}
function windowRecord({id,coordinate,timeWindow,label,labelSource,labelAuthority,qualification,provenance,observations=[],eligible=false,eligibilityReason,tags=[],referenceEvidence=null,burnedAreaHa=null,region=null,context={}}){
  const rows=observations.map(masked).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));
  return{windowId:id,caseId:id,evaluationSplit:split(id),geometry:geometry(coordinate),coordinate,timeWindow,areaTime:{areaKm2:AREA_KM2,durationDays:WINDOW_DAYS,unit:'100 km² × 7 days'},referenceLabel:label,labelSource,labelAuthority,referenceQualification:qualification,referenceEvidence,evidenceProvenance:provenance,sensorCoverage:{viirs:{state:rows.length?'POSITIVE_PIXEL_PRESENT':eligible?'OBSERVATION_OPPORTUNITY_PROVEN':'OBSERVATION_OPPORTUNITY_UNRESOLVED',observationCount:rows.length,basis:rows.length?'At least one archived VIIRS pixel lies in the evaluation cell/time window.':'The annual detection archive has no complete swath mask; no opportunity is inferred from absence.'},sentinel3:{state:'NOT_EVALUATED'}},observationOpportunity:rows.length?'PROVEN_BY_PIXEL':'UNRESOLVED_NO_SWATH_MASK',sourceQuality:{dayNight:[...new Set(rows.map((item)=>item.dayNight).filter(Boolean))],confidence:[...new Set(rows.map((item)=>item.confidence).filter(Boolean))],scanKmRange:rows.length?[Math.min(...rows.map((item)=>Number(item.scanKm)||Infinity)),Math.max(...rows.map((item)=>Number(item.scanKm)||0))]:null},evaluationEligibility:{eligible,reason:eligibilityReason},tags,burnedAreaHa,region,temporalContext:context.temporal??null,spatialContext:context.spatial??null,firstPhysicalAt:rows[0]?.at??null,latestPhysicalAt:rows.at(-1)?.at??null,alertAt:referenceEvidence?.alertAt??null,timeToFirstPhysicalMinutes:rows[0]?.at&&referenceEvidence?.alertAt?round((Date.parse(rows[0].at)-Date.parse(referenceEvidence.alertAt))/60_000,2):null,observationToReportMinutes:rows[0]?.at&&referenceEvidence?.alertAt?round((Date.parse(referenceEvidence.alertAt)-Date.parse(rows[0].at))/60_000,2):null,observations:rows};
}

const active=JSON.parse(await readFile(sourcePath,'utf8')),windows=[],usedObservationIds=new Set();
for(const item of active.cases.filter((row)=>row.referenceLabel==='FIRE_POSITIVE')){
  for(const observation of item.observations)usedObservationIds.add(observation.id);
  const anchor=item.firstPhysicalAt??item.alertAt,timeWindow=range(anchor),rows=item.observations.filter((observation)=>Date.parse(observation.at)>=Date.parse(timeWindow.start)&&Date.parse(observation.at)<Date.parse(timeWindow.end)),eligible=rows.length>0;
  windows.push(windowRecord({id:`area-time:${item.caseId}`,coordinate:item.geometry.coordinates,timeWindow,label:'FIRE_POSITIVE',labelSource:item.labelSource,labelAuthority:item.labelAuthority,qualification:item.referenceQualification,provenance:item.evidenceProvenance,observations:rows,eligible,eligibilityReason:eligible?'REFERENCE_FIRE_WITH_VIIRS_PIXEL_IN_WINDOW':'NO_OBSERVATION_OPPORTUNITY_NOT_PROVEN',tags:[...item.tags,'AREA_TIME_FIRE_WINDOW'],referenceEvidence:{caseId:item.caseId,alertAt:item.alertAt,burnedAreaHa:item.burnedAreaHa,fireType:item.tags.includes('AGRICULTURAL_FIRE')?'Agrícola':'Florestal'},burnedAreaHa:item.burnedAreaHa,region:item.region,context:{temporal:{selection:'Seven-day cell anchored to first matched physical observation when present, otherwise official alert time.'},spatial:{referencePoint:item.geometry.coordinates,matchingRadiusKm:item.geometry.radiusKm}}}));
}
const negativeGroups=new Map();
for(const item of active.cases.filter((row)=>row.referenceLabel==='NON_WILDFIRE_NEGATIVE'))for(const observation of item.observations){const tag=item.tags.includes('OFFSHORE_HEAT')?'OFFSHORE_HEAT':'STATIC_OR_INDUSTRIAL_HEAT',key=`${tag}:${grid(observation.coordinate)}:${week(observation.at)}`;if(!negativeGroups.has(key))negativeGroups.set(key,{tag,rows:[],provenance:item.evidenceProvenance});negativeGroups.get(key).rows.push(observation);}
for(const [key,value] of negativeGroups){const coordinate=centre(value.rows,value.rows[0].coordinate),timeWindow=range(iso(Date.UTC(2024,0,1)+(week(value.rows[0].at)*WINDOW_DAYS+.5)*DAY)),id=`area-time:negative:${sha(key).slice(0,20)}`;windows.push(windowRecord({id,coordinate,timeWindow,label:'NON_WILDFIRE_NEGATIVE',labelSource:value.tag==='OFFSHORE_HEAT'?'NASA FIRMS VIIRS Type 3 offshore reference':'NASA FIRMS VIIRS Type 2 static-land reference',labelAuthority:'NASA LANCE FIRMS VIIRS standard active-fire product; label withheld from policy inputs',qualification:'Provider classification is used only as independent reference truth. It is removed before detector evaluation and conflict-checked against ICNF fires in the source corpus.',provenance:value.provenance,observations:value.rows,eligible:true,eligibilityReason:'PROVIDER_ADJUDICATED_NON_WILDFIRE_PIXEL_WITH_NO_ICNF_CONFLICT',tags:[value.tag,value.rows.length>1?'PERSISTENT_STATIC_HEAT':'SINGLE_HEAT','HARD_THERMAL_NEGATIVE','AREA_TIME_NEGATIVE_WINDOW'],referenceEvidence:{providerClass:value.tag==='OFFSHORE_HEAT'?3:2,providerClassAvailableToPolicy:false},context:{temporal:{weekIndex:week(value.rows[0].at),observationCount:value.rows.length},spatial:{gridCell:grid(coordinate),landContext:value.tag}}}));}
const raw=[];
for(const [relative,sourceKey] of viirsSources){const body=await readFile(path.join(root,relative)),rows=parseCsv(body),checksumSha256=sha(body);raw.push(...normalizeFirmsRows(rows,sourceKey,{rawSourceProductId:relative,checksumSha256,providerProductId:path.basename(relative)}));}
const unmatchedGroups=new Map();
for(const observation of raw.filter((item)=>Number(item.hotspotType)===0&&!usedObservationIds.has(item.id))){const key=`${grid(observation.coordinate)}:${week(observation.observedAt)}`;if(!unmatchedGroups.has(key))unmatchedGroups.set(key,[]);unmatchedGroups.get(key).push(observation);}
for(const [key,rows] of unmatchedGroups){const coordinate=centre(rows,rows[0].coordinate),timeWindow=range(iso(Date.UTC(2024,0,1)+(week(rows[0].observedAt)*WINDOW_DAYS+.5)*DAY)),id=`area-time:unlabelled-thermal:${sha(key).slice(0,20)}`;windows.push(windowRecord({id,coordinate,timeWindow,label:'UNLABELLED',labelSource:'No independent reference resolved',labelAuthority:'UNRESOLVED',qualification:'A provider-presumed vegetation-fire pixel without a matching ICNF reference is not forced positive or negative.',provenance:{rawSourceProductIds:[...new Set(rows.map((item)=>item.provenance.rawSourceProductId))]},observations:rows,eligible:false,eligibilityReason:'UNLABELLED_REFERENCE_UNRESOLVED',tags:['UNLABELLED_THERMAL_CONTEXT','DIFFICULT_WINDOW_NEAR_OR_OUTSIDE_REFERENCE_FIRES'],context:{temporal:{weekIndex:week(rows[0].observedAt),observationCount:rows.length},spatial:{gridCell:grid(coordinate)}}}));}
for(const item of active.cases.filter((row)=>row.referenceLabel==='FIRE_POSITIVE'&&parseInt(sha(row.caseId).slice(0,8),16)%10===0)){
  const base=item.geometry.coordinates,temporalAnchor=iso(Date.parse(item.alertAt)+28*DAY),spatial=[round(base[0]+.28),base[1]];
  windows.push(windowRecord({id:`area-time:matched-temporal:${sha(item.caseId).slice(0,20)}`,coordinate:base,timeWindow:range(temporalAnchor),label:'UNLABELLED',labelSource:'Systematic matched temporal sample',labelAuthority:'UNRESOLVED',qualification:'No complete swath or independent no-fire authority; this window is never forced negative.',eligible:false,eligibilityReason:'UNLABELLED_NO_OBSERVATION_OPPORTUNITY_PROVEN',tags:['MATCHED_TEMPORAL_NEGATIVE_CANDIDATE','NO_OBSERVATION_OPPORTUNITY'],context:{temporal:{matchedFrom:item.caseId,offsetDays:28}}}));
  windows.push(windowRecord({id:`area-time:matched-spatial:${sha(item.caseId).slice(0,20)}`,coordinate:spatial,timeWindow:range(item.alertAt),label:'UNLABELLED',labelSource:'Systematic matched spatial sample',labelAuthority:'UNRESOLVED',qualification:'No complete swath or independent no-fire authority; this window is never forced negative.',eligible:false,eligibilityReason:'UNLABELLED_NO_OBSERVATION_OPPORTUNITY_PROVEN',tags:['MATCHED_SPATIAL_NEGATIVE_CANDIDATE','NO_OBSERVATION_OPPORTUNITY'],context:{spatial:{matchedFrom:item.caseId,longitudeOffsetDegrees:.28}}}));
}
windows.sort((a,b)=>a.windowId.localeCompare(b.windowId));
const datasetHash=`sha256:${sha(JSON.stringify(windows))}`,generatedAt=new Date().toISOString(),corpus={schema:'vigia.area-time-detection-corpus.v1',generatedAt,datasetHash,region:'Portugal mainland and adjacent offshore FIRMS coverage',year:2024,samplingUnit:'Approximate 100 km² × 7-day window',selectionPolicy:{positives:'All unique official ICNF 2024 Florestal/Agrícola references; no performance-based selection.',negatives:'All provider-adjudicated Type 2/3 pixels regrouped into fixed spatial/week cells after ICNF conflict exclusion; provider label is withheld from policy inputs.',unlabelled:'All unmatched Type 0 thermal cells plus systematic hash-selected temporal/spatial matches. Unknown windows are never forced negative.',splits:'SHA-256(window ID) modulo 10: 60% development, 20% validation, 20% frozen confirmatory. Fixed before any area-time outcome evaluation.',coverage:'Pixels prove an observation opportunity. Absence in the annual detection archive does not.'},referenceIndependence:{referenceLabelsAvailableToPolicy:false,providerTypeAvailableToPolicy:false,providerClassAvailableToPolicy:false},inventory:{windows:windows.length,labelled:windows.filter((item)=>item.referenceLabel!=='UNLABELLED').length,unlabelled:windows.filter((item)=>item.referenceLabel==='UNLABELLED').length,positive:windows.filter((item)=>item.referenceLabel==='FIRE_POSITIVE').length,negative:windows.filter((item)=>item.referenceLabel==='NON_WILDFIRE_NEGATIVE').length,eligible:windows.filter((item)=>item.evaluationEligibility.eligible).length,splits:Object.fromEntries(['DEVELOPMENT','VALIDATION','FROZEN_CONFIRMATORY'].map((name)=>[name,windows.filter((item)=>item.evaluationSplit===name).length]))},limitations:['This is a stratified area-time reference-window benchmark, not a population-weighted census of every Portuguese km²-day.','Full VIIRS swath coverage is unavailable, so no-signal windows remain opportunity-unresolved.','Static-land provider reference does not by itself distinguish a named industrial facility from other persistent static heat.','Official ICNF alert time is not ignition or public-publication time.'],sourceArtifacts:[{path:path.relative(root,sourcePath),checksumSha256:sha(await readFile(sourcePath))},...viirsSources.map(([relative])=>({path:relative}))],windows};
const policyLock={schema:'vigia.area-time-policy-lock.v1',lockedAt:generatedAt,corpusDatasetHash:datasetHash,confirmatoryOutcomeInspectedBeforeLock:false,v1:{policyVersion:THERMAL_CANDIDATE_POLICY_VERSION,thresholdVersion:THERMAL_CANDIDATE_THRESHOLD_VERSION},v2Candidate:{policyVersion:THERMAL_CANDIDATE_V2_CANDIDATE_VERSION,thresholdVersion:THERMAL_CANDIDATE_V2_CANDIDATE_THRESHOLD_VERSION,featureSet:['thermal recurrence duration','maximum FRP','Portugal land-context compatibility'],staticSourceMaskVersion:'none-coordinate-free-recurrence-v1',referenceDataVersion:'ICNF-SGIF-2024-full + FIRMS-2024-archive',promotionRule:'Confirmatory specificity, FPR, balanced accuracy and MCC must materially improve without unacceptable eligible-fire recall loss.'}};
await mkdir(directory,{recursive:true});await writeFile(outputPath,`${JSON.stringify(corpus)}\n`);await writeFile(lockPath,`${JSON.stringify(policyLock,null,2)}\n`);console.log(JSON.stringify({outputPath,lockPath,datasetHash,inventory:corpus.inventory,confirmatoryOutcomes:'NOT_EVALUATED_BY_THIS_COMMAND'},null,2));
