#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { evidenceOperationEffectiveness } from '../apps/api/src/modules/mission/ground-truth-service.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),base=process.env.VIGIA_BASE_URL||'http://127.0.0.1:4177',output=path.join(root,'data/validation/release/vigia-gold-run-evidence.json');
const sha=(value)=>createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
async function request(route){const started=performance.now(),response=await fetch(`${base}${route}`),text=await response.text();let body;try{body=JSON.parse(text);}catch{body=text;}return{route,status:response.status,durationMs:Number((performance.now()-started).toFixed(1)),body};}
const [rootResponse,healthResponse,readyResponse,eventsResponse,bootstrapResponse,benchmarkResponse]=await Promise.all([request('/'),request('/api/v10/health'),request('/api/v10/ready'),request('/api/v10/events'),request('/api/v2/bootstrap'),request('/api/v10/detection/benchmark')]);
for(const response of [rootResponse,healthResponse,eventsResponse,bootstrapResponse,benchmarkResponse])if(response.status!==200)throw new Error(`runtime_route_failed:${response.route}:${response.status}`);
// V10 is intentionally command-bounded. The explicit forensic version retains
// the complete trace ledger for governed evidence capture.
const traceEventsResponse=await request('/api/v9/events');if(traceEventsResponse.status!==200)throw new Error(`runtime_route_failed:${traceEventsResponse.route}:${traceEventsResponse.status}`);
const events=eventsResponse.body,traceEvents=traceEventsResponse.body,bootstrap=bootstrapResponse.body,benchmark=benchmarkResponse.body,required=traceEvents.summary?.fullTimingRequiredFields??[];
const fullTrace=(traceEvents.events??[]).find((event)=>required.every((field)=>event.prospectiveDetectionTiming?.[field])&&event.prospectiveDetectionTiming?.traceIntegrity?.valid===true);
if(!fullTrace)throw new Error('complete_valid_live_trace_not_found');
const trace=fullTrace.prospectiveDetectionTiming,pairs=[[trace.providerObservationAt,trace.vigiaAcquiredAt],[trace.vigiaAcquiredAt,trace.vigiaParsedAt],[trace.vigiaParsedAt,trace.observationPersistedAt],[trace.observationPersistedAt,trace.candidateDecisionAt],[trace.vigiaParsedAt,trace.vigiaRawProductIngestedAt],[trace.candidateDecisionAt,trace.apiAvailableAt],[trace.vigiaRawProductIngestedAt,trace.apiAvailableAt],[trace.apiAvailableAt,trace.uiFirstSeenAt]];
if(pairs.some(([before,after])=>!Number.isFinite(Date.parse(before))||!Number.isFinite(Date.parse(after))||Date.parse(after)<Date.parse(before)))throw new Error('complete_trace_causal_order_failed');
const state=JSON.parse(await readFile(path.join(root,'data/runtime/production-v1.json'),'utf8')),action=evidenceOperationEffectiveness(state);
const safeSource=(source={})=>({state:source.state??null,configurationState:source.configurationState??null,accessClassification:source.accessClassification??null,fetchedAt:source.fetchedAt??null,latestSourceObservation:source.latestSourceObservation??source.upstreamAt??null,accepted:source.accepted??null,rejected:source.rejected??null,acquiredProducts:source.acquiredProducts??null,positiveObservations:source.positiveObservations??null,observationConclusion:source.observationConclusion??null,error:source.error??null});
const sentinel3Runtime=events.sources?.sentinel3Pixels??{},sentinel3Diagnostics=sentinel3Runtime.productDiagnostics??[],sumDiagnostics=(field)=>sentinel3Diagnostics.reduce((sum,item)=>sum+Number(item[field]??0),0),twoFamilyEventIds=(events.events??[]).filter((event)=>event.physicalSourceProfile?.twoPhysicalSourceFamilies===true||event.fireEvidenceState?.twoPhysicalSourceFamilies===true).map((event)=>event.id),currentProductionMultisensor={acquiredProducts:Number(sentinel3Runtime.acquiredProducts??0),parsedProducts:sentinel3Diagnostics.length,positiveProducts:sentinel3Diagnostics.filter((item)=>Number(item.positiveFrpRecordCount??0)>0).length,portugalPositiveProducts:sentinel3Diagnostics.filter((item)=>Number(item.aoiObservationCount??0)>0).length,parsedSourceRecords:sumDiagnostics('sourceRecordCount'),positiveFrpRecords:sumDiagnostics('positiveFrpRecordCount'),qualifyingPortugalObservations:sumDiagnostics('aoiObservationCount'),persistedSentinel3Observations:Number(events.summary?.sentinel3PhysicalObservations??sentinel3Runtime.accepted??0),sentinel3SupportedEvents:Number(events.summary?.viirsSentinel3Events??0),twoPhysicalFamilyEvents:Number(events.summary?.twoPhysicalFamilyEvents??twoFamilyEventIds.length),twoFamilyEventIds};
const artifact={
  schema:'vigia.gold-run.release-evidence.v1',capturedAt:new Date().toISOString(),baseUrl:`local-runtime:${new URL(base).port}`,
  runtime:{routes:[rootResponse,healthResponse,readyResponse,eventsResponse,traceEventsResponse,bootstrapResponse,benchmarkResponse].map(({route,status,durationMs})=>({route,status,durationMs})),health:healthResponse.body,readiness:{ready:readyResponse.body.ready,checks:readyResponse.body.checks}},
  detection:{summary:events.summary,sources:{firms:safeSource(events.sources?.firms),sentinel3:safeSource(events.sources?.sentinel3Pixels)},benchmark:{schema:benchmark.schema,evidenceHash:benchmark.evidenceHash,v3Baseline:benchmark.v3Baseline,v4:benchmark.v4,cohort:benchmark.cohort,sourceSpecific:benchmark.sourceSpecific,falsePositiveTaxonomy:benchmark.falsePositiveTaxonomy,falseNegativeTaxonomy:benchmark.falseNegativeTaxonomy},smallFire:benchmark.smallFire,physicalSensing:{handoff:benchmark.physicalSensing,handoffQualification:'The specialist handoff is a historical preflight snapshot. Current production acquisition and association evidence below supersedes its former Sentinel-3 credential blocker.',viirs:benchmark.physicalSensingViirs,currentProductionMultisensor},sentinel3:benchmark.sentinel3},
  prospectiveTiming:{requiredFields:required,populatedTimingCaptures:traceEvents.summary?.populatedTimingCaptures,invalidTimingCaptures:traceEvents.summary?.invalidTimingCaptures,fullTimingCaptures:traceEvents.summary?.fullTimingCaptures,traceDiagnostics:bootstrap.operations?.traceCompleteness??null,completeTrace:{eventId:fullTrace.id,label:fullTrace.label,timing:trace},qualification:'apiAvailableAt is the completed server snapshot. uiFirstSeenAt is the server receipt of a trace-bound acknowledgement emitted only after a same-origin browser visibly rendered the event. Provider receipt remains null unless supplied by the provider.'},
  prevention:{summary:bootstrap.prevention?.summary,validation:bootstrap.prevention?.validation,reviewContext:bootstrap.prevention?.reviewContext,reviewExchange:bootstrap.prevention?.reviewExchange,reviewCorpus:benchmark.prevention,expertReviewPack:{path:'data/validation/prevention/portugal-sentinel2-expert-review-pack-v1.json',labelsGenerated:false}},
  action:{...action,systemActionability:bootstrap.operations?.systemActionability??null,backlogReconciliation:state.actionBacklogReconciliation},
  integrity:{syntheticOperationalEvidence:false,secretValuesCaptured:false,completeTraceCausallyValid:true,rootHttp200:rootResponse.status===200,postgisReady:readyResponse.body.checks?.some((item)=>item.id==='postgres_physical_truth'&&item.ok)??false,limitations:['Current source state may be stale when the newest qualifying observation falls outside its freshness window; stale does not imply acquisition or authentication failure.','Sentinel-3 catalogue metadata is never counted as physical observation evidence.','PREVENT expert metrics remain unmeasured until an attributable qualified human completes the generated pack.']}
};
artifact.evidenceHash=`sha256:${sha(artifact)}`;
await writeFile(output,`${JSON.stringify(artifact)}\n`);
console.log(JSON.stringify({output,evidenceHash:artifact.evidenceHash,runtime:artifact.runtime.routes,completeTrace:artifact.prospectiveTiming.completeTrace,preventionContext:artifact.prevention.reviewContext?.inventory,physicalSensing:{viirsGranules:benchmark.physicalSensingViirs?.granuleMetrics?.activeFireGranulesAcquired??0,validOpportunities:benchmark.physicalSensingViirs?.smallFireOpportunityMetrics?.validOpportunity??0,sensorRecall:benchmark.physicalSensingViirs?.smallFireOpportunityMetrics?.sensorDetectionGivenValidOpportunity??null,sentinel3PositiveProducts:currentProductionMultisensor.positiveProducts,sentinel3Observations:currentProductionMultisensor.persistedSentinel3Observations,twoFamilyEvents:currentProductionMultisensor.twoPhysicalFamilyEvents},action:{systemActionable:artifact.action.systemActionability?.systemActionable??null,systemCompleted:artifact.action.systemActionability?.systemCompleted??null,systemEvidenceProducing:artifact.action.systemActionability?.evidenceProducing??null,systemUnknownsClosed:artifact.action.systemActionability?.unknownsClosed??null,systemYieldPercent:artifact.action.systemActionability?.yieldPercent??null,internallyActionableRequests:action.internallyActionableRequests,requestEvidenceProducing:action.requestsProducingNewEvidence,unknownsClosedWithEvidence:action.unknownsClosedWithEvidence,open:action.unknownsOpen,requestEvidenceYieldPercent:action.evidenceYieldPercent}},null,2));
