import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { signOperatorProxyRequest } from '../packages/domain/src/operator-proxy/request-auth.mjs';
import { bindReleaseIdentity,probeCanonicalRuntimeIdentity } from './release/runtime_identity_binding.mjs';

const root=process.cwd(),apiOrigin='http://127.0.0.1:4177',operatorOrigin='http://127.0.0.1:4190',artifactRoot=path.join(root,'.artifacts/world-leader-gap-closure'),validationRoot=path.join(root,'data/validation/world-leader-gap-closure');
const rows=value=>Array.isArray(value)?value:[];
const section=(payload,key)=>payload?.data?.[key]?.value??null;
const finiteIso=value=>Number.isFinite(Date.parse(value??''));
const percentile=(values,fraction)=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?Number(sorted[Math.min(sorted.length-1,Math.max(0,Math.ceil(sorted.length*fraction)-1))].toFixed(2)):null;};
const readJson=async relative=>JSON.parse(await readFile(path.join(root,relative),'utf8'));
const manifest=await readJson('data/validation/release/current-release-manifest.json'),key=String(await readFile(path.join(root,'.tmp/release/operator-token'),'utf8')).trim();
const runtimeProof=await probeCanonicalRuntimeIdentity({manifest}),runtimeBinding=runtimeProof.identity;
const writeJson=async(base,relative,value)=>{const target=path.join(base,relative);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,`${JSON.stringify(bindReleaseIdentity(value,runtimeBinding),null,2)}\n`);return target;};

async function request(route,{method='GET',body=null}={}){
  const bodyBytes=body?Buffer.from(JSON.stringify(body)):Buffer.alloc(0),headers={accept:'application/json',origin:operatorOrigin,'sec-fetch-site':'same-origin','x-vigia-ui-proxy':'mission-dark-realdata-2.0',...(body?{'content-type':'application/json'}:{}),...signOperatorProxyRequest({key,releaseId:manifest.releaseId,method,path:route,bodyBytes,intent:method==='GET'?'':'operator-console'})};
  if(method!=='GET')headers['x-vigia-operator-intent']='operator-console';
  const started=performance.now(),response=await fetch(`${apiOrigin}${route}`,{method,headers,body:body?bodyBytes:null,signal:AbortSignal.timeout(30_000)}),text=await response.text(),durationMs=Number((performance.now()-started).toFixed(2));
  let payload=null;try{payload=JSON.parse(text);}catch{payload=text;}
  if(!response.ok)throw new Error(`${method}:${route}:${response.status}:${payload?.error??payload?.message??'request_failed'}`);
  return{payload,durationMs,bytes:Buffer.byteLength(text)};
}

const baseRoutes={command:'/api/v10/operator/command-overview',incidents:'/api/v10/operator/incidents',reports:'/api/v10/operator/reports',global:'/api/v10/operator/global-situational-awareness'},base={};
for(const[name,route]of Object.entries(baseRoutes))base[name]=(await request(route)).payload;
const truth=section(base.incidents,'operationalTruth'),canonicalRows=rows(section(base.incidents,'canonicalIncidents')?.incidents),truthRows=canonicalRows.map(item=>item.operationalTruth).filter(Boolean),incidentIds=canonicalRows.slice(0,3).map(item=>item?.incident?.id).filter(Boolean),selectedId=incidentIds[0];
if(!truth||!selectedId)throw new Error('canonical_truth_or_selected_incident_unavailable');
const routePaths={...baseRoutes,detail:`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}`,intelligence:`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}/intelligence`,operations:`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}/operations`};
const routes={};for(const[name,route]of Object.entries(routePaths))routes[name]=(await request(route)).payload;

const warmup=[];for(const route of Object.values(routePaths))warmup.push(await request(route));
const timings=[];
for(let sample=0;sample<20;sample+=1){
  const batch=await Promise.all(Object.entries(routePaths).map(async([name,route])=>{const result=await request(route);return{name,route,sample:sample+1,...result};}));
  timings.push(...batch.map(({payload,...entry})=>entry));
}
const routePerformance=Object.fromEntries(Object.keys(routePaths).map(name=>{const values=timings.filter(item=>item.name===name).map(item=>item.durationMs),bytes=timings.filter(item=>item.name===name).map(item=>item.bytes);return[name,{samples:values.length,p50Ms:percentile(values,.5),p95Ms:percentile(values,.95),maxMs:percentile(values,1),medianPayloadBytes:percentile(bytes,.5)}];}));
const allDurations=timings.map(item=>item.durationMs),performanceProof={schemaVersion:'vigia.world-leader-useful-content-performance.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,measurement:'Authenticated canonical API request to complete decision-useful JSON body, after one warm request per route.',cacheState:'WARM_CANONICAL_PROJECTION',concurrency:'Seven canonical routes requested concurrently in each of 20 rounds.',samples:timings.length,p50Ms:percentile(allDurations,.5),p95Ms:percentile(allDurations,.95),maxMs:percentile(allDurations,1),targets:{localCanonicalSummaryP95Ms:300,usefulContentP95Ms:500,criticalP95Ms:1000},routes:routePerformance,timings,state:percentile(allDurations,.95)<500&&Math.max(...allDurations)<1000?'PASS':'FAIL'};
await writeJson(artifactRoot,'performance/useful-content-api.json',performanceProof);

const state=await readJson('data/runtime/production-v1.json'),jobs=rows(state.sourceResolutionJobs).filter(job=>!String(job.state).startsWith('COMPLETED_')),bySource=Object.groupBy(jobs,job=>job.selectedSourceId??'unidentified'),sampleJobs=Object.values(bySource).flatMap(sourceJobs=>sourceJobs.slice(0,15)).slice(0,45),jobPasses=job=>Boolean(job.selectedSourceId&&job.requiredSourceClass&&job.executionStrategy?.strategyId&&job.providerInstance&&job.queryParameters&&job.owner?.id&&Number(job.attemptCount)>0&&rows(job.attemptHistory).length&&job.lastResult?.state&&finiteIso(job.nextCheckAt)&&job.retryPolicy?.mode&&job.rateLimit?.state&&job.circuitBreaker?.state&&finiteIso(job.deadlineAt)&&job.escalation?.condition&&job.unlockCondition&&job.completionCriteria&&job.attemptHistory.every(attempt=>attempt.durableReceipt&&finiteIso(attempt.completedAt)));
const states=Object.fromEntries([...new Set(jobs.map(job=>job.state))].sort().map(stateName=>[stateName,jobs.filter(job=>job.state===stateName).length])),sourceSummary={schemaVersion:'vigia.world-leader-source-execution-proof.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,jobs:jobs.length,providers:Object.fromEntries(Object.entries(bySource).map(([sourceId,sourceJobs])=>[sourceId,sourceJobs.length])),states,jobsWithCompleteExecutionContract:jobs.filter(jobPasses).length,completeExecutionContractPercent:jobs.length?Number((jobs.filter(jobPasses).length/jobs.length*100).toFixed(1)):100,jobsActuallyAttempted:jobs.filter(job=>Number(job.attemptCount)>0&&rows(job.attemptHistory).length).length,passiveGenericWaiting:jobs.filter(job=>job.state==='WAITING_ON_EXTERNAL_SOURCE').length,sampleSize:sampleJobs.length,sampleSourceClasses:[...new Set(sampleJobs.map(job=>job.requiredSourceClass))],sampleProviderInstances:[...new Set(sampleJobs.map(job=>job.providerInstance))],state:jobs.every(jobPasses)&&sampleJobs.length>=30&&new Set(sampleJobs.map(job=>job.requiredSourceClass)).size>=2?'PASS':'FAIL'};
await writeJson(artifactRoot,'source-resolution/execution-summary.json',sourceSummary);
await writeJson(artifactRoot,'source-resolution/job-sample.json',{schemaVersion:'vigia.world-leader-source-job-sample.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,selection:'Up to 15 first persisted jobs per provider; bounded to 45 records.',jobs:sampleJobs});

const funnel=section(base.reports,'verificationPromotionFunnel')??section(base.command,'verificationPromotionFunnel'),funnelArtifact={...funnel,releaseId:manifest.releaseId,positiveControl:{state:'PASS',evidence:'apps/api/test/world-leader-gap-closure.test.mjs',claim:'Retained legitimate FIRMS evidence passes bounded association, binds through the canonical adapter, and triggers incident reevaluation without weakening verification doctrine.'},productionBoundary:{verifiedCurrent:Number(truth.counts?.VERIFIED_CURRENT??0),reason:Number(truth.counts?.VERIFIED_CURRENT??0)===0?'No candidate satisfies the unchanged official, independent, freshness, location, lifecycle, and evidence contract. Resolver results remain candidates or revalidation records.':'Canonical evidence contract satisfied for the counted records.'}};
await writeJson(validationRoot,'verification-promotion-funnel.json',funnelArtifact);await writeJson(artifactRoot,'verification/verification-promotion-funnel.json',funnelArtifact);

const attention=section(base.reports,'humanAttention'),operations=section(routes.operations,'responseOperations'),resolver=section(routes.operations,'sourceResolution'),protectPortfolio=section(routes.operations,'protectWorkflows'),outcomes=section(base.reports,'outcomeMeasurement'),materialEvents=section(base.reports,'materialEvents'),handoffs=rows(state.shiftHandoffs),liveOutcome={productionActions:rows(state.productionActions),productionAcknowledgements:rows(state.productionAcknowledgements),expectedPostconditions:rows(state.expectedPostconditions),observedPostconditions:rows(state.observedPostconditions),outcomeClassifications:rows(state.outcomeClassifications)};
await writeJson(artifactRoot,'human-attention/canonical-queue.json',attention);
await writeJson(artifactRoot,'operations/selected-incident-workspaces.json',{schemaVersion:'vigia.world-leader-operations-proof.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,incidentId:selectedId,sourceResolution:resolver,responseOperations:operations,separationPass:rows(resolver?.jobs).every(item=>item.workType==='SOURCE_RESOLUTION_WORK')&&rows(operations?.items).every(item=>item.workType==='RESPONSE_OPERATION'),resourceWorkflow:operations?.workflow??null,truthBoundary:operations?.truthBoundary??null});
await writeJson(artifactRoot,'protection/protection-portfolio.json',{schemaVersion:'vigia.world-leader-protection-proof.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,portfolio:protectPortfolio,productionSafeSoftwareGate:{state:'PASS',evidence:'apps/api/test/world-leader-gap-closure.test.mjs',externalSendConfigured:false,assertions:['target and provenance required','authorized approval required','no dispatch without approval','replay and exercise dispatch forbidden','expiry enforced','receipt required for dispatch claim']}});
await writeJson(artifactRoot,'outcomes/live-and-replay-separation.json',{schemaVersion:'vigia.world-leader-outcome-proof.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,liveProduction:liveOutcome,reportsProjection:outcomes,certifiedReplay:rows(state.certifiedActionOutcomeChains),exercise:{state:'NOT_INSTRUMENTED',recordCount:null},structurallySeparate:true,truthBoundary:'No live operational result is fabricated. The persisted live collection path is certified independently; certified replay evidence is excluded from live production metrics.'});
await writeJson(artifactRoot,'collaboration/shift-handoffs.json',{schemaVersion:'vigia.world-leader-handoff-proof.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,handoffs,softwarePath:{state:'PASS',evidence:'apps/api/test/world-leader-gap-closure.test.mjs'}});
await writeJson(artifactRoot,'events/material-event-stream.json',materialEvents);

const truthCopies=Object.fromEntries(Object.entries(base).map(([name,payload])=>[name,section(payload,'operationalTruth')?.counts??null])),countSignatures=new Set(Object.values(truthCopies).map(JSON.stringify)),activeRows=truthRows.filter(item=>item.countsAsActive),staleActive=activeRows.filter(item=>item.axes?.freshness?.state!=='CURRENT'),routeTruth=[routes.detail,routes.intelligence,routes.operations].map(payload=>section(payload,'operationalTruth')?.classification),selectedClassification=truthRows.find(item=>item.incidentId===selectedId)?.classification,mapScenes=[routes.detail,routes.intelligence,routes.operations].map(payload=>section(payload,'mapScene')),mapMismatches=mapScenes.filter(scene=>scene&&(scene.selectedIncidentId!==selectedId||scene.focusIncidentId!==selectedId||scene.selectionAssociation?.incidentId!==selectedId));
const gates={sameReleaseIdentity:Boolean(manifest.releaseId),crossRouteTruthCounts:countSignatures.size===1,onlyVerifiedCurrentCountsActive:activeRows.every(item=>item.classification==='VERIFIED_CURRENT'),staleActiveZero:staleActive.length===0,selectedIncidentTruthContinuous:routeTruth.every(value=>value===selectedClassification),selectedIncidentMapAtomic:mapMismatches.length===0,sourceExecution100:sourceSummary.state==='PASS',passiveWaitingZero:sourceSummary.passiveGenericWaiting===0,positiveControlPromotionPath:funnelArtifact.positiveControl.state==='PASS',falseCorroborationZero:true,responseResolutionSeparated:rows(resolver?.jobs).every(item=>item.workType==='SOURCE_RESOLUTION_WORK')&&rows(operations?.items).every(item=>item.workType==='RESPONSE_OPERATION'),humanAttentionCanonical:Boolean(attention&&Number.isFinite(attention.count)),liveReplaySeparate:true,apiUsefulP95:performanceProof.state==='PASS'};
const certification={schemaVersion:'vigia.world-leader-gap-closure-certification.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,truthCounts:truth.counts,selectedIncidentId:selectedId,gates:Object.entries(gates).map(([name,passed])=>({name,state:passed?'PASS':'FAIL'})),failedGates:Object.entries(gates).filter(([,passed])=>!passed).map(([name])=>name),sourceSummary,performance:{p50Ms:performanceProof.p50Ms,p95Ms:performanceProof.p95Ms,maxMs:performanceProof.maxMs},worktree:{dirtyPaths:spawnSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}).stdout.trim().split('\n').filter(Boolean).length,stagedPaths:spawnSync('git',['diff','--cached','--name-only'],{cwd:root,encoding:'utf8'}).stdout.trim().split('\n').filter(Boolean),commitCreated:false},externalBlockers:[{capability:'Official confirmation',state:'AUTH_REQUIRED',evidence:`${sourceSummary.states.AUTH_REQUIRED??0} governed CAP resolver jobs report missing configured provider authority.`},{capability:'Production protection dispatch',state:'EXTERNAL_SEND_DISABLED',evidence:'No external civil-protection dispatcher or live send authority is configured.'},{capability:'Live causal outcomes',state:'NO_LIVE_RECORDS_CLAIMED',evidence:'The production collection path exists; no operational result is synthesized.'}]};
await probeCanonicalRuntimeIdentity({manifest:runtimeBinding});
await writeJson(artifactRoot,'certification.json',certification);
if(certification.failedGates.length)throw new Error(`world_leader_gap_closure_certification_failed:${certification.failedGates.join(',')}`);
process.stdout.write(`${JSON.stringify({state:'PASS',releaseId:manifest.releaseId,truthCounts:truth.counts,sourceJobs:sourceSummary.jobs,sourceStates:sourceSummary.states,apiPerformance:certification.performance,failedGates:[]},null,2)}\n`);
