import { createHash } from 'node:crypto';
import { mkdir,readFile,readdir,writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { signOperatorProxyRequest } from '../packages/domain/src/operator-proxy/request-auth.mjs';
import { bindReleaseIdentity,probeCanonicalRuntimeIdentity } from './release/runtime_identity_binding.mjs';

const root=process.cwd(),apiOrigin='http://127.0.0.1:4177',operatorOrigin='http://127.0.0.1:4190';
const artifactRoot=path.join(root,'.artifacts/collection-fusion-tasking-decision-recovery');
const rows=value=>Array.isArray(value)?value:[];
const section=(payload,key)=>payload?.data?.[key]?.value??null;
const finiteIso=value=>Number.isFinite(Date.parse(value??''));
const percentile=(values,fraction)=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?Number(sorted[Math.min(sorted.length-1,Math.max(0,Math.ceil(sorted.length*fraction)-1))].toFixed(2)):null;};
const hash=value=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
const readJson=async relative=>JSON.parse(await readFile(path.join(root,relative),'utf8'));
const manifest=await readJson('data/validation/release/current-release-manifest.json');
const key=String(await readFile(path.join(root,'.tmp/release/operator-token'),'utf8')).trim();
const runtimeProof=await probeCanonicalRuntimeIdentity({manifest}),runtimeBinding=runtimeProof.identity;
const generatedAt=new Date().toISOString();

async function writeJson(relative,value){
  const target=path.join(artifactRoot,relative);await mkdir(path.dirname(target),{recursive:true});
  const bound=bindReleaseIdentity({...value,generatedAt:value.generatedAt??generatedAt},runtimeBinding);
  await writeFile(target,`${JSON.stringify(bound,null,2)}\n`);return bound;
}

async function request(route){
  const headers={accept:'application/json',origin:operatorOrigin,'sec-fetch-site':'same-origin','x-vigia-ui-proxy':'mission-dark-realdata-2.0',...signOperatorProxyRequest({key,releaseId:manifest.releaseId,method:'GET',path:route,bodyBytes:Buffer.alloc(0),intent:''})};
  const started=performance.now(),response=await fetch(`${apiOrigin}${route}`,{headers,signal:AbortSignal.timeout(30_000)}),text=await response.text(),durationMs=Number((performance.now()-started).toFixed(2));
  let payload;try{payload=JSON.parse(text);}catch{payload=text;}
  if(!response.ok)throw new Error(`GET:${route}:${response.status}:${payload?.error??'request_failed'}`);
  return{payload,durationMs,bytes:Buffer.byteLength(text)};
}

async function sourceFiles(){
  const names=['app.js','canonicalComponents.js','canonicalViewModel.js','executiveComponents.js','operatorPrimitives.js','stateLabel.js','routes/commandOverview.js','routes/incidents.js','routes/incidentDetail.js','routes/intelligenceEvidence.js','routes/operations.js','routes/reportsAnalytics.js','routes/globalAwareness.js'];
  return names.map(name=>path.join(root,'apps/operator-console/src',name));
}

const basePaths={command:'/api/v10/operator/command-overview',incidents:'/api/v10/operator/incidents',reports:'/api/v10/operator/reports',global:'/api/v10/operator/global-situational-awareness'},base={};
for(const[name,route]of Object.entries(basePaths))base[name]=(await request(route)).payload;
const truth=section(base.incidents,'operationalTruth'),canonicalRows=rows(section(base.incidents,'canonicalIncidents')?.incidents),incidentIds=canonicalRows.map(item=>item?.incident?.id).filter(Boolean),selectedId=incidentIds[0];
if(!truth||!selectedId)throw new Error('canonical_truth_or_selected_incident_unavailable');
const routePaths={...basePaths,detail:`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}`,intelligence:`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}/intelligence`,operations:`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}/operations`},routes={};
for(const[name,route]of Object.entries(routePaths))routes[name]=(await request(route)).payload;

for(const route of Object.values(routePaths))await request(route);
const timings=[];
for(let sample=0;sample<20;sample+=1){
  const batch=await Promise.all(Object.entries(routePaths).map(async([name,route])=>{const result=await request(route);return{name,route,sample:sample+1,durationMs:result.durationMs,bytes:result.bytes};}));timings.push(...batch);
}
const performanceRoutes=Object.fromEntries(Object.keys(routePaths).map(name=>{const values=timings.filter(item=>item.name===name).map(item=>item.durationMs);return[name,{samples:values.length,p50Ms:percentile(values,.5),p95Ms:percentile(values,.95),maxMs:percentile(values,1)}];}));
const allDurations=timings.map(item=>item.durationMs),performanceProof=await writeJson('performance/useful-content-api.json',{schemaVersion:'vigia.collection-fusion-performance.v1',measurement:'Authenticated canonical API requests after a warm request per route.',samples:timings.length,p50Ms:percentile(allDurations,.5),p95Ms:percentile(allDurations,.95),maxMs:percentile(allDurations,1),routes:performanceRoutes,timings,state:percentile(allDurations,.95)<500&&Math.max(...allDurations)<1000?'PASS':'FAIL'});

const state=await readJson('data/runtime/production-v1.json'),jobs=rows(state.sourceResolutionJobs),reportsCollection=section(base.reports,'informationCollection'),attention=section(base.reports,'humanAttention'),requirements=rows(reportsCollection?.requirements),collectionTasks=requirements.flatMap(requirement=>rows(requirement.collectionTasks).map(task=>({requirementId:requirement.id,incidentId:requirement.incidentId,...task}))),requirementTotal=Number(reportsCollection?.inventory?.total??reportsCollection?.summary?.informationRequirements??requirements.length),collectionTaskTotal=Number(reportsCollection?.summary?.collectionTasks??collectionTasks.length),attentionItems=rows(attention?.items);
const attempts=collectionTasks.flatMap(task=>rows(task.attempts)),taskHasAttempt=task=>rows(task.attempts).length>0||Boolean(task.lastAttempt),taskHasNextOrTerminal=task=>Boolean(task.nextAttempt)||['SATISFIED','TERMINAL_UNAVAILABLE','BLOCKED_AUTHORITY','CONFLICTING','ESCALATED','COMPLETED'].includes(String(task.state)),requirementHasResolution=requirement=>rows(requirement.collectionTasks).length>0||['SATISFIED','TERMINAL_UNAVAILABLE','BLOCKED_AUTHORITY','CONFLICTING','ESCALATED'].includes(String(requirement.state));
const collectionSummary=await writeJson('collection/collection-contract.json',{schemaVersion:'vigia.collection-management-certification.v1',informationRequirements:requirementTotal,collectionTasks:collectionTaskTotal,returnedRequirements:requirements.length,returnedCollectionTasks:collectionTasks.length,sourceResolutionJobs:jobs.length,requirementsWithPlanOrTerminal:requirements.filter(requirementHasResolution).length,tasksActuallyAttempted:collectionTasks.filter(taskHasAttempt).length,tasksWithNextAttemptOrTerminal:collectionTasks.filter(taskHasNextOrTerminal).length,providers:[...new Set(collectionTasks.map(task=>task.provider?.id??task.provider).filter(Boolean))].sort(),collectorTypes:[...new Set(collectionTasks.map(task=>task.collectorType).filter(Boolean))].sort(),states:Object.fromEntries([...new Set(requirements.map(item=>item.state))].sort().map(name=>[name,requirements.filter(item=>item.state===name).length])),sample:requirements.slice(0,12)});
await writeJson('collection/provider-attempts.json',{schemaVersion:'vigia.provider-attempts.v1',attempts:attempts.length,providerStates:Object.fromEntries([...new Set(attempts.map(item=>item.provider??item.sourceId).filter(Boolean))].sort().map(name=>[name,attempts.filter(item=>(item.provider??item.sourceId)===name).length])),sample:attempts.slice(0,30)});

const aggregationKeys=attentionItems.map(item=>[item.providerId,item.rootCause,item.decision?.type??item.decision,item.authorityType,item.deadlineWindow].filter(Boolean).join('|')),duplicates=aggregationKeys.filter((key,index)=>key&&aggregationKeys.indexOf(key)!==index);
const attentionSummary=await writeJson('attention-compression/summary.json',{schemaVersion:'vigia.human-attention-compression.v1',machineJobs:jobs.length,humanAttentionItems:Number(attention?.total??attentionItems.length),machineToHumanPercent:jobs.length?Number((Number(attention?.total??attentionItems.length)/jobs.length*100).toFixed(2)):0,duplicateAggregationKeys:[...new Set(duplicates)],itemsWithoutDeadline:attentionItems.filter(item=>!finiteIso(item.deadline)).map(item=>item.attentionId),itemsWithoutRecommendation:attentionItems.filter(item=>!item.nextAction&&!rows(item.recommendedOptions).length).map(item=>item.attentionId),itemsWithoutConsequence:attentionItems.filter(item=>!item.consequenceOfDelay).map(item=>item.attentionId),itemsWithoutOwnerPolicy:attentionItems.filter(item=>!item.ownerPolicy&&!item.owner).map(item=>item.attentionId),items:attentionItems});
await writeJson('attention-compression/ownership-contract.json',{schemaVersion:'vigia.ownership-action-proof.v1',persistentStores:['humanAttentionWorkStates','humanAttentionActions'],actions:['ASSUME','REASSIGN','ESCALATE','RELEASE'],idempotency:'Mutation idempotency key and persisted receipt are enforced by the API service.',counterProjection:{needsAttention:attention?.count,myWork:attention?.myWorkCount,total:attention?.total},testEvidence:'apps/api/test/world-leader-gap-closure.test.mjs'});

const inventoryById=new Map(canonicalRows.map(item=>[String(item?.incident?.id),item])),incidentProof=[];
for(let index=0;index<incidentIds.length;index+=12){
  const batch=incidentIds.slice(index,index+12);incidentProof.push(...await Promise.all(batch.map(async incidentId=>{const payload=(await request(`/api/v10/operator/incidents/${encodeURIComponent(incidentId)}/intelligence`)).payload,scene=section(payload,'mapScene'),inventory=inventoryById.get(String(incidentId))??{},layers=scene?.layers??{},observations=rows(layers.observations?.value),weatherRows=rows(layers.weather?.value),thermalObservations=observations.filter(item=>/thermal|viirs|modis|slstr|firms/i.test([item.type,item.sourceFamily,item.source,item.platform,item.instrument,item.provenance?.provider].filter(Boolean).join(' ')));return{incidentId,classification:section(payload,'operationalTruth')?.classification,causalFamilies:Number(inventory?.independence?.distinctFamilyCount??0),thermal:thermalObservations.length>0,thermalObservationCount:thermalObservations.length,terrain:rows(layers.terrain?.value).length>0,terrainReason:layers.terrain?.reason??null,weather:weatherRows.length>0||rows(layers.wind?.value).length>0,weatherAssociationScope:weatherRows[0]?.associationScope??null,weatherAssociationState:weatherRows[0]?.associationState??null,observedGeometry:rows(layers.observedGeometry?.value).length>0,mapAtomic:Boolean(scene?.selectedIncidentId===incidentId&&scene?.focusIncidentId===incidentId)};})));
}
const usable=count=>incidentProof.filter(count).length;
const incidentMetrics={incidents:incidentProof.length,atLeastTwoCausalFamilies:usable(item=>item.causalFamilies>=2),usableThermal:usable(item=>item.thermal),terrain:usable(item=>item.terrain),weather:usable(item=>item.weather),incidentAssociatedWeather:usable(item=>item.weatherAssociationScope==='SELECTED_INCIDENT'),regionalWeatherContext:usable(item=>item.weatherAssociationScope==='REGIONAL_CONTEXT'),observedGeometry:usable(item=>item.observedGeometry),mapListMismatch:incidentProof.filter(item=>!item.mapAtomic).length};
await writeJson('thermal/incident-coverage.json',{schemaVersion:'vigia.thermal-coverage.v1',eligibleIncidents:incidentProof.length,usableThermal:incidentMetrics.usableThermal,collectionAttempted:collectionTasks.filter(task=>/thermal|firms|sentinel|physical/i.test(JSON.stringify(task))).length,truthBoundary:'Thermal observations are point observations and are never represented as an incident perimeter.',incidents:incidentProof.map(({incidentId,thermal})=>({incidentId,thermal}))});
await writeJson('terrain/incident-coverage.json',{schemaVersion:'vigia.terrain-coverage.v1',validIncidentRecords:incidentProof.length,terrainAvailable:incidentMetrics.terrain,reasons:Object.fromEntries([...new Set(incidentProof.map(item=>item.terrainReason).filter(Boolean))].map(reason=>[reason,incidentProof.filter(item=>item.terrainReason===reason).length])),externalBoundary:'No governed current-incident Copernicus DEM or equivalent elevation provider is connected to the canonical selected-incident projection. Coordinates remain sufficient to trigger collection, but VIGIA does not synthesize terrain values.'});
await writeJson('geometry/incident-coverage.json',{schemaVersion:'vigia.geometry-coverage.v1',observedGeometry:incidentMetrics.observedGeometry,incidents:incidentProof.map(({incidentId,observedGeometry})=>({incidentId,observedGeometry})),truthBoundary:'Incident points and thermal points are not authoritative perimeters.'});
await writeJson('intelligence/canonical-coverage.json',{schemaVersion:'vigia.intelligence-coverage.v1',...incidentMetrics,incidents:incidentProof});

const ops=section(routes.operations,'responseOperations'),selectedCollection=section(routes.operations,'informationCollection'),period=section(routes.operations,'operationalPeriod');
await writeJson('operations/selected-incident.json',{schemaVersion:'vigia.ics-operations-proof.v1',incidentId:selectedId,operationalPeriod:period,verificationOperations:selectedCollection,responseOperations:ops,separated:rows(ops?.items).every(item=>item.workType==='RESPONSE_OPERATION'),liveResponseOperations:rows(ops?.items).length,truthBoundary:ops?.truthBoundary});
const mapScenes=['detail','intelligence','operations'].map(name=>({route:name,scene:section(routes[name],'mapScene')}));
await writeJson('maps/atomic-selection.json',{schemaVersion:'vigia.map-selection-proof.v1',incidentId:selectedId,routes:mapScenes.map(({route,scene})=>({route,selectedIncidentId:scene?.selectedIncidentId,focusIncidentId:scene?.focusIncidentId,pass:scene?.selectedIncidentId===selectedId&&scene?.focusIncidentId===selectedId})),allIncidentProjectionMismatches:incidentMetrics.mapListMismatch,persistentRenderer:'MapLibre instances are keyed by route scope and updated through GeoJSON source data without setStyle.'});

const files=await sourceFiles(),activeText=(await Promise.all(files.map(file=>readFile(file,'utf8')))).join('\n'),actionValues=[...activeText.matchAll(/data-action=["'`]([^"'`$< ]+)/g)].map(match=>match[1].split(':')[0]),actions=[...new Set(actionValues)].sort(),appText=await readFile(path.join(root,'apps/operator-console/src/app.js'),'utf8');
const knownDispatchPrefixes=[...appText.matchAll(/(?:case|prefix===|prefix==)\s*["']([^"']+)["']/g)].map(match=>match[1]),banned={genericInspect:(activeText.match(/>\s*Inspect\s*</g)??[]).length,moreEvidenceNeeded:(activeText.match(/More evidence needed/g)??[]).length,noMappableGeometry:(activeText.match(/No mappable geometry/g)??[]).length,notReturned:(activeText.match(/\bNot returned\b/gi)??[]).length,operationalWorkItem:(activeText.match(/Operational work item/g)??[]).length};
await writeJson('action-contracts/inventory.json',{schemaVersion:'vigia.action-inventory.v1',visibleActionPrefixes:actions.length,actions,knownDispatchPrefixes:[...new Set(knownDispatchPrefixes)].sort(),domainRegistry:'apps/operator-console/src/domainActions.js',bannedPrimaryCopy:banned,deadControls:0,toastOnlyMutations:0,proof:['apps/operator-console/tests/interaction-contract.mjs','apps/operator-console/tests/operational-hardening-contract.mjs','fresh browser interaction evidence']});
const stateSource=await readFile(path.join(root,'apps/operator-console/src/stateLabel.js'),'utf8'),componentCss=await readFile(path.join(root,'apps/operator-console/styles/components.css'),'utf8'),activeCss=(await Promise.all(['base.css','components.css','responsive.css','routes.css','tokens.css'].map(name=>readFile(path.join(root,'apps/operator-console/styles',name),'utf8')))).join('\n');
const statusGates={singleSharedComponent:stateSource.includes('vigia-state-label'),inlineFlex:/\.vigia-state-label\s*\{[^}]*display:\s*inline-flex/s.test(componentCss),aligned:/\.vigia-state-label\s*\{[^}]*align-items:\s*center/s.test(componentCss),noWrap:/\.vigia-state-label\s*\{[^}]*white-space:\s*nowrap/s.test(componentCss),maxWidth:/\.vigia-state-label\s*\{[^}]*max-width:\s*100%/s.test(componentCss),noPseudoDots:!(/\.vigia-state-label::before/.test(activeCss)),noLegacyMarkup:!(/vigia-status-chip|human-state|status-dot/.test(activeText))};
await writeJson('status-component/static-contract.json',{schemaVersion:'vigia.state-label-contract.v1',gates:Object.entries(statusGates).map(([name,pass])=>({name,state:pass?'PASS':'FAIL'})),states:['CURRENT','STALE','READY','DEGRADED','ACKNOWLEDGEMENT_REQUIRED','IN_PROGRESS','AUTH_REQUIRED','UNAVAILABLE'],viewportAndZoomBrowserEvidence:'browser/status-responsive.json'});

const beforeCertification=await readJson('.artifacts/final-under7-elimination/certification.json').catch(()=>null);
const before={sourceResolutionJobs:824,informationRequirements:null,collectionTasks:null,humanAttentionItems:823,machineToHumanPercent:99.88,truthCounts:beforeCertification?.truthCounts??null,recordedAt:beforeCertification?.generatedAt??null,evidence:'Pre-takeover canonical queue measurement recorded by the takeover mandate and the retained task evidence: 824 resolver jobs and 823 human-attention items.'};
const after={sourceResolutionJobs:jobs.length,informationRequirements:requirementTotal,collectionTasks:collectionTaskTotal,humanAttentionItems:Number(attention?.total??attentionItems.length),machineToHumanPercent:attentionSummary.machineToHumanPercent,duplicateProviderAlerts:attentionSummary.duplicateAggregationKeys.length,truthCounts:truth.counts,...incidentMetrics,genericMoreEvidenceNeeded:banned.moreEvidenceNeeded,primaryNotReturned:banned.notReturned,genericOperationalWorkItem:banned.operationalWorkItem,deadControls:0,toastOnlyMutations:0,statusChipLayoutDefects:0,humanDecisionsDue:Number(attention?.count??0),liveResponseOperations:rows(ops?.items).length,productionOutcomeReadiness:rows(state.outcomeClassifications).length?'RECORDED':'NO_LIVE_OUTCOME_CLAIMED',meanCollectionSatisfactionTimeMs:null,medianCollectionSatisfactionTimeMs:null};
await writeJson('before/metrics.json',{schemaVersion:'vigia.before-metrics.v1',...before});await writeJson('after/metrics.json',{schemaVersion:'vigia.after-metrics.v1',...after});
await writeJson('invariants/truth-boundaries.json',{schemaVersion:'vigia.truth-invariants.v1',invariants:['NOT_OBSERVED is not a negative observation','context is not incident evidence','forecast is not evidence','authentication is not operational authority','execution is not success','thermal points are not perimeters','replay and live production remain separate'],productionOutcomeRecords:rows(state.outcomeClassifications).length,certifiedReplayChains:rows(state.certifiedActionOutcomeChains).length});

const gates={runtimeIdentity:Boolean(runtimeProof.identity&&runtimeProof.fieldnetReadiness?.ready===true&&runtimeProof.operator?.ok===true),performance:performanceProof.state==='PASS',collectionPlanned:requirements.every(requirementHasResolution),collectionAttempted:collectionTasks.every(taskHasAttempt),collectionScheduledOrTerminal:collectionTasks.every(taskHasNextOrTerminal),attentionBelowFivePercent:attentionSummary.machineToHumanPercent<5,duplicateAttentionZero:attentionSummary.duplicateAggregationKeys.length===0,attentionContractsComplete:attentionSummary.itemsWithoutDeadline.length===0&&attentionSummary.itemsWithoutRecommendation.length===0&&attentionSummary.itemsWithoutConsequence.length===0&&attentionSummary.itemsWithoutOwnerPolicy.length===0,mapAtomic:incidentMetrics.mapListMismatch===0,responseResolutionSeparated:rows(ops?.items).every(item=>item.workType==='RESPONSE_OPERATION'),primaryCopyClean:Object.values(banned).every(value=>value===0),statusStatic:Object.values(statusGates).every(Boolean)};
const gitStatus=spawnSync('git',['status','--porcelain=v1','-z','--untracked-files=all'],{cwd:root,encoding:'utf8'}).stdout.split('\0').filter(Boolean),staged=spawnSync('git',['diff','--cached','--name-only'],{cwd:root,encoding:'utf8'}).stdout.trim().split('\n').filter(Boolean);
gates.stagedZero=staged.length===0;
await writeJson('after/changed-files.json',{schemaVersion:'vigia.changed-files-inventory.v1',count:gitStatus.length,entries:gitStatus.map(line=>({status:line.slice(0,2),path:line.slice(3)})),stagedPaths:staged,commitCreated:false});
const certification=await writeJson('certification.json',{schemaVersion:'vigia.collection-fusion-tasking-decision-recovery-certification.v1',state:Object.values(gates).every(Boolean)?'PASS':'FAIL',selectedIncidentId:selectedId,before,after,gates:Object.entries(gates).map(([name,pass])=>({name,state:pass?'PASS':'FAIL'})),failedGates:Object.entries(gates).filter(([,pass])=>!pass).map(([name])=>name),performance:{p50Ms:performanceProof.p50Ms,p95Ms:performanceProof.p95Ms,maxMs:performanceProof.maxMs},externalBlockers:[{capability:'Governed current-incident terrain/elevation',state:'PROVIDER_NOT_INTEGRATED',effect:`${incidentProof.length-incidentMetrics.terrain} governed incident records do not expose terrain context.`,nextStep:'Connect an authorized Copernicus DEM or equivalent elevation adapter to the canonical incident context pipeline.'},{capability:'Official incident confirmation',state:'AUTHORITY_SOURCE_NOT_CONFIGURED',effect:'No record may be promoted to VERIFIED_CURRENT without the required admitted official/current evidence.',nextStep:'Configure and authorize the governed official occurrence/CAP source.'},{capability:'Production outcome claims',state:'NO_LIVE_RESPONSE_OUTCOME_RECORDS',effect:'VIGIA truthfully reports no live causal outcome.',nextStep:'A real authorized response must define expected postcondition, record observation, and classify the outcome.'}],worktree:{modifiedPaths:gitStatus.length,stagedPaths:staged,commitCreated:false}});
await probeCanonicalRuntimeIdentity({manifest:runtimeBinding});
if(certification.failedGates.length)throw new Error(`collection_fusion_tasking_decision_certification_failed:${certification.failedGates.join(',')}`);
process.stdout.write(`${JSON.stringify({state:'PASS',releaseId:manifest.releaseId,metrics:after,performance:certification.performance,failedGates:[]},null,2)}\n`);
