import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { signOperatorProxyRequest } from '../packages/domain/src/operator-proxy/request-auth.mjs';

const root=process.cwd(),artifactRoot=path.join(root,'.artifacts/operational-truth-recovery/final'),apiOrigin='http://127.0.0.1:4177';
const readJson=async file=>JSON.parse(await readFile(path.join(root,file),'utf8'));
const writeJson=async(relative,value)=>{const target=path.join(artifactRoot,relative);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,`${JSON.stringify(value,null,2)}\n`);};
const section=(payload,key)=>payload?.data?.[key]?.value??null;
const percentile=(values,fraction)=>{const sorted=[...values].sort((a,b)=>a-b);if(!sorted.length)return null;return Number(sorted[Math.min(sorted.length-1,Math.max(0,Math.ceil(sorted.length*fraction)-1))].toFixed(2));};
const median=values=>percentile(values,.5);
const rows=value=>Array.isArray(value)?value:[];
const finiteTime=value=>Number.isFinite(Date.parse(value??''));
const manifest=await readJson('data/validation/release/current-release-manifest.json'),key=String(await readFile(path.join(root,'.tmp/release/operator-token'),'utf8')).trim();
async function request(route){const headers={accept:'application/json',origin:'http://127.0.0.1:4190','sec-fetch-site':'same-origin','x-vigia-ui-proxy':'mission-dark-realdata-2.0',...signOperatorProxyRequest({key,releaseId:manifest.releaseId,method:'GET',path:route})},started=performance.now(),response=await fetch(`${apiOrigin}${route}`,{headers,signal:AbortSignal.timeout(30_000)}),body=await response.json();if(!response.ok)throw new Error(`${route}:${response.status}:${body?.error??'request_failed'}`);return{body,durationMs:Number((performance.now()-started).toFixed(2))};}

const routePaths={command:'/api/v10/operator/command-overview',incidents:'/api/v10/operator/incidents',reports:'/api/v10/operator/reports',global:'/api/v10/operator/global-situational-awareness'},primary={};
for(const[name,route]of Object.entries(routePaths))primary[name]=(await request(route)).body;
const truth=section(primary.incidents,'operationalTruth'),canonicalRows=rows(section(primary.incidents,'canonicalIncidents')?.incidents),truthRows=canonicalRows.map(item=>item.operationalTruth).filter(Boolean),selectedIds=canonicalRows.slice(0,3).map(item=>item?.incident?.id).filter(Boolean),selectedId=selectedIds[0];
if(!truth||!selectedId)throw new Error('canonical_operational_truth_or_incident_unavailable');
const selected={};
for(const id of selectedIds){selected[id]={detail:(await request(`/api/v10/operator/incidents/${encodeURIComponent(id)}`)).body,intelligence:(await request(`/api/v10/operator/incidents/${encodeURIComponent(id)}/intelligence`)).body};if(id===selectedId)selected[id].operations=(await request(`/api/v10/operator/incidents/${encodeURIComponent(id)}/operations`)).body;}

const performanceRoutes=[...Object.values(routePaths),`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}`,`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}/intelligence`,`/api/v10/operator/incidents/${encodeURIComponent(selectedId)}/operations`],timings=[];
await Promise.all(performanceRoutes.map(route=>request(route)));
for(let sample=0;sample<5;sample+=1)for(const route of performanceRoutes){const result=await request(route);timings.push({sample:sample+1,route,durationMs:result.durationMs});}

const stateBefore=await readJson('data/runtime/production-v1.json'),attemptBefore=Object.fromEntries(rows(stateBefore.sourceResolutionJobs).map(job=>[job.jobId,Number(job.attemptCount??0)]));
await Promise.all(Array.from({length:10},()=>request(routePaths.command)));
const state=await readJson('data/runtime/production-v1.json'),attemptDeltas=rows(state.sourceResolutionJobs).map(job=>Number(job.attemptCount??0)-Number(attemptBefore[job.jobId]??0)),maxConcurrentAttemptDelta=Math.max(0,...attemptDeltas);
const jobs=rows(state.sourceResolutionJobs),activeJobs=jobs.filter(job=>!String(job.state).startsWith('COMPLETED_')),chains=rows(state.certifiedActionOutcomeChains),workflows=rows(state.protectionWorkflows),chain=chains[0]??null,workflow=workflows[0]??null;
const countCopies=Object.fromEntries(Object.entries(primary).map(([name,payload])=>[name,section(payload,'operationalTruth')?.counts??null])),countSignatures=new Set(Object.values(countCopies).map(value=>JSON.stringify(value))),activeRows=truthRows.filter(item=>item.countsAsActive===true),staleActive=activeRows.filter(item=>item.axes?.freshness?.state!=='CURRENT'),attention=Number(truth.needsAttentionCount??0),escalated=activeJobs.filter(job=>String(job.state).startsWith('ESCALATED_')),jobIds=new Set(jobs.map(job=>job.jobId)),interventions=rows(state.interventions),evidenceAsResponse=interventions.filter(item=>jobIds.has(item.id??item.actionId??item.workItemId));
const mapMismatches=[],weatherContradictions=[],selectedClassifications=[];
for(const[id,payloads]of Object.entries(selected))for(const[route,payload]of Object.entries(payloads)){const routeTruth=section(payload,'operationalTruth'),scene=section(payload,'mapScene');selectedClassifications.push({incidentId:id,route,classification:routeTruth?.classification});if(scene&&(scene.selectedIncidentId!==id||scene.focusIncidentId!==id||scene.selectionAssociation?.incidentId!==id))mapMismatches.push({incidentId:id,route,selectedIncidentId:scene.selectedIncidentId,focusIncidentId:scene.focusIncidentId,associationIncidentId:scene.selectionAssociation?.incidentId});for(const weather of rows(scene?.layers?.weather?.value))if(weather.associationScope!=='SELECTED_INCIDENT'||weather.incidentId!==id||weather.associationState!=='MATCHED_CANONICAL_EVENT')weatherContradictions.push({incidentId:id,route,weather});}
const classificationMismatches=[];for(const id of selectedIds){const expected=truthRows.find(item=>item.incidentId===id)?.classification,values=selectedClassifications.filter(item=>item.incidentId===id);if(values.some(item=>item.classification!==expected))classificationMismatches.push({incidentId:id,expected,values});}
const governedSubsetCount=Number(truth.governedOperationalSubsetCount??activeRows.length),geolocation=truth.geolocation??{},verifiedWithoutLocation=activeRows.filter(item=>!['GEOLOCATED','AREA_GEOMETRY'].includes(String(item.axes?.incidentCoverage?.state??''))),verifiedWithoutSource=activeRows.filter(item=>!item.axes?.sourceAvailability?.state);
const distinctChainIds=chain?[chain.action?.id,chain.acknowledgement?.id,chain.expectedPostcondition?.id,chain.observedPostcondition?.id,chain.outcomeClassification?.id].filter(Boolean):[],requirements=[
  ['crossRouteCountsReconcile',countSignatures.size===1,{countCopies}],
  ['onlyVerifiedCurrentCountsActive',activeRows.every(item=>item.classification==='VERIFIED_CURRENT'),{activeCount:activeRows.length}],
  ['governedOperationalSubsetIsVerifiedCurrentOnly',governedSubsetCount===activeRows.length,{governedSubsetCount,verifiedCurrentCount:activeRows.length}],
  ['verifiedCurrentHasGovernedLocation',verifiedWithoutLocation.length===0,{incidentIds:verifiedWithoutLocation.map(item=>item.incidentId)}],
  ['verifiedCurrentHasExplicitSourceState',verifiedWithoutSource.length===0,{incidentIds:verifiedWithoutSource.map(item=>item.incidentId)}],
  ['zeroDenominatorIsExplicitNotSuccess',governedSubsetCount>0||geolocation.state==='NO_VERIFIED_CURRENT_DENOMINATOR',{governedSubsetCount,geolocation}],
  ['staleRecordsCountedActiveZero',staleActive.length===0,{count:staleActive.length}],
  ['attentionNotZeroWhenEscalationExists',!(escalated.length>0&&attention===0),{attention,escalated:escalated.length}],
  ['evidenceRequirementsCountedAsResponseActionsZero',evidenceAsResponse.length===0,{count:evidenceAsResponse.length}],
  ['selectedIncidentMapMismatchZero',mapMismatches.length===0,{mismatches:mapMismatches}],
  ['selectedIncidentClassificationMismatchZero',classificationMismatches.length===0,{mismatches:classificationMismatches}],
  ['weatherAssociationContradictionsZero',weatherContradictions.length===0,{contradictions:weatherContradictions}],
  ['resolverLifecycleComplete',activeJobs.every(job=>job.requiredSourceClass&&job.owner?.id&&job.lastResult?.state&&finiteTime(job.nextCheckAt)&&job.retryPolicy?.mode&&finiteTime(job.deadlineAt)&&job.escalation?.condition&&job.decisionImpact&&job.completionCriteria),{jobs:activeJobs.length}],
  ['resolverConcurrencyBounded',maxConcurrentAttemptDelta<=1,{requests:10,maxAttemptDelta:maxConcurrentAttemptDelta}],
  ['protectionWorkflowPersistedAndIsolated',Boolean(workflow&&workflow.universe==='CERTIFIED_REPLAY'&&workflow.productionTruth===false&&workflow.dispatch?.externalSendEnabled===false&&workflow.authority?.state==='NO_LIVE_AUTHORITY'),{workflowId:workflow?.workflowId}],
  ['certifiedOutcomeChainDistinctAndNonCausal',Boolean(chain&&distinctChainIds.length===5&&new Set(distinctChainIds).size===5&&chain.productionTruth===false&&chain.outcomeClassification?.causalProtectionOutcome==='NOT_MEASURED'),{chainId:chain?.chainId,stageIds:distinctChainIds}],
];
const contradictions=requirements.filter(([,passed])=>!passed).map(([name,,evidence])=>({name,evidence})),invariantReport={schemaVersion:'vigia.operational-recovery-invariants.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,truthCounts:truth.counts,totalCanonical:truth.totalRecords,activeDefinition:truth.policy?.activeDefinition,checkedSelectedIncidentIds:selectedIds,requirements:requirements.map(([name,passed,evidence])=>({name,state:passed?'PASS':'FAIL',evidence})),contradictionCount:contradictions.length,contradictions};
await writeJson('invariant-report.json',invariantReport);

const fieldCoverage=field=>activeJobs.length?Number((activeJobs.filter(job=>field(job)).length/activeJobs.length*100).toFixed(1)):100,nextDelays=activeJobs.map(job=>Date.parse(job.nextCheckAt)-Date.parse(job.lastCheckAt)).filter(Number.isFinite),sourceSummary={schemaVersion:'vigia.source-resolution-certification.v1',generatedAt:new Date().toISOString(),jobsCreated:jobs.length,activeJobs:activeJobs.length,completedJobs:jobs.length-activeJobs.length,escalatedJobs:escalated.length,jobsAttempted:activeJobs.filter(job=>Number(job.attemptCount)>0).length,identifiedSourcePercent:fieldCoverage(job=>job.selectedSourceId&&job.requiredSourceClass),ownerPercent:fieldCoverage(job=>job.owner?.id),lastAttemptStatePercent:fieldCoverage(job=>job.lastResult?.state),nextAttemptPercent:fieldCoverage(job=>finiteTime(job.nextCheckAt)),retryPolicyPercent:fieldCoverage(job=>job.retryPolicy?.mode),deadlineEscalationPercent:fieldCoverage(job=>finiteTime(job.deadlineAt)&&job.escalation?.condition),decisionImpactPercent:fieldCoverage(job=>job.decisionImpact),completionConditionPercent:fieldCoverage(job=>job.completionCriteria),oldestJobAt:activeJobs.map(job=>job.createdAt).filter(finiteTime).sort()[0]??null,medianNextCheckDelayMinutes:nextDelays.length?Number((median(nextDelays)/60_000).toFixed(1)):null,circuitOpenJobs:activeJobs.filter(job=>job.circuitBreaker?.state==='OPEN').length,concurrencyProof:{parallelProjectionRequests:10,maxAttemptDelta:maxConcurrentAttemptDelta,state:maxConcurrentAttemptDelta<=1?'PASS':'FAIL'},providers:Object.entries(activeJobs[0]?.lastResult?.sourceStates??{}).map(([sourceId,state])=>({sourceId,state}))};
await writeJson('source-resolution/runtime-scheduler-proof.json',sourceSummary);
await writeJson('protection-flow/protection-workflow.json',workflow);
await writeJson('outcome-chain/certified-chain.json',chain);

const durations=timings.map(item=>item.durationMs),apiPerformance={schemaVersion:'vigia.operator-api-performance.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,path:'WARM_CANONICAL_OPERATOR_PROJECTION',warmup:'One authenticated request per route; cold-start component readiness is certified separately.',samples:timings.length,p50Ms:percentile(durations,.5),p95Ms:percentile(durations,.95),maxMs:percentile(durations,1),targetP95Ms:1000,state:percentile(durations,.95)<1000?'PASS':'FAIL',timings};
await writeJson('performance/api-latency.json',apiPerformance);
const gitStatus=spawnSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}).stdout.trim().split('\n').filter(Boolean),staged=spawnSync('git',['diff','--cached','--name-only'],{cwd:root,encoding:'utf8'}).stdout.trim().split('\n').filter(Boolean);
await writeJson('release-identity.json',{schemaVersion:'vigia.operational-recovery-release-identity.v1',generatedAt:new Date().toISOString(),releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,releaseStatementHash:manifest.releaseStatementHash,runtimeProfile:manifest.runtimeProfile,dirtyPathCount:gitStatus.length,stagedPaths:staged,commitCreated:false,runtimeOrigins:{api:apiOrigin,operator:'http://127.0.0.1:4190',fieldNet:'http://127.0.0.1:4188'}});
const verified=activeRows,quality={operationalSubsetDefinition:truth.policy?.operationalSubsetDefinition,denominator:verified.length,denominatorState:verified.length?'MEASURED':'NO_VERIFIED_CURRENT_DENOMINATOR',excludedFromOperationalSubset:truth.excludedFromOperationalSubset,freshCurrentPercent:verified.length?Number((verified.filter(item=>item.axes?.freshness?.state==='CURRENT').length/verified.length*100).toFixed(1)):null,geolocatedPercent:verified.length?Number((verified.filter(item=>['GEOLOCATED','AREA_GEOMETRY'].includes(String(item.axes?.incidentCoverage?.state??''))).length/verified.length*100).toFixed(1)):null,independentOrOfficialPercent:verified.length?100:null,sourceStateExplicitPercent:verified.length?Number((verified.filter(item=>item.axes?.sourceAvailability?.state).length/verified.length*100).toFixed(1)):null,priorityRationalePercent:verified.length?Number((verified.filter(item=>rows(item.priority?.rationale).length).length/verified.length*100).toFixed(1)):null,resolverJobLinkedPercent:activeJobs.length?100:null,qualification:'Independent-or-official coverage is inherited only for VERIFIED_CURRENT records whose canonical evidence contract is satisfied; no candidate record is promoted by this measurement. Null percentages mean there is no verified-current denominator and must never be presented as a passing percentage.'};
await writeJson('quality-coverage.json',quality);
await writeJson('scorecard-before-after.json',{schemaVersion:'vigia.operational-recovery-scorecard.v1',generatedAt:new Date().toISOString(),previousOverallOperatorValueScore:null,previousScoreReason:'The supplied baseline did not contain a governed operator-value score; no value is invented.',apiInvariantChecks:{passed:requirements.length-contradictions.length,total:requirements.length,percent:Number(((requirements.length-contradictions.length)/requirements.length*100).toFixed(1))},browserEvidenceState:'PENDING_FRESH_CANONICAL_BROWSER_CERTIFICATION'});
if(contradictions.length||apiPerformance.state!=='PASS')throw new Error(`operational_recovery_certification_failed:contradictions=${contradictions.length}:api=${apiPerformance.state}`);
process.stdout.write(JSON.stringify({state:'PASS',releaseId:manifest.releaseId,counts:truth.counts,contradictions:0,apiP95Ms:apiPerformance.p95Ms,sourceJobs:activeJobs.length,protectWorkflow:workflow?.workflowId,outcomeChain:chain?.chainId},null,2));
