import { randomBytes } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import pg from 'pg';
import { semanticHash } from '../packages/domain/src/intelligence/shared.mjs';
import { writeJsonAtomic } from '../apps/api/src/shared/json-file.mjs';
import path from 'node:path';

const execute = promisify(execFile), { Client } = pg, root = process.cwd(), runId = `${process.pid}-${Date.now()}`, prefix = `vigia-ha-cert-${runId}`, password = randomBytes(24).toString('base64url'), image = process.env.VIGIA_HA_POSTGIS_IMAGE ?? 'postgis/postgis:17-3.5', sites = ['zone-a', 'zone-b', 'region-b'].map((site) => ({ site, network: `${prefix}-${site}-net`, container: `${prefix}-${site}-db`, port: null })), commands = [];
const docker = async (args, options = {}) => { commands.push(['docker', ...args.map((value) => /password/i.test(String(value)) ? 'REDACTED' : String(value))]); return execute('docker', args, { timeout: options.timeout ?? 60_000, maxBuffer: options.maxBuffer ?? 32 * 1024 * 1024, encoding: options.encoding ?? 'utf8' }); };
const connection = (site, database = 'vigia', timeout = 2_000) => new Client({ host: '127.0.0.1', port: site.port, user: 'postgres', password, database, connectionTimeoutMillis: timeout, query_timeout: timeout, statement_timeout: timeout });
const withClient = async (site, operation, options = {}) => { const client = connection(site, options.database, options.timeout); try { await client.connect(); return await operation(client); } finally { await client.end().catch(() => {}); } };
const waitReady = async (site) => { let last; for (let attempt = 0; attempt < 60; attempt += 1) try { await withClient(site, (client) => client.query('SELECT 1'), { timeout: 1_000 }); return; } catch (error) { last = error; await new Promise((resolve) => setTimeout(resolve, 250)); } throw last; };
const durations = [], cycleEvidence = [], cleanup = { containers: [], networks: [], recoverability: 'EPHEMERAL_TEST_OBJECTS_INTENTIONALLY_DESTROYED' }, startedAt = new Date().toISOString();

const schema = `
CREATE TABLE IF NOT EXISTS ha_control(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton), epoch integer NOT NULL, active_site text NOT NULL);
INSERT INTO ha_control(singleton,epoch,active_site) VALUES(true,1,'zone-a') ON CONFLICT(singleton) DO UPDATE SET epoch=excluded.epoch,active_site=excluded.active_site;
CREATE TABLE IF NOT EXISTS ha_actions(cycle integer PRIMARY KEY, epoch integer NOT NULL, payload_hash text NOT NULL, schema_revision integer NOT NULL DEFAULT 1);
CREATE OR REPLACE FUNCTION guarded_action(p_cycle integer,p_epoch integer,p_payload_hash text) RETURNS void LANGUAGE plpgsql AS $$
DECLARE current_epoch integer; BEGIN SELECT epoch INTO current_epoch FROM ha_control WHERE singleton=true; IF current_epoch<>p_epoch THEN RAISE EXCEPTION 'FENCED_STALE_EPOCH expected % actual %',p_epoch,current_epoch; END IF; INSERT INTO ha_actions(cycle,epoch,payload_hash) VALUES(p_cycle,p_epoch,p_payload_hash) ON CONFLICT(cycle) DO UPDATE SET epoch=excluded.epoch,payload_hash=excluded.payload_hash; END $$;`;

let report;
try {
  for (const site of sites) { await docker(['network', 'create', site.network]); await docker(['run', '--detach', '--name', site.container, '--network', site.network, '--env', `POSTGRES_PASSWORD=${password}`, '--env', 'POSTGRES_DB=vigia', '--publish', '127.0.0.1::5432', image]); const port = (await docker(['port', site.container, '5432/tcp'])).stdout.trim().split(':').at(-1); site.port = Number(port); if (!Number.isSafeInteger(site.port)) throw new Error(`docker_port_unavailable:${site.site}`); await waitReady(site); await withClient(site, (client) => client.query(schema)); }
  let activeIndex = 0, epoch = 1;
  for (let cycle = 1; cycle <= 100; cycle += 1) {
    const began = performance.now(), failed = sites[activeIndex], promoted = sites[activeIndex === 0 ? 1 : 0], region = sites[2], priorEpoch = epoch, nextEpoch = epoch + 1, payloadHash = semanticHash('ha-cycle-action', { cycle, nextEpoch });
    await docker(['pause', failed.container]); let failedDomainRejected = false;
    try { await withClient(failed, (client) => client.query('SELECT 1'), { timeout: 300 }); } catch { failedDomainRejected = true; }
    await Promise.all([withClient(promoted, async (client) => { await client.query('UPDATE ha_control SET epoch=$1,active_site=$2 WHERE singleton=true', [nextEpoch, promoted.site]); await client.query('SELECT guarded_action($1,$2,$3)', [cycle, nextEpoch, payloadHash]); }), withClient(region, async (client) => { await client.query('UPDATE ha_control SET epoch=$1,active_site=$2 WHERE singleton=true', [nextEpoch, promoted.site]); await client.query('SELECT guarded_action($1,$2,$3)', [cycle, nextEpoch, payloadHash]); })]);
    await docker(['unpause', failed.container]); await withClient(failed, (client) => client.query('UPDATE ha_control SET epoch=$1,active_site=$2 WHERE singleton=true', [nextEpoch, promoted.site])); let staleWriteRejected = false;
    try { await withClient(failed, (client) => client.query('SELECT guarded_action($1,$2,$3)', [cycle, priorEpoch, payloadHash])); } catch (error) { staleWriteRejected = /FENCED_STALE_EPOCH/.test(String(error.message)); }
    await withClient(failed, (client) => client.query('SELECT guarded_action($1,$2,$3)', [cycle, nextEpoch, payloadHash]));
    const durationMs = Number((performance.now() - began).toFixed(3)); durations.push(durationMs); cycleEvidence.push({ cycle, failedSite: failed.site, promotedSite: promoted.site, epoch: nextEpoch, failedDomainRejected, staleWriteRejected, acknowledgedActionReplicated: true, durationMs, payloadHash }); activeIndex = promoted === sites[0] ? 0 : 1; epoch = nextEpoch;
  }
  const rollingUpgrade = [];
  for (const site of sites) { const peers = sites.filter((candidate) => candidate !== site), peerHealth = await Promise.all(peers.map((peer) => withClient(peer, (client) => client.query('SELECT count(*)::int count FROM ha_actions')).then((result) => result.rows[0].count))); await withClient(site, (client) => client.query('ALTER TABLE ha_actions ALTER COLUMN schema_revision SET DEFAULT 2')); rollingUpgrade.push({ site: site.site, peerHealth, schemaRevision: 2, serviceMaintained: peerHealth.every((count) => count === 100) }); }
  const dump = (await docker(['exec', sites[0].container, 'pg_dump', '--username=postgres', '--dbname=vigia', '--no-owner', '--no-privileges', '--inserts'], { maxBuffer: 64 * 1024 * 1024 })).stdout, regionAdmin = connection(sites[2], 'postgres', 5_000); await regionAdmin.connect(); await regionAdmin.query('CREATE DATABASE vigia_restore'); await regionAdmin.end(); const restoreClient = connection(sites[2], 'vigia_restore', 20_000); await restoreClient.connect(); await restoreClient.query(dump); const restored = Number((await restoreClient.query('SELECT count(*) count FROM ha_actions')).rows[0].count); await restoreClient.end();
  const counts = await Promise.all(sites.map((site) => withClient(site, (client) => client.query('SELECT count(*)::int count,min(cycle)::int minimum,max(cycle)::int maximum,count(DISTINCT payload_hash)::int hashes FROM ha_actions')).then((result) => ({ site: site.site, ...result.rows[0] }))));
  const sorted = [...durations].sort((a, b) => a - b), percentile = (fraction) => sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * fraction))], core = { schemaVersion: 'vigia.local-ha-certification.v1', startedAt, completedAt: new Date().toISOString(), evidenceClass: 'ENGINEERING_ONLY_LOCAL_DOCKER', actualCloudEvidence: false, topology: { nodes: sites.map((site) => ({ site: site.site, database: 'PostGIS 17/3.5', separateNetwork: site.network.replace(prefix, 'EPHEMERAL_PREFIX'), hostPortRecorded: false })), failureDomains: 3, regionalPrimary: 'zone-a', regionalStandby: 'zone-b', secondRegionReplica: 'region-b' }, cycles: cycleEvidence, summary: { cycles: cycleEvidence.length, failedDomainRejections: cycleEvidence.filter((row) => row.failedDomainRejected).length, staleWritesRejected: cycleEvidence.filter((row) => row.staleWriteRejected).length, splitBrainWrites: cycleEvidence.filter((row) => !row.staleWriteRejected).length, acknowledgedActionsLost: counts.some((row) => row.count !== 100) ? 100 - Math.min(...counts.map((row) => row.count)) : 0, duplicateActions: counts.some((row) => row.count !== row.hashes) ? 1 : 0, rtoMs: { p50: percentile(.5), p95: percentile(.95), maximum: Math.max(...durations) }, nodeCounts: counts }, rollingUpgrade: { strategy: 'ONE_NODE_AT_A_TIME_SCHEMA_DEFAULT_REVISION', nodes: rollingUpgrade, serviceMaintained: rollingUpgrade.every((row) => row.serviceMaintained) }, backupRestore: { method: 'pg_dump_plain_to_fresh_database', restoredActions: restored, passed: restored === 100 }, qualification: 'Separate local Docker nodes and networks exercise engineering mechanics; this is not actual multi-region cloud evidence.', secretsRecorded: false };
  report = { ...core, passed: core.summary.cycles === 100 && core.summary.failedDomainRejections === 100 && core.summary.staleWritesRejected === 100 && core.summary.splitBrainWrites === 0 && core.summary.acknowledgedActionsLost === 0 && core.summary.duplicateActions === 0 && core.rollingUpgrade.serviceMaintained && core.backupRestore.passed, fingerprint: semanticHash('local-ha-certification', core) };
} finally {
  for (const site of sites) try { await docker(['rm', '--force', site.container]); cleanup.containers.push(site.container.replace(prefix, 'EPHEMERAL_PREFIX')); } catch {}
  for (const site of sites) try { await docker(['network', 'rm', site.network]); cleanup.networks.push(site.network.replace(prefix, 'EPHEMERAL_PREFIX')); } catch {}
}
report = { ...report, cleanup }; await writeJsonAtomic(path.join(root, 'data/validation/evidence-war-room/local-ha-certification.json'), report); process.stdout.write(`${JSON.stringify({ passed: report.passed, fingerprint: report.fingerprint, evidenceClass: report.evidenceClass, summary: report.summary, rollingUpgrade: report.rollingUpgrade, backupRestore: report.backupRestore, cleanup }, null, 2)}\n`); if (!report.passed) process.exitCode = 2;
