#!/usr/bin/env node
import { loadConfig } from '../apps/api/src/config/env.mjs';
import { createForecastRuntime,doctorForecasting } from '../apps/api/src/modules/forecasting/index.mjs';
import { createRealityNetworkRuntime } from '../apps/api/src/modules/reality-network/index.mjs';
import { doctorRealityProviders } from '../apps/api/src/modules/reality-network/provider-doctor.mjs';

if(process.argv.includes('--help')){console.log('Usage: npm run demo:spread-forecast\nRuns provider and forecast doctors, then performs one bounded current-data shadow issue with no consequential execution.');process.exit(0);}
const config=loadConfig(),realityRuntime=await createRealityNetworkRuntime({config}),providerDoctor=await doctorRealityProviders({runtime:realityRuntime,config}),runtime=await createForecastRuntime({config}),forecastDoctor=await doctorForecasting({config,runner:runtime.runner,registry:runtime.registry}),report=await runtime.runOnce(),proof={schemaVersion:'vigia.spread-forecast-demo-proof.v1',runId:report.runId,runHash:report.runHash,doctors:{providers:providerDoctor.summary,forecast:forecastDoctor},incident:report.incident,inputPackage:{manifestHash:report.inputManifest.semanticHash,informationCutoff:report.inputManifest.informationCutoff,weatherMemberCount:report.inputManifest.weatherMembers.length,fuelDatasetAttached:Boolean(report.inputManifest.fuelDataset),terrainDatasetAttached:Boolean(report.inputManifest.terrainDataset)},applicability:report.applicability,assimilation:{state:report.assimilation.state,revisionCount:report.assimilation.revisionCount,latestObservedAt:report.assimilation.latestPerimeter?.observedAt??null,latestKnowledgeTime:report.assimilation.latestPerimeter?.knowledgeTime??null,observedProgression:report.assimilation.observedProgression,physicalObservationCount:report.assimilation.physicalObservationIds.length,contradictionCount:report.assimilation.contradictions.length,assimilationHash:report.assimilation.assimilationHash},forecast:{id:report.forecast.forecastId,state:report.forecast.state,epistemicType:report.forecast.epistemicType,evidenceEligible:report.forecast.evidenceEligible,authorityEligible:report.forecast.authorityEligible,horizons:report.forecast.horizons.map((item)=>item.hours),uncertainty:report.consumerSnapshot.uncertainty,abstention:report.forecast.abstention},impact:{possibleAssetExposures:report.impact.exposures,timeToExposureRanges:report.consumerSnapshot.timeToExposureRanges},replay:report.replay,physicalRunner:report.physicalRunner,policyInput:report.policyInput,shadow:report.shadow,persistedOutput:config.forecastReportFile,consumerContract:report.consumerSnapshot.schemaVersion};
console.log(JSON.stringify(proof,null,2));
if(!proof.replay.valid||proof.forecast.epistemicType!=='FORECAST'||proof.forecast.evidenceEligible!==false||proof.forecast.authorityEligible!==false||proof.shadow.externalActionsExecuted!==0)process.exitCode=1;
