#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCsv } from '../apps/api/src/shared/csv.mjs';
import { normalizeFirmsRows } from '../apps/api/src/modules/world/firms-normalizer.mjs';
import { assessThermalCandidateV4 } from '../packages/domain/src/thermal-candidate-policy.mjs';
import { thermalTrend } from '../packages/domain/src/fire-event-tracker.mjs';
import { buildThermalContextResolver } from '../packages/domain/src/thermal-site-context.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),directory=path.join(root,'data/validation/detection');
const corpusPath=path.join(directory,'portugal-2024-active-fire-corpus.json'),outputPath=path.join(directory,'portugal-2024-small-fire-opportunity.json');
const contextPath=path.join(root,'data/reference/portugal-thermal-context-v1.json');
const sources=[['data/replay/raw/nasa-firms/viirs-jpss1_2024_Portugal.csv','VIIRS_NOAA20_ARCHIVE'],['data/replay/raw/nasa-firms/viirs-snpp_2024_Portugal.csv','VIIRS_SNPP_ARCHIVE']];
const WINDOW_MS=12*3_600_000,NEIGHBOR_KM=150,SIGNAL_KM=3,sha=(value)=>createHash('sha256').update(String(value)).digest('hex'),ratio=(a,b)=>b?Number((a/b).toFixed(4)):null;
function distanceKm(a,b){const rad=Math.PI/180,dy=(b[1]-a[1])*111.32,dx=(b[0]-a[0])*111.32*Math.cos((a[1]+b[1])/2*rad);return Math.hypot(dx,dy);}
function lowerBound(rows,target){let lo=0,hi=rows.length;while(lo<hi){const mid=(lo+hi)>>1;if(rows[mid].time<target)lo=mid+1;else hi=mid;}return lo;}
function memory(rows,asOf){const causal=rows.filter((item)=>Date.parse(item.at)<=Date.parse(asOf)).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));if(!causal.length)return{observationCount:0,distinctObservationDays:0,durationHours:0,stationarityRadiusKm:null,frpP90Mw:null};const centroid=[causal.reduce((sum,item)=>sum+item.coordinate[0],0)/causal.length,causal.reduce((sum,item)=>sum+item.coordinate[1],0)/causal.length],frp=causal.map((item)=>Number(item.frpMw)).filter(Number.isFinite).sort((a,b)=>a-b);return{observationCount:causal.length,distinctObservationDays:new Set(causal.map((item)=>item.at.slice(0,10))).size,durationHours:(Date.parse(causal.at(-1).at)-Date.parse(causal[0].at))/3_600_000,stationarityRadiusKm:Math.max(...causal.map((item)=>distanceKm(centroid,item.coordinate))),frpP90Mw:frp[Math.min(frp.length-1,Math.ceil(frp.length*.9)-1)]??null};}
const active=JSON.parse(await readFile(corpusPath,'utf8')),contextBody=await readFile(contextPath),context=JSON.parse(contextBody),resolveContext=buildThermalContextResolver(context),raw=[];
for(const [relative,sourceKey] of sources){const body=await readFile(path.join(root,relative)),checksumSha256=sha(body);raw.push(...normalizeFirmsRows(parseCsv(body),sourceKey,{rawSourceProductId:relative,checksumSha256,providerProductId:path.basename(relative)}).map((item)=>({...item,time:Date.parse(item.observedAt)})));}
raw.sort((a,b)=>a.time-b.time);
const small=active.cases.filter((item)=>item.referenceLabel==='FIRE_POSITIVE'&&Number(item.burnedAreaHa)<10),cases=[];
for(const item of small){
  const alertMs=Date.parse(item.alertAt),start=lowerBound(raw,alertMs-WINDOW_MS),nearby=[];
  for(let index=start;index<raw.length&&raw[index].time<=alertMs+WINDOW_MS;index+=1)if(distanceKm(raw[index].coordinate,item.geometry.coordinates)<=NEIGHBOR_KM)nearby.push(raw[index]);
  const signal=(item.observations??[]).filter((observation)=>Math.abs(Date.parse(observation.at)-alertMs)<=WINDOW_MS&&distanceKm(observation.coordinate,item.geometry.coordinates)<=SIGNAL_KM);
  const decisionAt=signal.at(-1)?.at??item.alertAt,siteContext=resolveContext(item.geometry.coordinates),assessment=signal.length?assessThermalCandidateV4({observations:signal,thermal:thermalTrend(signal,{now:new Date(Date.parse(decisionAt)+300_000)}),thermalMemory:memory(item.observations??[],decisionAt),siteContext},{now:new Date(Date.parse(decisionAt)+300_000)}):null;
  const passProxy=nearby.length>0,retained=signal.length>0,accepted=Boolean(assessment?.qualifiesAsFireCandidate);
  const failureClass=!passProxy?'NO_NEARBY_PASS_PROXY':!retained?'PASS_PROXY_WITHOUT_RETAINED_SIGNAL':!accepted?'POLICY_REJECTION_GIVEN_RETAINED_SIGNAL':null;
  cases.push({caseId:item.caseId,burnedAreaHa:item.burnedAreaHa,region:item.region,alertAt:item.alertAt,coordinate:item.geometry.coordinates,observationOpportunity:{state:'UNRESOLVED_MISSING_GEOLOCATION_AND_CLOUD_MASK_GRANULES',geometryCoverage:null,viewGeometry:null,cloudUsability:null,pixelQuality:null,basis:'Detection-only FIRMS CSV does not retain the source granule footprint/geolocation array or cloud/quality mask at this reference coordinate.'},passProxy:{state:passProxy?'NEARBY_SAME_WINDOW_DETECTION_PRESENT':'NO_NEARBY_DETECTION',basis:passProxy?`At least one real archived VIIRS detection occurred within ${NEIGHBOR_KM} km during the fixed ±12 hour window. This is not product-level coverage at the fire coordinate.`:'No nearby detection is not evidence of no pass or no coverage.',nearbyDetectionCount:nearby.length,platforms:[...new Set(nearby.map((row)=>row.satellite??row.source))].sort(),firstNearbyAt:nearby[0]?.observedAt??null,lastNearbyAt:nearby.at(-1)?.observedAt??null},providerRetainedSignal:{present:retained,observationCount:signal.length,firstAt:signal[0]?.at??null,platforms:[...new Set(signal.map((row)=>row.satellite??row.source))].sort()},policy:{evaluated:retained,accepted,decision:assessment?.decision??null,policyVersion:assessment?.policyVersion??null,thresholdVersion:assessment?.thresholdVersion??null,siteContext},failureClass});
}
const proxy=cases.filter((item)=>item.passProxy.state==='NEARBY_SAME_WINDOW_DETECTION_PRESENT'),signal=cases.filter((item)=>item.providerRetainedSignal.present),proxySignal=proxy.filter((item)=>item.providerRetainedSignal.present),proxyAccepted=proxy.filter((item)=>item.policy.accepted),failures=Object.fromEntries([...new Set(cases.map((item)=>item.failureClass).filter(Boolean))].sort().map((name)=>[name,cases.filter((item)=>item.failureClass===name).length]));
const platformPerformance=Object.fromEntries(['VIIRS NOAA-20','VIIRS S-NPP'].map((platform)=>{const retained=signal.filter((item)=>item.providerRetainedSignal.platforms.includes(platform)),accepted=retained.filter((item)=>item.policy.accepted);return[platform,{retainedSignals:retained.length,policyAccepted:accepted.length,policyRecallGivenRetainedSignal:ratio(accepted.length,retained.length),sensorOpportunityCount:null,sensorRecall:null}];}));
const sourceArtifacts=[];for(const[relative]of sources)sourceArtifacts.push({path:relative,checksumSha256:sha(await readFile(path.join(root,relative)))});sourceArtifacts.push({path:path.relative(root,contextPath),checksumSha256:sha(contextBody),datasetHash:context.datasetHash});
const artifact={schema:'vigia.small-fire-observation-opportunity.v2',generatedAt:new Date().toISOString(),population:{definition:'Official ICNF 2024 fires with burned area below 10 hectares',knownSmallFires:small.length},opportunityModel:{version:'viirs-product-opportunity-audit-v2',referenceWindow:'ICNF alert ±12 hours',neighborRadiusKm:NEIGHBOR_KM,signalMatchRadiusKm:SIGNAL_KM,requiredProductLevelEvidence:['VIIRS geolocation/footprint granule covering the reference coordinate and time','sensor/view geometry or scan position at the reference coordinate','cloud mask and applicable pixel quality at the reference coordinate'],availableProductLevelEvidence:[],missingArtifactProof:{firmsArchiveFields:['latitude','longitude','acq_date','acq_time','satellite','confidence','frp','type'],missing:['source granule identifier','swath footprint/geolocation array','scan angle at reference point','cloud mask at reference point','non-detection pixel quality'],conclusion:'The retained detection CSV cannot establish a denominator of actual usable sensor opportunities.'},proxyQualification:'A nearby positive pixel is retained only as a neighborhood pass proxy and is excluded from the sensor-opportunity denominator.',absenceClaim:'Missing retained signal remains unknown; it is never classified as a sensor miss without product-level opportunity evidence.'},results:{productLevelOpportunityProven:0,productLevelOpportunityUnresolved:small.length,opportunityProvenByProxy:proxy.length,opportunityUnresolved:small.length,observationCoverageLowerBound:null,neighborPassProxyShare:ratio(proxy.length,small.length),providerRetainedSignalAllCases:signal.length,providerRetainedSignalGivenPassProxy:proxySignal.length,providerPipelineSignalRecallGivenPassProxy:ratio(proxySignal.length,proxy.length),policyAcceptedGivenPassProxy:proxyAccepted.length,endToEndRecallGivenPassProxy:ratio(proxyAccepted.length,proxy.length),policyAcceptedGivenRetainedSignal:cases.filter((item)=>item.providerRetainedSignal.present&&item.policy.accepted).length,policyRecallGivenRetainedSignal:ratio(cases.filter((item)=>item.providerRetainedSignal.present&&item.policy.accepted).length,signal.length),pureSensorRecall:null,pureSensorRecallQualification:'UNMEASURED: zero cases have the geolocation, view-geometry, cloud and pixel-quality artifacts required for a valid sensor-opportunity denominator.',sourceSpecific:platformPerformance},failureTaxonomy:failures,sourceArtifacts,cases};
artifact.evidenceHash=`sha256:${sha(JSON.stringify(artifact))}`;
await writeFile(outputPath,`${JSON.stringify(artifact)}\n`);
console.log(JSON.stringify({outputPath,evidenceHash:artifact.evidenceHash,population:artifact.population,opportunityModel:artifact.opportunityModel,results:artifact.results,failureTaxonomy:artifact.failureTaxonomy},null,2));
