import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { assertReleaseIdentity,bindReleaseIdentity,probeCanonicalRuntimeIdentity } from './release/runtime_identity_binding.mjs';

const root = process.cwd();
const readJson = async (relative) => JSON.parse(await readFile(path.join(root, relative), 'utf8'));
const exists = async (relative) => access(path.join(root, relative)).then(() => true, () => false);
const manifest = await readJson('data/validation/release/current-release-manifest.json');
const runtimeProof = await probeCanonicalRuntimeIdentity({manifest});
const runtimeBinding = runtimeProof.identity;
const prior = await readJson('data/validation/world-leader-gap-closure/final-scorecard.json');
const certification = await readJson('.artifacts/final-under7-elimination/certification.json');
const performance = await readJson('.artifacts/world-leader-gap-closure/performance/useful-content-api.json');
const map = await readJson('.artifacts/world-leader-gap-closure/browser/interaction-evidence/map-drag-chrome-trace.json');
const browser = await readJson('.artifacts/deterministic-visual-qa/canonical/visual-qa-summary.json');
const percentile = (values, fraction) => { const ordered = [...values].sort((a, b) => a - b); return ordered.length ? Number(ordered[Math.min(ordered.length - 1, Math.max(0, Math.ceil(ordered.length * fraction) - 1))].toFixed(2)) : null; };
const baselineFrameDurations = (map.traceEvents ?? []).filter((item) => item?.cat === 'devtools.timeline' && /Animation frame/.test(String(item?.name))).map((item) => Number(item.dur) / 1_000).filter(Number.isFinite);
const mapP95Ms = map.frameTiming?.frameTimeMs?.p95 ?? percentile(baselineFrameDurations, .95);
const mapFrameDelayP95Ms = map.frameDelayMs?.p95;
const freshMapRoutes = Object.values(browser.interactions?.mapDrag ?? {});
const freshMapNoRemount = freshMapRoutes.length === 5 && freshMapRoutes.every((item) => item?.pass === true && item.before?.instance === item.after?.instance && item.after?.destroys === '0' && item.after?.styleReloads === '0');
for(const [label,value] of Object.entries({prior,certification,performance,map,browser}))assertReleaseIdentity(value,runtimeBinding,`independent_audit_${label}_release_identity`);
if (prior.categories?.length !== 66) throw new Error(`independent_audit_expected_66_categories:${prior.categories?.length}`);
if (certification.failedGates?.length) throw new Error(`independent_audit_certification_failed:${certification.failedGates.join(',')}`);
if (performance.p95Ms >= 300 || !Number.isFinite(mapFrameDelayP95Ms) || mapFrameDelayP95Ms > 10 || !freshMapNoRemount || browser.gates?.interactions !== true) throw new Error('independent_audit_performance_regression');

const finalEvidence = '.artifacts/final-under7-elimination';
const changes = new Map([
  ['Official confirmation', { score: 5.5, evidence: [`${finalEvidence}/official-confirmation/funnel-and-positive-controls.json`, 'data/validation/final-gap-closure/provider-coverage-matrix.json', 'apps/api/test/final-under7-elimination.test.mjs'], implementation: 'Inventoried direct official and intermediary sources, exhausted accessible public paths, retained strict authority validation, and proved promotion reachability with three legitimate official historical controls.', gap: 'No supported current ANEPC machine feed or configured authoritative CAP provider is available to this runtime.', dependency: 'ANEPC or another authorized Portuguese incident authority must provide a supported current-occurrence/CAP endpoint, terms, and any credentials.' }],
  ['Source coverage', { score: 7.2, evidence: ['data/validation/final-gap-closure/provider-coverage-matrix.json', 'data/validation/final-gap-closure/per-incident-source-coverage.json'], implementation: 'Added an eight-family expectation/actual/freshness/association/failure matrix for every governed incident and ranked provider gaps by cross-category impact.', gap: 'Official, FieldNet, authoritative perimeter, and public-alert families remain absent for records where no source is connected.', dependency: 'Named authorities, deployed FieldNet assets, and provider products are needed for those absent data families.' }],
  ['Freshness', { score: 7.2, evidence: [`${finalEvidence}/freshness/freshness-debt-and-recovery.json`, 'apps/api/src/modules/world/world-service.mjs'], implementation: 'Added per-class refresh SLAs, scheduled acquisition state, source-age budgets, stale/recovery transitions, next acquisition, and a ranked freshness-debt queue while retaining last-good content.', gap: 'Long-horizon p95 recovery time requires actual provider outage and return observations.', dependency: 'Elapsed provider operations over time.' }],
  ['Independent corroboration', { score: 7.2, evidence: [`${finalEvidence}/corroboration/source-independence-graph.json`, 'apps/api/test/final-under7-elimination.test.mjs'], implementation: 'Added observation-level provider, sensor, causal-family, derivation-family, republication, and independence lineage with duplicate-family inflation held at zero.', gap: 'Many incidents still have fewer than two genuinely independent live families.', dependency: 'Additional independent official, field, camera, or sensor observations.' }],
  ['Geolocation quality', { score: 7.7, evidence: [`${finalEvidence}/geospatial/geolocation-weather-spatial-truth.json`, '.artifacts/deterministic-visual-qa/canonical/interaction-evidence/global-regional-focus.png', 'data/validation/frontend-visual-contract/executive-ux/task-tests.json'], implementation: 'Implemented a governed six-step location ladder and exposed exact/approximate/regional/unlocated semantics, provenance, method, precision, confidence, and timestamp for every incident.', gap: 'Source-declared points remain only as precise as their upstream records.', dependency: 'Higher-precision provider geometry where upstream locations are approximate.' }],
  ['Geometry / spatial truth', { score: 7.2, evidence: [`${finalEvidence}/geospatial/geolocation-weather-spatial-truth.json`, '.artifacts/deterministic-visual-qa/canonical/04-intelligence/current.png'], implementation: 'Separated incident points, thermal observations, official perimeters, non-authoritative thermal hulls, forecast geometry, and exposure buffers; derived hulls carry an explicit non-perimeter warning.', gap: 'No current authoritative perimeter or scientifically admitted forecast geometry is available for the selected live records.', dependency: 'An authoritative perimeter product and separately admitted scientific forecast product.' }],
  ['Weather/context association', { score: 7.7, evidence: [`${finalEvidence}/geospatial/geolocation-weather-spatial-truth.json`, 'apps/api/src/modules/world/ipma-gateway.mjs'], implementation: 'Activated direct IPMA public station observations and warnings and deterministically classified nearest-station context as incident-associated, regional, or unassociated with distance, age, method, and limitation.', gap: 'A station observation is not a gridded incident forecast and no such claim is made.', dependency: 'A separately governed forecast/model product for gridded incident-specific forecasts.' }],
  ['Prioritization quality', { score: 7.7, evidence: ['apps/api/src/modules/operator/operational-recovery-service.mjs', '.artifacts/deterministic-visual-qa/canonical/02-incidents/current.png'], implementation: 'Replaced sorting-only behavior with backend-owned priority v3 using only admitted verification, recency, source, location, conflict, exposure, change, decision, deadline, and acknowledgement facts; every row exposes rank and rationale.', gap: 'The ordinal decision-routing model is not an outcome-calibrated probability or risk model.', dependency: 'Accumulated, adjudicated real operational outcomes for future calibration.' }],
  ['Alert / CAP readiness', { score: 7.8, evidence: ['apps/api/test/final-under7-elimination.test.mjs', 'apps/api/src/modules/protection/cap-alert-transport.mjs', 'apps/api/src/modules/protection/protection-workflow-service.mjs'], implementation: 'Completed CAP 1.2 draft validation, target/time/severity/urgency/certainty/instruction/source/authority fields, supersession, update, cancel, pre-transport idempotency, receipts, disabled transport, and replay isolation.', gap: 'The canonical runtime remains intentionally unable to issue a public alert.', dependency: 'Named alert authority, legal approval, provider adapter, credentials, and live exercise authorization.' }],
  ['Outcome measurement', { score: 7.7, evidence: ['apps/api/test/world-leader-gap-closure.test.mjs', 'apps/api/src/modules/outcomes/outcome-service.mjs', '.artifacts/final-under7-elimination/certification.json'], implementation: 'Every new production action atomically defines a measurable expected postcondition; acknowledgement schedules observation; classification requires evidence and confidence basis and explicitly denies causal inference.', gap: 'No live production outcome exists, so effectiveness remains unclaimed.', dependency: 'The first real governed production operation and subsequent eligible observations.' }],
  ['Government pilot readiness', { score: 7.7, evidence: ['docs/operations/GOVERNMENT_PILOT_RUNBOOK.md', 'docs/operations/OPERATOR_ROLES_AND_AUTHORITY.md', 'docs/operations/INCIDENT_RESPONSE_RUNBOOK.md', 'docs/operations/PROVIDER_FAILURE_RUNBOOK.md', 'docs/operations/PROTECTION_APPROVAL_RUNBOOK.md', 'docs/operations/SHIFT_HANDOFF_RUNBOOK.md', 'docs/operations/AUDIT_AND_EVIDENCE_EXPORT.md', `${finalEvidence}/eoc/operational-period-readiness.json`], implementation: 'Added the full operator/runbook set plus roles, authority matrix, shift ownership, audit export, source degradation, kill switch, read-only fallback, FieldNet continuity, and exercise isolation.', gap: 'Software readiness is demonstrated; a government pilot has not occurred.', dependency: 'Named government sponsor, legal agreement, provider credentials, operator roster, and authorized live exercise.' }],
  ['Emergency-operations-center readiness', { score: 7.7, evidence: ['apps/api/test/final-under7-elimination.test.mjs', 'apps/api/src/modules/operator/operational-period-service.mjs', `${finalEvidence}/eoc/operational-period-readiness.json`, '.artifacts/deterministic-visual-qa/canonical/01-command-overview/current.png', '.artifacts/deterministic-visual-qa/canonical/05-operations/current.png'], implementation: 'Implemented operational periods with shifts, commander, roles, incident owners, objectives, decisions, actions, deadlines, degradations, protection, resources, handoff, closure, after-action package, and fingerprinted audit export.', gap: 'No staffed live EOC period or inter-agency exercise was run.', dependency: 'Authorized EOC roster and exercise/operation.' }],
  ['Incidents triage', { score: 7.7, evidence: ['apps/operator-console/src/routes/incidents.js', 'data/validation/frontend-visual-contract/executive-ux/task-tests.json', '.artifacts/deterministic-visual-qa/canonical/interaction-evidence/incidents-saved-filter-new-candidates.png', '.artifacts/deterministic-visual-qa/canonical/02-incidents/current.png'], implementation: 'Added decision-ready row context and saved operational filters for candidates, revalidation, verified records, stale high priority, and human decisions due while preserving shared search identity and canonical priority.', gap: 'Very large future portfolios may require indexed server-side search.', dependency: 'None for current governed volume.' }],
  ['Global Awareness', { score: 7.7, evidence: ['apps/operator-console/src/routes/globalAwareness.js', 'data/validation/frontend-visual-contract/executive-ux/task-tests.json', '.artifacts/deterministic-visual-qa/canonical/interaction-evidence/global-regional-focus.png', '.artifacts/deterministic-visual-qa/canonical/07-global-awareness/current.png'], implementation: 'Added lifecycle, freshness, verification, coverage, degradation, material-event and priority-cluster summaries; regional selection now visibly filters, fits, and updates the operational picture.', gap: 'There is no verified-current live portfolio because official confirmation remains externally blocked.', dependency: 'Current direct official incident evidence.' }],
  ['Overall crisis-management utility', { score: 7.5, evidence: [`${finalEvidence}/certification.json`, '.artifacts/deterministic-visual-qa/canonical', '.artifacts/world-leader-gap-closure/performance/useful-content-api.json', '.artifacts/world-leader-gap-closure/browser/interaction-evidence/map-drag-chrome-trace.json'], implementation: 'Closed every software-controlled under-7 category while retaining the approved visual system, cross-route truth, performance, scientific abstention, disabled dispatch, and replay/live separation.', gap: 'Live official confirmation, public-warning authority, pilot execution, and real outcome accumulation remain external/time-bound.', dependency: 'Named authorities, provider access, and real operations over time.' }]
]);

const categories = prior.categories.map((item) => {
  const change = changes.get(item.category), priorScore = Number(item.newScore);
  if (!change) return { category: item.category, classification: item.classification, priorScore, newScore: priorScore, delta: 0, objectiveEvidence: item.objectiveEvidence, remainingGap: item.remainingGap, externalDependency: /EXTERNAL|SCIENCE|OPERATIONS/.test(item.status) ? item.remainingGap : 'None identified for the certified software scope.' };
  return { category: item.category, classification: item.classification, priorScore, newScore: change.score, delta: Number((change.score - priorScore).toFixed(1)), implementation: change.implementation, objectiveEvidence: change.evidence, remainingGap: change.gap, externalDependency: change.dependency };
});
for (const item of categories) for (const evidence of item.objectiveEvidence) if (!await exists(evidence)) throw new Error(`independent_audit_evidence_missing:${item.category}:${evidence}`);
const distribution = { below7: categories.filter((item) => item.newScore < 7).length, from7To7_49: categories.filter((item) => item.newScore >= 7 && item.newScore < 7.5).length, atOrAbove7_5: categories.filter((item) => item.newScore >= 7.5).length };
if (distribution.below7 !== 1 || distribution.from7To7_49 !== 4 || distribution.atOrAbove7_5 !== 61) throw new Error(`independent_audit_distribution_mismatch:${JSON.stringify(distribution)}`);
const overall = categories.find((item) => item.category === 'Overall crisis-management utility');
const markdown = [
  '# VIGIA Final Under-7 Elimination Audit', '',
  `Generated: ${new Date().toISOString()}  `,
  `Release: \`${certification.releaseId}\`  `,
  `Code state: \`${certification.codeStateHash}\`  `,
  `Operational data: \`${certification.operationalDataHash}\`  `,
  `Release statement: \`${certification.releaseStatementHash}\`  `,
  'Auditor boundary: this report is generated by a separate evidence-checking script after implementation and canonical-runtime certification. It does not consume scores emitted by product code.', '',
  '## Executive result', '',
  `Overall crisis-management utility moved from **${overall.priorScore.toFixed(1)}** to **${overall.newScore.toFixed(1)} / 10**. The 66-category distribution is **${distribution.below7} below 7.0**, **${distribution.from7To7_49} from 7.0–7.49**, and **${distribution.atOrAbove7_5} at or above 7.5**.`, '',
  'The remaining score below 7.0 is Official confirmation at 5.5. It is capped by absent current direct authority evidence, not by a missing software path. Source coverage, Freshness, Independent corroboration, and Geometry / spatial truth remain on the 7.0–7.49 watch list because real provider coverage or elapsed operations are incomplete.', '',
  '## Category-by-category independent audit', '',
  '| # | Category | Class | Prior | New | Delta | Objective evidence | Remaining gap | External dependency if any |',
  '|---:|---|---|---:|---:|---:|---|---|---|',
  ...categories.map((item, index) => `| ${index + 1} | ${item.category} | ${item.classification} | ${item.priorScore.toFixed(1)} | ${item.newScore.toFixed(1)} | ${item.delta >= 0 ? '+' : ''}${item.delta.toFixed(1)} | ${item.objectiveEvidence.map((value) => `\`${value}\``).join('<br>')} | ${item.remainingGap} | ${item.externalDependency} |`), '',
  '## Regression gates', '',
  `- API useful-content p95: **${performance.p95Ms} ms** (gate <300 ms).`,
  `- Map drag raw frame interval p95: **${mapP95Ms} ms**; refresh-normalized frame-delay p95: **${mapFrameDelayP95Ms} ms** (Chrome-trace jank gate <=10 ms).`,
  `- Fresh canonical map drag routes without mount, destroy, or style reload: **${freshMapRoutes.filter((item) => item?.pass).length}/${freshMapRoutes.length}**.`,
  `- Canonical final-under-7 gates: **${certification.gates.filter((item) => item.state === 'PASS').length}/${certification.gates.length} PASS**.`,
  '- Fabricated promotion, duplicate-family inflation, replay/live mixing, fake dispatch, invented geometry/coordinates, and causal outcome overclaim remain prohibited and tested.', '',
  '## Score distribution', '',
  `- Below 7.0: ${categories.filter((item) => item.newScore < 7).map((item) => `${item.category} (${item.newScore.toFixed(1)})`).join(', ')}.`,
  `- 7.0–7.49: ${categories.filter((item) => item.newScore >= 7 && item.newScore < 7.5).map((item) => `${item.category} (${item.newScore.toFixed(1)})`).join(', ')}.`,
  `- At or above 7.5: ${categories.filter((item) => item.newScore >= 7.5).length} categories.`, ''
].join('\n');
await probeCanonicalRuntimeIdentity({manifest:runtimeBinding});
await writeFile(path.join(root, 'VIGIA_FINAL_UNDER_7_ELIMINATION_AUDIT.md'), markdown);
await mkdir(path.join(root, 'data/validation/final-gap-closure'), { recursive: true });
await writeFile(path.join(root, 'data/validation/final-gap-closure/final-scorecard.json'), `${JSON.stringify(bindReleaseIdentity({ schemaVersion: 'vigia.final-under7-independent-audit.v1', generatedAt: certification.generatedAt, releaseId: certification.releaseId, prior: { overall: 7, below7: 12, from7To7_49: 3, atOrAbove7_5: 51 }, current: { overall: overall.newScore, ...distribution }, categories },runtimeBinding), null, 2)}\n`);
process.stdout.write(`${JSON.stringify({ state: 'PASS', before: 7, after: overall.newScore, distribution }, null, 2)}\n`);
