import { readFile,writeFile,mkdir } from 'node:fs/promises';
import pg from 'pg';
import { resolveLocalDatabaseUrl } from './local_database_secret.mjs';
import { WorldKnowledgeStore } from '../apps/api/src/modules/intelligence/world-knowledge-store.mjs';
import { WorldKnowledgeService } from '../apps/api/src/modules/intelligence/world-knowledge-service.mjs';
import { parseDocument } from '../apps/api/src/modules/intelligence/knowledge-sources.mjs';
import { hash,distanceKm,normalize } from '../packages/domain/src/intelligence/world-knowledge.mjs';

const output='data/reference/facility-intelligence';await mkdir(output,{recursive:true});
const context=JSON.parse(await readFile('data/reference/operational-proof/governed-incident-context.json','utf8')),archive=[...context.sources.openStreetMap.archives].filter(a=>a.purpose==='RESPONSE_FACILITIES').sort((a,b)=>b.retrievedAt.localeCompare(a.retrievedAt))[0],bytes=await readFile(archive.path);
if('sha256:'+hash(bytes)!==archive.sha256)throw new Error('governed_baseline_hash_mismatch');
const elements=JSON.parse(bytes).elements;
function classify(t){if(/departamento.*investiga.*penal|\bdiap\b/i.test(t.name??''))return 'public_prosecutor';return{hospital:'hospital',clinic:'health_center',doctors:'health_center',fire_station:'fire_station',police:'police_station',shelter:'shelter_generic',school:'school',townhall:'municipal_building'}[t.amenity]??(t.office==='government'?'other_public_facility':['fire_hydrant','water_tank'].includes(t.emergency)?'water_point':t.healthcare==='centre'?'health_center':null);}
const rows=elements.flatMap(e=>{const t=e.tags??{},type=classify(t),coordinate=[e.lon??e.center?.lon,e.lat??e.center?.lat];if(!type||!coordinate.every(Number.isFinite))return[];return[{id:`osm:${e.type}:${e.id}`,name:t.name??t.operator??'Unnamed '+type,canonicalName:t.name??t.operator??null,canonicalType:t.amenity==='police'?'police_station':type,coordinate,operator:t.operator,phone:t['contact:phone']??t.phone,email:t['contact:email']??t.email,website:t['contact:website']??t.website,address:{street:t['addr:street'],houseNumber:t['addr:housenumber'],postcode:t['addr:postcode'],locality:t['addr:city']??t['addr:town']??t['addr:village'],municipality:t['addr:municipality'],district:t['addr:district']},upstreamType:t.amenity,sourceTags:t}];});
const centres=[['Évora',[-7.908,38.571],34],['Coimbra',[-8.429,40.211],33],['Leiria',[-8.807,39.744],33]],selected=[];
for(const [area,point,count]of centres){const near=rows.map(r=>({...r,pilotArea:area,pilotDistanceKm:distanceKm(point,r.coordinate)})).filter(r=>r.pilotDistanceKm<30).sort((a,b)=>a.pilotDistanceKm-b.pilotDistanceKm||a.id.localeCompare(b.id));const kinds=[...new Set(near.map(r=>r.canonicalType))];let n=0;while(selected.filter(r=>r.pilotArea===area).length<count){let added=false;for(const type of kinds){const r=near.filter(r=>r.canonicalType===type)[n];if(r&&!selected.some(x=>x.id===r.id)&&selected.filter(x=>x.pilotArea===area).length<count){selected.push(r);added=true;}}if(!added)break;n++;}}
const failure=rows.find(r=>/departamento.*penal.*evora/.test(normalize(r.name)));if(failure&&!selected.some(r=>r.id===failure.id)){const index=selected.findLastIndex(r=>r.pilotArea==='Évora');selected[index]={...failure,pilotArea:'Évora',pilotDistanceKm:distanceKm(centres[0][1],failure.coordinate)};}
if(selected.length!==100)throw new Error('pilot_requires_100_real_records');
await writeFile(output+'/pilot-baseline.json',JSON.stringify({sourceArchive:archive,selection:'34 Évora, 33 Coimbra, 33 Leiria; diverse mapped types within 30 km of city reference points. Pilot area is not an inferred municipality.',records:selected},null,2));
const pool=new pg.Pool({connectionString:await resolveLocalDatabaseUrl(),max:2,statement_timeout:30000});
try{const store=new WorldKnowledgeStore({pool}),service=new WorldKnowledgeService({store});await service.initialize();
 const baseline=await service.seed(selected,{url:'https://www.openstreetmap.org/',provider:'OpenStreetMap contributors',authority:'OSM',watch:false,archivePath:archive.path,archiveSha256:archive.sha256,observedAt:archive.retrievedAt});
 const source={url:'https://www.ministeriopublico.pt/contactos',provider:'Ministério Público',authority:'OWNER',format:'HTML',adapter:'MP_CONTACT_DIRECTORY',watch:true,pollIntervalMs:86400000};
 const officialBytes=await readFile(output+'/raw/mp-contacts.html'),parsed=await parseDocument(officialBytes,source);const official=await service.ingest(officialBytes,source);
 const resolution=await service.resolveKnownEntities();const state=await store.read(),entities=await store.entities();const reviewedOfficial=parsed.records.filter(r=>/evora|coimbra|leiria/.test(normalize(r.canonicalName)));const originalIds=new Set(selected.map(raw=>entities.find(e=>!e.redirectTo&&e.externalIds.includes(raw.id))?.id));const expanded=[...selected,...reviewedOfficial.filter(r=>!originalIds.has(entities.find(e=>!e.redirectTo&&e.externalIds.includes(r.id))?.id)).map(r=>({...r,pilotArea:centres.find(([area])=>normalize(r.canonicalName).includes(normalize(area)))?.[0],selectionBasis:'ALL_REVIEWED_OFFICIAL_REGIONAL_DIRECTORY_RECORDS'}))];const pilot=expanded.map(raw=>{const entity=entities.find(e=>!e.redirectTo&&e.externalIds.includes(raw.id));return{raw,entity,review:{identity:entity?.canonicalName?'SOURCE_PUBLISHED':'UNRESOLVED',type:entity?.fields.canonicalType?.authority??'UNKNOWN',address:entity?.fields['address.street']?.authority??'NOT_RESOLVED_YET',coordinateQuality:entity?.location.locationQuality??'UNKNOWN',independentAuthorityVerified:entity?.fields.canonicalName?.authority==='OWNER'}};});
 const matchedOfficial=reviewedOfficial.map(r=>({sourceRecord:r,entity:entities.find(e=>e.externalIds.includes(r.id))}));
 const resolved=pilot.filter(p=>p.entity?.resolutionState==='resolved').length,ambiguous=pilot.filter(p=>p.entity?.resolutionState==='conflicting').length,unresolved=pilot.filter(p=>!p.entity?.canonicalName||!p.entity?.canonicalType).length;
 const metrics={total:pilot.length,originalMapCohort:100,officialRecordsAdded:pilot.length-100,types:Object.fromEntries([...new Set(pilot.map(p=>p.entity?.canonicalType))].map(type=>[type,pilot.filter(p=>p.entity?.canonicalType===type).length])),resolved,partiallyResolved:pilot.length-resolved-ambiguous-unresolved,ambiguous,unresolved,incorrect:pilot.filter(p=>/departamento.*penal/.test(normalize(p.raw.name))&&p.entity?.canonicalType!=='public_prosecutor').length,fieldCoverage:Object.fromEntries(['canonicalName','canonicalType','address.street','contact.phone','contact.website','operator'].map(k=>{const count=pilot.filter(p=>p.entity?.fields?.[k]?.value!=null).length;return[k,{count,percent:Math.round(count/pilot.length*10000)/100}]})),authoritativeReviewedAddressSet:{total:matchedOfficial.length,recovered:matchedOfficial.filter(r=>r.entity?.address.street).length,percent:matchedOfficial.length?100*matchedOfficial.filter(r=>r.entity?.address.street).length/matchedOfficial.length:0},incorrectReviewScope:'Known DIAP misclassification regression plus source-consistency checks; not an independent audit of every physical facility.',criticalFalseOperationalClaims:pilot.filter(p=>p.entity?.capabilities?.wildfireRefuge===true&&p.entity?.fields?.['capabilities.wildfireRefuge']?.authority==='OSM').length,limitations:['The original 100 difficult map records are retained. Every regional official-directory record is included, deduplicating the matched DIAP record.','Pilot OSM records are source-reviewed, not field-verified. A mapped type/location is probable until independently corroborated.','Authoritative address recovery denominator is every address-bearing official record in the reviewed three-city MP directory subset; it is not 90% authoritative coverage of the entire expanded pilot.','ANEPC directory acquisition was rejected by the source. No bypass used. No live capacity or official refuge designation inferred.'],baselineResult:baseline,officialResult:official};
 await writeFile(output+'/pilot-review.json',JSON.stringify({metrics,pilot,officialReview:matchedOfficial},null,2));await writeFile(output+'/source-manifest.json',JSON.stringify({sources:state.sources,documents:state.documents.map(({text,...d})=>d)},null,2));console.log(JSON.stringify({metrics:{...metrics,baselineResult:undefined,officialResult:undefined},failure:failure?service.decorate({id:failure.id,name:failure.name,kind:'POLICE',coordinate:failure.coordinate}):null},null,2));
}finally{await pool.end();}
