import { randomBytes } from 'node:crypto';
import { execFile } from 'node:child_process';
import { lstat, readFile, unlink } from 'node:fs/promises';
import { request as nodeHttpRequest } from 'node:http';
import net from 'node:net';
import path from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { loadConfig } from '../apps/api/src/config/env.mjs';
import { createOneTimeAdmission } from '../apps/operator-console/admission.mjs';
import { assertCanonicalIncidentIndex, selectCanonicalFieldNetIncident } from '../packages/domain/src/event-fabric/canonical-incident-index.mjs';
import { signOperatorProxyRequest } from '../packages/domain/src/operator-proxy/request-auth.mjs';
import { operatorOpen } from './operator_open.mjs';
import { runDbDoctor } from './db_doctor.mjs';
import { resolveLocalDatabaseUrl } from './local_database_secret.mjs';
import { reuseOrBuildReleaseManifest } from './release/build_release_manifest.mjs';
import { projectReleaseCertification } from './release/certification_semantics.mjs';
import { atomicWriteNoFollow, readFileNoFollow, verifyDirectoryChain } from './release/safe_artifact.mjs';
import { CANONICAL_INCIDENT_INDEX_MAX_BYTES, CANONICAL_STARTUP_SUMMARY_MAX_BYTES, LOCAL_RUNTIME_DESCRIPTOR_MAX_BYTES, RETAINED_FIELDNET_SCOPE_MAX_BYTES, readOptionalJson, readRequiredJson } from './local_runtime_json.mjs';

const exec=promisify(execFile),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),defaultRuntimeDir=path.join(root,'.tmp','runtime');
const defaultPorts=Object.freeze({api:4177,fieldnet:4188,operator:4190});
const localApiStartupTimeoutMs=Math.max(60_000,Math.min(180_000,Number(process.env.VIGIA_LOCAL_API_STARTUP_TIMEOUT_MS)||120_000));
const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
const relative=(file)=>path.relative(root,file);

function runtimePaths(runtimeDir=defaultRuntimeDir){return{runtimeDir,pointer:path.join(runtimeDir,'local-runtime.json'),failure:path.join(runtimeDir,'last-failure.json'),retainedScope:path.join(runtimeDir,'fieldnet-retained-scope.json'),orchestrationLog:path.join(runtimeDir,'orchestration.log'),controlToken:path.join(runtimeDir,'control-token'),operatorToken:path.join(root,'.tmp','release','operator-token'),operatorAccessToken:path.join(root,'.tmp','release','operator-console-access-token'),operatorPointer:path.join(root,'.tmp','operator-console-current.json')};}
const canonicalIncidentIndexFile=path.join(root,'data/runtime/canonical-incident-index.production.json');
// OPTIONAL only when absent: runtime pointer (STOPPED), prior failure (none),
// supervisor descriptors while polling, and retained FieldNet scope (first run).
// If any optional descriptor exists, invalid JSON, unsafe reads, or invalid
// schema are fatal. The canonical incident index is always REQUIRED.
const optionalJson=(file,label,fallback=null,validate=null,maxBytes=LOCAL_RUNTIME_DESCRIPTOR_MAX_BYTES)=>readOptionalJson(file,{root,maxBytes,label,fallback,validate});
const runtimePointerSchema=(value)=>{if(!value||value.schemaVersion!=='vigia.local-runtime.v2')throw new Error('local_runtime_pointer_schema_invalid');return value;};
const retainedScopeSchema=(value)=>{if(!value||value.schemaVersion!=='vigia.fieldnet-retained-scope.v1'||typeof value.incidentId!=='string')throw new Error('fieldnet_retained_scope_schema_invalid');return value;};
export async function resolveCanonicalFieldNetScope({indexFile=canonicalIncidentIndexFile,retainedScopeFile=null,projectRoot=root}={}){
  const index=await readRequiredJson(indexFile,{root:projectRoot,maxBytes:CANONICAL_INCIDENT_INDEX_MAX_BYTES,label:'canonical_incident_index_artifact',validate:assertCanonicalIncidentIndex}),prior=retainedScopeFile?await readOptionalJson(retainedScopeFile,{root:projectRoot,maxBytes:RETAINED_FIELDNET_SCOPE_MAX_BYTES,label:'fieldnet_retained_scope_descriptor',fallback:null,validate:retainedScopeSchema}):null,incidentId=selectCanonicalFieldNetIncident(index,{priorIncidentId:prior?.incidentId});
  if(!incidentId)throw Object.assign(new Error('canonical_fieldnet_incident_scope_unavailable'),{code:'FIELDNET_SCOPE_UNAVAILABLE',terminal:true});
  return{index,incidentId,retained:Boolean(prior?.incidentId===incidentId)};
}
async function command(program,args,{env={},timeout=180_000}={}){return exec(program,args,{cwd:root,env:{...process.env,...env},timeout,maxBuffer:64*1024*1024,encoding:'utf8'});}
function safeLoopbackUrl(value){const url=new URL(value);if(url.protocol!=='http:'||url.hostname!=='127.0.0.1'||url.username||url.password)throw new Error('local_runtime_probe_url_invalid');return url;}
async function loopbackRequest(value,{headers={},timeoutMs=4_000,maxBytes=2*1024*1024}={}){const url=safeLoopbackUrl(value);return new Promise((resolve)=>{let settled=false;const finish=(result)=>{if(settled)return;settled=true;resolve({...result,url:url.href});},request=nodeHttpRequest({protocol:url.protocol,hostname:url.hostname,port:url.port,path:`${url.pathname}${url.search}`,method:'GET',headers,agent:false},(response)=>{const chunks=[];let bytes=0;response.on('data',(chunk)=>{bytes+=chunk.length;if(bytes>maxBytes)request.destroy(new Error('local_runtime_response_too_large'));else chunks.push(chunk);});response.once('end',()=>finish({ok:Number(response.statusCode)>=200&&Number(response.statusCode)<300,status:Number(response.statusCode??0),headers:response.headers,buffer:Buffer.concat(chunks)}));response.once('error',(error)=>finish({ok:false,status:0,error:String(error?.message??error)}));});request.setTimeout(timeoutMs,()=>request.destroy(new Error('local_runtime_probe_timeout')));request.once('error',(error)=>finish({ok:false,status:0,error:String(error?.message??error),cause:String(error?.cause?.message??error?.cause??'')||null}));request.end();});}
async function fetchJson(url,{headers={},timeoutMs=4_000,maxBytes=2*1024*1024}={}){const response=await loopbackRequest(url,{headers:{accept:'application/json',...headers},timeoutMs,maxBytes});if(!response.buffer)return response;try{return{...response,body:response.buffer.length?JSON.parse(response.buffer.toString('utf8')):null};}catch(error){return{...response,ok:false,error:`local_runtime_response_invalid:${String(error?.message??error)}`};}}
async function listenerPids(port){try{const{stdout}=await command('lsof',[`-tiTCP:${port}`,'-sTCP:LISTEN'],{timeout:3_000});return stdout.split(/\s+/).map(Number).filter((pid)=>Number.isInteger(pid)&&pid>0);}catch{return[];}}
async function waitUntil(work,{timeoutMs=60_000,intervalMs=200,label='condition'}={}){const deadline=Date.now()+timeoutMs;let last;while(Date.now()<deadline){try{last=await work();if(last?.ready)return last;if(last?.terminal)throw Object.assign(new Error(`${label}_failed:${last.error??'terminal_failure'}`),{terminal:true});}catch(error){if(error?.terminal)throw error;last={error:String(error?.message??error)};}await sleep(intervalMs);}throw new Error(`${label}_timeout:${last?.error??JSON.stringify(last)}`);}
async function protectedSecret(file){const metadata=await lstat(file).catch(()=>null);if(!metadata?.isFile()||metadata.isSymbolicLink()||(metadata.mode&0o077)!==0||metadata.size<32||metadata.size>512)throw new Error(`local_runtime_secret_invalid:${relative(file)}`);return String(await readFileNoFollow(file,{root,maxBytes:512,encoding:'utf8'})).trim();}
async function writeSecret(file,value){await atomicWriteNoFollow(file,`${value}\n`,{root,mode:0o600});}
function componentFiles(runtimeDir,name){return{config:path.join(runtimeDir,`${name}.supervisor.json`),descriptor:path.join(runtimeDir,`${name}.process.json`),socket:path.join(runtimeDir,`${name}.sock`),log:path.join(runtimeDir,`${name}.log`)};}
async function startSupervised({runtimeDir,name,entry,args=[],cwd='.',env,controlTokenFile}){
  const files=componentFiles(runtimeDir,name),startupErrorFile=path.join(runtimeDir,'supervisor-startup-error.log'),config={schemaVersion:'vigia.local-supervisor-config.v1',name,entry,cwd,args,logFile:files.log,descriptorFile:files.descriptor,socketPath:files.socket,tokenFile:controlTokenFile};await unlink(startupErrorFile).catch(()=>undefined);await atomicWriteNoFollow(files.config,`${JSON.stringify(config,null,2)}\n`,{root,mode:0o600});
  const {spawn}=await import('node:child_process'),supervisor=spawn(process.execPath,[path.join(root,'scripts/local_process_supervisor.mjs'),files.config],{cwd:root,env,detached:true,stdio:'ignore'});await new Promise((resolve,reject)=>{supervisor.once('spawn',resolve);supervisor.once('error',reject);});supervisor.unref();
  // Secure descriptor writes launch the platform Python helper. On a cold macOS
  // host these can exceed eight seconds; this is process admission, not a map SLA.
  const result=await waitUntil(async()=>{const descriptor=await optionalJson(files.descriptor,`${name}_supervisor_descriptor`),socket=await lstat(files.socket).catch(()=>null),startupError=await readFile(startupErrorFile,'utf8').catch(()=>null);if(startupError)throw new Error(startupError.trim());return descriptor?.state==='RUNNING'&&socket?{ready:true,descriptor}:null;},{timeoutMs:30_000,label:`${name}_supervisor_start`});return{...files,...result.descriptor};
}
async function supervisorRequest(component,token,action){return new Promise((resolve,reject)=>{const socket=net.createConnection(component.socket);let value='',settled=false;const finish=(error,result)=>{if(settled)return;settled=true;socket.destroy();error?reject(error):resolve(result);};socket.setTimeout(7_000,()=>finish(new Error('local_supervisor_control_timeout')));socket.once('connect',()=>socket.end(`${JSON.stringify({token,action})}\n`));socket.on('data',(chunk)=>{value+=chunk;if(Buffer.byteLength(value)>16*1024)return finish(new Error('local_supervisor_control_response_too_large'));});socket.once('error',(error)=>finish(error));socket.once('close',()=>{try{const result=JSON.parse(value.trim());result.ok?finish(null,result):finish(new Error(result.error??'local_supervisor_control_failed'));}catch(error){finish(error);}});});}
async function waitPortFree(port){return waitUntil(async()=>({ready:(await listenerPids(port)).length===0}),{timeoutMs:10_000,label:`port_${port}_stop`});}
async function waitSupervisorStopped(component){return waitUntil(async()=>{const descriptor=await optionalJson(component.descriptor,`${component.name??'component'}_supervisor_descriptor`),socket=await lstat(component.socket).catch(()=>null);return{ready:descriptor?.state==='EXITED'&&descriptor?.supervisorPid===component.supervisorPid&&!socket,descriptor};},{timeoutMs:10_000,label:`${component.name??'component'}_supervisor_stop`});}
function processAlive(pid){if(!Number.isInteger(pid)||pid<=1)return false;try{process.kill(pid,0);return true;}catch(error){if(error?.code==='ESRCH')return false;throw error;}}
async function forceStopOwnedSupervisor(component){
  const descriptor=await readRequiredJson(component.descriptor,{root,maxBytes:LOCAL_RUNTIME_DESCRIPTOR_MAX_BYTES,label:`${component.name??'component'}_supervisor_descriptor`});
  if(descriptor?.state!=='RUNNING'||descriptor?.supervisorPid!==component.supervisorPid||descriptor?.childPid!==component.childPid||descriptor?.socketPath!==relative(component.socket))throw new Error(`${component.name??'component'}_supervisor_ownership_changed`);
  try{process.kill(component.supervisorPid,'SIGKILL');}catch(error){if(error?.code!=='ESRCH')throw error;}
  await waitUntil(async()=>({ready:!processAlive(component.supervisorPid)}),{timeoutMs:5_000,label:`${component.name??'component'}_supervisor_force_stop`});
  await unlink(component.socket).catch((error)=>{if(error?.code!=='ENOENT')throw error;});
}
function signedHeaders({token,releaseId,method='GET',pathname,operatorOrigin}){return{origin:operatorOrigin,'sec-fetch-site':'same-origin','x-vigia-ui-proxy':'mission-dark-realdata-2.0',...signOperatorProxyRequest({key:token,releaseId,method,path:pathname})};}
function releaseMatches(body,manifest){return Boolean(body&&body.releaseId===manifest.releaseId&&body.codeStateHash===manifest.codeStateHash&&body.operationalDataHash===manifest.operationalDataHash&&body.releaseStatementHash===manifest.releaseStatementHash);}
export function authoritativeFieldNetReady({componentOwnedReady=false,release=null,readiness=null,manifest=null,expectedIncidentId=null}={}){
  const releaseBody=release?.body??release,readyBody=readiness?.body??readiness,deployment=releaseBody?.schema?.deploymentIdentity,startup=releaseBody?.process?.startup,checks=readyBody?.checks??{};
  return Boolean(
    componentOwnedReady&&release?.ok!==false&&readiness?.ok!==false&&releaseMatches(releaseBody,manifest)&&
    releaseBody?.process?.servicesReady===true&&startup?.state==='services_ready'&&startup?.ready===true&&
    deployment?.state==='ready'&&releaseMatches(deployment,manifest)&&readyBody?.ready===true&&
    checks.liveness?.ready===true&&checks.listener?.ready===true&&checks.releaseIdentity?.ready===true&&
    checks.startup?.ready===true&&checks.deploymentIdentity?.ready===true&&checks.incidentScope?.ready===true&&
    checks.incidentScope?.incidentId===expectedIncidentId&&checks.storage?.ready===true
  );
}
export async function canonicalStartupSummary({apiOrigin,operatorOrigin,releaseId,operatorToken,expectedProjectionFingerprint=null,expectedIncidentCount=null}){const pathname='/api/v10/events',response=await fetchJson(`${apiOrigin}${pathname}`,{headers:signedHeaders({token:operatorToken,releaseId,pathname,operatorOrigin}),timeoutMs:15_000,maxBytes:CANONICAL_STARTUP_SUMMARY_MAX_BYTES}),inventory=response.body?.eventInventory,count=Number(inventory?.total),fingerprint=response.body?.projectionFingerprint??null,mismatch=response.ok&&((expectedProjectionFingerprint&&fingerprint!==expectedProjectionFingerprint)||(Number.isInteger(expectedIncidentCount)&&count!==expectedIncidentCount));return{response,count:Number.isInteger(count)?count:0,projectionFingerprint:fingerprint,responseBytes:response.buffer?.length??0,ready:response.ok&&!mismatch&&Number.isInteger(count)&&count>0&&fingerprint===expectedProjectionFingerprint,...(mismatch?{terminal:true,error:'canonical_startup_summary_projection_mismatch'}:{})};}
async function admittedMapState(operatorOrigin,accessToken){
  try{
    const admission=createOneTimeAdmission(accessToken),response=await loopbackRequest(`${operatorOrigin}/?admission=${encodeURIComponent(admission)}`,{timeoutMs:4_000,maxBytes:128*1024}),setCookie=Array.isArray(response.headers?.['set-cookie'])?response.headers['set-cookie'][0]:String(response.headers?.['set-cookie']??''),cookie=setCookie.split(';')[0];
    if(response.status!==303||!cookie)return{state:'UNAVAILABLE',loaded:0,failed:32,error:'operator_admission_failed'};
    const headers={cookie,origin:operatorOrigin,'sec-fetch-site':'same-origin',accept:'image/avif,image/webp,image/png,image/jpeg,image/*;q=0.8'},urls=[];
    for(const kind of ['imagery','labels'])for(let x=14;x<18;x+=1)for(let y=10;y<14;y+=1)urls.push(`${operatorOrigin}/backend/api/v1/basemap/${kind}/5/${x}/${y}`);
    const tiles=[];for(let offset=0;offset<urls.length;offset+=8){const batch=urls.slice(offset,offset+8).map(url=>loopbackRequest(url,{headers,timeoutMs:5_000,maxBytes:3*1024*1024}).then((tile)=>({ok:tile.ok&&String(tile.headers?.['content-type']??'').startsWith('image/'),sourceState:tile.headers?.['x-vigia-source-state']??null,status:tile.status})).catch((error)=>({ok:false,status:0,error:String(error?.message??error)})));tiles.push(...await Promise.all(batch));}
    const loaded=tiles.filter((tile)=>tile.ok).length,stale=tiles.filter((tile)=>tile.ok&&tile.sourceState==='stale').length,failed=tiles.length-loaded,state=loaded===tiles.length?(stale?'STALE_LAST_GOOD':'LIVE'):loaded?'DEGRADED_PARTIAL':'STRUCTURED_FALLBACK';
    return{state,loaded,failed,total:tiles.length,stale};
  }catch(error){return{state:'UNAVAILABLE',loaded:0,failed:32,total:32,error:String(error?.message??error)};}
}
function publicProbeUrl(value){const url=safeLoopbackUrl(value);if(url.search)url.search='?[REDACTED]';return url.href;}
async function orchestrationEvent(paths,event,{reset=false}={}){const line=`${JSON.stringify({at:new Date().toISOString(),...event})}\n`,prior=reset?'':await readFileNoFollow(paths.orchestrationLog,{root,maxBytes:128*1024,encoding:'utf8'}).catch(()=>''),next=Buffer.from(`${prior}${line}`),bounded=next.length<=128*1024?next:next.subarray(next.length-128*1024);await atomicWriteNoFollow(paths.orchestrationLog,bounded,{root,mode:0o600});}
async function startupFailure(paths,details){const value={schemaVersion:'vigia.local-runtime-failure.v2',failedAt:new Date().toISOString(),...details};await atomicWriteNoFollow(paths.failure,`${JSON.stringify(value,null,2)}\n`,{root,mode:0o600});return value;}
function failureMessage(value){return`${value.component} ${value.state}\n\nCause:\n${value.cause}\n\nRemediation:\n${value.remediation}\n\nLog:\n${value.log??'not available'}`;}

export async function localStatus({runtimeDir=defaultRuntimeDir,ports=defaultPorts,print=true}={}){
  const paths=runtimePaths(runtimeDir),pointer=await optionalJson(paths.pointer,'local_runtime_pointer',null,runtimePointerSchema),failure=await optionalJson(paths.failure,'local_runtime_failure_descriptor'),database=await runDbDoctor();
  if(!pointer){const listeners={};for(const[name,port]of Object.entries(ports))listeners[name]=await listenerPids(port);const unmanaged=Object.values(listeners).some((rows)=>rows.length),result={state:unmanaged?'UNMANAGED_LISTENER':'STOPPED',database,failure,listeners};if(print){console.log('VIGIA LOCAL\n');console.log(`Database       ${database.classification}`);console.log(`Central API    ${listeners.api.length?`UNMANAGED · PID ${listeners.api.join(', ')}`:'STOPPED'}`);console.log(`FieldNet       ${listeners.fieldnet.length?`UNMANAGED · PID ${listeners.fieldnet.join(', ')}`:'STOPPED'}`);console.log(`Operator       ${listeners.operator.length?`UNMANAGED · PID ${listeners.operator.join(', ')}`:'STOPPED'}`);if(failure)console.log(`\nLast failure\n${failureMessage(failure)}`);}return result;}
  const apiOrigin=`http://127.0.0.1:${ports.api}`,fieldOrigin=`http://127.0.0.1:${ports.fieldnet}`,operatorOrigin=`http://127.0.0.1:${ports.operator}`,accessToken=await protectedSecret(paths.operatorAccessToken).catch(()=>null),[apiRelease,apiHealth,fieldRelease,fieldHealth,fieldReady,operatorReady]=await Promise.all([fetchJson(`${apiOrigin}/api/v10/release`),fetchJson(`${apiOrigin}/api/v10/health`),fetchJson(`${fieldOrigin}/api/fieldnet/release`),fetchJson(`${fieldOrigin}/health`),fetchJson(`${fieldOrigin}/ready`),fetchJson(`${operatorOrigin}/__operator/ready`)]);
  const listenerState={};for(const[name,port]of Object.entries(ports))listenerState[name]=await listenerPids(port);
  const identityMatchesPointer=(body)=>body?.releaseId===pointer.releaseId&&body?.codeStateHash===pointer.codeStateHash&&body?.operationalDataHash===pointer.operationalDataHash&&body?.releaseStatementHash===pointer.releaseStatementHash;
  const finalCertification=await optionalJson(path.join(root,'.artifacts/final-under7-elimination/certification.json'),'final_under7_certification',null,null,2*1024*1024),releaseCertification=projectReleaseCertification({artifact:finalCertification,current:pointer}),certificationState=releaseCertification.state==='PASS'?'CERTIFIED_CURRENT':!finalCertification?'MISSING':'STALE_OR_FAILED';
  const componentReady=(name,response,identity=true)=>{const expected=pointer.components?.[name]?.childPid,listeners=listenerState[name]??[];return response.ok&&listeners.length===1&&listeners[0]===expected&&(!identity||identityMatchesPointer(response.body));};
  const states={api:componentReady('api',apiRelease)&&apiRelease.body?.process?.servicesReady===true&&apiHealth.ok&&apiHealth.body?.startup?.ready===true,fieldnet:authoritativeFieldNetReady({componentOwnedReady:componentReady('fieldnet',fieldRelease)&&fieldHealth.ok,release:fieldRelease,readiness:fieldReady,manifest:pointer,expectedIncidentId:pointer.governedFieldNetIncidentId}),operator:componentReady('operator',operatorReady)&&operatorReady.body?.ok===true&&operatorReady.body?.frontend==='operator-console'};
  let projection={ready:false,count:0,error:null};try{const index=await readRequiredJson(canonicalIncidentIndexFile,{root,maxBytes:CANONICAL_INCIDENT_INDEX_MAX_BYTES,label:'canonical_incident_index_artifact',validate:assertCanonicalIncidentIndex});if(!index.incidents.some((incident)=>incident.id===pointer.governedFieldNetIncidentId))throw new Error('canonical_fieldnet_incident_scope_no_longer_retained');projection=await canonicalStartupSummary({apiOrigin,operatorOrigin,releaseId:pointer.releaseId,operatorToken:await protectedSecret(paths.operatorToken),expectedProjectionFingerprint:index.projectionFingerprint,expectedIncidentCount:index.incidentCount});}catch(error){projection={ready:false,count:0,error:String(error?.message??error)};}
  const map=accessToken?await admittedMapState(operatorOrigin,accessToken):{state:'UNAVAILABLE',loaded:0,failed:32,total:32,error:'operator_access_token_unavailable'};
  const ready=database.classification==='READY'&&Object.values(states).every(Boolean)&&projection.ready,result={state:ready?'READY':'DEGRADED',database,pointer,states,listenerState,apiRelease,apiHealth,fieldRelease,fieldHealth,fieldReady,operatorReady,operatorBackend:apiHealth,projection,map,certificationState,releaseCertification,finalCertification,failure};
  if(print){console.log('VIGIA LOCAL\n');console.log(`Database       ${database.classification}`);console.log(`Central API    ${states.api?'READY':'FAILED'}`);console.log(`FieldNet       ${states.fieldnet?'READY':'FAILED'}`);console.log(`Operator       ${states.operator?'READY':'FAILED'}`);console.log(`\nRelease        ${pointer.releaseId}`);console.log(`Incident truth ${projection.ready?'READY':'UNAVAILABLE'} · ${projection.ready?projection.count:0} canonical`);console.log(`Operations     ${apiHealth.ok?'READY':'UNAVAILABLE'}`);console.log(`Map            ${map.state} · ${map.loaded}/${map.total??32} layers`);console.log(`Certification  ${certificationState}`);console.log(`\nOpen:\n${operatorOrigin}/#/command-overview`);if(!ready&&failure)console.log(`\nLast failure\n${failureMessage(failure)}`);}
  return result;
}

export async function localDown({runtimeDir=defaultRuntimeDir,ports=defaultPorts,print=true,preserveFailure=true}={}){
  const paths=runtimePaths(runtimeDir),pointer=await optionalJson(paths.pointer,'local_runtime_pointer',null,runtimePointerSchema);if(!pointer){const listeners={};for(const[name,port]of Object.entries(ports))listeners[name]=await listenerPids(port);const unmanaged=Object.entries(listeners).filter(([,pids])=>pids.length);if(unmanaged.length)throw new Error(`local_down_unmanaged_listeners:${unmanaged.map(([name,pids])=>`${name}:${pids.join(',')}`).join(';')}`);}if(pointer){const token=await protectedSecret(paths.controlToken).catch(()=>null);if(token)for(const name of ['operator','fieldnet','api']){const component=pointer.components?.[name];if(!component)continue;await supervisorRequest(component,token,'stop').catch((error)=>{if(error?.code!=='ENOENT'&&!/ENOENT|ECONNREFUSED/.test(String(error.message)))throw error;});}for(const component of Object.values(pointer.components??{})){try{await waitSupervisorStopped(component);}catch(error){if(!/_supervisor_stop_timeout:/.test(String(error?.message??error)))throw error;await forceStopOwnedSupervisor(component);}}for(const port of Object.values(ports))await waitPortFree(port);}
  const ownedFiles=pointer?[paths.pointer,paths.controlToken,paths.operatorToken,paths.operatorAccessToken,paths.operatorPointer]:[paths.pointer,paths.controlToken];for(const file of ownedFiles)await unlink(file).catch((error)=>{if(error?.code!=='ENOENT')throw error;});if(!preserveFailure)await unlink(paths.failure).catch(()=>undefined);if(print)console.log('VIGIA LOCAL STOPPED');return{state:'STOPPED'};
}

export async function localUp({runtimeDir=defaultRuntimeDir,ports=defaultPorts,print=true}={}){
  const paths=runtimePaths(runtimeDir),attemptId=`local-${Date.now().toString(36)}-${randomBytes(8).toString('hex')}`,attemptStartedAt=new Date().toISOString(),attemptOrigins={backend:`http://127.0.0.1:${ports.api}`,backendHealth:`http://127.0.0.1:${ports.api}/api/v10/health`,fieldnet:`http://127.0.0.1:${ports.fieldnet}`,operator:`http://127.0.0.1:${ports.operator}`,operatorIdentity:`http://127.0.0.1:${ports.operator}/__operator/ready`};let currentComponent='LOCAL RUNTIME',currentLog=relative(paths.orchestrationLog);await verifyDirectoryChain(root,runtimeDir);await unlink(paths.failure).catch((error)=>{if(error?.code!=='ENOENT')throw error;});await orchestrationEvent(paths,{event:'LOCAL_UP_ATTEMPT_STARTED',attemptId,attemptStartedAt,ports,...attemptOrigins});
  try{
    const existing=await localStatus({runtimeDir,ports,print:false});let manifest=null;if(existing.state==='READY'){manifest=await reuseOrBuildReleaseManifest();if(releaseMatches(existing.pointer,manifest)){const access=await protectedSecret(paths.operatorAccessToken),url=`http://127.0.0.1:${ports.operator}/?admission=${encodeURIComponent(createOneTimeAdmission(access))}`;await orchestrationEvent(paths,{event:'LOCAL_UP_REUSED',attemptId,releaseId:manifest.releaseId});if(print)console.log(`VIGIA LOCAL READY\n\n${url}`);return{...existing,url,reused:true,attemptId};}}
    if(existing.pointer)await localDown({runtimeDir,ports,print:false});for(const[name,port]of Object.entries(ports)){const listeners=await listenerPids(port);if(listeners.length){currentComponent=name.toUpperCase();const value=await startupFailure(paths,{attemptId,attemptStartedAt,component:currentComponent,state:'LISTENER_OWNERSHIP_FAILED',cause:`Port ${port} is already listening with unmanaged PID ${listeners.join(', ')}.`,remediation:'Stop the stale repository runtime through its owning session, then rerun npm run local:up.',log:currentLog});throw new Error(failureMessage(value));}}
    currentComponent='POSTGIS';let database=await runDbDoctor();if(database.classification!=='READY'){await command(process.execPath,['scripts/db_up.mjs'],{timeout:240_000});database=await runDbDoctor();}if(database.classification!=='READY')throw new Error(`POSTGIS STARTUP FAILED:${database.classification}`);
    currentComponent='CANONICAL RUNTIME DATA';const fieldNetScope=await resolveCanonicalFieldNetScope({retainedScopeFile:paths.retainedScope});let canonicalIndex=fieldNetScope.index;
    currentComponent='FIELDNET SCOPE';const governedIncidentId=fieldNetScope.incidentId;
    const databaseUrl=await resolveLocalDatabaseUrl();manifest??=await reuseOrBuildReleaseManifest();const apiOrigin=`http://127.0.0.1:${ports.api}`,fieldOrigin=`http://127.0.0.1:${ports.fieldnet}`,operatorOrigin=`http://127.0.0.1:${ports.operator}`,controlToken=randomBytes(32).toString('base64url'),operatorToken=randomBytes(32).toString('base64url'),operatorAccessToken=randomBytes(32).toString('base64url'),fieldControlKey=randomBytes(32).toString('base64url'),fieldCapacityTaskKey=randomBytes(32).toString('base64url'),fieldNodeKey=randomBytes(32).toString('base64url');
    await orchestrationEvent(paths,{event:'CANONICAL_PROBE_ORIGINS',attemptId,backend:apiOrigin,backendHealth:`${apiOrigin}/api/v10/health`,fieldnet:fieldOrigin,operator:operatorOrigin,operatorIdentity:`${operatorOrigin}/__operator/ready`});
    if(operatorToken===operatorAccessToken)throw new Error('local_operator_credentials_must_be_distinct');
    const secretsFile=process.env.VIGIA_SECRETS_FILE??path.join(process.env.HOME??'', '.config/vigia/secrets.env'),releaseEnv={VIGIA_DATABASE_URL:databaseUrl,HOST:'127.0.0.1',OPEN_BROWSER:'0',REQUEST_TIMEOUT_MS:'12000',VIGIA_RUNTIME_PROFILE:'local_shadow',VIGIA_LOCAL_OPERATOR_AUTOLOGIN:'1',VIGIA_OPERATOR_CONSOLE_ORIGIN:operatorOrigin,NODE_ENV:'development',VIGIA_RELEASE_ID:manifest.releaseId,VIGIA_CODE_STATE_HASH:manifest.codeStateHash,VIGIA_OPERATIONAL_DATA_HASH:manifest.operationalDataHash,VIGIA_APPROVED_RELEASE_STATEMENT_SHA256:manifest.releaseStatementHash,VIGIA_OPERATOR_TOKEN:operatorToken,VIGIA_SECRETS_FILE:secretsFile};
    const config=loadConfig({...process.env,...releaseEnv,PORT:String(ports.api)}),protectedState={firms:Boolean(config.firmsMapKey),cdse:Boolean(config.cdseAccessToken||(config.cdseUsername&&config.cdsePassword)),earthdata:Boolean(config.earthdataToken)};if(!Object.values(protectedState).every(Boolean))throw new Error(`protected_configuration_incomplete:FIRMS=${protectedState.firms}:CDSE=${protectedState.cdse}:EARTHDATA=${protectedState.earthdata}`);
    await Promise.all([writeSecret(paths.controlToken,controlToken),writeSecret(paths.operatorToken,operatorToken),writeSecret(paths.operatorAccessToken,operatorAccessToken)]);
    const fieldNodeId=`field-node:local:${manifest.releaseId}`,fieldCapacityTaskSocket=path.join(runtimeDir,'fn.sock'),registry=JSON.stringify({[fieldNodeId]:{key:fieldNodeKey,incidentIds:[governedIncidentId],capabilities:['fieldnet:sync','fieldnet:command-survival','fieldnet:capacity-task'],status:'active'}}),pointer={schemaVersion:'vigia.local-runtime.v2',state:'STARTING',attemptId,attemptStartedAt,certification:'LOCAL_REHEARSAL_UNSEALED',releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,releaseStatementHash:manifest.releaseStatementHash,projectionFingerprint:canonicalIndex.projectionFingerprint,incidentCount:canonicalIndex.incidentCount,ports,governedFieldNetIncidentId:governedIncidentId,startedAt:new Date().toISOString(),components:{}};await atomicWriteNoFollow(paths.pointer,`${JSON.stringify(pointer,null,2)}\n`,{root,mode:0o600});
    const savePointer=()=>atomicWriteNoFollow(paths.pointer,`${JSON.stringify(pointer,null,2)}\n`,{root,mode:0o600});
    currentComponent='CENTRAL API';const apiEnv={...process.env,...releaseEnv,PORT:String(ports.api),FIELDNET_CONTROL_KEY:'',FIELDNET_CONTROL_KEY_FILE:'',VIGIA_FIELDNET_NODE_REGISTRY_JSON:registry,VIGIA_FIELDNET_CAPACITY_TASK_SOCKET:fieldCapacityTaskSocket,VIGIA_FIELDNET_CAPACITY_TASK_KEY:fieldCapacityTaskKey,VIGIA_FIELDNET_CAPACITY_TASK_KEY_ID:'fieldnet-capacity-task-resolver',VIGIA_FIELDNET_CAPACITY_TASK_INCIDENT_SCOPES:governedIncidentId,VIGIA_FIELDNET_CAPACITY_TASK_NODE_ID:fieldNodeId};pointer.components.api=await startSupervised({runtimeDir,name:'api',entry:'apps/api/src/server.mjs',env:apiEnv,controlTokenFile:paths.controlToken});currentLog=relative(pointer.components.api.log);await savePointer();
    const apiReady=await waitUntil(async()=>{const [release,health]=await Promise.all([fetchJson(`${apiOrigin}/api/v10/release`),fetchJson(`${apiOrigin}/api/v10/health`)]),startup=health.body?.startup??null;if(release.body?.process?.startup?.state==='failed')return{ready:false,terminal:true,error:`${release.body.process.startup.error??'unknown_startup_failure'}:phase=${startup?.phase??'unknown'}`,releaseUrl:release.url,healthUrl:health.url};return{ready:release.ok&&health.ok&&releaseMatches(release.body,manifest)&&release.body?.process?.servicesReady===true&&startup?.ready===true,release:{ok:release.ok,status:release.status,url:release.url},health:{ok:health.ok,status:health.status,url:health.url,startupReady:startup?.ready===true,phase:startup?.phase??null,lastCompletedPhase:startup?.lastCompletedPhase??null}};},{timeoutMs:localApiStartupTimeoutMs,intervalMs:500,label:'central_api_services'});await orchestrationEvent(paths,{event:'BACKEND_READY',attemptId,releaseProbe:apiReady.release,healthProbe:apiReady.health});
    currentComponent='CANONICAL RUNTIME DATA';canonicalIndex=await readRequiredJson(canonicalIncidentIndexFile,{root,maxBytes:CANONICAL_INCIDENT_INDEX_MAX_BYTES,label:'canonical_incident_index_artifact',validate:assertCanonicalIncidentIndex});if(!canonicalIndex.incidents.some((incident)=>incident.id===governedIncidentId)){currentComponent='FIELDNET SCOPE';throw new Error('canonical_fieldnet_incident_scope_no_longer_retained');}const projection=await waitUntil(async()=>canonicalStartupSummary({apiOrigin,operatorOrigin,releaseId:manifest.releaseId,operatorToken,expectedProjectionFingerprint:canonicalIndex.projectionFingerprint,expectedIncidentCount:canonicalIndex.incidentCount}),{timeoutMs:60_000,label:'canonical_startup_summary'});pointer.projectionFingerprint=canonicalIndex.projectionFingerprint;pointer.incidentCount=canonicalIndex.incidentCount;await savePointer();
    currentComponent='FIELDNET';const fieldEnv={PATH:process.env.PATH??'/usr/bin:/bin',LANG:process.env.LANG??'C.UTF-8',TZ:process.env.TZ??'UTC',NODE_ENV:'development',VIGIA_RUNTIME_PROFILE:'local_shadow',VIGIA_RELEASE_ID:manifest.releaseId,VIGIA_CODE_STATE_HASH:manifest.codeStateHash,VIGIA_OPERATIONAL_DATA_HASH:manifest.operationalDataHash,VIGIA_APPROVED_RELEASE_STATEMENT_SHA256:manifest.releaseStatementHash,FIELDNET_CONTROL_KEY:fieldControlKey,FIELDNET_CONTROL_KEY_ID:'field-operator',FIELDNET_CAPACITY_TASK_KEY:fieldCapacityTaskKey,FIELDNET_CAPACITY_TASK_KEY_ID:'fieldnet-capacity-task-resolver',FIELDNET_CONTROL_SOCKET:fieldCapacityTaskSocket,FIELDNET_CONTROL_INCIDENT_SCOPES:governedIncidentId,FIELDNET_NODE_KEY:fieldNodeKey,FIELDNET_PORT:String(ports.fieldnet),FIELDNET_HOST:'127.0.0.1',FIELDNET_NODE_ID:fieldNodeId,FIELDNET_CENTRAL_URL:`${apiOrigin}/api/v10`,FIELDNET_DB_PATH:path.join(runtimeDir,`fieldnet-${manifest.releaseId}.sqlite`),FIELDNET_REQUEST_TIMEOUT_MS:'5000'};
    pointer.components.fieldnet=await startSupervised({runtimeDir,name:'fieldnet',entry:'apps/field-node/src/server.mjs',env:fieldEnv,controlTokenFile:paths.controlToken});currentLog=relative(pointer.components.fieldnet.log);await savePointer();const fieldnetReady=await waitUntil(async()=>{const [release,health,readiness]=await Promise.all([fetchJson(`${fieldOrigin}/api/fieldnet/release`),fetchJson(`${fieldOrigin}/health`),fetchJson(`${fieldOrigin}/ready`)]),componentOwnedReady=(await listenerPids(ports.fieldnet)).length===1&&(await listenerPids(ports.fieldnet))[0]===pointer.components.fieldnet.childPid;return{ready:authoritativeFieldNetReady({componentOwnedReady:componentOwnedReady&&health.ok,release,readiness,manifest,expectedIncidentId:governedIncidentId}),release:{ok:release.ok,status:release.status,url:release.url,servicesReady:release.body?.process?.servicesReady===true,startupReady:release.body?.process?.startup?.ready===true,deploymentIdentity:release.body?.schema?.deploymentIdentity?.state??null},health:{ok:health.ok,status:health.status,url:health.url},readiness:{ok:readiness.ok,status:readiness.status,url:readiness.url,ready:readiness.body?.ready===true,checks:readiness.body?.checks??null}};},{timeoutMs:20_000,label:'fieldnet_authoritative_readiness'});await orchestrationEvent(paths,{event:'FIELDNET_READY',attemptId,probe:fieldnetReady});
    currentComponent='OPERATOR';await command(process.execPath,['apps/operator-console/scripts/build.mjs'],{env:releaseEnv,timeout:180_000});const operatorEnv={PATH:process.env.PATH??'/usr/bin:/bin',LANG:process.env.LANG??'C.UTF-8',TZ:process.env.TZ??'UTC',HOST:'127.0.0.1',PORT:String(ports.operator),VIGIA_OPERATOR_PUBLIC_AUTHORITY:`127.0.0.1:${ports.operator}`,VIGIA_BACKEND_URL:apiOrigin,VIGIA_OPERATOR_STATIC_ROOT:'dist',VIGIA_OPERATOR_PROXY_KEY:operatorToken,VIGIA_OPERATOR_ACCESS_TOKEN:operatorAccessToken,VIGIA_RELEASE_ID:manifest.releaseId,VIGIA_CODE_STATE_HASH:manifest.codeStateHash,VIGIA_OPERATIONAL_DATA_HASH:manifest.operationalDataHash,VIGIA_APPROVED_RELEASE_STATEMENT_SHA256:manifest.releaseStatementHash};
    pointer.components.operator=await startSupervised({runtimeDir,name:'operator',entry:'apps/operator-console/server.mjs',cwd:'apps/operator-console',env:operatorEnv,controlTokenFile:paths.controlToken});currentLog=relative(pointer.components.operator.log);await savePointer();const operatorReady=await waitUntil(async()=>{const probe=await fetchJson(`${operatorOrigin}/__operator/ready`);return{ready:probe.ok&&probe.body?.ok===true&&probe.body?.frontend==='operator-console'&&releaseMatches(probe.body,manifest),operator:{ok:probe.ok,status:probe.status,url:probe.url,error:probe.error??null,frontend:probe.body?.frontend??null,releaseId:probe.body?.releaseId??null}};},{timeoutMs:30_000,label:'operator'});await orchestrationEvent(paths,{event:'OPERATOR_READY',attemptId,probe:operatorReady.operator});
    await atomicWriteNoFollow(paths.operatorPointer,`${JSON.stringify({schemaVersion:'vigia.operator-runtime-pointer.v1',origin:operatorOrigin,port:ports.operator,pid:pointer.components.operator.childPid,releaseId:manifest.releaseId,updatedAt:new Date().toISOString()})}\n`,{root,mode:0o600});await atomicWriteNoFollow(paths.retainedScope,`${JSON.stringify({schemaVersion:'vigia.fieldnet-retained-scope.v1',incidentId:governedIncidentId,projectionFingerprint:canonicalIndex.projectionFingerprint,selectedAt:new Date().toISOString()},null,2)}\n`,{root,mode:0o600});pointer.state='READY';pointer.readyAt=new Date().toISOString();pointer.incidentCount=projection.count;pointer.commandSummaryBytes=projection.responseBytes;await savePointer();await unlink(paths.failure).catch(()=>undefined);await orchestrationEvent(paths,{event:'LOCAL_UP_READY',attemptId,releaseId:manifest.releaseId,incidents:projection.count,commandSummaryBytes:projection.responseBytes});
    const url=`${operatorOrigin}/?admission=${encodeURIComponent(createOneTimeAdmission(operatorAccessToken))}`,result={state:'READY',releaseId:manifest.releaseId,certification:'LOCAL_REHEARSAL_UNSEALED',incidents:projection.count,governedFieldNetIncidentId:governedIncidentId,url,components:pointer.components,apiReady,operatorReady,attemptId};if(print)console.log(`VIGIA LOCAL READY\n\nDatabase       READY\nCentral API    READY\nFieldNet       READY\nOperator       READY\nRelease        ${manifest.releaseId}\nIncidents      ${projection.count}\nCertification  LOCAL_REHEARSAL_UNSEALED\n\n${url}`);return result;
  }catch(error){
    const message=String(error?.message??error).replace(/postgres(?:ql)?:\/\/[^\s/@:]+(?::[^\s/@]*)?@/gi,'postgresql://[REDACTED]@').replace(/\b(?:Bearer|Basic)\s+[A-Za-z0-9._~+/=-]+/gi,'[REDACTED CREDENTIAL]').replace(/([?&]admission=)[^&\s]+/gi,'$1[REDACTED]').slice(0,4_000);let failure;try{failure=await optionalJson(paths.failure,'local_runtime_failure_descriptor');}catch(failureReadError){failure=await startupFailure(paths,{attemptId,attemptStartedAt,component:currentComponent,state:'STARTUP_FAILED',cause:`${message}; failure_descriptor_read_failed:${String(failureReadError?.message??failureReadError)}`,remediation:'Inspect the bounded component and orchestration logs for this exact attempt; the invalid failure descriptor was atomically replaced.',log:currentLog});}if(failure?.attemptId!==attemptId)failure=await startupFailure(paths,{attemptId,attemptStartedAt,component:currentComponent,state:'STARTUP_FAILED',cause:message,remediation:'Inspect the bounded component and orchestration logs for this exact attempt; downstream services were stopped safely.',log:currentLog});await orchestrationEvent(paths,{event:'LOCAL_UP_FAILED',attemptId,component:currentComponent,error:message,log:currentLog}).catch(()=>undefined);await localDown({runtimeDir,ports,print:false,preserveFailure:true}).catch(()=>undefined);throw new Error(failureMessage(failure));
  }
}

export async function localOpen({runtimeDir=defaultRuntimeDir,ports=defaultPorts,open,print=true}={}){const status=await localStatus({runtimeDir,ports,print:false});if(status.state!=='READY')throw new Error('VIGIA LOCAL NOT READY\nRun npm run local:up first.');const result=await operatorOpen({open});if(result.origin!==`http://127.0.0.1:${ports.operator}`||result.releaseId!==status.pointer.releaseId)throw new Error('local_open_runtime_identity_mismatch');if(print)console.log(`VIGIA LOCAL OPENED\n${result.origin}/#/command-overview`);return result;}

export async function localCrashComponentForTest(name,{runtimeDir=defaultRuntimeDir,ports=defaultPorts}={}){if(!['api','fieldnet','operator'].includes(name))throw new Error('local_runtime_test_component_invalid');const paths=runtimePaths(runtimeDir),pointer=await readRequiredJson(paths.pointer,{root,maxBytes:LOCAL_RUNTIME_DESCRIPTOR_MAX_BYTES,label:'local_runtime_pointer',validate:runtimePointerSchema}),component=pointer?.components?.[name];if(!component)throw new Error('local_runtime_test_component_not_running');await supervisorRequest(component,await protectedSecret(paths.controlToken),'crash');await waitPortFree(ports[name]);return{state:'CRASHED',name};}

if(path.resolve(process.argv[1]??'')===fileURLToPath(import.meta.url)){
  const action=process.argv[2]??'status';try{if(action==='up')await localUp();else if(action==='status')await localStatus();else if(action==='down')await localDown();else if(action==='open')await localOpen();else throw new Error(`unknown_local_runtime_action:${action}`);}catch(error){console.error(`LOCAL RUNTIME FAILED\n\n${String(error?.message??error)}`);process.exitCode=1;}
}
