import {readFile,writeFile,mkdir} from 'node:fs/promises';
const out='docs/handoffs/mega-ii',token=(await readFile('.tmp/release/operator-token','utf8')).trim();
async function get(path){const start=performance.now(),r=await fetch('http://127.0.0.1:4177'+path,{headers:{authorization:'Bearer '+token},signal:AbortSignal.timeout(60000)});let data=await r.json();return {status:r.status,latencyMs:performance.now()-start,data};}
const incidents=['incident:PT-2026-03CFDC147C','incident:PT-2026-01F7E2E21A','incident:PT-2026-08D08E2A0D'];
const capture={capturedAt:new Date().toISOString(),incidents:[]};await mkdir(out,{recursive:true});
for(const id of incidents){const base='/api/v10/operator/incidents/'+encodeURIComponent(id),ops=await get(base+'/operations');console.log(JSON.stringify({id,operationsStatus:ops.status,latencyMs:ops.latencyMs}));const p=ops.data.data??{};capture.incidents.push({id,operationsStatus:ops.status,thermalCount:p.physicalWorld?.value?.incidents?.[0]?.thermal?.detections?.length??null,physicalState:p.physicalWorld?.status});await writeFile('.tmp/mega-ii/operations-'+id.split(':')[1]+'.json',JSON.stringify(ops.data));}
// Worker is asynchronous; the caller reruns capture after its normal scheduled tick.
for(const row of capture.incidents){const base='/api/v10/operator/incidents/'+encodeURIComponent(row.id)+'/situation',view=await get(base);row.situationStatus=view.status;row.state=view.data.state;const s=view.data.snapshot;if(s){row.snapshotId=s.id;row.knownAt=s.knownAt;row.relationships=s.relationships.reduce((o,e)=>(o[e.kind]=(o[e.kind]??0)+1,o),{});row.facilities=s.facilities.length;row.routes=s.routes.length;row.rankings=s.rankings;row.hospitalExample=s.facilities.filter(f=>f.canonicalType==='hospital').sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,2).map(f=>({facility:f,route:s.routes.find(r=>r.facilityId===f.id)}));await writeFile(out+'/live-situation-'+row.id.split(':')[1]+'.json',JSON.stringify(s,null,2));row.ask=await get(base+'/ask?question='+encodeURIComponent('Which hospital is closest with a verified emergency department?'));}}
capture.quality=await get('/api/v10/operator/situation-quality');await writeFile(out+'/live-proof.json',JSON.stringify(capture,null,2));console.log(JSON.stringify(capture.incidents.map(({id,state,relationships,facilities,routes})=>({id,state,relationships,facilities,routes})),null,2));
