#!/usr/bin/env node
// Authored for execution in a normal LOCAL workspace. Do not execute in the
// restricted handoff session. --help and --check syntax do not access a browser.
import {readFile,mkdir,writeFile,open} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createOneTimeAdmission} from '../apps/operator-console/admission.mjs';
import {signOperatorProxyRequest} from '../packages/domain/src/operator-proxy/request-auth.mjs';
import {startControlledTeamHarness} from './mega_ix_acceptance_harness.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
if(!process.argv.includes('--run-local')){
  console.log('Run outside the restricted sandbox: node scripts/mega_ix_local_acceptance.mjs --run-local\nRequires Playwright+Chromium, PostgreSQL, the current VIGIA baseline, MEGA_IX_API_KEY_FILE and MEGA_IX_ACCESS_KEY_FILE (or existing .tmp/release token files). Optional MEGA_IX_INCIDENT_ID, MEGA_IX_API_URL, MEGA_IX_CONSOLE_URL, MEGA_IX_OUTPUT, MEGA_IX_PLAYWRIGHT_MODULE, MEGA_IX_HEADED=1, MEGA_IX_KEEP_SERVERS=1. See MEGA-IX-APPLY.md.');
  process.exit(0);
}
process.chdir(root);
const env=process.env,api=new URL(env.MEGA_IX_API_URL??'http://127.0.0.1:4177'),consoleURL=new URL(env.MEGA_IX_CONSOLE_URL??'http://127.0.0.1:4191');
const output=path.resolve(env.MEGA_IX_OUTPUT??'.tmp/mega-ix-local-acceptance/'+new Date().toISOString().replaceAll(':','-'));
await mkdir(output,{recursive:true,mode:0o700});
const required=['command-important-now','mission-good','mission-problem','road-field-report','confirmation-request','confirmed-report','route-comparison','team-chat-online','team-chat-offline','partial-delivery','what-changed','local-vigia-active','restored-connection','mobile-mission','mobile-messaging'];
const result={schemaVersion:'vigia.mega-ix.local-acceptance.v1',startedAt:new Date().toISOString(),state:'RUNNING',controlledScenario:'CONTROLLED FIELD TEST: isolated in-memory TeamService + actual production console assets; synthetic Louredo paths and 11/24-minute estimates. Not an operational team.',steps:[],errors:[],consoleErrors:[],pageErrors:[],requestFailures:[],captures:Object.fromEntries(required.map(name=>[name,{state:'NOT_RUN'}])),responsive:[],performance:{previousStartupMs:9500,improvedFirstRequestMs:4305,uncachedP95Ms:3904,targetMs:2500,targetMet:false},humanComprehension:{state:'NOT_RUN',reason:'A fresh human participant must answer the nine questions; automated timings do not certify comprehension.'}};
const children=[],secrets=[];let browser,harness;
const redact=value=>{let s=String(value?.stack??value);for(const secret of secrets)if(secret)s=s.replaceAll(secret,'[REDACTED]');return s.replace(/([?&]admission=)[^\s&]+/g,'$1[REDACTED]').replace(/postgres(?:ql)?:\/\/[^\s]+/g,'postgresql://[REDACTED]');};
const save=()=>writeFile(path.join(output,'acceptance.json'),JSON.stringify(result,null,2)+'\n',{mode:0o600});
const step=async(name,fn)=>{const start=performance.now();try{const detail=await fn();result.steps.push({name,state:'PASS',ms:Math.round(performance.now()-start),detail});await save();return detail;}catch(error){result.steps.push({name,state:'FAIL',ms:Math.round(performance.now()-start),error:redact(error)});await save();throw error;}};
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const eventually=async(fn,timeout=45000)=>{const end=Date.now()+timeout;let error;do{try{const value=await fn();if(value)return value;}catch(e){error=e;}await delay(300);}while(Date.now()<end);throw error??Error('Condition timed out');};
async function command(args,label,extra={}){const file=await open(path.join(output,label+'.log'),'a',0o600),child=spawn(process.execPath,args,{cwd:root,env:{...env,...extra},stdio:['ignore',file.fd,file.fd]});await file.close();return child;}
async function run(args,label){const child=await command(args,label);await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',code=>code===0?resolve():reject(Error(label+' failed; see protected log')));});}
async function probe(url){try{return await fetch(url,{signal:AbortSignal.timeout(2500)});}catch{return null;}}
try{
  for(const url of [api,consoleURL])assert.ok(url.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(url.hostname),'Only local HTTP listeners are supported');
  const apiKey=(await readFile(env.MEGA_IX_API_KEY_FILE??'.tmp/release/operator-token','utf8')).trim(),accessKey=(await readFile(env.MEGA_IX_ACCESS_KEY_FILE??'.tmp/release/operator-console-access-token','utf8')).trim();secrets.push(apiKey,accessKey);assert.ok(apiKey.length>=32&&accessKey.length>=32,'Supply local installation keys of at least 32 characters');
  const {reuseOrBuildReleaseManifest}=await import('./release/build_release_manifest.mjs');
  const release=await step('release manifest',()=>reuseOrBuildReleaseManifest());result.releaseId=release.releaseId;
  await step('production build',()=>run(['apps/operator-console/scripts/build.mjs'],'build'));
  const common={OPEN_BROWSER:'0',NODE_ENV:'development',VIGIA_RELEASE_ID:release.releaseId,VIGIA_CODE_STATE_HASH:release.codeStateHash,VIGIA_OPERATIONAL_DATA_HASH:release.operationalDataHash,VIGIA_APPROVED_RELEASE_STATEMENT_SHA256:release.releaseStatementHash};
  await step('start or check API',async()=>{
    if(!await probe(new URL('/api/v10/release',api))){assert.ok(env.VIGIA_DATABASE_URL||env.VIGIA_DATABASE_URL_FILE,'Configure PostgreSQL before starting the API');const child=await command(['apps/api/src/server.mjs'],'api',{...common,HOST:api.hostname,PORT:api.port,VIGIA_RUNTIME_PROFILE:'local_shadow',VIGIA_LOCAL_OPERATOR_AUTOLOGIN:'1',VIGIA_OPERATOR_CONSOLE_ORIGIN:consoleURL.origin,VIGIA_OPERATOR_TOKEN:apiKey});children.push(child);}
    const live=await eventually(async()=>{const r=await probe(new URL('/api/v10/release',api));return r?.ok?await r.json():null;},180000);
    const text=JSON.stringify(live);assert.ok(text.includes(release.releaseId),'Existing API release mismatch: restart it with this baseline; runner never kills an existing listener');return {releaseId:release.releaseId};
  });
  const signedGet=async part=>{const r=await fetch(new URL(part,api),{headers:{origin:consoleURL.origin,'sec-fetch-site':'same-origin','x-vigia-ui-proxy':'mission-dark-realdata-2.0',...signOperatorProxyRequest({key:apiKey,releaseId:release.releaseId,method:'GET',path:part})},signal:AbortSignal.timeout(60000)});assert.equal(r.status,200,'Backend projection '+part);return r.json();};
  const overview=await step('real retained overview',()=>signedGet('/api/v10/operator/command-overview'));
  const rows=overview.data?.incidents?.value?.incidents??[];
  const incidentId=env.MEGA_IX_INCIDENT_ID??rows.map(r=>r.incident?.id??r.incidentId??r.id).find(Boolean);assert.ok(incidentId,'No retained incident returned; provide MEGA_IX_INCIDENT_ID');result.incidentId=incidentId;
  await step('start or check production console',async()=>{
    if(!await probe(new URL('/__operator/ready',consoleURL))){const child=await command(['apps/operator-console/server.mjs'],'console',{...common,HOST:consoleURL.hostname,PORT:consoleURL.port,VIGIA_BACKEND_URL:api.origin,VIGIA_OPERATOR_PUBLIC_AUTHORITY:consoleURL.host,VIGIA_OPERATOR_STATIC_ROOT:path.join(root,'apps/operator-console/dist'),VIGIA_OPERATOR_PROXY_KEY:apiKey,VIGIA_OPERATOR_ACCESS_TOKEN:accessKey});children.push(child);}
    const live=await eventually(async()=>{const r=await probe(new URL('/__operator/ready',consoleURL));return r?.ok?await r.json():null;},60000);assert.ok(JSON.stringify(live).includes(release.releaseId),'Existing console release mismatch');return {releaseId:release.releaseId};
  });
  const {chromium}=await import(env.MEGA_IX_PLAYWRIGHT_MODULE??'playwright');
  browser=await chromium.launch({headless:env.MEGA_IX_HEADED!=='1'});
  const pages={};let teamInterception=false;
  async function pageFor(name){
    const context=await browser.newContext({viewport:{width:1672,height:941},deviceScaleFactor:1,serviceWorkers:'block'}),page=await context.newPage();
    page.on('console',message=>{if(message.type()==='error')result.consoleErrors.push({person:name,message:redact(message.text()),expectedOffline:Boolean(page.testOffline)});});page.on('pageerror',e=>result.pageErrors.push({person:name,error:redact(e)}));page.on('requestfailed',r=>result.requestFailures.push({person:name,url:r.url().split('?')[0],error:r.failure()?.errorText,expectedOffline:Boolean(page.testOffline)}));
    await context.route('**/backend/api/v10/team/**',async route=>{if(!teamInterception)return route.continue();if(page.testOffline)return route.abort('internetdisconnected');const req=route.request(),target=harness.origin+new URL(req.url()).pathname.replace('/backend','')+new URL(req.url()).search;const response=await route.fetch({url:target,headers:{authorization:'Bearer '+harness.tokens[name],'content-type':'application/json'},timeout:15000});await route.fulfill({response});});
    const admission=createOneTimeAdmission(accessKey);secrets.push(admission);const admitted=await context.request.get(consoleURL.origin+'/?admission='+encodeURIComponent(admission),{maxRedirects:0});assert.ok(admitted.status()<400,'Console admission failed');pages[name]=page;return page;
  }
  const ana=await pageFor('Ana');
  const route=async(page,name)=>{await page.goto(consoleURL.origin+'/?mega_ix_acceptance='+Date.now()+'#/'+name+'?id='+encodeURIComponent(incidentId),{waitUntil:'domcontentloaded'});await page.locator('[data-mission-command]').waitFor({state:'visible',timeout:60000});await page.waitForFunction(()=>{const el=document.querySelector('[data-mission-command]');return el&&!el.textContent.includes('Reading team objectives');},{},{timeout:60000});await page.evaluate(()=>document.fonts.ready);};
  const team=page=>page.locator('[data-mission-command]');
  const action=(page,name)=>team(page).locator('[data-team="'+name+'"]').first().click();
  async function capture(page,name){const file=path.join(output,name+'.png');await page.screenshot({path:file,fullPage:true,animations:'disabled',timeout:30000});result.captures[name]={state:'CAPTURED',file:path.relative(output,file),viewport:page.viewportSize(),controlled:teamInterception};await save();}
  async function geometry(page,label){const measures=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,offenders:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&s.visibility!=='hidden'&&s.position!=='fixed'&&(r.right>innerWidth+1||r.left< -1);}).slice(0,20).map(e=>({tag:e.tagName,classes:e.className?.toString().slice(0,100)}))}));result.responsive.push({label,...measures});return measures;}
  await step('real incident detail and response',async()=>{for(const r of ['command-overview','incident-detail','response-access']){await route(ana,r);await capture(ana,'real-'+r);await geometry(ana,'real-'+r);}return {syntheticTeam:false};});
  harness=await startControlledTeamHarness(incidentId);secrets.push(...Object.values(harness.tokens));teamInterception=true;
  await step('controlled mission GOOD',async()=>{await route(ana,'incident-detail');await team(ana).getByText('CONTROLLED FIELD TEST · separate from operational history',{exact:true}).waitFor();await action(ana,'new-mission');await team(ana).locator('[name=objective]').fill('Keep Louredo connected to emergency healthcare');await team(ana).locator('[data-team-form=mission] button[type=submit]').click();await eventually(async()=>{const v=await harness.snapshot('Ana');return v.missions[0]?.state==='GOOD';});await action(ana,'mission');await team(ana).locator('.mc-good').waitFor();await capture(ana,'mission-good');});
  await step('field report and mission PROBLEM',async()=>{await action(ana,'new-report');await team(ana).locator('[name=note]').fill('CONTROLLED FIELD TEST: fallen tree blocks the EM527 approach.');await team(ana).locator('[data-team-form=report] button[type=submit]').click();await eventually(async()=>{const v=await harness.snapshot('Ana');return v.missions[0]?.state==='PROBLEM'&&v.reports.length===1;});await action(ana,'mission');await team(ana).locator('.mc-problem').waitFor();await capture(ana,'mission-problem');await action(ana,'report');await team(ana).getByText('Not yet confirmed',{exact:true}).waitFor();await capture(ana,'road-field-report');});
  await step('request confirmation',async()=>{await action(ana,'request-confirmation');await eventually(async()=>((await harness.snapshot('Ana')).requests.length===1));await team(ana).locator('.mc-feedback').filter({hasText:'Confirmation request saved'}).waitFor();await capture(ana,'confirmation-request');});
  const pedro=await pageFor('Pedro');
  await step('second responder confirms',async()=>{await route(pedro,'incident-detail');await action(pedro,'report');await action(pedro,'confirm');await team(pedro).locator('[data-team-form=confirm] button[type=submit]').click();await eventually(async()=>((await harness.snapshot('Pedro')).reports[0]?.verification.state==='FIELD_CONFIRMED'));await action(pedro,'report');await team(pedro).getByText('Confirmed by two or more responders',{exact:true}).waitFor();await capture(pedro,'confirmed-report');});
  await step('route comparison and chronology',async()=>{await action(pedro,'mission');await action(pedro,'routes');await capture(pedro,'route-comparison');await action(pedro,'home');await action(pedro,'timeline');await capture(pedro,'what-changed');});
  await step('Command Overview Important now',async()=>{await route(ana,'command-overview');await team(ana).locator('.mc-important').waitFor();await capture(ana,'command-important-now');await capture(ana,'local-vigia-active');});
  const onlineText='CONTROLLED '+Date.now()+': check the alternative approach',offlineText='CONTROLLED '+Date.now()+': local message while upstream is down';
  const send=async(page,text)=>{await team(page).locator('[data-team-form=message] textarea').fill(text);await team(page).locator('[data-team-form=message] button[type=submit]').click();await team(page).locator('.mc-message').filter({hasText:text}).waitFor();};
  await step('online messaging and partial delivery',async()=>{await action(ana,'chat');await send(ana,onlineText);await action(pedro,'home');await action(pedro,'chat');await action(pedro,'retry');await eventually(async()=>{const m=(await harness.snapshot('Ana')).messages.find(m=>m.text===onlineText);return m?.delivery.received.includes('Pedro')&&m.delivery.waiting.includes('Sofia');});await action(ana,'retry');await capture(ana,'team-chat-online');await capture(ana,'partial-delivery');});
  await step('controlled upstream loss with local service active',async()=>{harness.setUpstream(false);await action(ana,'sync-central');await team(ana).locator('.mc-connection').filter({hasText:'INTERNET OFFLINE'}).waitFor();await send(ana,offlineText);await capture(ana,'team-chat-offline');return {scope:'Injected local-to-central transport failure. Host internet and retained-data providers are not disabled.'};});
  await step('device queue and reconnect',async()=>{ana.testOffline=true;await ana.context().setOffline(true);await send(ana,offlineText+' device queue');await team(ana).locator('.mc-pending').waitFor();await capture(ana,'device-offline-queue');ana.testOffline=false;await ana.context().setOffline(false);await action(ana,'retry');await eventually(async()=>((await harness.snapshot('Ana')).messages.some(m=>m.text===offlineText+' device queue')));});
  await step('restore central connection without duplicates',async()=>{harness.setUpstream(true);await action(ana,'sync-central');await eventually(async()=>((await harness.snapshot('Ana')).hub.state==='CENTRAL_CONNECTION_RESTORED'));const before=harness.counts();await Promise.all([ana.waitForResponse(r=>r.url().endsWith('/sync')&&r.request().method()==='POST'&&r.status()===200),action(ana,'sync-central')]);await eventually(async()=>{const after=harness.counts();assert.deepEqual(after.local.report,before.local.report);assert.deepEqual(after.local.message,before.local.message);assert.deepEqual(after.central.report,before.central.report);assert.deepEqual(after.central.message,before.central.message);return true;});assert.equal(before.central.report.length,1);assert.equal(before.central.message.length,3);await capture(ana,'restored-connection');return {counts:before};});
  await step('waiting recipient receives after returning',async()=>{const sofia=await pageFor('Sofia');await route(sofia,'incident-detail');await action(sofia,'chat');await action(sofia,'retry');await eventually(async()=>{const m=(await harness.snapshot('Ana')).messages.find(m=>m.text===onlineText);return m.delivery.received.includes('Sofia')&&m.delivery.waiting.length===0;});await action(ana,'retry');await capture(ana,'all-recipients-delivered');});
  await step('people view and keyboard focus',async()=>{await action(ana,'people');await team(ana).getByRole('heading',{name:'People and team'}).waitFor();await ana.keyboard.press('Tab');assert.ok(await ana.evaluate(()=>document.activeElement!==document.body),'Tab did not reach a control');await capture(ana,'people');});
  await step('desktop and mobile responsive matrix',async()=>{for(const width of [1672,1440,1280,1024,430,390,320]){await ana.setViewportSize({width,height:width<=430?844:941});for(const section of ['mission','chat']){await route(ana,'incident-detail');await action(ana,section);await geometry(ana,width+'-'+section);await capture(ana,width+'-'+section);if(width===390)await capture(ana,section==='mission'?'mobile-mission':'mobile-messaging');}}});
  assert.ok(result.responsive.every(r=>!r.overflow),'Horizontal overflow recorded in responsive matrix');result.duplicateCheck='PASS';result.unoperated=['Physical microphone recording and camera hardware','Map picking and attachment controls require separate operation','Fresh-user comprehension study','External central deployment and real network-disconnection exercise'];
  assert.equal(result.pageErrors.length,0,'Page errors were recorded');assert.equal(result.consoleErrors.filter(e=>!e.expectedOffline).length,0,'Console errors were recorded');assert.ok(required.every(name=>result.captures[name].state==='CAPTURED'),'Required capture missing');
  result.state='AUTOMATED_PASS_HUMAN_REVIEW_REQUIRED';
}catch(error){result.state='FAIL';result.errors.push(redact(error));process.exitCode=1;}
finally{await browser?.close().catch(()=>{});await harness?.close().catch(()=>{});if(env.MEGA_IX_KEEP_SERVERS!=='1')for(const child of children)child.kill('SIGTERM');result.finishedAt=new Date().toISOString();await save();console.log(JSON.stringify({state:result.state,acceptance:path.join(output,'acceptance.json')}));}
