import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { performance } from 'node:perf_hooks';
import { EvidenceClosureService } from '../apps/api/src/modules/alerts/evidence-closure-service.mjs';
import { createObservationOpportunity } from '../packages/domain/src/observation-opportunity.mjs';
import { predictOrbitalPasses, validateOrbitalPredictions } from '../packages/domain/src/orbital-opportunity.mjs';
import { createCoverageIntelligence } from '../packages/domain/src/coverage-intelligence.mjs';

const root = path.resolve(import.meta.dirname, '..');
const read = async (file) => JSON.parse(await readFile(path.join(root, file), 'utf8'));
const sha = (value) => `sha256:${createHash('sha256').update(typeof value === 'string' ? value : JSON.stringify(value)).digest('hex')}`;
const quantile = (values, p) => { const sorted = [...values].sort((a, b) => a - b); return sorted.length ? sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * p))] : null; };

class MemoryStore {
  constructor() { this.plans = new Map(); this.decisions = []; this.coverages = new Map(); this.truth = new Map(); this.races = new Map(); this.next = new Map(); this.stages = []; }
  async listPlans({ subjectType = null, subjectId = null, resolutionState = null, limit = 300 } = {}) { return [...this.plans.values()].filter((item) => (!subjectType || item.subjectType === subjectType) && (!subjectId || item.subjectId === subjectId) && (!resolutionState || item.resolutionState === resolutionState)).sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt)).slice(0, limit); }
  async getPlan(id) { return this.plans.get(id) ?? null; }
  async persistReconciliation({ plan, coverage = null, autopilot = null, decisions = [] }) { this.plans.set(plan.id, plan); if (coverage) this.coverages.set(plan.subjectId, coverage); if (autopilot?.truthState) this.truth.set(autopilot.truthState.id, autopilot.truthState); if (autopilot?.nextBestEvidence) this.next.set(autopilot.nextBestEvidence.id, autopilot.nextBestEvidence); if (autopilot?.evidenceRace) this.races.set(autopilot.evidenceRace.id, autopilot.evidenceRace); this.stages.push(...(autopilot?.latencyStages ?? [])); for (const item of decisions) if (!this.decisions.some((prior) => prior.subjectId === item.subjectId && prior.decisionType === item.decisionType && prior.reasonCode === item.reasonCode)) this.decisions.push(item); return plan; }
  async coverage(id) { return this.coverages.get(id) ?? null; }
  async decisionLedger({ subjectId = null } = {}) { return this.decisions.filter((item) => !subjectId || item.subjectId === subjectId); }
  async truthStates({ eventId = null } = {}) { return [...this.truth.values()].filter((item) => !eventId || item.eventId === eventId); }
  async evidenceRaces({ eventId = null, state = null } = {}) { return [...this.races.values()].filter((item) => (!eventId || item.eventId === eventId) && (!state || item.state === state)); }
  async latencyMetrics() { return {}; }
  async summary() { const plans = [...this.plans.values()], closed = plans.filter((item) => item.resolutionState === 'CLOSED'), preserved = plans.filter((item) => item.resolutionState === 'PRESERVED'); return { plans: plans.length, open: plans.filter((item) => item.resolutionState === 'OPEN').length, closed: closed.length, preserved: preserved.length, truthStates: this.truth.size, evidenceRaces: this.races.size, settledRaces: [...this.races.values()].filter((item) => item.state === 'SETTLED').length, preservedReasons: Object.fromEntries(Object.entries(Object.groupBy(preserved, (item) => item.resultReason)).map(([key, values]) => [key, values.length])), timeToCorroboration: { sampleCount: closed.length, medianMs: quantile(closed.map((item) => Date.parse(item.closedAt) - Date.parse(item.createdAt)), .5), p95Ms: quantile(closed.map((item) => Date.parse(item.closedAt) - Date.parse(item.createdAt)), .95) } }; }
}

const [projection, runtime, acquisitions, orbit, priorProof, detectionCorpus] = await Promise.all([
  read('data/runtime/event-projections.production.json'), read('data/runtime/fire-event-observations.production.json'), read('data/runtime/acquisition-state.json'),
  read('data/reference/orbits/sentinel3-current.json'), read('data/validation/operations/autonomous-evidence-operations-proof.json'), read('data/validation/detection/portugal-2024-active-fire-corpus.json')
]);
const eligible = projection.operatorEvents.filter((event) => event.physicalFirst === true && event.thermal?.series?.some((item) => item.sourceFamily === 'viirs') && event.thermal?.series?.some((item) => item.sourceFamily === 'sentinel3_slstr'));
if (!eligible.length) throw new Error('no_real_viirs_to_sentinel3_vertical');
const sourceEvent = eligible.sort((a, b) => (b.thermal?.series?.length ?? 0) - (a.thermal?.series?.length ?? 0))[0];
const associated = runtime.observations.filter((item) => runtime.observationEvents[item.id] === sourceEvent.id);
const viirs = associated.filter((item) => item.sourceFamily === 'viirs').sort((a, b) => Date.parse(a.at) - Date.parse(b.at))[0];
const sentinelGroups = Object.values(Object.groupBy(associated.filter((item) => item.sourceFamily === 'sentinel3_slstr'), (item) => item.provenance.rawSourceProductId));
const products = sentinelGroups.map((items) => { const observation = items[0], raw = acquisitions.products[observation.provenance.rawSourceProductId] ?? {}; return { productId: observation.provenance.providerProductId.split(':')[0], rawSourceProductId: observation.provenance.rawSourceProductId, platform: observation.satellite, observedAt: observation.at, coordinate: observation.coordinate, windowStart: raw.sourceTimestampRange?.start, windowEnd: raw.sourceTimestampRange?.end, receivedAt: observation.receivedAt, observation, count: items.length }; }).sort((a, b) => Date.parse(a.observedAt) - Date.parse(b.observedAt));
const validation = validateOrbitalPredictions({ eventId: sourceEvent.id, coordinate: sourceEvent.coordinate, orbitSnapshot: orbit, actualProducts: products });
const winnerProduct = products.at(-1), initialAt = new Date(Date.parse(winnerProduct.observedAt) - 60 * 60_000);
const historicalPasses = predictOrbitalPasses({ eventId: sourceEvent.id, coordinate: sourceEvent.coordinate, orbitSnapshot: orbit, from: initialAt, horizonHours: 12, stepSeconds: 5 });
const opportunity = historicalPasses.find((item) => item.platform === winnerProduct.platform && Date.parse(item.windowStart) <= Date.parse(winnerProduct.observedAt) && Date.parse(item.windowEnd) >= Date.parse(winnerProduct.observedAt));
if (!opportunity) throw new Error('historical_product_has_no_compatible_predicted_pass');
const governedOpportunities = historicalPasses.map((item) => createObservationOpportunity(item, { now: initialAt })), governedOpportunity = governedOpportunities.find((item) => item.id === opportunity.id);
const initialEvent = { id: sourceEvent.id, label: sourceEvent.label ?? sourceEvent.id, coordinate: sourceEvent.coordinate, physicalFirst: true, observations: [viirs], physicalSourceProfile: { families: ['viirs'], familyCount: 1 }, physicalState: { firstAt: viirs.at, lastAt: viirs.at, freshness: 'delayed' }, reportState: sourceEvent.reportState, behaviorState: 'unknown', actionNeed: { kind: 'independent_physical_confirmation', needsRouting: true, reason: 'Independent physical corroboration is not yet attributable.' }, observationPlan: { opportunitiesV2: governedOpportunities, opportunityResults: [] } };
const finalObservation = winnerProduct.observation, repositoryAt = finalObservation.latestAcquisition?.repositoryPersistedAt ?? finalObservation.vigiaObservationPersistedAt ?? finalObservation.vigiaIngestedAt ?? finalObservation.receivedAt;
let clock = initialAt, store = new MemoryStore(), service = new EvidenceClosureService({ store, clock: () => new Date(clock) });
const execution = [], started = performance.now(), beforeState = await service.reconcileEvent(initialEvent, { sources: { firms: { state: 'current' }, sentinel3Pixels: { state: 'stale' }, sentinel2: { state: 'catalogue_available' } } }); execution.push(performance.now() - started);
clock = new Date(Math.max(Date.parse(repositoryAt ?? ''), Date.parse(finalObservation.vigiaIngestedAt ?? ''), Date.parse(finalObservation.receivedAt ?? ''), Date.parse(winnerProduct.observedAt)) + 1000);
const result = { opportunityId: governedOpportunity.id, resultState: 'CORROBORATED', attributableObservationId: finalObservation.id, observedAt: finalObservation.at, sourceFamily: 'sentinel3_slstr', reasonCode: 'INDEPENDENT_SOURCE_MATCHED_GOVERNED_WINDOW' };
const finalEvent = { ...initialEvent, observations: [viirs, finalObservation], physicalSourceProfile: { families: ['viirs', 'sentinel3_slstr'], familyCount: 2 }, physicalState: { firstAt: viirs.at, lastAt: finalObservation.at, freshness: 'aging' }, actionNeed: { kind: 'monitor_multisource_physical_evidence', needsRouting: false, reason: 'Independent physical corroboration is attributable.' }, observationPlan: { opportunitiesV2: governedOpportunities, opportunityResults: [result] } };
const finalStarted = performance.now(), afterState = await service.reconcileEvent(finalEvent, { sources: { firms: { state: 'current' }, sentinel3Pixels: { state: 'stale' }, sentinel2: { state: 'catalogue_available' } } }); execution.push(performance.now() - finalStarted);
await service.recordAlertDecision({ id: `alert:${sourceEvent.id}`, subjectId: sourceEvent.id, alertType: 'PHYSICAL_FIRE', lifecycleState: 'OPEN', reasonCode: 'INDEPENDENT_PHYSICAL_CORROBORATION_ADDED' }, { materialChange: true });
const currentPasses = predictOrbitalPasses({ eventId: sourceEvent.id, coordinate: sourceEvent.coordinate, orbitSnapshot: orbit, from: new Date(orbit.fetchedAt), horizonHours: 12 });
const currentCoverage = createCoverageIntelligence({ subject: { type: 'EVENT', id: sourceEvent.id, coordinate: sourceEvent.coordinate }, opportunities: currentPasses, sourceStates: { viirs: { state: 'current' }, sentinel3_slstr: { state: 'stale' }, sentinel2_msi: { state: 'catalogue_available' } }, now: new Date(orbit.fetchedAt) });
const priorPreserved = priorProof.after.unknownPreserved, acceptedOutcomes = priorPreserved + 1;
const stageMetrics = Object.fromEntries(Object.entries(Object.groupBy(afterState.latencyStages, (item) => item.stageName)).map(([name, values]) => [name, { measured: values.filter((item) => item.state === 'MEASURED').length, preservedUnknown: values.filter((item) => item.state !== 'MEASURED').length, medianMs: quantile(values.map((item) => item.durationMs).filter(Number.isFinite), .5), p95Ms: quantile(values.map((item) => item.durationMs).filter(Number.isFinite), .95) }]));
const negative = detectionCorpus.cases.find((item) => item.referenceLabel === 'NON_WILDFIRE_NEGATIVE'), unresolvedNoDetection = detectionCorpus.cases.find((item) => item.referenceLabel === 'FIRE_POSITIVE' && item.sensorCoverage?.viirs?.state === 'OBSERVATION_OPPORTUNITY_UNRESOLVED'), rejected = Object.values(acquisitions.products).find((item) => item.processingState === 'rejected' && item.provider === 'nasa-firms'), ambiguous = projection.operatorEvents.find((item) => item.associationState === 'ambiguous' || item.evidenceState === 'association-uncertain');
const corpusEntries = [
  { kind: 'DETECTION', id: viirs.id, eventId: sourceEvent.id, observedAt: viirs.at, sourceFamily: 'viirs', provenance: viirs.provenance },
  ...products.map((item) => ({ kind: 'CONFIRMATION', id: item.observation.id, eventId: sourceEvent.id, observedAt: item.observedAt, sourceFamily: 'sentinel3_slstr', productId: item.productId, rawSourceProductId: item.rawSourceProductId, associatedPixelCount: item.count, lateDeliveryMs: Date.parse(item.receivedAt) - Date.parse(item.observedAt) })),
  { kind: 'EXCLUSION', id: negative.caseId, qualification: negative.referenceQualification, authority: negative.labelAuthority, provenance: negative.evidenceProvenance },
  { kind: 'NO_DETECTION_OUTCOME_UNRESOLVED', id: unresolvedNoDetection.caseId, outcome: unresolvedNoDetection.sensorCoverage.viirs.state, qualification: unresolvedNoDetection.sensorCoverage.viirs.basis, unknownPreserved: true },
  { kind: 'AMBIGUOUS_ASSOCIATION', id: ambiguous.id, evidenceState: ambiguous.evidenceState, associationState: ambiguous.associationState, unknownPreserved: true },
  { kind: 'PROVIDER_FAILURE', id: rejected.id, provider: rejected.provider, reason: rejected.parserError, at: rejected.rejectedAt, unknownPreserved: true },
  ...priorProof.replay.map((item) => ({ kind: 'EXPIRED_EVIDENCE_PATH', id: `${item.eventId}:expired`, eventId: item.eventId, resultState: item.resultState, resolutionState: item.resolutionState }))
];
const corpus = { schemaVersion: 'vigia.physical-truth-operations-corpus.v1', generatedAt: new Date().toISOString(), selectionPolicy: 'Deterministic union of the production VIIRS→Sentinel-3 associated vertical, governed historical validation artifacts, preserved-unknown operations proof, one governed non-wildfire exclusion, one unresolved no-detection case, one ambiguous association and one rejected provider acquisition.', inventory: { entries: corpusEntries.length, byKind: Object.fromEntries(Object.entries(Object.groupBy(corpusEntries, (item) => item.kind)).map(([kind, values]) => [kind, values.length])), corrections: 0 }, correctionQualification: 'No attributable correction exists in the production repository; the corpus records zero rather than manufacturing one.', entries: corpusEntries, sourceArtifacts: ['data/runtime/fire-event-observations.production.json', 'data/runtime/event-projections.production.json', 'data/runtime/acquisition-state.json', 'data/validation/operations/autonomous-evidence-operations-proof.json', 'data/validation/detection/portugal-2024-active-fire-corpus.json'], limitations: ['The no-detection reference has no proven swath opportunity and therefore remains unresolved.', 'The historical Sentinel-3 cohort is one event with four independently archived product passages; it is evidence depth, not population diversity.'] };
corpus.datasetHash = sha(corpus);
const proof = { schemaVersion: 'vigia.physical-truth-autopilot-proof.v1', generatedAt: new Date().toISOString(), mode: 'CONTROLLED_REPLAY_OF_REAL_PRODUCTION_ASSOCIATIONS', productionInjection: false, selectedByPolicy: { rule: 'physicalFirst event with attributable VIIRS and Sentinel-3 observations; greatest associated thermal depth', eventId: sourceEvent.id, forcedJoins: 0 },
  sourceArtifacts: { runtime: 'data/runtime/fire-event-observations.production.json', projections: 'data/runtime/event-projections.production.json', acquisitions: 'data/runtime/acquisition-state.json', orbit: 'data/reference/orbits/sentinel3-current.json', priorProof: 'data/validation/operations/autonomous-evidence-operations-proof.json' },
  criticalDelta: { before: { fireTruthState: null, nextBestEvidenceDecision: null, eventSpecificOrbitalPasses: 0, orbitalValidationProducts: 0, closedUnknowns: 0, preservedUnknowns: priorPreserved, evidenceRaceWinner: null, alertMaterialUpdates: 0 }, after: { fireTruthStates: store.truth.size, nextBestEvidenceDecisions: store.next.size, currentEventSpecificOrbitalPasses: currentPasses.length, orbitalValidationProducts: products.length, closedUnknowns: 1, preservedUnknowns: priorPreserved, evidenceRaceWinner: afterState.evidenceRace.winnerPathId, cancelledRacePaths: afterState.evidenceRace.paths.filter((item) => item.raceState === 'CANCELLED').length, alertMaterialUpdates: store.decisions.filter((item) => ['ALERT_MATERIAL_UPDATE','ALERT_UPDATED'].includes(item.decisionType)).length } },
  vertical: { eventId: sourceEvent.id, viirsFirst: { observationId: viirs.id, at: viirs.at, rawSourceProductId: viirs.provenance.rawSourceProductId }, raceBefore: beforeState.evidenceRace, selectedOpportunity: governedOpportunity, compatibleSentinel3: { observationId: finalObservation.id, productId: winnerProduct.productId, rawSourceProductId: winnerProduct.rawSourceProductId, observedAt: winnerProduct.observedAt, receivedAt: winnerProduct.receivedAt }, association: { existingProductionEventId: runtime.observationEvents[finalObservation.id], forcedJoin: false }, closure: afterState.plan, truthBefore: beforeState.truthState, truthAfter: afterState.truthState, raceAfter: afterState.evidenceRace },
  nextBestEvidence: beforeState.nextBestEvidence, nextBestEvidenceAfterCorroboration: afterState.nextBestEvidence, currentPrediction: { calculatedFrom: orbit.fetchedAt, datasetHash: orbit.datasetHash, opportunities: currentPasses }, predictionValidation: validation, coverageTruth: currentCoverage, closureReplayCoverage: afterState.coverage,
  metrics: { closureRate: { numerator: 1, denominator: acceptedOutcomes, value: 1 / acceptedOutcomes, qualification: 'Accepted terminal controlled-replay outcomes only; open backlog excluded.' }, preservedUnknownRate: { numerator: priorPreserved, denominator: acceptedOutcomes, value: priorPreserved / acceptedOutcomes, byReason: priorProof.resultStates }, timeToCorroboration: { sampleCount: 1, milliseconds: Date.parse(afterState.plan.closedAt) - Date.parse(afterState.plan.createdAt), qualification: 'Controlled replay clock from plan creation through attributable product processing.' }, stageSeparatedLatency: stageMetrics, localAutopilotExecution: { samples: execution.length, medianMs: quantile(execution, .5), p95Ms: quantile(execution, .95), qualification: 'Local domain/service execution only; provider latency is reported separately by stage.' } },
  liveWatch: { state: beforeState.watch.state, sourceFamily: beforeState.watch.sourceFamily, opportunityId: beforeState.watch.opportunityId, watchFrom: beforeState.watch.watchFrom, watchUntil: beforeState.watch.watchUntil, settledState: afterState.plan.sourceWatch.state }, decisionLedger: { count: store.decisions.length, types: Object.fromEntries(Object.entries(Object.groupBy(store.decisions, (item) => item.decisionType)).map(([type, values]) => [type, values.length])), records: store.decisions }, corpus: { path: 'data/validation/operations/vigia-physical-truth-operations-corpus-v1.json', datasetHash: corpus.datasetHash },
  remoteDb: { postgisExecution: 'BLOCKED_EXTERNAL_DOCKER_DAEMON_UNAVAILABLE', migration: '011-physical-truth-autopilot.sql', remoteComposeConfig: 'VALIDATED_WITH_NON_SECRET_PLACEHOLDER_FILE_PATHS', degradedSemantics: 'HTTP 503 structured dependency state; root application remains live', destructiveRecoveryAttempted: false }, limitations: ['False-opportunity rate remains unmeasured without a complete pass/no-pass product archive.', corpus.correctionQualification, 'PostGIS migration execution remains pending until Docker Desktop is healthy.'] };
proof.evidenceHash = sha(proof);
async function probe(url) { try { const response = await fetch(url, { signal: AbortSignal.timeout(5_000) }); return { httpStatus: response.status, reachable: true }; } catch (error) { return { httpStatus: null, reachable: false, errorCode: error.cause?.code ?? error.code ?? 'FETCH_FAILED' }; } }
const runtimeProbe = { root: await probe('http://127.0.0.1:4177/'), operations: await probe('http://127.0.0.1:4177/api/v10/operations/status') };
const handoff = { schemaVersion: 'vigia.physical-truth-autopilot-handoff.v1', generatedAt: proof.generatedAt, owner: 'backend-physical-truth-autopilot', consumer: 'Agent 2 UI', releaseVerdict: 'BACKEND_P0_CAPABILITY_READY_WITH_EXTERNAL_POSTGIS_BLOCKER', runtime: { url: 'http://127.0.0.1:4177', mustRemainOwnedByAgent2: true, observed: runtimeProbe, activation: runtimeProbe.operations.httpStatus === 500 ? 'Current 4177 process predates structured degraded-state and autopilot routes; activate the current tree only during Agent 2 final restart.' : 'Current tree active.' }, criticalDelta: proof.criticalDelta, fireTruthState: afterState.truthState, nextBestEvidence: afterState.nextBestEvidence, closureReplayNextBestEvidence: beforeState.nextBestEvidence, orbitalPrediction: proof.currentPrediction, predictionValidation: validation.metrics, coverageTruth: currentCoverage, evidenceRace: afterState.evidenceRace, closureMetrics: proof.metrics, currentWatches: [proof.liveWatch], currentGaps: currentCoverage.gaps, currentAlerts: { state: runtimeProbe.operations.httpStatus === 200 ? 'QUERY_API' : 'UNAVAILABLE_POSTGIS', value: null, qualification: 'No zero is substituted while operational persistence is unavailable.' }, historicalProofIds: { eventId: sourceEvent.id, viirsObservationId: viirs.id, sentinel3ObservationIds: products.map((item) => item.observation.id), sentinel3ProductIds: products.map((item) => item.productId) }, liveWatch: proof.liveWatch, decisionLedger: proof.decisionLedger, degradedSemantics: { databaseUnavailable: { httpStatus: 503, dependency: 'postgis', retryable: true }, currentProcessQualification: runtimeProbe.operations.httpStatus === 500 ? 'Predates current structured-degraded router.' : null }, apiContracts: ['/api/v10/operations/fire-truth-states', '/api/v10/operations/evidence-races', '/api/v10/operations/latency', '/api/v10/operations/coverage/:subjectId', '/api/v10/operations/decision-ledger'], database: proof.remoteDb, artifacts: { proof: 'data/validation/operations/physical-truth-autopilot-proof.json', corpus: proof.corpus.path, orbit: proof.sourceArtifacts.orbit }, integrationNotes: ['Render unknowns, contradictions and blindness as distinct concepts.', 'A PREDICTED_ORBITAL_PASS is never an acquisition.', 'Keep null coverage percentages visible as unavailable, never coerce them to zero.', 'Use nextBestEvidence score components and qualification verbatim; it is not calibrated information gain.'] };
await mkdir(path.join(root, 'data/validation/operations'), { recursive: true });
await Promise.all([writeFile(path.join(root, 'data/validation/operations/physical-truth-autopilot-proof.json'), `${JSON.stringify(proof, null, 2)}\n`), writeFile(path.join(root, 'data/validation/operations/vigia-physical-truth-operations-corpus-v1.json'), `${JSON.stringify(corpus, null, 2)}\n`), writeFile(path.join(root, 'data/validation/operations/truth-autopilot-handoff.json'), `${JSON.stringify(handoff, null, 2)}\n`)]);
console.log(JSON.stringify({ proof: 'data/validation/operations/physical-truth-autopilot-proof.json', handoff: 'data/validation/operations/truth-autopilot-handoff.json', corpus: proof.corpus, eventId: sourceEvent.id, criticalDelta: proof.criticalDelta, predictionValidation: validation.metrics, metrics: proof.metrics, evidenceHash: proof.evidenceHash }, null, 2));
