import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CdseFrpAcquirer, CDSE_FRP_NTC_COLLECTION } from '../apps/api/src/modules/world/sentinel3/cdse-frp-acquirer.mjs';
import { AcquisitionStore } from '../apps/api/src/modules/acquisition/acquisition-store.mjs';
import { loadConfig } from '../apps/api/src/config/env.mjs';
import { haversineKm } from '../packages/domain/src/geo.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),detectionDirectory=path.join(root,'data/validation/detection'),corpusPath=path.join(detectionDirectory,'portugal-2024-active-fire-corpus.json'),benchmarkPath=path.join(detectionDirectory,'portugal-2024-active-fire-benchmark.json'),outputPath=path.join(detectionDirectory,'sentinel3-portugal-2024-search.json'),config=loadConfig(),credentials={accessToken:Boolean(config.cdseAccessToken),username:Boolean(config.cdseUsername),password:Boolean(config.cdsePassword)};
const sha=(value)=>createHash('sha256').update(value).digest('hex');
const wait=(milliseconds)=>new Promise((resolve)=>setTimeout(resolve,milliseconds));
async function catalogueWithRetry(acquirer,options){for(let attempt=0;attempt<8;attempt+=1){try{return await acquirer.catalogue(options);}catch(error){if(!String(error?.message).includes('upstream_http_429')||attempt===7)throw error;await wait(Math.min(12_000,750*2**attempt));}}}
const corpus=JSON.parse(await readFile(corpusPath,'utf8')),benchmark=JSON.parse(await readFile(benchmarkPath,'utf8')),caseById=new Map(corpus.cases.map((item)=>[item.caseId,item])),eligible=benchmark.results.filter((item)=>item.referenceLabel==='FIRE_POSITIVE'&&item.evaluationEligibility?.eligible);
const ranked=[],seen=new Set();
function take(rows,reason,limit){for(const row of rows){if(ranked.length>=12||limit<=0)break;if(seen.has(row.caseId))continue;const item=caseById.get(row.caseId);if(!item)continue;seen.add(row.caseId);ranked.push({item,result:row,reason});limit-=1;}}
take(benchmark.errors.filter((item)=>item.failure==='FALSE_NEGATIVE').map((item)=>benchmark.results.find((row)=>row.caseId===item.caseId)).filter(Boolean),'V1_FALSE_NEGATIVE_LOW_SIGNAL',4);
take([...eligible].sort((a,b)=>Number(a.maxFrpMw)-Number(b.maxFrpMw)),'LOW_FRP_POSITIVE',3);
take([...eligible].filter((item)=>item.tags.includes('PHYSICAL_FIRST')).sort((a,b)=>Number(b.maxFrpMw)-Number(a.maxFrpMw)),'PHYSICAL_FIRST_HIGH_SUPPORT',3);
take([...eligible].filter((item)=>item.tags.includes('REPORT_FIRST')).sort((a,b)=>Number(b.maxFrpMw)-Number(a.maxFrpMw)),'REPORT_FIRST_HIGH_SUPPORT',2);

const acquisitionStore=new AcquisitionStore({filePath:config.acquisitionStateFile,archiveDir:config.rawArchiveDir});await acquisitionStore.initialize();
const acquirer=new CdseFrpAcquirer({username:config.cdseUsername,password:config.cdsePassword,accessToken:config.cdseAccessToken,acquisitionStore,pythonBinary:config.geoPython,tempRoot:path.join(root,'.tmp','sentinel3-search'),timeoutMs:config.cdseDownloadTimeoutMs,collection:CDSE_FRP_NTC_COLLECTION,maxProducts:8}),matrix=[];
for(const target of ranked){
  if(matrix.length)await wait(750);
  const start=new Date(Date.parse(target.item.alertAt)-12*3_600_000).toISOString(),end=new Date(Math.min(Date.parse(target.item.timeWindow.end),Date.parse(target.item.alertAt)+96*3_600_000)).toISOString(),catalogue=await catalogueWithRetry(acquirer,{start,end,limit:100,collection:CDSE_FRP_NTC_COLLECTION}),coordinate=target.item.geometry.coordinates;
  const intersecting=catalogue.products.filter((product)=>Array.isArray(product.bbox)&&coordinate[0]>=product.bbox[0]&&coordinate[0]<=product.bbox[2]&&coordinate[1]>=product.bbox[1]&&coordinate[1]<=product.bbox[3]);
  let outputs=[];if(acquirer.configured()&&intersecting.length)outputs=(await acquirer.acquire({start,end,limit:100,collection:CDSE_FRP_NTC_COLLECTION,productIds:intersecting.map((item)=>item.id),maxProducts:intersecting.length,selectionMode:'governed_systematic_fire_search'})).outputs;
  const positiveRows=outputs.flatMap((output)=>(output.parsed?.detections??[]).map((item)=>({...item,productId:output.item.id,rawSourceProductId:output.rawSourceProduct.id}))).filter((item)=>Number(item.frpMw)>0),associated=positiveRows.filter((item)=>haversineKm(coordinate,[Number(item.longitude),Number(item.latitude)])<=3&&Date.parse(item.observedAt??start)>=Date.parse(start)&&Date.parse(item.observedAt??end)<=Date.parse(end));
  matrix.push({rank:matrix.length+1,caseId:target.item.caseId,selectionReason:target.reason,coordinate,region:target.item.region,burnedAreaHa:target.item.burnedAreaHa,viirs:{firstPhysicalAt:target.item.firstPhysicalAt,latestPhysicalAt:target.item.latestPhysicalAt,maxFrpMw:target.result.maxFrpMw,observationCount:target.result.sourceQuality.observationCount,v1Decision:target.result.decision},searchWindow:{start,end},catalogue:{collection:CDSE_FRP_NTC_COLLECTION,totalPortugalProducts:catalogue.products.length,intersectingProducts:intersecting.length,products:intersecting.map((item)=>({id:item.id,platform:item.platform,observedAt:item.observedAt,bbox:item.bbox,asset:item.asset,officialItemUrl:item.officialItemUrl}))},acquisition:{state:acquirer.configured()?(outputs.length?'ACQUIRED_PARSED':'CONFIGURED_NO_INTERSECTING_ACQUISITION'):'BLOCKED_CREDENTIALS_UNAVAILABLE_TO_PROCESS',credentialFieldsPresent:credentials,downloadedProducts:outputs.length,archivedProducts:outputs.filter((item)=>item.rawSourceProduct).length,parsedProducts:outputs.filter((item)=>item.parsed?.ok).length,positiveFrpObservations:positiveRows.length,aoiRecords:outputs.reduce((sum,item)=>sum+Number(item.parsed?.aoiObservationCount??0),0),associationResult:associated.length?'PRODUCTION_RADIUS_TIME_CANDIDATE':'NO_3KM_TIME_WINDOW_MATCH',associatedObservations:associated.map((item)=>({productId:item.productId,rawSourceProductId:item.rawSourceProductId,coordinate:[Number(item.longitude),Number(item.latitude)],observedAt:item.observedAt,frpMw:Number(item.frpMw),confidence:item.confidence??null}))}});
}
let priorParseProof=null;try{const evidence=JSON.parse(await readFile(path.join(root,'data/validation/release/vigia-category-leadership-evidence.json'),'utf8'));priorParseProof=evidence.evidence?.sentinel3ParseProof??evidence.sentinel3ParseProof??null;}catch{}
const uniqueProducts=new Map();for(const row of matrix)for(const product of row.catalogue.products)uniqueProducts.set(product.id,product);const totals=matrix.reduce((sum,row)=>({downloadedProducts:sum.downloadedProducts+row.acquisition.downloadedProducts,archivedProducts:sum.archivedProducts+row.acquisition.archivedProducts,parsedProducts:sum.parsedProducts+row.acquisition.parsedProducts,positiveSentinel3Observations:sum.positiveSentinel3Observations+row.acquisition.positiveFrpObservations,associatedObservations:sum.associatedObservations+(row.acquisition.associatedObservations?.length??0)}),{downloadedProducts:0,archivedProducts:0,parsedProducts:0,positiveSentinel3Observations:0,associatedObservations:0});
const artifact={schema:'vigia.sentinel3-systematic-search.v2',generatedAt:new Date().toISOString(),inputs:{corpus:{path:path.relative(root,corpusPath),checksumSha256:sha(await readFile(corpusPath))},benchmark:{path:path.relative(root,benchmarkPath),checksumSha256:sha(await readFile(benchmarkPath))}},selectionPolicy:'Deterministic priority order: all V1 false negatives first, then lowest-FRP positives, high-support physical-first fires, and high-support report-first fires; de-duplicated to 12 targets.',credentialInheritance:{configured:acquirer.configured(),fieldsPresent:credentials,secretValuesRecorded:false,keychainAware:true,qualification:acquirer.configured()?'Credentials are securely inherited from environment or macOS Keychain; secret values are never recorded.':'No CDSE token or username/password pair is available to this process or macOS Keychain. Public catalogue search proceeds; protected asset download does not.'},searchSummary:{targetCases:matrix.length,catalogueQueries:matrix.length,uniqueIntersectingProducts:uniqueProducts.size,...totals,twoFamilyEvents:0},priorRuntimeParseProof:priorParseProof,matrix,releaseGate:{positiveSentinel3Observation:totals.positiveSentinel3Observations?'MET_POSITIVE_NATIVE_FRP':'NOT_MET_NO_PROTECTED_PRODUCTS_ACQUIRED',twoFamilyPhysicalEvent:totals.associatedObservations?'CANDIDATE_REQUIRES_PRODUCTION_HYPOTHESIS_PERSISTENCE':'NOT_MET_NO_POSITIVE_SENTINEL3_ASSOCIATION'}};
await mkdir(detectionDirectory,{recursive:true});await writeFile(outputPath,`${JSON.stringify(artifact,null,2)}\n`);console.log(JSON.stringify({outputPath,credentialConfigured:artifact.credentialInheritance.configured,...artifact.searchSummary,releaseGate:artifact.releaseGate},null,2));
