export const PROOF_STATUSES = Object.freeze([
  'NOT_YET_VALID', 'VALID', 'EXPIRED', 'REVOKED', 'UNKNOWN_ISSUER', 'INVALID_PROOF',
  'INVALID_SCOPE', 'MALFORMED', 'QUARANTINED', 'REPLAYED'
]);

export const TRUST_ZONES = Object.freeze([
  'PUBLIC_OBSERVATIONAL', 'PROVENANCE_BOUND', 'CRYPTOGRAPHICALLY_VERIFIED',
  'ORGANIZATION_AUTHORIZED', 'PRIVILEGED_OPERATIONAL'
]);

export const AUTHORITY_DECISIONS = Object.freeze([
  'AUTHORIZED', 'STEP_UP_REQUIRED', 'LIMITED', 'DENIED', 'QUARANTINED'
]);

export const CONTINUOUS_TRUST_DECISIONS = Object.freeze(['ALLOW', 'STEP_UP', 'LIMIT', 'DENY', 'QUARANTINE']);
export const PROOF_TYPES = Object.freeze(['ED25519']);
