function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function zoneFromEpsg(epsg){const value=Number(epsg);if(value>=32601&&value<=32660)return{zone:value-32600,south:false};if(value>=32701&&value<=32760)return{zone:value-32700,south:true};return null;}
function wgs84ToUtm(lon,lat,zone,south){const a=6378137,e=0.081819190842622,ep2=e*e/(1-e*e),k0=.9996;const rad=Math.PI/180,phi=lat*rad,lambda=lon*rad,lambda0=((zone-1)*6-180+3)*rad;const n=a/Math.sqrt(1-e*e*Math.sin(phi)**2),t=Math.tan(phi)**2,c=ep2*Math.cos(phi)**2,A=Math.cos(phi)*(lambda-lambda0);const e2=e*e,e4=e2*e2,e6=e4*e2;const M=a*((1-e2/4-3*e4/64-5*e6/256)*phi-(3*e2/8+3*e4/32+45*e6/1024)*Math.sin(2*phi)+(15*e4/256+45*e6/1024)*Math.sin(4*phi)-(35*e6/3072)*Math.sin(6*phi));let x=k0*n*(A+(1-t+c)*A**3/6+(5-18*t+t*t+72*c-58*ep2)*A**5/120)+500000;let y=k0*(M+n*Math.tan(phi)*(A*A/2+(5-t+9*c+4*c*c)*A**4/24+(61-58*t+t*t+600*c-330*ep2)*A**6/720));if(south)y+=10000000;return[x,y];}
function cropWindow(image,coordinate,radiusKm){const keys=image.getGeoKeys?.()??{},projection=zoneFromEpsg(keys.ProjectedCSTypeGeoKey);if(!projection)return null;const[easting,northing]=wgs84ToUtm(coordinate[0],coordinate[1],projection.zone,projection.south);const origin=image.getOrigin(),resolution=image.getResolution(),width=image.getWidth(),height=image.getHeight();if(!origin||!resolution)return null;const rx=Number(resolution[0]),ry=Number(resolution[1]);if(!Number.isFinite(rx)||!Number.isFinite(ry)||rx===0||ry===0)return null;const px=(easting-origin[0])/rx,py=ry<0?(northing-origin[1])/ry:(origin[1]-northing)/ry;const radius=Math.max(300,Math.abs(radiusKm*1000/rx));return[clamp(Math.floor(px-radius),0,width-1),clamp(Math.floor(py-radius),0,height-1),clamp(Math.ceil(px+radius),1,width),clamp(Math.ceil(py+radius),1,height)];}
function geoBbox(coordinate,radiusKm){const lat=coordinate[1],latDelta=radiusKm/111.32,lonDelta=radiusKm/(111.32*Math.max(.2,Math.cos(lat*Math.PI/180)));return[coordinate[0]-lonDelta,lat-latDelta,coordinate[0]+lonDelta,lat+latDelta];}
function drawRgb(canvas,rgb,width,height){canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false});const image=ctx.createImageData(width,height),out=image.data;for(let src=0,dst=0;src<rgb.length;src+=3,dst+=4){out[dst]=rgb[src];out[dst+1]=rgb[src+1];out[dst+2]=rgb[src+2];out[dst+3]=255;}ctx.putImageData(image,0,0);}
function indexColor(value,mode){
  if(!Number.isFinite(value))return[13,16,14];
  const t=clamp((value+1)/2,0,1);
  if(mode==='moisture'){const stops=[[93,49,29],[165,122,65],[34,45,40],[36,123,119],[135,214,205]];const p=t*(stops.length-1),i=Math.min(stops.length-2,Math.floor(p)),f=p-i;return stops[i].map((v,k)=>Math.round(v+(stops[i+1][k]-v)*f));}
  const stops=[[57,39,28],[137,103,52],[61,72,43],[39,116,58],[137,193,87]];const p=t*(stops.length-1),i=Math.min(stops.length-2,Math.floor(p)),f=p-i;return stops[i].map((v,k)=>Math.round(v+(stops[i+1][k]-v)*f));
}
function drawIndex(canvas,values,width,height,mode){canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false}),image=ctx.createImageData(width,height),out=image.data;for(let src=0,dst=0;src<values.length;src+=1,dst+=4){const color=indexColor(values[src],mode);out[dst]=color[0];out[dst+1]=color[1];out[dst+2]=color[2];out[dst+3]=255;}ctx.putImageData(image,0,0);}
export async function renderCog({url,canvas,coordinate,radiusKm=11,signal}){if(!url||!canvas||!globalThis.GeoTIFF?.fromUrl)return null;const tiff=await globalThis.GeoTIFF.fromUrl(url,{signal});const image=await tiff.getImage();const window=cropWindow(image,coordinate,radiusKm);const sourceWidth=window?window[2]-window[0]:image.getWidth(),sourceHeight=window?window[3]-window[1]:image.getHeight();const limit=2048,scale=Math.min(1,limit/Math.max(sourceWidth,sourceHeight)),width=Math.max(512,Math.round(sourceWidth*scale)),height=Math.max(512,Math.round(sourceHeight*scale));const rgb=await image.readRGB({window:window??undefined,width,height,resampleMethod:'bilinear',signal});drawRgb(canvas,rgb,width,height);canvas.dataset.cogReady='true';return{width,height,bbox:geoBbox(coordinate,radiusKm),sourceWidth,sourceHeight,nativeResolutionMeters:Math.abs(image.getResolution?.()?.[0]??10)};}
export async function readCogBand({url,coordinate,radiusKm=11,width=256,height=256,signal}){if(!url||!globalThis.GeoTIFF?.fromUrl)return null;const tiff=await globalThis.GeoTIFF.fromUrl(url,{signal});const image=await tiff.getImage();const window=cropWindow(image,coordinate,radiusKm);const values=await image.readRasters({window:window??undefined,width,height,samples:[0],interleave:true,resampleMethod:'bilinear',signal});return{values,width,height,bbox:geoBbox(coordinate,radiusKm),nativeResolutionMeters:Math.abs(image.getResolution?.()?.[0]??10)};}
export async function renderBandIndex({firstUrl,secondUrl,canvas,coordinate,radiusKm=11,mode='vegetation',signal}){if(!firstUrl||!secondUrl||!canvas)return null;const[first,second]=await Promise.all([readCogBand({url:firstUrl,coordinate,radiusKm,width:768,height:768,signal}),readCogBand({url:secondUrl,coordinate,radiusKm,width:768,height:768,signal})]);if(!first||!second)return null;const values=new Float32Array(first.values.length);for(let i=0;i<values.length;i+=1){const a=Number(first.values[i]),b=Number(second.values[i]),den=a+b;values[i]=Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(den)>1e-6?(a-b)/den:Number.NaN;}drawIndex(canvas,values,first.width,first.height,mode);canvas.dataset.cogReady='true';canvas.dataset.viewMode=mode;return{width:first.width,height:first.height,bbox:first.bbox,nativeResolutionMeters:Math.max(first.nativeResolutionMeters,second.nativeResolutionMeters),mode};}
