import { renderScreeningResult } from './change-screening-renderer.js';
import { renderBandIndex, renderCog } from './cog-raster.js';
import { ensureGeoTiff } from './geotiff-loader.js';
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function labelCoordinate(coordinate){if(!coordinate)return'Pointer outside observation';const[lon,lat]=coordinate;return`${Math.abs(lat).toFixed(4)}° ${lat>=0?'N':'S'} · ${Math.abs(lon).toFixed(4)}° ${lon>=0?'E':'W'}`;}
function coordinateFromFrame(frame){const value=String(frame?.dataset.coordinate??'').split(',').map(Number);return value.length===2&&value.every(Number.isFinite)?value:null;}
function geoAt(frame,event){const bbox=String(frame.dataset.bbox??'').split(',').map(Number);if(bbox.length!==4||!bbox.every(Number.isFinite))return null;const rect=frame.getBoundingClientRect(),px=clamp((event.clientX-rect.left)/rect.width,0,1),py=clamp((event.clientY-rect.top)/rect.height,0,1);return[bbox[0]+(bbox[2]-bbox[0])*px,bbox[3]-(bbox[3]-bbox[1])*py];}
export class ObservationStudio{
  constructor(root){this.root=root;this.frame=root.querySelector('[data-observation-frame]');this.before=root.querySelector('[data-observation-before]');this.after=root.querySelector('[data-observation-after]');this.beforeCog=root.querySelector('[data-cog-before]');this.afterCog=root.querySelector('[data-cog-after]');this.afterWrap=root.querySelector('[data-observation-after-wrap]');this.divider=root.querySelector('[data-observation-divider]');this.range=root.querySelector('[data-observation-slider]');this.transformTargets=[...root.querySelectorAll('[data-observation-transform]')];this.pointerReadout=root.querySelector('[data-pointer-coordinate]');this.beforeDate=root.querySelector('[data-before-date]');this.viewLegend=root.querySelector('[data-observation-view-legend]');this.findingLayer=root.querySelector('[data-finding-layer]');this.findingSummary=root.querySelector('[data-finding-summary]');this.findingButton=root.querySelector('[data-studio-action="findings"]');this.connectivityOverlay=root.querySelector('[data-connectivity-overlay]');this.zoom=1;this.x=0;this.y=0;this.mode='natural';this.drag=null;this.flickerTimer=null;this.cogController=new AbortController();this.analysisController=new AbortController();this.eventController=new AbortController();this.resizeObserver=null;this.compareDrag=false;const product=this.frame?.dataset.renderProduct;this.maxZoom=this.frame?.classList.contains('observation-fallback-frame')?1.25:product==='browse_preview'?2:4;if(this.frame)this.bind();}
  on(node,type,handler,options={}){node?.addEventListener(type,handler,{...options,signal:this.eventController.signal});}
  bind(){this.on(this.range,'input',()=>this.syncDivider());this.on(this.divider,'pointerdown',(event)=>this.startDividerDrag(event));this.on(this.divider,'pointermove',(event)=>this.moveDividerDrag(event));this.on(this.divider,'pointerup',(event)=>this.endDividerDrag(event));this.on(this.divider,'pointercancel',(event)=>this.endDividerDrag(event));this.on(this.frame,'wheel',(event)=>{event.preventDefault();this.setZoom(this.zoom*(event.deltaY>0?.88:1.14));},{passive:false});this.on(this.frame,'pointerdown',(event)=>this.startDrag(event));this.on(this.frame,'pointermove',(event)=>this.pointerMove(event));this.on(this.frame,'pointerup',(event)=>this.endDrag(event));this.on(this.frame,'pointercancel',(event)=>this.endDrag(event));this.on(this.root,'click',(event)=>this.click(event));this.resizeObserver=new ResizeObserver(()=>this.syncDivider());this.resizeObserver.observe(this.frame);this.syncDivider();this.applyTransform();this.loadNativeRasters();}
  async loadNativeRasters(){const analysis=this.analyzeChange();await this.renderMode('natural');await analysis;}
  async renderMode(mode){const coordinate=coordinateFromFrame(this.frame),radiusKm=Number(this.frame?.dataset.radiusKm??9);if(!coordinate||!this.beforeCog||!this.afterCog)return;const geotiff=await ensureGeoTiff();if(!geotiff?.fromUrl)return;this.cogController.abort('view_mode_changed');this.cogController=new AbortController();const signal=this.cogController.signal;try{let results;if(mode==='natural')results=await Promise.all([renderCog({url:this.beforeCog.dataset.cogUrl,canvas:this.beforeCog,coordinate,radiusKm,signal}),renderCog({url:this.afterCog.dataset.cogUrl,canvas:this.afterCog,coordinate,radiusKm,signal})]);else{const second=mode==='vegetation'?'red':'swir';results=await Promise.all([renderBandIndex({firstUrl:this.beforeCog.dataset.nirUrl,secondUrl:this.beforeCog.dataset[`${second}Url`],canvas:this.beforeCog,coordinate,radiusKm,mode,signal}),renderBandIndex({firstUrl:this.afterCog.dataset.nirUrl,secondUrl:this.afterCog.dataset[`${second}Url`],canvas:this.afterCog,coordinate,radiusKm,mode,signal})]);}if(results.some((item)=>!item))return;this.mode=mode;if(this.before)this.before.hidden=true;if(this.after)this.after.hidden=true;this.frame.dataset.renderProduct='native_cog_crop';this.frame.dataset.viewMode=mode;this.maxZoom=5;this.frame.dataset.bbox=results[1].bbox.join(',');for(const button of this.root.querySelectorAll('[data-studio-action="natural"],[data-studio-action="vegetation"],[data-studio-action="moisture"]'))button.classList.toggle('is-active',button.dataset.studioAction===mode);if(this.viewLegend)this.viewLegend.textContent=mode==='natural'?'Natural colour · native pixels':mode==='vegetation'?'Vegetation index · NIR − red / NIR + red':'Moisture index · NIR − SWIR / NIR + SWIR';this.root.querySelector('.observation-suitability')?.setAttribute('data-native-raster','true');this.root.dispatchEvent(new CustomEvent('vigia:raster-ready',{bubbles:true,detail:{product:'native_cog_crop',mode,resolutionMeters:results[1].nativeResolutionMeters}}));}catch(error){if(signal.aborted)return;console.warn('Verified native observation view failed; no substitute image was used.',error);}}
  async click(event){const control=event.target.closest('[data-studio-action]');if(control){const action=control.dataset.studioAction;if(action==='zoom-in')this.setZoom(this.zoom*1.2);if(action==='zoom-out')this.setZoom(this.zoom/1.2);if(action==='fit')this.reset();if(action==='flicker')this.toggleFlicker(control);if(action==='findings')this.toggleFindings(control);if(['connectivity','assets','consensus'].includes(action))return;if(['natural','vegetation','moisture'].includes(action))await this.renderMode(action);return;}const scene=event.target.closest('[data-observation-scene]');if(!scene||!this.beforeCog)return;this.frame.dataset.comparableId=scene.dataset.sceneId||'';this.beforeCog.dataset.cogReady='false';this.beforeCog.dataset.cogUrl=scene.dataset.cogUrl||'';this.beforeCog.dataset.redUrl=scene.dataset.redUrl||'';this.beforeCog.dataset.nirUrl=scene.dataset.nirUrl||'';this.beforeCog.dataset.swirUrl=scene.dataset.swirUrl||'';if(this.before){this.before.hidden=true;this.before.removeAttribute('src');}if(this.beforeDate)this.beforeDate.textContent=scene.dataset.dateLabel;for(const button of this.root.querySelectorAll('[data-observation-scene]'))button.classList.toggle('is-active',button===scene);if(!scene.dataset.cogUrl&&scene.dataset.imageUrl&&this.before){this.before.src=scene.dataset.imageUrl;this.before.hidden=false;}await this.renderMode(this.mode);await this.analyzeChange();}
  startDividerDrag(event){event.preventDefault();event.stopPropagation();this.compareDrag=true;this.divider.setPointerCapture?.(event.pointerId);this.moveDividerDrag(event);}
  moveDividerDrag(event){if(!this.compareDrag||!this.frame||!this.range)return;const rect=this.frame.getBoundingClientRect(),value=clamp((event.clientX-rect.left)/rect.width*100,0,100);this.range.value=String(value);this.syncDivider();}
  endDividerDrag(event){this.compareDrag=false;this.divider?.releasePointerCapture?.(event.pointerId);}
  startDrag(event){if(event.target.closest('button,input,.observation-divider'))return;this.frame.setPointerCapture?.(event.pointerId);this.drag={startX:event.clientX,startY:event.clientY,x:this.x,y:this.y};}
  pointerMove(event){if(this.pointerReadout)this.pointerReadout.textContent=labelCoordinate(geoAt(this.frame,event));if(!this.drag||this.zoom<=1)return;this.x=this.drag.x+event.clientX-this.drag.startX;this.y=this.drag.y+event.clientY-this.drag.startY;this.applyTransform();}
  endDrag(event){this.frame.releasePointerCapture?.(event.pointerId);this.drag=null;}
  setZoom(value){this.zoom=clamp(value,1,this.maxZoom);if(this.zoom===1){this.x=0;this.y=0;}this.applyTransform();}
  reset(){this.zoom=1;this.x=0;this.y=0;this.applyTransform();}
  applyTransform(){for(const node of this.transformTargets)node.style.transform=`translate(${this.x}px, ${this.y}px) scale(${this.zoom})`;}
  syncDivider(){const value=Number(this.range?.value??50);if(this.afterWrap)this.afterWrap.style.width=`${value}%`;if(this.divider)this.divider.style.left=`${value}%`;if(this.frame){const width=`${this.frame.clientWidth}px`,height=`${this.frame.clientHeight}px`,afterTransform=this.afterWrap?.querySelector('[data-observation-transform]');if(afterTransform){afterTransform.style.width=width;afterTransform.style.height=height;}if(this.after){this.after.style.width=width;this.after.style.height=height;}}}
  toggleFlicker(button){if(this.flickerTimer){clearInterval(this.flickerTimer);this.flickerTimer=null;this.afterWrap.style.opacity='1';button.classList.remove('is-active');return;}let visible=true;this.flickerTimer=setInterval(()=>{visible=!visible;this.afterWrap.style.opacity=visible?'1':'0';},430);button.classList.add('is-active');}
  toggleFindings(button){if(!this.findingLayer)return;const hidden=this.findingLayer.classList.toggle('is-hidden');button.classList.toggle('is-active',!hidden);}
  toggleConnectivity(button,layer){if(!this.connectivityOverlay)return;const selector={connectivity:'.fuel-graph-lines',assets:'.fuel-asset-connections',consensus:'.fuel-consensus-zone'}[layer],group=this.connectivityOverlay.querySelector(selector),hidden=group?.classList.toggle('is-hidden');button.classList.toggle('is-active',!hidden);}
  async analyzeChange(){if(!this.frame?.dataset.changeScreening||this.frame.dataset.changeScreening==='off')return;const coordinate=coordinateFromFrame(this.frame);if(!coordinate)return;this.analysisController.abort('analysis_replaced');this.analysisController=new AbortController();if(this.findingSummary){this.findingSummary.classList.add('is-loading');this.findingSummary.textContent='Running server-side native spectral screening…';}try{const params=new URLSearchParams({lon:String(coordinate[0]),lat:String(coordinate[1]),radiusKm:String(Number(this.frame.dataset.radiusKm??9)),primaryId:this.frame.dataset.primaryId||'',comparableId:this.frame.dataset.comparableId||''});const response=await fetch(`/api/v10/observations/change-screening?${params}`,{signal:this.analysisController.signal});if(!response.ok)throw new Error(`screening_http_${response.status}`);const result=await response.json();renderScreeningResult({result,layer:this.findingLayer,summary:this.findingSummary,button:this.findingButton});}catch(error){if(this.analysisController.signal.aborted)return;renderScreeningResult({result:{state:'abstained',reason:String(error.message??error),findings:[],calibrationState:'unvalidated_screening'},layer:this.findingLayer,summary:this.findingSummary,button:this.findingButton});}}
  destroy(){this.cogController.abort('studio_destroyed');this.analysisController.abort('studio_destroyed');this.eventController.abort('studio_destroyed');if(this.flickerTimer)clearInterval(this.flickerTimer);this.resizeObserver?.disconnect();}
}
