import { immutable, isoTime, semanticHash } from '../intelligence/shared.mjs';

const changes = (before = [], after = [], id, state) => { const left = new Map(before.map((item) => [item[id], item])), right = new Map(after.map((item) => [item[id], item])); return [...new Set([...left.keys(), ...right.keys()])].sort().flatMap((key) => { const prior = left.get(key), next = right.get(key), from = prior?.[state] ?? null, to = next?.[state] ?? null; return from === to ? [] : [{ id: key, from, to, beforeFingerprint: prior?.fingerprint ?? null, afterFingerprint: next?.fingerprint ?? null }]; }); };
const ids = (value) => [...new Set(value ?? [])].sort();
export function calculateDecisionDelta({ before, after, policies = [], actions = [], knowledgeTime } = {}) {
  const hypothesisChanges = changes(before?.hypotheses?.results, after?.hypotheses?.results, 'hypothesisId', 'state'), decisionChanges = changes(before?.decisions?.results, after?.decisions?.results, 'decisionId', 'state'), beforeGaps = new Set((before?.openDataGaps ?? []).map((item) => item.id)), afterGaps = new Set((after?.openDataGaps ?? []).map((item) => item.id)), beforeNeeds = new Set(before?.evidenceNeedIds ?? []), afterNeeds = new Set(after?.evidenceNeedIds ?? []);
  const core = { schemaVersion: 'vigia.decision-delta.v1', incidentId: after?.incident?.id ?? before?.incident?.id ?? null, knowledgeTime: isoTime(knowledgeTime, 'decision_delta_time_required'), hypothesisChanges, decisionChanges, conclusionsChanged: hypothesisChanges.map((item) => item.id), actionsBecameAvailable: ids(decisionChanges.filter((item) => item.to === 'READY').flatMap((item) => after?.decisions?.results.find((row) => row.decisionId === item.id)?.actionsUnlocked ?? [])), actionsBecameBlocked: ids(decisionChanges.filter((item) => item.from === 'READY').flatMap((item) => before?.decisions?.results.find((row) => row.decisionId === item.id)?.actionsUnlocked ?? [])), evidenceNeedsOpened: [...afterNeeds].filter((id) => !beforeNeeds.has(id)).sort(), evidenceNeedsClosed: [...beforeNeeds].filter((id) => !afterNeeds.has(id)).sort(), dataGapsOpened: [...afterGaps].filter((id) => !beforeGaps.has(id)).sort(), dataGapsClosed: [...beforeGaps].filter((id) => !afterGaps.has(id)).sort(), causingDataProductIds: ids(after?.causingDataProductIds), policyFingerprints: ids(policies.map((item) => item.fingerprint)), operatorAttentionRequired: decisionChanges.some((item) => ['BLOCKED_BY_AUTHORITY', 'BLOCKED_BY_TRUST'].includes(item.to)) || actions.some((item) => item.operatorAttentionRequired) };
  return immutable({ ...core, fingerprint: semanticHash('decision-delta', core) });
}
