import { immutable, semanticHash } from '../intelligence/shared.mjs';
import { ACQUISITION_PLAN_STATES } from './constants.mjs';

function initialState(row) { if (row.blockingConditions.includes('CREDENTIALS_REQUIRED')) return 'CREDENTIALS_REQUIRED'; if (row.blockingConditions.includes('PARTNER_REQUIRED')) return 'PARTNER_REQUIRED'; if (row.rights !== 'READY') return 'RIGHTS_BLOCKED'; if (!row.components.coverageReady) return 'OUTSIDE_COVERAGE'; if (!row.components.sourceAvailable || !row.components.sourceHealthy) return 'SOURCE_DEGRADED'; if (row.components.causalDuplicationRisk) return 'CAUSAL_DUPLICATE'; if (row.blockingConditions.includes('NO_VALID_OBSERVATION_OPPORTUNITY')) return 'NO_VALID_OBSERVATION_OPPORTUNITY'; return 'ELIGIBLE'; }
export function planIntelligenceAcquisitions({ rankedCandidates = [], budgets, existingTaskCandidateIds = [], completedCandidateIds = [], maximumSelections = 1 } = {}) {
  if (!budgets || !Number.isSafeInteger(budgets.maxAcquisitionsPerIncident) || !Number.isFinite(budgets.maxBytesPerIncident) || !Number.isSafeInteger(budgets.maxRequestsPerProvider) || !Number.isSafeInteger(budgets.maxProviderRetries) || !Number.isSafeInteger(budgets.maxConcurrentTasks) || !Number.isFinite(budgets.maxEstimatedCostUnits) || !Number.isSafeInteger(budgets.maxControllerCycles) || !Number.isSafeInteger(budgets.maxBlockedProviderAttempts)) throw new Error('acquisition_budget_state_required');
  const existing = new Set(existingTaskCandidateIds), completed = new Set(completedCandidateIds), providerCounts = new Map(), incidentCounts = new Map(), selected = [];
  const items = rankedCandidates.map((candidate) => {
    let state = completed.has(candidate.candidateId) ? 'COMPLETED' : existing.has(candidate.candidateId) ? 'SCHEDULED' : initialState(candidate), reason = null;
    const providerCount = providerCounts.get(candidate.provider) ?? 0, incidentCount = incidentCounts.get(candidate.incidentId) ?? 0;
    const budgetBlocked = candidate.cost.expectedBytes > budgets.maxBytesPerIncident || candidate.cost.estimatedCostUnits > budgets.maxEstimatedCostUnits || providerCount >= budgets.maxRequestsPerProvider || incidentCount >= budgets.maxAcquisitionsPerIncident || candidate.risk.retryAttempts >= budgets.maxProviderRetries || selected.length >= budgets.maxConcurrentTasks;
    if (state === 'ELIGIBLE' && budgetBlocked) { state = 'BUDGET_BLOCKED'; reason = 'EXPLICIT_ACQUISITION_BUDGET_EXCEEDED'; }
    if (state === 'ELIGIBLE' && selected.length < Math.min(maximumSelections, budgets.maxConcurrentTasks)) { state = 'SELECTED'; selected.push(candidate.candidateId); providerCounts.set(candidate.provider, providerCount + 1); incidentCounts.set(candidate.incidentId, incidentCount + 1); }
    if (!ACQUISITION_PLAN_STATES.includes(state)) throw new Error('acquisition_plan_state_invalid');
    return { id: semanticHash('intelligence-acquisition-plan-item', { candidateId: candidate.candidateId, state }), candidateId: candidate.candidateId, incidentId: candidate.incidentId, provider: candidate.provider, requirement: candidate.requirement, state, reason, decisionValueFingerprint: candidate.fingerprint, whyNow: candidate.explanation, decisionsAffected: candidate.decisionsAffected, hypothesesSeparated: candidate.hypothesesSeparated, contractsPotentiallySatisfied: candidate.contractsPotentiallySatisfied, horizonsUnlocked: candidate.horizonsUnlocked, forecastExamplesUnlocked: candidate.forecastExamplesUnlocked, independence: candidate.independentFamilyGained ? 'NEW_INDEPENDENT_FAMILY' : candidate.risk.causalDuplication === 'HIGH' ? 'CAUSAL_DUPLICATE' : 'NO_NEW_FAMILY', cost: candidate.cost, failureModes: candidate.blockingConditions, fallback: candidate.fallback ?? null };
  });
  const core = { schemaVersion: 'vigia.intelligence-acquisition-plan.v1', budgets: structuredClone(budgets), items, selectedCandidateIds: selected };
  return immutable({ ...core, fingerprint: semanticHash('intelligence-acquisition-plan', core) });
}
