import { mkdir,readFile,writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CapFeedAdapter,FileCapIntegrationRepository } from '../../apps/api/src/modules/integrations/cap-feed-adapter.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),output=path.resolve(process.env.VIGIA_CAP_ACCEPTANCE_OUTPUT??path.join(root,'.tmp/operational-maturity-75/cap-integration-acceptance.json')),stateFile=path.resolve(process.env.VIGIA_CAP_STATE_FILE??path.join(root,'.tmp/operational-maturity-75/cap-integration-state.json'));
const endpoint=String(process.env.VIGIA_CAP_PARTNER_URL??process.env.VIGIA_CAP_FEED_URL??''),token=String(process.env.VIGIA_CAP_PARTNER_TOKEN??process.env.VIGIA_CAP_BEARER_TOKEN??''),bindingsFile=String(process.env.VIGIA_CAP_INCIDENT_BINDINGS_FILE??'');
async function bindings(){if(!bindingsFile)return{};const resolved=path.resolve(bindingsFile),body=JSON.parse(await readFile(resolved,'utf8'));if(!body||Array.isArray(body)||typeof body!=='object')throw new Error('cap_bindings_invalid');return body;}
const bindingMap=await bindings(),projections=[],repository=new FileCapIntegrationRepository({filePath:stateFile}),adapter=new CapFeedAdapter({endpoint,bearerToken:token,repository,bindIncident:async alert=>{const incidentId=String(bindingMap[alert.identifier]??'');return incidentId?{incidentId}:null;},projectIncident:async projection=>projections.push(projection)}),startedAt=new Date().toISOString(),result=await adapter.poll(),completedAt=new Date().toISOString();
const evidence={schemaVersion:'vigia.cap-integration-acceptance.v1',startedAt,completedAt,mode:endpoint?'REAL_CONFIGURED_ENDPOINT':'NOT_CONFIGURED',endpointHost:endpoint?new URL(endpoint).hostname:null,authentication:endpoint?(token?'BEARER_CONFIGURED':'PUBLIC_OR_UPSTREAM_AUTH'):'NOT_CONFIGURED',bindingCount:Object.keys(bindingMap).length,result,projectedIncidents:projections.map(item=>({incidentId:item.incidentId,externalIncidentId:item.externalIncidentId,sourceFamily:item.sourceFamily,physicalEvidence:item.physicalEvidence,provenance:item.provenance})),secretsRecorded:false,gate:{configured:Boolean(endpoint),realInboundFlow:result.outcomes?.some(item=>item.state==='ACCEPTED')??false,persistedProjection:(result.accepted??0)>0,operatorProjectionReady:projections.length>0,liveScoreEligible:Boolean(endpoint)&&projections.length>0}};
await mkdir(path.dirname(output),{recursive:true});await writeFile(output,`${JSON.stringify(evidence,null,2)}\n`,{mode:0o600});console.log(JSON.stringify({state:result.state,mode:evidence.mode,endpointHost:evidence.endpointHost,accepted:result.accepted,quarantined:result.quarantined,output:path.relative(root,output)}));
if(endpoint&&!evidence.gate.liveScoreEligible)process.exitCode=2;
