import path from 'node:path';
import { readdir, readFile } from 'node:fs/promises';
import { semanticHash, uniqueSorted } from '../../../../../packages/domain/src/intelligence/shared.mjs';
import { createDataProduct, createDataProductVersion, createForecastInputPackage, createLineageEdge, createLineageNode, deriveIncidentDataGaps, planDataGapResolution, propagateRights, verifyLineageGraph } from '../../../../../packages/domain/src/data-foundry/index.mjs';
import { readJson, writeJsonAtomic } from '../../shared/json-file.mjs';
import { corpusPaths } from '../forecast-corpus/corpus-paths.mjs';
import { dataFoundryPaths } from './foundry-paths.mjs';

const licenceRights = (id) => ({ id, licenceIds: [id].filter(Boolean), rawRedistribution: ['NOAA-HRRR-PUBLIC-DATA', 'USFS-LANDFIRE-PUBLIC-DATA', 'NIFC-OPEN-DATA', 'NASA-FEDS-TERMS', 'NASA-FIRMS-TERMS'].includes(id), derivedRedistribution: true, attributions: id ? [id] : [] });
const safeTime = (value, fallback) => Number.isFinite(Date.parse(value)) ? new Date(value).toISOString() : fallback;
const hash = (value) => value.startsWith?.('sha256:') || value.includes?.(':sha256:') ? value : `sha256:${value}`;
async function loadWeatherSlices(directory) { const files = (await readdir(directory).catch(() => [])).filter((file) => file.endsWith('.json')).sort(), rows = []; for (const file of files) rows.push(JSON.parse(await readFile(path.join(directory, file), 'utf8'))); return rows; }

function addNode(nodes, node) { if (!nodes.some((item) => item.id === node.id)) nodes.push(node); }
function addEdge(edges, edge) { if (!edges.some((item) => item.id === edge.id)) edges.push(edge); }
function edge(source, target, transformation, version = 'vigia.data-foundry.v1') { return createLineageEdge({ id: semanticHash('lineage-edge-id', { source: source.id, target: target.id, transformation, version }), sourceId: source.id, targetId: target.id, transformation, codeVersion: version, inputHash: source.contentHash, outputHash: target.contentHash, rightsPropagation: target.rights, qualityResult: { passed: true }, createdAt: target.createdAt }); }

export async function buildDataFoundryCatalog({ projectRoot = process.cwd() } = {}) {
  const foundry = dataFoundryPaths(projectRoot), corpus = corpusPaths(projectRoot), acquisition = await readJson(corpus.acquisitionState, { products: {} }), gold = await readJson(path.join(corpus.gold, 'forecast-corpus.json'), { incidents: [], examples: [], rejections: [], splits: { cases: [], counts: {} }, readiness: {} }), slices = await loadWeatherSlices(path.join(corpus.runtime, 'materialized/weather')), fedsProducts = await loadWeatherSlices(path.join(foundry.runtime, 'feds'));
  const products = [], versions = [], nodes = [], edges = [], incidentProducts = {}, packages = [], fallbackTime = '1970-01-01T00:00:00.000Z';
  for (const raw of Object.values(acquisition.products).sort((a, b) => a.id.localeCompare(b.id))) {
    const productId = `provider:${raw.provider}:${raw.sourceId}`, versionId = `version:${raw.id}`, createdAt = safeTime(raw.receivedAt, fallbackTime), rights = licenceRights(raw.licenceMetadata?.licenceId), contentHash = hash(raw.checksumSha256);
    if (!products.some((item) => item.id === productId)) products.push(createDataProduct({ id: productId, name: raw.sourceId, kind: 'RAW_ARTIFACT', ontologyObjectType: 'RawArtifact', owner: raw.provider, currentVersionId: versionId, createdAt }));
    versions.push(createDataProductVersion({ id: versionId, productId, semanticVersion: '1.0.0', dataSchemaVersion: raw.parserVersion ?? 'raw.v1', contentFingerprint: contentHash, provider: raw.provider, sourceProduct: raw.providerProductId, coverage: { requestWindow: raw.requestWindow }, timeRange: raw.sourceTimestampRange ?? { from: raw.sourceTimestamp, to: raw.sourceTimestamp }, maturity: 'OPERATIONAL', rights, qualityState: raw.processingState === 'ingested' ? 'PASSED' : 'PENDING', lineageRoot: raw.id, clocks: { providerPublishedAt: raw.sourceTimestamp, providerRetrievedAt: raw.retrievedAt, availableToVigiaAt: raw.retrievedAt, canonicalIngestedAt: raw.ingestedAt }, parserVersion: raw.parserVersion ?? 'raw.v1', contractVersion: 'raw-envelope.v1', createdAt }));
    addNode(nodes, createLineageNode({ id: raw.id, kind: 'RAW_ARTIFACT', contentHash, rights, createdAt }));
  }
  for (const incident of gold.incidents ?? []) {
    const bindings = [], entry = { incidentId: incident.id, region: incident.region, season: incident.season, dataProductVersionIds: [] };
    const sequenceCore = { incidentId: incident.id, sourceClass: incident.perimeterSourceClass, stateIds: (incident.perimeterStates ?? []).map((item) => item.id), stateHashes: (incident.perimeterStates ?? []).map((item) => item.originalGeometryHash) }, sequenceHash = semanticHash('perimeter-sequence', sequenceCore), sequenceProductId = `incident:${incident.id}:perimeter-sequence`, sequenceVersionId = `version:${sequenceHash}`;
    products.push(createDataProduct({ id: sequenceProductId, name: `${incident.id} perimeter sequence`, kind: 'MATERIALIZED_DATASET', ontologyObjectType: 'PerimeterSequence', currentVersionId: sequenceVersionId, createdAt: safeTime(incident.discoveryTime, fallbackTime) }));
    versions.push(createDataProductVersion({ id: sequenceVersionId, productId: sequenceProductId, semanticVersion: '1.0.0', dataSchemaVersion: 'vigia.perimeter-sequence.v1', contentFingerprint: sequenceHash, provider: incident.region === 'portugal' ? 'ICNF' : 'nifc-wfigs-daily', sourceProduct: incident.perimeterSourceClass, ontologyBindings: [incident.id], coverage: { region: incident.region }, timeRange: { from: incident.perimeterStates?.[0]?.clocks?.observedAt ?? incident.discoveryTime, to: incident.perimeterStates?.at(-1)?.clocks?.observedAt ?? incident.discoveryTime }, maturity: incident.perimeterSourceClass === 'FINAL_ONLY' ? 'RETROSPECTIVE' : 'PROVISIONAL', rights: licenceRights(incident.region === 'portugal' ? 'ICNF-ATTRIBUTION' : 'NIFC-OPEN-DATA'), qualityState: (incident.perimeterStates?.length ?? 0) >= 3 ? 'PASSED' : 'FAILED', lineageRoot: sequenceVersionId, clocks: { physicalOccurredAt: incident.discoveryTime, availableToVigiaAt: incident.perimeterStates?.at(-1)?.clocks?.availableToVigiaAt ?? incident.discoveryTime, materializedAt: incident.perimeterStates?.at(-1)?.clocks?.canonicalIngestedAt ?? incident.discoveryTime }, parserVersion: 'vigia.perimeter-sequence-materializer.v1', contractVersion: 'vigia.perimeter-sequence-contract.v1', createdAt: safeTime(incident.discoveryTime, fallbackTime) }));
    const sequenceNode = createLineageNode({ id: sequenceVersionId, kind: 'CANONICAL_DATASET', contentHash: sequenceHash, rights: licenceRights(incident.region === 'portugal' ? 'ICNF-ATTRIBUTION' : 'NIFC-OPEN-DATA'), createdAt: safeTime(incident.discoveryTime, fallbackTime) }); addNode(nodes, sequenceNode); bindings.push(sequenceVersionId);
    for (const state of incident.perimeterStates ?? []) for (const rawId of state.bronzeRefs ?? []) { const rawNode = nodes.find((item) => item.id === rawId); if (rawNode) addEdge(edges, edge(rawNode, sequenceNode, 'NORMALIZE_WFIGS_STATE', 'vigia.wfigs-daily-geojson.v1')); }
    for (const slice of slices.filter((item) => item.incidentId === incident.id)) {
      const productId = `incident:${incident.id}:weather-slice`, versionId = `version:${slice.id}`;
      products.push(createDataProduct({ id: productId, name: `${incident.id} incident-local weather`, kind: 'DATASET_SLICE', ontologyObjectType: 'WeatherRun', currentVersionId: versionId, createdAt: slice.issueTime }));
      const rights = licenceRights('NOAA-HRRR-PUBLIC-DATA'); versions.push(createDataProductVersion({ id: versionId, productId, semanticVersion: '1.0.0', dataSchemaVersion: slice.schemaVersion, contentFingerprint: slice.fingerprint, provider: 'noaa-hrrr-archive', sourceProduct: slice.weatherRunId, ontologyBindings: [incident.id], coverage: { bbox: slice.bbox }, timeRange: { from: slice.issueTime, to: slice.validTimes.at(-1) }, maturity: 'OPERATIONAL', rights, qualityState: slice.qualityState, lineageRoot: versionId, clocks: { physicalOccurredAt: slice.issueTime, availableToVigiaAt: incident.weatherRuns?.find((run) => run.runId === slice.weatherRunId)?.availableToVigiaAt ?? slice.issueTime, materializedAt: slice.issueTime }, parserVersion: `rasterio-${slice.decoderVersion}`, contractVersion: slice.contractResult.contractVersion, createdAt: slice.issueTime }));
      const sliceNode = createLineageNode({ id: versionId, kind: 'DATASET_SLICE', contentHash: slice.fingerprint, rights, createdAt: slice.issueTime }); addNode(nodes, sliceNode); bindings.push(versionId);
      for (const field of slice.fields) { const rawId = `raw:noaa-hrrr-archive:hrrr_conus_message:${field.sourceHash}`, rawNode = nodes.find((item) => item.id === rawId); if (rawNode) addEdge(edges, edge(rawNode, sliceNode, 'DECODE_GRIB_AND_EXTRACT_INCIDENT_WINDOW', `rasterio-${slice.decoderVersion}`)); }
    }
    for (const feds of fedsProducts.filter((item) => item.incidentId === incident.id)) {
      const productId = `incident:${incident.id}:feds-progression`, versionId = `version:${feds.fingerprint}`, rights = licenceRights('NASA-FEDS-TERMS'); products.push(createDataProduct({ id: productId, name: `${incident.id} FEDS VIIRS-derived progression`, kind: 'MATERIALIZED_DATASET', ontologyObjectType: 'PhysicalObservationSequence', currentVersionId: versionId, createdAt: feds.retrievedAt }));
      versions.push(createDataProductVersion({ id: versionId, productId, semanticVersion: '1.0.0', dataSchemaVersion: feds.schemaVersion, contentFingerprint: feds.fingerprint, provider: 'nasa-feds', sourceProduct: 'FEDS_FIRE_PERIMETERS_NRT', ontologyBindings: [incident.id], coverage: { bbox: feds.bbox, stateCount: feds.states?.length ?? 0 }, timeRange: { from: feds.states?.[0]?.observedAt, to: feds.states?.at(-1)?.observedAt }, maturity: 'RETROSPECTIVE', rights, qualityState: feds.states?.length ? 'PASSED_RETROSPECTIVE_ONLY' : 'FAILED', lineageRoot: versionId, clocks: { providerRetrievedAt: feds.retrievedAt, availableToVigiaAt: feds.retrievedAt, materializedAt: feds.retrievedAt }, parserVersion: 'vigia.feds-geojson.v1', contractVersion: 'vigia.feds-progression-contract.v1', createdAt: feds.retrievedAt })); const fedsNode = createLineageNode({ id: versionId, kind: 'CANONICAL_DATASET', contentHash: feds.fingerprint, rights, createdAt: feds.retrievedAt }); addNode(nodes, fedsNode); bindings.push(versionId); const rawNode = nodes.find((item) => item.id === feds.rawProductId); if (rawNode) addEdge(edges, edge(rawNode, fedsNode, 'NORMALIZE_FEDS_VIIRS_DERIVED_PROGRESSION', 'vigia.feds-geojson.v1'));
    }
    entry.dataProductVersionIds = uniqueSorted(bindings); incidentProducts[incident.id] = entry;
  }
  for (const example of gold.examples ?? []) {
    const rights = propagateRights([{ ...licenceRights('NIFC-OPEN-DATA') }, { ...licenceRights('NOAA-HRRR-PUBLIC-DATA') }, { ...licenceRights('USFS-LANDFIRE-PUBLIC-DATA') }]), packageValue = createForecastInputPackage({ incidentId: example.incidentId, issueTime: example.issuedAt, horizonHours: example.horizonHours, knowledgeTimeCutoff: example.informationCutoff, perimeterStateIds: example.features.map((item) => item.id), physicalObservationIds: example.upstreamObservationIds, weatherSliceIds: incidentProducts[example.incidentId]?.dataProductVersionIds.filter((id) => id.includes('incident-weather-slice')) ?? [], fuelPackId: example.fuelPack?.datasetId, terrainPackId: example.terrainPack?.datasetId, futureLabelIds: [example.label.id], rightsManifest: rights, lineageManifest: { bronzeRefs: uniqueSorted(example.features.flatMap((item) => item.bronzeRefs ?? []).concat(example.label.bronzeRefs ?? [])) }, qualityResults: { eligible: true } });
    packages.push(packageValue); const packageNode = createLineageNode({ id: packageValue.id, kind: 'FORECAST_INPUT_PACKAGE', contentHash: packageValue.fingerprint, rights, createdAt: packageValue.issueTime }); addNode(nodes, packageNode);
    for (const upstreamId of incidentProducts[example.incidentId]?.dataProductVersionIds ?? []) { const upstream = nodes.find((item) => item.id === upstreamId); if (upstream) addEdge(edges, edge(upstream, packageNode, 'MATERIALIZE_FORECAST_INPUT_PACKAGE')); }
    const exampleHash = semanticHash('corpus-example', example), exampleNode = createLineageNode({ id: example.id, kind: 'CORPUS_EXAMPLE', contentHash: exampleHash, rights, createdAt: example.issuedAt }); addNode(nodes, exampleNode); addEdge(edges, edge(packageNode, exampleNode, 'BUILD_LEAKAGE_SAFE_CORPUS_EXAMPLE'));
    incidentProducts[example.incidentId].dataProductVersionIds.push(packageValue.id, example.id);
  }
  const incidentForGaps = (incident) => ({ ...incident, futureLabels: uniqueSorted((gold.examples ?? []).filter((example) => example.incidentId === incident.id).map((example) => example.horizonHours)).map((horizonHours) => ({ horizonHours: Number(horizonHours), qualityState: 'PASSED' })) });
  const gaps = (gold.incidents ?? []).flatMap((incident) => deriveIncidentDataGaps({ incident: incidentForGaps(incident) })), providerCapabilities = [{ provider: 'noaa-hrrr-archive', requirement: 'DECODED_WEATHER', covered: true, access: 'READY', rights: 'READY', expectedBytes: 8_000_000, expectedLatencyMs: 2_000 }, { provider: 'nifc-wfigs-daily', requirement: 'PROGRESSION_SEQUENCE', covered: true, access: 'READY', rights: 'READY', expectedBytes: 16_000_000, expectedLatencyMs: 8_000 }, { provider: 'nifc-wfigs-daily', requirement: 'FUTURE_LABEL', covered: true, access: 'READY', rights: 'READY', expectedBytes: 16_000_000, expectedLatencyMs: 8_000 }, { provider: 'usfs-landfire', requirement: 'FUEL_PACK', covered: true, access: 'READY', rights: 'READY', expectedBytes: 1_000_000, expectedLatencyMs: 10_000 }, { provider: 'usfs-landfire', requirement: 'TERRAIN_PACK', covered: true, access: 'READY', rights: 'READY', expectedBytes: 1_000_000, expectedLatencyMs: 10_000 }], plan = planDataGapResolution({ gaps, providerCapabilities, coverage: { 'noaa-hrrr-archive': ['western-us'], 'nifc-wfigs-daily': ['western-us'], 'usfs-landfire': ['western-us'] }, access: {}, rights: {}, costBudget: { maxBytes: 64 * 1024 * 1024 }, timeBudget: { maxLatencyMs: 60_000 } });
  versions.sort((a, b) => a.id.localeCompare(b.id)); nodes.sort((a, b) => a.id.localeCompare(b.id)); edges.sort((a, b) => a.id.localeCompare(b.id));
  const currentProducts = [...new Map(products.map((item) => [item.id, item])).values()].map((product) => { const candidates = versions.filter((version) => version.productId === product.id).sort((left, right) => Date.parse(left.createdAt) - Date.parse(right.createdAt) || left.id.localeCompare(right.id)), current = candidates.at(-1); return createDataProduct({ ...product, currentVersionId: current?.id ?? null }); }).sort((a, b) => a.id.localeCompare(b.id));
  const graph = { schemaVersion: 'vigia.data-lineage.v1', nodes, edges }, lineageVerification = verifyLineageGraph(graph), registryCore = { schemaVersion: 'vigia.data-product-registry.v1', products: currentProducts, versions, incidentProducts, packages, generatedFromCorpusFingerprint: gold.replay?.corpusFingerprint ?? null, consumerState: { corpusReadiness: gold.readiness, splitManifest: gold.splits, leakageAudit: gold.leakage, baselineEvaluation: gold.baselines } }, registry = { ...registryCore, fingerprint: semanticHash('data-product-registry', registryCore) };
  await Promise.all([writeJsonAtomic(foundry.registry, registry), writeJsonAtomic(foundry.lineage, { ...graph, verification: lineageVerification }), writeJsonAtomic(foundry.gaps, { schemaVersion: 'vigia.data-gap-graph.v1', gaps, fingerprint: semanticHash('data-gap-graph', gaps) }), writeJsonAtomic(foundry.plans, plan)]);
  return { registry, graph: { ...graph, verification: lineageVerification }, gaps, plan, gold };
}
