import path from 'node:path';
import { createHardNegative, createObservationOpportunity } from '../../../../../packages/domain/src/data-foundry/index.mjs';
import { readJson, writeJsonAtomic } from '../../shared/json-file.mjs';
import { corpusPaths } from '../forecast-corpus/corpus-paths.mjs';
import { dataFoundryPaths } from './foundry-paths.mjs';

export async function buildObservationOpportunityLedger({ projectRoot = process.cwd() } = {}) {
  const paths = dataFoundryPaths(projectRoot), corpus = corpusPaths(projectRoot), gold = await readJson(path.join(corpus.gold, 'forecast-corpus.json'), { negatives: [], thermalAnomalyRegistry: { entries: [] } }), anomalies = new Map((gold.thermalAnomalyRegistry?.entries ?? []).map((item) => [item.id, item]));
  const opportunities = (gold.negatives ?? []).map((candidate) => createObservationOpportunity({ id: candidate.id, sourceId: 'research-candidate-only', window: candidate.window, geometry: candidate.geometry, outcome: 'UNKNOWN', coverage: candidate.checks?.sourceCoverage, productAvailability: candidate.checks?.observationOpportunity, providerHealth: candidate.checks?.providerHealthy, quality: candidate.checks?.qualityAdequate, retrievalSuccess: false, officialSourcesChecked: candidate.checks?.officialIncidentChecked, physicalSourcesChecked: candidate.checks?.physicalFireChecked, noObservationReason: 'NO_VALID_OBSERVATION_OPPORTUNITY_EVIDENCE', originalObservationIds: candidate.physicalCheckIds, createdAt: candidate.window?.from }));
  const hardNegatives = (gold.negatives ?? []).map((candidate) => { const anomaly = anomalies.get(candidate.id.replace(/^negative-candidate:\d+$/, (value) => value)) ?? [...anomalies.values()].find((item) => item.geometry?.coordinates?.join(',') === candidate.geometry?.coordinates?.join(',')); return createHardNegative({ id: `hard-negative-registry:${candidate.id}`, category: candidate.category, label: 'NO_VALID_OBSERVATION', geometry: candidate.geometry, effectiveFrom: candidate.window.from, sourceFamily: 'OPENSTREETMAP_CONTEXT', observationHistory: [], labelEvidence: anomaly?.evidenceIds ?? [], reviewState: 'REQUIRES_SOURCE_OPPORTUNITY_REVIEW', knownUncertainty: 'Context location only; not a scientifically valid negative or fire label.' }); });
  const ledger = { schemaVersion: 'vigia.observation-opportunity-ledger.v1', opportunities, counts: Object.fromEntries(['VALID_OBSERVATION_OPPORTUNITY', 'OBSERVED_POSITIVE', 'OBSERVED_NEGATIVE', 'NOT_COVERED', 'PRODUCT_UNAVAILABLE', 'PROVIDER_UNAVAILABLE', 'QUALITY_INSUFFICIENT', 'UNKNOWN'].map((outcome) => [outcome, opportunities.filter((item) => item.outcome === outcome).length])) }, registry = { schemaVersion: 'vigia.hard-negative-registry.v1', entries: hardNegatives, validHardNegatives: hardNegatives.filter((item) => item.label !== 'NO_VALID_OBSERVATION' && item.reviewState === 'VERIFIED').length };
  await Promise.all([writeJsonAtomic(paths.opportunities, ledger), writeJsonAtomic(paths.hardNegatives, registry)]); return { ledger, registry };
}
