import{datum,exceptionCard,icon,locationBlock,personCard,stateTag}from'../components.js';
import{ageLabel,escapeHtml,label,text,timeLabel}from'../format.js';
import{activeMayday,personById}from'../model.js';

export function dispatchView(model){
  const unresolved=model.resourceRequests.filter((item)=>!['FULFILLED','CANCELLED','COMPLETED'].includes(item.state)),coordination=model.exceptions.filter((item)=>item.audience?.includes?.('DISPATCH_EOC')||item.dispatchRelevant===true);
  const uncertain=unresolved.filter((item)=>['LOW','UNVERIFIED','UNKNOWN'].includes(item.etaConfidence)).length,mutual=unresolved.filter((item)=>item.mutualAid===true).length;
  return`<main class="fg-system-page fg-dispatch" data-fireground-role="DISPATCH_EOC" data-retrieval="dispatch-resource"><header class="fg-page-heading"><div><span>DISPATCH / EOC</span><h1>Regional coordination</h1><p>${escapeHtml(model.incident.name)} · consequence-relevant abstraction only</p></div><button type="button" data-fg-panel="fieldnet">${icon('sync')}Sync state</button></header><section class="fg-metric-strip"><article>${icon('resources')}<div><strong>${unresolved.length}</strong><span>Requests unresolved</span><small>Regional queue</small></div></article><article class="is-warning">${icon('timer')}<div><strong>${uncertain}</strong><span>ETA uncertain</span><small>Low / unverified</small></div></article><article>${icon('dispatch')}<div><strong>${mutual}</strong><span>Mutual aid</span><small>Agency coordination</small></div></article></section><div class="fg-dispatch-grid"><section><header><span>RESOURCE REQUEST QUEUE</span><strong>${unresolved.length}</strong></header>${unresolved.map((item)=>`<article><header><h2>${escapeHtml(text(item.title??item.type??item.requestId))}</h2>${stateTag(item.state)}</header><p>${escapeHtml(text(item.reason??item.operationalNeed,'Reason not reported.'))}</p><dl><div><dt>Requested</dt><dd>${escapeHtml(timeLabel(item.requestedAt))}</dd></div><div><dt>ETA</dt><dd>${escapeHtml(text(item.eta,'UNKNOWN'))} · ${escapeHtml(label(item.etaConfidence??'UNVERIFIED'))}</dd></div><div><dt>Agency</dt><dd>${escapeHtml(text(item.agency,'UNASSIGNED'))}</dd></div><div><dt>Staging / access</dt><dd>${escapeHtml(text(item.staging??item.access,'NOT REPORTED'))}</dd></div></dl></article>`).join('')||'<div class="fg-normal-state">No unresolved regional resource requests.</div>'}</section><aside><section><span>PUBLIC CONSEQUENCE</span><h2>${escapeHtml(text(model.roleData.publicWarningState,'NOT CONFIGURED'))}</h2><p>No public-warning integration is inferred.</p></section><section><span>ROADS / INFRASTRUCTURE</span><h2>${escapeHtml(text(model.roleData.infrastructureState,'UNKNOWN'))}</h2><p>${escapeHtml(text(model.roleData.infrastructureDetail,'No attributable infrastructure update received.'))}</p></section><section><span>SHELTER / SUPPORT</span><h2>${escapeHtml(text(model.roleData.shelterState,'NOT CONFIGURED'))}</h2><p>${escapeHtml(text(model.roleData.shelterDetail,'No configured consequence-management feed.'))}</p></section></aside></div><div class="fg-exception-grid">${coordination.map(exceptionCard).join('')}</div></main>`;
}

export function accountabilityView(model){
  const areas=Map.groupBy(model.crews,(crew)=>crew.operationalArea??'UNASSIGNED');
  const hazard=model.people.filter((person)=>person.inHazardZone!==false&&person.exitConfirmed!==true).length,out=model.people.filter((person)=>person.exitConfirmed===true).length,unknown=model.people.filter((person)=>!person.location||String(person.location?.verificationState??'UNKNOWN').includes('UNKNOWN')).length;
  return`<main class="fg-system-page fg-accountability" data-fireground-role="ACCOUNTABILITY" data-retrieval="accountability-person"><header class="fg-page-heading"><div><span>ACCOUNTABILITY</span><h1>People and crews</h1><p>Operational area → crew → individual. Apparatus accountability is never substituted.</p></div><button type="button" data-fg-action="par">${icon('people')}Report PAR</button></header><section class="fg-metric-strip"><article>${icon('people')}<div><strong>${model.people.length}</strong><span>People tracked</span><small>Current projection</small></div></article><article class="is-critical">${icon('warning')}<div><strong>${hazard}</strong><span>In hazard zone</span><small>Needs attention</small></div></article><article class="is-normal">${icon('ok')}<div><strong>${out}</strong><span>Confirmed out</span><small>Attributable exit</small></div></article><article class="is-warning">${icon('unknown')}<div><strong>${unknown}</strong><span>Unknown location</span><small>No point inference</small></div></article></section>${[...areas.entries()].map(([area,crews])=>`<section class="fg-accountability-area"><header><div><span>OPERATIONAL AREA</span><h2>${escapeHtml(area)}</h2></div><strong>${crews.length} crews</strong></header>${crews.map((crew)=>crewBlock(model,crew)).join('')}</section>`).join('')||'<div class="fg-empty">No accountability organization received.</div>'}<footer class="fg-page-actions"><button type="button" class="is-primary" data-fg-action="par">${icon('people')}<span><strong>Report PAR</strong><small>Update accountability</small></span></button><button type="button" data-fg-action="location">${icon('locate')}<span><strong>Update location</strong><small>Attributable report</small></span></button><button type="button" data-fg-action="status">${icon('ok')}<span><strong>Acknowledge</strong><small>Record review</small></span></button></footer></main>`;
}

function crewBlock(model,crew){const id=crew.crewId??crew.id,members=model.people.filter((person)=>String(person.crewId)===String(id));return`<section class="fg-accountability-crew"><header><div><span>CREW</span><h3>${escapeHtml(text(crew.name??crew.callSign??id))}</h3></div>${stateTag(crew.integrityState??crew.state)}</header><div class="fg-person-grid">${members.map(personCard).join('')||'<div class="fg-empty">No individual roster received.</div>'}</div></section>`;}

export function maydayView(model){
  const mayday=activeMayday(model),person=personById(model,mayday?.personId??mayday?.memberId)??{},timers=model.timers.filter((timer)=>!timer.maydayId||timer.maydayId===mayday?.maydayId),teams=model.rescue.teams??model.rescueTeams??[];
  if(!mayday)return`<main class="fg-mayday-empty" data-fireground-role="MAYDAY_RESCUE"><section><span>MAYDAY / RESCUE</span><h1>No active Mayday</h1><p>Normal operations remain quiet. This mode opens only for an active, authorized Mayday or controlled exercise.</p></section></main>`;
  return`<main class="fg-mayday" data-fireground-role="MAYDAY_RESCUE" data-retrieval="mayday-rescue"><section class="fg-mayday-head"><div><span>MAYDAY ACTIVE · ${escapeHtml(text(mayday.state))}</span><h1>${escapeHtml(text(person.name??person.callSign??mayday.memberName))}</h1><p>${escapeHtml(text(person.assignment??mayday.assignment))} · ${escapeHtml(text(person.crewName??person.crewId??mayday.crewId))}</p></div><strong>PINNED UNTIL PHYSICALLY RECOVERED</strong></section><div class="fg-mayday-grid"><section class="fg-distressed"><header><span>DISTRESSED MEMBER</span>${stateTag(person.status??'MAYDAY')}</header>${locationBlock(mayday.lastReliableLocation??person.location??{})}<div class="fg-lunar">${datum('Location',mayday.lunar?.location??mayday.ucan?.location)}${datum('Unit',mayday.lunar?.unit??mayday.ucan?.unit??person.crewId)}${datum('Name',mayday.lunar?.name??person.name)}${datum('Assignment',mayday.lunar?.assignment??person.assignment)}${datum('Resources needed',mayday.lunar?.resourcesNeeded??mayday.ucan?.needs)}${datum('Entry point',mayday.entryPoint??person.entryPoint)}</div></section><section class="fg-rescue-board"><header><span>RESCUE GROUP</span><h2>${escapeHtml(text(model.rescue.state,'NOT ASSIGNED'))}</h2></header><div>${teams.map((team)=>`<article><header><h3>${escapeHtml(text(team.name??team.callSign))}</h3>${stateTag(team.state)}</header><p>${escapeHtml(text(team.assignment))}</p><span>Entry ${escapeHtml(text(team.entryPoint))} · Route ${escapeHtml(text(team.route))}</span></article>`).join('')||'<div class="fg-empty">No rescue team assignment received.</div>'}</div>${datum('Fire-control protection',model.rescue.fireControlProtection)}${datum('Backup team',model.rescue.backupTeam)}${datum('Rescue route / hazards',model.rescue.routeHazards)}</section></div>${maydayTimers(timers)}<section class="fg-mayday-accountability"><div><span>UNACCOUNTED PERSONNEL</span><strong>${model.people.filter((item)=>['MISSING','MAYDAY'].includes(item.status)).length}</strong></div><div><span>PAR</span><strong>${escapeHtml(text(model.par[0]?.state,'NOT REQUESTED'))}</strong></div><div><span>FIELDNET</span><strong>${escapeHtml(label(model.connection.state??'UNKNOWN'))}</strong></div><button type="button" data-fg-action="mayday-recovered" data-mayday-id="${escapeHtml(mayday.maydayId??'')}">Confirm physical recovery</button></section></main>`;
}

function maydayTimers(timers){const required=['ACKNOWLEDGEMENT','LOCATION_CONFIRMATION','RESCUE_ASSIGNMENT','RESCUE_ENTRY','FIRE_CONTROL_PROTECTION','PAR','PHYSICAL_RECOVERY'];return`<section class="fg-mayday-timers"><header><span>WORKFLOW ACCOUNTABILITY TIMERS</span><p>Elapsed workflow time, never predicted survival.</p></header><div>${required.map((name)=>{const timer=timers.find((item)=>item.type===name)??{};return`<article class="${timer.overdue?'is-overdue':''}"><span>${escapeHtml(label(name))}</span><strong>${escapeHtml(text(timer.elapsed??timer.elapsedLabel,'NOT STARTED'))}</strong><p>${escapeHtml(text(timer.owner,'OWNER UNASSIGNED'))}</p>${stateTag(timer.state??(timer.overdue?'OVERDUE':'PENDING'))}</article>`;}).join('')}</div></section>`;}

export function commandTransferView(model){if(model.releaseGates.p0Complete!==true)return`<section class="fg-command-transfer is-deferred"><span>COMMAND TRANSFER</span><h1>Deferred until P0 workflows pass</h1><p>Mayday, accountability, evacuation, PAR, closed-loop orders and FieldNet survival must be certified before a transfer package can be accepted.</p></section>`;return`<section class="fg-command-transfer"><header><div><span>COMMAND TRANSFER PACKAGE</span><h1>${escapeHtml(model.incident.name)}</h1></div><button type="button" data-fg-action="accept-transfer">Receiving commander accepts</button></header><div>${datum('Strategy',model.incident.strategy)}${datum('Objective',model.incident.objective)}${datum('People in hazard zone',model.people.filter((person)=>person.inHazardZone!==false&&person.exitConfirmed!==true).length)}${datum('Accountability exceptions',model.people.filter((person)=>person.accountabilityException).length)}${datum('Water',model.water.state)}${datum('Communications',model.communications.state)}${datum('Evacuation / PAR',model.evacuations[0]?.state??model.par[0]?.state)}${datum('Unresolved requests',model.resourceRequests.filter((item)=>!['FULFILLED','CANCELLED'].includes(item.state)).length)}</div></section>`;}
