import test from 'node:test';
import assert from 'node:assert/strict';
import {buildSituation,compareSituations} from '../../../packages/domain/src/intelligence/situation-model.mjs';
import {accessResilience,failureAnalysis,significantRoads,historicalAnalogs} from '../../../packages/domain/src/intelligence/access-resilience.mjs';
const at='2026-09-12T12:00:00Z';
function fixture(){
 const facilities=['a','b','c'].map((id,i)=>({id,canonicalName:'Hospital '+id,canonicalType:'hospital',coordinate:[-8+i*.01,39],fields:{'capabilities.emergencyDepartment':{state:'RESOLVED'}},capabilities:{emergencyDepartment:true}}));
 const routes=facilities.map((f,i)=>({id:'r'+f.id,facilityId:f.id,geometry:{type:'LineString',coordinates:[f.coordinate,[-8,39.1]]},roads:[{ref:i===2?'IC2':'N114'},{name:'Small street'},{ref:'N114'}],distanceKm:10+i,travelTimeMinutes:10+i*5,direction:'FACILITY_TO_INCIDENT',calculatedAt:at,validUntil:'2026-09-12T13:00:00Z'}));routes[2].roads=[{ref:'IC2'}];
 return buildSituation({incident:{id:'x',name:'Incident X',coordinate:[-8,39.1],observedAt:'2026-09-12T10:00:00Z',municipality:'Évora'},facilities,routes,weather:{station:{id:'s'},windSpeed:{value:20,observedAt:at},temperature:{value:30,observedAt:at},humidity:{value:20,observedAt:at}}},{at,universe:'CONTROLLED_TEST'});
}
test('shared road counts distinct qualified routes and keeps ordinary streets out',()=>{const s=fixture(),a=accessResilience(s);assert.equal(a.corridors[0].routeCount,2);assert.deepEqual(significantRoads(s.routes[0]),['N114']);assert.equal(a.groups[0].secondary.facilityId,'b');assert.equal(a.scope.completeSearchRadiusKm,null);});
test('closure changes calculated option, preserves geographic nearest and operational state',()=>{const s=fixture(),saved=JSON.stringify(s),r=failureAnalysis(s,{kind:'ROAD_UNAVAILABLE',entityId:'N114'});assert.equal(r.resilience.routes.length,2);assert.equal(r.snapshot.rankings.nearestEmergencyHospital,'a');assert.equal(r.snapshot.rankings.nearestCalculatedEmergencyOption,'c');assert.equal(r.resilience.categories[0].redundancyLost,true);assert.equal(JSON.stringify(s),saved);});
test('unverified facilities and stale routes cannot establish qualified redundancy',()=>{const s=fixture();s.facilities[0].fields['capabilities.emergencyDepartment'].state='UNRESOLVED';s.routes[1].state='STALE';const a=accessResilience(s);assert.equal(a.groups[0].options.length,1);assert.equal(a.corridors.length,0);assert.ok(a.holes.some(h=>h.category==='fire_response'));});
test('scenario never revives an expired alternative',()=>{const s=fixture();s.routes[0].validUntil='2026-09-12T11:00:00Z';s.routes[0].alternatives=[{geometry:s.routes[0].geometry,roads:[{ref:'A1'}],travelTimeMinutes:25,distanceKm:30}];const r=failureAnalysis(s,{kind:'ROAD_UNAVAILABLE',entityId:'N114'});assert.notEqual(r.snapshot.routes[0].state,'CALCULATED');});
test('analogs require earlier incident and at least three measured comparable attributes',()=>{const a=fixture(),b=structuredClone(a);b.incident.id='old';b.incident.observedAt='2025-09-12T10:00:00Z';assert.equal(historicalAnalogs(a,[b]).matches.length,1);b.weather=null;b.incident.municipality=null;b.routes=[];assert.equal(historicalAnalogs(a,[b]).state,'INSUFFICIENT_COMPARABLE_HISTORY');b.knownAt='2027-01-01T00:00:00Z';assert.equal(historicalAnalogs(a,[b]).matches.length,0);});

test('identical route refresh does not crowd material changes but geometry changes remain material',()=>{const a=fixture(),b=structuredClone(a);a.routes[0].state='STALE';assert.equal(compareSituations(a,b).material.some(c=>c.kind==='ROUTE_CHANGED'),false);b.routes[0].geometry.coordinates[0][0]+=.02;assert.equal(compareSituations(a,b).material.some(c=>c.kind==='ROUTE_CHANGED'),true);});
