import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { buildNegativeOpportunityAtlas, compileAndPersistDecisionPacket, explainNegativeCandidate, materializeFuelTerrainScale, materializeWeatherAvailabilityGraph, queryDecisionObjectSet, reconcileDecisionFoundryOnce, replayDecisionPacket, adjudicateSecondRegions, validateProgressionGeometries } from '../src/modules/decision-foundry/index.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..'), retainedStatePresent = existsSync(path.join(root, 'data/runtime/forecast-corpus/gold/forecast-corpus.json')) && existsSync(path.join(root, 'data/runtime/data-foundry/observation-opportunities.json')), retainedTest = retainedStatePresent ? test : test.skip;
retainedTest('real retained incident compiles into a signed packet and replays identically', async () => { const compiled = await compileAndPersistDecisionPacket({ projectRoot: root, incidentId: '2025-AZGCP-000597' }), replay = await replayDecisionPacket({ projectRoot: root, incidentId: '2025-AZGCP-000597' }); assert.equal(compiled.packet.schemaVersion, 'vigia.crisis-decision-packet.v1'); assert.equal(compiled.packet.proofVerification.status, 'VALID'); assert.equal(replay.verification.identical, true); assert.equal(compiled.packet.currentActions.includes('PROPOSE_OFFICIAL_WARNING'), false); });
retainedTest('real acquisition plan ranks the measured +3h label gap but schedules no unproven opportunity', async () => { const { packet } = await compileAndPersistDecisionPacket({ projectRoot: root, incidentId: '2025-AZGCP-000597' }); assert.equal(packet.rankedAcquisitions[0].provider, 'nifc-wfigs-daily'); assert.deepEqual(packet.rankedAcquisitions[0].horizonsUnlocked, [3]); assert.equal(packet.rankedAcquisitions[0].forecastExamplesUnlocked, 40); assert.equal(packet.acquisitionPlan.selectedCandidateIds.length, 0); assert.equal(packet.acquisitionPlan.items[0].state, 'NO_VALID_OBSERVATION_OPPORTUNITY'); });
retainedTest('negative atlas preserves all 100 candidates as unknown', async () => { const atlas = await buildNegativeOpportunityAtlas({ projectRoot: root }), explanation = explainNegativeCandidate(atlas.entries[0]); assert.equal(atlas.candidates, 100); assert.equal(atlas.certifiedNegatives, 0); assert.equal(atlas.unknowns, 100); assert.equal(atlas.validHardNegatives, 0); assert.equal(explanation.emptyResponseCanCertify, false); });
test('geometry engine quarantines malformed geometry with mature library provenance', async () => { const output = await validateProgressionGeometries({ projectRoot: root, incident: { id: 'malformed', perimeterStates: [{ id: 'bad', geometry: { type: 'Polygon', coordinates: [[[200, 0], [201, 0], [200, 0]]] }, clocks: { observedAt: '2026-08-24T00:00:00Z', availableToVigiaAt: '2026-08-24T00:00:01Z' } }] } }); assert.match(output.engine.version, /^2\./); assert.ok(output.rows[0].failures.length > 0); assert.equal(output.rows[0].normalizedValid, false); });
retainedTest('weather and fuel/terrain scale reports remain explicit about retained scope', async () => { const weather = await materializeWeatherAvailabilityGraph({ projectRoot: root }), context = await materializeFuelTerrainScale({ projectRoot: root }); assert.equal(weather.certifiedSlices, 2); assert.equal(context.materializedPacks, 2); assert.equal(context.missingVegetationClass, 2); assert.equal(context.missingDisturbance, 2); });
test('second region adjudication selects evidence-backed Canadian partner path', async () => { const report = await adjudicateSecondRegions({ projectRoot: root }), states = Object.fromEntries(report.regions.map((x) => [x.regionId, x.state])); assert.equal(states.portugal, 'FINAL_ONLY'); assert.equal(states.canada, 'PARTNER_REQUIRED'); assert.equal(report.selection.selectedRegionId, 'canada'); });
retainedTest('autonomous reconciliation executes no action for blocked retained candidates', async () => { const result = await reconcileDecisionFoundryOnce({ projectRoot: root, incidentId: '2025-AZGCP-000597' }); assert.equal(result.tasksCreated.length, 0); assert.equal(result.unsafeActionsExecuted, 0); assert.equal(result.blocked.length, 5); assert.equal(result.eventChainValid, true); });
retainedTest('object-set boundary is canonical, explainable, and fingerprinted', async () => { const query = await queryDecisionObjectSet({ projectRoot: root, name: 'ACQUISITIONS_RANKED_BY_DECISION_VALUE' }); assert.equal(query.queryDefinition, 'ACQUISITIONS_RANKED_BY_DECISION_VALUE'); assert.ok(query.resultCount >= 5); assert.match(query.resultFingerprint, /^decision-object-set-query-result:sha256:/); assert.ok(query.filterDoctrine); });
