import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdir,mkdtemp,readFile,rm } from 'node:fs/promises';
import { CentralFieldNetService } from '../src/modules/fieldnet/central-fieldnet-service.mjs';
import { IncidentCommandService } from '../src/modules/incident-command/incident-command-service.mjs';
import { applyIncidentCommandEvent,emptyIncidentState } from '../../../packages/domain/src/incident-command/reducer.mjs';
import { hash as commandHash } from '../../../packages/domain/src/incident-command/contracts.mjs';
import { canonical,sha256 } from '../../../packages/domain/src/fieldnet/contracts.mjs';

const now=new Date('2026-08-25T08:00:00.000Z'),incidents=['incident:one','incident:two'];
const operationalEventService={operatorEvent:async(id)=>({event:{id,evidenceState:'CURRENT',knowledgeState:'CURRENT',physicalOperationalState:'UNKNOWN',lastSeenAt:now.toISOString()}})};
const registry={'node:compromised':{status:'active',key:'k'.repeat(32),incidentIds:incidents,capabilities:['fieldnet:sync','fieldnet:command-survival']},'node:emergency':{status:'active',key:'e'.repeat(32),incidentIds:incidents,capabilities:['fieldnet:sync','fieldnet:command-survival']}};
const request=(mutations,nodeId='node:compromised')=>({schemaVersion:'vigia.fieldnet-sync-request.v1',nodeId,mutations});
function command(sequence,event,{incidentId='incident:one',originNode='node:compromised',id=`mutation:${originNode}:${sequence}`,extra={}}={}){const payload={event};return{id,incidentId,originNode,actor:'claimed:operator',type:'COMMAND_SURVIVAL_EVENT',priority:'P0_LIFE_SAFETY',reserveEligibility:{state:'ELIGIBLE'},localSequence:sequence,payload,payloadHash:sha256(canonical(payload)),...extra};}
const mayday=(sequence,{incidentId='incident:one',description='',originNode='node:compromised'}={})=>command(sequence,{eventId:`event:mayday:${originNode}:${sequence}`,incidentId,type:'MAYDAY_ACTIVATED',payload:{maydayId:`mayday:${originNode}:${sequence}`,personId:`person:${originNode}:${sequence}`,timers:{},description}},{incidentId,originNode});
const ordinary=(sequence,{description=''}={})=>command(sequence,{eventId:`event:objective:${sequence}`,incidentId:'incident:one',type:'OBJECTIVE_UPSERTED',payload:{objectiveId:`objective:${sequence}`,description}});
const unsupported=(sequence,{incidentId='incident:one',id=`mutation:unsupported:${sequence}`}={})=>command(sequence,{eventId:`event:forged:${sequence}`,incidentId,type:'MAYDAY_FORGED',payload:{description:'forged'}},{incidentId,id});
const annotation=(sequence,size,{incidentId='incident:one',originNode='node:compromised',id=`annotation:${sequence}`}={})=>{const payload={note:'x'.repeat(size)};return{id,incidentId,originNode,actor:'claimed:operator',type:'ANNOTATION_ADDED',priority:'P0_LIFE_SAFETY',localSequence:sequence,payload,payloadHash:sha256(canonical(payload))};};
function semanticService(){const events=new Map(),states=new Map(incidents.map((incidentId)=>{const state=emptyIncidentState(incidentId);state.incident={incidentId,universe:'PRODUCTION',canonicalEventIds:[incidentId],lastUpdatedAt:now.toISOString()};return[incidentId,state];})),identity=(event)=>({eventId:event.eventId,incidentId:event.incidentId,type:event.type,actor:event.author,source:event.source,payloadHash:commandHash(event.payload),releaseId:event.releaseId,exercise:event.exercise}),repository={state:async(incidentId)=>structuredClone(states.get(incidentId)),eventIdentity:async(eventId)=>events.has(eventId)?identity(events.get(eventId)):null,append:async(event)=>{if(events.has(event.eventId))return{duplicate:true};events.set(event.eventId,structuredClone(event));states.set(event.incidentId,applyIncidentCommandEvent(states.get(event.incidentId),event));return{duplicate:false};},recordOfflineReceipt:async()=>({duplicate:false})};return new IncidentCommandService({repository,releaseId:'release:test',clock:()=>now});}
async function setup(t,options={}){const base=path.resolve('.tmp/test');await mkdir(base,{recursive:true});const directory=await mkdtemp(path.join(base,'fieldnet-reserve-'));t.after(()=>rm(directory,{recursive:true,force:true}));const filePath=path.join(directory,'ledger.json'),incidentCommandService=options.incidentCommandService??semanticService(),service=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,maxQueuedSyncs:32,maxQueuedSyncsPerNode:32,maxQueuedSyncsPerIncident:32,...options});await service.initialize();return{filePath,incidentCommandService,service};}

test('supported semantically valid life-safety command may consume reserve while an ordinary valid command may not',async(t)=>{
  const nodeRegistry={'node:compromised':registry['node:compromised']},{service}=await setup(t,{nodeRegistry,maxLedgerBytes:13_000,priorityReserveBytes:7_000,maxMutationBytes:10_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});
  await assert.rejects(()=>service.sync(request([ordinary(1,{description:'x'.repeat(5_000)})])),error=>error.statusCode===507&&error.details?.priorityReserveApplied===false);
  await service.sync(request([mayday(1,{description:'x'.repeat(5_000)})]));const stored=service.snapshot('incident:one').mutations[0];assert.equal(stored.priority,'P0_LIFE_SAFETY');assert.deepEqual(stored.reserveEligibility,{schemaVersion:'vigia.fieldnet-reserve-eligibility.v1',state:'ELIGIBLE',basis:'INCIDENT_COMMAND_REDUCER_V1',eventType:'MAYDAY_ACTIVATED',previewState:'READY'});
});

test('ordinary saturation cannot strand free reserve needed by a newly seen emergency node',async(t)=>{
  const{filePath,incidentCommandService,service}=await setup(t,{maxLedgerBytes:11_000,priorityReserveBytes:4_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});
  await service.sync(request([annotation(1,5_600)]));
  await assert.doesNotReject(()=>service.sync(request([mayday(1,{originNode:'node:emergency'})],'node:emergency')));
  const stored=service.snapshot('incident:one').mutations.find((item)=>item.originNode==='node:emergency');assert.equal(stored.priority,'P0_LIFE_SAFETY');assert.equal(stored.reserveEligibility.state,'ELIGIBLE');const accounting=JSON.parse(await readFile(filePath,'utf8'));delete accounting.mutations[stored.id];delete accounting.mutationBindings[stored.id];delete accounting.commandOutbox[stored.id];accounting.incidentMutationIds['incident:one']=accounting.incidentMutationIds['incident:one'].filter((id)=>id!==stored.id);for(const[id,conflict]of Object.entries(accounting.conflicts))if(id===stored.id||conflict?.centralRecordId===stored.id)delete accounting.conflicts[id];const naiveOrdinaryBytes=Buffer.byteLength(JSON.stringify(accounting));assert.ok(naiveOrdinaryBytes>7_000,`expected naive post-emergency accounting above 7000 bytes, got ${naiveOrdinaryBytes}`);const reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,maxLedgerBytes:11_000,priorityReserveBytes:4_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});await assert.doesNotReject(()=>reopened.initialize());assert.equal(reopened.snapshot('incident:one').mutations.find((item)=>item.id===stored.id)?.reserveEligibility.state,'ELIGIBLE');
});

test('post-preview terminal conflict cannot persist an ordinary-over-limit ledger or starve the next emergency command',async(t)=>{
  const conflictService={previewOfflineMutations:async(mutations)=>Object.fromEntries(mutations.map((mutation)=>[mutation.id,{state:'READY',eventId:mutation.payload.event.eventId,semanticValidation:'INCIDENT_COMMAND_REDUCER_V1',lifeSafetyEligible:true}])),acceptOfflineMutation:async(mutation)=>({state:'CONFLICTED',eventId:mutation.payload.event.eventId,reason:'concurrent_command_transition'})},{filePath,service}=await setup(t,{incidentCommandService:conflictService,maxLedgerBytes:11_000,priorityReserveBytes:4_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});
  await service.sync(request([annotation(1,5_600)]));await service.sync(request([mayday(1,{originNode:'node:emergency'})],'node:emergency'));assert.equal(service.snapshot('incident:one').mutations.some((item)=>item.originNode==='node:emergency'),false);assert.equal(service.status().mutationIdentityBindings,1);assert.equal(service.status().pendingCommandEffects,0);
  const incidentCommandService=semanticService(),reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,maxLedgerBytes:11_000,priorityReserveBytes:4_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});await assert.doesNotReject(()=>reopened.initialize());await assert.doesNotReject(()=>reopened.sync(request([mayday(2,{originNode:'node:emergency'})],'node:emergency')));assert.equal(reopened.snapshot('incident:one').mutations.find((item)=>item.originNode==='node:emergency')?.priority,'P0_LIFE_SAFETY');
});

test('post-preview repository capacity rejection releases reserve and leaves no restart retry backlog',async(t)=>{
  const capacityService={previewOfflineMutations:async(mutations)=>Object.fromEntries(mutations.map((mutation)=>[mutation.id,{state:'READY',eventId:mutation.payload.event.eventId,semanticValidation:'INCIDENT_COMMAND_REDUCER_V1',lifeSafetyEligible:true}])),acceptOfflineMutation:async(mutation)=>({state:'CAPACITY_REJECTED',eventId:mutation.payload.event.eventId,reason:'incident_command_projection_capacity_exceeded'})},{filePath,service}=await setup(t,{incidentCommandService:capacityService,maxLedgerBytes:11_000,priorityReserveBytes:4_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});
  await service.sync(request([annotation(1,5_600)]));await service.sync(request([mayday(1,{originNode:'node:emergency'})],'node:emergency'));assert.equal(service.status().pendingCommandEffects,0);assert.equal(service.snapshot('incident:one').mutations.some((item)=>item.originNode==='node:emergency'),false);
  const incidentCommandService=semanticService(),reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,maxLedgerBytes:11_000,priorityReserveBytes:4_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});await reopened.initialize();assert.equal(reopened.status().pendingCommandEffects,0);await reopened.sync(request([mayday(2,{originNode:'node:emergency'})],'node:emergency'));assert.equal(reopened.snapshot('incident:one').mutations.find((item)=>item.originNode==='node:emergency')?.priority,'P0_LIFE_SAFETY');
});

test('reserve admission falls back from optional compaction metadata that would consume ordinary allowance',async(t)=>{
  const{filePath,incidentCommandService,service}=await setup(t,{maxActiveMutationsPerIncident:10,maxLedgerBytes:200_000,priorityReserveBytes:20_000,maxMutationBytes:20_000,maxActiveBytesPerIncident:200_000,maxActiveBytesPerNode:200_000,maxActiveBytesPerIncidentNode:200_000});await service.sync(request([annotation(1,8),annotation(2,8)]));const saved=JSON.parse(await readFile(filePath,'utf8')),ordinary=structuredClone(saved);ordinary.nextCursor=0;ordinary.updatedAt=null;ordinary.nodes={'node:compromised':{nodeId:'node:compromised',lastSeenAt:null,lastLocalSequence:0}};const ordinaryLimit=Buffer.byteLength(JSON.stringify(ordinary))+64,reserve=9_000;service.maxActiveMutationsPerIncident=1;service.maxLedgerBytes=ordinaryLimit+reserve;service.priorityReserveBytes=reserve;
  await assert.doesNotReject(()=>service.sync(request([mayday(1,{originNode:'node:emergency'})],'node:emergency')));assert.equal(service.status().archiveSegments,0);assert.equal(service.snapshot('incident:one').mutations.filter((item)=>item.type==='ANNOTATION_ADDED').length,2);assert.equal(service.snapshot('incident:one').mutations.find((item)=>item.originNode==='node:emergency')?.priority,'P0_LIFE_SAFETY');
  const reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,maxActiveMutationsPerIncident:1,maxLedgerBytes:ordinaryLimit+reserve,priorityReserveBytes:reserve,maxMutationBytes:20_000,maxActiveBytesPerIncident:200_000,maxActiveBytesPerNode:200_000,maxActiveBytesPerIncidentNode:200_000});await assert.doesNotReject(()=>reopened.initialize());assert.equal(reopened.status().archiveSegments,0);assert.equal(reopened.snapshot('incident:one').mutations.length,3);
});

test('eligible life-safety records remain active through compaction so archive metadata cannot consume ordinary allowance',async(t)=>{
  const{filePath,incidentCommandService,service}=await setup(t,{maxActiveMutationsPerIncident:1,maxLedgerBytes:16_000,priorityReserveBytes:9_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});await service.sync(request([annotation(1,5_400,{incidentId:'incident:two'})]));await service.sync(request([mayday(2,{description:'x'.repeat(700)})]));await assert.doesNotReject(()=>service.sync(request([mayday(3,{description:'x'.repeat(700)})])));const rows=service.snapshot('incident:one').mutations;assert.equal(rows.length,2);assert.equal(rows.every((item)=>item.priority==='P0_LIFE_SAFETY'),true);assert.equal(service.status().archiveSegments,0);const reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,maxActiveMutationsPerIncident:1,maxLedgerBytes:16_000,priorityReserveBytes:9_000,maxMutationBytes:9_000,maxActiveBytesPerIncident:24_000,maxActiveBytesPerNode:24_000,maxActiveBytesPerIncidentNode:24_000});await assert.doesNotReject(()=>reopened.initialize());assert.equal(reopened.snapshot('incident:one').mutations.length,2);
});

test('saturated archive publication cannot block a peer life-safety command',async(t)=>{
  const{filePath,incidentCommandService,service}=await setup(t,{maxActiveMutationsPerIncident:2,maxArchiveSegmentsPerIncident:1,maxActiveBytesPerIncident:200_000,maxActiveBytesPerNode:200_000,maxActiveBytesPerIncidentNode:200_000});
  for(let sequence=1;sequence<=3;sequence+=1)await service.sync(request([annotation(sequence,16)]));assert.equal(service.status().archiveSegments,1);await service.sync(request([mayday(1,{originNode:'node:emergency'})],'node:emergency'));assert.equal(service.status().archiveSegments,1);assert.equal(service.snapshot('incident:one').mutations.find((item)=>item.originNode==='node:emergency')?.priority,'P0_LIFE_SAFETY');const reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,maxActiveMutationsPerIncident:2,maxArchiveSegmentsPerIncident:1,maxActiveBytesPerIncident:200_000,maxActiveBytesPerNode:200_000,maxActiveBytesPerIncidentNode:200_000});await assert.doesNotReject(()=>reopened.initialize());assert.equal(reopened.status().archiveSegments,1);
});

test('durable duplicate event identities never retain reserve eligibility',async(t)=>{
  const{filePath,incidentCommandService,service}=await setup(t),first=mayday(1),second=command(2,structuredClone(first.payload.event),{id:'mutation:duplicate-event:2'});await service.sync(request([first,second]));const rows=service.snapshot('incident:one').mutations;assert.equal(rows.length,1);assert.equal(rows[0].id,first.id);assert.equal(rows[0].priority,'P0_LIFE_SAFETY');assert.equal(service.status().mutationIdentityBindings,1);const reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now});await reopened.initialize();assert.equal(reopened.snapshot('incident:one').mutations.length,1);
});

test('incident-node byte quotas charge only the selected node bindings',async(t)=>{
  const{service}=await setup(t,{maxActiveMutationsPerIncident:1,maxActiveBytesPerIncident:200_000,maxActiveBytesPerNode:200_000,maxActiveBytesPerIncidentNode:5_000});for(let sequence=1;sequence<=12;sequence+=1)await service.sync(request([annotation(sequence,8)]));const peerPayload={note:'p'.repeat(2_400)},peer={id:'annotation:peer:1',incidentId:'incident:one',originNode:'node:emergency',actor:'claimed:operator',type:'ANNOTATION_ADDED',localSequence:1,payload:peerPayload,payloadHash:sha256(canonical(peerPayload))};await assert.doesNotReject(()=>service.sync(request([peer],'node:emergency')));assert.equal(service.snapshot('incident:one').mutations.some((item)=>item.id===peer.id),true);
});

test('unsupported life-safety-like prefix is rejected before ledger or reserve mutation',async(t)=>{
  const{service}=await setup(t);await assert.rejects(()=>service.sync(request([unsupported(1)])),error=>error.statusCode===400&&error.message==='fieldnet_life_safety_command_type_rejected');assert.equal(service.status().persistedMutations,0);assert.equal(service.status().cursor,'0');
});

test('malformed supported command and forged eligibility remain ordinary',async(t)=>{
  const{service}=await setup(t),malformed=command(1,{eventId:'event:malformed',incidentId:'incident:one',type:'MAYDAY_ACTIVATED',payload:{description:'missing identifiers'}});await service.sync(request([malformed]));const stored=service.snapshot('incident:one').mutations[0];assert.equal(stored.commandDisposition.state,'CONFLICTED');assert.equal(stored.priority,'P1_COMMAND');assert.equal(stored.reserveEligibility.state,'INELIGIBLE');
});

test('repeated compromised-node lookalikes cannot starve valid emergency traffic',async(t)=>{
  const{service}=await setup(t);for(let index=1;index<=40;index+=1)await assert.rejects(()=>service.sync(request([unsupported(index,{incidentId:index%2?'incident:one':'incident:two'})])),/fieldnet_life_safety_command_type_rejected/);await service.sync(request([mayday(1)]));const rows=service.snapshot('incident:one').mutations;assert.equal(rows.length,1);assert.equal(rows[0].priority,'P0_LIFE_SAFETY');
});

test('concurrent invalid flood reserves no capacity ahead of validated life-safety work',async(t)=>{
  const{service}=await setup(t),attempts=[...Array.from({length:20},(_,index)=>service.sync(request([unsupported(index+1,{id:`flood:${index+1}`})]))),service.sync(request([mayday(1)]))],results=await Promise.allSettled(attempts);assert.equal(results.filter((item)=>item.status==='fulfilled').length,1);assert.equal(results.filter((item)=>item.status==='rejected'&&item.reason?.message==='fieldnet_life_safety_command_type_rejected').length,20);assert.equal(service.snapshot('incident:one').mutations.filter((item)=>item.priority==='P0_LIFE_SAFETY').length,1);
});

test('reserve proof survives duplicate replay and restart without trusting caller metadata',async(t)=>{
  const{filePath,incidentCommandService,service}=await setup(t),value=mayday(1);await service.sync(request([value]));const replay=await service.sync(request([value]));assert.equal(replay.duplicates,1);const reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now});await reopened.initialize();const rows=reopened.snapshot('incident:one').mutations;assert.equal(rows.length,1);assert.equal(rows[0].priority,'P0_LIFE_SAFETY');assert.equal(rows[0].reserveEligibility.basis,'INCIDENT_COMMAND_REDUCER_V1');
});

test('a valid same-node emergency flood is partitioned and cannot starve a peer emergency node',async(t)=>{
  const options={maxLedgerBytes:24_000,priorityReserveBytes:10_000,maxMutationBytes:8_000,maxActiveBytesPerIncident:40_000,maxActiveBytesPerNode:40_000,maxActiveBytesPerIncidentNode:40_000},valueBySequence=new Map(),{filePath,incidentCommandService,service}=await setup(t,options);let rejected=null;
  for(let sequence=1;sequence<=20;sequence+=1){const value=mayday(sequence,{description:'x'.repeat(350)});valueBySequence.set(sequence,value);try{await service.sync(request([value]));}catch(error){rejected=error;break;}}
  assert.equal(rejected?.message,'central_fieldnet_node_reserve_capacity_reached');const afterFlood=service.status().capacityAccounting;assert.ok(afterFlood.reserve.byNode['node:compromised'].eligibleRecords>=1);assert.ok(afterFlood.reserve.byNode['node:compromised'].usedBytes<=afterFlood.reserve.fairShareBytes);const peer=mayday(1,{originNode:'node:emergency',description:'peer-life-safety'});await assert.doesNotReject(()=>service.sync(request([peer],'node:emergency')));const afterPeer=service.status().capacityAccounting;assert.ok(afterPeer.reserve.byNode['node:emergency'].usedBytes>0);assert.ok(afterPeer.reserve.byNode['node:emergency'].usedBytes<=afterPeer.reserve.fairShareBytes);assert.ok(afterPeer.reserve.usedBytes<=afterPeer.reserve.limitBytes);const first=valueBySequence.get(1),replay=await service.sync(request([first]));assert.equal(replay.duplicates,1);
  const reopened=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now,...options});await reopened.initialize();assert.deepEqual(reopened.status().capacityAccounting,service.status().capacityAccounting);assert.deepEqual(reopened.snapshot('incident:one').mutations.map((item)=>[item.id,item.priority,item.reserveEligibility.state]),service.snapshot('incident:one').mutations.map((item)=>[item.id,item.priority,item.reserveEligibility.state]));
});

test('concurrent valid emergency traffic preserves a peer partition under noisy-node pressure',async(t)=>{
  const{service}=await setup(t,{maxLedgerBytes:24_000,priorityReserveBytes:10_000,maxMutationBytes:8_000,maxActiveBytesPerIncident:40_000,maxActiveBytesPerNode:40_000,maxActiveBytesPerIncidentNode:40_000}),noisy=Array.from({length:10},(_,index)=>service.sync(request([mayday(index+1,{description:'x'.repeat(350)})]))),peer=service.sync(request([mayday(1,{originNode:'node:emergency',description:'peer-concurrent'})],'node:emergency')),results=await Promise.allSettled([...noisy,peer]);assert.equal(results.at(-1).status,'fulfilled');assert.ok(results.some((item)=>item.status==='rejected'&&item.reason?.message==='central_fieldnet_node_reserve_capacity_reached'));const accounting=service.status().capacityAccounting;assert.ok(accounting.reserve.byNode['node:emergency'].eligibleRecords===1);assert.ok(accounting.reserve.byNode['node:compromised'].usedBytes<=accounting.reserve.fairShareBytes);
});

test('allocation persistence failure consumes no reserve and the same semantic command recovers cleanly',async(t)=>{
  const incidentCommandService=semanticService(),{filePath,service}=await setup(t,{incidentCommandService,writer:async()=>{throw new Error('simulated_reserve_allocation_persistence_failure');}}),value=mayday(1);await assert.rejects(()=>service.sync(request([value])),/simulated_reserve_allocation_persistence_failure/);const failed=service.status();assert.equal(failed.persistedMutations,0);assert.equal(failed.capacityAccounting.reserve.usedBytes,0);const recovered=new CentralFieldNetService({filePath,operationalEventService,incidentCommandService,nodeRegistry:registry,clock:()=>now});await recovered.initialize();await assert.doesNotReject(()=>recovered.sync(request([value])));assert.equal(recovered.snapshot('incident:one').mutations[0].reserveEligibility.state,'ELIGIBLE');assert.ok(recovered.status().capacityAccounting.reserve.byNode['node:compromised'].usedBytes>0);
});
