import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp,readFile,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import {
  createForecast,createForecastInputManifest,createForecastReceipt,noGrowthPersistence
} from '../../../packages/domain/src/forecasting/index.mjs';
import { createForecastConsumerSnapshot } from '../src/modules/forecasting/forecast-consumer-snapshot.mjs';
import { loadForecastContextPack } from '../src/modules/forecasting/context-pack-loader.mjs';
import { ForecastStore } from '../src/modules/forecasting/forecast-store.mjs';
import { ForecastScoringController } from '../src/modules/forecasting/forecast-scoring-controller.mjs';
import { createDefaultForecastModelRegistry } from '../src/modules/forecasting/model-registry.mjs';
import { IsolatedPhysicalModelRunner } from '../src/modules/forecasting/physical-model-runner.mjs';

const square={type:'Polygon',coordinates:[[[-121,47],[-120.99,47],[-120.99,47.01],[-121,47.01],[-121,47]]]};
const issuedAt='2026-08-24T01:00:00.000Z';
function sample(){const registry=createDefaultForecastModelRegistry(),modelEntry=registry.models.find((item)=>item.modelId==='NO_GROWTH_PERSISTENCE'),inputManifest=createForecastInputManifest({incidentId:'incident:test',forecastIssuedAt:issuedAt,informationCutoff:'2026-08-24T00:59:00.000Z',initialPerimeter:{id:'perimeter:1',kind:'INITIAL_PERIMETER',version:'1',sourceClass:'OFFICIAL',knowledgeTime:'2026-08-24T00:58:00.000Z',contentHash:'sha256:initial'},modelVersion:modelEntry.version,policyVersion:'test-v1'}),member=noGrowthPersistence({issuedAt,initialPerimeter:square}),forecast=createForecast({incidentId:'incident:test',forecastType:'PERIMETER_PROGRESSION',state:'ISSUED',qualityState:'RESEARCH_ONLY',issuedAt,informationCutoff:inputManifest.informationCutoff,model:{id:modelEntry.modelId,version:modelEntry.version,fingerprint:modelEntry.fingerprint},inputManifestHash:inputManifest.semanticHash,initialPerimeterRef:'perimeter:1',horizons:member.horizons}),receipt=createForecastReceipt({forecast,inputManifest,modelEntry});return{registry,modelEntry,inputManifest,forecast,receipt};}

test('physical runner performs a bounded, shell-free subprocess round trip',async()=>{const root=await mkdtemp(path.join(tmpdir(),'forecast-runner-')),fixture=fileURLToPath(new URL('./fixtures/mock-physical-forecast-runner.mjs',import.meta.url)),artifactHash=`sha256:${createHash('sha256').update(await readFile(fixture)).digest('hex')}`,runner=new IsolatedPhysicalModelRunner({rootDir:root,commands:{mock:{modelId:'MOCK',version:'1',executable:process.execPath,args:[fixture],artifactPath:fixture,artifactHash}},timeoutMs:5_000}),prepared=await runner.prepareInputs({commandId:'mock',domainAreaKm2:10,inputManifestHash:'sha256:manifest',modelFingerprint:'sha256:model',horizonsHours:[1,3]});const executed=await runner.execute(prepared),parsed=await runner.parseOutputs(executed);assert.equal(runner.verifyOutputs(parsed),true);const manifest=await runner.recordManifest(parsed),saved=JSON.parse(await readFile(path.join(prepared.runDir,'run-manifest.json'),'utf8'));assert.equal(manifest.shell,false);assert.equal(saved.outputHash,parsed.outputHash);assert.equal(saved.artifactHash,artifactHash);assert.equal((await runner.doctor()).models[0].status,'READY');});
test('physical runner rejects unallowlisted commands, escaped paths, and oversized domains',async()=>{const root=await mkdtemp(path.join(tmpdir(),'forecast-runner-negative-')),runner=new IsolatedPhysicalModelRunner({rootDir:root,commands:{mock:{modelId:'MOCK',version:'1',executable:process.execPath}}});assert.throws(()=>runner.validateInputs({commandId:'other',domainAreaKm2:1}),/not_allowlisted/);assert.throws(()=>runner.validateInputs({commandId:'mock',domainAreaKm2:25_001,inputManifestHash:'x',modelFingerprint:'y',horizonsHours:[1]}),/domain_invalid/);});
test('physical runner rejects malformed rasters and a substituted model artifact',async()=>{const root=await mkdtemp(path.join(tmpdir(),'forecast-runner-artifact-')),fixture=fileURLToPath(new URL('./fixtures/mock-physical-forecast-runner.mjs',import.meta.url)),runner=new IsolatedPhysicalModelRunner({rootDir:root,commands:{mock:{modelId:'MOCK',version:'1',executable:process.execPath,args:[fixture],artifactPath:fixture,artifactHash:'sha256:0000000000000000000000000000000000000000000000000000000000000000'}}});assert.throws(()=>runner.validateInputs({commandId:'mock',domainAreaKm2:1,inputManifestHash:'x',modelFingerprint:'y',horizonsHours:[1],rasters:[{width:-1,height:2,dataType:'float32',contentHash:'bad'}]}),/raster_invalid/);const prepared=await runner.prepareInputs({commandId:'mock',domainAreaKm2:1,inputManifestHash:'x',modelFingerprint:'y',horizonsHours:[1]});await assert.rejects(runner.execute(prepared),/artifact_hash_mismatch/);assert.equal((await runner.doctor()).models[0].status,'ARTIFACT_HASH_MISMATCH');});
test('forecast store is idempotent, scores later labels, detects conflicts, and survives restart',async()=>{const root=await mkdtemp(path.join(tmpdir(),'forecast-store-')),filePath=path.join(root,'store.json'),{forecast,receipt}=sample(),event={eventId:'event:1'},store=new ForecastStore({filePath});await store.initialize();assert.equal((await store.append({forecast,receipt,event})).duplicate,false);assert.equal((await store.append({forecast,receipt,event})).duplicate,true);const scoring=new ForecastScoringController({store}),update=await scoring.observe({incidentId:'incident:test',observation:{id:'perimeter:later',observedAt:'2026-08-24T02:00:00.000Z',knowledgeTime:'2026-08-24T02:05:00.000Z',contentHash:'sha256:later',geometry:square}});assert.equal(update.scores.length,1);await scoring.observe({incidentId:'incident:test',observation:{id:'perimeter:later',observedAt:'2026-08-24T02:00:00.000Z',knowledgeTime:'2026-08-24T02:05:00.000Z',contentHash:'sha256:later',geometry:square}});assert.equal(store.status().scoreCount,1);await assert.rejects(store.append({forecast:{...forecast,outputHash:'sha256:substituted'},receipt,event}),/identity_conflict/);const restarted=new ForecastStore({filePath});await restarted.initialize();assert.equal(restarted.latest('incident:test').forecastId,forecast.forecastId);assert.equal(restarted.status().eventCount,1);assert.equal(restarted.status().scoreCount,1);});
test('consumer contract keeps forecast semantics distinct from observation and authority',()=>{const {forecast,inputManifest}=sample(),snapshot=createForecastConsumerSnapshot({forecast,inputManifest,impact:{exposures:[]},shadow:{mode:'SHADOW',consequentialExecution:'DISABLED'},replay:{valid:true,identical:true}});assert.equal(snapshot.forecastAvailability,'AVAILABLE');assert.equal(snapshot.model.id,'NO_GROWTH_PERSISTENCE');assert.equal(snapshot.shadow.consequentialExecution,'DISABLED');assert.match(snapshot.uncertainty.warning,/not a statement/);assert.deepEqual(snapshot.semanticDisplayRules.map((item)=>item.type),['OBSERVED','FORECAST_EXPECTED','FORECAST_UNCERTAINTY','WEATHER_CONTEXT','POTENTIAL_EXPOSURE','CONFIRMED_EXPOSURE']);});
test('content-addressed fuel and terrain packs enforce cutoff, coverage, path, and layer hash',async()=>{const root=await mkdtemp(path.join(tmpdir(),'forecast-context-')),layer=path.join(root,'fuel.bin'),body=Buffer.from('real retained layer bytes'),contentHash=`sha256:${createHash('sha256').update(body).digest('hex')}`,base={schemaVersion:'vigia.forecast-context-pack.v1',kind:'FUEL',datasetId:'LANDFIRE-FBFM40',version:'2025',referenceDate:'2025-06-01T00:00:00Z',knowledgeTime:'2026-08-24T00:00:00Z',resolution:'30m',coverage:{bbox:[-122,46,-120,48]},licenceId:'LANDFIRE-PUBLIC',transformation:'Retained source bytes; no transformation.',layers:[{name:'FBFM40',path:'fuel.bin',contentHash,width:1,height:1,bands:1,dataType:'uint8'}]},manifest=path.join(root,'manifest.json');await writeFile(layer,body);await writeFile(manifest,JSON.stringify(base));const pack=await loadForecastContextPack({manifestFile:manifest,kind:'FUEL',informationCutoff:'2026-08-24T01:00:00Z',bbox:[-121,47,-121,47]});assert.equal(pack.dataset.datasetId,'LANDFIRE-FBFM40');await writeFile(manifest,JSON.stringify({...base,knowledgeTime:'2026-08-24T02:00:00Z'}));await assert.rejects(loadForecastContextPack({manifestFile:manifest,kind:'FUEL',informationCutoff:'2026-08-24T01:00:00Z',bbox:[-121,47,-121,47]}),/future_information/);await writeFile(manifest,JSON.stringify({...base,layers:[{...base.layers[0],path:'../escape.bin'}]}));await assert.rejects(loadForecastContextPack({manifestFile:manifest,kind:'FUEL',informationCutoff:'2026-08-24T01:00:00Z',bbox:[-121,47,-121,47]}),/path_escape/);});
