import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { IntelligenceService } from '../src/modules/intelligence/intelligence-service.mjs';
import { policyForRoute } from '../src/http/route-security-policy.mjs';

const NOW='2026-08-23T12:00:00.000Z';
const actor=(scopes=['*'])=>({id:'operator:1',agencyId:'agency:pt',role:'supervisor',incidentScopes:scopes,capabilities:['read:evidence','read:replay','review:incident','review:prevention'],authentication:{authenticated:true,mode:'local_shadow_session'}});
const observation=(id,family,minutes=5)=>({id,type:'thermal',sourceFamily:family,independenceGroup:family,at:new Date(Date.parse(NOW)-minutes*60_000).toISOString(),receivedAt:new Date(Date.parse(NOW)-minutes*60_000).toISOString()});
function event(id,index=0){return{id,label:`Incident ${index}`,observations:[observation(`${id}:viirs`,'viirs')],physicalState:{freshness:'current'},physicalOperationalState:'CURRENT_PHYSICAL_FIRE',lastSeenAt:NOW,observationPlan:{opportunitiesV2:[{id:`${id}:sentinel3`,eventId:id,sourceFamily:'sentinel3_slstr',platform:'Sentinel-3',opportunityType:'PREDICTED_ORBITAL_PASS',authority:'ORBIT:v1',availability:'SCHEDULED_CONFIRMED',windowStart:'2026-08-23T13:00:00Z',canCloseEvidenceNeed:true}]}};}
class MemoryRepository{
  constructor(){this.snapshots=new Map();this.decisionRows=new Map();this.ready=true;this.failWrites=false;this.failReads=false;this.latestManyCalls=0;}
  status(){return{state:this.ready?'ready':'degraded'};}async initialize(){return this.status();}
  async latest(id){if(this.failReads){this.ready=false;throw Object.assign(new Error('intelligence_postgis_read_failed'),{dependency:'postgis'});}return this.snapshots.get(id)?.at(-1)??null;}async decisions(id){return this.decisionRows.get(id)??[];}
  async latestMany(ids){this.latestManyCalls+=1;if(this.failReads){this.ready=false;throw Object.assign(new Error('intelligence_postgis_read_failed'),{dependency:'postgis'});}return ids.map((id)=>this.snapshots.get(id)?.at(-1)??null).filter(Boolean);}
  async save(snapshot){if(this.failWrites)throw new Error('intelligence_postgis_write_failed');const rows=this.snapshots.get(snapshot.incidentId)??[],prior=rows.find((item)=>item.inputHash===snapshot.inputHash);if(prior)return{duplicate:true,snapshot:prior};rows.push(structuredClone(snapshot));this.snapshots.set(snapshot.incidentId,rows);return{duplicate:false,snapshot};}
  async history(id,{limit=25}={}){const rows=[...(this.snapshots.get(id)??[])].reverse().slice(0,limit);return{snapshots:rows,page:{returned:rows.length,hasMore:false}};}
  async recordDecision(decision){const rows=this.decisionRows.get(decision.incidentId)??[];rows.push(decision);this.decisionRows.set(decision.incidentId,rows);return{duplicate:false,decision};}
}
function harness(count=7){const events=Array.from({length:count},(_,index)=>event(`incident:${index+1}`,index+1)),repository=new MemoryRepository(),eventService={async operatorEvent(id){const item=events.find((row)=>row.id===id);return item?{event:item}:null;},async commandSnapshot(){return{meta:{mode:'LIVE'},events,sources:{firms:{state:'healthy'},sentinel3:{state:'healthy'}}};}},service=new IntelligenceService({snapshotRepository:repository,operationalEventService:eventService,evidenceNeedService:{snapshot:()=>events.map((item)=>({id:`need:${item.id}`,subjectId:item.id,state:'OPEN',missingQuantity:'independent_corroboration',blocksDecisionState:true,strongerClaim:'MULTI_FAMILY_PHYSICAL_SUPPORT',createdAt:NOW}))},stateRepository:{snapshot:()=>({evidenceRequests:[]})},replayService:{async caseDetail(id){return{case:{name:id},controlledClock:{steps:['2026-08-23T10:00:00.000Z','2026-08-23T11:00:00.000Z'],endAt:'2026-08-23T11:00:00.000Z'},evidence:[{id:'past',kind:'thermal',sourceFamily:'viirs',observedAt:'2026-08-23T09:55:00.000Z',visibleAt:'2026-08-23T10:00:00.000Z'},{id:'future',kind:'report',observedAt:'2026-08-23T10:30:00.000Z',visibleAt:'2026-08-23T11:00:00.000Z'}]};}},preventionFindingService:{find:id=>({findingId:id,reviewSummary:{count:0},evidenceNeedId:`need:${id}`})},centralFieldNetService:{snapshot:id=>({incidentId:id,updatedAt:NOW})},clock:()=>new Date(NOW)});return{service,repository,events};}

test('intelligence inbox enforces a maximum of five primary items with deterministic factor ordering',async()=>{const{service}=harness();const inbox=await service.inbox(actor(),{limit:99});assert.equal(inbox.items.length,5);assert.equal(inbox.primaryLimit,5);assert.ok(inbox.items.every((item)=>item.attention.tier==='P2'));assert.ok(inbox.items.every((item)=>item.nextBestEvidence.candidates[0].eligibleSource==='sentinel3_slstr'));assert.ok(service.status().timings.projectionP95Ms<75);});

test('cold intelligence inbox projection is concurrent but bounded',async()=>{const{service}=harness(40),original=service.operationalEventService.operatorEvent.bind(service.operationalEventService);let active=0,maximum=0;service.operationalEventService.operatorEvent=async(id)=>{active+=1;maximum=Math.max(maximum,active);try{await new Promise((resolve)=>setTimeout(resolve,5));return await original(id);}finally{active-=1;}};const inbox=await service.inbox(actor());assert.equal(inbox.items.length,5);assert.ok(maximum>1);assert.ok(maximum<=8);});

test('new principal inbox reads use one persisted projection batch without recomputation',async()=>{const{service,repository}=harness(40);await service.inbox(actor());const original=service.operationalEventService.operatorEvent.bind(service.operationalEventService);let calls=0;service.operationalEventService.operatorEvent=async(id)=>{calls+=1;return original(id);};const inbox=await service.inbox({...actor(),id:'operator:2'});assert.equal(inbox.items.length,5);assert.equal(calls,0);assert.equal(repository.latestManyCalls,2);assert.ok(inbox.items.every((item)=>item.computation.state==='CACHED'));});

test('simultaneous identical cold inbox reads share one globally bounded computation',async()=>{const{service}=harness(40),original=service.operationalEventService.operatorEvent.bind(service.operationalEventService);let active=0,maximum=0,calls=0;service.operationalEventService.operatorEvent=async(id)=>{calls+=1;active+=1;maximum=Math.max(maximum,active);try{await new Promise((resolve)=>setTimeout(resolve,5));return await original(id);}finally{active-=1;}};const responses=await Promise.all(Array.from({length:24},()=>service.inbox(actor())));assert.equal(calls,40);assert.ok(maximum>1);assert.ok(maximum<=8);assert.ok(responses.every((response)=>response===responses[0]));assert.equal(service.status().projectionAdmission.maximumActive,maximum);});

test('distinct cold inbox reads remain globally bounded and excess batches fail closed',async()=>{const{service}=harness(40),original=service.operationalEventService.operatorEvent.bind(service.operationalEventService);let active=0,maximum=0;service.operationalEventService.operatorEvent=async(id)=>{active+=1;maximum=Math.max(maximum,active);try{await new Promise((resolve)=>setTimeout(resolve,5));return await original(id);}finally{active-=1;}};const settled=await Promise.allSettled(Array.from({length:5},(_,index)=>service.inbox({...actor(),id:`operator:${index+1}`})));assert.equal(settled.filter((item)=>item.status==='fulfilled').length,4);const rejected=settled.find((item)=>item.status==='rejected');assert.equal(rejected.reason.statusCode,503);assert.equal(rejected.reason.message,'request_capacity_exhausted');assert.ok(maximum<=8);assert.ok(service.status().projectionAdmission.queued<=service.status().projectionAdmission.maxQueued);});

test('inbox detail handoff is a bounded cached read and material change invalidates it',async()=>{const{service,events}=harness(1),user=actor(),inbox=await service.inbox(user);for(let read=0;read<2;read+=1){const cached=await service.incident(user,'incident:1');assert.equal(cached.computation.state,'CACHED');assert.ok(cached.computation.durationMs<25);}assert.strictEqual(await service.inbox(user),inbox);events[0].observations.push(observation('incident:1:sentinel3','sentinel3_slstr'));service.schedule('incident:1');await new Promise((resolve)=>setImmediate(resolve));const updated=await service.incident(user,'incident:1'),refreshedInbox=await service.inbox(user);assert.equal(updated.situation.underlyingState,'MULTI_FAMILY_PHYSICAL_SUPPORT');assert.notStrictEqual(refreshedInbox,inbox);});

test('principal-scoped intelligence read caches remain capacity bounded',async()=>{const{service}=harness(1);for(let index=0;index<70;index+=1)await service.inbox({...actor(),id:`operator:${index}`});const status=service.status();assert.equal(status.cache.inboxes,64);assert.ok(status.cache.details<=status.cache.maxDetails);});

test('intelligence projections expose only a bounded FieldNet context, never raw reconciliation payloads',async()=>{const{service}=harness(1),projection=await service.incident(actor(),'incident:1');assert.equal(projection.fieldNetState.schemaVersion,'vigia.intelligence-fieldnet-context.v1');assert.equal(projection.fieldNetState.lastReconciledAt,NOW);assert.equal(Object.hasOwn(projection.fieldNetState,'mutations'),false);assert.equal(Object.hasOwn(projection.fieldNetState,'tasks'),false);});

test('incident scope is enforced for list and detail reads',async()=>{const{service}=harness(3),scoped=actor(['incident:2']),inbox=await service.inbox(scoped);assert.deepEqual(inbox.items.map((item)=>item.incidentId),['incident:2']);await assert.rejects(service.incident(scoped,'incident:1'),/incident_scope_forbidden/);});

test('same input is cached and a failed newer write retains explicit stale last-good state',async()=>{const{service,repository,events}=harness(1),user=actor();const first=await service.incident(user,'incident:1'),second=await service.incident(user,'incident:1');assert.equal(second.computation.state,'CACHED');events[0].observations.push(observation('incident:1:sentinel3','sentinel3_slstr'));repository.failWrites=true;const stale=await service.incident(user,'incident:1');assert.equal(stale.projectionState,'STALE');assert.equal(stale.computation.state,'FAILED_RETAINED_LAST_GOOD');assert.equal(stale.situation.underlyingState,first.situation.underlyingState);});

test('a PostGIS read loss returns explicit stale last-good intelligence without recomputation',async()=>{const{service,repository,events}=harness(1),user=actor(),current=await service.incident(user,'incident:1');events[0].observations.push(observation('incident:1:sentinel3','sentinel3_slstr'));repository.failReads=true;const stale=await service.incident(user,'incident:1');assert.equal(stale.snapshotVersion,current.snapshotVersion);assert.equal(stale.projectionState,'STALE');assert.equal(stale.computation.failureClass,'POSTGIS_FAILURE');assert.equal(stale.situation.underlyingState,'SINGLE_FAMILY_PHYSICAL_SIGNAL');});

test('operator decisions reject stale client bindings and persist exact server-owned versions',async()=>{const{service}=harness(1),user=actor(),current=await service.incident(user,'incident:1');await assert.rejects(service.decide(user,'incident:1',{snapshotVersion:'client-selected',evidenceGraphVersion:current.evidenceGraphHash,decisionType:'ASSESSMENT_ACKNOWLEDGED',selectedOption:'REVIEWED',reasonCode:'EVIDENCE_REVIEWED'}),/snapshot_changed/);const saved=await service.decide(user,'incident:1',{snapshotVersion:current.snapshotVersion,evidenceGraphVersion:current.evidenceGraphHash,decisionType:'ASSESSMENT_ACKNOWLEDGED',selectedOption:'REVIEWED',reasonCode:'EVIDENCE_REVIEWED'});assert.equal(saved.decision.principalId,user.id);assert.equal(saved.decision.snapshotVersion,current.snapshotVersion);});

test('operator decisions fail closed when projection recomputation retains stale last-good state',async()=>{const{service,repository,events}=harness(1),user=actor(),current=await service.incident(user,'incident:1');events[0].observations.push(observation('incident:1:sentinel3','sentinel3_slstr'));repository.failWrites=true;await assert.rejects(()=>service.decide(user,'incident:1',{snapshotVersion:current.snapshotVersion,evidenceGraphVersion:current.evidenceGraphHash,decisionType:'ASSESSMENT_ACKNOWLEDGED',selectedOption:'REVIEWED',reasonCode:'EVIDENCE_REVIEWED'}),error=>error.statusCode===409&&error.message==='intelligence_decision_projection_stale'&&error.details.refreshRequired===true);assert.deepEqual(await repository.decisions('incident:1'),[]);});

test('material input invalidation immediately marks retained projections stale and blocks decisions',async()=>{const{service,repository,events}=harness(1),user=actor(),current=await service.incident(user,'incident:1');events[0].observations.push(observation('incident:1:sentinel3','sentinel3_slstr'));service.markDirty('incident:1');const inbox=await service.inbox({...user,id:'operator:dirty'});assert.equal(inbox.items[0].projectionState,'STALE');assert.equal(inbox.items[0].computation.state,'PENDING_RECOMPUTATION_LAST_GOOD');await assert.rejects(()=>service.decide(user,'incident:1',{snapshotVersion:current.snapshotVersion,evidenceGraphVersion:current.evidenceGraphHash,decisionType:'ASSESSMENT_ACKNOWLEDGED',selectedOption:'REVIEWED',reasonCode:'EVIDENCE_REVIEWED'}),error=>error.statusCode===409&&error.message==='intelligence_decision_projection_stale');assert.deepEqual(await repository.decisions('incident:1'),[]);});

test('mutation ownership tokens prevent duplicate completion from closing another in-flight change',async()=>{
  const{service}=harness(1),user=actor(),current=await service.incident(user,'incident:1'),first=await service.beginInputMutation('incident:1'),second=await service.beginInputMutation('incident:1');
  assert.notEqual(first.mutationToken,second.mutationToken);
  assert.throws(()=>service.finishInputMutation('incident:1',{mutationToken:'foreign-token'}),error=>error.statusCode===409&&error.message==='intelligence_mutation_token_invalid');
  const completed=service.finishInputMutation('incident:1',{mutationToken:first.mutationToken}),duplicate=service.finishInputMutation('incident:1',{mutationToken:first.mutationToken});
  assert.equal((await completed).activeMutations,1);
  await assert.rejects(duplicate,error=>error.statusCode===409&&error.message==='intelligence_mutation_token_invalid');
  await assert.rejects(()=>service.decide(user,'incident:1',{snapshotVersion:current.snapshotVersion,evidenceGraphVersion:current.evidenceGraphHash,decisionType:'ASSESSMENT_ACKNOWLEDGED',selectedOption:'REVIEWED',reasonCode:'EVIDENCE_REVIEWED'}),error=>error.statusCode===409&&error.message==='intelligence_decision_projection_stale');
  assert.equal((await service.finishInputMutation('incident:1',{mutationToken:second.mutationToken})).activeMutations,0);
});

test('a durable mutation completion retries after transient PostGIS loss and releases the lease',async()=>{
  const{service}=harness(1);let state='ready',finishCalls=0,initializeCalls=0;const durable={status:()=>({state}),async initialize(){initializeCalls+=1;state='ready';return{state};},async beginInputMutation(){return{generation:1,dirty:true,activeMutations:1,expiresAt:'2026-08-23T12:02:00.000Z'};},async finishInputMutation(){finishCalls+=1;if(finishCalls===1){state='degraded';throw Object.assign(new Error('intelligence_postgis_unavailable'),{statusCode:503,dependency:'postgis'});}return{generation:1,dirty:true,activeMutations:0};}};service.snapshotRepository=durable;service.mutationRetryMs=10;const lease=await service.beginInputMutation('incident:1'),queued=await service.finishInputMutation('incident:1',{mutationToken:lease.mutationToken});assert.equal(queued.recomputation.state,'DURABLE_COMPLETION_RETRY_QUEUED');await new Promise((resolve)=>setTimeout(resolve,30));assert.equal(finishCalls,2);assert.equal(initializeCalls,1);assert.deepEqual(service.status().mutationRecovery,{durableLeases:0,scheduled:0,retryMs:10});
});

test('clients cannot select intelligence results and unauthorized principals cannot write decisions',async()=>{const{service}=harness(1),user=actor(),current=await service.incident(user,'incident:1'),input={snapshotVersion:current.snapshotVersion,evidenceGraphVersion:current.evidenceGraphHash,decisionType:'ASSESSMENT_ACKNOWLEDGED',selectedOption:'REVIEWED',reasonCode:'EVIDENCE_REVIEWED',attentionTier:'P1',ruleSetVersion:'client-rule',sourcePerformance:'STRONG',tdtStage:'COMPLETE'};const saved=await service.decide(user,'incident:1',input);assert.equal(Object.hasOwn(saved.decision,'attentionTier'),false);assert.equal(Object.hasOwn(saved.decision,'ruleSetVersion'),false);const unauthorized={...user,capabilities:['read:evidence']};await assert.rejects(service.decide(unauthorized,'incident:1',input),/forbidden/);});

test('a committed decision remains a 201-style success when recomputation admission is saturated',async()=>{const{service}=harness(1),user=actor(),current=await service.incident(user,'incident:1');service.queue.enqueue=()=>{throw new Error('intelligence_projection_queue_capacity_reached');};const saved=await service.decide(user,'incident:1',{snapshotVersion:current.snapshotVersion,evidenceGraphVersion:current.evidenceGraphHash,decisionType:'ASSESSMENT_ACKNOWLEDGED',selectedOption:'REVIEWED',reasonCode:'EVIDENCE_REVIEWED'});assert.equal(saved.duplicate,false);assert.equal(saved.recomputation.state,'DEFERRED_UNTIL_NEXT_READ');assert.equal(saved.recomputation.durableDecision,true);});

test('missing inputs after a last-good projection preserve explicit stale state without erasing incident access',async()=>{const{service,events}=harness(1),user=actor(),current=await service.incident(user,'incident:1');events.splice(0,1);const stale=await service.incident(user,'incident:1');assert.equal(stale.snapshotVersion,current.snapshotVersion);assert.equal(stale.projectionState,'STALE');assert.equal(stale.computation.failureClass,'INPUT_NOT_FOUND');});

test('historical intelligence uses only evidence visible at the governed replay clock',async()=>{const{service}=harness(1),result=await service.replay(actor(),'case:1',{asOf:'2026-08-23T10:00:00.000Z'});assert.deepEqual(result.inputEvidenceIds,['past']);assert.equal(result.futureEvidenceExcluded[0].id,'future');assert.equal(result.situation.state,'HISTORICAL_REHEARSAL_CASE');});

test('PREVENT intelligence remains measurement-safe and contains no treatment recommendation',()=>{const{service}=harness(1),result=service.prevent(actor(),'finding:1');assert.equal(result.screeningState,'MEASUREMENT_REQUIRED');assert.equal(result.unknown.classification,'DECISION_BLOCKING');assert.equal(result.treatmentRecommendation,null);});

test('intelligence route policy requires authenticated capabilities and incident-scopes decisions',()=>{assert.equal(policyForRoute('GET','/api/v10/intelligence/inbox').capability,'read:evidence');const detail=policyForRoute('GET','/api/v10/intelligence/incidents/:incidentId');assert.equal(detail.incidentScoped,true);assert.equal(policyForRoute('POST','/api/v10/intelligence/incidents/:incidentId/decisions').capability,'review:incident');});

test('migrations create immutable ledgers, monotonic history, leased token ownership, and trigger-maintained capacity counters',async()=>{const base=await readFile(new URL('../src/modules/storage/migrations/017-intelligence-fabric.sql',import.meta.url),'utf8'),hardening=await readFile(new URL('../src/modules/storage/migrations/018-intelligence-security-hardening.sql',import.meta.url),'utf8'),capacity=await readFile(new URL('../src/modules/storage/migrations/019-release-identity-capacity-counters.sql',import.meta.url),'utf8'),ownership=await readFile(new URL('../src/modules/storage/migrations/021-intelligence-mutation-ownership.sql',import.meta.url),'utf8'),repositories=await Promise.all([readFile(new URL('../src/modules/intelligence/postgres-intelligence-repository.mjs',import.meta.url),'utf8'),readFile(new URL('../src/modules/incident-command/postgres-incident-command-repository.mjs',import.meta.url),'utf8')]);assert.match(base,/CREATE TABLE IF NOT EXISTS intelligence_snapshot/);assert.match(base,/operator_intelligence_decision/);assert.match(base,/FOREIGN KEY \(snapshot_version, incident_id\) REFERENCES intelligence_snapshot\(snapshot_version, incident_id\)/);assert.match(base,/BEFORE UPDATE OR DELETE ON intelligence_snapshot/);assert.match(base,/BEFORE UPDATE OR DELETE ON operator_intelligence_decision/);assert.match(hardening,/snapshot_sequence bigserial/);assert.match(hardening,/intelligence_snapshot\(incident_id, snapshot_sequence DESC\)/);assert.match(capacity,/CREATE TABLE IF NOT EXISTS vigia_capacity_counter/);assert.match(capacity,/CREATE TABLE IF NOT EXISTS vigia_release_deployment_identity/);assert.match(capacity,/AFTER INSERT ON intelligence_snapshot/);assert.match(capacity,/AFTER INSERT ON incident_command_offline_receipt/);assert.match(ownership,/CREATE TABLE IF NOT EXISTS vigia_intelligence_input_mutation/);assert.match(ownership,/mutation_token uuid PRIMARY KEY/);assert.match(ownership,/owner_id text NOT NULL/);assert.match(ownership,/expires_at timestamptz NOT NULL/);assert.match(ownership,/CHECK \(expires_at > begun_at\)/);assert.match(ownership,/REFERENCES vigia_intelligence_input_generation/);assert.doesNotMatch(repositories.join('\n'),/SELECT count\(\*\) FILTER|sum\(octet_length/);});
