import test from 'node:test';
import assert from 'node:assert/strict';
import { PostgresIntelligenceRepository } from '../src/modules/intelligence/postgres-intelligence-repository.mjs';
import { RULE_SET_VERSION } from '../../../packages/domain/src/intelligence/rules.mjs';

const NOW='2026-08-23T12:00:00.000Z';
const readySchema={snapshot_table:'intelligence_snapshot',decision_table:'operator_intelligence_decision',capacity_table:'vigia_capacity_counter',generation_table:'vigia_intelligence_input_generation',mutation_table:'vigia_intelligence_input_mutation',sequence_ready:true,decision_generation_ready:true,mutation_owner_ready:true,mutation_expiry_ready:true};
const poolWith=(client,direct=async(sql)=>{if(sql.includes('to_regclass'))return{rows:[readySchema]};throw new Error(`unexpected_direct_query:${sql}`);})=>({on(){},query:direct,connect:async()=>client});
const snapshot=(overrides={})=>({snapshotVersion:'intelligence:test',incidentId:'incident:1',ontologyVersion:'vigia.crisis-ontology.v1',ruleSetVersion:RULE_SET_VERSION,incidentVersion:`sha256:${'1'.repeat(64)}`,evidenceGraphHash:`sha256:${'2'.repeat(64)}`,sourceStateVersion:`sha256:${'3'.repeat(64)}`,inputHash:`sha256:${'4'.repeat(64)}`,projectionHash:`sha256:${'5'.repeat(64)}`,explanationTrace:{explanationHash:`sha256:${'6'.repeat(64)}`},mode:'LIVE',generatedAt:NOW,...overrides});
const rawSnapshot=(sequence,blob='')=>({snapshot_sequence:sequence,snapshot_version:`snapshot:${sequence}`,incident_id:'incident:1',ontology_version:'vigia.crisis-ontology.v1',rule_set_version:RULE_SET_VERSION,incident_version:`sha256:${'1'.repeat(64)}`,evidence_graph_hash:`sha256:${'2'.repeat(64)}`,source_state_version:`sha256:${'3'.repeat(64)}`,input_hash:`sha256:${'4'.repeat(64)}`,projection_hash:`sha256:${'5'.repeat(64)}`,generated_at:NOW,state:{blob}});

test('decision persistence rechecks the latest snapshot under the incident transaction lock',async()=>{
  let inserted=false;const client={release(){},async query(sql){if(sql==='BEGIN'||sql.startsWith('SET LOCAL')||sql==='ROLLBACK'||sql.includes('pg_advisory_xact_lock'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT * FROM operator_intelligence_decision'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT generation,dirty,active_mutations'))return{rows:[{generation:0,dirty:false,active_mutations:0}],rowCount:1};if(sql.startsWith('SELECT snapshot_version'))return{rows:[{snapshot_version:'newer',evidence_graph_hash:`sha256:${'9'.repeat(64)}`}],rowCount:1};if(sql.startsWith('INSERT INTO operator_intelligence_decision')){inserted=true;return{rows:[],rowCount:0};}throw new Error(`unexpected_query:${sql}`);}},repository=new PostgresIntelligenceRepository({pool:poolWith(client)});await repository.initialize();await assert.rejects(()=>repository.recordDecision({decisionId:'decision:1',incidentId:'incident:1',snapshotVersion:'stale',evidenceGraphVersion:`sha256:${'2'.repeat(64)}`,authoritativeInputGeneration:0}),error=>error.statusCode===409&&error.details.refreshRequired===true);assert.equal(inserted,false);
});

test('immutable decision history enforces transactional incident, principal, and global quotas',async()=>{
  let inserted=false;const client={release(){},async query(sql){if(sql==='BEGIN'||sql.startsWith('SET LOCAL')||sql==='ROLLBACK'||sql.includes('pg_advisory_xact_lock')||sql.startsWith('INSERT INTO vigia_capacity_counter'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT * FROM operator_intelligence_decision'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT generation,dirty,active_mutations'))return{rows:[{generation:0,dirty:false,active_mutations:0}],rowCount:1};if(sql.startsWith('SELECT snapshot_version'))return{rows:[{snapshot_version:'snapshot:current',evidence_graph_hash:`sha256:${'2'.repeat(64)}`}],rowCount:1};if(sql.startsWith('SELECT rows,bytes FROM vigia_capacity_counter'))return{rows:[{rows:'1',bytes:'512'}],rowCount:1};if(sql.startsWith('INSERT INTO operator_intelligence_decision')){inserted=true;return{rows:[],rowCount:0};}throw new Error(`unexpected_query:${sql}`);}},repository=new PostgresIntelligenceRepository({pool:poolWith(client),maxDecisionsPerIncident:1});await repository.initialize();await assert.rejects(()=>repository.recordDecision({decisionId:'decision:capacity',incidentId:'incident:1',principalId:'operator:1',snapshotVersion:'snapshot:current',evidenceGraphVersion:`sha256:${'2'.repeat(64)}`,bindingHash:`sha256:${'7'.repeat(64)}`,authoritativeInputGeneration:0}),error=>error.statusCode===507&&error.details.scope==='incident');assert.equal(inserted,false);
});

test('idempotent decision retries resolve before capacity and current-head checks',async()=>{
  const existing={decision_id:'decision:retry',incident_id:'incident:1',principal_id:'operator:1',agency_id:'agency:1',capability:'review:incident',snapshot_version:'snapshot:old',evidence_graph_version:`sha256:${'2'.repeat(64)}`,decision_type:'ASSESSMENT_ACKNOWLEDGED',selected_option:'REVIEWED',reason_code:'EVIDENCE_REVIEWED',note:null,created_at:NOW,binding_hash:`sha256:${'7'.repeat(64)}`};let checkedHead=false;const client={release(){},async query(sql){if(sql==='BEGIN'||sql.startsWith('SET LOCAL')||sql==='COMMIT'||sql.includes('pg_advisory_xact_lock'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT * FROM operator_intelligence_decision'))return{rows:[existing],rowCount:1};if(sql.startsWith('SELECT snapshot_version'))checkedHead=true;return{rows:[],rowCount:0};}},repository=new PostgresIntelligenceRepository({pool:poolWith(client),maxDecisionsPerIncident:1});await repository.initialize();const result=await repository.recordDecision({decisionId:'decision:retry',incidentId:'incident:1',bindingHash:existing.binding_hash});assert.equal(result.duplicate,true);assert.equal(checkedHead,false);
});

test('snapshot history is monotonic, page-capped, and aggregate-byte bounded',async()=>{
  const rows=[rawSnapshot(3,'x'.repeat(40_000)),rawSnapshot(2,'y'.repeat(40_000)),rawSnapshot(1,'z'.repeat(40_000))],direct=async(sql)=>{if(sql.includes('to_regclass'))return{rows:[readySchema]};assert.match(sql,/ORDER BY snapshot_sequence DESC LIMIT/);return{rows,rowCount:rows.length};},repository=new PostgresIntelligenceRepository({pool:poolWith({},direct),maxHistoryPage:25,maxHistoryBytes:64*1024});await repository.initialize();const result=await repository.history('incident:1',{limit:250,maxBytes:64*1024});assert.equal(result.snapshots.length,1);assert.equal(result.snapshots[0].snapshotSequence,3);assert.equal(result.page.hasMore,true);assert.equal(result.page.limit,25);assert.ok(result.page.responseBytes<=result.page.maxBytes);
});

test('latest snapshots for an inbox are loaded in one bounded query',async()=>{
  const rows=[rawSnapshot(4),{...rawSnapshot(7),incident_id:'incident:2'}],direct=async(sql,params)=>{if(sql.includes('to_regclass'))return{rows:[readySchema]};assert.match(sql,/SELECT DISTINCT ON \(incident_id\)/);assert.deepEqual(params,[['incident:1','incident:2']]);return{rows,rowCount:rows.length};},repository=new PostgresIntelligenceRepository({pool:poolWith({},direct)});await repository.initialize();const snapshots=await repository.latestMany(['incident:1','incident:2','incident:1']);assert.deepEqual(snapshots.map((item)=>[item.incidentId,item.snapshotSequence]),[['incident:1',4],['incident:2',7]]);
});

test('immutable snapshot persistence enforces incident and global quotas before insert',async()=>{
  let insert=false;const client={release(){},async query(sql){if(sql==='BEGIN'||sql.startsWith('SET LOCAL')||sql==='ROLLBACK'||sql.includes('pg_advisory_xact_lock')||sql.startsWith('INSERT INTO vigia_capacity_counter'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT generation,dirty,active_mutations'))return{rows:[{generation:0,dirty:false,active_mutations:0}],rowCount:1};if(sql.includes('WHERE incident_id=$1 AND input_hash=$2')||sql.startsWith('SELECT generated_at'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT rows,bytes FROM vigia_capacity_counter'))return{rows:[{rows:'1',bytes:'1024'}],rowCount:1};if(sql.startsWith('INSERT INTO intelligence_snapshot')){insert=true;return{rows:[{snapshot_sequence:2}],rowCount:1};}throw new Error(`unexpected_query:${sql}`);}},repository=new PostgresIntelligenceRepository({pool:poolWith(client),maxSnapshotsPerIncident:1});await repository.initialize();await assert.rejects(()=>repository.save(snapshot()),error=>error.statusCode===507&&error.details.scope==='incident');assert.equal(insert,false);
});

test('decision commit rejects a dirty or generation-changed authoritative input under the incident lock',async()=>{let inserted=false;const client={release(){},async query(sql){if(sql==='BEGIN'||sql.startsWith('SET LOCAL')||sql==='ROLLBACK'||sql.includes('pg_advisory_xact_lock'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT * FROM operator_intelligence_decision'))return{rows:[],rowCount:0};if(sql.startsWith('SELECT generation,dirty,active_mutations'))return{rows:[{generation:8,dirty:true,active_mutations:1}],rowCount:1};if(sql.startsWith('INSERT INTO operator_intelligence_decision'))inserted=true;throw new Error(`unexpected_query:${sql}`);}},repository=new PostgresIntelligenceRepository({pool:poolWith(client)});await repository.initialize();await assert.rejects(()=>repository.recordDecision({decisionId:'decision:generation',incidentId:'incident:1',bindingHash:`sha256:${'8'.repeat(64)}`,authoritativeInputGeneration:7}),error=>error.statusCode===409&&error.details.refreshRequired===true);assert.equal(inserted,false);});

test('a duplicate or foreign mutation token is rejected before decrementing durable mutation authority',async()=>{
  let decremented=false,rolledBack=false;const client={release(){},async query(sql){if(sql==='BEGIN'||sql.startsWith('SET LOCAL')||sql.includes('pg_advisory_xact_lock'))return{rows:[],rowCount:0};if(sql.startsWith('DELETE FROM vigia_intelligence_input_mutation'))return{rows:[],rowCount:0};if(sql.startsWith('UPDATE vigia_intelligence_input_generation')){decremented=true;return{rows:[{generation:2,dirty:true,active_mutations:0}],rowCount:1};}if(sql==='ROLLBACK'){rolledBack=true;return{rows:[],rowCount:0};}throw new Error(`unexpected_query:${sql}`);}},repository=new PostgresIntelligenceRepository({pool:poolWith(client)});await repository.initialize();await assert.rejects(()=>repository.finishInputMutation('incident:1',{mutationToken:'11111111-1111-4111-8111-111111111111'}),error=>error.statusCode===409&&error.message==='intelligence_mutation_token_invalid');assert.equal(decremented,false);assert.equal(rolledBack,true);
});

test('expired mutation leases are transactionally reclaimed without clearing a live lease',async()=>{
  let recoveryUpdate='';const client={release(){},async query(sql){if(sql==='BEGIN'||sql.startsWith('SET LOCAL')||sql.includes('pg_advisory_xact_lock')||sql==='COMMIT')return{rows:[],rowCount:0};if(sql.startsWith('DELETE FROM vigia_intelligence_input_mutation WHERE incident_id='))return{rows:[{mutation_token:'expired'}],rowCount:1};if(sql.startsWith('UPDATE vigia_intelligence_input_generation SET dirty=true,active_mutations=(SELECT count(*)')){recoveryUpdate=sql;return{rows:[],rowCount:1};}if(sql.startsWith('SELECT generation,dirty,active_mutations'))return{rows:[{generation:9,dirty:true,active_mutations:1}],rowCount:1};throw new Error(`unexpected_query:${sql}`);}},repository=new PostgresIntelligenceRepository({pool:poolWith(client),clock:()=>new Date(NOW)});await repository.initialize();const authority=await repository.inputGeneration('incident:1');assert.deepEqual(authority,{generation:9,dirty:true,activeMutations:1});assert.match(recoveryUpdate,/SELECT count\(\*\).*WHERE incident_id=\$1/);
});
