import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, truncate, writeFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { buildCanonicalIncidentIndex, selectCanonicalFieldNetIncident } from '../../../packages/domain/src/event-fabric/canonical-incident-index.mjs';
import { commandOperationalSnapshot, operatorEventProjection } from '../src/modules/events/event-routes.mjs';
import { OperationalEventService } from '../src/modules/events/operational-event-service.mjs';
import { resolveCanonicalFieldNetScope } from '../../../scripts/local_runtime.mjs';
import { CANONICAL_STARTUP_SUMMARY_MAX_BYTES, EVENT_PROJECTION_MAX_BYTES, RequiredJsonArtifactError, readRequiredJson } from '../../../scripts/local_runtime_json.mjs';

const projectRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),scratchRoot=path.join(projectRoot,'.tmp','test');
const projection=(events)=>({schema:'vigia.event-projections.v1',generatedAt:'2026-09-03T00:00:00.000Z',meta:{region:'Portugal mainland'},clocks:{},command:{},operatorEvents:events});
const incident=(ordinal)=>({id:`PT-2026-${String(ordinal).padStart(10,'0')}`,physicalOperationalState:'MONITORING'});
async function scratch(t,prefix){await mkdir(scratchRoot,{recursive:true});const directory=await mkdtemp(path.join(scratchRoot,prefix));t.after(()=>rm(directory,{recursive:true,force:true}));return directory;}
function assertArtifactError(code){return(error)=>error instanceof RequiredJsonArtifactError&&error.code===code;}

test('A: a valid projection above the former 16 MiB limit reads inside the explicit 64 MiB projection budget',async(t)=>{const directory=await scratch(t,'projection-over-16mib-'),file=path.join(directory,'projection.json'),value=projection([{...incident(1),payload:'x'.repeat(17*1024*1024)}]);await writeFile(file,JSON.stringify(value));const result=await readRequiredJson(file,{root:projectRoot,maxBytes:EVENT_PROJECTION_MAX_BYTES,label:'canonical_event_projection_artifact'});assert.equal(result.operatorEvents[0].id,incident(1).id);});

test('B: a projection beyond the 64 MiB hard bound fails as FILE_TOO_LARGE before parsing',async(t)=>{const directory=await scratch(t,'projection-over-hard-bound-'),file=path.join(directory,'projection.json');await writeFile(file,'{}');await truncate(file,EVENT_PROJECTION_MAX_BYTES+1);await assert.rejects(()=>readRequiredJson(file,{root:projectRoot,maxBytes:EVENT_PROJECTION_MAX_BYTES,label:'canonical_event_projection_artifact'}),assertArtifactError('FILE_TOO_LARGE'));});

test('C and D: missing and malformed mandatory incident indexes retain precise errors',async(t)=>{const directory=await scratch(t,'incident-index-errors-'),missing=path.join(directory,'missing.json'),malformed=path.join(directory,'malformed.json');await assert.rejects(()=>resolveCanonicalFieldNetScope({indexFile:missing,projectRoot}),assertArtifactError('FILE_NOT_FOUND'));await writeFile(malformed,'{"schemaVersion":');await assert.rejects(()=>resolveCanonicalFieldNetScope({indexFile:malformed,projectRoot}),assertArtifactError('INVALID_JSON'));});

test('required JSON schema failures never become fallback objects',async(t)=>{const directory=await scratch(t,'incident-index-schema-'),file=path.join(directory,'index.json');await writeFile(file,JSON.stringify({schemaVersion:'wrong'}));await assert.rejects(()=>resolveCanonicalFieldNetScope({indexFile:file,projectRoot}),assertArtifactError('SCHEMA_INVALID'));});

test('E and F: a 166-incident index resolves one deterministic scope independent of event ordering',()=>{const events=Array.from({length:166},(_,index)=>incident(166-index)),forward=buildCanonicalIncidentIndex(projection(events)),shuffled=buildCanonicalIncidentIndex(projection([...events].sort((left,right)=>left.id.localeCompare(right.id)).reverse()));assert.equal(forward.incidentCount,166);assert.equal(selectCanonicalFieldNetIncident(forward),incident(1).id);assert.equal(selectCanonicalFieldNetIncident(shuffled),incident(1).id);});

test('G and H: a valid prior scope is retained and a removed prior scope falls back deterministically',()=>{const index=buildCanonicalIncidentIndex(projection([incident(3),incident(1),incident(2)]));assert.equal(selectCanonicalFieldNetIncident(index,{priorIncidentId:incident(2).id}),incident(2).id);assert.equal(selectCanonicalFieldNetIncident(index,{priorIncidentId:'PT-2026-REMOVED000'}),incident(1).id);});

test('I: zero canonical incidents produce explicit FIELDNET_SCOPE_UNAVAILABLE and never a PostGIS error',async(t)=>{const directory=await scratch(t,'incident-index-empty-'),file=path.join(directory,'index.json'),index=buildCanonicalIncidentIndex(projection([]));await writeFile(file,JSON.stringify(index));await assert.rejects(()=>resolveCanonicalFieldNetScope({indexFile:file,projectRoot}),error=>error.code==='FIELDNET_SCOPE_UNAVAILABLE'&&error.message==='canonical_fieldnet_incident_scope_unavailable'&&!/postgis/i.test(error.message));});

test('projection growth is bounded without deleting durable opportunity-result history',()=>{const opportunityResults=Array.from({length:382},(_,index)=>({id:`result:${index}`,created_at:new Date(Date.UTC(2026,8,1,0,0,index)).toISOString()})),projected=operatorEventProjection({...incident(1),observations:[],timeline:[],geometryTimeline:[],observationPlan:{opportunityResults}});assert.equal(projected.observationPlan.opportunityResults.length,96);assert.deepEqual(projected.observationPlan.opportunityResultInventory,{total:382,returned:96,truncated:true,detailHref:`/api/v10/operations/opportunity-results?eventId=${encodeURIComponent(incident(1).id)}&limit=1000`});});

test('the projection generator atomically publishes a fingerprint-bound compact incident index alongside the projection',async(t)=>{const directory=await scratch(t,'projection-index-pair-'),projectionFile=path.join(directory,'event-projections.production.json'),indexFile=path.join(directory,'canonical-incident-index.production.json'),service=new OperationalEventService({projectionFile,fireEventService:{async snapshot(){return{meta:{region:'Portugal mainland'},events:[incident(2),incident(1)]};}},evidenceNeedService:{async ingestAcceptedEvidence(){},async sync(){},enrich(value){return value;}},clock:()=>new Date('2026-09-03T00:00:00.000Z')});await service.snapshot({force:true});const retained=JSON.parse(await readFile(projectionFile,'utf8')),index=JSON.parse(await readFile(indexFile,'utf8'));assert.equal(index.projectionFingerprint,retained.projectionFingerprint);assert.equal(index.projectionFingerprint,retained.command.projectionFingerprint);assert.deepEqual(index.incidents.map((item)=>item.id),[incident(1).id,incident(2).id]);});

test('K: the compact startup summary for a realistic 166-incident dataset remains inside its 2 MiB budget',()=>{const events=Array.from({length:166},(_,index)=>({...incident(index+1),label:`Incident ${index+1}`,observations:Array.from({length:120},(__,item)=>({id:`observation:${index}:${item}`,at:'2026-09-03T00:00:00.000Z',type:'thermal'}))})),summary=commandOperationalSnapshot({schema:'vigia.command-input.v1',events}),bytes=Buffer.byteLength(JSON.stringify({...summary,projectionFingerprint:`sha256:${'a'.repeat(64)}`}));assert.equal(summary.eventInventory.total,166);assert.equal(summary.eventInventory.returned,40);assert.ok(bytes<CANONICAL_STARTUP_SUMMARY_MAX_BYTES,`${bytes} must remain below ${CANONICAL_STARTUP_SUMMARY_MAX_BYTES}`);});
