import test from 'node:test';
import assert from 'node:assert/strict';
import {buildSituation,scenario} from '../../../packages/domain/src/intelligence/situation-model.mjs';
import {operationalPicture,stressSupport} from '../../../packages/domain/src/intelligence/operational-cognition.mjs';
import {MLXLocalModel,qualifiedReceipt} from '../src/modules/intelligence/intelligence-language-model.mjs';
import {SituationAsk,answerMapIntents} from '../src/modules/intelligence/situation-ask.mjs';
const at='2026-09-13T10:00:00Z';
function fixture(){
 const facilities=['h1','h2','f1','f2','rc'].map((id,i)=>({id,canonicalName:id,canonicalType:id[0]==='h'?'hospital':id[0]==='f'?'fire_station':'temporary_reception_center',coordinate:[-7.9+i*.01,38.6],fields:{'capabilities.emergencyDepartment':{state:'RESOLVED'},'capabilities.fireResponse':{state:'RESOLVED'},'designation.kind':{state:'RESOLVED'}},capabilities:{emergencyDepartment:id[0]==='h',fireResponse:id[0]==='f'},designation:id==='rc'?{kind:'ZCAP'}:null,provenance:{'capabilities.emergencyDepartment':[{retrievedAt:at,validUntil:'2026-09-14T10:00:00Z'}]}}));
 const routes=facilities.map((f,i)=>({id:'r'+f.id,facilityId:f.id,direction:'FACILITY_TO_INCIDENT',calculatedAt:at,validUntil:'2026-09-13T10:05:00Z',travelTimeMinutes:10+i*5,distanceKm:8+i,geometry:{type:'LineString',coordinates:[f.coordinate,[-7.8,38.7]]},roads:[{ref:i%2===0?'N114':'A6'}]}));
 routes[0].alternatives=[{...routes[0],roads:[{ref:'N236'}],travelTimeMinutes:18}];
 const places=[{id:'town',name:'Test settlement',kind:'settlement',coordinate:[-7.85,38.7],municipality:'Test municipality',source:'CONTROLLED_TEST',population:{value:0,authority:'INE',referenceYear:2021,sourceUrl:'https://mapas.ine.pt/test',retrievedAt:at,geographicUnit:'SETTLEMENT'}}];
 return buildSituation({incident:{id:'test',coordinate:[-7.8,38.7]},facilities,routes,places,communityRoutes:routes.map(r=>({...r,id:'c'+r.id,settlementId:'town',direction:'FACILITY_TO_SETTLEMENT'})),roadCoverage:{connected:true,state:'PARTIAL',checkedAt:at,validUntil:'2026-09-13T10:10:00Z',coveredRoads:['N114','N236','A6']},sources:[]},{at,universe:'CONTROLLED_TEST'});
}
test('picture excludes unqualified POIs and contains inspectable qualified support and communities',()=>{const s=fixture();s.facilities.push({id:'noise',canonicalName:'Unverified hospital',coordinate:[-7.81,38.7],canonicalType:'hospital',fields:{}});const p=operationalPicture(s);assert.ok(p.features.some(f=>f.properties.kind==='community'));assert.ok(p.features.some(f=>f.properties.kind==='facility'));assert.ok(!p.features.some(f=>f.properties.entityId==='noise'));assert.ok(p.features.filter(f=>f.properties.kind==='route').every(f=>f.properties.calculatedAt));});
test('selected community preserves only its support paths',()=>{const p=operationalPicture(fixture(),{communityId:'town'});assert.ok(p.features.some(f=>f.properties.kind==='route'));assert.ok(p.features.filter(f=>f.properties.kind==='route').every(f=>f.properties.subjectId==='town'));});
test('coverage failure displays lost paths separately from retained paths and does not mutate truth',()=>{const s=fixture(),original=JSON.stringify(s),after=scenario(s,[{kind:'ROAD_UNAVAILABLE',entityId:'N114'},{kind:'ROAD_UNAVAILABLE',entityId:'N236'}]).snapshot,p=operationalPicture(after,{before:s,category:'emergency_hospital'});assert.ok(p.features.some(f=>f.properties.state==='lost'));assert.ok(p.features.some(f=>f.properties.state==='retained'));assert.equal(JSON.stringify(s),original);assert.ok(p.features.filter(f=>f.properties.kind==='route').every(f=>f.geometry.type==='LineString'));});
test('stress test is bounded, sorted and isolated',()=>{const s=fixture(),original=JSON.stringify(s),r=stressSupport(s);assert.ok(r.results.length>1&&r.results.length<=12);assert.equal(r.operationalWrites,0);assert.equal(r.universe,'SCENARIO');assert.equal(JSON.stringify(s),original);assert.ok(r.results.every((x,i)=>i===0||r.results[i-1].affectedRelationships>=x.affectedRelationships));});
test('expired support is not promoted by an operational picture',()=>{const p=operationalPicture(fixture(),{at:'2026-09-13T11:00:00Z'});assert.equal(p.features.filter(f=>f.properties.kind==='route').length,0);assert.ok(p.gaps.length);});
test('qualification receipt cannot enable failed startup or inadequate corpus',()=>{assert.equal(qualifiedReceipt({selected:true,model:'test',startup:{passed:50,attempts:50},metrics:{cases:99}},'test'),false);});
test('unqualified MLX adapter makes zero network/model calls',async()=>{let calls=0;const model=new MLXLocalModel({fetchImpl:()=>calls++});assert.equal((await model.health()).state,'disabled');assert.equal(await model.intent({question:'Show hospital',tools:['getQualifiedFacilities']}),null);assert.equal(calls,0);});
test('literal extraction blocks unsupported values even with a source quote',async()=>{const model=new MLXLocalModel();model.qualified=true;model.request=async()=>({state:'supported',candidates:[{subjectCandidate:'Hospital A',predicate:'contact.phone',value:'999999999',sourceText:'Hospital A: 222222222'}]});const r=await model.extract({text:'Hospital A: 222222222'});assert.equal(r.candidates.length,0);});
test('single hospital community question retains its exact filter and sanctioned map command',()=>{const ask=new SituationAsk({});assert.equal(ask.parse('Show communities with only one retained hospital option.',fixture()).filter,'SINGLE_HEALTHCARE');assert.deepEqual(answerMapIntents('getRoadDependencies',{road:'EM 527'},{}),[{type:'FOCUS_ROAD',road:'EM527'}]);assert.deepEqual(answerMapIntents('unknown',{},{}),[]);});
test('selected healthcare filter does not turn every gap into one-hospital redundancy',()=>{const s=fixture();assert.equal(operationalPicture(s,{filter:'SINGLE_HEALTHCARE'}).communities.length,0);s.facilities.find(f=>f.id==='h2').unavailable=true;assert.equal(operationalPicture(s,{filter:'SINGLE_HEALTHCARE'}).communities.length,1);});
test('failure map keeps affected qualified facilities visible',()=>{const s=fixture(),after=scenario(s,[{kind:'FACILITY_UNAVAILABLE',entityId:'h1'}]).snapshot,p=operationalPicture(after,{before:s});assert.ok(p.features.some(f=>f.properties.entityId==='h1'&&f.properties.state==='affected'));});
