import test from 'node:test';
import assert from 'node:assert/strict';
import { loadMigrations,runPostgresMigrations } from '../src/modules/storage/postgres-migration-runner.mjs';
import { VIGIA_RELEASE_CONTRACT } from '../../../packages/domain/src/release-contract.mjs';

function poolFor(initial=[]){const ledger=structuredClone(initial),aliases=[];const client={release(){},async query(sql,params=[]){const text=String(sql);if(text.startsWith("SELECT version,name,checksum"))return{rows:ledger.filter((row)=>/^\d{3}$/.test(row.version)).sort((a,b)=>a.version.localeCompare(b.version))};if(text.startsWith('UPDATE vigia_schema_migration SET version=')){const row=ledger.find((item)=>item.version===params[1]&&item.name===params[2]&&item.checksum===params[3]);if(row)row.version=params[0];return{rows:[],rowCount:row?1:0};}if(text.startsWith('INSERT INTO vigia_schema_migration_lineage_alias')){aliases.push({aliasVersion:params[0],canonicalVersion:params[1],originalName:params[2],originalChecksum:params[3],originalAppliedAt:params[4],adoptedAt:params[5],reason:params[6]});return{rows:[],rowCount:1};}if(text.startsWith('INSERT INTO vigia_schema_migration(version')){ledger.push({version:params[0],name:params[1],checksum:params[2],applied_at:params[3],execution_ms:params[4]});return{rows:[],rowCount:1};}if(text.startsWith('SELECT PostGIS_Version'))return{rows:[{version:'3.5-test'}]};return{rows:[],rowCount:0};}};return{pool:{connect:async()=>client},ledger,aliases};}

test('canonical migration DAG preserves Agent 1 001-021 and places intelligence convergence at forward head 024',async()=>{const migrations=await loadMigrations();assert.equal(VIGIA_RELEASE_CONTRACT.migrationHead,'024');assert.deepEqual(migrations.map((item)=>item.version),Array.from({length:24},(_,index)=>String(index+1).padStart(3,'0')));assert.equal(migrations.find((item)=>item.version==='017').name,'intelligence-fabric');assert.equal(migrations.at(-1).name,'incident-situation');});

test('Agent 1 head 021 upgrades by applying 022 through 024 without rewriting prior checksums',async()=>{const migrations=await loadMigrations(),initial=migrations.slice(0,21).map((item)=>({version:item.version,name:item.name,checksum:item.checksum,applied_at:'2026-08-24T00:00:00.000Z',execution_ms:1})),before=structuredClone(initial),state=poolFor(initial),result=await runPostgresMigrations(state.pool,{clock:()=>new Date('2026-08-25T00:00:00.000Z')});assert.deepEqual(result.applied,['022','023','024']);assert.deepEqual(result.skipped,migrations.slice(0,21).map((item)=>item.version));assert.deepEqual(state.ledger.slice(0,21),before);assert.equal(state.ledger.at(-1).version,'024');});

test('an Agent 2-only 017 convergence ledger is preserved as an audited lineage alias before canonical 017-024 apply',async()=>{const migrations=await loadMigrations(),convergence=migrations.find(m=>m.version==='022'),initial=[...migrations.slice(0,16).map((item)=>({version:item.version,name:item.name,checksum:item.checksum,applied_at:'2026-08-24T00:00:00.000Z',execution_ms:1})),{version:'017',name:'intelligence-convergence',checksum:convergence.checksum,applied_at:'2026-08-24T01:00:00.000Z',execution_ms:7}],state=poolFor(initial),result=await runPostgresMigrations(state.pool,{clock:()=>new Date('2026-08-25T00:00:00.000Z')});assert.deepEqual(result.applied,['017','018','019','020','021','022','023','024']);assert.equal(state.aliases.length,1);assert.equal(state.aliases[0].aliasVersion,'agent2-017-intelligence-convergence');assert.equal(state.aliases[0].canonicalVersion,'022');assert.equal(state.aliases[0].originalChecksum,convergence.checksum);assert.equal(state.ledger.some((row)=>row.version==='agent2-017-intelligence-convergence'&&row.checksum===convergence.checksum),true);assert.equal(state.ledger.find((row)=>row.version==='017').name,'intelligence-fabric');});
