import assert from 'node:assert/strict';
import test from 'node:test';

import { OperationalPeriodService } from '../src/modules/operator/operational-period-service.mjs';
import { OperationalProofService } from '../src/modules/operator/operational-proof-service.mjs';

test('governed context and collection ledger satisfy the operational-proof contract without changing incident verification', async () => {
  const service=new OperationalProofService({projectRoot:process.cwd()}),recovery={truth:{counts:{VERIFIED_CURRENT:0},incidents:[{incidentId:'incident:20261255634',classification:'DETECTION_CANDIDATE',countsAsActive:false,priority:{score:75,factors:[{code:'POINT_CONTEXT',value:null,weight:0}],missingFactors:['POINT_CONTEXT'],dataCompleteness:{availableDimensions:5}}}]},informationCollection:{summary:{informationRequirements:0,collectionTasks:0},requirements:[],tasks:[]}},result=await service.project(recovery),collection=result.recovery.informationCollection,effectiveness=result.collectionEffectiveness,context=result.incidentContextById.get('20261255634');
  const coveredCoordinates=result.contextPack.coverage.validCoordinates;
  assert.ok(coveredCoordinates>=207);assert.equal(result.contextPack.coverage.terrainAvailable,coveredCoordinates);assert.equal(result.contextPack.coverage.terrainUnavailable,0);assert.equal(result.incidentContextById.size,coveredCoordinates);
  for(const key of ['community','medicalAccess','fireStation','protectedArea','majorRoad','wildfireRelevantAsset'])assert.equal(result.contextPack.coverage[key],coveredCoordinates);
  assert.ok(context.terrain.elevationRange);assert.equal(context.terrain.state,'AVAILABLE');assert.equal(context.roads.length,1);assert.ok(context.assets.length>=4);assert.ok(context.assets.every(item=>item.preliminary===true&&item.distanceKm!==null&&item.method&&item.source));
  assert.ok(effectiveness.summary.satisfied>=20);assert.ok(effectiveness.summary.satisfiedEvidenceClassCount>=4);assert.equal(effectiveness.cohort.selectedIncidentCount,20);assert.ok(effectiveness.cohort.selectedRequirementCount>=30);assert.ok(effectiveness.cohort.evidenceClasses.length>=5);
  assert.ok(effectiveness.requirements.some(item=>item.state!=='SATISFIED'),'hard official/field/extent requirements remain visible rather than being selected away');
  for(const requirement of effectiveness.requirements.filter(item=>item.state==='SATISFIED')){assert.deepEqual(requirement.transitionHistory.map(item=>item.newState),['COLLECTION_PLANNED','COLLECTING','PARTIALLY_SATISFIED','SATISFIED']);assert.ok(requirement.currentAssessment.incidentRevisionHash);assert.equal(requirement.incidentVerificationImpact,'NONE');}
  assert.ok(effectiveness.latency.scheduling.p95Ms<250);assert.ok(effectiveness.latency.admissionDecision.p95Ms<500);assert.ok(effectiveness.latency.incidentRevision.p95Ms<500);assert.ok(effectiveness.latency.operatorUpdate.p95Ms<500);
  assert.equal(result.recovery.truth.counts.VERIFIED_CURRENT,0);assert.equal(result.recovery.truth.incidents[0].classification,'DETECTION_CANDIDATE');assert.equal(result.recovery.truth.incidents[0].countsAsActive,false);assert.ok(result.recovery.truth.incidents[0].priority.factors.some(item=>item.code==='TERRAIN_CONTEXT'&&item.value==='AVAILABLE'));
  assert.equal(result.geometryAudit.thermalGeometryExcludedFromPerimeterMetrics,true);assert.equal(result.geometryAudit.officialPerimeterAreaClaims,0);assert.equal(result.geometryAudit.exactEqualityFailures,0);
  assert.ok(collection.summary.satisfiedRequirements>=20);assert.ok(collection.requirements.length>=30);
});

test('controlled EOC exercise is isolated and cannot close until every operational object and acknowledgement exists', async () => {
  let state={operationalPeriods:[],operationalPeriodAfterActionPackages:[],audit:[]};const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},at='2026-09-04T14:30:00.000Z',service=new OperationalPeriodService({repository,clock:()=>new Date(at)}),actor={id:'administrator:exercise',role:'administrator',incidentScopes:['incident:exercise']},due='2026-09-04T18:00:00.000Z';
  const period=await service.start(actor,{periodId:'period:controlled-eoc',exerciseMode:true,executionMode:'AUTOMATED_RELEASE_REHEARSAL',participantType:'AUTOMATED_RELEASE_OPERATOR',shift:'Controlled field-deployment rehearsal',commander:'Exercise commander',endsAt:due,roles:['Incident Commander','Intelligence Lead','Operations Lead','Protection / Alert Authority','Field / Resource Operator','Observer / Auditor'].map((role,index)=>({role,person:`Exercise role ${index+1}`})),authorityMatrix:[{role:'Incident Commander',capability:'Approve internal exercise action',scope:'CONTROLLED_EOC_EXERCISE'}],incidentOwners:[{incidentId:'incident:exercise',owner:'Exercise intelligence lead'}],objectives:[{objectiveId:'objective:exercise',statement:'Verify the candidate and execute a no-send protection rehearsal.',owner:'Exercise commander',dueAt:due}]});
  await assert.rejects(()=>service.close(actor,period.periodId,{summary:'Incomplete close must fail.'}),/operational_period_exercise_incomplete/);
  await service.record(actor,period.periodId,{kind:'OBJECTIVE_ACKNOWLEDGEMENT',objectiveId:'objective:exercise'});
  await service.record(actor,period.periodId,{kind:'TACTIC',tacticId:'tactic:field-verification',incidentId:'incident:exercise',objectiveId:'objective:exercise',statement:'Collect an attributable field update.',owner:'Operations lead'});
  await service.record(actor,period.periodId,{kind:'AUTHORITY_DECISION',decisionId:'decision:no-send',incidentId:'incident:exercise',statement:'Authorize an exercise-only CAP draft with external transport disabled.',owner:'Protection authority',authority:'CONTROLLED_EOC_EXERCISE',dueAt:due,acknowledged:true,state:'APPROVED'});
  await service.record(actor,period.periodId,{kind:'ASSIGNMENT',assignmentId:'assignment:field-check',incidentId:'incident:exercise',tacticId:'tactic:field-verification',assignee:'Field operator',resourceIds:['resource:exercise-unit'],authorityDecisionId:'decision:no-send',dueAt:due,state:'COMPLETED'});
  await service.record(actor,period.periodId,{kind:'RESOURCE_STATUS',resource:'resource:exercise-unit',assigned:1,available:0,state:'EXERCISE_ASSIGNED'});
  await service.record(actor,period.periodId,{kind:'ACTION',actionId:'action:field-check',assignmentId:'assignment:field-check',incidentId:'incident:exercise',statement:'Record the exercise field-verification result.',owner:'Field operator',source:'CONTROLLED_EOC_EXERCISE field-update form',authorityDecisionId:'decision:no-send',dueAt:due,expectedPostcondition:'An attributable exercise field update is retained.',completionCriteria:'The assignment and update receipt are persisted.',state:'COMPLETED'});
  await service.record(actor,period.periodId,{kind:'ACKNOWLEDGEMENT',targetType:'ASSIGNMENT',targetId:'assignment:field-check',role:'Field / Resource Operator'});
  await service.record(actor,period.periodId,{kind:'ACKNOWLEDGEMENT',targetType:'ACTION',targetId:'action:field-check',role:'Operations Lead'});
  await service.record(actor,period.periodId,{kind:'PROTECTION_ITEM',workflowId:'protect:exercise:no-send',incidentId:'incident:exercise',state:'EXTERNAL_SEND_DISABLED',owner:'Protection authority',dueAt:due});
  await service.record(actor,period.periodId,{kind:'POSTCONDITION',postconditionId:'postcondition:field-update',incidentId:'incident:exercise',actionId:'action:field-check',statement:'Exercise field update retained.',observedState:'OBSERVED',source:'Exercise audit receipt',observedAt:at});
  await service.record(actor,period.periodId,{kind:'OUTCOME',outcomeId:'outcome:exercise',incidentId:'incident:exercise',actionId:'action:field-check',postconditionId:'postcondition:field-update',classification:'INDETERMINATE',statement:'The workflow completed; the exercise does not establish real-world protection impact.',causalClaim:'NOT_ESTABLISHED',evidenceIds:['postcondition:field-update']});
  await service.record(actor,period.periodId,{kind:'AFTER_ACTION_FINDING',statement:'A human role-play remains required before pilot go.',owner:'Pilot lead',dueAt:due});
  const beforeHandoff=service.snapshot(actor).current.fingerprint;
  const handedOff=await service.handoff(actor,period.periodId,{from:'Exercise commander',to:'Incoming exercise commander',acknowledgedBy:'Incoming exercise commander'});
  assert.notEqual(handedOff.fingerprint,beforeHandoff);assert.equal(handedOff.handoff.state,'ACKNOWLEDGED');assert.equal(handedOff.updatedAt,at);
  const beforeClose=handedOff.fingerprint,closed=await service.close(actor,period.periodId,{summary:'Automated isolated rehearsal completed with external send disabled and no production claims.'}),snapshot=service.snapshot(actor);
  assert.notEqual(closed.period.fingerprint,beforeClose);assert.equal(closed.period.updatedAt,at);
  assert.equal(closed.period.state,'CLOSED');assert.equal(closed.period.universe,'CONTROLLED_EOC_EXERCISE');assert.equal(closed.afterActionPackage.outcomes[0].classification,'INDETERMINATE');assert.equal(snapshot.current,null);assert.equal(snapshot.readiness.externalReadiness.liveExercise,'AUTOMATED_REHEARSAL_ONLY');assert.equal(snapshot.latestExercise.exerciseDeclaration.countsAsLiveIncident,false);assert.equal(snapshot.latestExercise.exerciseDeclaration.countsAsProductionOutcome,false);
});

test('operator lifecycle transitions require acknowledgements and outcome lineage', async () => {
  let state={operationalPeriods:[],operationalPeriodAfterActionPackages:[],audit:[]};const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},service=new OperationalPeriodService({repository,clock:()=>new Date('2026-09-04T15:00:00.000Z')}),actor={id:'supervisor:lifecycle',role:'supervisor',incidentScopes:['incident:lifecycle']},due='2026-09-04T18:00:00.000Z';
  const period=await service.start(actor,{periodId:'period:lifecycle',shift:'Lifecycle',commander:'Commander',endsAt:due,incidentOwners:[{incidentId:'incident:lifecycle',owner:'Commander'}],objectives:[{objectiveId:'objective:lifecycle',statement:'Preserve access.',owner:'Commander',dueAt:due}]});
  await service.record(actor,period.periodId,{kind:'TACTIC',tacticId:'tactic:lifecycle',incidentId:'incident:lifecycle',objectiveId:'objective:lifecycle',statement:'Verify access.',owner:'Operations'});
  await service.record(actor,period.periodId,{kind:'ASSIGNMENT',assignmentId:'assignment:lifecycle',incidentId:'incident:lifecycle',tacticId:'tactic:lifecycle',assignee:'Field unit',dueAt:due});
  await assert.rejects(()=>service.record(actor,period.periodId,{kind:'ASSIGNMENT_STATE',assignmentId:'assignment:lifecycle',state:'COMPLETED'}),/assignment_completion_requires_acknowledgement/);
  await service.record(actor,period.periodId,{kind:'ACKNOWLEDGEMENT',targetType:'ASSIGNMENT',targetId:'assignment:lifecycle',role:'Field unit'});
  await service.record(actor,period.periodId,{kind:'ASSIGNMENT_STATE',assignmentId:'assignment:lifecycle',state:'COMPLETED'});
  await service.record(actor,period.periodId,{kind:'ACTION',actionId:'action:lifecycle',incidentId:'incident:lifecycle',assignmentId:'assignment:lifecycle',statement:'Check road.',owner:'Field unit',dueAt:due,expectedPostcondition:'Road state observed.',completionCriteria:'Attributable observation retained.'});
  await assert.rejects(()=>service.record(actor,period.periodId,{kind:'ACTION_STATE',actionId:'action:lifecycle',state:'COMPLETED'}),/action_completion_requires_acknowledgement/);
  await service.record(actor,period.periodId,{kind:'ACKNOWLEDGEMENT',targetType:'ACTION',targetId:'action:lifecycle',role:'Field unit'});
  await service.record(actor,period.periodId,{kind:'ACTION_STATE',actionId:'action:lifecycle',state:'COMPLETED'});
  await service.record(actor,period.periodId,{kind:'POSTCONDITION',postconditionId:'postcondition:lifecycle',incidentId:'incident:lifecycle',actionId:'action:lifecycle',statement:'Road observation retained.',observedState:'PARTIALLY_BLOCKED',source:'Field report receipt',observedAt:'2026-09-04T14:59:00.000Z'});
  await assert.rejects(()=>service.record(actor,period.periodId,{kind:'OUTCOME',incidentId:'incident:lifecycle',actionId:'action:other',postconditionId:'postcondition:lifecycle',classification:'PARTIAL',statement:'Forged lineage.'}),/outcome_action_not_found|outcome_postcondition_lineage_invalid/);
  const result=await service.record(actor,period.periodId,{kind:'OUTCOME',incidentId:'incident:lifecycle',actionId:'action:lifecycle',postconditionId:'postcondition:lifecycle',classification:'PARTIAL',statement:'Access remains constrained.',causalClaim:'NOT_ESTABLISHED'});
  assert.equal(result.assignments[0].state,'COMPLETED');assert.equal(result.actions[0].state,'COMPLETED');assert.equal(result.outcomes[0].classification,'PARTIAL');assert.equal(result.outcomes[0].postconditionId,'postcondition:lifecycle');
});
