import assert from 'node:assert/strict';
import { mkdtemp,readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { AcquisitionStore } from '../src/modules/acquisition/acquisition-store.mjs';
import { geometryCentroid } from '../src/modules/reality-network/providers/arcgis-provider.mjs';
import { parseCapXml } from '../src/modules/reality-network/parsers/cap-xml-parser.mjs';
import { ProviderStateStore } from '../src/modules/reality-network/provider-state-store.mjs';
import { RawDataVault } from '../src/modules/reality-network/raw-data-vault.mjs';
import { redactRequestIdentity,validateTrustedEndpoint } from '../src/modules/reality-network/trusted-endpoint.mjs';
import { createRealityCoverageIndex,createRealitySourceRegistry } from '../src/modules/reality-network/source-registry.mjs';

test('trusted endpoint boundary rejects SSRF targets and redacts credentials',()=>{assert.throws(()=>validateTrustedEndpoint('http://example.com',{allowedHosts:['example.com']}),/https_required/);assert.throws(()=>validateTrustedEndpoint('https://127.0.0.1/a',{allowedHosts:['127.0.0.1']}),/private_host/);assert.throws(()=>validateTrustedEndpoint('https://evil.example/a',{allowedHosts:['example.com']}),/not_allowed/);assert.equal(redactRequestIdentity('https://example.com/a?MAP_KEY=secret',{secretValues:['secret'],sensitiveQueryKeys:['MAP_KEY']}),'https://example.com/a?MAP_KEY=REDACTED');});
test('CAP parser accepts bounded CAP and rejects entity expansion',()=>{const xml='<?xml version="1.0"?><alert><identifier>x</identifier><sender>ops@example</sender><sent>2026-08-24T00:00:00Z</sent><status>Actual</status><msgType>Alert</msgType><scope>Public</scope><info><event>Fire Warning</event><area><areaDesc>Test</areaDesc><polygon>47,-121 47.1,-121 47,-120.9</polygon></area></info></alert>',alerts=parseCapXml(xml);assert.equal(alerts[0].infos[0].event,'Fire Warning');assert.throws(()=>parseCapXml('<!DOCTYPE x [<!ENTITY y "z">]><alert>&y;</alert>'),/unsafe_xml/);});
test('ArcGIS centroid handles deeply nested polygon coordinates',()=>{assert.deepEqual(geometryCentroid({type:'Polygon',coordinates:[[[-2,40],[0,42],[2,40],[-2,40]]]}),[-.5,40.5]);});
test('raw vault preserves bytes, retrieval provenance, and survives restart',async()=>{const root=await mkdtemp(path.join(tmpdir(),'reality-vault-')),stateFile=path.join(root,'provider.json'),acquisitionFile=path.join(root,'acquisition.json'),archiveDir=path.join(root,'raw'),state=new ProviderStateStore({filePath:stateFile}),store=new AcquisitionStore({filePath:acquisitionFile,archiveDir}),vault=new RawDataVault({acquisitionStore:store,stateStore:state});await vault.initialize();const saved=await vault.preserve({providerId:'test-provider',sourceId:'test:source',providerProductId:'product-1',body:Buffer.from('real bytes'),requestIdentity:'https://example.com/product',response:{status:200,contentType:'application/octet-stream',headers:{etag:'"1"'},sourceTimestamp:'2026-08-24T00:00:00Z'},licenceId:'TEST',parserVersion:'v1',requestWindow:{bbox:[0,0,1,1]},fetchRunId:'run-1',retrievedAt:'2026-08-24T00:00:01Z'});await vault.bindOutcome(saved.retrieval,{canonicalEventIds:['event-1']});const restartedState=new ProviderStateStore({filePath:stateFile}),restartedStore=new AcquisitionStore({filePath:acquisitionFile,archiveDir}),restarted=new RawDataVault({acquisitionStore:restartedStore,stateStore:restartedState});await restarted.initialize();assert.equal(restarted.status().rawProductCount,1);assert.equal((await readFile(restartedStore.productArchivePath(saved.product.id),'utf8')),'real bytes');assert.equal(restartedState.status().retrievals.some((item)=>item.canonicalEventIds.includes('event-1')),true);});
test('source registry and coverage index expose the activated portfolio',()=>{const registry=createRealitySourceRegistry(),coverage=createRealityCoverageIndex();assert.equal(registry.sources.length,11);assert.equal(coverage.entries.length,11);assert.ok(registry.sources.some((item)=>item.familyClass==='PHYSICAL'));assert.ok(coverage.entries.some((item)=>item.productId==='IFS_OPEN_DATA_0P25'));});
