import assert from 'node:assert/strict';
import test from 'node:test';
import { access,mkdir,mkdtemp,readFile,rm,writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { browserAttestationMac,browserEvidenceMatches,classifyBrowserCertificationFailure } from '../../../scripts/release/browser_evidence.mjs';
import { destroyBrowserRuntimeSnapshot,materializeBrowserRuntime,publicBrowserRuntime } from '../../../scripts/release/browser_runtime.mjs';
import { destroyCertificationRuntimeSnapshot,materializeCertificationRuntime,publicCertificationRuntime,verifyCertificationRuntime } from '../../../scripts/release/certification_runtime.mjs';
import { isolatedProducerArguments,isolatedProducerEnvironment } from '../../../scripts/release/run_operator_certification.mjs';
import { artifactHelperArguments } from '../../../scripts/release/safe_artifact.mjs';

const manifest={releaseId:'release-current',codeStateHash:'sha256:current',operationalDataHash:`sha256:${'d'.repeat(64)}`,releaseStatementHash:`sha256:${'e'.repeat(64)}`,canonicalOperatorConsole:{path:'apps/operator-console',origin:'http://127.0.0.1:4190',sourceHash:'sha256:frontend-current'}};
const projectRoot=fileURLToPath(new URL('../../..',import.meta.url)),run=promisify(execFile);
const states=['overview-truth-first','detect-first-event','detect-second-event','detect-third-event','evidence-selected-event','handoff-bounded-work','prevent-real-comparator','source-health-semantics','fieldnet-truth-boundary','replay-focus-continuity','settings-persistence','responsive-1600x1000','responsive-1440x900','responsive-1280x800','responsive-1024x768','responsive-768x1024','responsive-430x932','responsive-390x844','responsive-320x568'];
const frontend={id:'operator-console',path:'apps/operator-console',origin:'http://127.0.0.1:4190',sourceHash:'sha256:frontend-current',assetDigest:`sha256:${'a'.repeat(64)}`};
const browserRuntime={schemaVersion:'vigia.browser-certification-browser.v1',platform:'darwin',architecture:'arm64',product:'Google Chrome for Testing',version:'151.0.7922.34',bytes:100,sha256:`sha256:${'b'.repeat(64)}`,assets:[{name:'icudtl.dat',bytes:10,sha256:`sha256:${'c'.repeat(64)}`}]};
const key='k'.repeat(43),runNonce='1'.repeat(64),options={attestationKey:key,runNonce,browserRuntime};
const validEvidence=()=>{const cdpUrl='http://127.0.0.1:49152',evidence={schemaVersion:'vigia.running-browser-certification.v6',state:'PASS',releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,operationalDataHash:manifest.operationalDataHash,certifiedRuntimeReleaseStatementHash:manifest.releaseStatementHash,frontend,assetDigestVerified:true,remoteAssetDigestVerified:true,remoteAssetFiles:42,remoteAssetBytes:4096,browserTransport:'CERTIFIER_OWNED_CDP',cdpUrl,browserRuntime,realPortugalEventsVerified:3,consoleErrors:0,unexpectedHttpErrors:0,routeNotFoundOccurrences:0,identityContradictions:0,cases:states.map((viewState,index)=>({case:index+1,state:'PASS',viewState,releaseId:manifest.releaseId,codeStateHash:manifest.codeStateHash,frontend,screenshot:`data/validation/release/operator-console-screenshots/${String(index+1).padStart(2,'0')}-${viewState}.png`,screenshotSha256:`sha256:${String(index%10).repeat(64)}`,horizontalOverflowPx:0,viewport:{width:1440,height:900}})),intelligenceScenarios:Array.from({length:24},(_,index)=>({scenario:index+1,state:'PASS',evidence:{verified:true}})),intelligencePerformance:{cachedProjectionMaximumMs:1,inboxHttpMs:10,projectionP95Ms:2},performanceMs:{routeSwitchMaximum:20,eventSelectionMaximum:30},attestation:{schemaVersion:'vigia.browser-certification-attestation.v2',runNonce,producerPid:123,browserVersion:'Chromium test',browserProcess:{pid:456,profileNonce:'1'.repeat(48),endpoint:cdpUrl,executableSha256:browserRuntime.sha256}}};evidence.attestationMac=browserAttestationMac(evidence,key);return evidence;};

test('browser evidence is reusable only for the exact current code identity and a real PASS',()=>{
  const evidence=validEvidence();
  assert.equal(browserEvidenceMatches(evidence,manifest,options),true);
  assert.equal(browserEvidenceMatches(evidence,manifest),false);
  assert.equal(browserEvidenceMatches({...evidence,state:'BLOCKED'},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,codeStateHash:'sha256:stale'},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,operationalDataHash:'sha256:stale'},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,certifiedRuntimeReleaseStatementHash:'sha256:stale'},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,cases:null},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,intelligenceScenarios:evidence.intelligenceScenarios.slice(0,23)},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,frontend:{...evidence.frontend,sourceHash:'sha256:stale'}},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,frontend:{...evidence.frontend,path:'apps/mission-dark'}},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,cdpUrl:'http://127.0.0.1:9222'},manifest,options),false);
  assert.equal(browserEvidenceMatches({...evidence,browserRuntime:{...browserRuntime,version:'tampered'}},manifest,options),false);
});

test('browser evidence rejects duplicate, traversing, incomplete, and self-attested screenshot cases',()=>{
  const duplicate=validEvidence();duplicate.cases[1].screenshot=duplicate.cases[0].screenshot;assert.equal(browserEvidenceMatches(duplicate,manifest,options),false);
  const traversal=validEvidence();traversal.cases[0].screenshot='data/validation/release/operator-console-screenshots/../forged.png';assert.equal(browserEvidenceMatches(traversal,manifest,options),false);
  const forged=validEvidence();forged.cases[0].state='overview-truth-first';assert.equal(browserEvidenceMatches(forged,manifest,options),false);
  const repeatedScenario=validEvidence();repeatedScenario.intelligenceScenarios[23].scenario=1;assert.equal(browserEvidenceMatches(repeatedScenario,manifest,options),false);
  const claimedAsset=validEvidence();claimedAsset.assetDigestVerified=false;assert.equal(browserEvidenceMatches(claimedAsset,manifest,options),false);
  const localOnlyAsset=validEvidence();localOnlyAsset.remoteAssetDigestVerified=false;assert.equal(browserEvidenceMatches(localOnlyAsset,manifest,options),false);
  assert.equal(browserEvidenceMatches(validEvidence(),manifest,{attestationKey:'x'.repeat(43),runNonce}),false);
});

test('macOS browser-process denial is distinguished from a product certification failure',()=>{
  const blocked=classifyBrowserCertificationFailure({stderr:'FATAL MachPortRendezvousServer Permission denied (1100)'});
  assert.equal(blocked.state,'BLOCKED');assert.equal(blocked.code,'HOST_BROWSER_PROCESS_SANDBOX_DENIED');
  const failed=classifyBrowserCertificationFailure(new Error('horizontal_overflow:14:22'));
  assert.equal(failed.state,'FAIL');assert.equal(failed.code,'BROWSER_CERTIFICATION_EXECUTION_FAILED');
});

test('remote web image builds only the canonical admitted operator console and generated staging is non-executing',async()=>{const[dockerfile,compose,operatorServer,apiServer,builder,executor,certifier,finalizer,orchestrator,safeArtifact]=await Promise.all([readFile(new URL('../../../infra/Dockerfile.operator',import.meta.url),'utf8'),readFile(new URL('../../../infra/docker-compose.remote-shadow.yml',import.meta.url),'utf8'),readFile(new URL('../../operator-console/server.mjs',import.meta.url),'utf8'),readFile(new URL('../src/server.mjs',import.meta.url),'utf8'),readFile(new URL('../../../scripts/release/build_release_manifest.mjs',import.meta.url),'utf8'),readFile(new URL('../../../scripts/release/execute_safe_staging.mjs',import.meta.url),'utf8'),readFile(new URL('../../../scripts/release/certify_operator_console.mjs',import.meta.url),'utf8'),readFile(new URL('../../../scripts/release/finalize_screenshots.mjs',import.meta.url),'utf8'),readFile(new URL('../../../scripts/release/run_operator_certification.mjs',import.meta.url),'utf8'),readFile(new URL('../../../scripts/release/safe_artifact.mjs',import.meta.url),'utf8')]);assert.match(dockerfile,/apps\/operator-console/);assert.doesNotMatch(dockerfile,/COPY\s+apps\/web/);assert.match(compose,/dockerfile:\s*infra\/Dockerfile\.operator/);assert.match(compose,/127\.0\.0\.1:\$\{VIGIA_SHADOW_PORT:-4190\}:4190/);assert.match(compose,/VIGIA_OPERATOR_ACCESS_TOKEN_FILE/);assert.match(operatorServer,/operator_console_one_time_admission_required/);assert.match(operatorServer,/HttpOnly; SameSite=Strict/);assert.match(operatorServer,/frame-ancestors 'none'/);assert.match(apiServer,/const hub = new SseHub\(\)/);assert.match(builder,/commandExecutesCommit:false/);assert.match(builder,/exit 0/);assert.doesNotMatch(executor,/git add|git commit/);assert.doesNotMatch(builder,/execute_safe_staging\.mjs/);assert.match(executor,/disabled_no_staging_or_commit_authorized/);assert.match(certifier,/standalone_operator_certification_disabled/);assert.match(finalizer,/standalone_screenshot_promotion_disabled/);assert.match(orchestrator,/STDIN_V1/);assert.match(orchestrator,/entry\(producerPath\)\?\.sha256!==digest\(producerBytes\)/);assert.match(orchestrator,/materializeCertificationRuntime/);assert.match(orchestrator,/return\['-s','-S','-B','-P','-X'/);assert.match(orchestrator,/sys\.path\.append/);assert.doesNotMatch(orchestrator,/VIGIA_BROWSER_CERTIFICATION_KEY\s*:/);assert.match(safeArtifact,/const helperSource=String\.raw/);assert.doesNotMatch(safeArtifact,/secure_artifact\.py/);});

test('browser producer ignores hostile Python and Node startup environments before attestation',async()=>{const testRoot=path.join(projectRoot,'.tmp/test');await mkdir(testRoot,{recursive:true});const hostile=await mkdtemp(path.join(testRoot,'vigia-hostile-python-')),sentinel=path.join(hostile,'startup-ran'),sitecustomize=path.join(hostile,'sitecustomize.py');try{await writeFile(sitecustomize,`from pathlib import Path\nPath(${JSON.stringify(sentinel)}).write_text('attestation-intercepted')\n`);const env=isolatedProducerEnvironment({...process.env,PYTHONPATH:hostile,PYTHONHOME:hostile,PYTHONSTARTUP:sitecustomize,PYTHONINSPECT:'1',NODE_OPTIONS:`--require=${sitecustomize}`});assert.deepEqual(Object.keys(env).filter((key)=>/^PYTHON/i.test(key)||key==='NODE_OPTIONS'),[]);assert.deepEqual(isolatedProducerArguments('print("isolated")').slice(0,5),['-s','-S','-B','-P','-X']);const{stdout}=await run(path.join(projectRoot,'.venv/bin/python'),isolatedProducerArguments('print("isolated")'),{cwd:projectRoot,env});assert.equal(stdout.trim(),'isolated');assert.deepEqual(artifactHelperArguments('read',projectRoot,path.join(projectRoot,'package.json'),1024).slice(0,4),['-I','-S','-B','-c']);await assert.rejects(access(sentinel),error=>error.code==='ENOENT');}finally{await rm(hostile,{recursive:true,force:true});}});

test('browser producer imports only the private hash-locked certification runtime snapshot',async()=>{const source=await verifyCertificationRuntime({projectRoot}),publicRuntime=publicCertificationRuntime(source),tampered=structuredClone(publicRuntime);assert.deepEqual(publicRuntime.startupHooks.names,['_virtualenv.pth']);tampered.dependencies.digest=`sha256:${'0'.repeat(64)}`;await assert.rejects(verifyCertificationRuntime({projectRoot,lockOverride:tampered}),/browser_certification_runtime_lock_mismatch:complete/);const runtime=await materializeCertificationRuntime({projectRoot});try{assert.notEqual(runtime.python,source.python);assert.equal(runtime.sourceRuntimeDigest,source.runtimeDigest);const program=`import sys\nsys.path.append(${JSON.stringify(runtime.sitePackages)})\nfrom playwright.sync_api import sync_playwright\nprint(sys.executable)`,{stdout}=await run(runtime.python,isolatedProducerArguments(program,{pycachePrefix:path.join(projectRoot,'.tmp/test/certification-runtime-pycache')}),{cwd:projectRoot,env:isolatedProducerEnvironment(process.env,runtime)});assert.equal(stdout.trim(),runtime.python);}finally{await destroyCertificationRuntimeSnapshot(runtime);}});

test('certification runtime traversal, hashing, copying, and sealing share explicit resource bounds',async()=>{const source=await readFile(new URL('../../../scripts/release/certification_runtime.mjs',import.meta.url),'utf8');for(const contract of ['maximumEntries','maximumDepth','maximumBytes','maximumStandardLibraryBytes','maximumDependencyBytes','deadlineMs','certification_runtime_deadline_exceeded','certification_runtime_entry_limit_exceeded','certification_runtime_depth_exceeded','certification_runtime_byte_limit_exceeded'])assert.match(source,new RegExp(contract));assert.doesNotMatch(source,/\bcp\(/);});

test('trusted certification launcher clears hostile Node preloads before Node starts',async()=>{const{stdout}=await run('/bin/sh',['scripts/release/trusted_operator_certification.sh','--probe'],{cwd:projectRoot,env:{...process.env,NODE_OPTIONS:'--require=/definitely/untrusted/vigia-preload.cjs'}}),result=JSON.parse(stdout);assert.equal(result.state,'PASS');assert.equal(result.startupEnvironment,'ISOLATED');assert.match(result.node,/\/opt\/homebrew\/Cellar\/node\/26\.0\.0\/bin\/node$/);});

test('trusted local launcher only admits a bounded temporary runtime root',async()=>{
  const[launcher,local]=await Promise.all([
    readFile(path.join(projectRoot,'scripts/release/trusted_operator_certification.sh'),'utf8'),
    readFile(path.join(projectRoot,'scripts/release/local_release.mjs'),'utf8'),
  ]);
  assert.match(launcher,/VIGIA_LOCAL_RUNTIME_ROOT="\$\{VIGIA_LOCAL_RUNTIME_ROOT-\}"/);
  assert.match(local,/local_runtime_root_outside_bounded_temporary_tree/);
  assert.match(local,/verifyDirectoryChain\(temporaryRoot,resolved,\{create:false\}\)/);
  assert.match(local,/local_runtime_state_file_invalid/);
});

test('certification launches and owns CDP from a private locked browser snapshot',async()=>{const runtime=await materializeBrowserRuntime({projectRoot});try{assert.match(runtime.executable,/\.tmp\/browser\/browser-runtime-/);const probe="import importlib.util,json,os; s=importlib.util.spec_from_file_location('smoke','scripts/release/operator_console_browser_smoke.py'); m=importlib.util.module_from_spec(s); s.loader.exec_module(m); b=m.launch_owned_browser(json.loads(os.environ['VIGIA_BROWSER_RUNTIME_JSON'])); print(b['endpoint']); m.stop_owned_browser(b)",{stdout}=await run(path.join(projectRoot,'.venv/bin/python'),['-c',probe],{cwd:projectRoot,env:{...process.env,VIGIA_BROWSER_EXECUTABLE:runtime.executable,VIGIA_BROWSER_EXECUTABLE_SHA256:runtime.sha256,VIGIA_BROWSER_PROFILE_NONCE:'2'.repeat(48),VIGIA_BROWSER_RUNTIME_JSON:JSON.stringify(publicBrowserRuntime(runtime))}});assert.match(stdout.trim(),/^http:\/\/127\.0\.0\.1:\d{2,5}$/);}finally{await destroyBrowserRuntimeSnapshot(runtime);}});

test('Python browser producer and Node finalizer derive the same attestation MAC',async()=>{const python="import hashlib,hmac,json\ndef canonical(v):\n if isinstance(v,dict): return '{'+','.join(json.dumps(k,ensure_ascii=False)+':'+canonical(v[k]) for k in sorted(v))+'}'\n if isinstance(v,list): return '['+','.join(canonical(x) for x in v)+']'\n if v is None:return 'null'\n if v is True:return 'true'\n if v is False:return 'false'\n if isinstance(v,int):return str(v)\n if isinstance(v,float):return '0' if v==0 else str(int(v)) if v.is_integer() else json.dumps(v,separators=(',',':'))\n return json.dumps(v,ensure_ascii=False,separators=(',',':'))\nkey='k'*43\ne={'schemaVersion':'vigia.running-browser-certification.v5','performanceMs':{'routeSwitchMaximum':1.0,'measurements':[0.125,2]},'attestation':{'schemaVersion':'vigia.browser-certification-attestation.v1','runNonce':'1'*64,'producerPid':123,'browserVersion':'Chromium test'}}\ne['attestationMac']='hmac-sha256:'+hmac.new(key.encode(),canonical(e).encode(),hashlib.sha256).hexdigest()\nprint(json.dumps(e))",{stdout}=await run(path.join(projectRoot,'.venv/bin/python'),['-c',python]),evidence=JSON.parse(stdout);assert.equal(evidence.attestationMac,browserAttestationMac(evidence,key));});
