import test from 'node:test';
import assert from 'node:assert/strict';
import { SourceResolutionRouter,sourceResolutionStrategy } from '../src/modules/operator/source-resolution-router.mjs';
import { OperationalRecoveryService,buildHumanAttention,buildInformationCollectionProjection,classifyOperationalIncident } from '../src/modules/operator/operational-recovery-service.mjs';
import { OutcomeService } from '../src/modules/outcomes/outcome-service.mjs';
import { ProtectionWorkflowService } from '../src/modules/protection/protection-workflow-service.mjs';
import { ShiftHandoffService } from '../src/modules/operator/shift-handoff-service.mjs';
import { HumanAttentionService } from '../src/modules/operator/human-attention-service.mjs';
import { OperationalPeriodService } from '../src/modules/operator/operational-period-service.mjs';

const at='2026-09-03T12:00:00.000Z';
const incident={incident:{id:'incident:positive-control',location:{coordinate:[-8.1,40.1]},updatedAt:at},claim:{validTime:{to:at}},evaluation:{state:'INSUFFICIENT_EVIDENCE'},evidenceGraph:{observations:[{id:'report:one',observedAt:at}],evidence:[]},evidenceDebt:{needs:[{id:'need:physical',missingQuantity:'independent physical corroboration',whyItMatters:'Determines whether the candidate can advance to verification.',eligibility:{requiredSourceFamilyClasses:['PHYSICAL']}}]}};
const twin={asOf:at,incidents:[incident],sourceHealth:{sources:[{sourceId:'nasa-firms',status:'ACTIVE'},{sourceId:'fieldnet',status:'ACTIVE'},{sourceId:'agent1-operational-projection',status:'ACTIVE'},{sourceId:'cap-authority',status:'UNKNOWN'}]}};

test('every governed source class has an exact provider strategy and bounded incident query',()=>{
  for(const id of ['nasa-firms','fieldnet','agent1-operational-projection','cap-authority']){
    const strategy=sourceResolutionStrategy(id,{incidentId:'incident:one',coordinate:[-8,40],observedAt:at,requirementId:'need:one'});
    assert.ok(strategy.strategyId);assert.ok(strategy.providerInstance);assert.ok(strategy.acquisitionMode);assert.equal(strategy.query.incidentId,'incident:one');assert.equal(strategy.query.requirementId,'need:one');
  }
});

test('retained legitimate FIRMS evidence passes the positive-control spatiotemporal association without duplicate-family inflation',async()=>{
  const router=new SourceResolutionRouter({clock:()=>new Date(at),firmsGateway:{async snapshot(){return{id:'firms',state:{state:'current'},data:[{id:'firms:one',coordinate:[-8.101,40.101],observedAt:at,sourceFamily:'viirs',independenceGroup:'viirs_noaa20',rawSourceProductId:'raw:retained:one'},{id:'firms:duplicate',coordinate:[-8.102,40.102],observedAt:at,sourceFamily:'viirs',independenceGroup:'viirs_noaa20',rawSourceProductId:'raw:retained:one'}]};}}});
  const strategy=router.strategy('nasa-firms',{incidentId:'incident:positive-control',coordinate:[-8.1,40.1],observedAt:at,requirementId:'need:physical'}),job={selectedSourceId:'nasa-firms',incidentId:'incident:positive-control',executionStrategy:strategy},acquired=await router.acquire(['nasa-firms']),result=router.evaluate(job,acquired);
  assert.equal(result.state,'QUALIFIED');assert.equal(result.matches.length,1);assert.equal(result.matches[0].recordId,'firms:one');assert.equal(result.matches[0].independenceGroup,'viirs_noaa20');assert.equal(result.receipt.state,'RECEIVED');assert.ok(result.receipt.payloadFingerprint.startsWith('sha256:'));
});

test('qualified FIRMS evidence binds through the existing canonical adapter and enters incident reevaluation',async()=>{
  let call=null;
  const router=new SourceResolutionRouter({clock:()=>new Date(at),operationalIntelligenceService:{async ingestRawProviderPayload(adapterId,payload,options){call={adapterId,payload,options};return{ingestion:[{state:'ACCEPTED'}],projection:{state:'READY',projectionHash:'sha256:positive-control'}};}}}),strategy=router.strategy('nasa-firms',{incidentId:'incident:positive-control',coordinate:[-8.1,40.1],observedAt:at,requirementId:'need:physical'}),job={selectedSourceId:'nasa-firms',incidentId:'incident:positive-control',executionStrategy:strategy},evaluation={state:'QUALIFIED',providerHealth:'CURRENT',matches:[{recordId:'firms:one',observedAt:at,distanceKm:.2,sourceFamily:'viirs',independenceGroup:'viirs_noaa20',bindingRecord:{id:'firms:one',coordinate:[-8.101,40.101],observedAt:at,satellite:'NOAA-20',instrument:'VIIRS',confidence:'nominal',frpMw:11.2,brightnessK:330,dayNight:'DAY',rawSourceProductId:'raw:retained:one'}}],rejections:{identity:0,spatial:0,temporal:0,duplicateFamily:0},receipt:{completedAt:at,payloadFingerprint:'sha256:retained-source-snapshot'}};
  const result=await router.bind(job,evaluation);
  assert.equal(result.state,'INCIDENT_REEVALUATION');assert.equal(result.bindingReceipt.state,'BOUND_FOR_REEVALUATION');assert.equal(call.adapterId,'nasa-firms');assert.deepEqual(call.options.context.correlationKeys,['incident:positive-control']);assert.equal(call.payload.latitude,40.101);assert.equal(call.payload.longitude,-8.101);
});

test('unchanged doctrine promotes a retained qualifying positive-control record and rejects stale or unverified lookalikes',()=>{
  const qualifying={...structuredClone(incident),evaluation:{state:'SATISFIED',requirementsSatisfied:true}};
  assert.equal(classifyOperationalIncident(qualifying,{at}).classification,'VERIFIED_CURRENT');
  assert.equal(classifyOperationalIncident({...structuredClone(qualifying),evaluation:{state:'INSUFFICIENT_EVIDENCE'}},{at}).classification,'DETECTION_CANDIDATE');
  assert.equal(classifyOperationalIncident({...structuredClone(qualifying),claim:{validTime:{to:'2026-08-01T00:00:00.000Z'}},incident:{...qualifying.incident,updatedAt:'2026-08-01T00:00:00.000Z'},evidenceGraph:{observations:[{observedAt:'2026-08-01T00:00:00.000Z'}]}},{at}).classification,'NEEDS_REVALIDATION');
});

test('operator projection is query-pure while the scheduler alone records real attempts and transition receipts',async()=>{
  let mutations=0,acquisitions=0,state={sourceResolutionJobs:[],certifiedActionOutcomeChains:[],protectionWorkflows:[],operationalRecovery:null};
  const repository={snapshot:()=>structuredClone(state),async mutate(mutator){mutations+=1;state=await mutator(structuredClone(state));return structuredClone(state);}},router=new SourceResolutionRouter({clock:()=>new Date(at),firmsGateway:{async snapshot(){acquisitions+=1;return{id:'firms',state:{state:'current'},data:[]};}}}),service=new OperationalRecoveryService({repository,projectRoot:'/definitely/missing',clock:()=>new Date(at),sourceResolutionRouter:router});
  const first=await service.project(twin),second=await service.project(twin);
  assert.equal(mutations,0);assert.equal(acquisitions,0);assert.equal(first.sourceResolution.summary.executionStrategyPercent,100);assert.deepEqual(first,second);
  const observed=await service.synchronize(twin),job=observed.sourceResolution.jobs[0];
  assert.equal(mutations,1);assert.equal(acquisitions,1);assert.equal(job.attemptCount,1);assert.equal(job.attemptHistory.length,1);assert.ok(job.attemptHistory[0].durableReceipt);assert.ok(job.stateTransitionHistory.some(item=>item.state==='ACQUIRING'));assert.equal(observed.sourceResolution.summary.passiveGenericWaiting,0);
  await service.project(twin);assert.equal(mutations,1);assert.equal(acquisitions,1);
});

test('live production outcome path persists distinct action, acknowledgement, expected, observed and classification records',async()=>{
  let state={productionActions:[],productionAcknowledgements:[],expectedPostconditions:[],observedPostconditions:[],outcomeClassifications:[],interventions:[],fieldOperationReceipts:[],reobservations:[],certifiedActionOutcomeChains:[],audit:[]};
  const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},clock=()=>new Date(at),service=new OutcomeService({repository,clock}),actor={id:'supervisor:one',role:'supervisor',incidentScopes:['incident:positive-control']};
  const action=(await service.createProductionAction(actor,{id:'action:one',incidentId:'incident:positive-control',objective:'Verify access before a bounded field assessment.',owner:'unit:internal-shadow',deadlineAt:'2026-09-03T13:00:00.000Z',expectedPostcondition:'An attributable access observation is recorded.'})).record;
  await service.acknowledgeProductionAction(actor,action.id,{id:'ack:one',acknowledgementType:'INTERNAL_SHADOW_ACCEPTED',source:'VIGIA command ledger'});
  await service.observePostcondition(actor,action.id,{id:'observed:one',observation:'The internal exercise recorded an attributable observation.',observedAt:at,evidenceRefs:['fieldnet:retained:test-proof']});
  await service.classifyProductionOutcome(actor,action.id,{id:'outcome:one',classification:'INDETERMINATE',rationale:'The postcondition was observed, but causal operational effect is not established.',confidenceBasis:'One governed retained field observation; no counterfactual is available.'});
  assert.deepEqual([state.productionActions.length,state.productionAcknowledgements.length,state.expectedPostconditions.length,state.observedPostconditions.length,state.outcomeClassifications.length],[1,1,1,1,1]);
  assert.match(state.observedPostconditions[0].truthBoundary,/not a success classification/);assert.equal(state.outcomeClassifications[0].classification,'INDETERMINATE');
});

test('production protection workflow fails closed at the dispatch boundary and replay can never dispatch',async()=>{
  let state={protectionWorkflows:[],audit:[]};const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},service=new ProtectionWorkflowService({repository,externalDispatch:null,clock:()=>new Date(at)}),actor={id:'supervisor:one',role:'supervisor',incidentScopes:['incident:positive-control']},input={workflowId:'protect:one',targetPopulationOrArea:{areaId:'community:retained'},exposureAssessment:'A governed exposure record requires authorized review.',protectionThreshold:'The retained policy threshold is met.',recommendation:'Prepare an authority-reviewed draft; do not send.',authorityRequirement:'Civil-protection approval',authorityOwner:'Duty supervisor',expiresAt:'2026-09-03T14:00:00.000Z',expectedPostcondition:'A delivery acknowledgement or explicit no-send receipt is retained.',provenanceRefs:['exposure:retained:one']};
  await service.create(actor,'incident:positive-control',input);await service.transition(actor,'incident:positive-control','protect:one',{state:'REVIEW'});await service.transition(actor,'incident:positive-control','protect:one',{state:'APPROVED'});await service.transition(actor,'incident:positive-control','protect:one',{state:'DISPATCH_ELIGIBLE'});
  await assert.rejects(()=>service.transition(actor,'incident:positive-control','protect:one',{state:'DISPATCHED',idempotencyKey:'one',deliveryReceipt:'fake'}),/external_protection_send_disabled/);
  const final=await service.transition(actor,'incident:positive-control','protect:one',{state:'EXTERNAL_SEND_DISABLED'});assert.equal(final.workflow.dispatch.state,'EXTERNAL_SEND_DISABLED');assert.equal(final.workflow.dispatch.externalSendEnabled,false);
  const replayState={protectionWorkflows:[{...final.workflow,workflowId:'protect:replay',universe:'CERTIFIED_REPLAY',state:'DISPATCH_ELIGIBLE',dispatch:{state:'ELIGIBLE',externalSendEnabled:true}}],audit:[]},replayRepository={snapshot:()=>structuredClone(replayState),async mutate(mutator){return mutator(structuredClone(replayState));}},replayService=new ProtectionWorkflowService({repository:replayRepository,externalDispatch:{},clock:()=>new Date(at)});
  await assert.rejects(()=>replayService.transition(actor,'incident:positive-control','protect:replay',{state:'DISPATCHED',idempotencyKey:'one',deliveryReceipt:'receipt'}),/non_production_protection_dispatch_forbidden/);
});

test('shift handoff persists the canonical attention/deadline snapshot and incoming acknowledgement receipt',async()=>{
  let state={shiftHandoffs:[],interventions:[],protectionWorkflows:[],audit:[]};const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},attention={attentionId:'attention:one',incidentId:'incident:positive-control',decision:'Confirm source',state:'ACKNOWLEDGEMENT_REQUIRED'},job={jobId:'resolver:one',incidentId:'incident:positive-control',selectedSourceId:'nasa-firms',deadlineAt:'2026-09-03T13:00:00.000Z',owner:{label:'VIGIA scheduler'},decisionImpact:'Verification remains blocked.'},service=new ShiftHandoffService({repository,operationalIntelligenceService:{async getCurrentTwin(){return twin;}},operationalRecoveryService:{async project(){return{truth:{incidents:[{incidentId:'incident:positive-control',classification:'VERIFIED_CURRENT'}]},humanAttention:{items:[attention]},sourceResolution:{jobs:[job]}};}},clock:()=>new Date(at)}),outgoing={id:'supervisor:out',role:'supervisor',incidentScopes:['incident:positive-control']},incoming={id:'supervisor:in',role:'supervisor',incidentScopes:['incident:positive-control']};
  const handoff=await service.create(outgoing,{handoffId:'handoff:one',incomingOperator:incoming.id,summary:'Measured transfer'});assert.equal(handoff.unresolvedDecisions.length,1);assert.equal(handoff.deadlines.length,1);
  const acknowledged=await service.acknowledge(incoming,handoff.handoffId,{assumeAttentionIds:['attention:one']});assert.equal(acknowledged.state,'ACKNOWLEDGED');assert.equal(acknowledged.ownershipAssumptions[0].owner,incoming.id);assert.equal(state.audit.at(-1).type,'SHIFT_HANDOFF_ACKNOWLEDGED');
});

test('human attention acknowledgement persists ownership without changing the underlying resolver or truth state',async()=>{
  let state={materialEventAcknowledgements:[],audit:[]};
  const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},attention={attentionId:'attention:resolver:one',incidentId:'incident:positive-control',resolverJobId:'resolver:one',state:'ACKNOWLEDGEMENT_REQUIRED'},recovery={humanAttention:{schemaVersion:'vigia.human-attention-queue.v1',count:1,items:[attention],truthBoundary:'Acknowledgement changes work ownership only.'}},service=new HumanAttentionService({repository,operationalIntelligenceService:{async getCurrentTwin(){return twin;}},operationalRecoveryService:{async project(){return recovery;}},clock:()=>new Date(at)}),actor={id:'supervisor:one',role:'supervisor',incidentScopes:['incident:positive-control']};
  const result=await service.acknowledge(actor,attention.attentionId,{decision:'REVIEWED_AND_ASSUMED_OWNERSHIP'});
  assert.equal(result.state,'ACKNOWLEDGED');assert.equal(result.acknowledgement.truthEffect,'WORK_STATE_ONLY');assert.equal(state.materialEventAcknowledgements.length,1);assert.equal(state.audit[0].type,'HUMAN_ATTENTION_ACKNOWLEDGED');assert.equal(recovery.humanAttention.items[0].state,'ACKNOWLEDGEMENT_REQUIRED');
  const repeated=await service.acknowledge(actor,attention.attentionId);assert.equal(repeated.state,'ALREADY_ACKNOWLEDGED');assert.equal(state.materialEventAcknowledgements.length,1);
});

test('physical information requirements fan out to every eligible collector with attempts and a next or terminal state',()=>{
  const providers=['nasa-firms','sentinel3-slstr','fieldnet'],providerAttempts=providers.map(sourceId=>({sourceId,resultState:'NO_COVERAGE',providerHealth:'CURRENT',matches:[],rejections:{identity:0,spatial:0,temporal:0,duplicateFamily:0},durableReceipt:{state:'RECEIVED',completedAt:at}})),job={jobId:'resolver:fanout',incidentId:'incident:positive-control',requirementId:'need:physical',requiredSourceClass:'PHYSICAL',requirementType:'independent physical corroboration',exactMissingFact:'independent physical corroboration',decisionImpact:'Verification requires another causal sensor family.',decisionAffected:'Incident verification',selectedSourceId:providers[0],selectedSourceIds:providers,queryParameters:{coordinate:[-8.1,40.1],anchorObservedAt:at},createdAt:at,lastAttemptAt:at,lastCheckAt:at,nextCheckAt:'2026-09-03T12:20:00.000Z',deadlineAt:'2026-09-03T18:00:00.000Z',state:'NO_COVERAGE',attemptHistory:[{providerAttempts}],lastResult:{providerAttempts,sourceStates:Object.fromEntries(providers.map(id=>[id,'CURRENT']))},owner:{kind:'SYSTEM_ACTOR',id:'scheduler',label:'VIGIA collection scheduler'},retryPolicy:{mode:'BOUNDED_PROVIDER_ACQUISITION'},escalation:{state:'ARMED',owner:'Duty intelligence lead',condition:'Escalate after the bounded SLA.'},completionCriteria:'A second admitted causal family triggers incident reevaluation.'},truth={incidents:[{incidentId:'incident:positive-control',priority:{band:'VERIFY_NOW',rank:1,score:90}}]},portfolio=buildInformationCollectionProjection([job],truth,{generatedAt:at}),requirement=portfolio.requirements[0];
  assert.equal(portfolio.summary.informationRequirements,1);assert.equal(portfolio.summary.collectionTasks,3);assert.deepEqual(requirement.collectionTasks.map(task=>task.provider.id),providers);assert.equal(requirement.collectionTasks.every(task=>task.attemptCount===1),true);assert.equal(requirement.collectionTasks.every(task=>task.lastAttempt===at),true);assert.equal(requirement.collectionTasks.every(task=>task.nextAttempt==='2026-09-03T12:20:00.000Z'||['TERMINAL_UNAVAILABLE','REJECTED'].includes(task.state)),true);assert.equal(requirement.collectionPlan.parallelism,'PARALLEL_ELIGIBLE_SOURCES');
});

test('provider failures across hundreds of machine jobs compress into one complete human decision',()=>{
  const jobs=Array.from({length:200},(_,index)=>({jobId:`resolver:${index}`,incidentId:`incident:${index}`,selectedSourceId:'cap-authority',state:'AUTH_REQUIRED',providerHealth:'NOT_CONFIGURED',lastResult:{failureClass:'CAP_PROVIDER_NOT_CONFIGURED'},deadlineAt:'2026-09-03T13:00:00.000Z',nextCheckAt:'2026-09-03T12:15:00.000Z',lastCheckAt:at,unlockCondition:'A current attributable authority record is admitted.',completionCriteria:'The official requirement resolves.',escalation:{state:'ARMED'}})),attention=buildHumanAttention(jobs,{generatedAt:at});
  assert.equal(attention.machineJobs,200);assert.equal(attention.items.length,1);assert.equal(attention.humanAttentionPercent,.5);assert.equal(new Set(attention.items.map(item=>`${item.providerId}:${item.rootCause}`)).size,1);assert.equal(attention.items.every(item=>item.deadline&&item.nextAction&&item.consequenceOfDelay&&item.ownerPolicy!==null),true);assert.equal(attention.items[0].affectedIncidentCount,200);
});

test('ownership mutation changes canonical counters, is idempotent, and survives a fresh projection',async()=>{
  const jobs=[{jobId:'resolver:ownership',incidentId:'incident:positive-control',selectedSourceId:'cap-authority',state:'AUTH_REQUIRED',providerHealth:'NOT_CONFIGURED',lastResult:{failureClass:'CAP_PROVIDER_NOT_CONFIGURED'},deadlineAt:'2026-09-03T13:00:00.000Z',nextCheckAt:'2026-09-03T12:15:00.000Z',lastCheckAt:at,unlockCondition:'A current attributable authority record is admitted.',completionCriteria:'The official requirement resolves.',escalation:{state:'ARMED'}}];let state={humanAttentionWorkStates:[],humanAttentionActions:[],materialEventAcknowledgements:[],audit:[]};
  const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},recovery={async project(){return{humanAttention:buildHumanAttention(jobs,{generatedAt:at,workStates:state.humanAttentionWorkStates,acknowledgements:state.materialEventAcknowledgements})};}},service=new HumanAttentionService({repository,operationalIntelligenceService:{async getCurrentTwin(){return twin;}},operationalRecoveryService:recovery,clock:()=>new Date(at)}),actor={id:'supervisor:one',name:'Miguel Almeida',role:'supervisor',incidentScopes:['incident:positive-control']},before=await service.snapshot(actor),id=before.items[0].attentionId,result=await service.action(actor,id,{action:'ASSUME_OWNERSHIP',idempotencyKey:'ownership:one'}),after=await service.snapshot(actor),repeat=await service.action(actor,id,{action:'ASSUME_OWNERSHIP',idempotencyKey:'ownership:one'});
  assert.deepEqual(result.counters,{needsAttention:0,myWork:1});assert.equal(after.items[0].state,'IN_PROGRESS');assert.equal(after.items[0].owner,'Miguel Almeida');assert.equal(after.items[0].acknowledgedAt,at);assert.equal(repeat.idempotent,true);assert.equal(state.humanAttentionActions.length,1);assert.equal(state.humanAttentionWorkStates.length,1);
});

test('operational period actions persist incident ownership, objectives, and handoff state',async()=>{
  let state={operationalPeriods:[]};const repository={snapshot:()=>structuredClone(state),async mutate(mutator){state=await mutator(structuredClone(state));return structuredClone(state);}},service=new OperationalPeriodService({repository,clock:()=>new Date(at)}),actor={id:'administrator:one',role:'administrator',incidentScopes:['incident:positive-control']},period=await service.start(actor,{periodId:'period:one',shift:'Day operational period',commander:'Miguel Almeida',endsAt:'2026-09-03T18:00:00.000Z',incidentOwners:[{incidentId:'incident:positive-control',owner:'Miguel Almeida'}]});
  await service.record(actor,period.periodId,{kind:'OBJECTIVE',incidentId:'incident:positive-control',statement:'Determine whether the candidate is current before the decision deadline.',owner:'Duty intelligence lead',dueAt:'2026-09-03T13:00:00.000Z'});await service.handoff(actor,period.periodId,{from:'Miguel Almeida',to:'Incoming duty lead'});const snapshot=service.snapshot(actor);
  assert.equal(snapshot.current.incidentOwners[0].owner,'Miguel Almeida');assert.equal(snapshot.current.objectives.length,1);assert.match(snapshot.current.objectives[0].statement,/Determine whether/);assert.equal(snapshot.current.handoff.state,'AWAITING_ACKNOWLEDGEMENT');
});
