import {registerTeamRoutes} from '../modules/mission/team-routes.mjs';
import {registerSituationRoutes} from '../modules/intelligence/situation-routes.mjs';
import {registerCollectionIntelligenceRoutes} from '../modules/intelligence/collection-intelligence-routes.mjs';
import { registerWorldKnowledgeRoutes } from '../modules/intelligence/world-knowledge-routes.mjs';
import { json, problem } from '../http/responses.mjs';
import { registerWorldRoutes } from '../modules/world/world-routes.mjs';
import { registerThermalRoutes } from '../modules/world/thermal-routes.mjs';
import { registerImageryRoutes } from '../modules/imagery/imagery-routes.mjs';
import { registerObservationRoutes } from '../modules/observations/observation-routes.mjs';
import { registerBasemapRoutes } from '../modules/basemap/basemap-routes.mjs';
import { registerExposureRoutes } from '../modules/exposure/exposure-routes.mjs';
import { registerPreventionRoutes } from '../modules/prevention/prevention-routes.mjs';
import { registerPreventionFindingRoutes } from '../modules/prevention/prevention-finding-routes.mjs';
import { registerHazardRoutes } from '../modules/prevention/hazard-routes.mjs';
import { registerDetectionRoutes } from '../modules/detection/detection-routes.mjs';
import { registerResponseRoutes } from '../modules/response/response-routes.mjs';
import { registerResponseCapabilityRoutes } from '../modules/response-capability/response-capability-routes.mjs';
import { registerRemediationRoutes } from '../modules/interventions/remediation-routes.mjs';
import { registerMissionRoutes } from '../modules/mission/mission-routes.mjs';
import { registerGroundTruthRoutes } from '../modules/mission/ground-truth-routes.mjs';
import { registerControlRoutes } from '../modules/control/control-routes.mjs';
import { registerAuditRoutes } from '../modules/audit/audit-routes.mjs';
import { registerEvidenceRequestRoutes } from '../modules/verification/evidence-request-routes.mjs';
import { registerIncidentReviewRoutes } from '../modules/verification/incident-review-routes.mjs';
import { registerOutcomeRoutes } from '../modules/outcomes/outcome-routes.mjs';
import { registerLiveRoutes } from '../modules/live/live-routes.mjs';
import { registerEventRoutes } from '../modules/events/event-routes.mjs';
import { registerSensorRoutes } from '../modules/sensors/sensor-routes.mjs';
import { registerAlertRoutes } from '../modules/alerts/alert-routes.mjs';
import { registerReplayRoutes } from '../modules/replay/replay-routes.mjs';
import { registerTerritoryCommandRoutes } from '../modules/territory/territory-command-routes.mjs';
import { registerMonitoredTerritoryRoutes } from '../modules/monitored-territory/monitored-territory-routes.mjs';
import { registerSessionRoutes } from '../modules/session/session-routes.mjs';
import { registerCommandProjectionRoutes } from '../modules/mission/command-projection-routes.mjs';
import { registerFieldNetRoutes } from '../modules/fieldnet/fieldnet-routes.mjs';
import { registerFieldCapacityAdmissionRoutes } from '../modules/fieldnet/field-capacity-admission-routes.mjs';
import { registerMeasurementDebtRoutes } from '../modules/validation/measurement-debt-routes.mjs';
import { registerPilotRoutes } from '../modules/pilot/pilot-routes.mjs';
import { registerIncidentCommandRoutes } from '../modules/incident-command/incident-command-routes.mjs';
import { registerIntelligenceRoutes } from '../modules/intelligence/intelligence-routes.mjs';
import { publicOperationalReadiness } from '../modules/mission/operational-readiness-service.mjs';
import { registerDecisionFoundryRoutes } from '../modules/decision-foundry/decision-foundry-routes.mjs';
import { registerCanonicalOperatorRoutes } from '../modules/operator/canonical-operator-api-routes.mjs';
import { registerDecisionIntelligenceRoutes } from '../modules/operator/decision-intelligence-routes.mjs';
import { registerProtectionWorkflowRoutes } from '../modules/protection/protection-workflow-routes.mjs';
import { registerShiftHandoffRoutes } from '../modules/operator/shift-handoff-routes.mjs';
import { registerHumanAttentionRoutes } from '../modules/operator/human-attention-routes.mjs';
import { registerOperationalPeriodRoutes } from '../modules/operator/operational-period-routes.mjs';

export function registerRoutes(router, { services, hub, runtime, sessionService,releaseIdentityService }) {
  registerTeamRoutes(router,services);
  registerWorldKnowledgeRoutes(router,services);
  const live = async ({ res }) => json(res, 200, { status: 'live', version: '10.0.0', releaseId:releaseIdentityService?.identity().releaseId??null, startedAt: runtime.startedAt, startup:runtime.startup });
  const health = async ({ res }) => json(res, 200, { status: runtime.refreshState === 'ready' ? 'live_degraded_until_ready_check' : 'degraded', version: '10.0.0', product: 'VIGIA Physical Intelligence Core', universe: 'production', streamClients: hub.size, startedAt: runtime.startedAt, sourceRefreshState: runtime.refreshState, refreshMetrics:{refreshSuccesses:Number(runtime.metrics.refreshSuccesses??0),refreshFailures:Number(runtime.metrics.refreshFailures??0),lastSuccessAt:runtime.metrics.lastSuccessAt??null,lastFailureAt:runtime.metrics.lastFailureAt??null,errorPresent:Boolean(runtime.metrics.lastError)},compatibilitySource:services.agent1CompatibilityReconciler?.status?.()??null,startup:runtime.startup?{processStartedAt:runtime.startup.processStartedAt??null,listenerAt:runtime.startup.listenerAt??null,servicesReadyAt:runtime.startup.servicesReadyAt??null,listenerMs:runtime.startup.listenerMs??null,servicesReadyMs:runtime.startup.servicesReadyMs??null,phase:runtime.startup.phase??null,subphase:runtime.startup.subphase??null,phaseStartedAt:runtime.startup.phaseStartedAt??null,lastCompletedPhase:runtime.startup.lastCompletedPhase??null,phaseHistory:runtime.startup.phaseHistory??[],state:runtime.startup.servicesReadyAt?'services_ready':'loading',ready:Boolean(runtime.startup.servicesReadyAt)}:null });
  const readiness = async ({ res }) => { const value = publicOperationalReadiness(await services.operationalReadinessService.snapshot()); json(res, value.ready ? 200 : 503, value); };
  router.get('/live', live); router.get('/api/v10/live', live); router.get('/ready', readiness); router.get('/api/v10/ready', readiness);
  router.get('/api/v10/capabilities', async ({ res }) => json(res, 200, publicOperationalReadiness(await services.operationalReadinessService.snapshot())));
  router.get('/api/v10/release/routes',async({res})=>json(res,200,{schemaVersion:'vigia.route-registry.v1',releaseId:releaseIdentityService?.identity().releaseId??null,routes:router.routes()}));
  router.get('/api/v10/acquisition/status', async ({ res }) => json(res, 200, services.acquisitionStore.publicStatus()));
  router.get('/api/v10/physical-sensing/live',async({res})=>json(res,200,services.livePhysicalIntelligenceService.publicStatus()));
  router.get('/api/v1/health', health); router.get('/api/v2/health', health); router.get('/api/v9/health', health); router.get('/api/v10/health', health);
  const stream = async ({ req, res }) => { try{hub.add(res,{clientKey:req.socket?.remoteAddress});}catch(error){return problem(res,error.statusCode??503,error.message,'Stream capacity is unavailable.');}res.writeHead(200, { 'content-type': 'text/event-stream; charset=utf-8', 'cache-control': 'no-cache, no-transform', connection: 'keep-alive', 'x-accel-buffering': 'no' }); res.write(`event: connected\ndata: ${JSON.stringify({ at: new Date().toISOString() })}\n\n`);req.socket.setKeepAlive?.(true); };
  router.get('/api/v1/stream', stream); router.get('/api/v2/stream', stream); router.get('/api/v9/stream', stream); router.get('/api/v10/stream', stream);
  registerSessionRoutes(router,{sessionService,controlService:services.controlService});
  registerCommandProjectionRoutes(router,services);
  registerFieldNetRoutes(router,{...services,releaseIdentityService});
  registerFieldCapacityAdmissionRoutes(router,services);
  registerIncidentCommandRoutes(router,services);
  registerProtectionWorkflowRoutes(router,services);
  registerIntelligenceRoutes(router,services);
  registerDecisionFoundryRoutes(router,services);
  registerCanonicalOperatorRoutes(router,services);
  registerDecisionIntelligenceRoutes(router,services);
  registerSituationRoutes(router,services);
  registerCollectionIntelligenceRoutes(router,services);
  registerResponseCapabilityRoutes(router,services);
  registerShiftHandoffRoutes(router,services);
  registerHumanAttentionRoutes(router,services);
  registerOperationalPeriodRoutes(router,services);
  registerMeasurementDebtRoutes(router);
  registerPilotRoutes(router,services);
  registerWorldRoutes(router, services); registerThermalRoutes(router, services); registerImageryRoutes(router, services); registerObservationRoutes(router, services);
  registerBasemapRoutes(router, services); registerExposureRoutes(router, services); registerPreventionRoutes(router, services); registerHazardRoutes(router, services);
  registerPreventionFindingRoutes(router,services);
  registerDetectionRoutes(router, services); registerResponseRoutes(router, services); registerRemediationRoutes(router, services);
  registerMissionRoutes(router, services); registerGroundTruthRoutes(router, services); registerControlRoutes(router, services); registerAuditRoutes(router, services);
  registerEvidenceRequestRoutes(router, services); registerIncidentReviewRoutes(router, services); registerOutcomeRoutes(router, services);
  registerTerritoryCommandRoutes(router, services);
  registerMonitoredTerritoryRoutes(router,services);
  registerLiveRoutes(router, services); registerEventRoutes(router, services); registerSensorRoutes(router, services); registerAlertRoutes(router, services); registerReplayRoutes(router, services);
}
