import { createHash,randomUUID } from 'node:crypto';
import { assertCan, assertGlobalIncidentScope,assertIncidentScope } from '../../../../../packages/domain/src/authorization.mjs';
import { computeOutcomeMetrics } from '../../../../../packages/domain/src/outcome-metrics.mjs';
import { buildOutcomeLoop } from './outcome-loop.mjs';

export class OutcomeService {
  constructor({ repository,clock=()=>new Date() }) { this.repository = repository;this.clock=clock; }
  #required(value,code){if(value===null||value===undefined||String(value).trim()==='')throw Object.assign(new Error(code),{statusCode:400});return value;}
  #actor(actor,incidentId){assertCan(actor,'create:intervention');assertIncidentScope(actor,incidentId);return String(actor?.id??'');}
  #id(prefix,input){return input.id??`${prefix}:${randomUUID()}`;}
  #receipt(kind,record){return{schemaVersion:'vigia.production-outcome-receipt.v1',receiptId:`receipt:${createHash('sha256').update(`${kind}\0${record.id}\0${record.updatedAt??record.createdAt}`).digest('hex').slice(0,24)}`,kind,recordId:record.id,incidentId:record.incidentId,persistedAt:record.updatedAt??record.createdAt,universe:'LIVE_PRODUCTION'};}
  async createProductionAction(actor,input={}){const incidentId=String(this.#required(input.incidentId,'incident_id_required')),actorId=this.#actor(actor,incidentId),createdAt=this.clock().toISOString(),deadlineAt=new Date(this.#required(input.deadlineAt,'deadline_at_required')).toISOString(),expectedSummary=String(this.#required(input.expectedPostcondition,'expected_postcondition_required')),record={schemaVersion:'vigia.production-action.v2',id:this.#id('action',input),universe:'LIVE_PRODUCTION',productionTruth:true,incidentId,objective:String(this.#required(input.objective,'objective_required')),owner:String(this.#required(input.owner,'owner_required')),organization:input.organization?String(input.organization):null,deadlineAt,authorityRequirement:input.authorityRequirement?String(input.authorityRequirement):null,expectedPostconditionSummary:expectedSummary,state:'INITIATED',createdAt,createdBy:actorId,auditTrail:[{at:createdAt,actorId,state:'INITIATED'}]},expected={schemaVersion:'vigia.expected-postcondition.v1',id:input.expectedPostconditionId??`expected-postcondition:${randomUUID()}`,universe:'LIVE_PRODUCTION',productionTruth:true,incidentId,actionId:record.id,definition:expectedSummary,measurementMethod:String(input.measurementMethod??'CANONICAL_INCIDENT_STATE_REVIEW'),evaluationDueAt:new Date(input.evaluationDueAt??deadlineAt).toISOString(),observationSources:Array.isArray(input.observationSources)&&input.observationSources.length?input.observationSources.map(String):['CANONICAL_INCIDENT_STATE','OFFICIAL_UPDATE','FIELD_CONFIRMATION','SENSOR_OBSERVATION','OPERATOR_VERIFICATION'],createdAt,createdBy:actorId,automatic:true};let receipt,expectedReceipt;await this.repository.mutate(state=>{if((state.productionActions??[]).some(item=>item.id===record.id))throw Object.assign(new Error('production_action_identity_conflict'),{statusCode:409});receipt=this.#receipt('ACTION_PERSISTED',record);expectedReceipt=this.#receipt('EXPECTED_POSTCONDITION_PERSISTED',expected);return{...state,productionActions:[...(state.productionActions??[]),record],expectedPostconditions:[...(state.expectedPostconditions??[]),expected],audit:[...(state.audit??[]),receipt,expectedReceipt]};});return{record,expectedPostcondition:expected,receipt,expectedPostconditionReceipt:expectedReceipt};}
  async acknowledgeProductionAction(actor,actionId,input={}){const state=this.repository.snapshot(),action=(state.productionActions??[]).find(item=>item.id===actionId),expected=(state.expectedPostconditions??[]).find(item=>item.actionId===actionId);if(!action)throw Object.assign(new Error('production_action_not_found'),{statusCode:404});if(!expected)throw Object.assign(new Error('expected_postcondition_not_found'),{statusCode:409});const actorId=this.#actor(actor,action.incidentId),createdAt=this.clock().toISOString(),record={schemaVersion:'vigia.production-acknowledgement.v1',id:this.#id('acknowledgement',input),universe:'LIVE_PRODUCTION',productionTruth:true,incidentId:action.incidentId,actionId,acknowledgementType:String(this.#required(input.acknowledgementType,'acknowledgement_type_required')),source:String(this.#required(input.source,'acknowledgement_source_required')),note:input.note?String(input.note):null,createdAt,createdBy:actorId},schedule={schemaVersion:'vigia.postcondition-observation-schedule.v1',id:input.scheduleId??`observation-schedule:${randomUUID()}`,universe:'LIVE_PRODUCTION',incidentId:action.incidentId,actionId,expectedPostconditionId:expected.id,state:'SCHEDULED',dueAt:expected.evaluationDueAt,measurementMethod:expected.measurementMethod,eligibleSources:expected.observationSources??['CANONICAL_INCIDENT_STATE','OFFICIAL_UPDATE','FIELD_CONFIRMATION','SENSOR_OBSERVATION','OPERATOR_VERIFICATION'],owner:action.owner,createdAt,triggeredByAcknowledgementId:record.id};let receipt,scheduleReceipt;await this.repository.mutate(current=>{if((current.productionAcknowledgements??[]).some(item=>item.actionId===actionId&&item.id===record.id))throw Object.assign(new Error('production_acknowledgement_identity_conflict'),{statusCode:409});receipt=this.#receipt('ACKNOWLEDGEMENT_PERSISTED',record);const existing=(current.postconditionObservationSchedules??[]).find(item=>item.actionId===actionId&&item.state==='SCHEDULED');scheduleReceipt=existing?null:this.#receipt('POSTCONDITION_OBSERVATION_SCHEDULED',schedule);return{...current,productionAcknowledgements:[...(current.productionAcknowledgements??[]),record],postconditionObservationSchedules:existing?(current.postconditionObservationSchedules??[]):[...(current.postconditionObservationSchedules??[]),schedule],audit:[...(current.audit??[]),receipt,...(scheduleReceipt?[scheduleReceipt]:[])]};});return{record,observationSchedule:schedule,scheduleCreated:Boolean(scheduleReceipt),receipt,scheduleReceipt};}
  async defineExpectedPostcondition(actor,actionId,input={}){const state=this.repository.snapshot(),action=(state.productionActions??[]).find(item=>item.id===actionId);if(!action)throw Object.assign(new Error('production_action_not_found'),{statusCode:404});const actorId=this.#actor(actor,action.incidentId),createdAt=this.clock().toISOString(),record={schemaVersion:'vigia.expected-postcondition.v1',id:this.#id('expected-postcondition',input),universe:'LIVE_PRODUCTION',productionTruth:true,incidentId:action.incidentId,actionId,definition:String(this.#required(input.definition,'postcondition_definition_required')),measurementMethod:String(this.#required(input.measurementMethod,'measurement_method_required')),evaluationDueAt:new Date(this.#required(input.evaluationDueAt,'evaluation_due_at_required')).toISOString(),createdAt,createdBy:actorId};let receipt;await this.repository.mutate(current=>{if((current.expectedPostconditions??[]).some(item=>item.actionId===actionId))throw Object.assign(new Error('expected_postcondition_already_defined'),{statusCode:409});receipt=this.#receipt('EXPECTED_POSTCONDITION_PERSISTED',record);return{...current,expectedPostconditions:[...(current.expectedPostconditions??[]),record],audit:[...(current.audit??[]),receipt]};});return{record,receipt};}
  async observePostcondition(actor,actionId,input={}){const state=this.repository.snapshot(),action=(state.productionActions??[]).find(item=>item.id===actionId),expected=(state.expectedPostconditions??[]).find(item=>item.actionId===actionId);if(!action)throw Object.assign(new Error('production_action_not_found'),{statusCode:404});if(!expected)throw Object.assign(new Error('expected_postcondition_not_found'),{statusCode:409});const actorId=this.#actor(actor,action.incidentId),createdAt=this.clock().toISOString(),evidenceRefs=Array.isArray(input.evidenceRefs)?input.evidenceRefs.map(String).filter(Boolean):[];if(!evidenceRefs.length)throw Object.assign(new Error('postcondition_evidence_required'),{statusCode:400});const record={schemaVersion:'vigia.observed-postcondition.v1',id:this.#id('observed-postcondition',input),universe:'LIVE_PRODUCTION',productionTruth:true,incidentId:action.incidentId,actionId,expectedPostconditionId:expected.id,observation:String(this.#required(input.observation,'postcondition_observation_required')),observedAt:new Date(this.#required(input.observedAt,'observed_at_required')).toISOString(),evidenceRefs,createdAt,createdBy:actorId,truthBoundary:'An observed postcondition is evidence, not a success classification.'};let receipt;await this.repository.mutate(current=>{receipt=this.#receipt('OBSERVED_POSTCONDITION_PERSISTED',record);return{...current,observedPostconditions:[...(current.observedPostconditions??[]),record],audit:[...(current.audit??[]),receipt]};});return{record,receipt};}
  async classifyProductionOutcome(actor,actionId,input={}){const state=this.repository.snapshot(),action=(state.productionActions??[]).find(item=>item.id===actionId),expected=(state.expectedPostconditions??[]).find(item=>item.actionId===actionId),observed=(state.observedPostconditions??[]).filter(item=>item.actionId===actionId).at(-1);if(!action)throw Object.assign(new Error('production_action_not_found'),{statusCode:404});if(!expected||!observed)throw Object.assign(new Error('outcome_lineage_incomplete'),{statusCode:409});const actorId=this.#actor(actor,action.incidentId),classification=String(input.classification??'');if(!['SUCCESS','PARTIAL','FAILED','INDETERMINATE','INSUFFICIENT_EVIDENCE'].includes(classification))throw Object.assign(new Error('invalid_outcome_classification'),{statusCode:400});const createdAt=this.clock().toISOString(),record={schemaVersion:'vigia.outcome-classification.v2',id:this.#id('outcome',input),universe:'LIVE_PRODUCTION',productionTruth:true,incidentId:action.incidentId,actionId,expectedPostconditionId:expected.id,observedPostconditionId:observed.id,classification,rationale:String(this.#required(input.rationale,'outcome_rationale_required')),evidenceRefs:observed.evidenceRefs,confidenceBasis:String(this.#required(input.confidenceBasis,'outcome_confidence_basis_required')),causalClaim:'NOT_ESTABLISHED',truthBoundary:'Classification compares the expected and observed postconditions; it does not establish that the action caused the observation.',reviewer:actorId,createdAt};let receipt;await this.repository.mutate(current=>{if((current.outcomeClassifications??[]).some(item=>item.actionId===actionId))throw Object.assign(new Error('outcome_already_classified'),{statusCode:409});receipt=this.#receipt('OUTCOME_CLASSIFICATION_PERSISTED',record);return{...current,outcomeClassifications:[...(current.outcomeClassifications??[]),record],postconditionObservationSchedules:(current.postconditionObservationSchedules??[]).map(item=>item.actionId===actionId&&item.state==='SCHEDULED'?{...item,state:'COMPLETED',completedAt:createdAt,observedPostconditionId:observed.id}:item),audit:[...(current.audit??[]),receipt]};});return{record,receipt};}
  snapshot(actor) {
    assertCan(actor, 'read:outcomes');
    assertGlobalIncidentScope(actor);
    const state = this.repository.snapshot();
    const generatedAt = new Date().toISOString();
    const metrics = computeOutcomeMetrics(state),productionActions=Array.isArray(state.productionActions)?state.productionActions:[],productionAcknowledgements=Array.isArray(state.productionAcknowledgements)?state.productionAcknowledgements:[],expectedPostconditions=Array.isArray(state.expectedPostconditions)?state.expectedPostconditions:[],observedPostconditions=Array.isArray(state.observedPostconditions)?state.observedPostconditions:[],outcomeClassifications=Array.isArray(state.outcomeClassifications)?state.outcomeClassifications:[],observationSchedules=Array.isArray(state.postconditionObservationSchedules)?state.postconditionObservationSchedules:[],measurableActions=productionActions.filter(action=>expectedPostconditions.some(item=>item.actionId===action.id&&item.measurementMethod&&item.evaluationDueAt));
    const interventions = Array.isArray(state.interventions) ? state.interventions : [];
    const receipts = Array.isArray(state.fieldOperationReceipts) ? state.fieldOperationReceipts : [];
    const reobservations = Array.isArray(state.reobservations) ? state.reobservations : [];
    const loops = interventions.filter((item) => item.state === 'closed').map((item) => buildOutcomeLoop(state, item));
    const certifiedReplayChains = Array.isArray(state.certifiedActionOutcomeChains) ? state.certifiedActionOutcomeChains.filter((item) => item?.universe === 'CERTIFIED_REPLAY' && item?.productionTruth === false) : [];
    const unique = (items, identifier) => [...new Map(items.map((item) => [identifier(item), item]).filter(([id]) => typeof id === 'string' && id)).values()];
    const initiated = unique([...interventions,...productionActions], (item) => item.id);
    const acknowledged = unique([...receipts.filter((item) => item.actionId || item.remediationId || item.interventionId),...productionAcknowledgements], (item) => item.id ?? item.receiptId);
    const postconditionsDefined = unique([...interventions.filter((item) => item.expectedPostconditionId || item.postconditionDefinitionId),...expectedPostconditions], (item) => item.id??item.expectedPostconditionId??item.postconditionDefinitionId);
    const postconditionsObserved = unique([...reobservations.filter((item) => item.remediationId || item.interventionId),...observedPostconditions], (item) => item.id);
    const outcomesMeasured = unique([...loops.filter((item) => item?.methodology?.exposureChangeState === 'MEASURED' || item?.outcomeClassification?.state === 'MEASURED'),...outcomeClassifications], (item) => item?.id??item?.outcomeClassification?.id??item?.remediation?.id);
    const lineageAudit = {
      schemaVersion: 'vigia.outcome-stage-lineage-audit.v1',
      validatedAt: generatedAt,
      population: 'Persisted operator action and outcome records',
      stages: [
        { key: 'INITIATED', label: 'Actions initiated', recordType: 'intervention', count: initiated.length, distinctRecordIds: initiated.map((item) => item.id) },
        { key: 'ACKNOWLEDGED', label: 'Acknowledged', recordType: 'field_operation_receipt', count: acknowledged.length, distinctRecordIds: acknowledged.map((item) => item.id ?? item.receiptId) },
        { key: 'POSTCONDITION_DEFINED', label: 'Postcondition defined', recordType: 'postcondition_definition', count: postconditionsDefined.length, distinctRecordIds: postconditionsDefined.map((item) => item.id ?? item.expectedPostconditionId ?? item.postconditionDefinitionId) },
        { key: 'POSTCONDITION_OBSERVED', label: 'Postcondition observed', recordType: 'reobservation', count: postconditionsObserved.length, distinctRecordIds: postconditionsObserved.map((item) => item.id) },
        { key: 'OUTCOME_MEASURED', label: 'Outcome measured', recordType: 'outcome_classification', count: outcomesMeasured.length, distinctRecordIds: outcomesMeasured.map((item) => item?.id ?? item?.outcomeClassification?.id ?? item?.remediation?.id) }
      ],
      truthBoundary: 'Each stage counts only distinct persisted records of the named type. Derived work requirements, state aliases, embedded completion conditions, and inferred transitions are excluded.'
    };
    const certifiedReplayLineageAudit={
      schemaVersion:'vigia.certified-replay-lineage-audit.v1',
      validatedAt:generatedAt,
      universe:'CERTIFIED_REPLAY',
      stages:[
        {key:'INITIATED',label:'Exercise actions initiated',recordType:'certified_replay_action',count:new Set(certifiedReplayChains.map(item=>item.action?.id).filter(Boolean)).size},
        {key:'ACKNOWLEDGED',label:'Replay acknowledgements',recordType:'certified_replay_acknowledgement',count:new Set(certifiedReplayChains.map(item=>item.acknowledgement?.id).filter(Boolean)).size},
        {key:'POSTCONDITION_DEFINED',label:'Expected postconditions',recordType:'certified_replay_expected_postcondition',count:new Set(certifiedReplayChains.map(item=>item.expectedPostcondition?.id).filter(Boolean)).size},
        {key:'POSTCONDITION_OBSERVED',label:'Observed postconditions',recordType:'certified_replay_observed_postcondition',count:new Set(certifiedReplayChains.filter(item=>item.observedPostcondition?.state==='OBSERVED').map(item=>item.observedPostcondition?.id).filter(Boolean)).size},
        {key:'OUTCOME_CLASSIFIED',label:'Workflow outcomes classified',recordType:'certified_replay_outcome_classification',count:new Set(certifiedReplayChains.map(item=>item.outcomeClassification?.id).filter(Boolean)).size}
      ],
      truthBoundary:'Certified replay records are structurally isolated from live operations. They certify workflow capability only and never count as production protection outcomes.'
    };
    return {
      generatedAt,
      metrics: { ...metrics, remediationSampleSize: loops.length },
      loops,
      production:{universe:'LIVE_PRODUCTION',actions:productionActions,acknowledgements:productionAcknowledgements,expectedPostconditions,observationSchedules,observedPostconditions,outcomeClassifications,measurementReadiness:{measurableActions:measurableActions.length,totalActions:productionActions.length,percent:productionActions.length?Number((measurableActions.length/productionActions.length*100).toFixed(1)):null,state:productionActions.length?'MEASURED':'NO_LIVE_PRODUCTION_ACTIONS',definition:'An action is measurable when a distinct expected postcondition, method and evaluation due time are persisted before observation.'},truthBoundary:'Observed postconditions and outcome classifications are distinct persisted records. Replay and exercise records cannot enter these collections.'},
      exercise:{universe:'EXERCISE',state:'NOT_INSTRUMENTED',recordCount:null,truthBoundary:'No governed exercise-outcome repository is configured. Exercise state is not inferred as zero and never enters live-production or certified-replay metrics.'},
      lineageAudit,
      certifiedReplayChains,
      certifiedReplayLineageAudit,
      methodology: {
        outcomeUnit: 'Closed before/action/after proof loop',
        exposureChange: 'Unmeasured until versioned pre-action and post-action exposure sets, a matching method and review independence are present.',
        remediationTime: loops.length < 3 ? 'Individual duration shown because sample size is too small for a meaningful median.' : 'Median duration across closed proof loops.'
      },
      narrative: 'Closed local evidence loops are review records. They do not prove causal risk reduction or measured exposure change.'
    };
  }
}
