import { shell, badge, button, esc } from '../components.js?v=2.1.0';
import { icon } from '../icons.js?v=2.1.0';

export function renderAccountability(state) {
  const response=state.runtime?.operationsRoster, roster=response?.roster??[], qualification=response?.qualification??'No authenticated canonical roster was returned.';
  const available=roster.filter(p=>String(p.availability).toUpperCase()==='AVAILABLE').length;
  const cards=roster.map(p=>`<article class="person-card person-card--${String(p.availability).toUpperCase()==='AVAILABLE'?'green':'warning'}"><header>${icon('people',22)}<div><span class="eyebrow">${esc(p.actorRole??'SHADOW ACTOR')}</span><h3>${esc(p.displayName??p.actorId)}</h3><p>${esc(p.identityScope??'SHADOW')}</p></div>${badge(p.availability??'UNKNOWN',String(p.availability).toUpperCase()==='AVAILABLE'?'green':'warning',true)}</header><div class="person-card__facts"><div><span>Source</span><strong>${esc(p.source??'canonical roster')}</strong></div><div><span>Assignments</span><strong>${esc(p.assignments?.length??'—')}</strong></div></div><div class="person-card__location"><span>Identity qualification</span><strong>${esc(p.identityScope??'SHADOW')}</strong><p>This is an explicit local shadow identity, not a real firefighter/personnel claim.</p></div></article>`).join('');
  const importedIncidents=Object.values(state.runtime?.commandIncidents??{}).filter(incident=>incident?.incident?.universe==='SHADOW'&&incident?.incident?.importHash),importedPeople=importedIncidents.flatMap(incident=>Object.values(incident.persons??{}).map(person=>({person,incident}))),manualCards=importedPeople.map(({person,incident})=>`<article class="person-card person-card--warning"><header>${icon('people',22)}<div><span class="eyebrow">MANUAL IMPORT</span><h3>${esc(person.name??person.displayName??person.personId)}</h3><p>${esc(person.personId)}</p></div>${badge('NOT LIVE','warning',true)}</header><div class="person-card__facts"><div><span>Availability</span><strong>UNKNOWN</strong></div><div><span>Location</span><strong>UNKNOWN</strong></div></div><div class="person-card__location"><span>Attributable provenance</span><strong>${esc(incident.incident.importHash)}</strong><p>Imported identity only. Roster membership does not prove presence, readiness, assignment, or current availability.</p></div></article>`).join('');
  const totalIdentities=roster.length+importedPeople.length;
  const content=`<div class="accountability-route"><header class="route-heading"><div><span class="eyebrow">Accountability · truth boundary</span><h2>Operator / ownership roster</h2><p>VIGIA does not currently expose a governed live fireground personnel roster through this integration.</p></div>${badge(totalIdentities?`${totalIdentities} SHADOW IDENTITIES`:'NO ROSTER',totalIdentities?'teal':'warning')}</header><section class="integration-boundary integration-boundary--warning"><div>${icon('warning',24)}<span><strong>NO LIVE FIREFIGHTER ACCOUNTABILITY FEED</strong><small>Only canonical shadow operators and explicitly provenance-bound manual imports may be shown. Neither establishes physical presence.</small></span></div></section><section class="accountability-summary"><article>${icon('people',24)}<strong>${totalIdentities}</strong><span>Shadow identities</span></article><article>${icon('check',24)}<strong>${available}</strong><span>Explicitly available operators</span></article><article>${icon('warning',24)}<strong>0</strong><span>Live crews claimed</span></article><article>${icon('map',24)}<strong>0</strong><span>Live locations claimed</span></article></section><section class="crew-panel panel"><header><div><span class="eyebrow">Canonical operations roster</span><h2>Shadow workflow ownership</h2></div></header><p class="truth-boundary-copy">${esc(qualification)}</p><div class="person-grid">${cards||'<div class="empty-state"><strong>Roster unavailable</strong><p>Authenticate against canonical VIGIA to inspect the local SHADOW operations roster. No fake people are substituted.</p></div>'}</div></section>${manualCards?`<section class="crew-panel panel"><header><div><span class="eyebrow">Manual pilot import</span><h2>Imported identity rows · not live-synced</h2></div>${badge(`${importedPeople.length} IMPORTED`,'warning')}</header><p class="truth-boundary-copy">Every row below is retained in the SHADOW command ledger with its source hash. Availability and location remain UNKNOWN.</p><div class="person-grid">${manualCards}</div></section>`:''}<div class="accountability-actions">${button('Refresh roster',{tone:'secondary',iconName:'sync',action:'refresh-runtime'})}${button('Print boundary',{tone:'ghost',iconName:'evidence',action:'auto:open-print-fallback'})}</div></div>`;
  return shell('accountability',content);
}
