import { shell, badge, button, esc } from '../components.js?v=2.1.0';
import { icon } from '../icons.js?v=2.1.0';
import { selectedOperationsIncident, selectedEventSummary, ageLabel } from '../viewModel.js?v=2.1.0';

export function renderDispatch(state) {
  const event=selectedEventSummary(state),ops=selectedOperationsIncident(state),alerts=ops?.alerts??state.runtime?.alerts?.alerts??[],needs=ops?.evidenceNeeds??state.runtime?.command?.operations?.evidenceNeeds??[],active=alerts.filter(a=>!['RESOLVED','SUPPRESSED'].includes(String(a.lifecycleState??a.state))),assets=ops?.territoryContext?.assets??[];
  const rows=[...active.slice(0,5).map(a=>({id:a.id,label:a.title??a.reasonCode??a.alertType??'Operational alert',state:a.lifecycleState??a.state??'OPEN',meta:`${event?.label??'Portugal'} · ${ageLabel(a.createdAt??a.detectedAt)}`,tone:'warning'})),...needs.slice(0,4).map(n=>({id:n.id,label:n.subjectLabel??n.missingQuantity??n.kind??'Evidence need',state:n.state??'OPEN',meta:n.reason??'Canonical evidence work',tone:'teal'}))];
  const content=`<div class="dispatch-route"><header class="route-heading"><div><span class="eyebrow">Dispatch / EOC · integration boundary</span><h2>Regional coordination</h2><p>Real VIGIA operations alerts and evidence work are shown. No CAD, mutual-aid ETA, public-warning or agency dispatch is invented.</p></div><div class="dispatch-summary"><article><span>Active alerts</span><strong>${active.length}</strong></article><article><span>Evidence needs</span><strong>${needs.length}</strong></article><article><span>External CAD</span><strong>Not configured</strong></article></div></header><section class="integration-boundary integration-boundary--warning"><div>${icon('warning',24)}<span><strong>CAD / AVL / MUTUAL AID NOT CONFIGURED</strong><small>The previous fake backup-water request and ETA have been removed. This route now exposes only canonical VIGIA work.</small></span></div>${badge('NO EXTERNAL DISPATCH CLAIM','warning')}</section><div class="dispatch-grid"><section class="panel request-queue"><header><div><span class="eyebrow">Canonical operations work</span><h2>${esc(event?.label??'Portugal territory')}</h2></div>${badge(`${rows.length} items`,rows.length?'warning':'green')}</header>${rows.length?`<div class="operations-work-list">${rows.map(r=>`<article><span class="status-dot status-dot--${r.tone}"></span><div><strong>${esc(r.label)}</strong><small>${esc(r.meta)}</small></div>${badge(r.state,r.tone,true)}</article>`).join('')}</div>`:'<div class="empty-state"><strong>No current coordination item</strong><p>No active canonical alert or evidence need is returned.</p></div>'}<footer>${button('Open detection workspace',{tone:'secondary',iconName:'external',action:'review-incident'})}${button('Refresh',{tone:'ghost',iconName:'sync',action:'refresh-runtime'})}</footer></section><aside class="consequence-stack"><section class="panel consequence"><span class="eyebrow">Public warning</span><h3>Not configured</h3><p>No public-warning integration is inferred.</p></section><section class="panel consequence"><span class="eyebrow">Monitored assets</span><h3>${assets.length}</h3><p>${assets.length?'OSM-derived reference assets inside configured policy radius.':'No monitored asset returned for selected event.'}</p></section><section class="panel consequence"><span class="eyebrow">Territory</span><h3>${ops?.territoryContext?.insideMonitoredTerritory?'Inside monitored territory':'Unconfirmed'}</h3><p>Territory context is canonical PostGIS state.</p></section></aside></div><section class="fallback-banner">${icon('evidence',22)}<div><span class="eyebrow">External integration boundary</span><strong>Real coordination feeds must be connected before operational dispatch actions appear.</strong></div>${button('Print current VIGIA work',{tone:'primary',iconName:'evidence',action:'auto:open-print-package'})}</section></div>`;
  return shell('dispatch',content);
}
