import { shell, esc } from '../components.js?v=2.1.0';
import { icon } from '../icons.js?v=2.1.0';
import { generatedAt, humanState, objectTitle, technicalDisclosure } from '../canonicalComponents.js?v=2.1.0';
import { evidenceDebtItems, evidenceGraph, evidenceQualification, incidentAssessment, incidentCoordinate, incidentEnvelope, incidentLabel, measured, operatorText, selectedIncident, technicalIdLabel, timeLabel, value } from '../canonicalViewModel.js?v=2.1.0';

const bucketNames=['NEW','UNDER_REVIEW','CONFIRMED','CONTRADICTORY'];
const evidenceId=item=>String(item?.id??item?.evidenceId??'');
const observationId=item=>String(item?.observationId??'');
const sourceId=item=>String(item?.sourceId??'');
const rows=input=>Array.isArray(input)?input:[];
const bucketClass=input=>String(input??'unavailable').toLowerCase().replaceAll('_','-');

function preview(observation){
  const asset=observation?.value?.preview??observation?.value?.asset??null,url=String(asset?.url??'');
  if(asset?.admitted===true&&/^(?:\/backend\/|\/assets\/|\.\/)/.test(url))return `<img src="${esc(url)}" alt="${esc(asset.alt??'Admitted evidence preview')}">`;
  return `<div class="evidence-preview-unavailable">${icon('evidence',20)}<span>Preview unavailable</span><small>No admitted preview asset</small></div>`;
}

function sourceDisplay(source,family){
  const raw=String(source?.label??source?.name??source?.id??''),looksInternal=/^(?:system|agent|service|source)[.:_-]|[.:_-](?:agent|service)[.:_-]/i.test(raw)||/^[a-z0-9_.:-]{24,}$/i.test(raw);
  if(!looksInternal&&raw)return raw;
  return family?.label??operatorText(family?.familyClass,{missing:'Canonical evidence source'});
}

function bucketCard(bucket,items,selected){
  const first=items[0]??null,isSelected=items.some(item=>evidenceId(item)===evidenceId(selected));
  return `<button class="evidence-bucket-card evidence-bucket-card--${bucketClass(bucket)} ${isSelected?'is-selected':''}" ${first?`data-action="select-evidence:${esc(evidenceId(first))}"`:'disabled'} aria-pressed="${isSelected}"><i aria-hidden="true"></i><span>${esc(operatorText(bucket))}</span><strong>${items.length}</strong></button>`;
}

function recentCard(observation,{sources,sourceFamilies,evidence}){
  const source=sources.find(item=>item.id===sourceId(observation))??null,family=sourceFamilies.find(item=>item.id===source?.familyId)??null,statement=evidence.find(item=>observationId(item)===observation.id)??null;
  return `<article class="recent-evidence-card recent-evidence-card--${bucketClass(statement?.bucket??statement?.stance)}"><div class="recent-evidence-card__copy"><i aria-hidden="true"></i><time>${esc(timeLabel(observation.observedAt))}</time><strong>${esc(objectTitle(statement,sourceDisplay(source,family)))}</strong><small>${esc(sourceDisplay(source,family))}</small>${technicalDisclosure('Provenance',[['Observation ID',observation.id],['Raw source ID',observation.sourceId],['Raw source label',source?.label],['Canonical stance',statement?.stance],['Preview state',observation?.value?.previewState]])}</div>${preview(observation)}</article>`;
}

export function renderEvidenceDebt(state){
  const intelligence=incidentEnvelope(state,'intelligence'),debtSource=incidentEnvelope(state,'debt'),incident=selectedIncident(state),graph=evidenceGraph(intelligence),qualification=evidenceQualification(intelligence),bucketProjection=value(intelligence,'evidenceBuckets'),sourceFamilies=rows(graph?.sourceFamilies),sources=rows(graph?.sources),observations=rows(graph?.observations),evidence=rows(graph?.evidence),lineages=rows(graph?.lineages),bucketRows=Object.fromEntries(bucketNames.map(name=>[name,rows(bucketProjection?.buckets?.[name])])),allBucketEvidence=bucketNames.flatMap(name=>bucketRows[name]),selected=allBucketEvidence.find(item=>evidenceId(item)===state.selectedEvidenceId)??bucketRows.CONTRADICTORY[0]??allBucketEvidence[0]??null,selectedObservation=observations.find(item=>item.id===observationId(selected))??null,selectedSource=sources.find(item=>item.id===sourceId(selectedObservation))??null,selectedFamily=sourceFamilies.find(item=>item.id===selectedSource?.familyId)??null,selectedLineage=lineages.find(item=>item.observationId===selectedObservation?.id)??null,debtContract=value(debtSource,'derivedEvidenceDebt'),debt=evidenceDebtItems(debtContract),recommendations=rows(value(debtSource,'acquisitionRecommendations')),coordinate=incidentCoordinate(incident),metadata=incident?.incident?.metadata??{},status=incidentAssessment(incident);
  const displaySources=sources.map(source=>({...source,label:sourceDisplay(source,sourceFamilies.find(family=>family.id===source.familyId))})),graphPayload=encodeURIComponent(JSON.stringify({incident:{id:incident?.incident?.id??incident?.id??null,label:incident?incidentLabel(incident):null,status},sourceFamilies,sources:displaySources,observations,evidence,lineages,selectedEvidenceId:evidenceId(selected)}));
  const selectedDetails=technicalDisclosure('View provenance',[
    ['Evidence ID',evidenceId(selected)],['Observation ID',selectedObservation?.id],['Source ID',selectedSource?.id],['Source family ID',selectedFamily?.id],['Root observation',selectedLineage?.rootObservationIds?.join(', ')],['Canonical stance',selected?.stance],['Canonical bucket',selected?.bucket]
  ]);
  const evidenceCount=graph?evidence.length:'Unavailable',qualificationCount=key=>qualification&&Array.isArray(qualification[key])?qualification[key].length:'Unavailable',debtCount=debtContract?debt.length:'Unavailable',recentRecords=observations.slice(0,7);
  const body=`<section class="route-context evidence-context"><div class="evidence-incident"><i aria-hidden="true">${icon('flame',18)}</i><strong>${esc(incident?incidentLabel(incident):'No incident selected')}</strong>${humanState(status)}</div><dl class="evidence-incident-facts"><div><dt>Area</dt><dd>${esc(measured(metadata.areaHa,{suffix:' ha'}))}</dd></div><div><dt>Location</dt><dd>${esc(coordinate?`${Math.abs(coordinate[1]).toFixed(4)} ${coordinate[1]<0?'S':'N'}, ${Math.abs(coordinate[0]).toFixed(4)} ${coordinate[0]<0?'W':'E'}`:'Unavailable')}</dd></div><div><dt>Record</dt><dd>${esc(technicalIdLabel(incident?.incident?.id??incident?.id,{prefix:'Incident'}))}</dd></div></dl><details class="evidence-settings"><summary>${icon('settings',15)}<span>Evidence settings</span>${icon('chevron',13)}</summary><div><strong>${esc(operatorText(qualification?.state))}</strong><small>${esc(generatedAt(intelligence))}</small></div></details></section>
  <div class="evidence-workspace">
    <aside class="evidence-bucket-rail" data-vqa="evidence.buckets" aria-label="Evidence buckets"><header><span>Evidence buckets</span></header><div class="evidence-bucket-cards">${bucketNames.map(bucket=>bucketCard(bucket,bucketRows[bucket],selected)).join('')}</div></aside>
    <section class="evidence-graph-surface" data-vqa="evidence.graph"><header data-vqa="evidence.graph.header"><span><strong>Evidence graph</strong><small>Evidence grouped by admitted source and relationship</small></span><em>${esc(evidenceCount)} statements · ${esc(graph?observations.length:'Unavailable')} observations</em></header>${graph&&evidence.length?`<div class="evidence-canvas-wrap" data-vqa="evidence.graph.canvas"><canvas class="evidence-graph-canvas" data-evidence-graph="${esc(graphPayload)}" data-graph-zoom="1" tabindex="0" role="img" aria-label="Evidence relationship graph. Use the graph controls or select an evidence node to inspect provenance."></canvas><div class="evidence-graph-tools" data-vqa="evidence.graph.controls"><button type="button" data-action="evidence-graph-provenance" aria-label="Open selected evidence provenance">${icon('external',15)}</button><button type="button" data-action="evidence-graph-zoom-in" aria-label="Zoom evidence graph in">${icon('plus',15)}</button><button type="button" data-action="evidence-graph-zoom-out" aria-label="Zoom evidence graph out">${icon('minus',15)}</button><button type="button" data-action="evidence-graph-fit" aria-label="Fit evidence graph">${icon('detect',15)}</button></div><div class="evidence-graph-legend" data-vqa="evidence.graph.legend"><span><i class="legend-support"></i>Supporting</span><span><i class="legend-review"></i>Under review</span><span><i class="legend-contradiction"></i>Contradictory</span></div></div>`:`<div class="evidence-graph-unavailable"><strong>Evidence graph unavailable</strong><p>No admitted evidence or observation objects were returned.</p></div>`}</section>
    <aside class="evidence-inspector" data-vqa="evidence.qualification"><header><span>Evidence qualification</span>${humanState(qualification?.state)}</header><section class="evidence-qualification-lead"><span>Canonical qualification</span><strong>${esc(operatorText(qualification?.state))}</strong><small>${qualification?.requirementsSatisfied===true?'Backend requirements satisfied':qualification?.requirementsSatisfied===false?'Backend requirements not satisfied':'Requirements unavailable'}</small><i class="qualification-rule qualification-rule--${qualification?.requirementsSatisfied===true?'ready':qualification?.requirementsSatisfied===false?'blocked':'unavailable'}"></i></section><section class="qualification-summary"><article><span>Independent families</span><strong>${qualificationCount('independentFamilies')}</strong></article><article><span>Qualifying evidence</span><strong>${qualificationCount('qualifyingEvidence')}</strong></article><article><span>Contradictions</span><strong>${qualificationCount('contradictions')}</strong></article><article><span>Evidence debt</span><strong>${debtCount}</strong></article></section><section class="source-qualification"><h3>Source status</h3>${sources.slice(0,5).map(item=>{const family=sourceFamilies.find(row=>row.id===item.familyId);return`<article class="source-health-row"><i aria-hidden="true"></i><strong>${esc(sourceDisplay(item,family))}</strong>${humanState(item.status??'UNAVAILABLE')}<small>${esc(family?.label??'Source family unavailable')}</small></article>`;}).join('')||'<p>Source qualification unavailable.</p>'}</section><section class="evidence-conflict"><span><strong>Conflict indicator</strong><small>${esc(qualificationCount('contradictions'))} canonical contradiction${qualificationCount('contradictions')===1?'':'s'}</small></span>${humanState(qualification?.contradictions?.length?'CONTRADICTORY':'READY')}</section><section class="selected-evidence-summary"><span>Selected evidence</span>${selected?`<strong>${esc(objectTitle(selected,'Evidence statement'))}</strong><p>${esc(selected.qualification?.reason??selected.rationale??'No qualification explanation was returned.')}</p><small>${esc(sourceDisplay(selectedSource,selectedFamily))}</small>${selectedDetails}`:'<strong>No evidence selected</strong><p>No inspectable evidence statement was returned.</p>'}</section><footer><span>Acquisition</span><strong>${esc(recommendations.length?`${recommendations.length} governed recommendation${recommendations.length===1?'':'s'}`:operatorText(debtContract?.needs?.[0]?.ranking?.state,{missing:'Unavailable'}))}</strong></footer></aside>
  </div>
  <section class="recent-evidence" data-vqa="evidence.recent"><header><span><strong>Recent evidence</strong><small>Latest admitted source material</small></span><em>Admitted sources only</em></header><div>${recentRecords.length?recentRecords.map(item=>recentCard(item,{sources,sourceFamilies,evidence})).join(''):'<article class="recent-evidence-empty"><strong>No admitted media records</strong><p>The canonical graph has no recent observation media to display.</p></article>'}</div></section>`;
  return shell('evidence',body,{pageClass:'phase-b-route locked-route'});
}
