import { shell, esc } from '../components.js?v=2.1.0';
import { canonicalMap, emptyTruthState, humanState, objectMeta, objectTitle, technicalDisclosure } from '../canonicalComponents.js?v=3.0.0';
import { availableCount, canonicalIncidents, envelope, incidentAssessment, incidentChangedAt, incidentCoordinate, incidentEnvelope, incidentId, incidentLabel, incidentLocation, operatorText, sectionAvailable, timeLabel, value } from '../canonicalViewModel.js?v=3.0.0';
import { icon } from '../icons.js?v=2.1.0';
import { freshnessState, vigiaSelect, vigiaStateLabel } from '../operatorPrimitives.js?v=3.2.0';
import { incidentQuicklook } from '../executiveComponents.js?v=3.0.0';
import { globalSentinelRail, strategicCrisisSystem } from '../crisisOperatingSystem.js?v=4.2.0';

const rows=input=>Array.isArray(input)?input:[];
const explicitText=value=>typeof value==='string'&&value.trim()&&!/^[-+]?\d+(?:\.\d+)?(?:,|$)/.test(value.trim())?value.trim():'';
const regionOf=item=>explicitText(item?.incident?.region)||explicitText(item?.incident?.jurisdiction)||explicitText(item?.incident?.location?.region)||explicitText(item?.region)||explicitText(item?._authorizedRegion)||'Authorized scope';
const typeOf=item=>String(item?.incident?.type??item?.incident?.incidentType??item?.type??'').trim();
const priorityOf=item=>{const raw=item?.incident?.priority??item?.priority??item?.severity;if(raw&&typeof raw==='object'){const value=raw.band??raw.label??raw.level??raw.rank;return value===null||value===undefined?'':typeof value==='number'?`P${value}`:String(value).toUpperCase();}return raw===null||raw===undefined?'':String(raw).toUpperCase();};
const statusOf=item=>String(item?.operationalTruth?.classification??item?.incident?.operationalTruth?.classification??item?.incident?.classification??item?.classification??item?.incident?.lifecycleState??item?.incident?.status??item?.evaluation?.state??item?.state??'NOT_CLASSIFIED').toUpperCase();
const changedOf=item=>item?.operationalTruth?.lastObservedAt??item?.incident?.operationalTruth?.lastObservedAt??incidentChangedAt(item)??item?.updatedAt??item?.incident?.updatedAt;

const facetLabel=value=>typeof value==='string'&&/^[a-z][a-z\s-]*$/.test(value)?value.replace(/^./,letter=>letter.toUpperCase()):operatorText(value);
function options(values,allLabel){const counts=new Map();for(const value of values.filter(Boolean))counts.set(value,(counts.get(value)??0)+1);return[{value:'ALL',label:allLabel,count:values.length},...[...counts.entries()].sort(([a],[b])=>String(a).localeCompare(String(b))).map(([value,count])=>({value,label:facetLabel(value),count}))];}

function filtered(state,items){
  const now=Math.max(...items.map(item=>Date.parse(changedOf(item)??'')).filter(Number.isFinite),Date.now()),hours={H24:24,H72:72,H168:168}[state.globalTime];
  return items.filter(item=>(state.globalRegion==='ALL'||regionOf(item)===state.globalRegion)&&(state.globalType==='ALL'||typeOf(item)===state.globalType)&&(state.globalPriority==='ALL'||/^CONTEXT$/i.test(state.globalPriority)||priorityOf(item)===state.globalPriority)&&(state.globalStatus==='ALL'||statusOf(item)===state.globalStatus)&&(!hours||Number.isFinite(Date.parse(changedOf(item)??''))&&now-Date.parse(changedOf(item))<=hours*3600000));
}

function filters(state,items){
  const regions=items.map(regionOf),types=items.map(typeOf),priorities=items.map(priorityOf).filter(value=>value&&!/^CONTEXT$/i.test(value)),statuses=items.map(statusOf),hasTime=items.some(item=>Number.isFinite(Date.parse(changedOf(item)??''))),active=[['region',state.globalRegion,facetLabel(state.globalRegion)],['type',state.globalType,facetLabel(state.globalType)],['priority',state.globalPriority,facetLabel(state.globalPriority)],['status',state.globalStatus,facetLabel(state.globalStatus)],['time',state.globalTime,{H24:'Last 24 hours',H72:'Last 72 hours',H168:'Last 7 days'}[state.globalTime]]].filter(([,value])=>value&&value!=='ALL');
  return`<section class="global-filter-panel panel-surface" data-vqa="global.filters"><div class="global-filters">${vigiaSelect({id:'global-region',label:'Region',value:state.globalRegion,options:options(regions,'All regions'),iconName:'globe',openId:state.openSelectId})}${vigiaSelect({id:'global-type',label:'Incident type',value:state.globalType,options:options(types,'All incident types'),iconName:'flame',disabled:!types.some(Boolean),disabledReason:'Incident type facets are unavailable by the current operational view.',openId:state.openSelectId})}${vigiaSelect({id:'global-priority',label:'Priority',value:priorities.includes(state.globalPriority)?state.globalPriority:'ALL',options:options(priorities,'All assessed priorities'),iconName:'warning',disabled:!priorities.length,disabledReason:'Priority not assessed for this scope.',openId:state.openSelectId})}${vigiaSelect({id:'global-status',label:'Status',value:state.globalStatus,options:options(statuses,'All statuses'),iconName:'filter',openId:state.openSelectId})}${vigiaSelect({id:'global-time',label:'Time window',value:state.globalTime,options:[{value:'ALL',label:'All available time'},{value:'H24',label:'Last 24 hours'},{value:'H72',label:'Last 72 hours'},{value:'H168',label:'Last 7 days'}],iconName:'clock',disabled:!hasTime,disabledReason:'No incident update times are available for time-window filtering.',openId:state.openSelectId,className:'global-time-filter'})}</div><div class="global-active-filters" aria-live="polite">${active.length?active.map(([key,,label])=>`<button data-action="clear-global-filter:${key}">${esc(label)} ${icon('close',12)}</button>`).join(''):'<span>All authorized incidents shown</span>'}${active.length?'<button class="text-button" data-action="clear-global-filters">Clear all</button>':''}</div></section>`;
}

function stateLegend(items){
  const states=new Map();for(const item of items){const state=statusOf(item);states.set(state,(states.get(state)??0)+1);}
  return`<div class="global-map-legend">${[...states.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([state,count])=>`<span>${humanState(state)}<strong>${count}</strong></span>`).join('')||'<span>No incidents in current filter</span>'}</div>`;
}

function regionalSummary(items){
  const groups=new Map();for(const item of items){const region=regionOf(item),group=groups.get(region)??{count:0,priority:0};group.count++;if(/CRITICAL|HIGH|P1|P2/.test(priorityOf(item)))group.priority++;groups.set(region,group);}
  const regions=[...groups.entries()].sort((a,b)=>b[1].count-a[1].count);
  return`<section class="global-rail-card panel-surface"><header><div><h2>Regional Summary</h2><p>Authorized records</p></div></header>${regions.length?`<div class="regional-summary">${regions.slice(0,8).map(([region,item])=>`<button data-action="global-region-focus:${encodeURIComponent(region)}"><b aria-hidden="true">${icon('globe',14)}</b><strong>${esc(region)}</strong><span>${item.count} records</span><em>${item.priority?`${item.priority} high priority`:'No reported high priority'}</em></button>`).join('')}</div>`:emptyTruthState('No regional inventory','No incident remains in the current filter.')}</section>`;
}

function strategicSummary(items,gap){
  const freshness=new Map(),verification=new Map();for(const item of items){const fresh=String(item?.operationalTruth?.axes?.freshness?.state??'NOT MEASURED'),verified=String(item?.operationalTruth?.axes?.verification?.state??'NOT MEASURED');freshness.set(fresh,(freshness.get(fresh)??0)+1);verification.set(verified,(verification.get(verified)??0)+1);}
  const providers=rows(gap?.providers?.inventory),degraded=providers.filter(item=>!['CURRENT','READY','ACTIVE'].includes(String(item.state))),families=gap?.sourceCoverage?.percent,providerState=!providers.length?'NOT_MEASURED':degraded.length?'DEGRADED':'READY';
  const groups=(title,values)=>`<span><small>${title}</small><strong>${[...values.entries()].map(([key,count])=>`${operatorText(key)} ${count}`).join(' · ')||'Not measured'}</strong></span>`;
  return`<section class="global-rail-card global-strategic panel-surface"><header><div><h2>Operational scope</h2><p>Lifecycle, freshness, verification and provider degradation</p></div>${vigiaStateLabel(providerState,{compact:true})}</header><div>${groups('Freshness',freshness)}${groups('Verification',verification)}<span><small>Source-family coverage</small><strong>${families===null||families===undefined?'Not measured':`${families}% associated`}</strong></span><span><small>Provider degradation</small><strong>${!providers.length?'Provider inventory not reported':degraded.length?`${degraded.length} · ${degraded.slice(0,2).map(item=>item.provider).join(' · ')}`:'No degraded provider in the reported inventory'}</strong></span></div></section>`;
}

function sourceHealth(health,available){
  const sources=rows(health?.sources),counts=new Map();for(const item of sources){const state=String(item?.status??item?.state??'UNKNOWN').toUpperCase();counts.set(state,(counts.get(state)??0)+1);}const total=sources.length,latest=sources.map(item=>item?.lastCheckedAt??item?.observedAt??item?.updatedAt??item?.lastSuccessAt).filter(value=>Number.isFinite(Date.parse(value))).sort((a,b)=>Date.parse(b)-Date.parse(a))[0]??health?.generatedAt??null;
  return`<section class="global-rail-card panel-surface"><header><div><h2>Source availability</h2><p>${esc(latest?`Last checked ${timeLabel(latest)}`:'Backend source registry')}</p></div><strong>${available?total:'Unavailable'}</strong></header>${sources.length?`<div class="source-health-bars">${[...counts.entries()].sort((a,b)=>b[1]-a[1]).map(([state,count])=>{const tone=/READY|HEALTHY|CURRENT/.test(state)?'green':/FAILED|CRITICAL|UNHEALTHY/.test(state)?'critical':/DEGRADED|STALE/.test(state)?'warning':'info';return`<article><span><i class="report-key report-key--${tone}"></i>${esc(operatorText(state))}</span><div><i class="source-health-fill--${tone}" style="width:${Math.round(count/total*100)}%"></i></div><strong>${count}</strong></article>`;}).join('')}</div><details class="source-health-details"><summary>Source freshness</summary>${sources.slice(0,8).map(item=>{const checked=item?.lastCheckedAt??item?.observedAt??item?.updatedAt??item?.lastSuccessAt;return`<span><strong>${esc(operatorText(item?.label??item?.name??item?.sourceFamily??item?.provider,{missing:'Canonical source'}))}</strong><small>${esc(checked?timeLabel(checked):'Check time not reported')}</small></span>`;}).join('')}</details>`:emptyTruthState(available?'No sources returned':'Source health unavailable',available?'The source registry returned no rows.':'The canonical source-health projection is unavailable.')}</section>`;
}

function recentEvents(events,available,lastChecked){
  return`<section class="global-rail-card global-events ${events.length?'':'is-empty'} panel-surface"><header><div><h2>Recent Material Events</h2><p>Canonical incident, source, and official-alert changes</p></div><strong>${available?events.length:'Unavailable'}</strong></header>${events.length?`<ol>${events.slice(0,7).map(item=>`<li><i>${icon('warning',14)}</i><span><strong>${esc(operatorText(item?.summary??item?.type??objectTitle(item,'Material event')))}</strong><small>${esc(operatorText(item?.source??item?.severity??objectMeta(item)))}</small></span><time datetime="${esc(item?.clocks?.occurredAt??item?.at??'')}">${esc(timeLabel(item?.clocks?.occurredAt??item?.at))}</time></li>`).join('')}</ol>`:emptyTruthState(available?'No recent material events':'Material-event feed unavailable',available?'No canonical material change was returned for the active filter.':'The canonical material-event projection is unavailable.')}<footer class="global-events__coverage"><span><small>Last checked</small><strong>${esc(lastChecked?timeLabel(lastChecked):'Not reported')}</strong></span><span><small>Source coverage</small><strong>${esc(available?'Authorized canonical scope':'Unavailable')}</strong></span></footer></section>`;
}

function scopedEvents(events,incidents){const ids=new Set(incidents.map(incidentId).flatMap(id=>[id,id.replace(/^incident:/,'')]));return events.filter(event=>{const keys=[event?.incidentId,event?.entityId,...rows(event?.correlationKeys)].filter(Boolean).map(String);return!keys.length||keys.some(key=>ids.has(key)||ids.has(key.replace(/^incident:/,'')));});}

function resultSummary(items,generatedAt,geolocatedCount,renderedCount){const recent=[...items].sort((a,b)=>Date.parse(changedOf(b)??0)-Date.parse(changedOf(a)??0)),verified=items.filter(item=>statusOf(item)==='VERIFIED_CURRENT'),candidates=items.filter(item=>statusOf(item)==='DETECTION_CANDIDATE'),revalidation=items.filter(item=>statusOf(item)==='NEEDS_REVALIDATION');return`<section class="global-rail-card global-results panel-surface" data-vqa="global.results" data-global-mappable-count="${geolocatedCount}" data-global-rendered-count="${renderedCount}"><header><div><h2>${items.length} matching records</h2><p>${geolocatedCount} have recorded coordinates · ${renderedCount} rendered</p></div><button class="text-button" data-action="fit-map-results" ${renderedCount?'':'disabled'}>Fit ${renderedCount} rendered</button></header><div class="global-result-signals"><span><strong>${verified.length}</strong><small>Verified current</small></span><span><strong>${candidates.length}</strong><small>Detection candidates</small></span><span><strong>${revalidation.length}</strong><small>Need revalidation</small></span></div><ol>${recent.slice(0,3).map(item=>`<li><button data-action="inspect-incident:${esc(incidentId(item))}"><i aria-hidden="true">${icon('flame',13)}</i><span><strong>${esc(incidentLabel(item))}</strong><small>${esc(incidentLocation(item))}</small></span>${vigiaStateLabel(statusOf(item),{compact:true})}</button></li>`).join('')||'<li class="global-results__empty">No incident remains in the active filter.</li>'}</ol></section>`;}

export function renderGlobalAwareness(state){
  const source=envelope(state,'globalAwareness'),authorizedScope=value(source,'authorizedScope')??{},truth=value(source,'operationalTruth')??{},gap=value(source,'gapClosure')??{},crisisAutopilot=value(source,'crisisAutopilot')??{},authorizedRegion=operatorText(authorizedScope.region,{missing:'Authorized scope'}),all=canonicalIncidents(source).map(item=>({...item,_authorizedRegion:authorizedRegion})),scoped=filtered(state,all),count=availableCount(source,'situationalAwareness',all),scene=value(source,'mapScene'),scenePoints=rows(scene?.layers?.incidentPoints?.value),scopedIds=new Set(scoped.map(incidentId)),geolocatedCount=scoped.filter(incidentCoordinate).length,renderedCount=scenePoints.filter(item=>scopedIds.has(String(item?.incidentId??incidentId(item)))&&Array.isArray(item?.coordinate)&&item.coordinate.length===2&&item.coordinate.every(Number.isFinite)).length,operationalSubset=Number(truth.governedOperationalSubsetCount??0),geolocation=gap.geolocation??truth.geolocation??{},geolocationSummary=geolocation.denominator?`${Number(geolocation.usable??geolocation.geolocated??0)}/${Number(geolocation.denominator)} geolocated (${geolocation.percent}%)`:'geolocation denominator is not available',excluded=truth.excludedFromOperationalSubset??{},health=value(source,'sourceHealth')??{},cap=scopedEvents(rows(value(source,'capLifecycle')),scoped),material=scopedEvents(rows(value(source,'materialEvents')?.events),scoped),events=[...new Map([...material,...cap].map(item=>[item.eventId??item.id??`${item.type}:${item.at}`,item])).values()].sort((a,b)=>Date.parse(b?.at??b?.clocks?.occurredAt??0)-Date.parse(a?.at??a?.clocks?.occurredAt??0)),selected=scoped.find(item=>incidentId(item)===String(state.globalSelectedIncidentId??''))??null,detailSource=incidentEnvelope(state,'detail'),detail=value(detailSource,'canonicalIncident'),work=rows(value(detailSource,'governedWork'));
  // Display viewport from the existing Portugal-mainland policy extent; never an incident geometry.
  const bounds=/Portugal.*mainland/i.test(authorizedRegion)?{west:-9.53,south:36.84,east:-6.38,north:42.29}:scene?.bounds,nationalScene=scene&&bounds?{...scene,bounds,camera:{...scene.camera,center:[(bounds.west+bounds.east)/2,(bounds.south+bounds.north)/2],bbox:bounds,zoom:6}}:scene;
  const body=`<section class="global-route final-white-route">
    ${filters(state,all)}
    <div class="global-workspace">
      <section class="global-map panel-surface" data-vqa="global.map"><header><div><h2>Portugal regional view</h2><p>${sectionAvailable(source,'situationalAwareness')?`${scoped.length} filter matches · ${renderedCount} mapped`:'Incident data unavailable'} · ${esc(authorizedRegion)}</p></div><div class="global-map__header-actions"><strong data-map-health>Retained map · refreshing</strong><button class="text-button" data-action="fit-map-results" ${renderedCount?'':'disabled'}>Fit ${renderedCount} rendered</button><button class="text-button" data-action="map-reset-world">Reset Portugal view</button><button class="text-button" data-action="national-map-fullscreen">Full-screen map</button></div></header><div class="global-map__canvas">${sectionAvailable(source,'situationalAwareness')?canonicalMap({state,incidents:scoped,selected,thermal:false,label:'National awareness incident map',mapScene:nationalScene,scope:'GLOBAL',vqa:'global.map-canvas'}):emptyTruthState('Global incident view unavailable','The global situation view is unavailable; no world inventory is synthesized.')}</div>${stateLegend(scoped)}</section>
      <aside class="global-rail ${events.length?'':'global-rail--events-empty'}">${state.quicklookRoute==='global-awareness'?incidentQuicklook({incident:selected,detail,work,scene,route:'global-awareness'}):resultSummary(scoped,source?.generatedAt,geolocatedCount,renderedCount)}${regionalSummary(scoped)}${strategicSummary(scoped,gap)}${sourceHealth(health,sectionAvailable(source,'sourceHealth'))}<details class="technical-details"><summary>Recent source and incident changes</summary>${recentEvents(events,sectionAvailable(source,'materialEvents')||sectionAvailable(source,'capLifecycle'),source?.generatedAt)}</details></aside>
    </div>
    ${technicalDisclosure('National view technical details',[['Projection generated',source?.generatedAt],['Canonical incidents',count],['Governed operational subset',operationalSubset],['Operational-subset definition',truth?.policy?.operationalSubsetDefinition],['Candidates missing governed location',excluded.candidateMissingGovernedLocation],['Filtered incidents',scoped.length],['Map scene state',source?.data?.mapScene?.state??'Explicit incident-inventory map'],['Source health state',source?.data?.sourceHealth?.state],['Material event state',source?.data?.materialEvents?.state],['CAP lifecycle state',source?.data?.capLifecycle?.state]])}
  </section>`;
  return shell('global-awareness',body,{pageClass:'final-white-route-page'});
}
