import { referenceMapUnavailable } from '../referenceMapUnavailable.js';
import { shell, esc } from '../components.js?v=2.1.0';
import { canonicalMap, emptyTruthState, technicalDisclosure } from '../canonicalComponents.js?v=3.0.0';
import { canonicalIncidents, envelope, evidenceDebtItems, incidentAssessment, incidentChangedAt, incidentCoordinate, incidentEnvelope, incidentId, incidentLabel, incidentLocation, incidentNextDecision, operatorText, sectionAvailable, selectedIncident, timeLabel, value } from '../canonicalViewModel.js?v=3.0.0';
import { icon } from '../icons.js?v=2.1.0';
import { freshnessState, relativeTimeLabel, vigiaStateLabel } from '../operatorPrimitives.js?v=3.2.0';
import { executiveDisclosure, executiveSection, incidentContextSwitcher, incidentQuicklook } from '../executiveComponents.js?v=3.1.0';
import { crisisContextSystem, livingTwinStrip, responseCapabilityPanel } from '../crisisOperatingSystem.js?v=4.1.0';

const rows=value=>Array.isArray(value)?value:[];
const sentence=(...values)=>operatorText(values.find(value=>value!==null&&value!==undefined&&String(value).trim())??null,{missing:'Not reported'});
const title=(item,fallback)=>sentence(item?.title,item?.label,item?.name,item?.whatIsMissing,item?.missingQuantity,item?.quantity_question,item?.reason,fallback);
const times=(items)=>items.map(item=>item?.observedAt??item?.updatedAt??item?.at??item?.changedAt).filter(value=>Number.isFinite(Date.parse(value))).sort((a,b)=>Date.parse(a)-Date.parse(b));

function meaningRow(label,titleText,body='',tone=''){
  return`<article class="incident-meaning-row ${tone?`incident-meaning-row--${tone}`:''}"><span>${esc(label)}</span><div><strong>${esc(titleText)}</strong>${body?`<p>${esc(body)}</p>`:''}</div></article>`;
}

function layerSummary(scene){
  const specs=[['geometry','Geometry'],['roads','Road access'],['communities','Communities'],['terrain','Terrain'],['smoke','Smoke'],['weather','Weather']];
  return`<div class="incident-layer-summary">${specs.map(([key,label])=>{const layer=scene?.layers?.[key]??{},items=rows(layer.value),state=layer.state??(items.length?'AVAILABLE':'UNAVAILABLE'),detail=items.length?`${items.length} governed record${items.length===1?'':'s'}`:sentence(layer.reason,'No governed record available');return`<article><span><strong>${esc(label)}</strong><small>${esc(detail)}</small></span>${vigiaStateLabel(state,{compact:true})}</article>`;}).join('')}</div>`;
}

function supportTable(assets){
  const supported=assets.filter(item=>/HOSPITAL|FIRE|STATION|EMS|CIVIL|SHELTER|WATER|AIR_SUPPORT|POLICE/i.test([item?.kind,item?.type,item?.category,item?.properties?.kind,item?.properties?.type].filter(Boolean).join(' ')));
  if(!supported.length)return`<div class="incident-support-empty"><strong>No governed critical-support facility is associated with this scene.</strong><p>VIGIA does not infer availability, travel time, or capability from a map label. Review response planning for current collection work.</p></div>`;
  return`<div class="incident-support-table" role="table" aria-label="Nearby critical support"><div class="incident-support-table__head" role="row"><span role="columnheader">Facility</span><span role="columnheader">Type</span><span role="columnheader">Distance</span><span role="columnheader">Travel time</span><span role="columnheader">Status</span></div>${supported.slice(0,12).map(item=>{const data=item?.properties??item,name=sentence(data.name,data.label,item.name,item.label,'Unnamed governed facility'),kind=sentence(data.kind,data.type,item.kind,item.type,'Facility'),distance=Number.isFinite(Number(data.distanceKm))?`${Number(data.distanceKm).toFixed(1)} km`:'Not measured',travel=Number.isFinite(Number(data.travelTimeMinutes))?`${Math.round(Number(data.travelTimeMinutes))} min`:'Not measured',status=data.status??data.state??data.freshness?.state??'NOT_MEASURED';return`<details class="incident-support-row"><summary role="row"><strong role="cell">${esc(name)}</strong><span role="cell">${esc(operatorText(kind))}</span><span role="cell">${esc(distance)}</span><span role="cell">${esc(travel)}</span><span role="cell">${vigiaStateLabel(status,{compact:true})}</span></summary><p>Only governed proximity and capability fields are shown. Missing travel or capacity data remains unmeasured.</p></details>`;}).join('')}</div>`;
}

function resolutionPanel(work,projectionAt){
  const item=work[0]??null,lifecycle=item?.lifecycle??{};
  if(!item)return`<section class="incident-resolution panel-surface"><header><div><h2>Active resolution</h2><p>Source-resolution activity for this incident</p></div>${vigiaStateLabel('MONITORING',{compact:true})}</header><div class="incident-resolution__empty"><strong>Monitoring for a qualifying source change</strong><p>No active resolution item is currently open. This is not treated as confirmation or completion.</p></div></section>`;
  const last=lifecycle.lastCheckedAt??projectionAt,next=lifecycle.nextCheckAt;
  return`<section class="incident-resolution panel-surface"><header><div><h2>Active resolution</h2><p>What VIGIA is doing now</p></div>${vigiaStateLabel(item.state??item.status,{compact:true})}</header><div class="incident-resolution__body"><strong>${esc(title(item,'Monitoring independent confirmation'))}</strong><p>${esc(sentence(item?.decisionImpact,item?.whyItMatters,item?.reason,'Independent confirmation can change the current decision.'))}</p><dl><div><dt>Sources being checked</dt><dd>${esc(sentence(lifecycle.sourceDependency,item?.sourceFamily,'Source selection pending'))}</dd></div><div><dt>Owner</dt><dd>${esc(sentence(lifecycle.owner?.label,item?.ownerClass,'VIGIA monitoring'))}</dd></div><div><dt>Last checked</dt><dd>${esc(last?`${timeLabel(last)} · ${relativeTimeLabel(last)}`:'No collection attempt recorded')}</dd></div><div><dt>Next check</dt><dd>${esc(next?timeLabel(next):sentence(lifecycle.nextCheckPolicy,'On the next qualifying source update'))}</dd></div><div><dt>Escalation</dt><dd>${esc(sentence(lifecycle.escalationTrigger,'No escalation condition declared'))}</dd></div></dl></div></section>`;
}

export function renderIncidentDetail(state){
  const source=incidentEnvelope(state,'detail'),selected=selectedIncident(state),inventory=canonicalIncidents(envelope(state,'incidents'));
  if(!selected)return shell('incident-detail',emptyTruthState('No incident selected','Open Incidents and select an incident.','go-incidents'),{pageClass:'final-white-route-page',contextualHeader:true});
  const incident=value(source,'canonicalIncident')??selected,truth=value(source,'operationalTruth')??incident?.operationalTruth??{},scene=value(source,'mapScene'),mapAvailable=sectionAvailable(source,'mapScene')&&Boolean(scene),returnedTimeline=rows(value(source,'operationalTimeline')),timeline=returnedTimeline.length?returnedTimeline:rows(incident?.transitions),work=rows(value(source,'governedWork')),graph=incident?.evidenceGraph??{},observations=[...rows(scene?.layers?.observations?.value),...rows(scene?.layers?.thermalSupport?.value),...rows(graph?.observations)],observationTimes=times(observations),lastObserved=truth.lastObservedAt??observationTimes.at(-1)??incidentChangedAt(incident),freshState=truth?.axes?.freshness?.state,fresh=freshnessState(lastObserved,Date.now()),sources=new Set([...rows(graph?.sources),...rows(graph?.evidence),...rows(graph?.observations)].map(item=>sentence(item?.sourceFamily,item?.provider,item?.platform,item?.instrument,item?.source)).filter(value=>value!=='Not reported')),material=[...timeline].sort((a,b)=>Date.parse(b?.at??b?.changedAt??0)-Date.parse(a?.at??a?.changedAt??0))[0],unknown=evidenceDebtItems(incident?.evidenceDebt)[0],recordedClaim=sentence(incident?.claim?.proposition,incident?.summary,'No observation statement returned'),statement=truth.classification==='VERIFIED_CURRENT'?sentence(incident?.evaluation?.operatorStatement,recordedClaim):truth.classification==='HISTORICAL_CLOSED'?'Historical incident record; not a current fire.':truth.classification==='NEEDS_REVALIDATION'?'Earlier incident information needs revalidation. Current fire presence is not verified.':truth.classification==='DETECTION_CANDIDATE'?'A candidate observation is recorded. A wildfire is not yet verified.':'The incident classification was not returned. Current fire presence is not verified.',risk=sentence(incident?.risk?.summary,incident?.exposure?.summary,incident?.atRisk,'Exposure assessment is not yet available'),nextRaw=incidentNextDecision(incident),next=nextRaw==='Not provided'?'Decision criteria are not yet available; VIGIA is monitoring the next qualifying source update.':nextRaw,coordinate=incidentCoordinate(incident),assets=rows(scene?.layers?.contextAssets?.value),quicklook=state.quicklookRoute==='incident-detail',crisisAutopilot=value(source,'crisisAutopilot'),crisisPlanning=value(source,'crisisPlanning'),responseCapability=value(source,'responseCapability');
  const mapPanel=`<section class="incident-detail-map panel-surface" data-vqa="detail.map"><header><div><h2>Incident map</h2><p>Observed geography, selected layers, and nearby context</p></div><span data-map-health>Map transport updating</span></header><div class="incident-detail-map__canvas">${mapAvailable?canonicalMap({state,incidents:[incident],selected:incident,thermal:state.mapThermal,label:`${incidentLabel(incident)} current operating picture`,mapScene:scene,scope:'INCIDENT_DETAIL',vqa:'detail.map-canvas'}):referenceMapUnavailable('Incident map',['Location','Observed boundary'])}</div><footer><span><small>Mapped center</small><strong>${esc(coordinate?.map(number=>number.toFixed(4)).join(', ')??'Not reported')}</strong></span><span><small>Nearby context</small><strong>${assets.length?`${assets.length} mapped features`:'Not reported'}</strong></span><button class="text-button" data-action="map-layers">Map layers ${icon('layers',14)}</button></footer></section>`;
  const meaningPanel=`<aside class="incident-meaning-panel panel-surface" data-vqa="detail.assessment"><header><div><small>Incident brief</small><h2>${esc(incidentLabel(incident))}</h2><p>${esc(incidentLocation(incident))}</p></div>${vigiaStateLabel(truth.classification??'NOT_CLASSIFIED',{compact:true})}</header><div class="incident-meaning-list">${meaningRow('Observation',statement,`${mapAvailable?`${observations.length} associated observations`:'Observation inventory unavailable'}`)}${meaningRow('Missing information',unknown?title(unknown,'Independent confirmation required'):'No uncertainty assessment returned.',unknown?sentence(unknown?.decisionImpact,unknown?.whyItMatters,'This may change the next decision.'):'','warning')}${meaningRow('Exposure',risk,assets.length?`${assets.length} mapped context feature${assets.length===1?'':'s'}; impact is not inferred.`:'','critical')}${meaningRow('Latest change',material?title(material,'Assessment updated'):'No newer material update',material?sentence(material?.consequence,material?.reason,material?.summary):'No newer retained material update.','info')}</div><div class="incident-next-action"><small>Priority action</small><strong>${esc(next)}</strong></div></aside>`;
  const situation=executiveSection({id:'incident-situation',eyebrow:'Situation summary',title:'Situation summary',description:'One concise reading of current truth, uncertainty, and source strength.',body:`<div class="incident-situation-copy"><p>${esc(statement)}</p><dl><div><dt>Incident class</dt><dd>${esc(incidentAssessment(incident))}</dd></div><div><dt>Last observation</dt><dd>${esc(lastObserved?`${timeLabel(lastObserved)} · ${relativeTimeLabel(lastObserved)}`:'No governed observation time')}</dd></div><div><dt>Source coverage</dt><dd>${esc(sources.size?`${sources.size} admitted sources`:'No admitted source')}</dd></div><div><dt>Main uncertainty</dt><dd>${esc(unknown?title(unknown,'Independent confirmation required'):'No ranked uncertainty is attached')}</dd></div></dl></div>`});
  const spatial=executiveSection({id:'incident-spatial',eyebrow:'Spatial / access context',title:'Spatial and access context',description:'Related layers are grouped by operational meaning; unavailable context stays quiet.',body:layerSummary(scene)});
  const support=executiveSection({id:'incident-support',eyebrow:'Nearby critical support',title:'Nearby critical support',description:'Governed facilities only. Distance, travel time, and status remain explicit when unmeasured.',aside:`<strong class="executive-section__count">${assets.length} mapped context</strong>`,body:supportTable(assets)});
  const planning=executiveSection({id:'incident-planning',eyebrow:'Response / resource planning',title:'Response and resource planning',description:'The active resolver is visible first; deeper capability and planning records expand on demand.',body:`${resolutionPanel(work,source?.generatedAt)}${executiveDisclosure({title:'Planning context and resource capability',description:'Candidate facilities, resource gaps, route limitations, and planning notes',body:`${crisisContextSystem(crisisPlanning,{compact:true})}${responseCapabilityPanel(responseCapability,{projectionAt:source?.generatedAt})}`})}`});
  const deepDetail=executiveDisclosure({title:'Evidence, timeline, and source detail',description:'Canonical twin axes and technical provenance for audit or deep inspection',count:`${timeline.length} timeline records`,body:`${livingTwinStrip(crisisAutopilot,{projectionAt:source?.generatedAt})}${technicalDisclosure('Technical incident provenance',[['Incident ID',incidentId(incident)],['Projection generated',source?.generatedAt],['Assessment state',incident?.evaluation?.state],['Coordinate',coordinate?.join(', ')]])}`});
  const body=`<section class="incident-detail-route final-white-route">
    ${incidentContextSwitcher({state,incidents:inventory,incident,source})}
    <section class="incident-status-strip panel-surface" aria-label="Incident truth axes"><span><small>Operational class</small>${vigiaStateLabel(truth.classification??'NOT_CLASSIFIED',{compact:true})}</span><span><small>Verification</small>${vigiaStateLabel(truth?.axes?.verification?.state??incidentAssessment(incident),{compact:true})}</span><span><small>Last observation</small><strong>${esc(lastObserved?timeLabel(lastObserved):'Not reported')}</strong></span><span><small>Observation age</small>${vigiaStateLabel(fresh.state,{label:fresh.label,compact:true})}</span><span><small>Source coverage</small><strong>${sources.size?`${sources.size} admitted sources`:'Not reported'}</strong></span></section>

    <div class="incident-command-layout">${quicklook?incidentQuicklook({incident,detail:incident,work,scene,route:'incident-detail'}):meaningPanel}${mapPanel}</div>
    <nav class="incident-workspace-links"><a href="#/intelligence">Check evidence in Intelligence</a><a href="#/operations">Manage work in Operations</a></nav><details class="technical-details"><summary>Mapped surroundings — not verified emergency support</summary><p>Nearby map features do not establish emergency roles, availability or response capacity.</p><ul>${assets.map(item=>`<li>${esc(item.label??item.properties?.name??'Mapped feature')}</li>`).join('')}</ul>${spatial}</details><details class="technical-details"><summary>Recorded claim and source interpretation</summary><p>${esc(recordedClaim)}</p><p>This is the claim being evaluated, not an independent confirmation.</p>${deepDetail}</details>
  </section>`;
  return shell('incident-detail',body,{pageClass:'final-white-route-page',contextualHeader:true});
}
