import { shell, badge, button, esc } from '../components.js?v=2.1.0';
import { icon } from '../icons.js?v=2.1.0';
import { preventionFindings, selectedFinding, openEvidenceNeeds } from '../viewModel.js?v=2.1.0';
import { backendAsset } from '../vigiaApi.js?v=2.1.0';
import { tileMap } from '../map.js?v=2.1.0';
import { formatMeasuredNumber, formatMeasuredPercent } from '../truth.js?v=2.1.0';
import { preventIntelligence } from '../intelligenceView.js?v=2.1.0';

function statusFor(finding,zone){const disposition=String(zone?.workflow?.disposition??'').toLowerCase();if(disposition.includes('measurement_required'))return['Measurement required','measurement'];const raw=String(zone?.state??zone?.status??finding?.reviewSummary?.state??'measurement_required').toLowerCase();if(raw.includes('robust')||raw.includes('accepted'))return['Robust','green'];if(raw.includes('mixed'))return['Mixed','warning'];if(raw.includes('unstable')||raw.includes('reject'))return['Unstable','critical'];return['Measurement required','measurement'];}
function stabilityFor(zone){const raw=String(zone?.claim_state??zone?.state??'unmeasured').toLowerCase().replaceAll('_',' ');return raw.replace(/\b\w/g,letter=>letter.toUpperCase());}
function fmt(value,suffix=''){return formatMeasuredNumber(value,{suffix,missing:'Measurement required'});}
function preview(scene){if(!scene)return{src:'',fallback:''};return{src:backendAsset(scene.imageUrl??''),fallback:''};}
function safeTab(value){return value==='decision'?'decision':'compare';}
function observationIdentity(label,scene){const acquired=scene?.acquiredAt?new Date(scene.acquiredAt).toISOString():'Acquisition time unavailable';return `<span><em>${label}</em><strong>${esc(scene?.id??'Observation ID unavailable')}</strong><time>${esc(acquired)}</time></span>`;}

function findingQueue(state,rows,id){
  return `<aside class="prevent-queue panel"><header><span class="eyebrow">Prevention findings</span><h2>${rows.length} governed findings</h2></header><div class="screening-list" data-scroll-key="prevent-queue">${rows.length?rows.map(item=>{const zid=(state.runtime?.preventionConsensus?.zones??[]).find(z=>String(z.finding_id??z.findingId)===String(item.findingId??item.id));const [s,t]=statusFor(item,zid);return `<button class="screening-row ${String(id)===String(item.findingId??item.id)?'is-active':''}" data-action="select-finding:${esc(item.findingId??item.id)}"><span class="screening-state screening-state--${t}">${icon(t==='green'?'check':t==='warning'?'warning':'evidence',14)}</span><span class="screening-row__copy"><strong>${esc(item.place??item.municipality??'Selected territory')}</strong><small>${esc(fmt(item.affectedAreaHa,' ha'))} · ${esc(fmt(item.corridorLengthM,' m'))}</small><em class="screening-row__status screening-row__status--${t}">${esc(s)}</em></span></button>`;}).join(''):`<div class="empty-state"><strong>No persisted prevention finding</strong><p>VIGIA returned no Portugal finding. No synthetic scene pair is substituted.</p></div>`}</div></aside>`;
}

function comparisonStage(state,finding,current,comparison,currentSrc,comparisonSrc){
  if(!finding)return `<div class="prevent-stage"><div class="map-loading-state"><div><strong>No prevention finding selected</strong></div></div></div>`;
  if(currentSrc.src&&comparisonSrc.src)return `<div class="prevent-stage">
    <div class="compare-toolbar" aria-label="Image comparison controls"><button data-action="prevent-compare-set:5">Before</button><button data-action="prevent-compare-set:50">Split</button><button data-action="prevent-compare-set:95">After</button><span>Drag image or slider</span></div>
    <div class="compare-map compare-map--real" style="--compare:${state.preventCompare}%" data-compare-stage data-preview-stage data-preview-state="LOADING">
      <img class="real-scene real-scene--before" data-preview-source="${esc(comparisonSrc.src)}" hidden alt="Comparable Copernicus scene" decoding="async">
      <img class="real-scene real-scene--after" data-compare-after data-preview-source="${esc(currentSrc.src)}" hidden alt="Current Copernicus scene" decoding="async" style="clip-path:inset(0 ${100-state.preventCompare}% 0 0)">
      <div class="preview-unavailable" data-preview-fallback><strong>Loading governed imagery</strong><span>Observation identity and acquisition metadata remain visible.</span></div>
      <div class="compare-map__divider" data-compare-divider style="left:${state.preventCompare}%" aria-hidden="true"><span></span></div>
      <input type="range" min="5" max="95" value="${state.preventCompare}" data-prevent-compare aria-label="Compare before and after imagery">
      <span class="compare-label compare-label--before">${comparison?.acquiredAt?new Date(comparison.acquiredAt).toLocaleDateString():'Before'}</span>
      <span class="compare-label compare-label--after">${current?.acquiredAt?new Date(current.acquiredAt).toLocaleDateString():'After'}</span>
      <output class="compare-position" data-compare-output>${state.preventCompare}%</output>
      <div class="compare-observation-identities">${observationIdentity('Before',comparison)}${observationIdentity('Current',current)}</div>
      <div class="real-scene-proof">COPERNICUS · ${esc(current?.sensor??'SENTINEL-2')} · REAL SOURCE PAIR</div>
    </div>
  </div>`;
  return `<div class="prevent-stage"><div class="compare-map">${tileMap({coordinate:finding.coordinate,zoom:10,thermal:false,label:'Real geographic context for prevention finding',enabled:state.runtime?.session?.authenticated===true})}<div class="map-loading-state map-loading-state--soft"><div><strong>Scene metadata present, preview unavailable</strong><span>VIGIA will not substitute generated imagery.</span></div></div></div></div>`;
}

function compareActionBar({finding,status,supportText,stability,nextMeasurement,need,request}){const measured=status==='Measurement required'?'<strong>SCREENING ESTIMATES WITHHELD</strong><small>Measurement or qualified review is required before decision-grade geometry.</small>':`<strong>${esc(fmt(finding?.affectedAreaHa,' ha'))} · ${esc(fmt(finding?.corridorLengthM,' m'))}</strong><small>${esc(fmt(finding?.nearestStructureM,' m'))} nearest mapped structure</small>`;return `<div class="prevent-action-bar"><article class="prevent-action-bar__state"><span>Screening state</span><strong>${esc(status)}</strong><small>Stability: ${esc(stability)} · consensus ${esc(supportText)}</small></article><article><span>Screening observation</span><strong>${esc(finding?.rationale?.whatChanged??'No persisted change rationale returned.')}</strong><small>${esc(finding?.rationale?.where??finding?.place??finding?.municipality??'Location unavailable')}</small></article><article><span>Decision-grade context</span>${measured}</article><article><span>Missing · next step</span><strong>${esc(nextMeasurement??need?.missingQuantity??(status==='Measurement required'?'Acquire measurement or qualified review':'Review governed evidence'))}</strong><small>${request?`Durable request ${esc(request.id)} · ${esc(request.state)}`:need?`${esc(need.state)} · request not recorded`:'MEASUREMENT REQUIRED · need unavailable'}</small><button class="inline-action" data-action="auto:open-evidence">Open evidence work</button></article></div>`;}

function decisionStage({state,finding,status,tone,supportText,current}){const map=finding?.coordinate?tileMap({coordinate:finding.coordinate,zoom:10,thermal:false,label:`Real geographic context for ${finding.place??finding.municipality??'prevention finding'}`,enabled:state.runtime?.session?.authenticated===true}):'',unmeasured=status==='Measurement required';return `<div class="prevent-decision-stage"><section class="prevent-decision-main"><div class="prevent-decision-hero prevent-decision-hero--${tone}"><span class="eyebrow">What VIGIA can defend</span><div><strong>${esc(status)}</strong>${badge(supportText,tone,true)}</div><p>${esc(finding?.rationale?.whatChanged??'No persisted change rationale returned.')}</p></div><div class="prevent-decision-cards"><article><span>Decision-grade geometry</span><strong>${unmeasured?'MEASUREMENT REQUIRED':`${esc(fmt(finding?.affectedAreaHa,' ha'))} affected`}</strong><p>${unmeasured?'Screening geometry is not promoted to an intervention claim.':`${esc(fmt(finding?.corridorLengthM,' m'))} persisted geometry span.`}</p></article><article><span>Exposure context</span><strong>${unmeasured?'NOT DECISION-GRADE':`${esc(fmt(finding?.nearestStructureM,' m'))} nearest structure`}</strong><p>${unmeasured?'Qualified measurement or expert review remains open.':`${esc(finding?.structuresWithinPolicyRadius??'—')} mapped structures in policy context.`}</p></article><article><span>Next</span><strong>${unmeasured?'Measurement / qualified review required':'Governed evidence review'}</strong><p>Screening support only; no treatment or intervention authority is created.</p></article><article><span>Source</span><strong>${esc(current?.sensor??'Scene metadata unavailable')}</strong><p>${current?.acquiredAt?`Current observation ${esc(new Date(current.acquiredAt).toLocaleString())}`:'No current scene preview returned.'}</p></article></div></section><div class="prevent-decision-map">${map||`<div class="map-loading-state"><div><strong>No geographic context returned</strong></div></div>`}</div></div>`;}

export function renderPrevent(state){
  const rows=preventionFindings(state),finding=selectedFinding(state),id=finding?.findingId??finding?.id,zone=(state.runtime?.preventionConsensus?.zones??[]).find(z=>String(z.finding_id??z.findingId)===String(id)),[status,tone]=statusFor(finding,zone),stability=stabilityFor(zone),pair=state.runtime?.observationPairs?.[id]??null,screen=state.runtime?.screeningDetails?.[id]??null,current=pair?.primary??screen?.observations?.current??null,comparison=pair?.comparable??screen?.observations?.comparison??null,currentSrc=preview(current),comparisonSrc=preview(comparison),supportText=formatMeasuredPercent(zone?.supportPercent??zone?.support??zone?.consensusSupport??zone?.support_fraction),activeTab=safeTab(state.preventTab),needs=openEvidenceNeeds(state),requests=state.runtime?.evidenceRequests?.requests??state.runtime?.command?.operations?.evidenceRequests??[],need=needs.find(item=>String(item.id)===String(finding?.evidenceNeedId)||String(item.subjectId)===String(id)),request=requests.find(item=>String(item.id)===String(finding?.evidenceRequestId??need?.evidenceRequestId)||String(item.evidenceNeedId)===String(need?.id));
  const tabs=`<div class="prevent-tabs" role="tablist" aria-label="Prevention finding view"><button class="${activeTab==='compare'?'is-active':''}" data-action="prevent-tab:compare">Compare imagery</button><button class="${activeTab==='decision'?'is-active':''}" data-action="prevent-tab:decision">Decision</button></div>`;
  const body=activeTab==='decision'?decisionStage({state,finding:{...finding,rationale:{...finding?.rationale,whatChanged:finding?.rationale?.whatChanged},measurementWorkflow:need?{state:need.state,missingQuantity:need.missingQuantity,requestId:request?.id??null}:null},status,tone,supportText,current}):`${comparisonStage(state,finding,current,comparison,currentSrc,comparisonSrc)}${compareActionBar({finding,status,supportText,stability,nextMeasurement:zone?.measurement_plan?.next_measurement,need,request})}`;
  const center=`<section class="prevent-workspace panel prevent-workspace--${activeTab}"><header class="workspace-header"><div><span class="eyebrow">Selected real finding</span><h2>${esc(finding?.place??finding?.municipality??'No finding')}</h2></div>${tabs}<div class="prevent-header-actions">${badge(status,tone)}${button('Refresh',{tone:'ghost',iconName:'sync',action:'refresh-runtime'})}</div></header>${preventIntelligence(state,id)}${body}</section>`;
  return shell('prevent',`<div class="prevent-grid">${findingQueue(state,rows,id)}${center}</div>`,{fullBleed:true});
}
