import { shell, badge, button, esc } from '../components.js?v=2.1.0';
import { icon } from '../icons.js?v=2.1.0';

export function renderResources(state) {
  const assets=state.runtime?.operationsAssets?.assets??[], query=(state.resourceSearch||'').trim().toLowerCase(), filter=state.resourceFilter||'all';
  const types=[...new Set(assets.map(a=>a.asset_type??a.assetType).filter(Boolean))];
  const shown=assets.filter(a=>(filter==='all'||String(a.asset_type??a.assetType)===filter)&&(!query||`${a.name} ${a.asset_type??a.assetType} ${a.source}`.toLowerCase().includes(query))).slice(0,48);
  const cards=shown.map(a=>`<article class="fleet-card governed-asset-card"><div class="fleet-card__image fleet-card__image--empty"><div class="fleet-photo-empty">${icon('map',30)}<strong>${esc(a.asset_type??a.assetType??'Monitored asset')}</strong><small>${esc(a.source??'Attributable monitored-territory registry')}</small></div>${badge('REFERENCE ASSET','teal',true)}</div><div class="fleet-card__body"><div class="fleet-card__title"><div><h3>${esc(a.name??a.id)}</h3><p>${esc(a.asset_type??a.assetType??'Context asset')}</p></div></div><span class="assignment">${icon('evidence',15)}${esc(a.source_id??a.sourceId??a.id)}</span><small class="truth-note">Not a fire-service apparatus. Not a connected device.</small></div></article>`).join('');
  const content=`<div class="resources-route"><header class="route-heading"><div><span class="eyebrow">Resources · integration truth</span><h2>Fleet / resource boundary</h2><p>VIGIA has no governed CAD/AVL or apparatus roster connected in this build. Fire engines, tankers, helicopters and water levels will not be fabricated.</p></div><div class="route-actions"><label class="search-box search-box--compact">${icon('search',16)}<input placeholder="Search monitored assets" aria-label="Search monitored assets" data-resource-search value="${esc(state.resourceSearch||'')}"></label></div></header><section class="integration-boundary integration-boundary--warning"><div>${icon('warning',24)}<span><strong>APPARATUS FEED NOT CONFIGURED</strong><small>The prior fixture fleet has been removed. Connect a governed resource integration before real fleet cards appear.</small></span></div>${badge('TRUTHFUL EMPTY STATE','warning')}</section><section class="fleet-summary"><article>${icon('resources',23)}<span>Governed apparatus<strong>0</strong></span></article><article>${icon('map',23)}<span>Monitored context assets<strong>${assets.length}</strong></span></article><article>${icon('people',23)}<span>Connected personnel<strong>0</strong></span></article><article>${icon('droplet',23)}<span>Water telemetry<strong>0</strong></span></article></section><div class="filter-tabs"><button class="${filter==='all'?'is-active':''}" data-action="filter-resource:all">All context assets</button>${types.slice(0,5).map(t=>`<button class="${filter===t?'is-active':''}" data-action="filter-resource:${esc(t)}">${esc(String(t).replaceAll('_',' '))}</button>`).join('')}</div><section class="fleet-grid">${cards||`<div class="empty-state fleet-empty">${icon('map',26)}<strong>No governed context asset matches</strong><p>The monitored-territory registry returned no matching row.</p></div>`}</section></div>`;
  return shell('resources',content);
}
