import { shell, button, badge, esc } from '../components.js?v=2.1.0';
import { sourceRows, sourceTone } from '../viewModel.js?v=2.1.0';

const select = (label, key, value, options) => `<label><span>${label}</span><select data-setting="${key}">${options.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></label>`;
const settingToggle = (label, key, checked) => `<label class="toggle"><span>${label}</span><input type="checkbox" data-setting="${key}" ${checked?'checked':''}><span class="toggle__track"></span></label>`;

function importPanel(state){
  const adapter=state.pilotImportAdapter??'CAD_JSON',draft=state.runtime?.pilotImport,preview=draft?.preview,mutationReady=state.runtime?.session?.mutationReady===true,canConfirm=mutationReady&&['VALID','PARTIALLY_VALID'].includes(preview?.status)&&Boolean(draft?.input),latest=state.pilotImportReceipts?.[0],counts=preview?.recordCounts??{};
  const rejectionRows=(preview?.rejections??[]).slice(0,8).map(item=>`<li><strong>${esc(item.code)}</strong><span>${esc(item.message)}</span>${item.row?`<small>Row ${esc(item.row)}</small>`:''}</li>`).join('');
  return `<section class="pilot-import" aria-label="Manual pilot import">
    <header><div><span class="eyebrow">Pilot integration · governed manual path</span><h3>FILE → VALIDATE → PREVIEW → CONFIRM → IMPORT</h3><p>Every accepted record remains <strong>MANUAL IMPORT</strong>. It is never labelled live, connected or synchronized.</p></div>${badge(String(preview?.status??'AWAITING FILE').replaceAll('_',' '),preview?.status==='VALID'?'green':preview?.status==='PARTIALLY_VALID'?'warning':preview?.status?'critical':'teal')}</header>
    <div class="pilot-import__controls"><label><span>Existing typed adapter</span><select data-pilot-import-adapter><option ${adapter==='CAD_JSON'?'selected':''}>CAD_JSON</option><option ${adapter==='CAD_CSV'?'selected':''}>CAD_CSV</option><option ${adapter==='ROSTER_JSON'?'selected':''}>ROSTER_JSON</option><option ${adapter==='ROSTER_CSV'?'selected':''}>ROSTER_CSV</option></select></label><label class="pilot-file"><span>Bounded file</span><input type="file" data-pilot-import-file accept="${adapter.endsWith('_JSON')?'.json,application/json':'.csv,text/csv'}" ${mutationReady?'':'disabled'}><small>${mutationReady?'JSON/CSV only · 700 KB maximum · no filesystem path is sent':'Secure mutation session unavailable until the canonical frontend proxy restarts'}</small></label></div>
    ${draft?`<div class="pilot-import__preview"><div class="pilot-import__identity"><span><small>File</small><strong>${esc(draft.file?.name??'Unavailable')}</strong></span><span><small>Size</small><strong>${Number.isFinite(draft.file?.size)?`${draft.file.size} bytes`:'Unavailable'}</strong></span><span><small>Source type</small><strong>MANUAL IMPORT</strong></span><span><small>Provenance hash</small><strong>${esc(preview?.sourcePayloadHash??'Unavailable until validation')}</strong></span></div><div class="pilot-import__counts"><article><strong>${preview?.acceptedRecords??'—'}</strong><span>Accepted</span></article><article><strong>${preview?.rejectedRecords??'—'}</strong><span>Rejected</span></article>${Object.entries(counts).filter(([,count])=>count).map(([name,count])=>`<article><strong>${esc(count)}</strong><span>${esc(name)}</span></article>`).join('')}</div>${rejectionRows?`<ul class="pilot-import__rejections">${rejectionRows}</ul>`:''}<div class="pilot-import__confirm"><p>${preview?.status==='PARTIALLY_VALID'?'Valid rows can be confirmed; rejected rows remain visible and are not discarded silently.':preview?.status==='VALID'?'The preview satisfies the governed adapter contract. Confirmation writes an attributable SHADOW import.':'Confirmation is unavailable until validation succeeds.'}</p>${button(draft.status==='importing'?'Importing…':'Confirm manual import',{tone:'primary',action:'confirm-pilot-import',disabled:!canConfirm||draft.status==='importing'})}</div></div>`:'<div class="empty-note">Choose the matching adapter and a bounded pilot file. No bundled fixture is used.</div>'}
    ${latest?`<footer><span>Latest confirmed import</span><strong>${esc(latest.incidentId)}</strong><small>${esc(latest.validation?.sourcePayloadHash??'Hash unavailable')} · ${esc(latest.confirmedAt)}</small>${badge('MANUAL IMPORT','warning',true)}</footer>`:''}
  </section>`;
}

function pilotSessionPanel(state){const session=state.pilotSession,active=Boolean(session&&!session.endedAt),records=session?.records??[];return `<section class="pilot-session"><header><div><span class="eyebrow">Pilot session instrumentation</span><h3>${active?'Recording actual operator interactions':session?'Session complete':'No session started'}</h3><p>No personal data, inferred success or fabricated rating is recorded.</p></div>${badge(active?'RECORDING':session?'ENDED':'NOT STARTED',active?'green':session?'teal':'warning')}</header>${session?`<div class="pilot-session__facts"><span><small>Session</small><strong>${esc(session.id)}</strong></span><span><small>Started</small><strong>${esc(session.startedAt)}</strong></span><span><small>Ended</small><strong>${esc(session.endedAt??'Active')}</strong></span><span><small>Actual records</small><strong>${records.length}</strong></span></div>`:''}${active?`<div class="pilot-observation"><header><strong>Explicit facilitator observation</strong><small>Optional human-entered fields only; blank ratings are not recorded.</small></header><div class="pilot-observation__grid"><label><span>Task</span><input data-pilot-observation="task" maxlength="120" placeholder="Observed task label"></label><label><span>Completed?</span><select data-pilot-observation="completed"><option value="">Not recorded</option><option value="true">Yes</option><option value="false">No</option></select></label><label><span>Incorrect interpretations</span><input data-pilot-observation="incorrectInterpretationCount" type="number" min="0" max="99" placeholder="Not recorded"></label><label><span>Trust rating · 1–5</span><input data-pilot-observation="trustRating" type="number" min="1" max="5" placeholder="Not recorded"></label><label><span>Clarity rating · 1–5</span><input data-pilot-observation="clarityRating" type="number" min="1" max="5" placeholder="Not recorded"></label><label><span>Workflow fit · 1–5</span><input data-pilot-observation="workflowFit" type="number" min="1" max="5" placeholder="Not recorded"></label><label class="is-wide"><span>Notes</span><textarea data-pilot-observation="notes" maxlength="240" rows="2" placeholder="Optional observed notes"></textarea></label></div>${button('Record facilitator observation',{tone:'primary',action:'pilot-facilitator-observation'})}</div>`:''}<div class="pilot-session__actions">${active?button('Mark current task complete',{tone:'secondary',action:'pilot-task-marker'}):button('Start pilot session',{tone:'primary',action:'start-pilot-session'})}${active?button('End session',{tone:'secondary',action:'end-pilot-session'}):''}${session?button('Export JSON',{tone:'ghost',action:'export-pilot-json'}):''}${session?button('Export CSV',{tone:'ghost',action:'export-pilot-csv'}):''}</div></section>`;}

export function renderSettings(state) {
  const s=state.settingsDraft||state.settingsSaved||{},sources=sourceRows(state);
  const integrationRows=sources.map(src=>`<article><strong>${esc(src.name)}</strong>${badge(src.state,sourceTone(src.state),true)}</article>`).join('');
  const saved=state.settingsSavedAt?new Date(state.settingsSavedAt).toLocaleString():'Not saved in this browser yet';
  return shell('settings',`<div class="settings-route"><header class="route-heading"><div><span class="eyebrow">Configuration</span><h2>Minimal operator settings</h2><p>Only presentation preferences used by this console are exposed. Changes remain staged until saved.</p><small class="settings-saved-at">Last saved: ${esc(saved)}</small></div>${button('Save changes',{tone:'primary',action:'save-settings'})}</header><section class="panel settings-panel"><div class="settings-content"><header><h2>Presentation</h2><p>Operational data and truth rules are not configurable here.</p></header><div class="settings-grid">${select('Density','density',s.density,['Operational compact','Comfortable'])}</div><div class="setting-toggles">${settingToggle('High contrast mode','highContrast',s.highContrast??false)}${settingToggle('Reduce motion','reduceMotion',s.reduceMotion??false)}</div></div></section><details class="panel specialist-settings"><summary>Specialist integration and import boundary</summary>${importPanel(state)}<div class="integration-list">${integrationRows||'<article><strong>Canonical source registry</strong><span>Unavailable</span></article>'}<article><strong>Live CAD / AVL / apparatus</strong>${badge('Not configured','warning',true)}</article><article><strong>Physical FieldNet mesh</strong>${badge('Not proven','critical',true)}</article></div></details><details class="panel specialist-settings"><summary>Supervised pilot instrumentation</summary>${pilotSessionPanel(state)}</details></div>`);
}
